classdef RunConfigPresenter < handle
    % RUNCONFIGPRESENTER Builds RunConfig values and control state.

    methods

        function request = createLaunchRequest(~, tableData, selection)

            batchIds = openmebius.presentation.batch ...
                .BatchTableSelectionMapper.selectedBatchIds( ...
                tableData, selection);
            request = openmebius.application.batch ...
                .BatchConfigurationLaunchRequest( ...
                batchIds, TableData = tableData);

        end % createLaunchRequest

        function viewModel = presentLaunchOutcome(obj, outcome)

            arguments
                obj (1, 1) openmebius.presentation.batch ...
                    .RunConfigPresenter
                outcome (1, 1) openmebius.application.batch ...
                    .BatchConfigurationLaunchOutcome
            end

            if outcome.isFailure()
                viewModel = obj.launchErrorViewModel( ...
                    outcome.ErrorMessage, outcome.Exception);
                return
            end

            try
                editor = obj.presentEditor(outcome.Session);
                viewModel = openmebius.presentation.batch ...
                    .RunConfigLaunchViewModel( ...
                    IsAvailable = true, ...
                    Session = outcome.Session, ...
                    Editor = editor, ...
                    Notifications = editor.Notifications);
            catch exception
                viewModel = obj.launchErrorViewModel( ...
                    string(exception.message), exception);
            end

        end % presentLaunchOutcome

        function viewModel = presentConfig(~, config)

            viewModel = openmebius.presentation.batch ...
                .RunConfigMapper.toViewModel(config);

        end % presentConfig

        function viewModel = presentDefaults(obj)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            viewModel = obj.presentConfig(config);

        end % presentDefaults

        function config = applyViewModel(~, viewModel, currentConfig)

            config = openmebius.presentation.batch.RunConfigMapper ...
                .fromViewModel(viewModel, currentConfig);

        end % applyViewModel

        function request = createApplyRequest( ...
                obj, session, configViewModel, msFragmentTable, ...
                msFragmentMetadata, suggestionData, applySuggestion)

            arguments
                obj (1, 1) openmebius.presentation.batch ...
                    .RunConfigPresenter
                session (1, 1) openmebius.application.batch ...
                    .BatchConfigurationSession
                configViewModel (1, 1) openmebius.presentation.batch ...
                    .RunConfigViewModel
                msFragmentTable table
                msFragmentMetadata
                suggestionData
                applySuggestion (1, 1) logical
            end

            config = obj.applyViewModel( ...
                configViewModel, session.primaryConfig());
            fragmentSelections = openmebius.presentation.batch ...
                .MSFragmentTableMapper.fromViewTable( ...
                msFragmentTable, msFragmentMetadata);

            if applySuggestion

                if ~istable(suggestionData)
                    error( ...
                        "OpenMebius2:RunConfigPresenter:" + ...
                        "InvalidSuggestionTable", ...
                    "Suggestion settings must be a table.");
                end

                suggestionTable = suggestionData;
            else
                suggestionTable = table();
            end

            request = openmebius.application.batch ...
                .BatchConfigurationApplyRequest( ...
                config, ...
                fragmentSelections, ...
                ApplySuggestion = applySuggestion, ...
                SuggestionTable = suggestionTable);

        end % createApplyRequest

        function viewModel = presentApplyOutcome(~, outcome)

            arguments
                ~
                outcome (1, 1) openmebius.application.batch ...
                    .BatchConfigurationApplyOutcome
            end

            if outcome.isSuccess()
                viewModel = openmebius.presentation.batch ...
                    .RunConfigApplyViewModel(IsSuccessful = true);
                return
            end

            if isempty(outcome.Exception)
                notification = openmebius.presentation.notification ...
                    .Notification.error( ...
                    outcome.ErrorMessage, ...
                    Title = "Batch configuration error", ...
                    ShowAlert = true);
            else
                notification = openmebius.presentation.notification ...
                    .Notification.fromException( ...
                    outcome.Exception, ...
                    Title = "Batch configuration error", ...
                    ShowAlert = true);
            end

            viewModel = openmebius.presentation.batch ...
                .RunConfigApplyViewModel( ...
                Notifications = {notification});

        end % presentApplyOutcome

        function editor = presentEditor(obj, session)

            config = obj.presentConfig(session.primaryConfig());
            msFragment = obj.presentMSFragmentTable(session);
            gridReaction = obj.presentGridReactionTable(session);
            efflux = openmebius.presentation.batch ...
                .RunConfigTableViewModel();
            suggestion = openmebius.presentation.batch ...
                .RunConfigTableViewModel();
            instMFA = openmebius.presentation.batch ...
                .RunConfigINSTMFATablesViewModel();

            if config.PerturbateEfflux
                efflux = obj.presentEffluxTable(session);
            end

            if config.SuggestNextFlux
                suggestion = obj.presentSuggestionTable(session);
            end

            if config.IsINSTMFA
                instMFA = obj.presentINSTMFATables(session);

                if ~instMFA.IsAvailable
                    config.IsINSTMFA = false;
                end

            end

            controlState = obj.presentControlState(config);
            editor = openmebius.presentation.batch ...
                .RunConfigEditorViewModel( ...
                Config = config, ...
                ControlState = controlState, ...
                MSFragmentTable = msFragment, ...
                GridReactionTable = gridReaction, ...
                EffluxTable = efflux, ...
                SuggestionTable = suggestion, ...
                INSTMFATables = instMFA, ...
                Notifications = instMFA.Notifications);

        end % presentEditor

        function viewModel = presentMSFragmentTable(~, session)

            mapped = openmebius.presentation.batch ...
                .MSFragmentTableMapper.toViewModel( ...
                session.msFragmentSelections());
            viewModel = openmebius.presentation.batch ...
                .RunConfigTableViewModel( ...
                Data = mapped.Data, ...
                ColumnName = mapped.ColumnName, ...
                RowName = mapped.RowName, ...
                ColumnEditable = mapped.ColumnEditable, ...
                Metadata = mapped.Metadata);

        end % presentMSFragmentTable

        function viewModel = presentGridReactionTable(~, session)

            tableData = session.gridReactionTable();
            viewModel = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                tableData, [true, false, false]);

        end % presentGridReactionTable

        function viewModel = presentEffluxTable(~, session)

            [tableData, editable] = session.effluxTable();
            viewModel = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                tableData, editable);

        end % presentEffluxTable

        function viewModel = presentSuggestionTable(~, session)

            tableData = session.suggestionTable();
            viewModel = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                tableData, false(1, 0));

        end % presentSuggestionTable

        function viewModel = presentINSTMFATables(~, session)

            if ~session.isSingleBatch()
                notification = openmebius.presentation.notification ...
                    .Notification.error( ...
                    "INST-MFA settings can only be configured " + ...
                    "when a single batch is selected.", ...
                    Title = "Batch configuration error", ...
                    ShowAlert = true);
                viewModel = openmebius.presentation.batch ...
                    .RunConfigINSTMFATablesViewModel( ...
                    Notifications = {notification});
                return
            end

            poolData = session.instPoolTable();
            [timePointData, timePointEditable] = ...
                session.instTimePointTable();
            poolTable = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                poolData, [false, true]);
            timePointTable = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                timePointData, timePointEditable);
            viewModel = openmebius.presentation.batch ...
                .RunConfigINSTMFATablesViewModel( ...
                IsAvailable = true, ...
                PoolTable = poolTable, ...
                TimePointTable = timePointTable);

        end % presentINSTMFATables

        function state = presentControlState(~, viewModel)

            arguments
                ~
                viewModel (1, 1) openmebius.presentation.batch ...
                    .RunConfigViewModel
            end

            isMonteCarlo = false;
            isGrid = false;

            if viewModel.CalculateCI

                switch lower(viewModel.CIAlgorithm)
                    case "monte carlo"
                        isMonteCarlo = true;
                    case "grid search"
                        isGrid = true;
                    otherwise
                        error( ...
                            "OpenMebius2:RunConfigPresenter:" + ...
                            "UnsupportedCIAlgorithm", ...
                            "Unsupported CI algorithm: %s.", ...
                            viewModel.CIAlgorithm);
                end

            end

            state = openmebius.presentation.batch ...
                .RunConfigControlState( ...
                CIAlgorithmEnabled = viewModel.CalculateCI, ...
                MonteCarloEnabled = isMonteCarlo, ...
                GridEnabled = isGrid, ...
                GridExecutionModeEnabled = isGrid, ...
                GridPointsEnabled = isGrid && ...
                viewModel.GridAutomaticInterval, ...
                GridDeltaEnabled = isGrid && ...
                ~viewModel.GridAutomaticInterval, ...
                GridReactionVisible = isGrid, ...
                EffluxEnabled = viewModel.PerturbateEfflux, ...
                SuggestionEnabled = viewModel.SuggestNextFlux, ...
                INSTMFATablesEnabled = viewModel.IsINSTMFA);

        end % presentControlState

    end % methods

    methods (Access = private)

        function viewModel = launchErrorViewModel( ...
                ~, errorMessage, exception)

            if isempty(exception)
                notification = openmebius.presentation.notification ...
                    .Notification.error( ...
                    errorMessage, ...
                    Title = "Batch configuration error", ...
                    ShowAlert = true);
            else
                notification = openmebius.presentation.notification ...
                    .Notification.fromException( ...
                    exception, ...
                    Title = "Batch configuration error", ...
                    ShowAlert = true);
            end

            viewModel = openmebius.presentation.batch ...
                .RunConfigLaunchViewModel( ...
                Notifications = {notification});

        end % launchErrorViewModel

    end % methods (Access = private)

    methods (Static, Access = private)

        function viewModel = tableViewModel(tableData, editable)

            arguments
                tableData table
                editable logical = false(1, 0)
            end

            columnNames = cellstr(string( ...
                tableData.Properties.VariableNames));
            rowNames = cellstr(string( ...
                tableData.Properties.RowNames));
            viewModel = openmebius.presentation.batch ...
                .RunConfigTableViewModel( ...
                Data = tableData, ...
                ColumnName = reshape(columnNames, 1, []), ...
                RowName = reshape(rowNames, 1, []), ...
                ColumnEditable = reshape(editable, 1, []));

        end % tableViewModel

    end % methods (Static, Access = private)

end % classdef
