classdef RunConfigPresenter < handle
    % RUNCONFIGPRESENTER Builds RunConfig values and control state.

    methods

        function viewModel = presentConfig(~, config)

            viewModel = openmebius.presentation.batch ...
                .RunConfigMapper.toViewModel(config);

        end % presentConfig

        function viewModel = presentDefaults(obj)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            viewModel = obj.presentConfig(config);

        end % presentDefaults

        function config = applyViewModel(~, viewModel, currentConfig)

            config = openmebius.presentation.batch.RunConfigMapper ...
                .fromViewModel(viewModel, currentConfig);

        end % applyViewModel

        function editor = presentEditor(obj, session)

            config = obj.presentConfig(session.primaryConfig());
            msFragment = obj.presentMSFragmentTable(session);
            efflux = openmebius.presentation.batch ...
                .RunConfigTableViewModel();
            suggestion = openmebius.presentation.batch ...
                .RunConfigTableViewModel();
            instMFA = openmebius.presentation.batch ...
                .RunConfigINSTMFATablesViewModel();

            if config.PerturbateEfflux
                efflux = obj.presentEffluxTable(session);
            end

            if config.SuggestNextFlux
                suggestion = obj.presentSuggestionTable(session);
            end

            if config.IsINSTMFA
                instMFA = obj.presentINSTMFATables(session);

                if ~instMFA.IsAvailable
                    config.IsINSTMFA = false;
                end
            end

            controlState = obj.presentControlState(config);
            editor = openmebius.presentation.batch ...
                .RunConfigEditorViewModel( ...
                    Config = config, ...
                    ControlState = controlState, ...
                    MSFragmentTable = msFragment, ...
                    EffluxTable = efflux, ...
                    SuggestionTable = suggestion, ...
                    INSTMFATables = instMFA, ...
                    Notifications = instMFA.Notifications);

        end % presentEditor

        function viewModel = presentMSFragmentTable(~, session)

            mapped = openmebius.presentation.batch ...
                .MSFragmentTableMapper.toViewModel( ...
                    session.msFragmentSelections());
            viewModel = openmebius.presentation.batch ...
                .RunConfigTableViewModel( ...
                    Data = mapped.Data, ...
                    ColumnName = mapped.ColumnName, ...
                    RowName = mapped.RowName, ...
                    ColumnEditable = mapped.ColumnEditable, ...
                    Metadata = mapped.Metadata);

        end % presentMSFragmentTable

        function viewModel = presentEffluxTable(~, session)

            [tableData, editable] = session.effluxTable();
            viewModel = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                    tableData, editable);

        end % presentEffluxTable

        function viewModel = presentSuggestionTable(~, session)

            tableData = session.suggestionTable();
            viewModel = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                    tableData, false(1, 0));

        end % presentSuggestionTable

        function viewModel = presentINSTMFATables(~, session)

            if ~session.isSingleBatch()
                notification = openmebius.presentation.notification ...
                    .Notification.error( ...
                        "INST-MFA settings can only be configured " + ...
                        "when a single batch is selected.", ...
                        Title = "Batch configuration error", ...
                        ShowAlert = true);
                viewModel = openmebius.presentation.batch ...
                    .RunConfigINSTMFATablesViewModel( ...
                        Notifications = {notification});
                return
            end

            poolData = session.instPoolTable();
            [timePointData, timePointEditable] = ...
                session.instTimePointTable();
            poolTable = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                    poolData, [false, true]);
            timePointTable = openmebius.presentation.batch ...
                .RunConfigPresenter.tableViewModel( ...
                    timePointData, timePointEditable);
            viewModel = openmebius.presentation.batch ...
                .RunConfigINSTMFATablesViewModel( ...
                    IsAvailable = true, ...
                    PoolTable = poolTable, ...
                    TimePointTable = timePointTable);

        end % presentINSTMFATables

        function state = presentControlState(~, viewModel)

            arguments
                ~
                viewModel (1, 1) openmebius.presentation.batch ...
                    .RunConfigViewModel
            end

            isMonteCarlo = false;
            isGrid = false;

            if viewModel.CalculateCI
                switch lower(viewModel.CIAlgorithm)
                    case "monte carlo"
                        isMonteCarlo = true;
                    case "grid search"
                        isGrid = true;
                    otherwise
                        error( ...
                            "OpenMebius2:RunConfigPresenter:" + ...
                            "UnsupportedCIAlgorithm", ...
                            "Unsupported CI algorithm: %s.", ...
                            viewModel.CIAlgorithm);
                end
            end

            state = openmebius.presentation.batch ...
                .RunConfigControlState( ...
                    CIAlgorithmEnabled = viewModel.CalculateCI, ...
                    MonteCarloEnabled = isMonteCarlo, ...
                    GridEnabled = isGrid, ...
                    GridPointsEnabled = isGrid && ...
                        viewModel.GridAutomaticInterval, ...
                    GridDeltaEnabled = isGrid && ...
                        ~viewModel.GridAutomaticInterval, ...
                    EffluxEnabled = viewModel.PerturbateEfflux, ...
                    SuggestionEnabled = viewModel.SuggestNextFlux, ...
                    INSTMFATablesEnabled = viewModel.IsINSTMFA);

        end % presentControlState

    end % methods

    methods (Static, Access = private)

        function viewModel = tableViewModel(tableData, editable)

            arguments
                tableData table
                editable logical = false(1, 0)
            end

            columnNames = cellstr(string( ...
                tableData.Properties.VariableNames));
            rowNames = cellstr(string( ...
                tableData.Properties.RowNames));
            viewModel = openmebius.presentation.batch ...
                .RunConfigTableViewModel( ...
                    Data = tableData, ...
                    ColumnName = reshape(columnNames, 1, []), ...
                    RowName = reshape(rowNames, 1, []), ...
                    ColumnEditable = reshape(editable, 1, []));

        end % tableViewModel

    end % methods (Static, Access = private)

end % classdef
