classdef AnalysisProvenanceBuilderTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(AnalysisProvenanceBuilderTest.sourcePath());

        end

    end

    methods (Test)

        function buildsManifestInputsFromModelAndExperiments(testCase)

            fixture = AnalysisProvenanceBuilderTest.createFixture();
            cleanup = onCleanup(@() ...
                AnalysisProvenanceBuilderTest.removeDirectory( ...
                fixture.Directory));
            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            model = struct('pathModel', fixture.ModelPath);
            experiments = helpers.AnalysisProvenanceExperimentStub( ...
                fixture.Directory, ...
                ["experiment-a.xlsx", "experiment-b.xlsx"]);
            builder = openmebius.application.analysis ...
                .AnalysisProvenanceBuilder();

            provenance = builder.build( ...
                config, ...
                "bat_test", ...
                model, ...
                experiments, ...
                ["experiment-b"; "experiment-a"]);

            modelHash = string( ...
                openmebius.infrastructure.filesystem.FileHasher ...
                .hashFile(fixture.ModelPath));
            experimentHashes = [ ...
                string(openmebius.infrastructure.filesystem.FileHasher ...
                .hashFile(fixture.ExperimentBPath)); ...
                string(openmebius.infrastructure.filesystem.FileHasher ...
                .hashFile(fixture.ExperimentAPath))];
            expectedContentHash = openmebius.domain.batch.BatchIdentity ...
                .contentHash( ...
                config, ...
                modelHash, ...
                ["experiment-b"; "experiment-a"], ...
                experimentHashes);

            testCase.verifyEqual(provenance.schemaVersion, 1);
            testCase.verifyEqual(provenance.batchId, "bat_test");
            testCase.verifyEqual(provenance.modelFileName, "model.xlsx");
            testCase.verifyEqual(provenance.modelSha256, modelHash);
            testCase.verifyEqual( ...
                provenance.experimentFileNames, ...
                ["experiment-b.xlsx"; "experiment-a.xlsx"]);
            testCase.verifyEqual( ...
                provenance.experimentSha256, experimentHashes);
            testCase.verifyEqual( ...
                provenance.contentHash, expectedContentHash);
            testCase.verifyEqual( ...
                provenance.configJson, ...
                openmebius.domain.batch.BatchIdentity.canonicalJson( ...
                openmebius.domain.batch.BatchIdentity.semanticConfig( ...
                config)));

        end

        function preservesMissingLegacyExperimentAsEmptyFingerprint(testCase)

            fixture = AnalysisProvenanceBuilderTest.createFixture();
            cleanup = onCleanup(@() ...
                AnalysisProvenanceBuilderTest.removeDirectory( ...
                fixture.Directory));
            experiments = helpers.AnalysisProvenanceExperimentStub( ...
                fixture.Directory, "experiment-a.xlsx");
            builder = openmebius.application.analysis ...
                .AnalysisProvenanceBuilder();

            provenance = builder.build( ...
                openmebius.domain.batch.BatchConfig.defaultConfig(), ...
                "bat_legacy", ...
                struct('pathModel', fixture.ModelPath), ...
                experiments, ...
                ["experiment-a"; "missing"]);

            testCase.verifyEqual( ...
                provenance.experimentFileNames, ...
                ["experiment-a.xlsx"; ""]);
            testCase.verifyEqual(provenance.experimentSha256(2), "");

        end

        function rejectsModelWithoutSourcePath(testCase)

            fixture = AnalysisProvenanceBuilderTest.createFixture();
            cleanup = onCleanup(@() ...
                AnalysisProvenanceBuilderTest.removeDirectory( ...
                fixture.Directory));
            experiments = helpers.AnalysisProvenanceExperimentStub( ...
                fixture.Directory, "experiment-a.xlsx");
            builder = openmebius.application.analysis ...
                .AnalysisProvenanceBuilder();

            testCase.verifyError( ...
                @() builder.build( ...
                openmebius.domain.batch.BatchConfig.defaultConfig(), ...
                "bat_invalid", ...
                struct, ...
                experiments, ...
                "experiment-a"), ...
                "OpenMebius2:AnalysisProvenanceBuilder:MissingModelPath");

        end

    end

    methods (Static, Access = private)

        function fixture = createFixture()

            directory = string(tempname);
            mkdir(directory);
            fixture = struct( ...
                'Directory', directory, ...
                'ModelPath', fullfile(directory, "model.xlsx"), ...
                'ExperimentAPath', ...
                fullfile(directory, "experiment-a.xlsx"), ...
                'ExperimentBPath', ...
                fullfile(directory, "experiment-b.xlsx"));
            AnalysisProvenanceBuilderTest.writeFile( ...
                fixture.ModelPath, "model");
            AnalysisProvenanceBuilderTest.writeFile( ...
                fixture.ExperimentAPath, "experiment-a");
            AnalysisProvenanceBuilderTest.writeFile( ...
                fixture.ExperimentBPath, "experiment-b");

        end

        function writeFile(path, text)

            fid = fopen(path, 'w');
            assert(fid >= 0, "Unable to create test fixture: " + path);
            cleanup = onCleanup(@() fclose(fid));
            fprintf(fid, '%s', text);
            clear cleanup

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, 's');
            end

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
