classdef AnalysisRunLifecycleTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(AnalysisRunLifecycleTest.sourcePath());

        end

    end

    methods (Test)

        function createsAndPersistsStartMetadata(testCase)

            repository = helpers.AnalysisRunRepositoryStub();
            lifecycle = openmebius.application.analysis ...
                .AnalysisRunLifecycle(Repository = repository);

            [metadata, isSuccess, message] = lifecycle.start( ...
                openmebius.domain.batch.BatchConfig.defaultConfig(), ...
                "batch-1", ...
                struct, ...
                "fallback", ...
                AnalysisRunLifecycleTest.provenance(), ...
                "2026-07-15T00:00:00.000Z", ...
                AnalysisRunLifecycleTest.randomState(), ...
                AnalysisRunLifecycleTest.resultLocation(), ...
                "result.h5");

            testCase.verifyTrue(isSuccess);
            testCase.verifyEqual(message, "");
            testCase.verifyEqual(metadata.batchId, "batch-1");
            testCase.verifyEqual(repository.StartCallCount, 1);
            testCase.verifyEqual( ...
                repository.StartedMetadata.contentHash, ...
                "content-hash");

        end

        function forwardsCompletionState(testCase)

            repository = helpers.AnalysisRunRepositoryStub();
            lifecycle = openmebius.application.analysis ...
                .AnalysisRunLifecycle(Repository = repository);
            metadata = struct(batchId = "batch-1");

            errors = lifecycle.finish( ...
                AnalysisRunLifecycleTest.resultLocation(), ...
                "result.h5", ...
                metadata, ...
                true, ...
                false, ...
                FinishedAtUtc = "2026-07-15T00:01:00.000Z");

            testCase.verifyEmpty(errors);
            testCase.verifyEqual(repository.CompletionCallCount, 1);
            testCase.verifyEqual(repository.CompletedMetadata, metadata);
            testCase.verifyEqual( ...
                repository.CompletedAtUtc, ...
                "2026-07-15T00:01:00.000Z");
            testCase.verifyTrue(repository.CompletedIsError);
            testCase.verifyFalse(repository.CompletedIsCanceled);

        end

    end

    methods (Static, Access = private)

        function value = provenance()

            value = struct( ...
                batchId = "batch-1", ...
                contentHash = "content-hash", ...
                configJson = "{}", ...
                modelFileName = "model.xlsx", ...
                modelSha256 = "model-hash", ...
                experimentNames = "E1", ...
                experimentFileNames = "E1.xlsx", ...
                experimentSha256 = "experiment-hash");

        end

        function value = randomState()

            value = struct( ...
                Type = 'twister', ...
                Seed = uint32(0), ...
                State = uint32(1));

        end

        function value = resultLocation()

            value = openmebius.domain.result.ResultLocation ...
                .fromDirectory(tempdir);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
