classdef AnalysisMetadataFactoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(AnalysisMetadataFactoryTest.sourcePath());

        end

    end

    methods (Test)

        function createsMetadataFromProvenance(testCase)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            provenance = struct( ...
                'schemaVersion', 2, ...
                'batchId', "bat_provenance", ...
                'batchName', "My batch", ...
                'batchDescription', "My description", ...
                'contentHash', "sha256:content", ...
                'contentHashVersion', 3, ...
                'configJson', '{"iteration":30}', ...
                'modelFileName', "model.xlsx", ...
                'modelSha256', "model-hash", ...
                'experimentNames', ["exp-a"; "exp-b"], ...
                'experimentFileNames', ["a.xlsx"; "b.xlsx"], ...
                'experimentSha256', ["hash-a"; "hash-b"]);
            randomState = struct( ...
                'Type', 'twister', ...
                'Seed', uint32(42), ...
                'State', uint32([1; 2; 3]));

            metadata = ...
                openmebius.application.analysis.AnalysisMetadataFactory.create( ...
                config, ...
                "bat_fallback", ...
                struct, ...
                "fallback-experiment", ...
                provenance, ...
                "2026-07-14T00:00:00.000Z", ...
                randomState);

            testCase.verifyEqual(metadata.schemaVersion, 2);
            testCase.verifyEqual(metadata.batchId, "bat_provenance");
            testCase.verifyEqual(metadata.batchName, "My batch");
            testCase.verifyEqual( ...
                metadata.batchDescription, "My description");
            testCase.verifyEqual(metadata.contentHash, "sha256:content");
            testCase.verifyEqual(metadata.contentHashVersion, 3);
            testCase.verifyEqual(metadata.configJson, "{""iteration"":30}");
            testCase.verifyEqual(metadata.modelFileName, "model.xlsx");
            testCase.verifyEqual(metadata.modelSha256, "model-hash");
            testCase.verifyEqual( ...
                metadata.experimentNames, ...
                ["exp-a"; "exp-b"]);
            testCase.verifyEqual( ...
                metadata.experimentFileNames, ...
                ["a.xlsx"; "b.xlsx"]);
            testCase.verifyEqual( ...
                metadata.experimentSha256, ...
                ["hash-a"; "hash-b"]);
            testCase.verifyEqual( ...
                metadata.openMebius2Version, ...
                System.getCurrentVersion());
            testCase.verifyEqual(metadata.randomType, "twister");
            testCase.verifyEqual(metadata.randomSeed, uint32(42));
            testCase.verifyEqual(metadata.randomState, uint32([1; 2; 3]));
            testCase.verifyEqual( ...
                metadata.startedAtUtc, ...
                "2026-07-14T00:00:00.000Z");

        end

        function derivesContentHashFromSemanticInputs(testCase)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            provenance = struct( ...
                'modelSha256', "model-hash", ...
                'experimentNames', "exp-a", ...
                'experimentSha256', "experiment-hash");
            randomState = struct( ...
                'Type', 'twister', ...
                'Seed', uint32(0), ...
                'State', uint32(1));
            expectedHash = ...
                openmebius.domain.batch.BatchIdentity.contentHash( ...
                config, ...
                "model-hash", ...
                "exp-a", ...
                "experiment-hash");

            metadata = ...
                openmebius.application.analysis.AnalysisMetadataFactory.create( ...
                config, ...
                "bat_001", ...
                struct, ...
                "fallback-experiment", ...
                provenance, ...
                "2026-07-14T00:00:00.000Z", ...
                randomState);

            testCase.verifyEqual(metadata.batchId, "bat_001");
            testCase.verifyEqual(metadata.contentHash, expectedHash);
            testCase.verifyEqual( ...
                metadata.contentHashVersion, ...
                openmebius.domain.batch.BatchIdentity.ContentHashVersion);

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
