classdef AnalysisWorkflowRefactorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(AnalysisWorkflowRefactorTest.sourcePath());

        end

    end

    methods (Test)

        function fluxAnalysisConstructsWithComposedDependencies(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            input = helpers.FluxAnalysisInputStub();
            analysis = FluxAnalysis( ...
                input, ...
                input, ...
                1, ...
                struct, ...
                resultDirectory, ...
                "unit-test");

            testCase.verifyClass(analysis, 'FluxAnalysis');
            testCase.verifyFalse(analysis.isError);
            testCase.verifyClass( ...
                analysis.Dependencies.MFAInputPreparationWorkflow, ...
                'openmebius.application.analysis.MFAInputPreparationWorkflow');

        end

        function runContextOwnsTransientAnalysisState(testCase)

            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = [0.2; 0.8], ...
                FragmentLabels = ["M0"; "M1"], ...
                FragmentMask = [true; true]);
            initial = openmebius.mfa.InitialFluxWorkflowResult( ...
                Problem = 42, ...
                Fluxes = [1; 2], ...
                RightHandSides = [3; 4], ...
                ObjectiveValues = 5);
            fitted = openmebius.mfa.MFAWorkflowResult( ...
                ObjectiveValues = 6, ...
                Fluxes = [7; 8], ...
                MDVs = reshape([0.3; 0.7], 2, 1, 1), ...
                Order = 1, ...
                IterationResults = {openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 1, ...
                Flux = [7; 8], ...
                MDV = [0.3; 0.7], ...
                ObjectiveValue = 6, ...
                ExitFlag = 1)});

            context.setExperimentalData(data);
            context.setBounds([0; 1], [2; 3]);
            context.setRightHandSide([4; 5]);
            context.setSubstrateEMUs({1; 2});
            context.setInitialResult(initial);
            context.setWorkflowResult(fitted);

            testCase.verifyEqual(context.ExperimentalData, data);
            testCase.verifyEqual(context.OptimizationMDV, [0.2; 0.8]);
            testCase.verifyEqual(context.LowerBounds, [0; 1]);
            testCase.verifyEqual(context.UpperBounds, [2; 3]);
            testCase.verifyEqual(context.Problem, 42);
            testCase.verifyEqual(context.InitialObjectiveValues, 5);
            testCase.verifyEqual(context.ObjectiveValues, 6);
            testCase.verifyEqual(context.Fluxes, [7; 8]);

        end

        function initialFluxWorkflowScoresAndOrdersCandidates(testCase)

            model = helpers.InitialFluxModelStub();
            generatedFluxes = [5, 5; 0.2, 0.8];
            generator = helpers.InitialPointGeneratorStub( ...
                generatedFluxes, generatedFluxes);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator);
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = 0.8, ...
                FragmentLabels = "M0", ...
                FragmentMask = true);

            result = workflow.run( ...
                model, ...
                struct(iteration = 1), ...
                [5; 0], ...
                [0; 0], ...
                [10; 1], ...
                {1}, ...
                data, ...
                data.ExperimentalMDV, ...
                data.FragmentMask, ...
                helpers.MDVPredictorStub(), ...
                openmebius.mfa.EffluxPenalty(), ...
                IterationRate = 2);

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual( ...
                result.Fluxes, [5, 5; 0.8, 0.2]);
            testCase.verifyEqual(result.RightHandSides, result.Fluxes);
            testCase.verifyEqual( ...
                result.ObjectiveValues, [0, 3600], ...
                AbsTol = 1e-10);
            testCase.verifyClass( ...
                result.Problem, 'openmebius.mfa.MFAProblem');

        end

        function confidenceIntervalWorkflowComposesRunRightHandSide( ...
                testCase)

            solver = helpers.ConfidenceIntervalSolverStub();
            observer = ...
                helpers.ConfidenceIntervalIterationObserverStub();
            workflow = openmebius.mfa.ConfidenceIntervalWorkflow( ...
                MonteCarloSolver = solver);
            problem = AnalysisWorkflowRefactorTest.createProblem();
            config = struct( ...
                isCalcCI = true, ...
                CIConf = struct( ...
                algorithm = "Monte Carlo", ...
                MC = struct));

            result = workflow.run( ...
                config, ...
                [0.2; 0.8], ...
                [5; 0.8], ...
                [0, 1, 0, 0], ...
                problem, ...
                [7; 0.1], ...
                zeros(0, 2), ...
                @(mdv, rhs) observer.run(mdv, rhs));

            testCase.verifyEqual(solver.CallCount, 1);
            testCase.verifyEqual(observer.RightHandSide, [7; 0.8]);
            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(result.LowerBounds, zeros(2, 1));
            testCase.verifyEqual(result.UpperBounds, ones(2, 1));
            testCase.verifyEqual(result.Output.time, 2);

        end

        function confidenceIntervalWorkflowSkipsDisabledCalculation( ...
                testCase)

            workflow = openmebius.mfa.ConfidenceIntervalWorkflow();
            result = workflow.run( ...
                struct(isCalcCI = false), ...
                [], [], zeros(1, 4), [], [], zeros(0, 2), ...
                @(~, ~) []);

            testCase.verifyFalse(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEmpty(result.LowerBounds);

        end

        function nextLabelWorkflowEvaluatesOnlyCompletePatterns(testCase)

            observer = helpers.NextLabelWorkflowObserverStub();
            workflow = openmebius.mfa.NextLabelExperimentWorkflow( ...
                SubstrateEMUFactory = ...
                helpers.SubstrateEMUFactoryStub(), ...
                MDVPredictor = helpers.MDVPredictorStub());
            config = struct;
            config.suggestionTable = {'A'; []};
            config.suggestionTableVarNames = {'Tracer'};
            config.suggestionTableRowNames = {'valid', 'empty'};

            result = workflow.run( ...
                [], [], [1, 2], config, [5; 0.8], ...
                ConfidenceIntervalFunction = ...
                @(mdv, emus) observer.calculate(mdv, emus), ...
                PatternCompleted = ...
                @(pattern, lower, upper) ...
                observer.complete(pattern, lower, upper));

            testCase.verifyEqual(observer.CallCount, 1);
            testCase.verifyEqual(observer.CompletedCount, 1);
            testCase.verifyEqual(observer.LastMDV, 0.8);
            testCase.verifyEqual(observer.LastEMUCount, 3);
            testCase.verifyEqual(numel(result.Patterns), 1);
            testCase.verifyEqual(result.LowerBounds{1}, [0.8; 3]);
            testCase.verifyFalse(result.IsCanceled);

        end

    end

    methods (Static, Access = private)

        function problem = createProblem()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0], ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = 10 * ones(2, 1), ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
