classdef AnalysisRunRepositoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename('fullpath')));
            addpath(fullfile(root, 'src'));
            addpath(fullfile(root, 'tests'));

        end

    end

    methods (Test)

        function stopsWhenHdf5MetadataCannotBeWritten(testCase)

            hdf5Repository = helpers.RecordingHdf5ResultRepository();
            hdf5Repository.MetadataSuccess = false;
            hdf5Repository.MetadataMessage = "hdf5 failure";
            manifestRepository = ...
                helpers.RecordingResultManifestRepository();
            repository = AnalysisRunRepositoryTest.createRepository( ...
                hdf5Repository, ...
                manifestRepository);

            [isSuccess, msg] = repository.writeStarted( ...
                AnalysisRunRepositoryTest.resultLocation(), ...
                "result.h5", ...
                struct);

            testCase.verifyFalse(isSuccess);
            testCase.verifyEqual( ...
                msg, ...
                "Failed to write analysis metadata: hdf5 failure");
            testCase.verifyEqual(manifestRepository.StartedCallCount, 0);

        end

        function reportsManifestStartFailure(testCase)

            hdf5Repository = helpers.RecordingHdf5ResultRepository();
            manifestRepository = ...
                helpers.RecordingResultManifestRepository();
            manifestRepository.StartedSuccess = false;
            manifestRepository.StartedMessage = "manifest failure";
            repository = AnalysisRunRepositoryTest.createRepository( ...
                hdf5Repository, ...
                manifestRepository);

            [isSuccess, msg] = repository.writeStarted( ...
                AnalysisRunRepositoryTest.resultLocation(), ...
                "result.h5", ...
                struct);

            testCase.verifyFalse(isSuccess);
            testCase.verifyEqual( ...
                msg, ...
                "Failed to write result manifest: manifest failure");
            testCase.verifyEqual(hdf5Repository.MetadataCallCount, 1);
            testCase.verifyEqual(manifestRepository.StartedCallCount, 1);

        end

        function marksManifestAsErrorWhenHdf5CompletionFails(testCase)

            hdf5Repository = helpers.RecordingHdf5ResultRepository();
            hdf5Repository.CompletionSuccess = false;
            hdf5Repository.CompletionMessage = "completion failure";
            manifestRepository = ...
                helpers.RecordingResultManifestRepository();
            repository = AnalysisRunRepositoryTest.createRepository( ...
                hdf5Repository, ...
                manifestRepository);

            errors = repository.writeCompleted( ...
                AnalysisRunRepositoryTest.resultLocation(), ...
                "result.h5", ...
                struct, ...
                "2026-07-14T00:01:00.000Z", ...
                false, ...
                false);

            testCase.verifyEqual( ...
                errors, ...
                "Failed to finalize analysis metadata: completion failure");
            testCase.verifyTrue(manifestRepository.CompletedIsError);
            testCase.verifyEqual(hdf5Repository.CompletionCallCount, 1);

        end

        function compensatesHdf5WhenManifestCompletionFails(testCase)

            hdf5Repository = helpers.RecordingHdf5ResultRepository();
            manifestRepository = ...
                helpers.RecordingResultManifestRepository();
            manifestRepository.CompletedSuccess = false;
            manifestRepository.CompletedMessage = "manifest failure";
            repository = AnalysisRunRepositoryTest.createRepository( ...
                hdf5Repository, ...
                manifestRepository);

            errors = repository.writeCompleted( ...
                AnalysisRunRepositoryTest.resultLocation(), ...
                "result.h5", ...
                struct, ...
                "2026-07-14T00:01:00.000Z", ...
                false, ...
                false);

            testCase.verifyEqual( ...
                errors, ...
                "Failed to finalize result manifest: manifest failure");
            testCase.verifyEqual(hdf5Repository.CompletionCallCount, 2);
            testCase.verifyEqual( ...
                hdf5Repository.CompletionErrorStates, ...
                [false; true]);

        end

    end

    methods (Static, Access = private)

        function repository = createRepository( ...
                hdf5Repository, manifestRepository)

            repository = ...
                openmebius.infrastructure.result.AnalysisRunRepository( ...
                Hdf5ResultRepository = hdf5Repository, ...
                ResultManifestRepository = manifestRepository);

        end

        function location = resultLocation()

            location = openmebius.domain.result.ResultLocation ...
                .fromDirectory(tempdir);

        end

    end

end
