classdef AnalysisWorkflowRefactorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(AnalysisWorkflowRefactorTest.sourcePath());

        end

    end

    methods (Test)

        function fluxAnalysisConstructsWithComposedDependencies(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            input = helpers.FluxAnalysisInputStub();
            analysis = FluxAnalysis( ...
                input, ...
                input, ...
                1, ...
                struct, ...
                resultDirectory, ...
                "unit-test");

            testCase.verifyClass(analysis, 'FluxAnalysis');
            testCase.verifyFalse(analysis.isError);
            testCase.verifyClass( ...
                analysis.Dependencies.MFAInputPreparationWorkflow, ...
                'openmebius.application.analysis.MFAInputPreparationWorkflow');
            testCase.verifyClass( ...
                analysis.Dependencies.FluxDistributionWorkflow, ...
                'openmebius.application.analysis.MFAFluxDistributionWorkflow');
            testCase.verifyClass( ...
                analysis.Dependencies ...
                .ConfidenceIntervalApplicationWorkflow, ...
                'openmebius.application.analysis.MFAConfidenceIntervalWorkflow');
            testCase.verifyClass( ...
                analysis.Dependencies.NextFluxExperimentWorkflow, ...
                'openmebius.application.analysis.NextFluxExperimentWorkflow');
            testCase.verifyFalse(isprop(analysis, 'status'));
            testCase.verifyFalse( ...
                ismethod(analysis, 'calculateFluxVariability'));
            testCase.verifyFalse( ...
                ismethod(analysis, ...
                'calculateInitialFluxDistribution'));

        end

        function runContextOwnsTransientAnalysisState(testCase)

            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = [0.2; 0.8], ...
                FragmentLabels = ["M0"; "M1"], ...
                FragmentMask = [true; true]);
            initial = openmebius.mfa.InitialFluxWorkflowResult( ...
                Problem = 42, ...
                Fluxes = [1; 2], ...
                RightHandSides = [3; 4], ...
                ObjectiveValues = 5);
            fitted = openmebius.mfa.MFAWorkflowResult( ...
                ObjectiveValues = 6, ...
                Fluxes = [7; 8], ...
                MDVs = reshape([0.3; 0.7], 2, 1, 1), ...
                Order = 1, ...
                IterationResults = {openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 1, ...
                Flux = [7; 8], ...
                MDV = [0.3; 0.7], ...
                ObjectiveValue = 6, ...
                ExitFlag = 1)});

            context.setExperimentalData(data);
            context.setBounds([0; 1], [2; 3]);
            context.setRightHandSide([4; 5]);
            context.setSubstrateEMUs({1; 2});
            context.setInitialResult(initial);
            context.setWorkflowResult(fitted);

            testCase.verifyEqual(context.ExperimentalData, data);
            testCase.verifyEqual(context.OptimizationMDV, [0.2; 0.8]);
            testCase.verifyEqual(context.LowerBounds, [0; 1]);
            testCase.verifyEqual(context.UpperBounds, [2; 3]);
            testCase.verifyEqual(context.Problem, 42);
            testCase.verifyEqual(context.InitialObjectiveValues, 5);
            testCase.verifyEqual(context.ObjectiveValues, 6);
            testCase.verifyEqual(context.Fluxes, [7; 8]);

        end

        function fluxAnalysisUsesInjectedRuntimeFactory(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            input = helpers.FluxAnalysisInputStub();
            dependencies = struct;
            dependencies.RunContext = ...
                openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            dependencies.MFAResultCoordinator = ...
                openmebius.infrastructure.result ...
                .MFAResultCoordinator(IsExport = false);
            dependencies.MFAExperimentListNormalizer = ...
                openmebius.mfa.MFAExperimentListNormalizer();
            session = openmebius.application.analysis ...
                .MFAResultSession( ...
                Coordinator = dependencies.MFAResultCoordinator);
            location = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            runtime = openmebius.application.analysis ...
                .FluxAnalysisRuntime( ...
                ResultLocation = location, ...
                ResultID = "unit-test", ...
                ResultFilePath = location.resultFile("unit-test"), ...
                IsExport = false, ...
                IsError = false, ...
                DirectoryMessage = "runtime ready", ...
                DirectoryMessageLevel = "Info", ...
                Dependencies = dependencies, ...
                RunContext = dependencies.RunContext, ...
                ResultSession = session);
            factory = helpers.FluxAnalysisRuntimeFactoryStub(runtime);
            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition(RuntimeFactory = factory);

            analysis = FluxAnalysis( ...
                input, ...
                input, ...
                1, ...
                struct, ...
                resultDirectory, ...
                "ignored", ...
                [], ...
                Composition = composition);

            testCase.verifyEqual(factory.CallCount, 1);
            testCase.verifyClass( ...
                factory.LastConfiguration, ...
                'openmebius.application.analysis.FluxAnalysisComposition');
            testCase.verifyEqual( ...
                factory.LastConfiguration.RuntimeFactory, factory);
            testCase.verifyEqual( ...
                analysis.ResultLocation.Directory, resultDirectory);
            testCase.verifyEqual(analysis.HDF5FileName, "unit-test");
            testCase.verifyFalse(analysis.isError);

        end

        function fluxAnalysisDelegatesDistributionRunToWorkflow(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            input = helpers.FluxAnalysisInputStub();
            lifecycle = helpers.AnalysisRunLifecycleStub();
            workflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .MFAFluxDistributionResult(IsCanceled = true));
            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition( ...
                FluxDistributionWorkflow = workflow, ...
                AnalysisRunLifecycle = lifecycle);
            analysis = FluxAnalysis( ...
                input, ...
                input, ...
                1, ...
                struct, ...
                resultDirectory, ...
                "unit-test", ...
                [], ...
                Composition = composition);

            analysis.calculateFluxDistribution();

            testCase.verifyEqual(workflow.CallCount, 1);
            testCase.verifyTrue(analysis.isCanceled);
            testCase.verifyEqual(lifecycle.StartCallCount, 1);
            testCase.verifyEqual(lifecycle.FinishCallCount, 1);

        end

        function fluxAnalysisPublishesTypedResultEvent(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            coordinator = openmebius.infrastructure.result ...
                .MFAResultCoordinator(IsExport = false);
            session = openmebius.application.analysis ...
                .MFAResultSession(Coordinator = coordinator);
            session.writeGeneral( ...
                "run-1", [], strings(0, 1), false(0, 1));
            session.writeFluxVariability( ...
                [0; 1], [2; 3], zeros(0, 2));
            iteration = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = [5; 2], ...
                Flux = [5; 2], ...
                MDV = [0.3; 0.7], ...
                ObjectiveValue = 4, ...
                ExitFlag = 1);
            session.writeIteration(2, iteration, zeros(0, 2));
            session.writeSummary(4, 2, 3.84);
            workflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .MFAFluxDistributionResult(MinimumObjective = 4));
            dependencies = struct;
            dependencies.RunContext = ...
                openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            dependencies.MFAResultCoordinator = coordinator;
            dependencies.MFAExperimentListNormalizer = ...
                openmebius.mfa.MFAExperimentListNormalizer();
            dependencies.FluxDistributionWorkflow = workflow;
            dependencies.AnalysisRunLifecycle = [];
            location = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            runtime = openmebius.application.analysis ...
                .FluxAnalysisRuntime( ...
                ResultLocation = location, ...
                ResultID = "run-1", ...
                ResultFilePath = location.resultFile("run-1"), ...
                IsExport = false, ...
                IsError = false, ...
                DirectoryMessage = "runtime ready", ...
                DirectoryMessageLevel = "Info", ...
                Dependencies = dependencies, ...
                RunContext = dependencies.RunContext, ...
                ResultSession = session);
            factory = helpers.FluxAnalysisRuntimeFactoryStub(runtime);
            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition(RuntimeFactory = factory);
            input = helpers.FluxAnalysisInputStub();
            analysis = FluxAnalysis( ...
                input, input, 1, struct, resultDirectory, "run-1", [], ...
                Composition = composition);
            observer = helpers.AnalysisNotificationObserverStub();
            listener = addlistener( ...
                analysis, ...
                'FluxResult', ...
                @(~, eventData) observer.publish(eventData));
            listenerCleanup = onCleanup(@() delete(listener));

            analysis.calculateFluxDistribution();

            testCase.verifyEqual(workflow.CallCount, 1);
            testCase.verifyEqual(observer.EventCount, 1);
            testCase.verifyClass( ...
                observer.LastEvent, ...
                'openmebius.presentation.result.FluxResultEventData');
            testCase.verifyEqual(observer.LastEvent.ID, "run-1");
            testCase.verifyEqual(observer.LastEvent.Flux, [5; 2]);
            testCase.verifyEqual(observer.LastEvent.RSS, 4);
            testCase.verifyEqual(observer.LastEvent.data.RSSIdx, 2);

        end

        function confidenceIntervalFailureSetsFacadeError(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            input = helpers.FluxAnalysisInputStub();
            workflow = helpers.WorkflowResultStub( ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                Method = "Monte Carlo", ...
                IsError = true, ...
                ErrorMessage = "CI failed."));
            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition( ...
                ConfidenceIntervalApplicationWorkflow = workflow);
            analysis = FluxAnalysis( ...
                input, ...
                input, ...
                1, ...
                struct, ...
                resultDirectory, ...
                "unit-test", ...
                [], ...
                Composition = composition);

            analysis.calculateConfidenceInterval();

            testCase.verifyEqual(workflow.CallCount, 1);
            testCase.verifyTrue(analysis.isError);
            testCase.verifyFalse(analysis.isCanceled);

        end

        function fluxAnalysisPublishesGeneralMessageEvent(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            input = helpers.FluxAnalysisInputStub();
            workflow = helpers.MessageReportingWorkflowStub( ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                IsError = true), ...
                "warning", ...
                "CI warning");
            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition( ...
                ConfidenceIntervalApplicationWorkflow = workflow);
            analysis = FluxAnalysis( ...
                input, ...
                input, ...
                1, ...
                struct, ...
                resultDirectory, ...
                "unit-test", ...
                [], ...
                Composition = composition);
            observer = helpers.AnalysisNotificationObserverStub();
            listener = addlistener( ...
                analysis, ...
                'GeneralMsg', ...
                @(~, eventData) observer.publish(eventData));
            listenerCleanup = onCleanup(@() delete(listener));

            analysis.calculateConfidenceInterval();

            testCase.verifyEqual(workflow.CallCount, 1);
            testCase.verifyEqual(observer.EventCount, 1);
            testCase.verifyClass( ...
                observer.LastEvent, ...
                ['openmebius.presentation.notification.' ...
                'GeneralMessageEventData']);
            testCase.verifyEqual( ...
                observer.LastEvent.data.status, "warning");
            testCase.verifyEqual( ...
                observer.LastEvent.data.msg, "CI warning");

        end

        function nextExperimentCancellationSetsFacadeState(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup( ...
                @() rmdir(resultDirectory, 's'));
            input = helpers.FluxAnalysisInputStub();
            workflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .NextFluxExperimentResult(IsCanceled = true));
            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition( ...
                NextFluxExperimentWorkflow = workflow);
            analysis = FluxAnalysis( ...
                input, ...
                input, ...
                1, ...
                struct, ...
                resultDirectory, ...
                "unit-test", ...
                [], ...
                Composition = composition);

            analysis.suggestNextFluxExperiment();

            testCase.verifyEqual(workflow.CallCount, 1);
            testCase.verifyTrue(analysis.isCanceled);
            testCase.verifyFalse(analysis.isError);

        end

        function initialFluxWorkflowScoresAndOrdersCandidates(testCase)

            model = helpers.InitialFluxModelStub();
            generatedFluxes = [5, 5; 0.2, 0.8];
            generator = helpers.InitialPointGeneratorStub( ...
                generatedFluxes, generatedFluxes);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = 0.8, ...
                FragmentLabels = "M0", ...
                FragmentMask = true);

            input = openmebius.mfa.InitialFluxWorkflowInput( ...
                Model = model, ...
                IterationCount = 1, ...
                RightHandSide = [5; 0], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                SubstrateEMUs = {1}, ...
                ExperimentalData = data, ...
                OptimizationMDV = data.ExperimentalMDV, ...
                EffluxPenalty = openmebius.mfa.EffluxPenalty());

            result = workflow.run( ...
                input, ...
                IterationRate = 2);

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual( ...
                result.Fluxes, [5, 5; 0.8, 0.2]);
            testCase.verifyEqual(result.RightHandSides, result.Fluxes);
            testCase.verifyEqual( ...
                result.ObjectiveValues, [0, 3600], ...
                AbsTol = 1e-10);
            testCase.verifyClass( ...
                result.Problem, 'openmebius.mfa.MFAProblem');

        end

        function confidenceIntervalWorkflowComposesRunRightHandSide( ...
                testCase)

            solver = helpers.ConfidenceIntervalSolverStub();
            observer = ...
                helpers.ConfidenceIntervalIterationObserverStub();
            workflow = openmebius.mfa.ConfidenceIntervalWorkflow( ...
                MonteCarloSolver = solver);
            problem = AnalysisWorkflowRefactorTest.createProblem();
            config = struct( ...
                isCalcCI = true, ...
                CIConf = struct( ...
                algorithm = "Monte Carlo", ...
                MC = struct));

            result = workflow.run( ...
                config, ...
                [0.2; 0.8], ...
                [5; 0.8], ...
                [0, 1, 0, 0], ...
                problem, ...
                [7; 0.1], ...
                zeros(0, 2), ...
                @(mdv, rhs) observer.run(mdv, rhs));

            testCase.verifyEqual(solver.CallCount, 1);
            testCase.verifyEqual(observer.RightHandSide, [7; 0.8]);
            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(result.LowerBounds, zeros(2, 1));
            testCase.verifyEqual(result.UpperBounds, ones(2, 1));
            testCase.verifyEqual(result.Output.time, 2);

        end

        function confidenceIntervalWorkflowSkipsDisabledCalculation( ...
                testCase)

            workflow = openmebius.mfa.ConfidenceIntervalWorkflow();
            result = workflow.run( ...
                struct(isCalcCI = false), ...
                [], [], zeros(1, 4), [], [], zeros(0, 2), ...
                @(~, ~) []);

            testCase.verifyFalse(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEmpty(result.LowerBounds);

        end

        function nextLabelWorkflowEvaluatesOnlyCompletePatterns(testCase)

            observer = helpers.NextLabelWorkflowObserverStub();
            workflow = openmebius.mfa.NextLabelExperimentWorkflow( ...
                SubstrateEMUFactory = ...
                helpers.SubstrateEMUFactoryStub(), ...
                MDVPredictor = helpers.MDVPredictorStub());
            config = struct;
            config.suggestionTable = {'A'; []};
            config.suggestionTableVarNames = {'Tracer'};
            config.suggestionTableRowNames = {'valid', 'empty'};

            result = workflow.run( ...
                [], [], [1, 2], config, [5; 0.8], ...
                ConfidenceIntervalFunction = ...
                @(mdv, emus) observer.calculate(mdv, emus), ...
                PatternCompleted = ...
                @(pattern, lower, upper) ...
                observer.complete(pattern, lower, upper));

            testCase.verifyEqual(observer.CallCount, 1);
            testCase.verifyEqual(observer.CompletedCount, 1);
            testCase.verifyEqual(observer.LastMDV, 0.8);
            testCase.verifyEqual(observer.LastEMUCount, 3);
            testCase.verifyEqual(numel(result.Patterns), 1);
            testCase.verifyEqual(result.LowerBounds{1}, [0.8; 3]);
            testCase.verifyFalse(result.IsCanceled);

        end

    end

    methods (Static, Access = private)

        function problem = createProblem()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0], ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = 10 * ones(2, 1), ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
