classdef BatchPreparationServiceTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(BatchPreparationServiceTest.sourcePath());

        end

    end

    methods (Test)

        function refreshesHashesWithoutReopeningTerminalBatches(testCase)

            batchTable = BatchPreparationServiceTest.batchTable( ...
                ["finished", "finished", "error", "ready"], ...
                ["", "sha256:old", "sha256:old", "sha256:bat_4"]);
            builder = helpers.AnalysisProvenanceBuilderStub();
            service = openmebius.application.batch ...
                .BatchPreparationService(ProvenanceBuilder = builder);

            [updatedTable, changed, provenances] = service.prepare( ...
                batchTable, ...
                batchTable.id, ...
                struct, ...
                struct);

            testCase.verifyEqual(changed, [true; true; true; false]);
            testCase.verifyEqual( ...
                updatedTable.contentHash, ...
                ["sha256:bat_1"; "sha256:bat_2"; ...
                "sha256:bat_3"; "sha256:bat_4"]);
            testCase.verifyEqual( ...
                string(updatedTable.config(1).status), "finished");
            testCase.verifyEqual( ...
                string(updatedTable.config(2).status), "finished");
            testCase.verifyEqual( ...
                string(updatedTable.config(3).status), "error");
            testCase.verifyEqual( ...
                string(updatedTable.config(4).status), "ready");
            provenanceIds = cellfun( ...
                @(value) string(value.batchId), provenances);
            testCase.verifyEqual( ...
                provenanceIds, ["bat_1"; "bat_2"; "bat_3"; "bat_4"]);
            provenanceNames = cellfun( ...
                @(value) string(value.batchName), provenances);
            testCase.verifyEqual( ...
                provenanceNames, ["Batch 1"; "Batch 2"; ...
                "Batch 3"; "Batch 4"]);

        end

        function preparesOnlyRequestedEntries(testCase)

            batchTable = BatchPreparationServiceTest.batchTable( ...
                ["ready", "ready", "ready"], ...
                ["", "sha256:old", ""]);
            builder = helpers.AnalysisProvenanceBuilderStub();
            service = openmebius.application.batch ...
                .BatchPreparationService(ProvenanceBuilder = builder);

            [updatedTable, changed, provenances] = service.prepare( ...
                batchTable, ...
                "bat_2", ...
                struct, ...
                struct);

            testCase.verifyTrue(changed);
            testCase.verifyEqual(builder.BatchIds, "bat_2");
            testCase.verifyEmpty(provenances{1});
            testCase.verifyEqual(provenances{2}.batchId, "bat_2");
            testCase.verifyEmpty(provenances{3});
            testCase.verifyEqual(updatedTable.contentHash(1), "");
            testCase.verifyEqual( ...
                updatedTable.contentHash(2), "sha256:bat_2");

        end

        function rejectsUnknownBatchId(testCase)

            service = openmebius.application.batch ...
                .BatchPreparationService( ...
                ProvenanceBuilder = ...
                helpers.AnalysisProvenanceBuilderStub());

            testCase.verifyError( ...
                @() service.prepare( ...
                BatchPreparationServiceTest.batchTable("ready", ""), ...
                "missing", ...
                struct, ...
                struct), ...
                "OpenMebius2:BatchPreparationService:BatchNotFound");

        end

    end

    methods (Static, Access = private)

        function batchTable = batchTable(statuses, hashes)

            statuses = string(statuses(:));
            hashes = string(hashes(:));
            numberOfBatches = numel(statuses);
            configs = repmat( ...
                openmebius.domain.batch.BatchConfig.defaultConfig(), ...
                numberOfBatches, ...
                1);

            for i = 1:numberOfBatches
                configs(i).status = char(statuses(i));
                configs(i).deleteResultFile = false;
            end

            batchTable = table( ...
                "bat_" + string((1:numberOfBatches)'), ...
                "Batch " + string((1:numberOfBatches)'), ...
                repmat({"experiment-a"}, numberOfBatches, 1), ...
                strings(numberOfBatches, 1), ...
                configs, ...
                hashes, ...
                'VariableNames', ...
                openmebius.infrastructure.batch.BatchJsonMapper ...
                .defaultVariableNames());

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
