classdef BatchExecutionCoordinatorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(BatchExecutionCoordinatorTest.sourcePath());

        end

    end

    methods (Test)

        function coordinatesRunnableEntriesAndCheckpoints(testCase)

            batchTable = BatchExecutionCoordinatorTest.batchTable( ...
                ["finished", "warning", "ready", "ready"]);
            [coordinator, runService] = ...
                BatchExecutionCoordinatorTest.createCoordinator( ...
                ["error", "finished"]);
            recorder = helpers.BatchExecutionRecorder();

            [updatedTable, status] = coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable), ...
                ProgressReporter = ...
                @(progress) recorder.recordProgress(progress), ...
                CheckpointWriter = ...
                @(tableValue) recorder.writeCheckpoint(tableValue));

            testCase.verifyEqual(status, "error");
            testCase.verifyEqual(runService.BatchIds, ["bat_3"; "bat_4"]);
            provenanceIds = cellfun( ...
                @(value) string(value.batchId), runService.Provenances);
            testCase.verifyEqual(provenanceIds, ["bat_3"; "bat_4"]);
            progressStatuses = cellfun( ...
                @(value) string(value.status), recorder.Progress);
            progressRates = cellfun( ...
                @(value) value.rate, recorder.Progress);
            testCase.verifyEqual( ...
                progressStatuses, ...
                ["finished"; "question"; "error"; "finished"]);
            testCase.verifyEqual(progressRates, [0.25; 0.5; 0.75; 1]);
            testCase.verifyEqual( ...
                string(updatedTable.config(3).status), "error");
            testCase.verifyEqual( ...
                string(updatedTable.config(4).status), "finished");
            testCase.verifyEqual(numel(recorder.Checkpoints), 2);

        end

        function cancellationStopsRemainingEntries(testCase)

            batchTable = BatchExecutionCoordinatorTest.batchTable( ...
                ["ready", "ready"]);
            [coordinator, runService] = ...
                BatchExecutionCoordinatorTest.createCoordinator( ...
                ["canceled", "finished"]);
            recorder = helpers.BatchExecutionRecorder();

            [updatedTable, status] = coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable), ...
                ProgressReporter = ...
                @(progress) recorder.recordProgress(progress), ...
                CheckpointWriter = ...
                @(tableValue) recorder.writeCheckpoint(tableValue));

            testCase.verifyEqual(status, "canceled");
            testCase.verifyEqual(runService.CallCount, 1);
            testCase.verifyEmpty(recorder.Progress);
            testCase.verifyEmpty(recorder.Checkpoints);
            testCase.verifyEqual( ...
                string(updatedTable.config(1).status), "ready");

        end

        function deletesOnlyArtifactsForRunnableEntry(testCase)

            directory = string(tempname);
            mkdir(directory);
            cleanup = onCleanup(@() ...
                BatchExecutionCoordinatorTest.removeDirectory(directory));
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(directory);
            artifacts = resultLocation.resultArtifactFiles("bat_1");
            BatchExecutionCoordinatorTest.writeFile(artifacts(1));
            BatchExecutionCoordinatorTest.writeFile(artifacts(2));
            unrelatedFile = resultLocation.reportFile("summary.html");
            BatchExecutionCoordinatorTest.writeFile(unrelatedFile);
            batchTable = BatchExecutionCoordinatorTest.batchTable("ready");
            batchTable.config(1).deleteResultFile = true;
            coordinator = ...
                BatchExecutionCoordinatorTest.createCoordinator("finished");

            coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                resultLocation, ...
                BatchExecutionCoordinatorTest.provenances(batchTable));

            testCase.verifyFalse(isfile(artifacts(1)));
            testCase.verifyFalse(isfile(artifacts(2)));
            testCase.verifyTrue(isfile(unrelatedFile));

        end

        function forwardsAnalysisCallbacks(testCase)

            runService = helpers.BatchRunServiceQueueStub( ...
                "finished", EmitCallbacks = true);
            coordinator = openmebius.application.batch ...
                .BatchExecutionCoordinator(RunService = runService);
            recorder = helpers.BatchExecutionRecorder();
            batchTable = BatchExecutionCoordinatorTest.batchTable("ready");

            coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable), ...
                MessageReporter = ...
                @(eventData) recorder.recordMessage(eventData), ...
                ResultReporter = ...
                @(eventData) recorder.recordResult(eventData));

            testCase.verifyEqual(recorder.MessageCount, 1);
            testCase.verifyEqual(recorder.ResultCount, 1);

        end

        function emptyTableCompletesWithoutCallbacks(testCase)

            [coordinator, runService] = ...
                BatchExecutionCoordinatorTest.createCoordinator("finished");
            recorder = helpers.BatchExecutionRecorder();

            [updatedTable, status] = coordinator.run( ...
                openmebius.infrastructure.batch.BatchJsonMapper.emptyTable(), ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                cell(0, 1), ...
                ProgressReporter = ...
                @(progress) recorder.recordProgress(progress));

            testCase.verifyEqual(status, "finished");
            testCase.verifyEqual(height(updatedTable), 0);
            testCase.verifyEqual(runService.CallCount, 0);
            testCase.verifyEmpty(recorder.Progress);

        end

        function rejectsMissingRunnableProvenance(testCase)

            coordinator = ...
                BatchExecutionCoordinatorTest.createCoordinator("finished");
            batchTable = BatchExecutionCoordinatorTest.batchTable("ready");

            testCase.verifyError( ...
                @() coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                {[]}), ...
                "OpenMebius2:BatchExecutionCoordinator:" + ...
                "MissingProvenance");

        end

    end

    methods (Static, Access = private)

        function [coordinator, runService] = createCoordinator(statuses)

            runService = helpers.BatchRunServiceQueueStub(statuses);
            coordinator = openmebius.application.batch ...
                .BatchExecutionCoordinator(RunService = runService);

        end

        function values = provenances(batchTable)

            values = cell(height(batchTable), 1);

            for i = 1:height(batchTable)
                values{i} = struct( ...
                    'batchId', batchTable.id(i), ...
                    'contentHash', "sha256:" + batchTable.id(i));
            end

        end

        function batchTable = batchTable(statuses)

            statuses = string(statuses(:));
            numberOfBatches = numel(statuses);
            configs = repmat( ...
                openmebius.domain.batch.BatchConfig.defaultConfig(), ...
                numberOfBatches, ...
                1);

            for i = 1:numberOfBatches
                configs(i).status = char(statuses(i));
                configs(i).deleteResultFile = false;
            end

            batchTable = table( ...
                "bat_" + string((1:numberOfBatches)'), ...
                "Batch " + string((1:numberOfBatches)'), ...
                repmat({"experiment-a"}, numberOfBatches, 1), ...
                strings(numberOfBatches, 1), ...
                configs, ...
                strings(numberOfBatches, 1), ...
                'VariableNames', ...
                openmebius.infrastructure.batch.BatchJsonMapper ...
                .defaultVariableNames());

        end

        function location = resultLocation()

            location = openmebius.domain.result.ResultLocation ...
                .fromDirectory(string(tempdir));

        end

        function writeFile(path)

            fid = fopen(path, 'w');
            assert(fid >= 0, "Unable to create test file: " + path);
            cleanup = onCleanup(@() fclose(fid));
            fprintf(fid, 'test');
            clear cleanup

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, 's');
            end

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
