classdef BatchExecutionCoordinatorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(BatchExecutionCoordinatorTest.sourcePath());

        end

    end

    methods (Test)

        function coordinatesRunnableEntriesAndCheckpoints(testCase)

            batchTable = BatchExecutionCoordinatorTest.batchTable( ...
                ["finished", "error", "warning", "ready", "ready"]);
            [coordinator, runService] = ...
                BatchExecutionCoordinatorTest.createCoordinator( ...
                ["error", "finished"]);
            recorder = helpers.BatchExecutionRecorder();

            [updatedTable, result] = coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable), ...
                ProgressReporter = ...
                @(progress) recorder.recordProgress(progress), ...
                CheckpointWriter = ...
                @(tableValue) recorder.writeCheckpoint(tableValue));

            testCase.verifyTrue(result.isFailure());
            testCase.verifyEqual(runService.BatchIds, ["bat_4"; "bat_5"]);
            provenanceIds = cellfun( ...
                @(value) string(value.batchId), runService.Provenances);
            testCase.verifyEqual(provenanceIds, ["bat_4"; "bat_5"]);
            progressStatuses = cellfun( ...
                @(value) string(value.status), recorder.Progress);
            progressRates = cellfun( ...
                @(value) value.rate, recorder.Progress);
            testCase.verifyEqual( ...
                progressStatuses, ...
                ["question"; "error"; "finished"]);
            testCase.verifyEqual(progressRates, [0; 0.5; 1]);
            testCase.verifyEqual( ...
                string(updatedTable.config(1).status), "finished");
            testCase.verifyEqual( ...
                string(updatedTable.config(2).status), "error");
            testCase.verifyEqual( ...
                string(updatedTable.config(4).status), "error");
            testCase.verifyEqual( ...
                string(updatedTable.config(5).status), "finished");
            testCase.verifyEqual(numel(recorder.Checkpoints), 2);

        end

        function cancellationStopsRemainingEntries(testCase)

            batchTable = BatchExecutionCoordinatorTest.batchTable( ...
                ["ready", "ready"]);
            [coordinator, runService] = ...
                BatchExecutionCoordinatorTest.createCoordinator( ...
                ["canceled", "finished"]);
            recorder = helpers.BatchExecutionRecorder();

            [updatedTable, result] = coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable), ...
                ProgressReporter = ...
                @(progress) recorder.recordProgress(progress), ...
                CheckpointWriter = ...
                @(tableValue) recorder.writeCheckpoint(tableValue));

            testCase.verifyTrue(result.isCanceled());
            testCase.verifyEqual(runService.CallCount, 1);
            testCase.verifyEmpty(recorder.Progress);
            testCase.verifyEmpty(recorder.Checkpoints);
            testCase.verifyEqual( ...
                string(updatedTable.config(1).status), "ready");

        end

        function deletesArtifactsOnlyWhenRequested(testCase)

            batchTable = BatchExecutionCoordinatorTest.batchTable( ...
                ["ready", "ready"]);
            batchTable.config(1).deleteResultFile = true;
            [coordinator, ~, artifactRepository] = ...
                BatchExecutionCoordinatorTest.createCoordinator( ...
                ["finished", "finished"]);

            coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable));

            testCase.verifyEqual( ...
                artifactRepository.DeletedBatchIds, "bat_1");

        end

        function forwardsAnalysisCallbacks(testCase)

            runService = helpers.BatchRunServiceQueueStub( ...
                "finished", EmitCallbacks = true);
            coordinator = openmebius.application.batch ...
                .BatchExecutionCoordinator(RunService = runService);
            recorder = helpers.BatchExecutionRecorder();
            batchTable = BatchExecutionCoordinatorTest.batchTable("ready");

            coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable), ...
                MessageReporter = ...
                @(eventData) recorder.recordMessage(eventData), ...
                ResultReporter = ...
                @(eventData) recorder.recordResult(eventData));

            testCase.verifyEqual(recorder.MessageCount, 1);
            testCase.verifyEqual(recorder.ResultCount, 1);

        end

        function mapsAnalysisProgressIntoBatchProgress(testCase)

            runService = helpers.BatchRunServiceQueueStub( ...
                "finished", EmitCallbacks = true);
            coordinator = openmebius.application.batch ...
                .BatchExecutionCoordinator(RunService = runService);
            recorder = helpers.BatchExecutionRecorder();
            batchTable = BatchExecutionCoordinatorTest.batchTable("ready");
            batchTable.config.iteration = 4;

            coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                BatchExecutionCoordinatorTest.provenances(batchTable), ...
                ProgressReporter = ...
                @(progress) recorder.recordProgress(progress));

            testCase.verifyNumElements(recorder.Progress, 2);
            running = recorder.Progress{1};
            testCase.verifyEqual(string(running.status), "running");
            testCase.verifyEqual(running.rate, 0.25);
            testCase.verifyEqual( ...
                string(running.message), "Optimization: 1/4");
            testCase.verifyEqual( ...
                string(recorder.Progress{2}.status), "finished");

        end

        function emptyTableCompletesWithoutCallbacks(testCase)

            [coordinator, runService] = ...
                BatchExecutionCoordinatorTest.createCoordinator("finished");
            recorder = helpers.BatchExecutionRecorder();

            [updatedTable, result] = coordinator.run( ...
                openmebius.infrastructure.batch.BatchJsonMapper.emptyTable(), ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                cell(0, 1), ...
                ProgressReporter = ...
                @(progress) recorder.recordProgress(progress));

            testCase.verifyTrue(result.isSuccess());
            testCase.verifyEqual(height(updatedTable), 0);
            testCase.verifyEqual(runService.CallCount, 0);
            testCase.verifyEmpty(recorder.Progress);

        end

        function rejectsMissingRunnableProvenance(testCase)

            coordinator = ...
                BatchExecutionCoordinatorTest.createCoordinator("finished");
            batchTable = BatchExecutionCoordinatorTest.batchTable("ready");

            testCase.verifyError( ...
                @() coordinator.run( ...
                batchTable, ...
                struct, ...
                struct, ...
                BatchExecutionCoordinatorTest.resultLocation(), ...
                {[]}), ...
                "OpenMebius2:BatchExecutionCoordinator:" + ...
                "MissingProvenance");

        end

    end

    methods (Static, Access = private)

        function [coordinator, runService, artifactRepository] = ...
                createCoordinator(statuses)

            runService = helpers.BatchRunServiceQueueStub(statuses);
            artifactRepository = helpers.ResultArtifactRepositoryStub();
            coordinator = openmebius.application.batch ...
                .BatchExecutionCoordinator( ...
                RunService = runService, ...
                ArtifactRepository = artifactRepository);

        end

        function values = provenances(batchTable)

            values = cell(height(batchTable), 1);

            for i = 1:height(batchTable)
                values{i} = struct( ...
                    'batchId', batchTable.id(i), ...
                    'contentHash', "sha256:" + batchTable.id(i));
            end

        end

        function batchTable = batchTable(statuses)

            statuses = string(statuses(:));
            numberOfBatches = numel(statuses);
            configs = repmat( ...
                openmebius.domain.batch.BatchConfig.defaultConfig(), ...
                numberOfBatches, ...
                1);

            for i = 1:numberOfBatches
                configs(i).status = char(statuses(i));
                configs(i).deleteResultFile = false;
            end

            batchTable = table( ...
                "bat_" + string((1:numberOfBatches)'), ...
                "Batch " + string((1:numberOfBatches)'), ...
                repmat({"experiment-a"}, numberOfBatches, 1), ...
                strings(numberOfBatches, 1), ...
                configs, ...
                strings(numberOfBatches, 1), ...
                'VariableNames', ...
                openmebius.infrastructure.batch.BatchJsonMapper ...
                .defaultVariableNames());

        end

        function location = resultLocation()

            location = openmebius.domain.result.ResultLocation ...
                .fromDirectory(string(tempdir));

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
