classdef ChildAppArchitectureBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function childAppsUseContextActionPresenterViewBoundary(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            appNames = [ ...
                "RunConfig", ...
                "RunAddBatch", ...
                "LabelConfig", ...
                "TracerConfig", ...
                "MSView", ...
                "ComparisonView"];

            for appName = appNames
                source = string(fileread(fullfile( ...
                    root, "src", appName + "_exported.m")));
                testCase.verifyTrue(contains( ...
                    source, "startupFcn(app, context)"), appName);
                testCase.verifyFalse(contains(source, "MainApp"), appName);
                testCase.verifyFalse( ...
                    contains(source, "GeneralMessagePublisher"), appName);
                testCase.verifyFalse( ...
                    contains(source, "openmebius.infrastructure"), appName);
                testCase.verifyFalse(contains(source, "Repository"), appName);
                testCase.verifyFalse(contains(source, "IOModel"), appName);
                testCase.verifyFalse(contains(source, "IOExps"), appName);
                testCase.verifyFalse(contains(source, "IOResult"), appName);
            end

        end

        function editingAndExportActionsAreOutsideChildViews(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            labelSource = string(fileread(fullfile( ...
                root, "src", "LabelConfig_exported.m")));
            addBatchSource = string(fileread(fullfile( ...
                root, "src", "RunAddBatch_exported.m")));
            msSource = string(fileread(fullfile( ...
                root, "src", "MSView_exported.m")));
            comparisonSource = string(fileread(fullfile( ...
                root, "src", "ComparisonView_exported.m")));

            testCase.verifyTrue(contains(labelSource, "LabelConfigAction"));
            testCase.verifyFalse(contains(labelSource, "matlab.lang."));
            testCase.verifyTrue(contains( ...
                addBatchSource, "RunAddBatchAction"));
            testCase.verifyFalse(contains( ...
                addBatchSource, "BatchExperimentSelection("));
            testCase.verifyTrue(contains(msSource, "MSViewAction"));
            testCase.verifyFalse(contains(msSource, "writetable("));
            testCase.verifyTrue(contains( ...
                comparisonSource, "ComparisonViewAction"));
            testCase.verifyFalse(contains( ...
                comparisonSource, "exportgraphics("));

        end

        function registeredChildCallbacksRemainThin(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            appNames = [ ...
                "RunConfig", "RunAddBatch", "LabelConfig", ...
                "TracerConfig", "MSView", "ComparisonView"];

            for appName = appNames
                source = string(fileread(fullfile( ...
                    root, "src", appName + "_exported.m")));
                callbackStart = strfind( ...
                    source, "% Callbacks that handle component events");
                callbackEnd = strfind( ...
                    source, "% Component initialization");
                callbackSource = extractBetween( ...
                    source, callbackStart(1), callbackEnd(end) - 1);
                methods = regexp( ...
                    char(callbackSource), ...
                    ['(?ms)^        function\s+(?<Name>\w+)\([^\r\n]*' ...
                    '.*?^        end(?:\s*%[^\r\n]*)?\r?$'], ...
                    'names');

                for methodIndex = 1:numel(methods)
                    expression = ['(?ms)^        function\s+' ...
                        methods(methodIndex).Name ...
                        '\([^\r\n]*.*?^        end' ...
                        '(?:\s*%[^\r\n]*)?\r?$'];
                    methodSource = regexp( ...
                        char(callbackSource), ...
                        expression, ...
                        'match', ...
                        'once');
                    lineCount = numel(splitlines(string(methodSource)));
                    testCase.verifyLessThanOrEqual( ...
                        lineCount, ...
                        15, ...
                        appName + "." + methods(methodIndex).Name + ...
                        " contains " + lineCount + " lines.");
                end
            end

        end

    end

end
