classdef DocumentationBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function developerDocumentsCoverRequiredContracts(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            docs = fullfile(root, "docs", "_docs");
            files = [ ...
                "developer.md"; ...
                "architecture.md"; ...
                "format.md"; ...
                "migration.md"; ...
                "build.md"];

            testCase.assertTrue(all(isfile(fullfile(docs, files))));
            architecture = string(fileread(fullfile( ...
                docs, "architecture.md")));
            format = string(fileread(fullfile(docs, "format.md")));
            migration = string(fileread(fullfile(docs, "migration.md")));
            build = string(fileread(fullfile(docs, "build.md")));

            DocumentationBoundaryTest.verifyContainsAll( ...
                testCase, architecture, [ ...
                    "MainAppCompositionRoot"; ...
                    "openmebius.core.notification.Message"; ...
                    "ModelLocation"; ...
                    "ChildAppHost"]);
            DocumentationBoundaryTest.verifyContainsAll( ...
                testCase, format, [ ...
                    """schemaVersion"": 2"; ...
                    "<batch-id>.manifest.json"; ...
                    "contentHash"; ...
                    "Experiment workbook"]);
            DocumentationBoundaryTest.verifyContainsAll( ...
                testCase, migration, [ ...
                    "ProjectMigrationService"; ...
                    "BatchConfig.defaultConfig()"; ...
                    "Result and manifest"]);
            DocumentationBoundaryTest.verifyContainsAll( ...
                testCase, build, [ ...
                    "OpenMebius2SourceSyncTest.m"; ...
                    "BuildMyApp"; ...
                    "runTestProfile"]);
        end

        function documentedSchemaVersionsMatchImplementation(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            batchSource = string(fileread(fullfile( ...
                root, "src", "+openmebius", "+infrastructure", ...
                "+batch", "BatchJsonMigration.m")));
            manifestSource = string(fileread(fullfile( ...
                root, "src", "+openmebius", "+infrastructure", ...
                "+result", "ResultManifestMigration.m")));
            format = string(fileread(fullfile( ...
                root, "docs", "_docs", "format.md")));

            testCase.verifyTrue(contains(batchSource, ...
                "schemaVersion = 2"));
            testCase.verifyTrue(contains(format, ...
                "current Batch schema is version 2"));
            testCase.verifyTrue(contains(manifestSource, ...
                "CurrentSchemaVersion = 1"));
            testCase.verifyTrue(contains(format, ...
                "version 1 JSON manifest"));
        end

        function documentsDoNotReferenceRemovedEntryPoints(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            files = dir(fullfile(root, "**", "*.md"));
            removed = [ ...
                "src/TestAll.m"; ...
                "OpenMebiusCUI"; ...
                "LegacyReportRepository"; ...
                "ModelWorkspace.m"; ...
                "ExperimentWorkspace.m"; ...
                "ResultWorkspace.m"];
            violations = strings(0, 1);

            for fileIndex = 1:numel(files)
                path = fullfile(files(fileIndex).folder, ...
                    files(fileIndex).name);
                source = string(fileread(path));

                for value = removed'
                    if contains(source, value)
                        violations(end + 1, 1) = ...
                            string(path) + ": " + value; %#ok<AGROW>
                    end
                end
            end

            testCase.verifyEmpty(unique(violations));
        end

    end

    methods (Static, Access = private)

        function verifyContainsAll(testCase, source, values)
            for value = values'
                testCase.verifyTrue(contains(source, value));
            end
        end

    end

end
