classdef EMUMatrixBuilderTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourceToPath(~)

            addpath(EMUMatrixBuilderTest.sourcePath());

        end

    end

    methods (Test)

        function buildCnMapsAnRowsToMetabolites(testCase)

            sizeInfo = table( ...
                [1; 2], ...
                [2; 2], ...
                [0; 0], ...
                VariableNames = ["EMUSize", "An", "Bn"]);
            anMetabolites = cell(2, 2);
            anMetabolites{1, 1} = "A";
            anMetabolites{2, 1} = "B";
            anMetabolites{1, 2} = "B";
            builder = openmebius.mfa.EMUMatrixBuilder();

            result = builder.buildCn( ...
                sizeInfo, ...
                anMetabolites, ...
                ["A"; "B"; "C"]);

            expected = false(2, 3, 2);
            expected(1, 1, 1) = true;
            expected(2, 2, 1) = true;
            expected(1, 2, 2) = true;
            testCase.verifyEqual(result.Matrix, expected);
            testCase.verifyEqual(result.Diagonal, zeros(2, 2));

        end

        function buildMDVCreatesStableConvolutionIndex(testCase)

            tableEMU = table( ...
                ["A_{A}"; "B_{A}"; "T_{AB}"], ...
                ["A"; "B"; "T"], ...
                {1; 1; [1, 2]}, ...
                [1; 1; 2], ...
                [false; false; true], ...
                VariableNames = [ ...
                    "EMU", "Metabolite", "Position", "Size", "Target"]);
            reactantGroup = {'A_{A}', 'B_{A}'};
            productGroup = {'T_{AB}'};
            tableEMUReaction = table( ...
                "R1", ...
                {reactantGroup}, ...
                {productGroup}, ...
                1, ...
                2, ...
                true, ...
                VariableNames = [ ...
                    "RxnID", "Reactants", "Products", ...
                    "Coefficient", "Size", "Target"]);
            anNames = cell(2, 2);
            anNames{1, 1} = {'A_{A}'};
            anNames{2, 1} = {'B_{A}'};
            sizeInfo = table( ...
                [1; 2], ...
                [2; 0], ...
                [0; 0], ...
                VariableNames = ["EMUSize", "An", "Bn"]);
            builder = openmebius.mfa.EMUMatrixBuilder();

            result = builder.buildMDV( ...
                tableEMU, ...
                tableEMUReaction, ...
                anNames, ...
                sizeInfo);

            testCase.verifyEqual(result.Info, [2, 1]);
            testCase.verifyEqual(result.Size, 3);
            testCase.verifyEqual( ...
                result.List, ...
                [ ...
                    1, 0, 1, 1, 2; ...
                    1, 1, 2, 1, 2 ...
                ]);

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                EMUMatrixBuilderTest.repositoryRoot(), ...
                "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

    end

end
