classdef EMUMatrixBuilderTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourceToPath(~)

            addpath(EMUMatrixBuilderTest.sourcePath());

        end

    end

    methods (Test)

        function buildAnBnSeparatesInternalAndSubstrateEMUs(testCase)

            sizeInfo = table( ...
                1, 1, 1, ...
                VariableNames = ["EMUSize", "An", "Bn"]);
            tableEMU = table( ...
                ["S_{A}"; "A_{A}"], ...
                ["S"; "A"], ...
                {1; 1}, ...
                [1; 1], ...
                [false; false], ...
                VariableNames = [ ...
                    "EMU", "Metabolite", "Position", "Size", "Target"]);
            reactantGroup = {'S_{A}'};
            productGroup = {'A_{A}'};
            tableEMUReaction = table( ...
                {'r1'}, ...
                {reactantGroup}, ...
                {productGroup}, ...
                1, ...
                1, ...
                false, ...
                VariableNames = [ ...
                    "RxnID", "Reactants", "Products", ...
                    "Coefficient", "Size", "Target"]);
            builder = openmebius.mfa.EMUMatrixBuilder();

            result = builder.buildAnBn( ...
                sizeInfo, ...
                tableEMU, ...
                tableEMUReaction, ...
                "S", ...
                "r1");

            testCase.verifyEqual(result.An, zeros(1, 1));
            testCase.verifyEqual(result.Bn, zeros(1, 1));
            testCase.verifyEqual(result.AnNames{1, 1}, {'A_{A}'});
            testCase.verifyEqual(result.BnNames{1, 1}, {'S_{A}'});
            testCase.verifyEqual(result.AnMetabolites{1, 1}, "A");
            testCase.verifyEqual(result.BnMetabolites{1, 1}, "S");
            testCase.verifyEqual(result.AnList, [1, 1, 1, 1, -1]);
            testCase.verifyEqual(result.BnList, [1, 1, 1, 1, -1]);

        end

        function buildCnMapsAnRowsToMetabolites(testCase)

            sizeInfo = table( ...
                [1; 2], ...
                [2; 2], ...
                [0; 0], ...
                VariableNames = ["EMUSize", "An", "Bn"]);
            anMetabolites = cell(2, 2);
            anMetabolites{1, 1} = "A";
            anMetabolites{2, 1} = "B";
            anMetabolites{1, 2} = "B";
            builder = openmebius.mfa.EMUMatrixBuilder();

            result = builder.buildCn( ...
                sizeInfo, ...
                anMetabolites, ...
                ["A"; "B"; "C"]);

            expected = false(2, 3, 2);
            expected(1, 1, 1) = true;
            expected(2, 2, 1) = true;
            expected(1, 2, 2) = true;
            testCase.verifyEqual(result.Matrix, expected);
            testCase.verifyEqual(result.Diagonal, zeros(2, 2));

        end

        function buildXnYnMapsSubstrateAndConvolutionSources(testCase)

            sizeInfo = table( ...
                [1; 2], ...
                [2; 1], ...
                [1; 1], ...
                VariableNames = ["EMUSize", "An", "Bn"]);
            tableEMU = table( ...
                ["S_{A}"; "A_{A}"; "B_{A}"; "AB_{AB}"], ...
                ["S"; "A"; "B"; "AB"], ...
                {1; 1; 1; [1, 2]}, ...
                [1; 1; 1; 2], ...
                [false; false; false; false], ...
                VariableNames = [ ...
                    "EMU", "Metabolite", "Position", "Size", "Target"]);
            anNames = cell(2, 2);
            anNames{1, 1} = {'A_{A}'};
            anNames{2, 1} = {'B_{A}'};
            anNames{1, 2} = {'AB_{AB}'};
            bnNames = cell(1, 2);
            bnNames{1, 1} = {'S_{A}'};
            bnNames{1, 2} = {'A_{A}', 'B_{A}'};
            metaboliteTable = table( ...
                ["S"; "A"; "B"; "AB"], ...
                ["substrate"; "metabolite"; "metabolite"; "metabolite"], ...
                {2; 1; 1; 2}, ...
                VariableNames = ["Metabolite", "Type", "Carbon"]);
            builder = openmebius.mfa.EMUMatrixBuilder();

            result = builder.buildXnYn( ...
                sizeInfo, ...
                tableEMU, ...
                anNames, ...
                bnNames, ...
                metaboliteTable);

            expectedXn = zeros(2, 3, 2);
            expectedXn(:, 1, :) = 1;
            expectedYn = zeros(1, 3, 2);
            expectedYn(:, 1, :) = 1;
            testCase.verifyEqual(result.Xn, expectedXn);
            testCase.verifyEqual(result.Yn, expectedYn);
            testCase.verifyEmpty(result.XnList);
            testCase.verifyEqual( ...
                result.YnList, ...
                [ ...
                    1, 1, 0, 1, 2, 0; ...
                    2, 1, 0, 0, 1, 1; ...
                    2, 1, 1, 0, 1, 2 ...
                ]);
            testCase.verifyTrue(result.HasSubstrates);

        end

        function buildMDVCreatesStableConvolutionIndex(testCase)

            tableEMU = table( ...
                ["A_{A}"; "B_{A}"; "T_{AB}"], ...
                ["A"; "B"; "T"], ...
                {1; 1; [1, 2]}, ...
                [1; 1; 2], ...
                [false; false; true], ...
                VariableNames = [ ...
                    "EMU", "Metabolite", "Position", "Size", "Target"]);
            reactantGroup = {'A_{A}', 'B_{A}'};
            productGroup = {'T_{AB}'};
            tableEMUReaction = table( ...
                "R1", ...
                {reactantGroup}, ...
                {productGroup}, ...
                1, ...
                2, ...
                true, ...
                VariableNames = [ ...
                    "RxnID", "Reactants", "Products", ...
                    "Coefficient", "Size", "Target"]);
            anNames = cell(2, 2);
            anNames{1, 1} = {'A_{A}'};
            anNames{2, 1} = {'B_{A}'};
            sizeInfo = table( ...
                [1; 2], ...
                [2; 0], ...
                [0; 0], ...
                VariableNames = ["EMUSize", "An", "Bn"]);
            builder = openmebius.mfa.EMUMatrixBuilder();

            result = builder.buildMDV( ...
                tableEMU, ...
                tableEMUReaction, ...
                anNames, ...
                sizeInfo);

            testCase.verifyEqual(result.Info, [2, 1]);
            testCase.verifyEqual(result.Size, 3);
            testCase.verifyEqual( ...
                result.List, ...
                [ ...
                    1, 0, 1, 1, 2; ...
                    1, 1, 2, 1, 2 ...
                ]);

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                EMUMatrixBuilderTest.repositoryRoot(), ...
                "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

    end

end
