classdef EMUNetworkBuilderTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourceToPath(~)

            addpath(EMUNetworkBuilderTest.sourcePath());

        end

    end

    methods (Test)

        function buildExecutesOperationsInOrder(testCase)

            recorder = EMUNetworkBuilderTest.createRecorder();
            sizeInfo = table(1, 2, 3, ...
                VariableNames = ["EMUSize", "An", "Bn"]);
            expectedSnapshot = EMUNetworkBuilderTest.createSnapshot();
            operations = openmebius.mfa.EMUNetworkBuildOperations( ...
                Initialize = @() EMUNetworkBuilderTest.record( ...
                recorder, "initialize"), ...
                Enumerate = @() EMUNetworkBuilderTest.record( ...
                recorder, "enumerate"), ...
                Validate = @() EMUNetworkBuilderTest.record( ...
                recorder, "validate"), ...
                ResolveSizeInfo = @() ...
                EMUNetworkBuilderTest.recordAndReturn( ...
                recorder, "resolveSizeInfo", sizeInfo), ...
                AssignSizeInfo = @(value) ...
                EMUNetworkBuilderTest.recordAssignment( ...
                recorder, value), ...
                BuildAnBn = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildAnBn"), ...
                BuildCn = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildCn"), ...
                BuildXnYn = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildXnYn"), ...
                BuildMDV = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildMDV"), ...
                CreateSnapshot = @() ...
                EMUNetworkBuilderTest.recordAndReturn( ...
                recorder, "createSnapshot", expectedSnapshot));

            builder = openmebius.mfa.EMUNetworkBuilder();
            actualSnapshot = builder.build(operations);

            testCase.verifyEqual( ...
                recorder("Calls"), ...
                [ ...
                "initialize"; ...
                "enumerate"; ...
                "validate"; ...
                "resolveSizeInfo"; ...
                "assignSizeInfo"; ...
                "buildAnBn"; ...
                "buildCn"; ...
                "buildXnYn"; ...
                "buildMDV"; ...
                "createSnapshot" ...
                ]);
            testCase.verifyEqual(recorder("SizeInfo"), sizeInfo);
            testCase.verifyEqual( ...
                actualSnapshot.TableEMU, ...
                expectedSnapshot.TableEMU);

        end

        function buildStopsAfterFailedEnumeration(testCase)

            recorder = EMUNetworkBuilderTest.createRecorder();
            operations = openmebius.mfa.EMUNetworkBuildOperations( ...
                Initialize = @() EMUNetworkBuilderTest.record( ...
                recorder, "initialize"), ...
                Enumerate = @() EMUNetworkBuilderTest.failEnumeration( ...
                recorder), ...
                Validate = @() EMUNetworkBuilderTest.record( ...
                recorder, "validate"), ...
                ResolveSizeInfo = @() table(), ...
                AssignSizeInfo = @(~) EMUNetworkBuilderTest.record( ...
                recorder, "assignSizeInfo"), ...
                BuildAnBn = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildAnBn"), ...
                BuildCn = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildCn"), ...
                BuildXnYn = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildXnYn"), ...
                BuildMDV = @() EMUNetworkBuilderTest.record( ...
                recorder, "buildMDV"), ...
                CreateSnapshot = @() ...
                EMUNetworkBuilderTest.createSnapshot());
            builder = openmebius.mfa.EMUNetworkBuilder();

            testCase.verifyError( ...
                @() builder.build(operations), ...
                "OpenMebius2:Test:EnumerationFailed");
            testCase.verifyEqual( ...
                recorder("Calls"), ...
                ["initialize"; "enumerate"]);

        end

    end

    methods (Static, Access = private)

        function recorder = createRecorder()

            recorder = containers.Map( ...
                "KeyType", "char", ...
                "ValueType", "any");
            recorder("Calls") = strings(0, 1);

        end

        function record(recorder, operation)

            recorder("Calls") = [ ...
                recorder("Calls"); string(operation)]; %#ok<NASGU>

        end

        function value = recordAndReturn(recorder, operation, value)

            EMUNetworkBuilderTest.record(recorder, operation);

        end

        function recordAssignment(recorder, sizeInfo)

            EMUNetworkBuilderTest.record(recorder, "assignSizeInfo");
            recorder("SizeInfo") = sizeInfo; %#ok<NASGU>

        end

        function failEnumeration(recorder)

            EMUNetworkBuilderTest.record(recorder, "enumerate");
            error( ...
                "OpenMebius2:Test:EnumerationFailed", ...
                "The test enumeration failed.");

        end

        function snapshot = createSnapshot()

            payload = struct( ...
                "tableEMU", table("A", VariableNames = "EMU"), ...
                "tableEMUReaction", table(), ...
                "tableEMUSizeInfo", table());
            snapshot = openmebius.domain.model.EMUNetworkSnapshot(payload);

        end

        function path = sourcePath()

            path = fullfile( ...
                EMUNetworkBuilderTest.repositoryRoot(), ...
                "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

    end

end
