classdef ExperimentMDVCalculatorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentMDVCalculatorTest.sourcePath());

        end

    end

    methods (Test)

        function validatesAndNormalizesBiomassMDV(testCase)

            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator(MDVTolerance = -1e-2);
            source = array2table( ...
                [1.005, 0.6; -0.005, 0.5], ...
                VariableNames = ["Accepted", "Invalid"]);

            [actual, errors] = calculator.validateBiomassMDV(source);

            testCase.verifyEqual(errors, [false, true]);
            testCase.verifyEqual( ...
                actual.Accepted, ...
                [1; 0], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(actual.Invalid, source.Invalid);

        end

        function createsSelectionFromModelAndValidMDV(testCase)

            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator();
            mdv = array2table( ...
                [0.8, 0.7; 0.2, 0.3], ...
                VariableNames = ["A", "C"]);
            modelMS = table( ...
                [true; false], ...
                VariableNames = "Used", ...
                RowNames = ["A"; "B"]);

            actual = calculator.createFragmentSelection( ...
                mdv, ...
                [false, true], ...
                modelMS, ...
                ["A"; "B"]);

            testCase.verifyEqual(actual.Select, [true; false]);
            testCase.verifyEqual(actual.Available, [true; false]);

        end

        function rejectsInconsistentTargetList(testCase)

            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator();
            mdv = array2table( ...
                [0.8; 0.2], ...
                VariableNames = "A");
            modelMS = table( ...
                true, ...
                VariableNames = "Used", ...
                RowNames = "A");

            testCase.verifyError( ...
                @() calculator.createFragmentSelection( ...
                mdv, ...
                false, ...
                modelMS, ...
                "Different"), ...
                "OpenMebius2:ExperimentMDVCalculator:" + ...
                "InvalidTargetList");

        end

        function resolvesCorrectionMethodAtCalculationTime(testCase)

            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator( ...
                NaturalIsotopeCorrectionMethodProvider = ...
                @() "matrix");
            input = ExperimentMDVCalculatorTest.calculationInput();

            actual = calculator.calculate(input);
            expected = MDVCorrection().correctNaturalIsotopoper( ...
                input.RawMS.A, ...
                1, 0, 0, 0, 0, 0, ...
                method = "matrix", ...
                numTracerCarbon = 1);

            testCase.verifyEqual( ...
                actual.MDV.A, ...
                expected', ...
                AbsTol = 1e-12);
            testCase.verifyEmpty(actual.MDVOptimization);

        end

        function fractionOptimizationStoresIdenticalMDVs(testCase)

            correction = MDVCorrection();
            correctionMatrix = correction.getCorrectedMatrixSkew( ...
                1, 0, 0, 0, 0, 0, ...
                numObservedMDV = 2, ...
                numTracerCarbon = 1);
            expectedMDV = [0.2; 0.8];
            expectedFraction = 0.08;
            initialMDV = [1; 0];
            observed = correctionMatrix * ( ...
                (1 - expectedFraction) * expectedMDV + ...
                expectedFraction * initialMDV);
            input = ExperimentMDVCalculatorTest.calculationInput();
            input = openmebius.domain.experiment ...
                .ExperimentMDVCalculationInput( ...
                ExperimentName = input.ExperimentName, ...
                RawMS = array2table( ...
                observed, VariableNames = "A"), ...
                ExperimentInfo = table( ...
                expectedFraction, 1, ...
                VariableNames = ["ODi", "ODf"]), ...
                AtomTable = input.AtomTable, ...
                MSMetaboliteTable = input.MSMetaboliteTable, ...
                ModelMSTable = input.ModelMSTable, ...
                TargetMetabolites = input.TargetMetabolites);
            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator( ...
                NaturalIsotopeCorrectionMethod = ...
                "least-squares-with-fraction");

            actual = calculator.calculate(input);

            testCase.verifyEqual( ...
                actual.MDV{:, :}, ...
                actual.MDVBiomass{:, :}, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                actual.MDV.A, expectedMDV, AbsTol = 1e-8);
            testCase.verifyEqual( ...
                actual.MDVOptimization.Fraction, ...
                expectedFraction, ...
                AbsTol = 1e-8);
            testCase.verifyLessThan( ...
                actual.MDVOptimization.Objective, 1e-12);

        end

        function derivedDataRequiresAlignedErrorFlags(testCase)

            testCase.verifyError( ...
                @() openmebius.domain.experiment.ExperimentDerivedData( ...
                MSNormalized = table(), ...
                MDV = table(), ...
                MDVBiomass = array2table(1, VariableNames = "A"), ...
                MDVErrors = false(1, 0), ...
                Enrichment = table(), ...
                EnrichmentErrors = false(0, 1), ...
                Selection = table()), ...
                "OpenMebius2:ExperimentDerivedData:InvalidMDVErrors");

        end

    end

    methods (Static, Access = private)

        function input = calculationInput()

            rawMS = array2table( ...
                [0.9; 0.1], ...
                VariableNames = "A");
            experimentInfo = table( ...
                0, ...
                1, ...
                VariableNames = ["ODi", "ODf"]);
            atomTable = table( ...
                1, 0, 0, 0, 0, 0, ...
                VariableNames = ["C", "H", "O", "N", "S", "Si"], ...
                RowNames = "A");
            msMetaboliteTable = table( ...
                "A", ...
                1, ...
                VariableNames = ["Metabolite", "Carbon"]);
            modelMSTable = table( ...
                true, ...
                VariableNames = "Used", ...
                RowNames = "A");
            input = openmebius.domain.experiment ...
                .ExperimentMDVCalculationInput( ...
                ExperimentName = "exp1", ...
                RawMS = rawMS, ...
                ExperimentInfo = experimentInfo, ...
                AtomTable = atomTable, ...
                MSMetaboliteTable = msMetaboliteTable, ...
                ModelMSTable = modelMSTable, ...
                TargetMetabolites = "A");

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
