classdef ExperimentTableAssemblerTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentTableAssemblerTest.sourcePath());

        end

    end

    methods (Test)

        function assemblesTypedAggregateTables(testCase)

            collection = ExperimentTableAssemblerTest.createCollection( ...
                ["ExpB.xlsx", "ExpA.xlsx"]);
            collection.replaceData(struct( ...
                "ExpB_xlsx", ...
                ExperimentTableAssemblerTest.experimentData( ...
                0.2, [2; 3], ["bA"; "bB"], true), ...
                "ExpA_xlsx", ...
                ExperimentTableAssemblerTest.experimentData( ...
                0.1, [1; 4], ["aA"; "aB"], true)));
            assembler = openmebius.domain.experiment ...
                .ExperimentTableAssembler();

            result = assembler.assemble(collection);

            testCase.verifyClass( ...
                result, ...
                "openmebius.domain.experiment.ExperimentAggregateTables");
            testCase.verifyEqual( ...
                string(result.Info.Properties.RowNames), ...
                ["ExpB"; "ExpA"]);
            testCase.verifyEqual( ...
                string(result.Uptake.Properties.RowNames), ...
                ["ExpA"; "ExpB"]);
            testCase.verifyEqual( ...
                string(result.Uptake.Properties.VariableNames), ...
                ["A", "B", "C"]);
            testCase.verifyEqual( ...
                result.Uptake{:, ["A", "B"]}, ...
                [1, 4; 2, 3]);
            testCase.verifyTrue(all(isnan(result.Uptake.C)));
            testCase.verifyEqual( ...
                string(result.Tracer.A), ["aA"; "bA"]);
            testCase.verifyEqual( ...
                string(result.UptakeFull.Properties.VariableNames), ...
                ["A", "B"]);

        end

        function fillsExperimentWithoutSubstrateRows(testCase)

            collection = ExperimentTableAssemblerTest.createCollection( ...
                ["Missing.xlsx", "Present.xlsx"]);
            collection.replaceData(struct( ...
                "Missing_xlsx", ...
                ExperimentTableAssemblerTest.experimentData( ...
                0.1, 1, "missing", false), ...
                "Present_xlsx", ...
                ExperimentTableAssemblerTest.experimentData( ...
                0.2, [2; 3], ["pA"; "pB"], true)));
            assembler = openmebius.domain.experiment ...
                .ExperimentTableAssembler();

            result = assembler.assemble(collection);

            testCase.verifyEqual( ...
                string(result.Uptake.Properties.RowNames), ...
                ["Missing"; "Present"]);
            testCase.verifyTrue(all(isnan( ...
                result.Uptake{"Missing", :})));
            testCase.verifyEqual( ...
                string(result.Tracer{"Missing", :}), ...
                ["", "", ""]);

        end

        function collectionAcceptsAggregateResult(testCase)

            collection = ExperimentTableAssemblerTest.createCollection( ...
                "ExpA.xlsx");
            collection.replaceData(struct( ...
                "ExpA_xlsx", ...
                ExperimentTableAssemblerTest.experimentData( ...
                0.1, [1; 4], ["aA"; "aB"], true)));
            assembler = openmebius.domain.experiment ...
                .ExperimentTableAssembler();

            aggregate = assembler.assemble(collection);
            collection.replaceAggregateTables(aggregate);

            testCase.verifyEqual(collection.InfoTable, aggregate.Info);
            testCase.verifyEqual(collection.TracerTable, aggregate.Tracer);
            testCase.verifyEqual(collection.UptakeTable, aggregate.Uptake);

        end

    end

    methods (Static, Access = private)

        function collection = createCollection(fileNames)

            location = openmebius.domain.experiment.ExperimentLocation ...
                .fromDirectory("experiment-root");
            collection = openmebius.domain.experiment ...
                .ExperimentCollection(location);
            collection.replaceFiles(fileNames);
            collection.replaceModel( ...
                helpers.ExperimentSubstrateModelStub(["A", "B", "C"]), ...
                "model.xlsx");

        end

        function data = experimentData(mu, uptake, label, withRowNames)

            info = table( ...
                mu, 0.1, 0.8, ...
                VariableNames = ["mu", "ODi", "ODf"]);

            if withRowNames
                rowNames = ["A"; "B"];
                substrate = table( ...
                    uptake, ...
                    label, ...
                    VariableNames = ["Uptake", "Label"], ...
                    RowNames = rowNames);
            else
                substrate = table( ...
                    uptake, ...
                    label, ...
                    VariableNames = ["Uptake", "Label"]);
            end

            data = struct( ...
                "tableInfo", info, ...
                "tableSubstrate", substrate);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
