classdef ExperimentDerivedDataRestorerTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentDerivedDataRestorerTest.sourcePath());

        end

    end

    methods (Test)

        function validatesStoredDerivedTables(testCase)

            restorer = openmebius.domain.experiment ...
                .ExperimentDerivedDataRestorer();
            biomass = array2table( ...
                [1.005; -0.005], ...
                VariableNames = "A");
            enrichment = table( ...
                [0.5; NaN], ...
                VariableNames = "Enrichment", ...
                RowNames = ["A"; "B"]);

            result = restorer.restore( ...
                MDVBiomass = biomass, ...
                Enrichment = enrichment, ...
                ModelMSTable = ...
                ExperimentDerivedDataRestorerTest.modelMSTable(), ...
                TargetMetabolites = "A");

            testCase.verifyEqual( ...
                result.MDVBiomass.A, ...
                [1; 0], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(result.MDVErrors, false);
            testCase.verifyEqual(result.Selection.Available, true);
            testCase.verifyEqual( ...
                result.EnrichmentErrors, ...
                [false; true]);
            testCase.verifyEmpty(result.Warnings);

        end

        function invalidSelectionContextBecomesWarning(testCase)

            restorer = openmebius.domain.experiment ...
                .ExperimentDerivedDataRestorer();
            biomass = array2table( ...
                [0.8; 0.2], ...
                VariableNames = "A");

            result = restorer.restore( ...
                MDVBiomass = biomass, ...
                ModelMSTable = ...
                ExperimentDerivedDataRestorerTest.modelMSTable(), ...
                TargetMetabolites = "Different");

            testCase.verifyEqual(result.MDVErrors, true);
            testCase.verifyEmpty(result.Selection);
            testCase.verifyTrue(any(contains( ...
                result.Warnings, ...
                "could not be validated")));

        end

        function nonnumericEnrichmentBecomesWarning(testCase)

            restorer = openmebius.domain.experiment ...
                .ExperimentDerivedDataRestorer();
            enrichment = table( ...
                ["bad"; "value"], ...
                VariableNames = "Enrichment");

            result = restorer.restore(Enrichment = enrichment);

            testCase.verifyEqual( ...
                result.EnrichmentErrors, ...
                [true; true]);
            testCase.verifyTrue(any(contains( ...
                result.Warnings, ...
                "stored enrichment sheet")));

        end

    end

    methods (Static, Access = private)

        function value = modelMSTable()

            value = table( ...
                true, ...
                VariableNames = "Used", ...
                RowNames = "A");

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
