classdef ExperimentWorkbookStoreTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentWorkbookStoreTest.sourcePath());

        end

    end

    methods (Test)

        function loadMapsWorkbookToTypedData(testCase)

            store = openmebius.infrastructure.experiment ...
                .ExperimentWorkbookStore();

            workbook = store.load( ...
                ExperimentWorkbookStoreTest.datasetWorkbook());

            testCase.verifyClass( ...
                workbook, ...
                "openmebius.infrastructure.experiment." + ...
                "ExperimentWorkbookData");
            testCase.verifyGreaterThan(width(workbook.MS), 0);
            testCase.verifyEqual( ...
                workbook.DefaultSubstrateVariableNames, ...
                ["Uptake", "Label"]);
            testCase.verifyEqual( ...
                workbook.DefaultSubstrateVariableTypes, ...
                ["double", "string"]);

        end

        function saveRoundTripPreservesWorkbookData(testCase)

            experimentDirectory = string(tempname);
            mkdir(experimentDirectory);
            cleanup = onCleanup(@() ...
                ExperimentWorkbookStoreTest ...
                .removeDirectory(experimentDirectory));
            pathFile = fullfile(experimentDirectory, "saved.xlsx");
            info = table( ...
                0.1, 0.2, 0.8, ...
                VariableNames = ["mu", "ODi", "ODf"]);
            substrate = table( ...
                [0.5; 1.0], ...
                ["A"; "B"], ...
                VariableNames = ["Uptake", "Label"], ...
                RowNames = ["glc"; "lac"]);
            ms = array2table( ...
                [100, 50; 80, 20], ...
                VariableNames = ["sample1", "sample2"], ...
                RowNames = ["A_0"; "A_1"]);
            normalized = array2table( ...
                [0.8, 0.7; 0.2, 0.3], ...
                VariableNames = ["sample1", "sample2"], ...
                RowNames = ["A_0"; "A_1"]);
            optimization = table( ...
                [1e-6; 2e-6], ...
                [0.1; 0.2], ...
                VariableNames = ["Objective", "Fraction"], ...
                RowNames = ["sample1"; "sample2"]);
            workbook = openmebius.infrastructure.experiment ...
                .ExperimentWorkbookData( ...
                Info = info, ...
                Substrate = substrate, ...
                MS = ms, ...
                MSNormalized = normalized, ...
                MDVOptimization = optimization, ...
                DefaultSubstrateVariableNames = ["Uptake", "Label"], ...
                DefaultSubstrateVariableTypes = ["double", "string"]);
            store = openmebius.infrastructure.experiment ...
                .ExperimentWorkbookStore();

            store.save(pathFile, workbook);
            loaded = store.load(pathFile);

            testCase.verifyEqual(loaded.Info{:, :}, info{:, :});
            testCase.verifyEqual(loaded.Substrate.Uptake, substrate.Uptake);
            testCase.verifyEqual( ...
                string(loaded.Substrate.Label), substrate.Label);
            testCase.verifyEqual(loaded.MS{:, :}, ms{:, :});
            testCase.verifyEqual( ...
                loaded.MSNormalized{:, :}, normalized{:, :});
            testCase.verifyEqual( ...
                loaded.MDVOptimization{:, :}, optimization{:, :});
            testCase.verifyEqual( ...
                string(loaded.MDVOptimization.Properties.RowNames), ...
                string(optimization.Properties.RowNames));

            clear cleanup

        end

        function readOptionalSheetUsesLegacyAlias(testCase)

            experimentDirectory = string(tempname);
            mkdir(experimentDirectory);
            cleanup = onCleanup(@() ...
                ExperimentWorkbookStoreTest ...
                .removeDirectory(experimentDirectory));
            pathFile = fullfile(experimentDirectory, "optional.xlsx");
            sourceTable = table( ...
                [0.1; 0.9], ...
                VariableNames = "M0");
            store = openmebius.infrastructure.experiment ...
                .ExperimentWorkbookStore();

            [isSuccess, message] = store.writeSheet( ...
                pathFile, ...
                sourceTable, ...
                "MS normalized data", ...
                WriteRowNames = false);
            testCase.assertTrue(isSuccess, message);

            loaded = store.readOptionalSheet( ...
                pathFile, ...
                "MS (Normalized)", ...
                ["MS normalized data", "MS normarized data"], ...
                ReadRowNames = false);

            testCase.verifyEqual(loaded.M0, sourceTable.M0);

            clear cleanup

        end

        function readSheetRejectsMissingWorkbook(testCase)

            store = openmebius.infrastructure.experiment ...
                .ExperimentWorkbookStore();

            testCase.verifyError( ...
                @() store.readSheet( ...
                fullfile(tempdir, "missing-openmebius-exp.xlsx"), ...
                "MS"), ...
                "OpenMebius2:ExperimentWorkbookStore:WorkbookNotFound");

        end

    end

    methods (Static, Access = private)

        function path = datasetWorkbook()

            path = fullfile( ...
                ExperimentWorkbookStoreTest.repositoryRoot(), ...
                "dataset", ...
                "WT_ecoli.xlsx");

        end

        function path = sourcePath()

            path = fullfile( ...
                ExperimentWorkbookStoreTest.repositoryRoot(), "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, "s");
            end

        end

    end

end % classdef
