classdef ExperimentEditMapperTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentEditMapperTest.sourcePath());

        end

    end

    methods (Test)

        function normalizesUITableValues(testCase)

            tracerValues = cell(2, 1);
            tracerValues{1} = [];
            tracerValues{2} = {"12C1~1"};
            tracer = table( ...
                tracerValues, ...
                VariableNames = "Glucose", ...
                RowNames = ["ExpA", "ExpB"]);
            uptake = table( ...
                {"1.5"; []}, ...
                VariableNames = "Glucose", ...
                RowNames = ["ExpA", "ExpB"]);
            mapper = openmebius.domain.experiment ...
                .ExperimentEditMapper();

            tracer = mapper.normalizeUITableInput(tracer, "Tracer");
            uptake = mapper.normalizeUITableInput(uptake, "Uptake");

            testCase.verifyEqual(tracer.Glucose, [""; "12C1~1"]);
            testCase.verifyEqual(uptake.Glucose(1), 1.5);
            testCase.verifyTrue(isnan(uptake.Glucose(2)));

        end

        function mapsTracerRowsBySampleName(testCase)

            collection = ExperimentEditMapperTest.createCollection();
            aggregateTable = table( ...
                ["bA"; "aA"], ...
                ["bB"; "aB"], ...
                VariableNames = ["A", "B"], ...
                RowNames = ["ExpB", "ExpA"]);
            mapper = openmebius.domain.experiment ...
                .ExperimentEditMapper();

            result = mapper.map( ...
                collection, aggregateTable, "Tracer");

            testCase.verifyClass( ...
                result, ...
                "openmebius.domain.experiment.ExperimentEditMappingResult");
            testCase.verifyEqual(result.FullTable{"ExpA", "A"}, "aA");
            testCase.verifyEqual(result.FullTable{"ExpB", "A"}, "bA");
            testCase.verifyEqual( ...
                result.Data.ExpA_xlsx.tableSubstrate{"B", "Label"}, ...
                "aB");
            testCase.verifyTrue(isnan( ...
                result.Data.ExpA_xlsx.tableSubstrate{"B", "Uptake"}));

            collection.applyEdit(result);
            testCase.verifyEqual(collection.TracerTable, aggregateTable);
            testCase.verifyEqual(collection.TracerTableFull, result.FullTable);
            testCase.verifyEqual(collection.Data, result.Data);

        end

        function mapsUptakeWithoutChangingTracerValues(testCase)

            collection = ExperimentEditMapperTest.createCollection();
            aggregateTable = table( ...
                [20; 10], ...
                [200; 100], ...
                VariableNames = ["A", "B"], ...
                RowNames = ["ExpB", "ExpA"]);
            mapper = openmebius.domain.experiment ...
                .ExperimentEditMapper();

            result = mapper.map( ...
                collection, aggregateTable, "Uptake");

            testCase.verifyEqual(result.FullTable{"ExpA", "A"}, 10);
            testCase.verifyEqual( ...
                result.Data.ExpA_xlsx.tableSubstrate{"B", "Uptake"}, ...
                100);
            testCase.verifyEqual( ...
                result.Data.ExpA_xlsx.tableSubstrate{"B", "Label"}, ...
                "");

        end

        function rejectsMismatchedSamplesBeforeMapping(testCase)

            collection = ExperimentEditMapperTest.createCollection();
            aggregateTable = table( ...
                ["a"; "c"], ...
                VariableNames = "A", ...
                RowNames = ["ExpA", "ExpC"]);
            mapper = openmebius.domain.experiment ...
                .ExperimentEditMapper();

            testCase.verifyError( ...
                @() mapper.map( ...
                collection, aggregateTable, "Tracer"), ...
                "OpenMebius2:ExperimentEditMapper:SampleMismatch");

        end

    end

    methods (Static, Access = private)

        function collection = createCollection()

            location = openmebius.domain.experiment.ExperimentLocation ...
                .fromDirectory("experiment-root");
            collection = openmebius.domain.experiment ...
                .ExperimentCollection(location);
            collection.replaceFiles(["ExpA.xlsx", "ExpB.xlsx"]);
            collection.replaceData(struct( ...
                "ExpA_xlsx", ...
                ExperimentEditMapperTest.experimentData(1, "old-a"), ...
                "ExpB_xlsx", ...
                ExperimentEditMapperTest.experimentData(2, "old-b")));

            tracer = table( ...
                ["old-a"; "old-b"], ...
                VariableNames = "A", ...
                RowNames = ["ExpA", "ExpB"]);
            uptake = table( ...
                [1; 2], ...
                VariableNames = "A", ...
                RowNames = ["ExpA", "ExpB"]);
            collection.replaceTracerTables(tracer, tracer);
            collection.replaceUptakeTables(uptake, uptake);

        end

        function data = experimentData(uptake, label)

            data = struct( ...
                "tableInfo", table(), ...
                "tableSubstrate", table( ...
                uptake, string(label), ...
                VariableNames = ["Uptake", "Label"], ...
                RowNames = "A"));

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
