classdef ExperimentEditValidatorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentEditValidatorTest.sourcePath());

        end

    end

    methods (Test)

        function acceptsValidTracerDefinitions(testCase)

            data = table( ...
                ["12C1~1"; "12C1~0.5;13C1~0.5"], ...
                [""; "13C1~1"], ...
                VariableNames = ["Glucose", "Acetate"], ...
                RowNames = ["ExpB", "ExpA"]);

            report = openmebius.domain.experiment ...
                .ExperimentEditValidator.validateTracer( ...
                data, ...
                ["Glucose", "Acetate"], ...
                ["ExpA", "ExpB"], ...
                ["12C1", "13C1"]);

            testCase.verifyTrue(report.IsValid);

        end

        function rejectsMalformedTracerDefinition(testCase)

            data = table( ...
                "12C1", ...
                VariableNames = "Glucose", ...
                RowNames = "ExpA");

            report = openmebius.domain.experiment ...
                .ExperimentEditValidator.validateTracer( ...
                data, "Glucose", "ExpA", "12C1");

            testCase.verifyFalse(report.IsValid);
            testCase.verifySubstring( ...
                report.ErrorMessage, "label~ratio");

        end

        function rejectsUnknownTracerAndInvalidRatio(testCase)

            unknownTracer = table( ...
                "13C1~1", ...
                VariableNames = "Glucose", ...
                RowNames = "ExpA");
            invalidRatio = table( ...
                "12C1~1.1", ...
                VariableNames = "Glucose", ...
                RowNames = "ExpA");

            unknownReport = openmebius.domain.experiment ...
                .ExperimentEditValidator.validateTracer( ...
                unknownTracer, "Glucose", "ExpA", "12C1");
            ratioReport = openmebius.domain.experiment ...
                .ExperimentEditValidator.validateTracer( ...
                invalidRatio, "Glucose", "ExpA", "12C1");

            testCase.verifyFalse(unknownReport.IsValid);
            testCase.verifySubstring( ...
                unknownReport.ErrorMessage, "not available");
            testCase.verifyFalse(ratioReport.IsValid);
            testCase.verifySubstring( ...
                ratioReport.ErrorMessage, "between 0 and 1");

        end

        function validatesUptakeValuesAndShape(testCase)

            validData = table( ...
                [1; NaN], ...
                VariableNames = "Glucose", ...
                RowNames = ["ExpA", "ExpB"]);
            invalidData = validData;
            invalidData.Glucose(1) = Inf;

            validReport = openmebius.domain.experiment ...
                .ExperimentEditValidator.validateUptake( ...
                validData, "Glucose", ["ExpA", "ExpB"]);
            invalidReport = openmebius.domain.experiment ...
                .ExperimentEditValidator.validateUptake( ...
                invalidData, "Glucose", ["ExpA", "ExpB"]);
            shapeReport = openmebius.domain.experiment ...
                .ExperimentEditValidator.validateUptake( ...
                validData, "Acetate", ["ExpA", "ExpB"]);

            testCase.verifyTrue(validReport.IsValid);
            testCase.verifyFalse(invalidReport.IsValid);
            testCase.verifyFalse(shapeReport.IsValid);
            testCase.verifySubstring( ...
                shapeReport.ErrorMessage, "variable names");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
