classdef ExperimentCalculationServiceTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            sourcePath = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');
            addpath(sourcePath);

        end % addSourcePath

    end % methods

    methods (Test)

        function calculateMDVUpdatesExperimentAndBatch(testCase)

            fixture = ExperimentCalculationServiceTest.importFixture();
            cleanup = onCleanup( ...
                @() ExperimentCalculationServiceTest ...
                .removeDirectory(fixture.Directory));

            [infoTable, uptakeTable, tracerTable] = ...
                ExperimentCalculationServiceTest.validExperimentTables( ...
                fixture.ImportResult.Experiments);

            service = ...
                openmebius.application.experiment.ExperimentCalculationService();

            result = service.calculateMDV( ...
                fixture.ImportResult.Experiments.getModel(), ...
                fixture.ImportResult.Experiments, ...
                fixture.ImportResult.Batch, ...
                infoTable, ...
                uptakeTable, ...
                tracerTable);

            testCase.verifyClass(result.Experiments, 'IOExps');
            testCase.verifyClass(result.Batch, 'Batch');
            testCase.verifyTrue(result.HasCalculatedMDV);
            testCase.verifyTrue(result.Experiments.hasCalculatedMDV());
            testCase.verifyTrue(any(contains( ...
                result.Messages, ...
                "MDV-derived tables have been updated successfully.")));
            testCase.verifyTrue(any(contains( ...
                result.Warnings, ...
                "is not found in the model.")));
            testCase.verifyFalse(ismethod(result.Experiments, "calculateMDV"));

            [enrichment, enrichmentErrors] = ...
                result.Experiments.getEnrichmentComparison();
            [selected, available] = ...
                result.Experiments.getSelectionComparison();
            experimentName = result.Experiments.getExpName(1);
            [mdvBiomass, ~] = ...
                result.Experiments.getMDVBiomassTable(experimentName);
            fragmentName = string( ...
                mdvBiomass.Properties.VariableNames(1));
            mdvComparison = ...
                result.Experiments.getMDVBiomassComparison(fragmentName);

            testCase.verifyNotEmpty(enrichment);
            testCase.verifySize(enrichmentErrors, size(enrichment));
            testCase.verifyNotEmpty(selected);
            testCase.verifyEqual(size(selected), size(available));
            testCase.verifyNotEmpty(mdvComparison);

        end % calculateMDVUpdatesExperimentAndBatch

        function invalidInfoTableRaisesUpdateError(testCase)

            fixture = ExperimentCalculationServiceTest.importFixture();
            cleanup = onCleanup( ...
                @() ExperimentCalculationServiceTest ...
                .removeDirectory(fixture.Directory));

            [~, uptakeTable, tracerTable] = ...
                ExperimentCalculationServiceTest.validExperimentTables( ...
                fixture.ImportResult.Experiments);

            service = ...
                openmebius.application.experiment.ExperimentCalculationService();

            testCase.verifyError( ...
                @() service.calculateMDV( ...
                fixture.ImportResult.Experiments.getModel(), ...
                fixture.ImportResult.Experiments, ...
                fixture.ImportResult.Batch, ...
                table(), ...
                uptakeTable, ...
                tracerTable), ...
                "OpenMebius2:ExperimentCalculation:UpdateFailed");

        end % invalidInfoTableRaisesUpdateError

        function calculatorFailureDoesNotApplyDerivedData(testCase)

            fixture = ExperimentCalculationServiceTest.importFixture();
            cleanup = onCleanup( ...
                @() ExperimentCalculationServiceTest ...
                .removeDirectory(fixture.Directory));

            [infoTable, uptakeTable, tracerTable] = ...
                ExperimentCalculationServiceTest.validExperimentTables( ...
                fixture.ImportResult.Experiments);
            calculator = helpers.FailingExperimentMDVCalculator();
            service = openmebius.application.experiment ...
                .ExperimentCalculationService( ...
                MDVCalculator = calculator);

            testCase.verifyError( ...
                @() service.calculateMDV( ...
                fixture.ImportResult.Experiments.getModel(), ...
                fixture.ImportResult.Experiments, ...
                fixture.ImportResult.Batch, ...
                infoTable, ...
                uptakeTable, ...
                tracerTable), ...
                "OpenMebius2:ExperimentCalculation:CalculationFailed");

            testCase.verifyEqual(calculator.CallCount, 1);
            testCase.verifyClass( ...
                calculator.LastInput, ...
                "openmebius.domain.experiment." + ...
                "ExperimentMDVCalculationInput");
            testCase.verifyFalse( ...
                fixture.ImportResult.Experiments.hasCalculatedMDV());

        end % calculatorFailureDoesNotApplyDerivedData

    end % methods

    methods (Static, Access = private)

        function fixture = importFixture()

            repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
            experimentDirectory = string(tempname);
            mkdir(experimentDirectory);

            sourceFile = fullfile(repositoryRoot, 'dataset', 'WT_ecoli.xlsx');
            modelDirectory = fullfile(repositoryRoot, 'model', 'Escherichia coli');
            experimentLocation = ...
                openmebius.domain.experiment.ExperimentLocation.fromDirectory( ...
                experimentDirectory);

            importService = ...
                openmebius.application.experiment.ExperimentImportService();

            fixture = struct( ...
                "Directory", experimentDirectory, ...
                "ImportResult", importService.importFiles( ...
                experimentLocation, ...
                string(sourceFile), ...
                string(modelDirectory)));

        end % importFixture

        function [infoTable, uptakeTable, tracerTable] = validExperimentTables(experiments)

            infoTable = experiments.getInfoTable();
            uptakeTable = experiments.getUptakeTable();
            tracerTable = experiments.getTracerTable();

            infoTable{1, 1} = 0.634525729817483;
            infoTable{1, 2} = 0;
            infoTable{1, 3} = 1;

            uptakeTable{1, 1} = 3.6405030802424;
            uptakeTable{1, 3} = 8.206603261;

            tracerTable{1, 1} = "12C2~1";
            tracerTable{1, 2} = "12C1~1";
            tracerTable{1, 3} = "[1]Glc~1";
            tracerTable{1, 4} = "12C1~1";

        end % validExperimentTables

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, 's');
            end

        end % removeDirectory

    end % methods

end % classdef
