classdef ExperimentComparisonBuilderTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentComparisonBuilderTest.sourcePath());

        end

    end

    methods (Test)

        function alignsFragmentRowsAndRemovesEmptyRows(testCase)

            collection = ExperimentComparisonBuilderTest.collection();
            builder = openmebius.domain.experiment ...
                .ExperimentComparisonBuilder();

            result = builder.buildMSNormalized(collection, "Frag");

            testCase.verifyTrue(result.IsAvailable);
            testCase.verifyEqual( ...
                string(result.Data.Properties.VariableNames), ...
                ["ExpA", "ExpB"]);
            testCase.verifyEqual( ...
                string(result.Data.Properties.RowNames), ...
                ["M0"; "M1"]);
            testCase.verifyEqual( ...
                result.Data{:,:}, ...
                [0.8, 0.7; 0.2, 0.3], ...
                AbsTol = 1e-12);

            mdvResult = builder.buildMDVBiomass(collection, "Frag");
            testCase.verifyEqual(mdvResult.Data, result.Data);

        end

        function marksInvalidEnrichmentValues(testCase)

            builder = openmebius.domain.experiment ...
                .ExperimentComparisonBuilder();

            result = builder.buildEnrichment( ...
                ExperimentComparisonBuilderTest.collection());

            testCase.verifyTrue(result.IsAvailable);
            testCase.verifyEqual( ...
                string(result.Data.Properties.RowNames), ...
                ["A"; "B"]);
            testCase.verifyEqual( ...
                result.ErrorMask, ...
                [false, false; true, true]);

        end

        function buildsSelectionTables(testCase)

            builder = openmebius.domain.experiment ...
                .ExperimentComparisonBuilder();

            result = builder.buildSelection( ...
                ExperimentComparisonBuilderTest.collection());

            testCase.verifyTrue(result.IsAvailable);
            testCase.verifyEqual( ...
                result.Selected{:,:}, ...
                [true, false; false, true]);
            testCase.verifyEqual( ...
                result.Available{:,:}, ...
                [true, true; true, false]);
            testCase.verifyEqual( ...
                string(result.Selected.Properties.RowNames), ...
                ["F1"; "F2"]);

        end

        function reportsMissingComparisonSource(testCase)

            collection = ExperimentComparisonBuilderTest.collection();
            data = collection.Data;
            data.ExpB_xlsx = rmfield( ...
                data.ExpB_xlsx, "tableSelection");
            collection.replaceData(data);
            builder = openmebius.domain.experiment ...
                .ExperimentComparisonBuilder();

            result = builder.buildSelection(collection);

            testCase.verifyFalse(result.IsAvailable);
            testCase.verifyEmpty(result.Selected);
            testCase.verifyNotEmpty(result.Message);

        end

    end

    methods (Static, Access = private)

        function collection = collection()

            location = openmebius.domain.experiment.ExperimentLocation ...
                .fromDirectory("experiment-root");
            collection = openmebius.domain.experiment ...
                .ExperimentCollection(location);
            collection.replaceFiles(["ExpA.xlsx", "ExpB.xlsx"]);
            collection.replaceData(struct( ...
                "ExpA_xlsx", ...
                ExperimentComparisonBuilderTest.experimentA(), ...
                "ExpB_xlsx", ...
                ExperimentComparisonBuilderTest.experimentB()));

        end

        function data = experimentA()

            fragment = table( ...
                [0.8; 0.2; 0], ...
                VariableNames = "Frag", ...
                RowNames = ["M0"; "M1"; "unused"]);
            enrichment = table( ...
                [0.2; 1.2], ...
                VariableNames = "Enrichment", ...
                RowNames = ["A"; "B"]);
            selection = table( ...
                [true; false], ...
                [true; true], ...
                VariableNames = ["Select", "Available"], ...
                RowNames = ["F1"; "F2"]);
            data = struct( ...
                "tableMSNormalized", fragment, ...
                "tableMDVBiomass", fragment, ...
                "tableEnrichment", enrichment, ...
                "tableSelection", selection);

        end

        function data = experimentB()

            fragment = table( ...
                [0.7; 0.3], ...
                VariableNames = "Frag", ...
                RowNames = ["M0"; "M1"]);
            enrichment = table( ...
                [0.3; nan], ...
                VariableNames = "Enrichment", ...
                RowNames = ["A"; "B"]);
            selection = table( ...
                [false; true], ...
                [true; false], ...
                VariableNames = ["Select", "Available"], ...
                RowNames = ["F1"; "F2"]);
            data = struct( ...
                "tableMSNormalized", fragment, ...
                "tableMDVBiomass", fragment, ...
                "tableEnrichment", enrichment, ...
                "tableSelection", selection);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
