classdef ExperimentMDVCalculatorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentMDVCalculatorTest.sourcePath());

        end

    end

    methods (Test)

        function validatesAndNormalizesBiomassMDV(testCase)

            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator(MDVTolerance = -1e-2);
            source = array2table( ...
                [1.005, 0.6; -0.005, 0.5], ...
                VariableNames = ["Accepted", "Invalid"]);

            [actual, errors] = calculator.validateBiomassMDV(source);

            testCase.verifyEqual(errors, [false, true]);
            testCase.verifyEqual( ...
                actual.Accepted, ...
                [1; 0], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(actual.Invalid, source.Invalid);

        end

        function createsSelectionFromModelAndValidMDV(testCase)

            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator();
            mdv = array2table( ...
                [0.8, 0.7; 0.2, 0.3], ...
                VariableNames = ["A", "C"]);
            modelMS = table( ...
                [true; false], ...
                VariableNames = "Used", ...
                RowNames = ["A"; "B"]);

            actual = calculator.createFragmentSelection( ...
                mdv, ...
                [false, true], ...
                modelMS, ...
                ["A"; "B"]);

            testCase.verifyEqual(actual.Select, [true; false]);
            testCase.verifyEqual(actual.Available, [true; false]);

        end

        function rejectsInconsistentTargetList(testCase)

            calculator = openmebius.domain.experiment ...
                .ExperimentMDVCalculator();
            mdv = array2table( ...
                [0.8; 0.2], ...
                VariableNames = "A");
            modelMS = table( ...
                true, ...
                VariableNames = "Used", ...
                RowNames = "A");

            testCase.verifyError( ...
                @() calculator.createFragmentSelection( ...
                mdv, ...
                false, ...
                modelMS, ...
                "Different"), ...
                "OpenMebius2:ExperimentMDVCalculator:" + ...
                "InvalidTargetList");

        end

        function derivedDataRequiresAlignedErrorFlags(testCase)

            testCase.verifyError( ...
                @() openmebius.domain.experiment.ExperimentDerivedData( ...
                MSNormalized = table(), ...
                MDV = table(), ...
                MDVBiomass = array2table(1, VariableNames = "A"), ...
                MDVErrors = false(1, 0), ...
                Enrichment = table(), ...
                EnrichmentErrors = false(0, 1), ...
                Selection = table()), ...
                "OpenMebius2:ExperimentDerivedData:InvalidMDVErrors");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
