classdef ExperimentMDVCalculationInputTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ExperimentMDVCalculationInputTest.sourcePath());

        end

    end

    methods (Test)

        function preservesCalculationSnapshot(testCase)

            info = table( ...
                0, ...
                1, ...
                VariableNames = ["ODi", "ODf"]);
            input = openmebius.domain.experiment ...
                .ExperimentMDVCalculationInput( ...
                ExperimentName = "exp1", ...
                RawMS = array2table(1, VariableNames = "A"), ...
                ExperimentInfo = info, ...
                AtomTable = table(), ...
                MSMetaboliteTable = table(), ...
                ModelMSTable = table(), ...
                TargetMetabolites = ["A", "B"]);

            testCase.verifyEqual(input.ExperimentName, "exp1");
            testCase.verifyEqual(input.ExperimentInfo, info);
            testCase.verifyEqual(input.TargetMetabolites, ["A"; "B"]);

        end

        function rejectsEmptyExperimentName(testCase)

            testCase.verifyError( ...
                @() ExperimentMDVCalculationInputTest.createInput( ...
                "", table( ...
                0, ...
                1, ...
                VariableNames = ["ODi", "ODf"])), ...
                "OpenMebius2:ExperimentMDVCalculationInput:" + ...
                "EmptyExperimentName");

        end

        function rejectsMultipleExperimentInfoRows(testCase)

            info = table( ...
                [0; 0], ...
                [1; 1], ...
                VariableNames = ["ODi", "ODf"]);

            testCase.verifyError( ...
                @() ExperimentMDVCalculationInputTest.createInput( ...
                "exp1", info), ...
                "OpenMebius2:ExperimentMDVCalculationInput:" + ...
                "InvalidExperimentInfo");

        end

    end

    methods (Static, Access = private)

        function input = createInput(experimentName, info)

            input = openmebius.domain.experiment ...
                .ExperimentMDVCalculationInput( ...
                ExperimentName = experimentName, ...
                RawMS = table(), ...
                ExperimentInfo = info, ...
                AtomTable = table(), ...
                MSMetaboliteTable = table(), ...
                ModelMSTable = table(), ...
                TargetMetabolites = strings(0, 1));

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
                "src");

        end

    end

end % classdef
