classdef FluxVariabilitySolverTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(FluxVariabilitySolverTest.sourcePath());

        end

    end

    methods (Test)

        function solvesBoundedEqualityProblem(testCase)

            solver = openmebius.mfa.FluxVariabilitySolver();

            result = solver.solve( ...
                [1, 1], ...
                10, ...
                [0; 0], ...
                [10; 10], ...
                [nan; nan]);

            testCase.verifyFalse(result.IsError);
            testCase.verifyGreaterThan(result.ExitFlag, 0);
            testCase.verifyEqual( ...
                result.LowerBounds, ...
                [0; 0], ...
                'AbsTol', 1e-10);
            testCase.verifyEqual( ...
                result.UpperBounds, ...
                [10; 10], ...
                'AbsTol', 1e-10);

        end

        function preservesLegacyReversePairTransformation(testCase)

            solver = openmebius.mfa.FluxVariabilitySolver();

            result = solver.solve( ...
                [1, 0], ...
                4, ...
                [0; 0], ...
                [10; 10], ...
                [nan; 1]);

            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual( ...
                result.LowerBounds, ...
                [2; -2], ...
                'AbsTol', 1e-10);
            testCase.verifyEqual( ...
                result.UpperBounds, ...
                [2; -2], ...
                'AbsTol', 1e-10);

        end

        function reportsInfeasibleProblem(testCase)

            solver = openmebius.mfa.FluxVariabilitySolver();

            result = solver.solve(1, 2, 0, 1, nan);

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(result.ExitFlag, -2);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                "FVA error. No feasible point was found.");
            testCase.verifyTrue(all(isnan(result.LowerBounds)));
            testCase.verifyTrue(all(isnan(result.UpperBounds)));

        end

        function rejectsMismatchedBoundaries(testCase)

            solver = openmebius.mfa.FluxVariabilitySolver();

            testCase.verifyError( ...
                @() solver.solve( ...
                [1, 1], ...
                1, ...
                0, ...
                [1; 1], ...
                [nan; nan]), ...
                "OpenMebius2:FVA:BoundaryDimensionMismatch");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
