classdef FluxVariabilityWorkflowTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(FluxVariabilityWorkflowTest.sourcePath());

        end

    end

    methods (Test)

        function buildsAndSolvesFluxVariabilityProblem(testCase)

            calculation = openmebius.mfa.FluxVariabilityResult( ...
                UpperBounds = 4 * ones(4, 1), ...
                LowerBounds = -4 * ones(4, 1), ...
                ExitFlag = 1);
            solver = helpers.FluxVariabilitySolverStub(calculation);
            observer = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.mfa.FluxVariabilityWorkflow( ...
                Solver = solver);

            result = workflow.run( ...
                helpers.FluxVariabilityModelStub(), ...
                0.2, ...
                "A", ...
                10, ...
                true, ...
                MessageReporter = ...
                @(level, message) observer.report(level, message));

            testCase.verifyEqual( ...
                result.RightHandSide, [0.2; 10; 0; 0]);
            testCase.verifyEqual( ...
                result.Problem.FreeConstraintIDs, "EX_A");
            testCase.verifyEqual( ...
                solver.EqualityMatrix, ...
                [1, 2, 0, 4; 9, 10, 0, 12]);
            testCase.verifyEqual( ...
                solver.EqualityRightHandSide, [0.2; 0]);
            testCase.verifyEqual(result.UpperBounds, 4 * ones(4, 1));
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(solver.CallCount, 1);
            testCase.verifyEqual(observer.Levels, "info");
            testCase.verifyEqual( ...
                observer.Messages, ...
                "FVA will not fix efflux-free reactions: EX_A.");

        end

        function reportsDefaultMaximumAndSolverFailure(testCase)

            calculation = openmebius.mfa.FluxVariabilityResult( ...
                UpperBounds = nan(4, 1), ...
                LowerBounds = nan(4, 1), ...
                ExitFlag = -2, ...
                ErrorMessage = "FVA failed.");
            solver = helpers.FluxVariabilitySolverStub(calculation);
            observer = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.mfa.FluxVariabilityWorkflow( ...
                Solver = solver);

            result = workflow.run( ...
                helpers.FluxVariabilityModelStub(), ...
                0.2, ...
                "A", ...
                0, ...
                false, ...
                MessageReporter = ...
                @(level, message) observer.report(level, message));

            testCase.verifyTrue( ...
                result.Problem.UsedDefaultMaximumEfflux);
            testCase.verifyEqual(result.Problem.MaximumEfflux, 1000);
            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual( ...
                observer.Levels, ["warning"; "error"]);
            testCase.verifyEqual( ...
                observer.Messages, ...
                ["Maximum efflux is not set or non-positive. " + ...
                "Using default value: 1000."; "FVA failed."]);

        end

        function forwardsCustomBoundsToProblemFactory(testCase)

            calculation = openmebius.mfa.FluxVariabilityResult( ...
                UpperBounds = 5 * ones(4, 1), ...
                LowerBounds = [0; -4; -4; 0], ...
                ExitFlag = 1);
            solver = helpers.FluxVariabilitySolverStub(calculation);
            workflow = openmebius.mfa.FluxVariabilityWorkflow( ...
                Solver = solver);

            result = workflow.run( ...
                helpers.FluxVariabilityModelStub(), ...
                0.2, ...
                "A", ...
                10, ...
                false, ...
                UseCustomBounds = true, ...
                LowerBounds = -4 * ones(4, 1), ...
                UpperBounds = 5 * ones(4, 1));

            testCase.verifyEqual( ...
                result.Problem.LowerBounds, [0; -4; -4; 0]);
            testCase.verifyEqual( ...
                result.Problem.UpperBounds, 5 * ones(4, 1));
            testCase.verifyEqual( ...
                solver.LowerBounds, result.Problem.LowerBounds);

        end

        function rejectsMismatchedWorkflowBounds(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa.FluxVariabilityWorkflowResult( ...
                RightHandSide = 0, ...
                Problem = [], ...
                UpperBounds = ones(2, 1), ...
                LowerBounds = 0, ...
                ExitFlag = 1), ...
                "OpenMebius2:FluxVariabilityWorkflow:" + ...
                "BoundSizeMismatch");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
