classdef FluxVariabilityProblemFactoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(FluxVariabilityProblemFactoryTest.sourcePath());

        end

    end

    methods (Test)

        function buildsFVAInputsAndRemovesFreeEffluxRows(testCase)

            factory = openmebius.mfa.FluxVariabilityProblemFactory();

            problem = factory.create( ...
                helpers.FluxVariabilityModelStub(), ...
                [0.2; 10; 0; 0], ...
                10, ...
                "A", ...
                true);

            testCase.verifyEqual( ...
                problem.EqualityMatrix, ...
                [1, 2, 0, 4; 9, 10, 0, 12]);
            testCase.verifyEqual( ...
                problem.EqualityRightHandSide, ...
                [0.2; 0]);
            testCase.verifyEqual( ...
                problem.LowerBounds, ...
                [0; -10000; -10000; 0]);
            testCase.verifyEqual( ...
                problem.UpperBounds, ...
                10000 * ones(4, 1));
            testCase.verifyEqual( ...
                problem.ReverseCounterpartIndices, ...
                [NaN; NaN; 2; NaN]);
            testCase.verifyEqual(problem.FreeConstraintIDs, "EX_A");
            testCase.verifyFalse(problem.UsedDefaultMaximumEfflux);

        end

        function usesDefaultForInvalidMaximumEfflux(testCase)

            factory = openmebius.mfa.FluxVariabilityProblemFactory();

            problem = factory.create( ...
                helpers.FluxVariabilityModelStub(), ...
                zeros(4, 1), ...
                NaN, ...
                "A", ...
                false);

            testCase.verifyTrue(problem.UsedDefaultMaximumEfflux);
            testCase.verifyEqual(problem.MaximumEfflux, 1000);
            testCase.verifyEqual(problem.UpperBounds, 1e6 * ones(4, 1));

        end

        function appliesCustomBoundsAndIrreversibility(testCase)

            factory = openmebius.mfa.FluxVariabilityProblemFactory();

            problem = factory.create( ...
                helpers.FluxVariabilityModelStub(), ...
                zeros(4, 1), ...
                10, ...
                "A", ...
                false, ...
                UseCustomBounds = true, ...
                LowerBounds = -4, ...
                UpperBounds = 5);

            testCase.verifyEqual( ...
                problem.LowerBounds, ...
                [0; -4; -4; 0]);
            testCase.verifyEqual( ...
                problem.UpperBounds, ...
                5 * ones(4, 1));

        end

        function rejectsCustomBoundsDimensionMismatch(testCase)

            factory = openmebius.mfa.FluxVariabilityProblemFactory();

            testCase.verifyError( ...
                @() factory.create( ...
                helpers.FluxVariabilityModelStub(), ...
                zeros(4, 1), ...
                10, ...
                "A", ...
                false, ...
                UseCustomBounds = true, ...
                LowerBounds = zeros(3, 1), ...
                UpperBounds = ones(3, 1)), ...
                "OpenMebius2:FluxVariabilityProblemFactory:" + ...
            "CustomBoundsDimensionMismatch");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
            'src');

        end

    end

end
