classdef FluxAnalysisRuntimeFactoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(FluxAnalysisRuntimeFactoryTest.sourcePath());

        end

    end

    methods (Test)

        function existingDirectoryCreatesExportRuntime(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                FluxAnalysisRuntimeFactoryTest ...
                .removeDirectory(resultDirectory));
            factory = FluxAnalysisRuntimeFactoryTest.createFactory();

            runtime = factory.create( ...
                resultDirectory, ...
                "batch-1", ...
                FluxAnalysisRuntimeFactoryTest.configuration());

            testCase.verifyFalse(runtime.IsError);
            testCase.verifyTrue(runtime.IsExport);
            testCase.verifyEqual( ...
                runtime.ResultLocation.Directory, resultDirectory);
            testCase.verifyEqual(runtime.ResultID, "batch-1");
            testCase.verifyEqual( ...
                runtime.ResultFilePath, ...
                fullfile(resultDirectory, "batch-1.h5"));
            testCase.verifyEqual( ...
                runtime.DirectoryMessageLevel, "Info");
            testCase.verifyClass( ...
                runtime.RunContext, ...
                'openmebius.application.analysis.MFAAnalysisRunContext');
            testCase.verifyClass( ...
                runtime.ResultSession, ...
                'openmebius.application.analysis.MFAResultSession');

        end

        function missingDirectoryDisablesExport(testCase)

            resultDirectory = string(tempname);
            factory = FluxAnalysisRuntimeFactoryTest.createFactory();

            runtime = factory.create( ...
                resultDirectory, ...
                "batch-1", ...
                FluxAnalysisRuntimeFactoryTest.configuration());

            testCase.verifyTrue(runtime.IsError);
            testCase.verifyFalse(runtime.IsExport);
            testCase.verifyEqual( ...
                runtime.DirectoryMessageLevel, "Error");
            testCase.verifyEqual( ...
                runtime.DirectoryMessage, ...
                "The directory " + resultDirectory + ...
                " does not exist.");

        end

        function failedRuntimeCannotEnableExport(testCase)

            dependencies = ...
                FluxAnalysisRuntimeFactoryTest.dependencies();
            session = openmebius.application.analysis ...
                .MFAResultSession( ...
                Coordinator = dependencies.MFAResultCoordinator);
            location = openmebius.domain.result.ResultLocation ...
                .fromDirectory(tempdir);

            testCase.verifyError( ...
                @() openmebius.application.analysis ...
                .FluxAnalysisRuntime( ...
                ResultLocation = location, ...
                ResultID = "batch-1", ...
                ResultFilePath = location.resultFile("batch-1"), ...
                IsExport = true, ...
                IsError = true, ...
                DirectoryMessage = "failed", ...
                DirectoryMessageLevel = "Error", ...
                Dependencies = dependencies, ...
                RunContext = dependencies.RunContext, ...
                ResultSession = session), ...
                "OpenMebius2:FluxAnalysisRuntime:" + ...
                "InconsistentExportState");

        end

    end

    methods (Static, Access = private)

        function factory = createFactory()

            factory = openmebius.application.analysis ...
                .FluxAnalysisRuntimeFactory( ...
                DependenciesFactory = ...
                    @(~, ~, ~) ...
                    FluxAnalysisRuntimeFactoryTest.dependencies());

        end

        function value = configuration()

            value = openmebius.application.analysis ...
                .FluxAnalysisComposition( ...
                Hdf5ResultRepository = ...
                    openmebius.infrastructure.result ...
                    .Hdf5ResultRepository());

        end

        function value = dependencies()

            value = struct;
            value.RunContext = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            value.MFAResultCoordinator = ...
                openmebius.infrastructure.result ...
                .MFAResultCoordinator(IsExport = false);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, 's');
            end

        end

    end

end
