classdef GeneralMessagePublisherTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(GeneralMessagePublisherTest.sourcePath());

        end

    end

    methods (Test)

        function reportWritesLogAndPublishesLegacyPayload(testCase)

            observer = helpers.AnalysisNotificationObserverStub();
            timestamp = datetime(2026, 7, 15, 19, 1, 2);
            publisher = openmebius.presentation.notification ...
                .GeneralMessagePublisher( ...
                LogWriter = @(text) observer.write(text), ...
                Clock = @() timestamp);

            notification = publisher.report( ...
                "warning", ...
                "Check the flux bounds.", ...
                @(eventData) observer.publish(eventData));

            testCase.verifyEqual(observer.EventCount, 1);
            testCase.verifyClass( ...
                observer.LastEvent, ...
                ['openmebius.presentation.notification.' ...
                'GeneralMessageEventData']);
            testCase.verifyEqual( ...
                observer.LastEvent.data.status, "warning");
            testCase.verifyEqual( ...
                observer.LastEvent.data.msg, ...
                "Check the flux bounds.");
            testCase.verifyEqual( ...
                observer.LastEvent.Notification, notification);
            testCase.verifyEqual( ...
                observer.LogText, ...
                "[2026-07-15 19:01:02]" + char(9) + ...
                "[WARNING]" + char(9) + ...
                "Check the flux bounds.");

        end

        function logThresholdDoesNotSuppressEvent(testCase)

            observer = helpers.AnalysisNotificationObserverStub();
            publisher = openmebius.presentation.notification ...
                .GeneralMessagePublisher( ...
                LogWriter = @(text) observer.write(text), ...
                LogLevel = "Error");

            publisher.report( ...
                "info", ...
                "Progress", ...
                @(eventData) observer.publish(eventData));

            testCase.verifyEqual(observer.EventCount, 1);
            testCase.verifyEmpty(observer.LogText);

        end

        function loggerAliasesAreNormalizedInPayload(testCase)

            observer = helpers.AnalysisNotificationObserverStub();
            publisher = openmebius.presentation.notification ...
                .GeneralMessagePublisher( ...
                LogWriter = @(text) observer.write(text));

            publisher.report( ...
                "completed", ...
                "Finished", ...
                @(eventData) observer.publish(eventData));

            testCase.verifyEqual( ...
                observer.LastEvent.data.status, "success");
            testCase.verifyTrue( ...
                contains(observer.LogText, "[SUCCESS]"));

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
