classdef GridSearchConfidenceIntervalSolverTest < ...
        matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(GridSearchConfidenceIntervalSolverTest.sourcePath());

        end

    end

    methods (Test)

        function automaticModeBisectsThenProfilesBothSides(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0.5], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Serial, ...
                PointCount = 4, ...
                IterationCount = 1, ...
                MaximumTrial = 3);
            evaluationFunction = ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateAutomaticProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.5], ...
                [5; 0.5], ...
                settings, ...
                evaluationFunction, ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 0.5);

            testCase.verifyEqual( ...
                result.ProfileData.FluxIndices, 2);
            testCase.verifyEqual( ...
                result.ProfileData.FixedFluxValues, ...
                reshape( ...
                [0.3125, 0.40625, 0.5, 0.59375, 0.6875], ...
                1, 5, 1), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.ProfileData.MinimumSumOfSquares, ...
                reshape( ...
                [1.125, 0.28125, 0, 0.28125, 1.125], ...
                1, 5, 1), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.LowerBounds, 0.326388888888889, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.UpperBounds, 0.673611111111111, ...
                AbsTol = 1e-12);

        end

        function fixedDeltaModeRetainsOddPointCounts(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0.5], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                IntervalMode = openmebius.mfa ...
                .GridSearchIntervalMode.FixedDelta, ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Serial, ...
                Delta = 0.25, ...
                PointCount = 3, ...
                IterationCount = 1);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.5], ...
                [5; 0.5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues), ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 0.5);

            testCase.verifyEqual( ...
                result.ProfileData.FixedFluxValues, ...
                reshape([0.25, 0.5, 0.75], 1, 3, 1), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.LowerBounds, 0.4375, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.UpperBounds, 0.5625, ...
                AbsTol = 1e-12);

        end

        function automaticModeRejectsOddPointCounts(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                PointCount = 3), ...
                "OpenMebius2:GridSearchConfidenceIntervalSettings:" + ...
                "AutomaticPointCountMustBeEven");

        end

        function settingsRejectInvalidWorkerCount(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings(WorkerCount = 0), ...
                "OpenMebius2:GridSearchConfidenceIntervalSettings:" + ...
                "InvalidPositiveInteger");

        end

        function reportsExecutionResources(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0.5], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                IntervalMode = openmebius.mfa ...
                .GridSearchIntervalMode.FixedDelta, ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Serial, ...
                Delta = 0.25, ...
                PointCount = 3, ...
                IterationCount = 1, ...
                WorkerCount = 12);
            observer = helpers.AnalysisMessageObserverStub();

            openmebius.mfa.GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.5], ...
                [5; 0.5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateProfilePoint( ...
                equalityMatrix, equalityRightHandSide, initialValues), ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 0.5, ...
                MessageReporter = @(level, message) ...
                observer.report(level, message));

            resourceMessage = observer.Messages(contains( ...
                observer.Messages, "Grid-search resources:"));
            testCase.verifyNumElements(resourceMessage, 1);
            testCase.verifyTrue(contains( ...
                resourceMessage, "physicalCores="));
            testCase.verifyTrue(contains( ...
                resourceMessage, "logicalProcessors="));
            testCase.verifyTrue(contains( ...
                resourceMessage, "configuredWorkers=12"));
            testCase.verifyTrue(contains(resourceMessage, "workers=1"));
            testCase.verifyTrue(contains(resourceMessage, "targetFluxes=1"));

        end

        function fixedDeltaModeExtendsWithSameDelta(testCase)

            [problem, ~] = ...
                GridSearchConfidenceIntervalSolverTest ...
                .extensionFixture();
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                IntervalMode = openmebius.mfa ...
                .GridSearchIntervalMode.FixedDelta, ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Serial, ...
                Delta = 0.5, ...
                PointCount = 3, ...
                IterationCount = 1, ...
                MinimumFluxRange = 0);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 5], ...
                [5; 5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateExtendedProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues, 0.1), ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 5);

            targets = reshape( ...
                result.ProfileData.FixedFluxValues, 1, []);
            testCase.verifyEqual(targets, 1.5:0.5:8.5);
            testCase.verifyGreaterThan( ...
                result.ProfileData.MinimumSumOfSquares(1, 1, 1), 1);
            testCase.verifyGreaterThan( ...
                result.ProfileData.MinimumSumOfSquares(1, end, 1), 1);

        end

        function narrowFVARangeSkipsGridSearch(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0.50000025], ...
                LowerBounds = [0; 0.5], ...
                UpperBounds = [10; 0.5000005], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Serial, ...
                IterationCount = 1, ...
                MinimumFluxRange = 1e-6);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.50000025], ...
                [5; 0.50000025], ...
                settings, ...
                @(~, ~, ~) GridSearchConfidenceIntervalSolverTest ...
                .unexpectedEvaluation(), ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 0.50000025);

            testCase.verifyEqual(result.LowerBounds, 0.5);
            testCase.verifyEqual(result.UpperBounds, 0.5000005);
            testCase.verifyTrue(all(isnan( ...
                result.ProfileData.MinimumSumOfSquares), "all"));

        end

        function automaticModeExtendsUntilThresholdIsExceeded(testCase)

            [problem, settings] = ...
                GridSearchConfidenceIntervalSolverTest ...
                .extensionFixture();

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 5], ...
                [5; 5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateExtendedProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues, 0.1), ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 5);

            expectedTargets = [ ...
                1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, ...
                5.5, 6, 6.5, 7, 7.5, 8, 8.5];
            testCase.verifyEqual( ...
                result.ProfileData.FixedFluxValues, ...
                reshape(expectedTargets, 1, [], 1), ...
                AbsTol = 1e-12);
            testCase.verifyGreaterThan( ...
                result.ProfileData.MinimumSumOfSquares(1, 1, 1), 1);
            testCase.verifyGreaterThan( ...
                result.ProfileData.MinimumSumOfSquares(1, end, 1), 1);
            testCase.verifyEqual( ...
                result.LowerBounds, 1.846153846153846, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.UpperBounds, 8.153846153846153, ...
                AbsTol = 1e-12);

        end

        function automaticModeExtendsToFVAEndsWithoutCrossing(testCase)

            [problem, settings] = ...
                GridSearchConfidenceIntervalSolverTest ...
                .extensionFixture();

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 5], ...
                [5; 5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateExtendedProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues, 0.01), ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 5);

            targets = reshape( ...
                result.ProfileData.FixedFluxValues, 1, []);
            testCase.verifyEqual(targets(1), 0);
            testCase.verifyEqual(targets(end), 10);
            testCase.verifyEqual(result.LowerBounds, 0);
            testCase.verifyEqual(result.UpperBounds, 10);

        end

        function mixedSkippedAndExtendedProfilesUseNaNPadding(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(3), ...
                RightHandSide = [5; 0.50000025; 5], ...
                LowerBounds = [0; 0.5; 0], ...
                UpperBounds = [10; 0.5000005; 10], ...
                IndependentMask = [false; true; true], ...
                BoundaryReactionMask = [false; true; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Serial, ...
                PointCount = 10, ...
                IterationCount = 1, ...
                MaximumTrial = 1, ...
                MinimumFluxRange = 1e-6);
            progress = helpers.AnalysisProgressRecorder();

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.50000025; 5], ...
                [5; 0.50000025; 5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateMixedProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues), ...
                zeros(0, 2), ...
                ProfileFluxIndices = [2; 3], ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = [0.50000025; 5], ...
                ProgressReporter = @(completed, total) ...
                progress.record(completed, total));

            fixedValues = result.ProfileData.FixedFluxValues;
            testCase.verifySize(fixedValues, [2, 15]);
            testCase.verifyEqual( ...
                fixedValues(1, 1:3), ...
                [0.5, 0.50000025, 0.5000005]);
            testCase.verifyTrue(all(isnan(fixedValues(1, 4:end))));
            testCase.verifyEqual( ...
                result.LowerBounds, [0.5; 1.846153846153846], ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.UpperBounds, [0.5000005; 8.153846153846153], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(progress.Completed, [0; 1]);
            testCase.verifyEqual(progress.Total, [1; 1]);

        end

        function parallelProfilesReportClientProgress(testCase)

            cleanup = onCleanup(@() ...
                GridSearchConfidenceIntervalSolverTest ...
                .deleteCurrentPool());
            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(3), ...
                RightHandSide = [5; 0.5; 0.5], ...
                LowerBounds = [0; 0; 0], ...
                UpperBounds = [10; 1; 1], ...
                IndependentMask = [false; true; true], ...
                BoundaryReactionMask = [false; true; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                IntervalMode = openmebius.mfa ...
                .GridSearchIntervalMode.FixedDelta, ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Parallel, ...
                Delta = 0.25, ...
                PointCount = 3, ...
                IterationCount = 1, ...
                WorkerCount = 2, ...
                MinimumFluxRange = 0);
            progress = helpers.AnalysisProgressRecorder();

            openmebius.mfa.GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.5; 0.5], ...
                [5; 0.5; 0.5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateParallelProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues), ...
                zeros(0, 2), ...
                ProfileFluxIndices = [2; 3], ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = [0.5; 0.5], ...
                ProgressReporter = @(completed, total) ...
                progress.record(completed, total));

            testCase.verifyEqual(progress.Completed, (0:2)');
            testCase.verifyEqual(progress.Total, repmat(2, 3, 1));

        end

    end

    methods (Static, Access = private)

        function [problem, settings] = extensionFixture()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 5], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 10], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                ExecutionMode = openmebius.mfa ...
                .GridSearchExecutionMode.Serial, ...
                PointCount = 10, ...
                IterationCount = 1, ...
                MaximumTrial = 1, ...
                MinimumFluxRange = 0);

        end

        function result = unexpectedEvaluation()

            error( ...
                "GridSearchConfidenceIntervalSolverTest:" + ...
                "UnexpectedEvaluation", ...
                "Grid search should have been skipped.");

        end

        function result = evaluateExtendedProfilePoint( ...
                ~, equalityRightHandSide, initialValues, scale)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                scale * (equalityRightHandSide - 5) ^ 2, ...
                ExitFlag = 1);

        end

        function result = evaluateMixedProfilePoint( ...
                ~, equalityRightHandSide, initialValues)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; 0.50000025; equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                0.1 * (equalityRightHandSide - 5) ^ 2, ...
                ExitFlag = 1);

        end

        function result = evaluateAutomaticProfilePoint( ...
                ~, equalityRightHandSide, initialValues)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                32 * (equalityRightHandSide - 0.5) ^ 2, ...
                ExitFlag = 1);

        end

        function result = evaluateProfilePoint( ...
                ~, equalityRightHandSide, initialValues)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                64 * (equalityRightHandSide - 0.5) ^ 2, ...
                ExitFlag = 1);

        end

        function result = evaluateParallelProfilePoint( ...
                ~, equalityRightHandSide, initialValues)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; equalityRightHandSide; ...
                equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                64 * (equalityRightHandSide - 0.5) ^ 2, ...
                ExitFlag = 1);

        end

        function deleteCurrentPool()

            pool = gcp("nocreate");

            if ~isempty(pool)
                delete(pool);
            end

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
