classdef GridSearchProfileDataTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(GridSearchProfileDataTest.sourcePath());

        end % method addSourcePath

    end % methods (TestMethodSetup)

    methods (Test)

        function constructMultipleFluxProfiles(testCase)

            fixedFluxValues = cat(3, ...
                [1, 2, 3; ...
                 10, 20, 30], ...
                [0.5, 1, 1.5; ...
                 5, 10, 15]);

            minimumSumOfSquares = cat(3, ...
                [4, 1, 5; ...
                 8, 2, 9], ...
                [6, 1.5, 7; ...
                 10, 3, 11]);

            profile = openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = [1; 2], ...
                FixedFluxValues = fixedFluxValues, ...
                MinimumSumOfSquares = minimumSumOfSquares);

            testCase.verifyEqual(profile.FluxIndices, [1; 2]);
            testCase.verifyEqual( ...
                profile.FixedFluxValues, fixedFluxValues);
            testCase.verifyEqual( ...
                profile.MinimumSumOfSquares, ...
                minimumSumOfSquares);
            testCase.verifySize( ...
                profile.FixedFluxValues, [2, 3, 2]);

        end % method constructMultipleFluxProfiles

        function rejectsMismatchedProfileSizes(testCase)

            constructor = @() ...
                openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = [1; 2], ...
                FixedFluxValues = zeros(2, 3, 2), ...
                MinimumSumOfSquares = zeros(2, 4, 2));

            testCase.verifyError( ...
                constructor, ...
            "OpenMebius2:GridSearchProfileData:InvalidInput");

        end % method rejectsMismatchedProfileSizes

        function rejectsFluxCountMismatch(testCase)

            constructor = @() ...
                openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = [1; 2; 3], ...
                FixedFluxValues = zeros(2, 3, 2), ...
                MinimumSumOfSquares = zeros(2, 3, 2));

            testCase.verifyError( ...
                constructor, ...
            "OpenMebius2:GridSearchProfileData:InvalidInput");

        end % method rejectsFluxCountMismatch

        function rejectsDuplicateFluxIndices(testCase)

            constructor = @() ...
                openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = [1; 1], ...
                FixedFluxValues = zeros(2, 3, 2), ...
                MinimumSumOfSquares = zeros(2, 3, 2));

            testCase.verifyError( ...
                constructor, ...
            "OpenMebius2:GridSearchProfile:InvalidFluxIndices");

        end % method rejectsDuplicateFluxIndices

        function rejectsNonPositiveFluxIndices(testCase)

            constructor = @() ...
                openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = [0; 2], ...
                FixedFluxValues = zeros(2, 3, 2), ...
                MinimumSumOfSquares = zeros(2, 3, 2));

            testCase.verifyError( ...
                constructor, ...
            "OpenMebius2:GridSearchProfile:InvalidFluxIndices");

        end % method rejectsNonPositiveFluxIndices

        function rejectsNonIntegerFluxIndices(testCase)

            constructor = @() ...
                openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = [1; 2.5], ...
                FixedFluxValues = zeros(2, 3, 2), ...
                MinimumSumOfSquares = zeros(2, 3, 2));

            testCase.verifyError( ...
                constructor, ...
            "OpenMebius2:GridSearchProfile:InvalidFluxIndices");

        end % method rejectsNonIntegerFluxIndices

    end % methods (Test)

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename("fullpath"))), ...
            "src");

        end % method sourcePath

    end % methods (Static, Access = private)

end % classdef
