classdef GridSearchConfidenceIntervalSolverTest < ...
        matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(GridSearchConfidenceIntervalSolverTest.sourcePath());

        end

    end

    methods (Test)

        function profilesSelectedFluxAndInterpolatesThreshold(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0.5], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                ExecutionMode = openmebius.mfa ...
                    .GridSearchExecutionMode.Serial, ...
                PointCount = 3, ...
                IterationCount = 1);
            evaluationFunction = ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.5], ...
                [5; 0.5], ...
                settings, ...
                evaluationFunction, ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                InitialIndependentValues = 0.5);

            testCase.verifyEqual( ...
                result.ProfileData.FluxIndices, 2);
            testCase.verifyEqual( ...
                result.LowerBounds, 0.48, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.UpperBounds, 0.52, ...
                AbsTol = 1e-12);

        end

    end

    methods (Static, Access = private)

        function result = evaluateProfilePoint( ...
                ~, equalityRightHandSide, initialValues)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                    100 * (equalityRightHandSide - 0.5) ^ 2, ...
                ExitFlag = 1);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
