classdef GridSearchConfidenceIntervalSolverTest < ...
        matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(GridSearchConfidenceIntervalSolverTest.sourcePath());

        end

    end

    methods (Test)

        function automaticModeBisectsThenProfilesBothSides(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0.5], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                ExecutionMode = openmebius.mfa ...
                    .GridSearchExecutionMode.Serial, ...
                PointCount = 4, ...
                IterationCount = 1, ...
                MaximumTrial = 3);
            evaluationFunction = ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateAutomaticProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.5], ...
                [5; 0.5], ...
                settings, ...
                evaluationFunction, ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 0.5);

            testCase.verifyEqual( ...
                result.ProfileData.FluxIndices, 2);
            testCase.verifyEqual( ...
                result.ProfileData.FixedFluxValues, ...
                reshape( ...
                    [0.3125, 0.40625, 0.5, 0.59375, 0.6875], ...
                    1, 5, 1), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.ProfileData.MinimumSumOfSquares, ...
                reshape( ...
                    [1.125, 0.28125, 0, 0.28125, 1.125], ...
                    1, 5, 1), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.LowerBounds, 0.326388888888889, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.UpperBounds, 0.673611111111111, ...
                AbsTol = 1e-12);

        end

        function fixedDeltaModeRetainsOddPointCounts(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0.5], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                IntervalMode = openmebius.mfa ...
                    .GridSearchIntervalMode.FixedDelta, ...
                ExecutionMode = openmebius.mfa ...
                    .GridSearchExecutionMode.Serial, ...
                Delta = 0.25, ...
                PointCount = 3, ...
                IterationCount = 1);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver().solve( ...
                problem, ...
                [5; 0.5], ...
                [5; 0.5], ...
                settings, ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialValues) ...
                GridSearchConfidenceIntervalSolverTest ...
                .evaluateProfilePoint( ...
                equalityMatrix, equalityRightHandSide, ...
                initialValues), ...
                zeros(0, 2), ...
                ProfileFluxIndices = 2, ...
                ObjectiveThreshold = 1, ...
                BestObjective = 0, ...
                InitialIndependentValues = 0.5);

            testCase.verifyEqual( ...
                result.ProfileData.FixedFluxValues, ...
                reshape([0.25, 0.5, 0.75], 1, 3, 1), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.LowerBounds, 0.4375, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.UpperBounds, 0.5625, ...
                AbsTol = 1e-12);

        end

        function automaticModeRejectsOddPointCounts(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                PointCount = 3), ...
                "OpenMebius2:GridSearchConfidenceIntervalSettings:" + ...
            "AutomaticPointCountMustBeEven");

        end

    end

    methods (Static, Access = private)

        function result = evaluateAutomaticProfilePoint( ...
                ~, equalityRightHandSide, initialValues)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                    32 * (equalityRightHandSide - 0.5) ^ 2, ...
                ExitFlag = 1);

        end

        function result = evaluateProfilePoint( ...
                ~, equalityRightHandSide, initialValues)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = initialValues, ...
                Flux = [5; equalityRightHandSide], ...
                MDV = zeros(0, 1), ...
                ObjectiveValue = ...
                    64 * (equalityRightHandSide - 0.5) ^ 2, ...
                ExitFlag = 1);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
