classdef Hdf5ResultRepositoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourceToPath(~)

            addpath(Hdf5ResultRepositoryTest.sourcePath());

        end

    end

    methods (Test)

        function writeDatasetCreatesHdf5Dataset(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result.Hdf5ResultRepository();
            pathFile = fullfile(resultDirectory, "result.h5");
            values = [1.0; 2.0; 3.0];

            [isSuccess, msg] = repository.writeDataset( ...
                pathFile, ...
                "/flux", ...
                values);

            testCase.verifyTrue(isSuccess, msg);
            testCase.verifyEqual(h5read(pathFile, "/flux"), values);

            clear cleanup

        end

        function readResultDataReadsHeaderWithoutOptionalSections(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result ...
                .Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            resultId = "batch-read";
            pathFile = resultLocation.resultFile(resultId);

            [isSuccess, msg] = repository.writeDataset( ...
                pathFile, ...
                "/ID", ...
                resultId, ...
                DataType = "string");
            testCase.assertTrue(isSuccess, msg);

            [isSuccess, msg] = repository.writeDataset( ...
                pathFile, ...
                "/status", ...
                int8([0; 0; 0; 0]), ...
                DataType = "int8");
            testCase.assertTrue(isSuccess, msg);

            data = repository.readResultData( ...
                resultLocation, ...
                resultId, ...
                ReadStatus = false(1, 4));

            testCase.verifyEqual(string(data.ID), resultId);
            testCase.verifyEqual( ...
                logical(data.status(:).'), ...
                false(1, 4));

            clear cleanup

        end

        function readResultDataRejectsMissingFile(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result ...
                .Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);

            testCase.verifyError( ...
                @() repository.readResultData( ...
                resultLocation, "missing"), ...
                "OpenMebius2:Hdf5ResultRepository:ResultFileNotFound");

            clear cleanup

        end

        function readsOptimizationStateWithoutFluxResults(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));
            repository = openmebius.infrastructure.result ...
                .Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            resultId = "batch-optimization";
            pathFile = resultLocation.resultFile(resultId);
            paths = ["/status", "/RSS", "/threshold"];
            values = {int8([0; 1; 0; 0]), [1; 2; 3], 2.5};
            types = ["int8", "double", "double"];

            for index = 1:numel(paths)
                [isSuccess, message] = repository.writeDataset( ...
                    pathFile, paths(index), values{index}, ...
                    DataType = types(index));
                testCase.assertTrue(isSuccess, message);
            end

            data = repository.readOptimizationState( ...
                resultLocation, resultId);

            testCase.verifyEqual(data.RSS, [1; 2; 3]);
            testCase.verifyEqual(data.threshold, 2.5);

            clear cleanup

        end

        function roundTripsGridSearchConfidenceInterval(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));
            repository = openmebius.infrastructure.result ...
                .Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            resultId = "batch-grid-search";
            pathFile = resultLocation.resultFile(resultId);
            basePaths = [ ...
                "/ID"; ...
                "/model/modelID"; ...
                "/model/modelReaction"; ...
                "/fluxVariability/fluxUBFwd"; ...
                "/fluxVariability/fluxLBFwd"; ...
                "/RSSIndex"; ...
                "/fluxResult/0001/fluxFwd"];
            baseValues = { ...
                resultId; ...
                "R1"; ...
                "First reaction"; ...
                [2; 3]; ...
                [0; 1]; ...
                int32(1); ...
                [1; 2]};
            baseTypes = [ ...
                "string"; "string"; "string"; ...
                "double"; "double"; "int32"; "double"];

            for index = 1:numel(basePaths)
                [isSuccess, message] = repository.writeDataset( ...
                    pathFile, ...
                    basePaths(index), ...
                    baseValues{index}, ...
                    DataType = baseTypes(index));
                testCase.assertTrue(isSuccess, message);
            end

            profile = openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = 1, ...
                FixedFluxValues = cat(3, [0.5, 1], [0.5, 1]), ...
                MinimumSumOfSquares = cat(3, [6, 4], [5, 3]));
            output = struct( ...
                profile = profile, ...
                time = 2.5, ...
                bestObjective = 2, ...
                objectiveThreshold = 5.5);
            settings = openmebius.mfa.ConfidenceIntervalSettings( ...
                Enabled = true, ...
                Method = openmebius.mfa ...
                .ConfidenceIntervalMethod.GridSearch);
            writer = openmebius.infrastructure.result ...
                .MFAResultCheckpointWriter(Repository = repository);
            checkpoint = writer ...
                .createGridSearchConfidenceIntervalCheckpoint( ...
                0.6, 1.4, settings, output, ["R1"; "biomass"]);

            [isSuccess, message] = ...
                writer.writeGridSearchConfidenceInterval( ...
                pathFile, checkpoint, [1, 1, 1, 0]);
            testCase.assertTrue(isSuccess, message);

            data = repository.readConfidenceInterval( ...
                resultLocation, resultId, "R1");

            testCase.verifyEqual(data.CI.algorithm, "Grid search");
            testCase.verifyEqual( ...
                data.CI.gridSearch.fluxIndices, 1);
            testCase.verifyEqual( ...
                data.CI.gridSearch.reactionIDs, "R1");
            testCase.verifyEqual( ...
                data.CI.gridSearch.fixedFlux, [0.5, 1]);
            testCase.verifyEqual( ...
                data.CI.gridSearch.RSS, ...
                cat(3, [6, 4], [5, 3]));
            testCase.verifyEqual( ...
                data.CI.gridSearch.minimumRSS, [5, 3]);
            testCase.verifyEqual( ...
                data.CI.gridSearch.bestObjective, 2);
            testCase.verifyEqual( ...
                data.CI.gridSearch.objectiveThreshold, 5.5);
            testCase.verifyEqual( ...
                data.CI.gridSearch.maximumTrial, 15);
            testCase.verifyEqual( ...
                data.CI.gridSearch.workerCount, 8);
            testCase.verifyEqual( ...
                data.CI.gridSearch.minimumFluxRange, 1e-6);
            testCase.verifyEqual(data.fluxLB, [0.6; NaN]);
            testCase.verifyEqual(data.fluxUB, [1.4; NaN]);

            resultData = repository.readResultData( ...
                resultLocation, ...
                resultId, ...
                ReadStatus = [false, false, true, false]);
            testCase.verifyEqual( ...
                resultData.CI.algorithm, "Grid search");
            testCase.verifyEqual( ...
                resultData.CI.gridSearch.minimumRSS, [5, 3]);

            clear cleanup

        end

        function assertResultDirectoryRejectsMissingDirectory(testCase)

            repository = openmebius.infrastructure.result.Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(fullfile(tempdir, "missing-openmebius-hdf5-result"));

            testCase.verifyError( ...
                @() repository.assertResultDirectory(resultLocation), ...
                "OpenMebius2:Hdf5ResultRepository:DirectoryNotFound");

        end

        function writesReproducibilityMetadata(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result.Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            metadata = struct( ...
                'schemaVersion', 1, ...
                'batchId', "bat_001", ...
                'batchName', "My batch", ...
                'batchDescription', "My description", ...
                'contentHash', "sha256:content", ...
                'contentHashVersion', 1, ...
                'configJson', "{}", ...
                'openMebius2Version', "2.4.3", ...
                'matlabRelease', "R2026a", ...
                'matlabVersion', "26.1", ...
                'toolboxesJson', "[]", ...
                'modelFileName', "model.xlsx", ...
                'modelSha256', "model-hash", ...
                'experimentNames', ["exp-a"; "exp-b"], ...
                'experimentFileNames', ["exp-a.xlsx"; "exp-b.xlsx"], ...
                'experimentSha256', ["hash-a"; "hash-b"], ...
                'randomType', "twister", ...
                'randomSeed', uint32(42), ...
                'randomState', uint32([1; 2; 3]), ...
                'startedAtUtc', "2026-07-14T00:00:00.000Z");
            pathFile = resultLocation.resultFile(metadata.batchId);

            [isSuccess, msg] = repository.writeAnalysisMetadata( ...
                pathFile, ...
                metadata);

            testCase.verifyTrue(isSuccess, msg);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/batch/id")), ...
                metadata.batchId);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/batch/name")), ...
                metadata.batchName);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/batch/description")), ...
                metadata.batchDescription);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/batch/contentHash")), ...
                metadata.contentHash);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/software/openMebius2Version")), ...
                metadata.openMebius2Version);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/model/sha256")), ...
                metadata.modelSha256);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/experiments/sha256")), ...
                metadata.experimentSha256);
            testCase.verifyEqual( ...
                h5read(pathFile, "/metadata/random/state"), ...
                metadata.randomState);

            [isSuccess, msg] = repository.writeRunCompletion( ...
                pathFile, ...
                "2026-07-14T00:01:00.000Z", ...
                false, ...
                false);

            testCase.verifyTrue(isSuccess, msg);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/run/finishedAtUtc")), ...
                "2026-07-14T00:01:00.000Z");

            snapshot = repository.readBatchSnapshot( ...
                resultLocation, metadata.batchId);
            testCase.verifyEqual(snapshot.ID, metadata.batchId);
            testCase.verifyEqual(snapshot.Name, metadata.batchName);
            testCase.verifyEqual( ...
                snapshot.Experiments, metadata.experimentNames);
            testCase.verifyEqual( ...
                snapshot.Description, metadata.batchDescription);
            testCase.verifyEqual(snapshot.ConfigJson, metadata.configJson);
            testCase.verifyEqual(snapshot.ContentHash, metadata.contentHash);
            testCase.verifyEqual(snapshot.Status, "finished");

            clear cleanup

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile(Hdf5ResultRepositoryTest.repositoryRoot(), "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, "s");
            end

        end

    end

end
