classdef Hdf5ResultRepositoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourceToPath(~)

            addpath(Hdf5ResultRepositoryTest.sourcePath());

        end

    end

    methods (Test)

        function writeDatasetCreatesHdf5Dataset(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result.Hdf5ResultRepository();
            pathFile = fullfile(resultDirectory, "result.h5");
            values = [1.0; 2.0; 3.0];

            [isSuccess, msg] = repository.writeDataset( ...
                pathFile, ...
                "/flux", ...
                values);

            testCase.verifyTrue(isSuccess, msg);
            testCase.verifyEqual(h5read(pathFile, "/flux"), values);

            clear cleanup

        end

        function readResultDataReadsHeaderWithoutOptionalSections(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result ...
                .Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            resultId = "batch-read";
            pathFile = resultLocation.resultFile(resultId);

            [isSuccess, msg] = repository.writeDataset( ...
                pathFile, ...
                "/ID", ...
                resultId, ...
                DataType = "string");
            testCase.assertTrue(isSuccess, msg);

            [isSuccess, msg] = repository.writeDataset( ...
                pathFile, ...
                "/status", ...
                int8([0; 0; 0; 0]), ...
                DataType = "int8");
            testCase.assertTrue(isSuccess, msg);

            data = repository.readResultData( ...
                resultLocation, ...
                resultId, ...
                ReadStatus = false(1, 4));

            testCase.verifyEqual(string(data.ID), resultId);
            testCase.verifyEqual( ...
                logical(data.status(:).'), ...
                false(1, 4));

            clear cleanup

        end

        function readResultDataRejectsMissingFile(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result ...
                .Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);

            testCase.verifyError( ...
                @() repository.readResultData( ...
                resultLocation, "missing"), ...
                "OpenMebius2:Hdf5ResultRepository:ResultFileNotFound");

            clear cleanup

        end

        function assertResultDirectoryRejectsMissingDirectory(testCase)

            repository = openmebius.infrastructure.result.Hdf5ResultRepository();
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(fullfile(tempdir, "missing-openmebius-hdf5-result"));

            testCase.verifyError( ...
                @() repository.assertResultDirectory(resultLocation), ...
                "OpenMebius2:Hdf5ResultRepository:DirectoryNotFound");

        end

        function writesReproducibilityMetadata(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                Hdf5ResultRepositoryTest.removeDirectory(resultDirectory));

            repository = openmebius.infrastructure.result.Hdf5ResultRepository();
            pathFile = fullfile(resultDirectory, "result.h5");
            metadata = struct( ...
                'schemaVersion', 1, ...
                'batchId', "bat_001", ...
                'contentHash', "sha256:content", ...
                'contentHashVersion', 1, ...
                'configJson', "{}", ...
                'openMebius2Version', "2.4.3", ...
                'matlabRelease', "R2026a", ...
                'matlabVersion', "26.1", ...
                'toolboxesJson', "[]", ...
                'modelFileName', "model.xlsx", ...
                'modelSha256', "model-hash", ...
                'experimentNames', ["exp-a"; "exp-b"], ...
                'experimentFileNames', ["exp-a.xlsx"; "exp-b.xlsx"], ...
                'experimentSha256', ["hash-a"; "hash-b"], ...
                'randomType', "twister", ...
                'randomSeed', uint32(42), ...
                'randomState', uint32([1; 2; 3]), ...
                'startedAtUtc', "2026-07-14T00:00:00.000Z");

            [isSuccess, msg] = repository.writeAnalysisMetadata( ...
                pathFile, ...
                metadata);

            testCase.verifyTrue(isSuccess, msg);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/batch/id")), ...
                metadata.batchId);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/batch/contentHash")), ...
                metadata.contentHash);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/software/openMebius2Version")), ...
                metadata.openMebius2Version);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/model/sha256")), ...
                metadata.modelSha256);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/experiments/sha256")), ...
                metadata.experimentSha256);
            testCase.verifyEqual( ...
                h5read(pathFile, "/metadata/random/state"), ...
                metadata.randomState);

            [isSuccess, msg] = repository.writeRunCompletion( ...
                pathFile, ...
                "2026-07-14T00:01:00.000Z", ...
                false, ...
                false);

            testCase.verifyTrue(isSuccess, msg);
            testCase.verifyEqual( ...
                string(h5read(pathFile, "/metadata/run/finishedAtUtc")), ...
                "2026-07-14T00:01:00.000Z");

            clear cleanup

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile(Hdf5ResultRepositoryTest.repositoryRoot(), "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, "s");
            end

        end

    end

end
