classdef InitialFluxSeedBoundsPolicyTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(InitialFluxSeedBoundsPolicyTest.sourcePath());

        end

    end

    methods (Test)

        function intersectsMeasurementRangesWithPhysicalBounds(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = [1; 3], ...
                ExperimentalValues = [10; 60], ...
                StandardDeviations = [2; 5]);

            [lowerBounds, upperBounds] = policy.apply( ...
                [0; -100; 5], ...
                [100; 100; 50], ...
                profile);

            testCase.verifyEqual(lowerBounds, [4; -100; 45]);
            testCase.verifyEqual(upperBounds, [16; 100; 50]);

        end

        function acceptsCustomSigmaMultiplier(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 1, ...
                ExperimentalValues = 20, ...
                StandardDeviations = 2);

            [lowerBounds, upperBounds] = policy.apply( ...
                0, 100, profile, SigmaMultiplier = 5);

            testCase.verifyEqual(lowerBounds, 10);
            testCase.verifyEqual(upperBounds, 30);

        end

        function preservesBoundsWithoutFreeEffluxMeasurements(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile();
            physicalLowerBounds = [-10; 0];
            physicalUpperBounds = [10; 20];

            [lowerBounds, upperBounds] = policy.apply( ...
                physicalLowerBounds, ...
                physicalUpperBounds, ...
                profile);

            testCase.verifyEqual(lowerBounds, physicalLowerBounds);
            testCase.verifyEqual(upperBounds, physicalUpperBounds);

        end

        function rejectsMeasurementRangeOutsidePhysicalBounds(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 1, ...
                ExperimentalValues = 20, ...
                StandardDeviations = 1);

            testCase.verifyError( ...
                @() policy.apply(0, 10, profile), ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
            "EmptyIntersection");

        end

        function rejectsInvalidReactionIndex(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 3, ...
                ExperimentalValues = 5, ...
                StandardDeviations = 1);

            testCase.verifyError( ...
                @() policy.apply([0; 0], [10; 10], profile), ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
            "InvalidReactionIndex");

        end

        function rejectsReversibleFreeEfflux(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 1, ...
                ExperimentalValues = 5, ...
                StandardDeviations = 1);

            testCase.verifyError( ...
                @() policy.apply( ...
                [0; 0], ...
                [10; 10], ...
                profile, ...
                ReversibleReactionIndices = [1, 2]), ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
            "ReversibleEffluxNotSupported");

        end

        function allowsUnrelatedReversibleReaction(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 1, ...
                ExperimentalValues = 5, ...
                StandardDeviations = 1);

            [lowerBounds, upperBounds] = policy.apply( ...
                zeros(3, 1), ...
                10 * ones(3, 1), ...
                profile, ...
                ReversibleReactionIndices = [2, 3]);

            testCase.verifyEqual(lowerBounds, [2; 0; 0]);
            testCase.verifyEqual(upperBounds, [8; 10; 10]);

        end

        function rejectsInvalidSigmaMultiplier(testCase)

            policy = openmebius.mfa.InitialFluxSeedBoundsPolicy();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 1, ...
                ExperimentalValues = 5, ...
                StandardDeviations = 1);
            errorID = "OpenMebius2:InitialFluxSeedBounds:" + ...
                "InvalidSigmaMultiplier";

            for multiplier = [0, -1, Inf, NaN]
                testCase.verifyError( ...
                    @() policy.apply( ...
                    0, 10, profile, ...
                    SigmaMultiplier = multiplier), ...
                    errorID);
            end

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
            'src');

        end

    end

end
