classdef InitialFluxWorkflowContractTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(InitialFluxWorkflowContractTest.sourcePath());

        end

    end

    methods (Test)

        function inputOwnsTypedSettings(testCase)

            input = InitialFluxWorkflowContractTest.createInput();

            testCase.verifyClass( ...
                input.Settings, 'openmebius.mfa.InitialFluxSettings');
            testCase.verifyEqual(input.IterationCount, 2);
            testCase.verifyEqual(input.RightHandSide, [5; 0]);
            testCase.verifyEqual(input.scoringSubstrateEMUs(false), {1});
            testCase.verifyClass( ...
                input.EffluxProfile, ...
                'openmebius.mfa.EffluxPerturbationProfile');
            testCase.verifyEmpty(input.ReversibleReactionIndices);

        end

        function inputRejectsMismatchedBounds(testCase)

            testCase.verifyError( ...
                @() InitialFluxWorkflowContractTest.createInput( ...
                UpperBounds = 1), ...
                "OpenMebius2:InitialFluxInput:DimensionMismatch");

        end

        function resultSeparatesCancellationFromFailure(testCase)

            result = openmebius.mfa.InitialFluxWorkflowResult.canceled();

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyFalse(result.IsError);

        end

        function failedResultRequiresMessage(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa.InitialFluxWorkflowResult( ...
                IsError = true), ...
                "OpenMebius2:InitialFluxResult:MissingErrorMessage");

        end

        function workflowHandlesRandomGenerationFailure(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                zeros(2, 0), ...
                zeros(2, 0), ...
                IsError = true, ...
                ErrorMessage = "generation failed");
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput(), ...
                Method = "random");

            testCase.verifyTrue(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.ErrorMessage, "generation failed");
            testCase.verifyEqual(generator.GenerationCount, 1);

        end

        function workflowRejectsEmptyGeneratedCandidates(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                zeros(2, 0), zeros(2, 0));
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput(), ...
                Method = "random");

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                "Initial point generation produced no candidates.");
            testCase.verifyEqual(generator.GenerationCount, 30);

        end

        function retriesMissingFeasiblePointThirtyTimes(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                zeros(2, 0), ...
                zeros(2, 0), ...
                IsError = true, ...
                ErrorMessage = ...
                "Hit-and-Run: no feasible initial point was found.");
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput());

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(generator.GenerationCount, 30);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                "Hit-and-Run: no feasible initial point was found.");

        end

        function workflowReturnsCanceledResultWithoutError(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 0.5], ...
                [5; 0.5], ...
                IsCanceled = true);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput());

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyFalse(result.IsError);

        end

        function usesRestrictedProblemOnlyForInitialSampling(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 0.5], [5; 0.5]);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 1, ...
                EffluxProfile = profile), ...
                Method = "random", ...
                IterationRate = 1);

            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual( ...
                generator.LastProblem.LowerBounds, [0; 0.2], ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                generator.LastProblem.UpperBounds, [10; 0.8], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 1]);

        end

        function resamplesWhenTooFewValidCandidates(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5, 5; 0.8, 1.2], ...
                [5, 5; 0.8, 1.2], ...
                RetryFluxes = [5, 5; 0.7, 1.3], ...
                RetryRightHandSides = [5, 5; 0.7, 1.3]);
            messages = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 2, ...
                UpperBounds = [10; 2]), ...
                Method = "random", ...
                IterationRate = 1, ...
                MessageReporter = @(level, message) ...
                messages.report(level, message));

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(generator.GenerationCount, 2);
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 2]);
            testCase.verifyEqual( ...
                result.Fluxes(:, 1:2), [5, 5; 0.8, 0.7]);
            testCase.verifyTrue(any(contains( ...
                messages.Messages, "sampling initial points again")));

        end

        function rejectsTooFewValidCandidatesAfterRetry(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5, 5; 0.8, 1.2], ...
                [5, 5; 0.8, 1.2]);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 3, ...
                UpperBounds = [10; 2]), ...
                Method = "random", ...
                IterationRate = 1, ...
                MaxSamplingAttempts = 2);

            testCase.verifyTrue(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(generator.GenerationCount, 2);
            testCase.verifyTrue(contains( ...
                result.ErrorMessage, "Required: 3, valid: 2"));

        end

        function limitsUnsuccessfulSamplingToThirtyAttempts(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 1.2], [5; 1.2]);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 1), ...
                Method = "random", ...
                IterationRate = 1);

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(generator.GenerationCount, 30);
            testCase.verifyTrue(contains( ...
                result.ErrorMessage, "Required: 1, valid: 0"));

        end

        function rejectsSamplingAttemptLimitAboveThirty(testCase)

            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                MDVPredictor = helpers.MDVPredictorStub());

            testCase.verifyError( ...
                @() workflow.run( ...
                InitialFluxWorkflowContractTest.createInput(), ...
                MaxSamplingAttempts = 31), ...
                "MATLAB:validators:mustBeLessThanOrEqual");

        end

        function reportsNonintersectingSamplingBounds(testCase)

            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 5, ...
                StandardDeviations = 0.1);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                EffluxProfile = profile), ...
                Method = "random");

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 1]);
            testCase.verifyTrue(contains( ...
                result.ErrorMessage, "does not intersect"));

        end

        function usesConfiguredSeedSigmaMultiplier(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 0.5], [5; 0.5]);
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 1, ...
                EffluxProfile = profile, ...
                FreeEffluxSeedSigmaMultiplier = 2), ...
                Method = "random", ...
                IterationRate = 1);

            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual( ...
                generator.LastProblem.LowerBounds, [0; 0.3], ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                generator.LastProblem.UpperBounds, [10; 0.7], ...
                AbsTol = 1e-12);

        end

        function reportsSeedBoundsAndDistributionSummary(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5, 5; 0.4, 0.6], ...
                [5, 5; 0.4, 0.6]);
            messages = helpers.AnalysisMessageObserverStub();
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIDs = "v2", ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 1, ...
                EffluxProfile = profile, ...
                FreeEffluxSeedSigmaMultiplier = 2), ...
                Method = "random", ...
                IterationRate = 2, ...
                MessageReporter = @(level, message) ...
                messages.report(level, message));

            boundMessage = messages.Messages(contains( ...
                messages.Messages, ...
                "Perturbate efflux:"));
            distributionMessage = messages.Messages(contains( ...
                messages.Messages, ...
                "Initial free-efflux seed distribution:"));
            testCase.verifyFalse(result.IsError);
            testCase.verifyNumElements(boundMessage, 1);
            testCase.verifyTrue(contains(boundMessage, "reaction=v2"));
            testCase.verifyTrue(contains(boundMessage, "mean=0.50"));
            testCase.verifyTrue(contains(boundMessage, "sd=0.10"));
            testCase.verifyTrue(contains(boundMessage, "sigma=2"));
            testCase.verifyTrue(contains( ...
                boundMessage, "samplingBounds=[0.30, 0.70]"));
            testCase.verifyNumElements(distributionMessage, 1);
            testCase.verifyTrue(contains( ...
                distributionMessage, "count=2"));
            testCase.verifyTrue(contains( ...
                distributionMessage, "minimum=0.4"));
            testCase.verifyTrue(contains( ...
                distributionMessage, "median=0.5"));
            testCase.verifyTrue(contains( ...
                distributionMessage, "maximum=0.6"));

        end

        function canDisableFreeEffluxSeedRestriction(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 0.5], [5; 0.5]);
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 1, ...
                EffluxProfile = profile, ...
                RestrictFreeEffluxSeeds = false, ...
                ReversibleReactionIndices = [1, 2]), ...
                Method = "random", ...
                IterationRate = 1);

            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual( ...
                generator.LastProblem.LowerBounds, [0; 0]);
            testCase.verifyEqual( ...
                generator.LastProblem.UpperBounds, [10; 1]);

        end

        function constrainsReversibleEffluxUsingNetFlux(testCase)

            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 1, ...
                CounterReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);
            generator = helpers.InitialPointGeneratorStub( ...
                [0.5; 0], [0.5; 0]);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 1, ...
                EffluxProfile = profile, ...
                ReversibleReactionIndices = [1, 2]), ...
                Method = "random", ...
                IterationRate = 1);

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 1]);
            testCase.verifyEqual( ...
                generator.LastProblem.FluxInequalityMatrix, ...
                [1, -1; -1, 1]);
            testCase.verifyEqual( ...
                generator.LastProblem.FluxInequalityRightHandSide, ...
                [0.8; -0.2], ...
                AbsTol = 1e-12);

        end

        function usesInvalidCandidatesWhenSamplingTimesOut(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5, 5; 1.2, 1.3], ...
                [5, 5; 1.2, 1.3], ...
                DelaySeconds = 0.2);
            messages = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 2, ...
                UpperBounds = [10; 2]), ...
                Method = "random", ...
                IterationRate = 1, ...
                MaxTime = 0.1, ...
                MessageReporter = @(level, message) ...
                messages.report(level, message));

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyEqual(result.Fluxes, [5, 5; 1.2, 1.3]);
            testCase.verifyEqual(result.RightHandSides, result.Fluxes);
            testCase.verifyEqual(result.ObjectiveValues, [1e9, 1e9]);
            testCase.verifyTrue(any(contains( ...
                messages.Messages, ...
                "Using the best available candidates")));

        end

        function returnsAvailableInvalidCandidateAfterTimeout(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 1.2], [5; 1.2], DelaySeconds = 0.2);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 2, ...
                UpperBounds = [10; 2]), ...
                Method = "random", ...
                IterationRate = 1, ...
                MaxTime = 0.1);

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyEqual(result.Fluxes, [5; 1.2]);
            testCase.verifyEqual(result.RightHandSides, [5; 1.2]);
            testCase.verifyEqual(result.ObjectiveValues, 1e9);

        end

        function usesPartialInvalidResultWhenGeneratorTimesOut(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 1.2], ...
                [5; 1.2], ...
                IsError = true, ...
                ErrorMessage = ...
                "Hit-and-Run: insufficient samples. Required at least " + ...
                "2, but generated 1.", ...
                DelaySeconds = 0.2);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 2, ...
                UpperBounds = [10; 2]), ...
                MaxTime = 0.1);

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyEqual(result.Fluxes, [5; 1.2]);
            testCase.verifyEqual(result.ObjectiveValues, 1e9);

        end

        function stillRejectsTooFewValidCandidatesWithoutInvalids( ...
                testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 0.8], [5; 0.8], DelaySeconds = 0.2);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 2), ...
                Method = "random", ...
                IterationRate = 1, ...
                MaxTime = 0.1);

            testCase.verifyTrue(result.IsError);
            testCase.verifyTrue(contains( ...
                lower(result.ErrorMessage), ...
                "required: 2, valid: 1"));

        end

    end

    methods (Static, Access = private)

        function input = createInput(options)

            arguments
                options.IterationCount (1, 1) double = 2
                options.RestrictFreeEffluxSeeds ...
                    (1, 1) logical = true
                options.FreeEffluxSeedSigmaMultiplier ...
                    (1, 1) double = 3
                options.UpperBounds double = [10; 1]
                options.EffluxProfile (1, 1) ...
                    openmebius.mfa.EffluxPerturbationProfile = ...
                    openmebius.mfa.EffluxPerturbationProfile()
                options.ReversibleReactionIndices (:, 2) double = ...
                    zeros(0, 2)
            end

            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = 0.8, ...
                FragmentLabels = "M0", ...
                FragmentMask = true);
            input = openmebius.mfa.InitialFluxWorkflowInput( ...
                Model = helpers.InitialFluxModelStub(), ...
                Settings = openmebius.mfa.InitialFluxSettings( ...
                IterationCount = options.IterationCount, ...
                RestrictFreeEffluxSeeds = ...
                options.RestrictFreeEffluxSeeds, ...
                FreeEffluxSeedSigmaMultiplier = ...
                options.FreeEffluxSeedSigmaMultiplier), ...
                RightHandSide = [5; 0], ...
                LowerBounds = [0; 0], ...
                UpperBounds = options.UpperBounds, ...
                SubstrateEMUs = {1}, ...
                ExperimentalData = data, ...
                EffluxPenalty = openmebius.mfa.EffluxPenalty( ...
                Profile = options.EffluxProfile), ...
                EffluxProfile = options.EffluxProfile, ...
                ReversibleReactionIndices = ...
                options.ReversibleReactionIndices);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
