classdef InitialFluxWorkflowContractTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(InitialFluxWorkflowContractTest.sourcePath());

        end

    end

    methods (Test)

        function inputOwnsTypedSettings(testCase)

            input = InitialFluxWorkflowContractTest.createInput();

            testCase.verifyClass( ...
                input.Settings, 'openmebius.mfa.InitialFluxSettings');
            testCase.verifyEqual(input.IterationCount, 2);
            testCase.verifyEqual(input.RightHandSide, [5; 0]);
            testCase.verifyEqual(input.scoringSubstrateEMUs(false), {1});
            testCase.verifyClass( ...
                input.EffluxProfile, ...
            'openmebius.mfa.EffluxPerturbationProfile');
            testCase.verifyEmpty(input.ReversibleReactionIndices);

        end

        function inputRejectsMismatchedBounds(testCase)

            testCase.verifyError( ...
                @() InitialFluxWorkflowContractTest.createInput( ...
                UpperBounds = 1), ...
            "OpenMebius2:InitialFluxInput:DimensionMismatch");

        end

        function resultSeparatesCancellationFromFailure(testCase)

            result = openmebius.mfa.InitialFluxWorkflowResult.canceled();

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyFalse(result.IsError);

        end

        function failedResultRequiresMessage(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa.InitialFluxWorkflowResult( ...
                IsError = true), ...
            "OpenMebius2:InitialFluxResult:MissingErrorMessage");

        end

        function workflowHandlesRandomGenerationFailure(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                zeros(2, 0), ...
                zeros(2, 0), ...
                IsError = true, ...
                ErrorMessage = "generation failed");
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput(), ...
                Method = "random");

            testCase.verifyTrue(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.ErrorMessage, "generation failed");

        end

        function workflowRejectsEmptyGeneratedCandidates(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                zeros(2, 0), zeros(2, 0));
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput(), ...
                Method = "random");

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
            "Initial point generation produced no candidates.");

        end

        function workflowReturnsCanceledResultWithoutError(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 0.5], ...
                [5; 0.5], ...
                IsCanceled = true);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput());

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyFalse(result.IsError);

        end

        function usesRestrictedProblemOnlyForInitialSampling(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5; 0.5], [5; 0.5]);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());
            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 1, ...
                EffluxProfile = profile), ...
                Method = "random", ...
                IterationRate = 1);

            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual( ...
                generator.LastProblem.LowerBounds, [0; 0.2], ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                generator.LastProblem.UpperBounds, [10; 0.8], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 1]);

        end

        function rejectsTooFewValidCandidates(testCase)

            generator = helpers.InitialPointGeneratorStub( ...
                [5, 5; 0.8, 1.2], ...
                [5, 5; 0.8, 1.2]);
            messages = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                PointGenerator = generator, ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                IterationCount = 2, ...
                UpperBounds = [10; 2]), ...
                Method = "random", ...
                IterationRate = 1, ...
                MessageReporter = @(level, message) ...
                messages.report(level, message));

            testCase.verifyTrue(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyTrue(contains( ...
                result.ErrorMessage, "Required: 2, valid: 1"));
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 2]);
            testCase.verifyEqual(messages.Levels(end), "error");
            testCase.verifyEqual(result.Fluxes(:, 1), [5; 0.8]);

        end

        function reportsNonintersectingSamplingBounds(testCase)

            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 5, ...
                StandardDeviations = 0.1);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                EffluxProfile = profile), ...
                Method = "random");

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 1]);
            testCase.verifyTrue(contains( ...
                result.ErrorMessage, "does not intersect"));

        end

        function rejectsReversibleEffluxSeedRestriction(testCase)

            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);
            workflow = openmebius.mfa.InitialFluxWorkflow( ...
                MDVPredictor = helpers.MDVPredictorStub());

            result = workflow.run( ...
                InitialFluxWorkflowContractTest.createInput( ...
                EffluxProfile = profile, ...
                ReversibleReactionIndices = [1, 2]), ...
                Method = "random");

            testCase.verifyTrue(result.IsError);
            testCase.verifyTrue(contains( ...
                result.ErrorMessage, ...
            "requires net-flux inequality constraints"));
            testCase.verifyEqual(result.Problem.LowerBounds, [0; 0]);
            testCase.verifyEqual(result.Problem.UpperBounds, [10; 1]);

        end

    end

    methods (Static, Access = private)

        function input = createInput(options)

            arguments
                options.IterationCount (1, 1) double = 2
                options.UpperBounds double = [10; 1]
                options.EffluxProfile (1, 1) ...
                    openmebius.mfa.EffluxPerturbationProfile = ...
                    openmebius.mfa.EffluxPerturbationProfile()
                options.ReversibleReactionIndices (:, 2) double = ...
                    zeros(0, 2)
            end

            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = 0.8, ...
                FragmentLabels = "M0", ...
                FragmentMask = true);
            input = openmebius.mfa.InitialFluxWorkflowInput( ...
                Model = helpers.InitialFluxModelStub(), ...
                Settings = openmebius.mfa.InitialFluxSettings( ...
                IterationCount = options.IterationCount), ...
                RightHandSide = [5; 0], ...
                LowerBounds = [0; 0], ...
                UpperBounds = options.UpperBounds, ...
                SubstrateEMUs = {1}, ...
                ExperimentalData = data, ...
                EffluxPenalty = openmebius.mfa.EffluxPenalty( ...
                Profile = options.EffluxProfile), ...
                EffluxProfile = options.EffluxProfile, ...
                ReversibleReactionIndices = ...
                options.ReversibleReactionIndices);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
            'src');

        end

    end

end
