classdef InitialPointGeneratorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(InitialPointGeneratorTest.sourcePath());

        end

    end

    methods (Test)

        function randomGenerationReturnsFeasiblePoints(testCase)

            initialRandomState = rng;
            cleanup = onCleanup(@() rng(initialRandomState));
            rng(42);
            generator = openmebius.mfa.InitialPointGenerator();
            problem = InitialPointGeneratorTest.createProblem( ...
                eye(2), ...
                zeros(2, 1), ...
                zeros(2, 1), ...
                ones(2, 1), ...
                true(2, 1), ...
                true(2, 1));

            result = generator.generateRandom( ...
                problem, ...
                2, ...
                IterationsPerBatch = 4, ...
                MaxTime = 1);

            testCase.verifyFalse(result.IsCanceled);
            testCase.verifySize(result.Fluxes, [2, 4]);
            testCase.verifyEqual( ...
                result.Fluxes, ...
                result.RightHandSides, ...
                'AbsTol', 1e-12);
            testCase.verifyGreaterThanOrEqual(result.Fluxes, zeros(2, 4));
            testCase.verifyLessThanOrEqual(result.Fluxes, ones(2, 4));
            clear cleanup

        end

        function cancellationDiscardsCurrentBatch(testCase)

            generator = openmebius.mfa.InitialPointGenerator();
            problem = InitialPointGeneratorTest.createProblem( ...
                1, 0, 0, 1, true, true);

            result = generator.generateRandom( ...
                problem, ...
                1, ...
                IterationsPerBatch = 2, ...
                MaxTime = 1, ...
                CancellationRequested = @() true);

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyEmpty(result.Fluxes);
            testCase.verifyEmpty(result.RightHandSides);

        end

        function randomGenerationUsesExplicitIndependentMask(testCase)

            generator = openmebius.mfa.InitialPointGenerator();
            problem = InitialPointGeneratorTest.createProblem( ...
                eye(2), ...
                [0; 0.5], ...
                zeros(2, 1), ...
                ones(2, 1), ...
                [true; false], ...
                [true; false]);
            randomStream = RandStream('mt19937ar', 'Seed', 42);

            result = generator.generateRandom( ...
                problem, ...
                1, ...
                IterationsPerBatch = 1, ...
                MaxTime = 1, ...
                RandomStream = randomStream);

            testCase.verifyFalse(result.IsCanceled);
            testCase.verifySize(result.RightHandSides, [2, 1]);
            testCase.verifyEqual(result.RightHandSides(2), 0.5);

        end

        function findsInteriorPointInGeneratorSpace(testCase)

            generator = openmebius.mfa.InitialPointGenerator();

            [z, isSuccess, msg] = generator.findInitialZ( ...
                zeros(2, 1), ...
                ones(2, 1), ...
                0.5 * ones(2, 1), ...
                eye(2));

            testCase.verifyTrue(isSuccess, msg);
            testCase.verifyEqual(z, zeros(2, 1), 'AbsTol', 1e-10);

        end

        function calculatesFeasibleStepRange(testCase)

            generator = openmebius.mfa.InitialPointGenerator();

            [minimumStep, maximumStep, isSuccess] = generator.stepRange( ...
                zeros(2, 1), ...
                ones(2, 1), ...
                0.5 * ones(2, 1), ...
                eye(2), ...
                zeros(2, 1), ...
                [1; 0]);

            testCase.verifyTrue(isSuccess);
            testCase.verifyEqual(minimumStep, -0.5, 'AbsTol', 1e-12);
            testCase.verifyEqual(maximumStep, 0.5, 'AbsTol', 1e-12);

        end

        function hitAndRunGeneratesFeasiblePoints(testCase)

            generator = openmebius.mfa.InitialPointGenerator();
            randomStream = RandStream('mt19937ar', 'Seed', 42);
            problem = InitialPointGeneratorTest.createProblem( ...
                eye(2), ...
                zeros(2, 1), ...
                zeros(2, 1), ...
                ones(2, 1), ...
                true(2, 1), ...
                true(2, 1));

            result = generator.generateHitAndRun( ...
                problem, ...
                3, ...
                1, ...
                BurnIn = 0, ...
                Thinning = 1, ...
                MaxStep = 100, ...
                MaxTime = 2, ...
                RandomStream = randomStream);

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifySize(result.Fluxes, [2, 3]);
            testCase.verifyEqual( ...
                result.Fluxes, ...
                result.RightHandSides, ...
                'AbsTol', 1e-12);
            testCase.verifyGreaterThanOrEqual( ...
                result.Fluxes, zeros(2, 3));
            testCase.verifyLessThanOrEqual( ...
                result.Fluxes, ones(2, 3));

        end

        function hitAndRunSampleProgressUsesDebugLevel(testCase)

            generator = openmebius.mfa.InitialPointGenerator();
            randomStream = RandStream('mt19937ar', 'Seed', 42);
            messages = helpers.AnalysisMessageObserverStub();
            problem = InitialPointGeneratorTest.createProblem( ...
                eye(2), ...
                zeros(2, 1), ...
                zeros(2, 1), ...
                ones(2, 1), ...
                true(2, 1), ...
                true(2, 1));

            result = generator.generateHitAndRun( ...
                problem, ...
                3, ...
                1, ...
                BurnIn = 0, ...
                Thinning = 1, ...
                MaxStep = 100, ...
                MaxTime = 2, ...
                RandomStream = randomStream, ...
                ProgressReporter = @(level, message) ...
                messages.report(level, message));

            progressRows = startsWith( ...
                messages.Messages, "Hit-and-Run: saved ");
            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyTrue(any(progressRows));
            testCase.verifyEqual( ...
                unique(messages.Levels(progressRows)), "debug");

        end

        function hitAndRunReusesZeroDimensionalPoint(testCase)

            generator = openmebius.mfa.InitialPointGenerator();
            problem = InitialPointGeneratorTest.createProblem( ...
                1, 0, 0.5, 0.5, true, true);

            result = generator.generateHitAndRun( ...
                problem, ...
                3, ...
                1);

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.Fluxes, 0.5 * ones(1, 3));
            testCase.verifyEqual(result.RightHandSides, 0.5 * ones(1, 3));

        end

        function hitAndRunReportsCancellation(testCase)

            generator = openmebius.mfa.InitialPointGenerator();
            problem = InitialPointGeneratorTest.createProblem( ...
                1, 0, 0, 1, true, true);

            result = generator.generateHitAndRun( ...
                problem, ...
                1, ...
                1, ...
                BurnIn = 0, ...
                Thinning = 1, ...
                MaxTime = 1, ...
                CancellationRequested = @() true);

            testCase.verifyTrue(result.IsError);
            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
            "Hit-and-Run: canceled.");

        end

    end

    methods (Static, Access = private)

        function problem = createProblem( ...
                stoichiometry, rightHandSide, lowerBounds, upperBounds, ...
                independentMask, boundaryReactionMask)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = stoichiometry, ...
                RightHandSide = rightHandSide, ...
                LowerBounds = lowerBounds, ...
                UpperBounds = upperBounds, ...
                IndependentMask = independentMask, ...
                BoundaryReactionMask = boundaryReactionMask);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
            'src');

        end

    end

end
