classdef InstationaryObjectiveTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(InstationaryObjectiveTest.sourcePath());

        end

    end

    methods (Test)

        function evaluatesTimeCourseAndEffluxResiduals(testCase)

            penalty = openmebius.mfa.EffluxPenalty( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);
            objective = openmebius.mfa.InstationaryObjective( ...
                Problem = InstationaryObjectiveTest.createProblem(), ...
                RightHandSide = zeros(2, 1), ...
                Model = helpers.SteadyStateModelStub(), ...
                SubstrateEMU = eye(2), ...
                PoolSizes = [2; 4], ...
                TimePoints = [0; 1; 2], ...
                ExperimentalMDV = ...
                    [0.1, 0.1, 0.3; 0, 0.2, 0.4], ...
                FragmentMask = [true; false], ...
                EffluxPenalty = penalty, ...
                MeasurementStandardDeviation = 0.1);

            rss = objective.evaluate([0.3; 0.6]);

            testCase.verifyEqual(rss, 3, 'AbsTol', 1e-12);

        end

        function predictsTimeCourseMDV(testCase)

            objective = InstationaryObjectiveTest.createObjective();

            testCase.verifyEqual( ...
                objective.predictFlux([0.3; 0.6]), ...
                [0, 0.1, 0.2; 0, 0.2, 0.4], ...
                'AbsTol', 1e-12);

        end

        function rejectsTimePointCountMismatch(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa.InstationaryObjective( ...
                Problem = InstationaryObjectiveTest.createProblem(), ...
                RightHandSide = zeros(2, 1), ...
                Model = helpers.SteadyStateModelStub(), ...
                SubstrateEMU = eye(2), ...
                PoolSizes = [2; 4], ...
                TimePoints = [0; 1], ...
                ExperimentalMDV = zeros(2, 3), ...
                FragmentMask = true(2, 1)), ...
                "OpenMebius2:InstationaryObjective:TimePointCountMismatch");

        end

        function rejectsInvalidPoolSize(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa.InstationaryObjective( ...
                Problem = InstationaryObjectiveTest.createProblem(), ...
                RightHandSide = zeros(2, 1), ...
                Model = helpers.SteadyStateModelStub(), ...
                SubstrateEMU = eye(2), ...
                PoolSizes = [2; 0], ...
                TimePoints = [0; 1], ...
                ExperimentalMDV = zeros(2, 2), ...
                FragmentMask = true(2, 1)), ...
                "OpenMebius2:InstationaryObjective:InvalidPoolSize");

        end

    end

    methods (Static, Access = private)

        function objective = createObjective()

            objective = openmebius.mfa.InstationaryObjective( ...
                Problem = InstationaryObjectiveTest.createProblem(), ...
                RightHandSide = zeros(2, 1), ...
                Model = helpers.SteadyStateModelStub(), ...
                SubstrateEMU = eye(2), ...
                PoolSizes = [2; 4], ...
                TimePoints = [0; 1; 2], ...
                ExperimentalMDV = zeros(2, 3), ...
                FragmentMask = true(2, 1));

        end

        function problem = createProblem()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = zeros(2, 1), ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = ones(2, 1), ...
                IndependentMask = true(2, 1), ...
                BoundaryReactionMask = true(2, 1));

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
