classdef LayerDependencyBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function coreLayersDoNotReferencePresentation(testCase)

            root = LayerDependencyBoundaryTest.repositoryRoot();
            layerDirectories = [ ...
                string(fullfile(root, "src", "+openmebius", ...
                "+application")); ...
                string(fullfile(root, "src", "+openmebius", ...
                "+domain")); ...
                string(fullfile(root, "src", "+openmebius", "+mfa"))];
            forbidden = [ ...
                "openmebius.presentation"; ...
                "matlab.ui."; ...
                "uialert("; ...
                "uitable("; ...
                "uiaxes("; ...
                "openmebius.infrastructure.logging"; ...
                "openmebius.infrastructure.notification"; ...
                "SlackWebhookNotifier"];

            for directory = layerDirectories'
                files = dir(fullfile(directory, "**", "*.m"));

                for fileIndex = 1:numel(files)
                    path = fullfile(files(fileIndex).folder, ...
                        files(fileIndex).name);
                    source = string(fileread(path));

                    for token = forbidden'
                        testCase.verifyFalse( ...
                            contains(source, token), ...
                            sprintf("%s references %s", path, token));
                    end
                end
            end

        end

        function serviceLayersUseNotificationPort(testCase)

            root = LayerDependencyBoundaryTest.repositoryRoot();
            paths = [ ...
                string(fullfile(root, "src", "+openmebius", ...
                "+application", "+model", "ModelDocument.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                "+application", "+experiment", ...
                "ExperimentSet.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                "+application", "+result", "ResultCatalog.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                "+application", "+batch", "BatchSession.m"))];

            for path = paths'
                source = string(fileread(path));
                testCase.verifyFalse( ...
                    contains(source, "GeneralMessagePublisher"), ...
                    sprintf("%s uses the presentation publisher", path));
                testCase.verifyTrue( ...
                    contains(source, "NotificationEmitter"), ...
                    sprintf("%s does not use the notification port", path));
            end

            repositoryDirectory = fullfile( ...
                root, "src", "+openmebius", "+infrastructure");
            files = dir(fullfile(repositoryDirectory, "**", "*Repository.m"));

            for fileIndex = 1:numel(files)
                path = fullfile(files(fileIndex).folder, files(fileIndex).name);
                source = string(fileread(path));
                testCase.verifyFalse(contains(source, "GeneralMessagePublisher"));
            end

        end

        function outcomeAndAnalysisStateAreTyped(testCase)

            root = LayerDependencyBoundaryTest.repositoryRoot();
            applicationDirectory = fullfile( ...
                root, "src", "+openmebius", "+application");
            outcomeFiles = dir(fullfile( ...
                applicationDirectory, "**", "*Outcome.m"));

            for fileIndex = 1:numel(outcomeFiles)
                path = fullfile( ...
                    outcomeFiles(fileIndex).folder, ...
                    outcomeFiles(fileIndex).name);
                source = string(fileread(path));
                testCase.verifyFalse(contains(source, " Status"));
                testCase.verifyFalse(contains(source, '"finished"'));
                testCase.verifyFalse(contains(source, '"canceled"'));
                testCase.verifyFalse(contains(source, '"error"'));
            end

            sessionPath = fullfile( ...
                applicationDirectory, "+analysis", "MFAResultSession.m");
            sessionSource = string(fileread(sessionPath));
            testCase.verifyFalse(contains(sessionSource, "Status"));
            testCase.verifyTrue(contains(sessionSource, "AnalysisProgress"));

        end

    end

    methods (Static, Access = private)

        function root = repositoryRoot()
            root = fileparts(fileparts(mfilename("fullpath")));
        end

    end

end
