classdef LegacyRemovalBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function supersededEntryPointsAreAbsent(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            removed = [ ...
                string(fullfile(root, "src", "Batch.m")); ...
                string(fullfile(root, "src", "FluxAnalysis.m")); ...
                string(fullfile(root, "src", "IORawFile.m")); ...
                string(fullfile(root, "src", "ModelUtility.m")); ...
                string(fullfile(root, "src", "MsgEventData.m")); ...
                string(fullfile(root, "src", "OpenMebiusCUI.m")); ...
                string(fullfile(root, "src", "TestAll.m")); ...
                string(fullfile(root, "src", "Web.m")); ...
                string(fullfile(root, "src", "batchRun.m")); ...
                string(fullfile(root, "src", "computeEmuPermutation.m")); ...
                string(fullfile(root, "src", ...
                    "convertOldExpressionToNewString.m")); ...
                string(fullfile(root, "src", ...
                    "convertOldMatrixFileToNewStrings.m")); ...
                string(fullfile(root, "src", "debugSplitOldMatrix.m")); ...
                string(fullfile(root, "src", "dispDirList.m")); ...
                string(fullfile(root, "src", "experimentalData.m")); ...
                string(fullfile(root, "src", "generateReport.m")); ...
                string(fullfile(root, "src", "logDisp.m")); ...
                string(fullfile(root, "src", "mainCUI.m")); ...
                string(fullfile(root, "src", "modelConstruction.m")); ...
                string(fullfile(root, "src", "modelConstructionSym.m")); ...
                string(fullfile(root, "src", ...
                    "splitTopLevelByCommaAndSemicolon.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+analysis", ...
                    "FluxAnalysisFactory.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+experiment", ...
                    "ExperimentWorkspace.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+model", "ModelWorkspace.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+result", "ResultWorkspace.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+report", ...
                    "LegacyReportRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyProjectLoader.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyProjectInitializer.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyBatchRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyRawMSDataRepository.m"))];

            for path = removed'
                testCase.verifyFalse(isfile(path), ...
                    sprintf("Superseded file still exists: %s", path));
            end
        end

        function replacementBoundariesExist(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            replacements = [ ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+batch", "BatchSession.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+analysis", ...
                    "MFAAnalysisRun.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+experiment", "ExperimentSet.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+model", "ModelDocument.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+result", "ResultCatalog.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+batch", ...
                    "BatchRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+experiment", ...
                    "RawMSDataRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+project", ...
                    "ProjectArtifactRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+project", ...
                    "ProjectMigrationService.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+report", ...
                    "ReportRepository.m")); ...
                string(fullfile(root, "tests", "runAllTests.m"))];

            for path = replacements'
                testCase.verifyTrue(isfile(path), ...
                    sprintf("Replacement file is missing: %s", path));
            end
        end

        function sourceDoesNotReferenceRemovedContracts(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            files = dir(fullfile(root, "src", "**", "*.m"));
            removedNames = [ ...
                "FluxAnalysis"; ...
                "FluxAnalysisFactory"; ...
                "ModelUtility"; ...
                "ModelWorkspace"; ...
                "ExperimentWorkspace"; ...
                "ResultWorkspace"; ...
                "LegacyReportRepository"; ...
                "MsgEventData"];
            violations = strings(0, 1);

            for fileIndex = 1:numel(files)
                path = fullfile(files(fileIndex).folder, ...
                    files(fileIndex).name);
                source = fileread(path);

                for removedName = removedNames'
                    pattern = "\\<" + removedName + "\\>";
                    if ~isempty(regexp(source, pattern, "once"))
                        violations(end + 1, 1) = ...
                            string(path) + ": " + removedName; %#ok<AGROW>
                    end
                end
            end

            testCase.verifyEmpty(unique(violations));
        end

        function mainAppDoesNotExposeMigrationOnlyState(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread(fullfile( ...
                root, "src", "OpenMebius2_exported.m")));

            testCase.verifyFalse(contains(source, "calcStatus"));
            testCase.verifyFalse(contains(source, "LegacyUi"));
            testCase.verifyFalse(contains(source, "context.Status"));
            testCase.verifyFalse(contains(source, "updateStatusModel"));
            testCase.verifyFalse(contains(source, "updateStatusExperiment"));
            testCase.verifyFalse(contains(source, "updateStatusBatch"));
            testCase.verifyFalse(contains(source, "updateStatusResult"));
        end

        function analysisRunDoesNotExposeFacadeForwarders(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread(fullfile( ...
                root, "src", "+openmebius", "+application", ...
                "+analysis", "MFAAnalysisRun.m")));
            removedMembers = [ ...
                "function config = getConfig"; ...
                "function value = get.model"; ...
                "function value = get.exps"; ...
                "function value = get.Dependencies"; ...
                "function value = get.RunContext"; ...
                "function value = get.ResultSession"; ...
                "function value = get.AnalysisRunScope"];

            for removedMember = removedMembers'
                testCase.verifyFalse(contains(source, removedMember));
            end
        end

    end

end
