classdef LegacyRemovalBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function supersededEntryPointsAreAbsent(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            removed = [ ...
                string(fullfile(root, "src", "Batch.m")); ...
                string(fullfile(root, "src", "IORawFile.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyProjectLoader.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyProjectInitializer.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyBatchRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+legacy", ...
                    "LegacyRawMSDataRepository.m"))];

            for path = removed'
                testCase.verifyFalse(isfile(path), ...
                    sprintf("Superseded file still exists: %s", path));
            end
        end

        function replacementBoundariesExist(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            replacements = [ ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+batch", "BatchSession.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+batch", ...
                    "BatchRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+experiment", ...
                    "RawMSDataRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+infrastructure", "+project", ...
                    "ProjectArtifactRepository.m")); ...
                string(fullfile(root, "src", "+openmebius", ...
                    "+application", "+project", ...
                    "ProjectMigrationService.m"))];

            for path = replacements'
                testCase.verifyTrue(isfile(path), ...
                    sprintf("Replacement file is missing: %s", path));
            end
        end

    end

end
