classdef MainApplicationControllerTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));
            addpath(fullfile(root, "tests"));

        end

    end

    methods (Test)

        function commitsOpenedProjectArtifactsToSession(testCase)

            fixture = MainApplicationControllerTest.fixture();
            fixture.ProjectUseCase.Result = fixture.Project;
            fixture.ProjectArtifacts.LoadResult = fixture.Artifacts;
            controller = MainApplicationControllerTest.controller(fixture);

            outcome = controller.openProject("project");

            testCase.verifyTrue(outcome.isSuccess());
            testCase.verifySameHandle( ...
                fixture.Session.Project, fixture.Project);
            testCase.verifyEqual( ...
                fixture.Session.Model, fixture.Artifacts.Model);
            testCase.verifyEqual( ...
                fixture.Session.Experiments, fixture.Artifacts.Experiments);
            testCase.verifyEqual( ...
                fixture.Session.Batch, fixture.Artifacts.Batch);
            testCase.verifyEqual( ...
                fixture.Session.Result, fixture.Artifacts.Result);

        end

        function commitsTemplateModelAndExperimentReload(testCase)

            fixture = MainApplicationControllerTest.fixture();
            location = openmebius.domain.model.ModelLocation ...
                .fromDirectory(string(tempdir));
            fixture.TemplateService.Result = ...
                openmebius.application.model.TemplateModelLoadResult( ...
                Model = "loaded-model", ...
                ModelLocation = location);
            fixture.ExperimentService.ReloadResult = ...
                openmebius.application.experiment ...
                .ExperimentImportResult( ...
                Experiments = "loaded-experiments", ...
                Batch = "loaded-batch");
            controller = MainApplicationControllerTest.controller(fixture);

            modelOutcome = controller.loadTemplateModel(string(tempdir));
            experimentOutcome = controller.reloadExperiments( ...
                string(tempdir));

            testCase.verifyTrue(modelOutcome.isSuccess());
            testCase.verifyEqual( ...
                fixture.Session.Model, "loaded-model");
            testCase.verifyTrue(experimentOutcome.isSuccess());
            testCase.verifyEqual( ...
                fixture.Session.Experiments, "loaded-experiments");
            testCase.verifyEqual( ...
                fixture.Session.Batch, "loaded-batch");

        end

        function preservesSessionWhenModelLoadFails(testCase)

            fixture = MainApplicationControllerTest.fixture();
            fixture.Session.replaceModel("existing-model");
            fixture.TemplateService.Exception = MException( ...
                "OpenMebius2:Test:TemplateLoadFailed", ...
                "Template load failed.");
            controller = MainApplicationControllerTest.controller(fixture);

            outcome = controller.loadTemplateModel(string(tempdir));

            testCase.verifyTrue(outcome.isFailure());
            testCase.verifyEqual( ...
                fixture.Session.Model, "existing-model");

        end

        function resetsWorkspaceSession(testCase)

            fixture = MainApplicationControllerTest.fixture();
            fixture.Session.replaceProject( ...
                fixture.Project, ...
                fixture.Artifacts.Model, ...
                fixture.Artifacts.Experiments, ...
                fixture.Artifacts.Batch, ...
                fixture.Artifacts.Result);
            controller = MainApplicationControllerTest.controller(fixture);

            controller.resetWorkspace();

            testCase.verifyEmpty(controller.project());
            testCase.verifyEmpty(controller.model());
            testCase.verifyEmpty(controller.experiments());
            testCase.verifyEmpty(controller.batch());
            testCase.verifyEmpty(controller.result());

        end

    end

    methods (Static, Access = private)

        function fixture = fixture()

            metadata = openmebius.domain.project.ProjectMetadata( ...
                Name = "Project");
            paths = openmebius.domain.project.ProjectPaths(tempdir);
            fixture = struct( ...
                "Session", openmebius.application.session ...
                .MainApplicationSession(), ...
                "Project", openmebius.domain.project.ProjectSession( ...
                metadata, paths), ...
                "Artifacts", struct( ...
                "Model", "model", ...
                "Experiments", "experiments", ...
                "Batch", "batch", ...
                "Result", "result", ...
                "Messages", "Loaded."), ...
                "ProjectUseCase", helpers.ProjectUseCaseStub(), ...
                "ProjectArtifacts", ...
                helpers.ProjectArtifactServiceStub(), ...
                "TemplateService", ...
                helpers.TemplateModelLoadServiceStub(), ...
                "ExperimentService", ...
                helpers.ExperimentImportServiceStub());

        end

        function controller = controller(fixture)

            projectController = openmebius.application.project ...
                .ProjectOperationController( ...
                Repository = helpers.ProjectRepositoryStub(), ...
                OpenProjectUseCase = fixture.ProjectUseCase, ...
                CreateProjectUseCase = helpers.ProjectUseCaseStub(), ...
                ArtifactRepository = fixture.ProjectArtifacts);
            modelController = openmebius.application.model ...
                .ModelOperationController( ...
                TemplateModelLoadService = fixture.TemplateService);
            experimentImportController = ...
                openmebius.application.experiment ...
                .ExperimentImportController( ...
                ExperimentImportService = ...
                fixture.ExperimentService);
            controller = openmebius.application.main ...
                .MainApplicationController( ...
                Session = fixture.Session, ...
                ProjectController = projectController, ...
                ModelController = modelController, ...
                LabelLaunchController = ...
                openmebius.application.model ...
                .LabelConfigurationLaunchController(), ...
                ExperimentImportController = ...
                experimentImportController, ...
                ExperimentCalculationController = ...
                openmebius.application.experiment ...
                .ExperimentCalculationController(), ...
                ExperimentEditController = ...
                openmebius.application.experiment ...
                .ExperimentEditController(), ...
                BatchController = openmebius.application.batch ...
                .BatchOperationController(), ...
                BatchLaunchController = ...
                openmebius.application.batch ...
                .BatchConfigurationLaunchController(), ...
                BatchSelectionController = ...
                openmebius.application.batch ...
                .BatchExperimentSelectionEditorController(), ...
                BatchRunController = openmebius.application.batch ...
                .BatchRunController(), ...
                ResultController = openmebius.application.result ...
                .ResultOperationController());

        end

    end

end
