classdef MainAppCompositionBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function mainAppUsesCompositionRoot(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            testCase.verifyTrue(contains( ...
                source, ".MainAppCompositionRoot.create()"));
            testCase.verifyTrue(contains( ...
                source, "applyApplicationDependencies(dependencies)"));
            testCase.verifyTrue(contains( ...
                source, "AppDependencies openmebius.bootstrap." + ...
                    "MainAppDependencies"));

            directConstructors = [ ...
                ".MainPresenter()", ...
                ".ProjectPresenter()", ...
                ".ModelPresenter()", ...
                ".LabelConfigPresenter()", ...
                ".BatchPresenter()", ...
                ".RunConfigPresenter()", ...
                ".BatchExperimentSelectionEditorPresenter()", ...
                ".ExperimentPresenter()", ...
                ".ResultPresenter()", ...
                ".ResultPlotPresenter()", ...
                ".ProjectOperationController()", ...
                ".ModelOperationController()", ...
                ".LabelConfigurationLaunchController()", ...
                ".BatchOperationController()", ...
                ".BatchConfigurationController()", ...
                ".BatchConfigurationLaunchController()", ...
                ".BatchExperimentSelectionEditorController()", ...
                ".BatchRunController()", ...
                ".ResultOperationController()", ...
                ".ExperimentImportController()", ...
                ".ExperimentCalculationController()", ...
                ".ExperimentEditController()"];

            for constructor = directConstructors
                testCase.verifyFalse(contains(source, constructor), ...
                    constructor);
            end

        end

        function ensureMethodsNoLongerConstructDependencies(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            testCase.verifyGreaterThanOrEqual( ...
                count(source, "requireApplicationDependency("), 17);
            testCase.verifyTrue(contains( ...
                source, ...
                "OpenMebius2:Composition:MissingDependency"));

        end

    end % methods (Test)

end % classdef
