classdef MainAppCompositionRootTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));

        end

    end

    methods (Test)

        function createsTypedMainAppDependencies(testCase)

            dependencies = openmebius.bootstrap ...
                .MainAppCompositionRoot.create();

            testCase.verifyClass( ...
                dependencies, ...
                "openmebius.bootstrap.MainAppDependencies");

            expectedTypes = {
                "ApplicationController", ...
                "openmebius.application.main.MainApplicationController";
                "MainPresenter", ...
                "openmebius.presentation.main.MainPresenter";
                "ProjectPresenter", ...
                "openmebius.presentation.project.ProjectPresenter";
                "ModelPresenter", ...
                "openmebius.presentation.model.ModelPresenter";
                "LabelConfigPresenter", ...
                "openmebius.presentation.model.LabelConfigPresenter";
                "BatchPresenter", ...
                "openmebius.presentation.batch.BatchPresenter";
                "RunConfigPresenter", ...
                "openmebius.presentation.batch.RunConfigPresenter";
                "BatchExperimentSelectionEditorPresenter", ...
                "openmebius.presentation.batch." + ...
                    "BatchExperimentSelectionEditorPresenter";
                "ExperimentPresenter", ...
                "openmebius.presentation.experiment.ExperimentPresenter";
                "ResultPresenter", ...
                "openmebius.presentation.result.ResultPresenter";
                "ResultPlotPresenter", ...
                "openmebius.presentation.result.ResultPlotPresenter";
                "ProgressBarFactory", ...
                "openmebius.presentation.main.ProgressBarFactory";
                "BatchConfigurationController", ...
                "openmebius.application.batch.BatchConfigurationController";
                "BatchExperimentSelectionEditorController", ...
                "openmebius.application.batch." + ...
                    "BatchExperimentSelectionEditorController";
                "ExperimentEditController", ...
                "openmebius.application.experiment." + ...
                    "ExperimentEditController";
                "SlackNotifier", ...
                "openmebius.infrastructure.notification." + ...
                    "SlackWebhookNotifier";
                "NotificationDispatcher", ...
                "openmebius.infrastructure.notification." + ...
                    "NotificationDispatcher"};

            for dependencyIndex = 1:size(expectedTypes, 1)
                propertyName = expectedTypes{dependencyIndex, 1};
                expectedType = expectedTypes{dependencyIndex, 2};
                testCase.verifyClass( ...
                    dependencies.(propertyName), expectedType, ...
                    propertyName);
            end

        end

    end % methods (Test)

end % classdef
