classdef MainAppControllerBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function callbacksUseMainApplicationBoundary(testCase)

            source = MainAppControllerBoundaryTest.mainAppSource();
            callbackStart = strfind( ...
                source, ...
                "% Close request function: OpenMebius2UIFigure");
            callbackEnd = strfind(source, "% Component initialization");
            testCase.assertNotEmpty(callbackStart);
            testCase.assertNotEmpty(callbackEnd);
            callbacks = extractBetween( ...
                source, callbackStart(1), callbackEnd(end) - 1);

            testCase.verifyTrue(contains( ...
                callbacks, "app.ApplicationController"));
            testCase.verifyFalse(contains(callbacks, "app.Session"));
            testCase.verifyFalse(contains( ...
                callbacks, "openmebius.domain."));

            individualControllers = regexp( ...
                callbacks, ...
                "app\.(ProjectOperationController|" + ...
                    "ModelOperationController|" + ...
                    "LabelConfigurationLaunchController|" + ...
                    "BatchOperationController|" + ...
                    "BatchConfigurationLaunchController|" + ...
                    "BatchExperimentSelectionEditorController|" + ...
                    "BatchRunController|ResultOperationController|" + ...
                    "ExperimentImportController|" + ...
                    "ExperimentCalculationController|" + ...
                    "ExperimentEditController)", ...
                "match");
            testCase.verifyEmpty(individualControllers);

        end

        function appDoesNotOwnWorkspaceSession(testCase)

            source = MainAppControllerBoundaryTest.mainAppSource();

            testCase.verifyFalse(contains( ...
                source, ...
                "Session openmebius.application.session." + ...
                    "MainApplicationSession"));
            testCase.verifyFalse(contains(source, "app.Session"));
            testCase.verifyTrue(contains( ...
                source, ...
                "ApplicationController openmebius.application.main"));
            testCase.verifyFalse(contains(source, ".replaceProject("));
            testCase.verifyFalse(contains(source, ".replaceModel("));
            testCase.verifyFalse(contains( ...
                source, ".replaceExperimentState("));

        end

    end

    methods (Static, Access = private)

        function source = mainAppSource()

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

        end

    end

end
