classdef MainAppCompositionBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function mainAppUsesCompositionRoot(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            testCase.verifyTrue(contains( ...
                source, ".MainAppCompositionRoot.create()"));
            testCase.verifyTrue(contains( ...
                source, "applyApplicationDependencies(dependencies)"));
            testCase.verifyTrue(contains( ...
                source, "AppDependencies openmebius.bootstrap." + ...
                    "MainAppDependencies"));

            directConstructors = [ ...
                ".MainPresenter()", ...
                ".ProjectPresenter()", ...
                ".ModelPresenter()", ...
                ".LabelConfigPresenter()", ...
                ".BatchPresenter()", ...
                ".RunConfigPresenter()", ...
                ".BatchExperimentSelectionEditorPresenter()", ...
                ".ExperimentPresenter()", ...
                ".ResultPresenter()", ...
                ".ResultPlotPresenter()", ...
                ".ProjectOperationController()", ...
                ".ModelOperationController()", ...
                ".LabelConfigurationLaunchController()", ...
                ".BatchOperationController()", ...
                ".BatchConfigurationController()", ...
                ".BatchConfigurationLaunchController()", ...
                ".BatchExperimentSelectionEditorController()", ...
                ".BatchRunController()", ...
                ".ResultOperationController()", ...
                ".ExperimentImportController()", ...
                ".ExperimentCalculationController()", ...
                ".ExperimentEditController()"];

            for constructor = directConstructors
                testCase.verifyFalse(contains(source, constructor), ...
                    constructor);
            end

        end

        function onlyRuntimeEnsureMethodsRemain(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            matches = regexp( ...
                char(source), ...
                'function\s+(ensure\w+)\(', ...
                'tokens');
            actual = sort(string([matches{:}]));
            expected = sort([ ...
                "ensureDialogService", ...
                "ensureProgressBar", ...
                "ensureProjectDirectoryItem", ...
                "ensureSlackNotifier"]);

            testCase.verifyEqual(actual, expected);
            testCase.verifyEqual( ...
                count(source, "requireApplicationDependency("), 3);

        end

    end % methods (Test)

end % classdef
