classdef MainAppCompositionBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function mainAppUsesCompositionRoot(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            testCase.verifyTrue(contains( ...
                source, ".MainAppCompositionRoot.create()"));
            testCase.verifyTrue(contains( ...
                source, "applyApplicationDependencies(dependencies)"));
            testCase.verifyTrue(contains( ...
                source, "AppDependencies openmebius.bootstrap." + ...
                "MainAppDependencies"));

            directConstructors = [ ...
                ".MainPresenter()", ...
                ".MainApplicationController(", ...
                ".MainApplicationSession()", ...
                ".ProjectPresenter()", ...
                ".ModelPresenter()", ...
                ".LabelConfigPresenter()", ...
                ".BatchPresenter()", ...
                ".RunConfigPresenter()", ...
                ".BatchExperimentSelectionEditorPresenter()", ...
                ".ExperimentPresenter()", ...
                ".ResultPresenter()", ...
                ".ResultPlotPresenter()", ...
                ".ProgressBarFactory()", ...
                "CustomProgressBar(", ...
                ".ProjectOperationController()", ...
                ".ModelOperationController()", ...
                ".LabelConfigurationLaunchController()", ...
                ".BatchOperationController()", ...
                ".BatchConfigurationController()", ...
                ".BatchConfigurationLaunchController()", ...
                ".BatchExperimentSelectionEditorController()", ...
                ".BatchRunController()", ...
                ".ResultOperationController()", ...
                ".ExperimentImportController()", ...
                ".ExperimentCalculationController()", ...
                ".ExperimentEditController()", ...
                ".SlackWebhookNotifier()"];

            for constructor = directConstructors
                testCase.verifyFalse(contains(source, constructor), ...
                    constructor);
            end

        end

        function mainAppHasNoEnsureMethods(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            matches = regexp( ...
                char(source), ...
                'function\s+(ensure\w+)\(', ...
                'tokens');
            actual = sort(string([matches{:}]));

            testCase.verifyEmpty(actual);
            testCase.verifyEqual( ...
                count(source, "requireApplicationDependency("), 3);
            testCase.verifyEqual( ...
                count(source, ".AppDialogService("), 1);
            testCase.verifyEqual( ...
                count(source, "getProgressBar("), 3);

        end

        function workspaceOwnershipAndLegacyListenersAreRemoved(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            testCase.verifyFalse(contains( ...
                source, ...
                "Session openmebius.application.session." + ...
                "MainApplicationSession"));
            testCase.verifyTrue(contains( ...
                source, ...
                "ApplicationController openmebius.application.main"));
            testCase.verifyEmpty(regexp( ...
                source, ...
                'app\.(model|exp|batch|result|ProjectSession)\b', ...
                'match'));
            testCase.verifyFalse(contains(source, "LegacyListeners"));
            testCase.verifyFalse(contains(source, "attachLegacyListeners"));
            testCase.verifyFalse(contains(source, "detachLegacyListeners"));
            testCase.verifyFalse(contains(source, "ProgressUpdate"));
            testCase.verifyFalse(contains(source, "BatchProgressEventData"));

        end

    end % methods (Test)

end % classdef
