classdef MFAAnalysisControllerFactoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAAnalysisControllerFactoryTest.sourcePath());

        end

    end

    methods (Test)

        function assemblesControllerFromRuntime(testCase)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            provenance = struct(Version = "2.1.0");
            lifecycle = helpers.AnalysisRunLifecycleStub();
            distributionWorkflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .MFAFluxDistributionResult());
            confidenceWorkflow = helpers.WorkflowResultStub( ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult());
            nextWorkflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .NextFluxExperimentResult());
            dependencies = struct( ...
                MFAExperimentListNormalizer = ...
                    openmebius.mfa.MFAExperimentListNormalizer(), ...
                FluxDistributionWorkflow = distributionWorkflow, ...
                ConfidenceIntervalApplicationWorkflow = ...
                    confidenceWorkflow, ...
                NextFluxExperimentWorkflow = nextWorkflow, ...
                AnalysisRunLifecycle = lifecycle);
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            coordinator = openmebius.infrastructure.result ...
                .MFAResultCoordinator(IsExport = false);
            session = openmebius.application.analysis ...
                .MFAResultSession(Coordinator = coordinator);
            location = openmebius.domain.result ...
                .ResultLocation.fromDirectory(string(tempdir));
            runtime = openmebius.application.analysis ...
                .FluxAnalysisRuntime( ...
                ResultLocation = location, ...
                ResultID = "run-1", ...
                ResultFilePath = location.resultFile("run-1"), ...
                IsExport = false, ...
                IsError = true, ...
                DirectoryMessage = "runtime failed", ...
                DirectoryMessageLevel = "Error", ...
                Dependencies = dependencies, ...
                RunContext = context, ...
                ResultSession = session);
            factory = openmebius.application.analysis ...
                .MFAAnalysisControllerFactory();

            controller = factory.create( ...
                "model", ...
                "experiments", ...
                [2, 1], ...
                config, ...
                runtime, ...
                provenance);

            testCase.verifyEqual(controller.Model, "model");
            testCase.verifyEqual(controller.Experiments, "experiments");
            testCase.verifyEqual(controller.ExperimentList, [2; 1]);
            testCase.verifyEqual(controller.Config, config);
            testCase.verifyEqual(controller.ResultID, "run-1");
            testCase.verifyEqual( ...
                controller.ResultLocation, location);
            testCase.verifyEqual(controller.ResultFilePath, ...
                location.resultFile("run-1"));
            testCase.verifyEqual(controller.Provenance, provenance);
            testCase.verifyEqual(controller.Dependencies, dependencies);
            testCase.verifyEqual( ...
                controller.AnalysisRunLifecycle, lifecycle);
            testCase.verifyTrue(controller.IsError);
            testCase.verifyTrue(controller.RunSettings.canRunDistribution());

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
