classdef MFAAnalysisCompositionGroupsTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAAnalysisCompositionGroupsTest.sourcePath());

        end

    end

    methods (Test)

        function groupedConfigurationProvidesCompatibilityViews(testCase)

            numericalWorkflow = struct(Name = "numerical");
            distributionWorkflow = struct(Name = "distribution");
            repository = struct(Name = "result-repository");
            runtimeFactory = struct(Name = "runtime-factory");
            numerical = openmebius.application.analysis ...
                .MFANumericalComposition( ...
                MFAWorkflow = numericalWorkflow);
            workflows = openmebius.application.analysis ...
                .MFAWorkflowComposition( ...
                FluxDistributionWorkflow = distributionWorkflow);
            results = openmebius.application.analysis ...
                .MFAResultComposition( ...
                Hdf5ResultRepository = repository);
            execution = openmebius.application.analysis ...
                .MFAExecutionComposition( ...
                RuntimeFactory = runtimeFactory);

            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition( ...
                Numerical = numerical, ...
                Workflows = workflows, ...
                Results = results, ...
                Execution = execution);

            testCase.verifyEqual(composition.Numerical, numerical);
            testCase.verifyEqual(composition.Workflows, workflows);
            testCase.verifyEqual(composition.Results, results);
            testCase.verifyEqual(composition.Execution, execution);
            testCase.verifyEqual( ...
                composition.MFAWorkflow, numericalWorkflow);
            testCase.verifyEqual( ...
                composition.FluxDistributionWorkflow, ...
                distributionWorkflow);
            testCase.verifyEqual( ...
                composition.Hdf5ResultRepository, repository);
            testCase.verifyEqual( ...
                composition.RuntimeFactory, runtimeFactory);

        end

        function dependenciesConsumeGroupedConfiguration(testCase)

            inputWorkflow = struct(Name = "input");
            initialWorkflow = struct(Name = "initial");
            iterationWorkflow = struct(Name = "iteration");
            distributionWorkflow = struct(Name = "distribution");
            confidenceWorkflow = struct(Name = "confidence");
            nextWorkflow = struct(Name = "next");
            workflows = openmebius.application.analysis ...
                .MFAWorkflowComposition( ...
                MFAInputPreparationWorkflow = inputWorkflow, ...
                InitialFluxApplicationWorkflow = initialWorkflow, ...
                MFAIterationApplicationWorkflow = iterationWorkflow, ...
                ConfidenceIntervalApplicationWorkflow = ...
                confidenceWorkflow, ...
                NextFluxExperimentWorkflow = nextWorkflow, ...
                FluxDistributionWorkflow = distributionWorkflow);
            coordinator = openmebius.infrastructure.result ...
                .MFAResultCoordinator(IsExport = false);
            results = openmebius.application.analysis ...
                .MFAResultComposition( ...
                MFAResultCoordinator = coordinator);
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            lifecycle = helpers.AnalysisRunLifecycleStub();
            execution = openmebius.application.analysis ...
                .MFAExecutionComposition( ...
                AnalysisRunLifecycle = lifecycle, ...
                RunContext = context);
            composition = openmebius.application.analysis ...
                .FluxAnalysisComposition( ...
                Workflows = workflows, ...
                Results = results, ...
                Execution = execution);

            dependencies = openmebius.application.analysis ...
                .FluxAnalysisDependencies( ...
                composition, "", false);

            testCase.verifyClass( ...
                dependencies.Numerical, ...
                ['openmebius.application.analysis.' ...
                'MFANumericalDependencies']);
            testCase.verifyClass( ...
                dependencies.Workflows, ...
                ['openmebius.application.analysis.' ...
                'MFAWorkflowDependencies']);
            testCase.verifyClass( ...
                dependencies.Results, ...
                ['openmebius.application.analysis.' ...
                'MFAResultDependencies']);
            testCase.verifyClass( ...
                dependencies.Execution, ...
                ['openmebius.application.analysis.' ...
                'MFAExecutionDependencies']);
            testCase.verifyEqual( ...
                dependencies.MFAInputPreparationWorkflow, ...
                inputWorkflow);
            testCase.verifyEqual( ...
                dependencies.InitialFluxApplicationWorkflow, ...
                initialWorkflow);
            testCase.verifyEqual( ...
                dependencies.MFAIterationApplicationWorkflow, ...
                iterationWorkflow);
            testCase.verifyEqual( ...
                dependencies.FluxDistributionWorkflow, ...
                distributionWorkflow);
            testCase.verifyEqual( ...
                dependencies.ConfidenceIntervalApplicationWorkflow, ...
                confidenceWorkflow);
            testCase.verifyEqual( ...
                dependencies.NextFluxExperimentWorkflow, ...
                nextWorkflow);
            testCase.verifyEqual( ...
                dependencies.MFAResultCoordinator, coordinator);
            testCase.verifyEqual(dependencies.RunContext, context);
            testCase.verifyEqual( ...
                dependencies.AnalysisRunLifecycle, lifecycle);

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
