classdef MFAAnalysisDependencyFactoriesTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAAnalysisDependencyFactoriesTest.sourcePath());

        end

    end

    methods (Test)

        function resultFactoryRetainsInjectedServices(testCase)

            inputWriter = struct(Name = "input");
            resultWriter = struct(Name = "result");
            nextWriter = struct(Name = "next");
            coordinator = struct(Name = "coordinator");
            configuration = openmebius.application.analysis ...
                .MFAResultComposition( ...
                MFAInputSnapshotWriter = inputWriter, ...
                MFAResultCheckpointWriter = resultWriter, ...
                NextLabelResultCheckpointWriter = nextWriter, ...
                MFAResultCoordinator = coordinator);
            factory = openmebius.application.analysis ...
                .MFAResultDependenciesFactory();

            dependencies = factory.create( ...
                configuration, "result.h5", true);

            testCase.verifyEqual( ...
                dependencies.MFAInputSnapshotWriter, inputWriter);
            testCase.verifyEqual( ...
                dependencies.MFAResultCheckpointWriter, resultWriter);
            testCase.verifyEqual( ...
                dependencies.NextLabelResultCheckpointWriter, ...
                nextWriter);
            testCase.verifyEqual( ...
                dependencies.MFAResultCoordinator, coordinator);

        end

        function executionFactoryRetainsInjectedServices(testCase)

            normalizer = struct(Name = "normalizer");
            lifecycle = helpers.AnalysisRunLifecycleStub();
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            configuration = openmebius.application.analysis ...
                .MFAExecutionComposition( ...
                MFAExperimentListNormalizer = normalizer, ...
                AnalysisRunLifecycle = lifecycle, ...
                RunContext = context);
            resultConfiguration = openmebius.application.analysis ...
                .MFAResultComposition();
            factory = openmebius.application.analysis ...
                .MFAExecutionDependenciesFactory();

            dependencies = factory.create( ...
                configuration, resultConfiguration);

            testCase.verifyEqual( ...
                dependencies.MFAExperimentListNormalizer, ...
                normalizer);
            testCase.verifyEqual( ...
                dependencies.AnalysisRunLifecycle, lifecycle);
            testCase.verifyEqual(dependencies.RunContext, context);

        end

        function numericalFactoryBuildsResolvedServices(testCase)

            factory = openmebius.application.analysis ...
                .MFANumericalDependenciesFactory();

            dependencies = factory.create( ...
                openmebius.application.analysis ...
                .MFANumericalComposition());

            testCase.verifyClass( ...
                dependencies, ...
                ['openmebius.application.analysis.' ...
                'MFANumericalDependencies']);
            testCase.verifyClass( ...
                dependencies.FluxVariabilityWorkflow, ...
                'openmebius.mfa.FluxVariabilityWorkflow');
            testCase.verifyClass( ...
                dependencies.InitialFluxWorkflow, ...
                'openmebius.mfa.InitialFluxWorkflow');
            testCase.verifyClass( ...
                dependencies.MFAIterationService, ...
                'openmebius.mfa.MFAIterationService');
            testCase.verifyEqual( ...
                dependencies.MFAIterationService.ObjectiveFactory, ...
                dependencies.MFAObjectiveFactory);
            testCase.verifyClass( ...
                dependencies.ConfidenceIntervalWorkflow ...
                .GridSearchSolver, ...
                'openmebius.mfa.GridSearchConfidenceIntervalSolver');

        end

        function workflowFactoryBuildsResolvedServices(testCase)

            numerical = openmebius.application.analysis ...
                .MFANumericalDependenciesFactory().create( ...
                openmebius.application.analysis ...
                .MFANumericalComposition());
            factory = openmebius.application.analysis ...
                .MFAWorkflowDependenciesFactory();

            dependencies = factory.create( ...
                openmebius.application.analysis ...
                .MFAWorkflowComposition(), ...
                numerical);

            testCase.verifyClass( ...
                dependencies, ...
                ['openmebius.application.analysis.' ...
                'MFAWorkflowDependencies']);
            testCase.verifyClass( ...
                dependencies.MFAInputPreparationWorkflow, ...
                ['openmebius.application.analysis.' ...
                'MFAInputPreparationWorkflow']);
            testCase.verifyClass( ...
                dependencies.FluxDistributionWorkflow, ...
                ['openmebius.application.analysis.' ...
                'MFAFluxDistributionWorkflow']);
            testCase.verifyClass( ...
                dependencies.NextFluxExperimentWorkflow, ...
                ['openmebius.application.analysis.' ...
                'NextFluxExperimentWorkflow']);
            testCase.verifyEqual( ...
                dependencies.ConfidenceIntervalApplicationWorkflow ...
                .FitStatistics, ...
                numerical.MFAFitStatistics);

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
