classdef MFAAnalysisControllerTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAAnalysisControllerTest.sourcePath());

        end

    end

    methods (Test)

        function delegatesCommandsAndOwnsInputPreparation(testCase)

            settings = MFAAnalysisControllerTest.validSettings();
            inputPreparation = struct('Marker', 42);
            distributionWorkflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .MFAFluxDistributionResult( ...
                InputPreparation = inputPreparation, ...
                MinimumObjective = 3));
            confidenceWorkflow = helpers.WorkflowResultStub( ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                LowerBounds = [1; 2], ...
                UpperBounds = [3; 4], ...
                IsCalculated = true));
            nextWorkflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .NextFluxExperimentResult( ...
                LowerBounds = 1, ...
                UpperBounds = 2));
            controller = MFAAnalysisControllerTest.createController( ...
                settings, ...
                distributionWorkflow, ...
                confidenceWorkflow, ...
                nextWorkflow);

            distributionResult = controller.runFluxDistribution( ...
                "run-1");
            confidenceResult = ...
                controller.calculateConfidenceInterval();
            nextResult = controller.suggestNextFluxExperiment();

            testCase.verifyEqual( ...
                distributionResult.MinimumObjective, 3);
            testCase.verifyEqual(confidenceResult.LowerBounds, [1; 2]);
            testCase.verifyEqual(nextResult.UpperBounds, 2);
            testCase.verifyEqual(controller.InputPreparation, ...
                inputPreparation);
            testCase.verifyEqual( ...
                confidenceWorkflow.LastArguments{5}, ...
                inputPreparation);
            testCase.verifyEqual( ...
                nextWorkflow.LastArguments{7}, ...
                inputPreparation);

        end

        function rejectsInvalidDistributionSettings(testCase)

            config = struct(iteration = 0, isINSTMFA = false);
            settings = openmebius.application.analysis ...
                .FluxAnalysisRunSettingsMapper.fromBatchConfig(config);
            distributionWorkflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .MFAFluxDistributionResult(IsCanceled = true));
            observer = helpers.AnalysisMessageObserverStub();
            controller = MFAAnalysisControllerTest.createController( ...
                settings, distributionWorkflow);

            result = controller.runFluxDistribution( ...
                "run-1", ...
                MessageReporter = @(level, message) ...
                    observer.report(level, message));

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(result.FailureStage, "initial");
            testCase.verifyEqual(distributionWorkflow.CallCount, 0);
            testCase.verifyEqual(observer.Levels, "error");
            testCase.verifyEqual( ...
                observer.Messages, settings.DistributionErrorMessage);

        end

        function rejectsInvalidConfidenceIntervalSettings(testCase)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            config.CIConf.algorithm = "unsupported";
            settings = openmebius.application.analysis ...
                .FluxAnalysisRunSettingsMapper.fromBatchConfig(config);
            confidenceWorkflow = helpers.WorkflowResultStub( ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                IsCanceled = true));
            controller = MFAAnalysisControllerTest.createController( ...
                settings, [], confidenceWorkflow);

            result = controller.calculateConfidenceInterval();

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(confidenceWorkflow.CallCount, 0);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                settings.ConfidenceIntervalErrorMessage);

        end

        function rejectsInvalidNextExperimentSettings(testCase)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            config.suggestionTable = ["A", "B"];
            config.suggestionTableVarNames = "Tracer";
            settings = openmebius.application.analysis ...
                .FluxAnalysisRunSettingsMapper.fromBatchConfig(config);
            nextWorkflow = helpers.WorkflowResultStub( ...
                openmebius.application.analysis ...
                .NextFluxExperimentResult(IsCanceled = true));
            controller = MFAAnalysisControllerTest.createController( ...
                settings, [], [], nextWorkflow);

            result = controller.suggestNextFluxExperiment();

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(nextWorkflow.CallCount, 0);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                settings.NextExperimentErrorMessage);

        end

    end

    methods (Static, Access = private)

        function settings = validSettings()

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            settings = openmebius.application.analysis ...
                .FluxAnalysisRunSettingsMapper.fromBatchConfig(config);

        end

        function controller = createController( ...
                settings, distributionWorkflow, ...
                confidenceWorkflow, nextWorkflow)

            arguments
                settings (1, 1) openmebius.application.analysis ...
                    .FluxAnalysisRunSettings
                distributionWorkflow = []
                confidenceWorkflow = []
                nextWorkflow = []
            end

            if isempty(distributionWorkflow)
                distributionWorkflow = helpers.WorkflowResultStub( ...
                    openmebius.application.analysis ...
                    .MFAFluxDistributionResult());
            end

            if isempty(confidenceWorkflow)
                confidenceWorkflow = helpers.WorkflowResultStub( ...
                    openmebius.mfa ...
                    .ConfidenceIntervalWorkflowResult());
            end

            if isempty(nextWorkflow)
                nextWorkflow = helpers.WorkflowResultStub( ...
                    openmebius.application.analysis ...
                    .NextFluxExperimentResult());
            end

            coordinator = openmebius.infrastructure.result ...
                .MFAResultCoordinator(IsExport = false);
            session = openmebius.application.analysis ...
                .MFAResultSession(Coordinator = coordinator);
            controller = openmebius.application.analysis ...
                .MFAAnalysisController( ...
                "model", ...
                "experiments", ...
                [1, 2], ...
                settings, ...
                openmebius.application.analysis ...
                    .MFAAnalysisRunContext(), ...
                session, ...
                FluxDistributionWorkflow = distributionWorkflow, ...
                ConfidenceIntervalApplicationWorkflow = ...
                    confidenceWorkflow, ...
                NextFluxExperimentWorkflow = nextWorkflow);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
