classdef MFAConfidenceIntervalApplicationWorkflowTest < ...
        matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath( ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .sourcePath());

        end

    end

    methods (Test)

        function calculatedMonteCarloResultIsPersisted(testCase)

            lowLevelWorkflow = helpers.WorkflowResultStub( ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .confidenceResult());
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = lowLevelWorkflow);
            session = helpers.MFAResultSessionStub();

            result = workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest.config(), ...
                openmebius.application.analysis ...
                    .MFAAnalysisRunContext(), ...
                session, ...
                []);

            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(session.Calls, "monte-carlo");
            testCase.verifyEqual(lowLevelWorkflow.CallCount, 1);

        end

        function candidateCalculationCanSkipPersistence(testCase)

            lowLevelWorkflow = helpers.WorkflowResultStub( ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .confidenceResult());
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = lowLevelWorkflow);
            session = helpers.MFAResultSessionStub();

            workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest.config(), ...
                openmebius.application.analysis ...
                    .MFAAnalysisRunContext(), ...
                session, ...
                [], ...
                PersistResult = false);

            testCase.verifyEmpty(session.Calls);

        end

        function monteCarloCallbackRunsIterationService(testCase)

            solver = helpers.ConfidenceIntervalSolverStub();
            iterationResult = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 0.8, ...
                Flux = [7; 0.8], ...
                MDV = [0.2; 0.8], ...
                ObjectiveValue = 0, ...
                ExitFlag = 1);
            iterationService = ...
                helpers.MFAIterationServiceStub(iterationResult);
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = ...
                    openmebius.mfa.ConfidenceIntervalWorkflow( ...
                    MonteCarloSolver = solver), ...
                MFAIterationService = iterationService);
            context = ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .analysisContext();
            session = helpers.MFAResultSessionStub();
            session.Status = [0, 1, 0, 0];
            inputPreparation = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = 0.1, ...
                SubstrateList = "A", ...
                Efflux = 10, ...
                EffluxStandardDeviation = 1, ...
                EffluxFree = false, ...
                ExperimentalData = context.ExperimentalData);

            result = workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                    .calculationConfig(), ...
                context, ...
                session, ...
                inputPreparation);

            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(solver.CallCount, 1);
            testCase.verifyEqual(iterationService.CallCount, 1);
            testCase.verifyClass( ...
                iterationService.LastInput, ...
                'openmebius.mfa.MFAIterationInput');
            testCase.verifyTrue( ...
                iterationService.LastInput.ForceSteadyState);
            testCase.verifyEqual(result.LowerBounds, zeros(2, 1));
            testCase.verifyEqual(result.UpperBounds, ones(2, 1));
            testCase.verifyEqual(session.Calls, "monte-carlo");

        end

    end

    methods (Static, Access = private)

        function result = confidenceResult()

            result = openmebius.mfa ...
                .ConfidenceIntervalWorkflowResult( ...
                LowerBounds = [0; 1], ...
                UpperBounds = [2; 3], ...
                Output = struct(Iteration = 1), ...
                Method = "Monte Carlo", ...
                IsCalculated = true);

        end

        function value = config()

            value = struct(CIConf = struct(MC = struct));

        end

        function value = calculationConfig()

            value = struct;
            value.isCalcCI = true;
            value.isINSTMFA = false;
            value.CIConf = struct( ...
                algorithm = "Monte Carlo", ...
                MC = struct);

        end

        function context = analysisContext()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0], ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = 10 * ones(2, 1), ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            initial = openmebius.mfa.InitialFluxWorkflowResult( ...
                Problem = problem, ...
                Fluxes = [5; 0.8], ...
                RightHandSides = [7; 0.1], ...
                ObjectiveValues = 1);
            iteration = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 0.8, ...
                Flux = [5; 0.8], ...
                MDV = [0.2; 0.8], ...
                ObjectiveValue = 1, ...
                ExitFlag = 1);
            fitted = openmebius.mfa.MFAWorkflowResult( ...
                ObjectiveValues = 1, ...
                Fluxes = [5; 0.8], ...
                MDVs = reshape([0.2; 0.8], 2, 1, 1), ...
                Order = 1, ...
                IterationResults = {iteration});
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = [0.2; 0.8], ...
                FragmentLabels = ["fragment"; "fragment"], ...
                FragmentMask = [true; true]);
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            context.setExperimentalData(data);
            context.setSubstrateEMUs({1});
            context.setInitialResult(initial);
            context.setWorkflowResult(fitted);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
