classdef MFAConfidenceIntervalApplicationWorkflowTest < ...
        matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath( ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .sourcePath());

        end

    end

    methods (Test)

        function calculatedMonteCarloResultIsPersisted(testCase)

            lowLevelWorkflow = helpers.WorkflowResultStub( ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .confidenceResult());
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = lowLevelWorkflow);
            session = helpers.MFAResultSessionStub();

            result = workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest.settings(), ...
                openmebius.application.analysis ...
                .MFAAnalysisRunContext(), ...
                session, ...
                []);

            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(session.Calls, "monte-carlo");
            testCase.verifyEqual(lowLevelWorkflow.CallCount, 1);

        end

        function candidateCalculationCanSkipPersistence(testCase)

            lowLevelWorkflow = helpers.WorkflowResultStub( ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .confidenceResult());
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = lowLevelWorkflow);
            session = helpers.MFAResultSessionStub();

            workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest.settings(), ...
                openmebius.application.analysis ...
                .MFAAnalysisRunContext(), ...
                session, ...
                [], ...
                PersistResult = false);

            testCase.verifyEmpty(session.Calls);

        end

        function monteCarloCallbackRunsIterationService(testCase)

            solver = helpers.ConfidenceIntervalSolverStub();
            iterationResult = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 0.8, ...
                Flux = [7; 0.8], ...
                MDV = [0.2; 0.8], ...
                ObjectiveValue = 0, ...
                ExitFlag = 1);
            iterationService = ...
                helpers.MFAIterationServiceStub( ...
                iterationResult, ReportOnRun = true);
            observer = helpers.AnalysisMessageObserverStub();
            progress = helpers.AnalysisProgressRecorder();
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = ...
                openmebius.mfa.ConfidenceIntervalWorkflow( ...
                MonteCarloSolver = solver), ...
                MFAIterationService = iterationService);
            context = ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .analysisContext();
            session = helpers.MFAResultSessionStub();
            session.Progress.markFluxDistributionCompleted();
            inputPreparation = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = 0.1, ...
                SubstrateList = "A", ...
                Efflux = 10, ...
                EffluxStandardDeviation = 1, ...
                EffluxFree = false, ...
                ExperimentalData = context.ExperimentalData);

            result = workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .settings(), ...
                context, ...
                session, ...
                inputPreparation, ...
                MessageReporter = ...
                @(level, message) observer.report(level, message), ...
                ProgressReporter = @(completed, total) ...
                progress.record(completed, total));

            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(solver.CallCount, 1);
            testCase.verifyEqual(iterationService.CallCount, 1);
            testCase.verifyEqual(progress.Completed, 1);
            testCase.verifyEqual(progress.Total, 1);
            testCase.verifyClass( ...
                iterationService.LastInput, ...
            'openmebius.mfa.MFAIterationInput');
            testCase.verifyEqual( ...
                iterationService.LastInput.analysisMode(), ...
                openmebius.mfa.MFAAnalysisMode.SteadyState);
            testCase.verifyEqual(result.LowerBounds, zeros(2, 1));
            testCase.verifyEqual(result.UpperBounds, ones(2, 1));
            testCase.verifyFalse(any( ...
                observer.Messages == ...
            "MFA iteration service invoked."));
            testCase.verifyTrue(any( ...
                observer.Messages == ...
            "Calculating confidence interval..."));
            testCase.verifyTrue(any(contains( ...
                observer.Messages, ...
            "Confidence interval calculated successfully.")));
            testCase.verifyEqual(session.Calls, "monte-carlo");

        end

        function gridSearchCallbackRunsProfileIterationService(testCase)

            solver = helpers.GridSearchConfidenceIntervalSolverStub();
            iterationResult = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 0.8, ...
                Flux = [7; 0.8], ...
                MDV = [0.2; 0.8], ...
                ObjectiveValue = 1, ...
                ExitFlag = 1);
            iterationService = ...
                helpers.MFAIterationServiceStub( ...
                iterationResult, ReportOnRun = true);
            observer = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = ...
                openmebius.mfa.ConfidenceIntervalWorkflow( ...
                GridSearchSolver = solver), ...
                MFAIterationService = iterationService);
            context = ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .analysisContext();
            session = helpers.MFAResultSessionStub();
            session.Progress.markFluxDistributionCompleted();
            inputPreparation = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = 0.1, ...
                SubstrateList = "A", ...
                Efflux = 10, ...
                EffluxStandardDeviation = 1, ...
                EffluxFree = false, ...
                ExperimentalData = context.ExperimentalData);

            result = workflow.run( ...
                helpers.GridSearchModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .gridSettings(), ...
                context, ...
                session, ...
                inputPreparation, ...
                MessageReporter = ...
                @(level, message) ...
                observer.report(level, message));

            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(result.Method, "Grid search");
            testCase.verifyEqual(solver.CallCount, 1);
            testCase.verifyEqual( ...
                solver.LastBaseRightHandSide, [7; 0.8]);
            testCase.verifyEqual( ...
                solver.LastProfileFluxIndices, 2);
            testCase.verifyEqual( ...
                solver.LastObjectiveThreshold, ...
                1 + chi2inv(0.95, 1), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(solver.LastBestObjective, 1);
            testCase.verifyEqual(iterationService.CallCount, 1);
            testCase.verifyEqual( ...
                iterationService.LastInput.RightHandSide, [7; 0.8]);
            testCase.verifyEqual( ...
                iterationService.LastLinearEqualityMatrix, ...
                solver.LastEqualityMatrix);
            testCase.verifyEqual( ...
                iterationService.LastLinearEqualityRightHandSide, ...
                solver.LastEqualityRightHandSide);
            testCase.verifyEqual( ...
                iterationService.LastInitialIndependentValues, 0.8);
            testCase.verifyEqual( ...
                solver.LastEvaluationResult, iterationResult);
            testCase.verifyFalse(any( ...
                observer.Messages == ...
            "MFA iteration service invoked."));
            testCase.verifyEqual(session.Calls, "grid-search");

        end

        function fDistributionThresholdUsesAllParallelExperiments(testCase)

            solver = helpers.GridSearchConfidenceIntervalSolverStub();
            iterationResult = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 0.8, ...
                Flux = [7; 0.8], ...
                MDV = repmat([0.2; 0.8], 1, 2), ...
                ObjectiveValue = 1, ...
                ExitFlag = 1);
            iterationService = helpers.MFAIterationServiceStub( ...
                iterationResult);
            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow( ...
                ConfidenceIntervalWorkflow = ...
                openmebius.mfa.ConfidenceIntervalWorkflow( ...
                GridSearchSolver = solver), ...
                MFAIterationService = iterationService);
            context = ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .analysisContext(ExperimentCount = 2);
            session = helpers.MFAResultSessionStub();
            session.Progress.markFluxDistributionCompleted();
            inputPreparation = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = 0.1, ...
                SubstrateList = "A", ...
                Efflux = 10, ...
                EffluxStandardDeviation = 1, ...
                EffluxFree = false, ...
                ExperimentalData = context.ExperimentalData);
            settings = openmebius.application.analysis ...
                .MFAConfidenceIntervalRunSettings( ...
                ConfidenceIntervalSettings = ...
                openmebius.mfa.ConfidenceIntervalSettings( ...
                Enabled = true, ...
                Method = openmebius.mfa ...
                .ConfidenceIntervalMethod.GridSearch, ...
                GridSearchSettings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                Threshold = "f-distribution")), ...
                GridSearchSelectedReactionIDs = "r2", ...
                UseAllGridSearchReactions = false);

            result = workflow.run( ...
                helpers.GridSearchModelStub(), ...
                settings, ...
                context, ...
                session, ...
                inputPreparation);

            testCase.verifyTrue(result.IsCalculated);
            testCase.verifyEqual( ...
                solver.LastObjectiveThreshold, ...
                1 + 0.5 * finv(0.95, 1, 2), ...
                AbsTol = 1e-12);

        end

        function gridSearchWithoutFluxDistributionReturnsError(testCase)

            workflow = openmebius.application.analysis ...
                .MFAConfidenceIntervalWorkflow();
            session = helpers.MFAResultSessionStub();

            result = workflow.run( ...
                helpers.GridSearchModelStub(), ...
                MFAConfidenceIntervalApplicationWorkflowTest ...
                .gridSettings(), ...
                openmebius.application.analysis ...
                .MFAAnalysisRunContext(), ...
                session, ...
                []);

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
            "Flux distribution is not calculated.");

        end

    end

    methods (Static, Access = private)

        function result = confidenceResult()

            result = openmebius.mfa ...
                .ConfidenceIntervalWorkflowResult( ...
                LowerBounds = [0; 1], ...
                UpperBounds = [2; 3], ...
                Output = struct(Iteration = 1), ...
                Method = "Monte Carlo", ...
                IsCalculated = true);

        end

        function value = settings()

            value = openmebius.application.analysis ...
                .MFAConfidenceIntervalRunSettings( ...
                ConfidenceIntervalSettings = ...
                openmebius.mfa.ConfidenceIntervalSettings( ...
                Enabled = true));

        end

        function value = gridSettings()

            value = openmebius.application.analysis ...
                .MFAConfidenceIntervalRunSettings( ...
                ConfidenceIntervalSettings = ...
                openmebius.mfa.ConfidenceIntervalSettings( ...
                Enabled = true, ...
                Method = openmebius.mfa ...
                .ConfidenceIntervalMethod.GridSearch), ...
                GridSearchSelectedReactionIDs = "r2", ...
                UseAllGridSearchReactions = false);

        end

        function context = analysisContext(options)

            arguments
                options.ExperimentCount (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 1
            end

            experimentCount = options.ExperimentCount;

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0], ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = 10 * ones(2, 1), ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            initial = openmebius.mfa.InitialFluxWorkflowResult( ...
                Problem = problem, ...
                Fluxes = [5; 0.8], ...
                RightHandSides = [7; 0.1], ...
                ObjectiveValues = 1);
            iteration = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 0.8, ...
                Flux = [5; 0.8], ...
                MDV = repmat([0.2; 0.8], 1, experimentCount), ...
                ObjectiveValue = 1, ...
                ExitFlag = 1);
            fitted = openmebius.mfa.MFAWorkflowResult( ...
                ObjectiveValues = 1, ...
                Fluxes = [5; 0.8], ...
                MDVs = reshape( ...
                repmat([0.2; 0.8], 1, experimentCount), ...
                2, experimentCount, 1), ...
                Order = 1, ...
                IterationResults = {iteration});
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = repmat( ...
                [0.2; 0.8], 1, experimentCount), ...
                FragmentLabels = ["fragment"; "fragment"], ...
                FragmentMask = [true; true]);
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            context.setExperimentalData(data);
            context.setSubstrateEMUs(repmat({1}, experimentCount, 1));
            context.setInitialResult(initial);
            context.setWorkflowResult(fitted);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
            'src');

        end

    end

end
