classdef MFACharacterizationTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFACharacterizationTest.sourcePath());

        end

    end

    methods (Test)

        function matchesSavedFluxRssMdvAndConfidenceInterval(testCase)

            baseline = MFACharacterizationTest.loadBaseline();
            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = zeros(2, 1), ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = ones(2, 1), ...
                IndependentMask = true(2, 1), ...
                BoundaryReactionMask = true(2, 1));
            solver = openmebius.mfa.SteadyStateSolver();
            target = [0.25; 0.75];

            iteration = solver.solve( ...
                problem, ...
                zeros(2, 1), ...
                @(values) sum((values - target) .^ 2), ...
                openmebius.mfa.SteadyStateOptions( ...
                    MaxIterations = 100, ...
                    StepSizeSearchEnabled = false));
            testCase.assertFalse( ...
                iteration.IsError, iteration.ErrorMessage);

            predictor = openmebius.mfa.SteadyStateMDVPredictor();
            model = helpers.SteadyStateModelStub();
            substrateMDV = {eye(2)};
            mdv = predictor.predictLinearized( ...
                model, iteration.Flux, substrateMDV);
            statistics = openmebius.mfa.MFAFitStatistics();
            fit = statistics.evaluateFluxes( ...
                iteration.Flux, ...
                [0.24; 0.74], ...
                true(2, 1), ...
                @(flux) predictor.predictLinearized( ...
                    model, flux, substrateMDV), ...
                openmebius.mfa.EffluxPenalty(), ...
                MeasurementStandardDeviation = 0.01);

            ciStub = helpers.MonteCarloIterationStub( ...
                [0.20, 0.24, 0.28, 0.26; ...
                 0.80, 0.76, 0.72, 0.74], ...
                [4, 3, 2, 1]);
            ciSettings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                    IterationCount = 4, ...
                    StandardDeviation = 0, ...
                    Procedure = openmebius.mfa ...
                        .MonteCarloOptimizationProcedure.SingleRun);
            ci = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSolver().solve( ...
                    mdv, ...
                    2, ...
                    ciSettings, ...
                    @(sample) ciStub.run(sample), ...
                    UseParallel = false, ...
                    ConfidenceLevel = 0.5);

            testCase.verifyEqual( ...
                iteration.Flux, baseline.flux(:), ...
                AbsTol = baseline.tolerance.flux);
            testCase.verifyEqual( ...
                fit.ObjectiveValues(1), baseline.rss, ...
                AbsTol = baseline.tolerance.rss);
            testCase.verifyEqual( ...
                mdv, baseline.mdv(:), ...
                AbsTol = baseline.tolerance.mdv);
            testCase.verifyEqual( ...
                ci.LowerBounds(:, end), baseline.ciLower(:), ...
                AbsTol = baseline.tolerance.ci);
            testCase.verifyEqual( ...
                ci.UpperBounds(:, end), baseline.ciUpper(:), ...
                AbsTol = baseline.tolerance.ci);
            testCase.verifyFalse(ci.IsCanceled);

        end

    end

    methods (Static, Access = private)

        function baseline = loadBaseline()

            path = fullfile( ...
                MFACharacterizationTest.repositoryRoot(), ...
                "tests", "characterization", ...
                "mfa-baseline-v1.json");
            baseline = jsondecode(fileread(path));

        end

        function path = sourcePath()

            path = fullfile( ...
                MFACharacterizationTest.repositoryRoot(), "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

    end

end
