classdef MFAExperimentalDataBuilderTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAExperimentalDataBuilderTest.sourcePath());

        end

    end

    methods (Test)

        function buildsAlignedMDVAndAllFragmentMask(testCase)

            builder = openmebius.mfa.MFAExperimentalDataBuilder();
            model = helpers.MFAExperimentalDataModelStub();
            experiments = ...
                MFAExperimentalDataBuilderTest.experiments();

            result = builder.build( ...
                model, ...
                experiments, ...
                ["E1"; "E2"], ...
                openmebius.mfa.MSFragmentSelection());

            testCase.verifyEqual( ...
                result.ExperimentalMDV, ...
                [0.1, 0.2; 0.2, 0.3; 0.7, 0.5; ...
                0.4, NaN; 0.6, NaN]);
            testCase.verifyEqual( ...
                result.FragmentLabels, ...
                ["A"; "A"; "A"; "B"; "B"]);
            testCase.verifyEqual( ...
                result.FragmentMask, ...
                [true; true; true; false; false]);
            testCase.verifyEqual(result.FragmentCount, 5);
            testCase.verifyEqual(result.ExperimentCount, 2);

        end

        function sortsAndAppliesCustomFragmentSelection(testCase)

            builder = openmebius.mfa.MFAExperimentalDataBuilder();
            model = helpers.MFAExperimentalDataModelStub();
            model.FragmentList = ["B"; "A"];
            selection = openmebius.mfa.MSFragmentSelection( ...
                Mode = openmebius.mfa ...
                .MSFragmentSelectionMode.CustomSelection, ...
                Fragments = ["B"; "A"], ...
                SelectedMask = [true; false]);

            result = builder.build( ...
                model, ...
                MFAExperimentalDataBuilderTest.experiments(), ...
                "E1", ...
                selection);

            testCase.verifyEqual( ...
                result.FragmentLabels, ...
                ["A"; "A"; "A"; "B"; "B"]);
            testCase.verifyEqual( ...
                result.FragmentMask, ...
                [false; false; false; true; true]);

        end

        function arrangesLinearizedMDVByExperiment(testCase)

            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = zeros(2, 2), ...
                FragmentLabels = ["A"; "A"], ...
                FragmentMask = [true; true]);

            arranged = data.arrangeMDV(1:6, ExperimentCount = 3);

            testCase.verifyEqual(arranged, [1, 3, 5; 2, 4, 6]);

        end

        function rejectsInsufficientLinearizedMDV(testCase)

            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = zeros(2, 2), ...
                FragmentLabels = ["A"; "A"], ...
                FragmentMask = [true; true]);

            testCase.verifyError( ...
                @() data.arrangeMDV(1:3), ...
                "OpenMebius2:MFAExperimentalData:InsufficientMDVValues");

        end

        function rejectsMismatchedCustomSelection(testCase)

            builder = openmebius.mfa.MFAExperimentalDataBuilder();
            selection = openmebius.mfa.MSFragmentSelection( ...
                Mode = openmebius.mfa ...
                .MSFragmentSelectionMode.CustomSelection, ...
                Fragments = ["A"; "B"], ...
                SelectedMask = true);

            testCase.verifyError( ...
                @() builder.build( ...
                helpers.MFAExperimentalDataModelStub(), ...
                MFAExperimentalDataBuilderTest.experiments(), ...
                "E1", ...
                selection), ...
                "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                "InvalidCustomFragmentSelection");

        end

    end

    methods (Static, Access = private)

        function experiments = experiments()

            first = table( ...
                [0.1; 0.2; 0.7], ...
                [0.4; 0.6; NaN], ...
                VariableNames = {'A', 'B'});
            second = table( ...
                [0.2; 0.3; 0.5], ...
                VariableNames = {'A'});
            experiments = ...
                helpers.MFAExperimentalDataExperimentsStub( ...
                ["E1"; "E2"], ...
                {first; second});

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
