classdef MFAFitStatisticsTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAFitStatisticsTest.sourcePath());

        end

    end

    methods (Test)

        function evaluatesSortsAndCountsCandidateFluxes(testCase)

            statistics = openmebius.mfa.MFAFitStatistics();
            penalty = openmebius.mfa.EffluxPenalty( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 4, ...
                StandardDeviations = 1);

            result = statistics.evaluateFluxes( ...
                [1, 2, 6; 2, 4, 6], ...
                [0.4; 0.3], ...
                [true; true], ...
                @(flux) [0.2 * flux(1); 0.3], ...
                penalty);

            testCase.verifyEqual( ...
                result.ObjectiveValues, [0, 404, 1e9], ...
                AbsTol = 1e-10);
            testCase.verifyEqual(result.Order, [2, 1, 3]);
            testCase.verifyEqual(result.ValidCount, 2);
            testCase.verifyFalse(result.IsCanceled);

        end

        function supportsCancellationBeforeFirstCandidate(testCase)

            statistics = openmebius.mfa.MFAFitStatistics();

            result = statistics.evaluateFluxes( ...
                [1, 2; 3, 4], ...
                [0.2; 0.8], ...
                [true; true], ...
                @(flux) flux, ...
                openmebius.mfa.EffluxPenalty(), ...
                CancellationRequested = @() true);

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyTrue( ...
                all(isnan(result.ObjectiveValues)));
            testCase.verifyEqual(result.ValidCount, 0);

        end

        function calculatesParallelLabelingChiSquareThreshold(testCase)

            statistics = openmebius.mfa.MFAFitStatistics();
            labels = [ ...
                "A", "A"; ...
                "A", "B"; ...
                "B", "B"; ...
                "B", "C"];
            mask = [ ...
                true, true; ...
                true, true; ...
                true, true; ...
                true, false];

            [threshold, degreesOfFreedom] = ...
                statistics.chiSquareThreshold( ...
                1, labels, mask, 0.05);

            testCase.verifyEqual(degreesOfFreedom, 2);
            testCase.verifyEqual( ...
                threshold, chi2inv(0.95, 2), ...
                AbsTol = 1e-12);

        end

        function rejectsMismatchedFragmentMetadata(testCase)

            statistics = openmebius.mfa.MFAFitStatistics();

            testCase.verifyError( ...
                @() statistics.chiSquareThreshold( ...
                1, ["A"; "B"], true, 0.05), ...
                "OpenMebius2:MFAFitStatistics:" + ...
                "FragmentDimensionMismatch");

        end

        function calculatesGridSearchChiSquareThreshold(testCase)

            statistics = openmebius.mfa.MFAFitStatistics();
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                Threshold = "chi-sq", ...
                Alpha = 0.05);

            threshold = statistics.gridSearchObjectiveThreshold( ...
                settings, 2, 10);

            testCase.verifyEqual( ...
                threshold, ...
                2 + chi2inv(0.95, 1), ...
                AbsTol = 1e-12);

        end

        function calculatesGridSearchFThreshold(testCase)

            statistics = openmebius.mfa.MFAFitStatistics();
            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                Threshold = "f-distribution", ...
                Alpha = 0.05);

            threshold = statistics.gridSearchObjectiveThreshold( ...
                settings, 2, 10);

            testCase.verifyEqual( ...
                threshold, ...
                2 + (2 / 10) * finv(0.95, 1, 10), ...
                AbsTol = 1e-12);

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
