classdef MFAFluxDistributionWorkflowTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAFluxDistributionWorkflowTest.sourcePath());

        end

    end

    methods (Test)

        function successfulRunCoordinatesWorkflowsAndPersistence(testCase)

            fixture = MFAFluxDistributionWorkflowTest.createFixture();
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                [], ...
                1, ...
                fixture.Settings, ...
                fixture.Context, ...
                fixture.Session, ...
                "unit-test", ...
                MessageReporter = ...
                    @(level, message) ...
                    fixture.Messages.report(level, message), ...
                ProgressReporter = ...
                    @(iteration, total) ...
                    fixture.Progress.reportProgress(iteration, total));

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.MinimumObjective, 6);
            testCase.verifyEqual( ...
                fixture.Context.RightHandSide, [4; 5]);
            testCase.verifyEqual(fixture.Context.LowerBounds, [0; 1]);
            testCase.verifyEqual(fixture.Context.UpperBounds, [2; 3]);
            testCase.verifyEqual( ...
                fixture.Context.SubstrateEMUs, {1});
            testCase.verifyEqual( ...
                fixture.Context.InitialResult.Problem, ...
                fixture.InitialProblem);
            testCase.verifyEqual( ...
                fixture.Context.WorkflowResult.Fluxes, [7; 8]);
            testCase.verifyEqual( ...
                fixture.Session.Calls, ...
                ["general"; "model"; "fva"; "initial"; ...
                "iteration"; "summary"]);
            testCase.verifyEqual( ...
                fixture.Session.SummaryObjectiveValues, 6);
            testCase.verifyEqual(fixture.Session.SummaryOrder, 1);
            testCase.verifyGreaterThan( ...
                fixture.Session.SummaryThreshold, 0);
            testCase.verifyEqual( ...
                fixture.Progress.ProgressIndices, 1);
            testCase.verifyEqual(fixture.IterationService.CallCount, 1);
            testCase.verifyClass( ...
                fixture.IterationService.LastInput, ...
                'openmebius.mfa.MFAIterationInput');
            testCase.verifyEqual( ...
                fixture.IterationService.LastInput.analysisMode(), ...
                openmebius.mfa.MFAAnalysisMode.SteadyState);
            testCase.verifyEqual(fixture.InputWorkflow.CallCount, 1);
            testCase.verifyEqual(fixture.FVAWorkflow.CallCount, 1);
            testCase.verifyEqual(fixture.InitialWorkflow.CallCount, 1);
            testCase.verifyEqual(fixture.ModelSession.RestoreCount, 1);

        end

        function fvaFailureStopsBeforeInitialFluxCalculation(testCase)

            fixture = MFAFluxDistributionWorkflowTest.createFixture( ...
                FVAError = true);
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                [], ...
                [1; 2], ...
                fixture.Settings, ...
                fixture.Context, ...
                fixture.Session, ...
                "unit-test");

            testCase.verifyTrue(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.FailureStage, "fva");
            testCase.verifyEqual(result.ErrorMessage, "FVA failed.");
            testCase.verifyEqual( ...
                fixture.Session.Calls, ["general"; "model"]);
            testCase.verifyEqual(fixture.InitialWorkflow.CallCount, 0);
            testCase.verifyEqual(fixture.IterationService.CallCount, 0);
            testCase.verifyEqual(fixture.ModelSession.RestoreCount, 1);

        end

        function instationaryRunMapsTypedInputSpecification(testCase)

            fixture = MFAFluxDistributionWorkflowTest.createFixture( ...
                Instationary = true);
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                [], ...
                1, ...
                fixture.Settings, ...
                fixture.Context, ...
                fixture.Session, ...
                "unit-test");

            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual( ...
                fixture.IterationService.LastInput.analysisMode(), ...
                openmebius.mfa.MFAAnalysisMode.Instationary);
            testCase.verifyEqual( ...
                fixture.InstationaryInputFactory.CallCount, 1);
            testCase.verifyClass( ...
                fixture.InstationaryInputFactory.LastSpecification, ...
                'openmebius.mfa.InstationaryInputSpecification');
            testCase.verifyEqual( ...
                fixture.InstationaryInputFactory.LastSpecification ...
                .PoolMetabolites, ...
                ["A"; "B"]);
            testCase.verifyEqual( ...
                fixture.Context.InstationaryInput.PoolSizes, [2; 4]);

        end

        function failedResultRequiresFailureStage(testCase)

            testCase.verifyError( ...
                @() openmebius.application.analysis ...
                .MFAFluxDistributionResult(IsError = true), ...
                "OpenMebius2:MFAFluxDistribution:" + ...
                "MissingFailureStage");

        end

    end

    methods (Static, Access = private)

        function fixture = createFixture(options)

            arguments
                options.FVAError (1, 1) logical = false
                options.Instationary (1, 1) logical = false
            end

            modelSession = helpers.EffluxFreeSessionStub();
            experimentalData = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = [0.2; 0.8], ...
                FragmentLabels = ["fragment"; "fragment"], ...
                FragmentMask = [true; true]);
            inputResult = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = 0.1, ...
                SubstrateList = "A", ...
                Efflux = 10, ...
                EffluxStandardDeviation = 1, ...
                EffluxFree = false, ...
                ExperimentalData = experimentalData, ...
                EffluxFreeSession = modelSession);

            if options.FVAError
                fvaResult = openmebius.mfa ...
                    .FluxVariabilityWorkflowResult( ...
                    RightHandSide = [4; 5], ...
                    Problem = 41, ...
                    UpperBounds = zeros(2, 1), ...
                    LowerBounds = zeros(2, 1), ...
                    ExitFlag = -1, ...
                    ErrorMessage = "FVA failed.", ...
                    IsError = true);
            else
                fvaResult = openmebius.mfa ...
                    .FluxVariabilityWorkflowResult( ...
                    RightHandSide = [4; 5], ...
                    Problem = 41, ...
                    UpperBounds = [2; 3], ...
                    LowerBounds = [0; 1], ...
                    ExitFlag = 1);
            end

            initialProblem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [4; 5], ...
                LowerBounds = [0; 1], ...
                UpperBounds = [2; 3], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            initialResult = openmebius.mfa ...
                .InitialFluxWorkflowResult( ...
                Problem = initialProblem, ...
                Fluxes = [1; 2], ...
                RightHandSides = [4; 5], ...
                ObjectiveValues = 5);
            iterationResult = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 1, ...
                Flux = [7; 8], ...
                MDV = [0.3; 0.7], ...
                ObjectiveValue = 6, ...
                ExitFlag = 1);
            inputWorkflow = helpers.WorkflowResultStub(inputResult);
            fvaWorkflow = helpers.WorkflowResultStub(fvaResult);
            initialWorkflow = helpers.WorkflowResultStub(initialResult);
            iterationService = ...
                helpers.MFAIterationServiceStub(iterationResult);
            instationaryInputFactory = ...
                helpers.InstationaryInputFactorySpy();
            workflow = openmebius.application.analysis ...
                .MFAFluxDistributionWorkflow( ...
                InputPreparationWorkflow = inputWorkflow, ...
                FluxVariabilityWorkflow = fvaWorkflow, ...
                InitialFluxWorkflow = initialWorkflow, ...
                MFAIterationService = iterationService, ...
                SubstrateEMUFactory = ...
                    helpers.SubstrateEMUFactoryStub(), ...
                EffluxPenaltyFactory = ...
                    helpers.EffluxPenaltyFactoryStub(), ...
                InstationaryInputFactory = ...
                    instationaryInputFactory);

            analysisMode = openmebius.mfa ...
                .MFAAnalysisMode.SteadyState;
            instationarySpecification = [];

            if options.Instationary
                analysisMode = openmebius.mfa ...
                    .MFAAnalysisMode.Instationary;
                instationarySpecification = openmebius.mfa ...
                    .InstationaryInputSpecification( ...
                    PoolMetabolites = ["A"; "B"], ...
                    PoolSizes = [2; 4], ...
                    TimePoints = [0; 1]);
            end

            settings = openmebius.application.analysis ...
                .MFAAnalysisSettings( ...
                IterationSettings = openmebius.mfa ...
                    .MFAIterationSettings( ...
                    AnalysisMode = analysisMode), ...
                InstationaryInputSpecification = ...
                    instationarySpecification);

            fixture = struct;
            fixture.Workflow = workflow;
            fixture.Model = helpers.FluxDistributionModelStub();
            fixture.Settings = settings;
            fixture.Context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            fixture.Session = helpers.MFAResultSessionStub();
            fixture.Messages = helpers.AnalysisMessageObserverStub();
            fixture.Progress = helpers.MFAWorkflowObserverStub();
            fixture.InputWorkflow = inputWorkflow;
            fixture.InitialProblem = initialProblem;
            fixture.FVAWorkflow = fvaWorkflow;
            fixture.InitialWorkflow = initialWorkflow;
            fixture.IterationService = iterationService;
            fixture.InstationaryInputFactory = ...
                instationaryInputFactory;
            fixture.ModelSession = modelSession;

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
