classdef MFAInputValidatorTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAInputValidatorTest.sourcePath());

        end

    end

    methods (Test)

        function validatesAndAggregatesEffluxInputs(testCase)

            validator = openmebius.mfa.MFAInputValidator();
            model = helpers.MFAInputValidationModelStub();
            experiments = MFAInputValidatorTest.experiments( ...
                [0.1; 0.3], [10, 2; 14, 4]);

            result = validator.validateEfflux( ...
                model, ...
                experiments, ...
                ["E1"; "E2"], ...
                openmebius.mfa.EffluxPerturbationSettings());

            testCase.verifyTrue(result.IsValid);
            testCase.verifyEqual(result.Value.GrowthRate, 0.2, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.Value.SubstrateList, ["A"; "B"]);
            testCase.verifyEqual(result.Value.Efflux, [12; 3]);
            testCase.verifyEmpty( ...
                result.Value.EffluxStandardDeviation);
            testCase.verifyEmpty(result.Value.EffluxFree);

        end

        function alignsPerturbationInputsBySubstrateName(testCase)

            validator = openmebius.mfa.MFAInputValidator();
            model = helpers.MFAInputValidationModelStub();
            experiments = MFAInputValidatorTest.experiments( ...
                [0.2; 0.2], [10, 2; 10, 2]);
            settings = openmebius.mfa ...
                .EffluxPerturbationSettings( ...
                Enabled = true, ...
                Substrates = ["B"; "A"], ...
                FreeSelection = [true; false], ...
                StandardDeviations = [0.5; 0.1]);

            result = validator.validateEfflux( ...
                model, experiments, ["E1"; "E2"], settings);

            testCase.verifyTrue(result.IsValid);
            testCase.verifyEqual( ...
                result.Value.EffluxStandardDeviation, [0.1; 0.5]);
            testCase.verifyEqual( ...
                result.Value.EffluxFree, [false; true]);

        end

        function rejectsNonPositiveSelectedStandardDeviation(testCase)

            validator = openmebius.mfa.MFAInputValidator();
            model = helpers.MFAInputValidationModelStub();
            experiments = MFAInputValidatorTest.experiments( ...
                [0.2; 0.2], [10, 2; 10, 2]);
            settings = openmebius.mfa ...
                .EffluxPerturbationSettings( ...
                Enabled = true, ...
                Substrates = ["A"; "B"], ...
                FreeSelection = [true; false], ...
                StandardDeviations = [0; 0.5]);

            result = validator.validateEfflux( ...
                model, experiments, ["E1"; "E2"], settings);

            testCase.verifyFalse(result.IsValid);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                "Efflux standard deviation must be positive " + ...
                "for perturbation.");

        end

        function validatesGrowthRatePerturbation(testCase)

            validator = openmebius.mfa.MFAInputValidator();
            model = helpers.MFAInputValidationModelStub();
            experiments = MFAInputValidatorTest.experiments( ...
                [0.1; 0.3], [10, 2; 14, 4]);
            settings = openmebius.mfa ...
                .EffluxPerturbationSettings( ...
                Enabled = true, ...
                GrowthRateFree = true, ...
                GrowthRateStandardDeviation = 0.02);

            result = validator.validateEfflux( ...
                model, experiments, ["E1"; "E2"], settings);

            testCase.verifyTrue(result.IsValid);
            testCase.verifyTrue(result.Value.GrowthRateFree);
            testCase.verifyEqual( ...
                result.Value.GrowthRateStandardDeviation, 0.02);
            testCase.verifyEqual( ...
                result.Value.EffluxFree, [false; false]);

        end

        function rejectsInvalidGrowthRateStandardDeviation(testCase)

            validator = openmebius.mfa.MFAInputValidator();
            experiments = MFAInputValidatorTest.experiments( ...
                [0.1; 0.3], [10, 2; 14, 4]);
            settings = openmebius.mfa ...
                .EffluxPerturbationSettings( ...
                Enabled = true, ...
                GrowthRateFree = true, ...
                GrowthRateStandardDeviation = NaN);

            result = validator.validateEfflux( ...
                helpers.MFAInputValidationModelStub(), ...
                experiments, ["E1"; "E2"], settings);

            testCase.verifyFalse(result.IsValid);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                "Growth-rate (mu) standard deviation must be " + ...
                "positive and finite for perturbation.");

        end

        function rejectsDuplicatedModelSubstrates(testCase)

            validator = openmebius.mfa.MFAInputValidator();
            model = helpers.MFAInputValidationModelStub();
            model.Substrates = ["A"; "A"];
            experiments = MFAInputValidatorTest.experiments( ...
                [0.2; 0.2], [10, 2; 10, 2]);

            result = validator.validateEfflux( ...
                model, experiments, ["E1"; "E2"], ...
                openmebius.mfa.EffluxPerturbationSettings());

            testCase.verifyFalse(result.IsValid);
            testCase.verifyEqual( ...
                result.ErrorMessage, "Substrates were duplicated.");

        end

        function acceptsReversibleExchangeAsSingleSubstrate(testCase)

            validator = openmebius.mfa.MFAInputValidator();
            model = MFAInputValidatorTest.reversibleExchangeModel();
            info = table(0.2, ...
                VariableNames = {'mu'}, ...
                RowNames = {'E1'});
            uptake = table(10, ...
                VariableNames = {'Subs_A'}, ...
                RowNames = {'E1'});
            experiments = ...
                helpers.MFAInputValidationExperimentsStub( ...
                info, uptake);
            stoichiometry = model.getSBefore();

            result = validator.validateEfflux( ...
                model, experiments, "E1", ...
                openmebius.mfa.EffluxPerturbationSettings());

            testCase.verifyTrue(result.IsValid);
            testCase.verifyEqual( ...
                result.Value.SubstrateList, "Subs_A");
            testCase.verifyEqual(result.Value.Efflux, 10);
            testCase.verifyEqual( ...
                stoichiometry{"r1", :}, [1, -1, 0, 0]);

        end

        function reportsFragmentsContainingSelectedNaNValues(testCase)

            validator = openmebius.mfa.MFAInputValidator();

            result = validator.validateMDV( ...
                [0.2, 0.3; NaN, 0.5; NaN, 0.7; NaN, 0.9], ...
                ["A"; "B"; "B"; "ignored"], ...
                [true; true; true; false]);

            testCase.verifyFalse(result.IsValid);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                "MDV experimental data contains NaN values in the " + ...
                "following fragments: B.");

        end

        function acceptsFiniteSelectedMDVValues(testCase)

            validator = openmebius.mfa.MFAInputValidator();

            result = validator.validateMDV( ...
                [0.2, 0.3; NaN, NaN], ...
                ["A"; "unused"], ...
                [true; false]);

            testCase.verifyTrue(result.IsValid);

        end

        function rejectsMismatchedMDVMetadata(testCase)

            validator = openmebius.mfa.MFAInputValidator();

            result = validator.validateMDV( ...
                [0.2; 0.8], "A", [true; true]);

            testCase.verifyFalse(result.IsValid);
            testCase.verifyEqual( ...
                result.ErrorMessage, ...
                "MDV fragment labels and mask must match the " + ...
                "experimental data row count.");

        end

    end

    methods (Static, Access = private)

        function experiments = experiments(growthRate, uptakeValues)

            rowNames = {'E1', 'E2'};
            info = table( ...
                growthRate, ...
                VariableNames = {'mu'}, ...
                RowNames = rowNames);
            uptake = array2table( ...
                uptakeValues, ...
                VariableNames = {'A', 'B'}, ...
                RowNames = rowNames);
            experiments = ...
                helpers.MFAInputValidationExperimentsStub( ...
                info, uptake);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

        function model = reversibleExchangeModel()

            rowNames = {'r1'; 'r2'};
            modelTable = table( ...
                {'Subs_A <=> A'; 'A --> Product'}, ...
                {'a <=> a'; 'a --> a'}, ...
                false(2, 1), ...
                VariableNames = [ ...
                "Reaction", "Transition", "Independent"], ...
                RowNames = rowNames);
            reactions = table( ...
                {{'Subs_A'}; {'A'}}, ...
                {{'A'}; {'Product'}}, ...
                [true; false], ...
                false(2, 1), ...
                VariableNames = [ ...
                "Reactants", "Products", "Reversible", ...
                "Independent"], ...
                RowNames = rowNames);
            transitions = table( ...
                {{'a'}; {'a'}}, ...
                {{'a'}; {'a'}}, ...
                [true; false], ...
                VariableNames = [ ...
                "Reactants", "Products", "Reversible"], ...
                RowNames = rowNames);
            metabolites = table( ...
                ["A"; "Subs_A"; "Product"], ...
                ["metabolite"; "substrate"; "product"], ...
                VariableNames = ["Metabolite", "Type"]);
            biomass = table({'A'}, 1, ...
                VariableNames = ["Precursor", "Biomass"]);
            reactionIndex = openmebius.domain.model ...
                .StoichiometricReactionIndex( ...
                modelTable, reactions, transitions);
            constraints = openmebius.mfa ...
                .StoichiometricMatrixBuilder() ...
                .build(reactionIndex, metabolites, biomass);
            model = openmebius.domain.model ...
                .StoichiometricNetwork( ...
                reactionIndex, constraints, metabolites);

        end

    end

end
