classdef MFAInputSnapshotWriterTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAInputSnapshotWriterTest.sourcePath());

        end

    end

    methods (Test)

        function createsBackwardCompatibleGeneralCheckpoint(testCase)

            writer = ...
                openmebius.infrastructure.result.MFAInputSnapshotWriter();
            checkpoint = writer.createGeneralCheckpoint( ...
                [1, 0, 0, 0], ...
                'batch-1', ...
                [0.2; 0.8], ...
                {'A'; 'B'}, ...
                [true; false]);

            testCase.verifyEqual(checkpoint.Value.status, [1, 0, 0, 0]);
            testCase.verifyEqual(checkpoint.Value.ID, 'batch-1');
            testCase.verifyEqual(checkpoint.Value.MDVExp, [0.2; 0.8]);
            testCase.verifyEqual(checkpoint.Value.MDVFragList, {'A'; 'B'});
            testCase.verifyEqual( ...
                checkpoint.Value.MDVFragMask, [true; false]);

        end

        function writesGeneralDatasetsAndTypes(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = MFAInputSnapshotWriterTest.writer(repository);
            checkpoint = writer.createGeneralCheckpoint( ...
                [1, 0, 0, 0], ...
                'batch-1', ...
                [0.2; 0.8], ...
                {'A'; 'B'}, ...
                [true; false]);

            [isSuccess, message] = writer.writeGeneral( ...
                "result.h5", checkpoint);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/status"; "/ID"; "/MDVExp"; ...
                "/MDVFragList"; "/MDVFragMask"]);
            testCase.verifyEqual(repository.Values{1}, int8([1, 0, 0, 0]));
            testCase.verifyEqual(repository.Values{2}, "batch-1");
            testCase.verifyEqual(repository.Values{4}, ["A"; "B"]);
            testCase.verifyEqual(repository.Values{5}, int8([true; false]));
            testCase.verifyEqual(repository.DataTypes, [ ...
                "int8"; "string"; "double"; "string"; "int8"]);

        end

        function createsBackwardCompatibleModelCheckpoint(testCase)

            [modelTable, reversibleModelTable] = ...
                MFAInputSnapshotWriterTest.modelTables();
            writer = ...
                openmebius.infrastructure.result.MFAInputSnapshotWriter();
            checkpoint = writer.createModelCheckpoint( ...
                modelTable, reversibleModelTable);

            testCase.verifyEqual(checkpoint.DataPath, "/model");
            testCase.verifyEqual(checkpoint.Value.modelID, ["R1"; "R2"]);
            testCase.verifyEqual( ...
                checkpoint.Value.modelReaction, ["A -> B"; "B -> C"]);
            testCase.verifyEqual( ...
                checkpoint.Value.modelIndependent, [true; false]);
            testCase.verifyEqual(checkpoint.Value.modelRevID, "R1_rev");

        end

        function writesModelDatasetsAndTypes(testCase)

            [modelTable, reversibleModelTable] = ...
                MFAInputSnapshotWriterTest.modelTables();
            repository = helpers.RecordingDatasetRepository();
            writer = MFAInputSnapshotWriterTest.writer(repository);
            checkpoint = writer.createModelCheckpoint( ...
                modelTable, reversibleModelTable);

            [isSuccess, message] = writer.writeModel( ...
                "result.h5", checkpoint);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/model/modelID"; ...
                "/model/modelReaction"; ...
                "/model/modelTransition"; ...
                "/model/modelIndependent"; ...
                "/model/modelRevID"; ...
                "/model/modelReactionRev"; ...
                "/model/modelTransitionRev"; ...
                "/model/modelIndependentRev"]);
            testCase.verifyEqual(repository.Values{4}, int8([true; false]));
            testCase.verifyEqual(repository.Values{8}, int8(true));
            testCase.verifyEqual(repository.DataTypes, [ ...
                "string"; "string"; "string"; "int8"; ...
                "string"; "string"; "string"; "int8"]);

        end

    end

    methods (Static, Access = private)

        function writer = writer(repository)

            writer = ...
                openmebius.infrastructure.result.MFAInputSnapshotWriter( ...
                Repository = repository);

        end

        function [modelTable, reversibleModelTable] = modelTables()

            modelTable = table( ...
                ["A -> B"; "B -> C"], ...
                ["a:b"; "b:c"], ...
                [true; false], ...
                VariableNames = ...
                {'Reaction', 'Transition', 'Independent'}, ...
                RowNames = {'R1', 'R2'});
            reversibleModelTable = table( ...
                "B -> A", ...
                "b:a", ...
                true, ...
                VariableNames = ...
                {'Reaction', 'Transition', 'Independent'}, ...
                RowNames = {'R1_rev'});

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
