classdef MFAIterationApplicationWorkflowTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAIterationApplicationWorkflowTest.sourcePath());

        end

    end

    methods (Test)

        function successfulRunBuildsTypedInputAndStoresResult(testCase)

            fixture = ...
                MFAIterationApplicationWorkflowTest.createFixture();
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                fixture.Settings, ...
                fixture.Specification, ...
                fixture.Context, ...
                fixture.Session, ...
                fixture.InputPreparation, ...
                ProgressReporter = ...
                    @(iteration, total) ...
                    fixture.Progress.reportProgress( ...
                    iteration, total));

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual( ...
                result.WorkflowResult.ObjectiveValues, 6);
            testCase.verifyEqual( ...
                fixture.Context.WorkflowResult, ...
                result.WorkflowResult);
            testCase.verifyEqual(fixture.Session.Calls, "iteration");
            testCase.verifyEqual(fixture.Progress.ProgressIndices, 1);
            testCase.verifyEqual(fixture.IterationService.CallCount, 1);
            testCase.verifyClass( ...
                fixture.IterationService.LastInput, ...
                'openmebius.mfa.MFAIterationInput');
            testCase.verifyEqual( ...
                fixture.IterationService.LastInput.analysisMode(), ...
                openmebius.mfa.MFAAnalysisMode.SteadyState);

        end

        function instationaryRunCreatesTypedInput(testCase)

            fixture = ...
                MFAIterationApplicationWorkflowTest.createFixture( ...
                Instationary = true);
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                fixture.Settings, ...
                fixture.Specification, ...
                fixture.Context, ...
                fixture.Session, ...
                fixture.InputPreparation);

            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual( ...
                fixture.InstationaryInputFactory.CallCount, 1);
            testCase.verifyClass( ...
                fixture.InstationaryInputFactory.LastSpecification, ...
                'openmebius.mfa.InstationaryInputSpecification');
            testCase.verifyEqual( ...
                fixture.Context.InstationaryInput.PoolSizes, [2; 4]);
            testCase.verifyEqual( ...
                fixture.IterationService.LastInput.analysisMode(), ...
                openmebius.mfa.MFAAnalysisMode.Instationary);

        end

        function invalidInstationaryConfigurationReturnsFailure(testCase)

            fixture = ...
                MFAIterationApplicationWorkflowTest.createFixture( ...
                Instationary = true);
            fixture.Specification = [];
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                fixture.Settings, ...
                fixture.Specification, ...
                fixture.Context, ...
                fixture.Session, ...
                fixture.InputPreparation, ...
                MessageReporter = ...
                    @(level, message) ...
                    fixture.Messages.report(level, message));

            testCase.verifyTrue(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual( ...
                result.FailureStage, "instationary");
            testCase.verifyEmpty(result.WorkflowResult);
            testCase.verifyEqual(fixture.IterationService.CallCount, 0);
            testCase.verifyEmpty(fixture.Context.WorkflowResult);
            testCase.verifyTrue(any(contains( ...
                fixture.Messages.Messages, ...
                "Input specification is required")));

        end

        function cancellationIsReturnedAndStored(testCase)

            fixture = ...
                MFAIterationApplicationWorkflowTest.createFixture( ...
                RightHandSides = [4, 6; 5, 7]);
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                fixture.Settings, ...
                fixture.Specification, ...
                fixture.Context, ...
                fixture.Session, ...
                fixture.InputPreparation, ...
                CancellationRequested = ...
                    @() fixture.IterationService.CallCount >= 1);

            testCase.verifyFalse(result.IsError);
            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyEqual( ...
                result.WorkflowResult.CompletedCount, 1);
            testCase.verifyEqual( ...
                fixture.Context.WorkflowResult, ...
                result.WorkflowResult);
            testCase.verifyEqual(fixture.Session.Calls, "iteration");

        end

        function parallelRunStoresCompletedIterationsOnClient(testCase)

            fixture = ...
                MFAIterationApplicationWorkflowTest.createFixture( ...
                RightHandSides = [4, 6; 5, 7]);
            cleanup = onCleanup(@() ...
                MFAIterationApplicationWorkflowTest.deleteCurrentPool());
            result = fixture.Workflow.run( ...
                fixture.Model, ...
                fixture.Settings, ...
                fixture.Specification, ...
                fixture.Context, ...
                fixture.Session, ...
                fixture.InputPreparation, ...
                UseParallel = true, ...
                WorkerCount = 2, ...
                MessageReporter = @(level, message) ...
                fixture.Messages.report(level, message), ...
                ProgressReporter = @(iteration, total) ...
                fixture.Progress.reportProgress(iteration, total));

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.WorkflowResult.CompletedCount, 2);
            testCase.verifyEqual( ...
                fixture.Progress.ProgressIndices, [1, 2]);
            testCase.verifyEqual( ...
                fixture.Progress.ProgressTotals, [2, 2]);
            testCase.verifyEqual( ...
                fixture.Session.Calls, ["iteration"; "iteration"]);
            [~, logicalProcessors] = openmebius.mfa ...
                .GridSearchParallelPoolManager.processorCounts();
            expectedWorkers = min([logicalProcessors, 2, 2]);
            pool = gcp("nocreate");
            testCase.verifyEqual(pool.NumWorkers, expectedWorkers);
            resourceMessage = fixture.Messages.Messages(contains( ...
                fixture.Messages.Messages, "Optimization resources:"));
            testCase.verifyTrue(contains( ...
                resourceMessage, "workers=" + string(expectedWorkers)));

        end

        function failedResultRequiresFailureStage(testCase)

            testCase.verifyError( ...
                @() openmebius.application.analysis ...
                .MFAIterationApplicationResult(IsError = true), ...
                "OpenMebius2:MFAIterationApplication:" + ...
                "MissingFailureStage");

        end

    end

    methods (Static, Access = private)

        function fixture = createFixture(options)

            arguments
                options.Instationary (1, 1) logical = false
                options.RightHandSides (:, :) double = [4; 5]
            end

            experimentalData = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = [0.2; 0.8], ...
                FragmentLabels = ["fragment"; "fragment"], ...
                FragmentMask = [true; true]);
            inputPreparation = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = 0.1, ...
                SubstrateList = "A", ...
                Efflux = 10, ...
                EffluxStandardDeviation = 1, ...
                EffluxFree = false, ...
                ExperimentalData = experimentalData);
            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = options.RightHandSides(:, 1), ...
                LowerBounds = [0; 1], ...
                UpperBounds = [2; 3], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);
            initialResult = openmebius.mfa ...
                .InitialFluxWorkflowResult( ...
                Problem = problem, ...
                Fluxes = repmat( ...
                    [1; 2], 1, size(options.RightHandSides, 2)), ...
                RightHandSides = options.RightHandSides, ...
                ObjectiveValues = ...
                    1:size(options.RightHandSides, 2));
            iterationResult = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 1, ...
                Flux = [7; 8], ...
                MDV = [0.3; 0.7], ...
                ObjectiveValue = 6, ...
                ExitFlag = 1);
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            context.setExperimentalData(experimentalData);
            context.setSubstrateEMUs({1});
            context.setInitialResult(initialResult);
            iterationService = ...
                helpers.MFAIterationServiceStub(iterationResult);
            instationaryInputFactory = ...
                helpers.InstationaryInputFactorySpy();
            workflow = openmebius.application.analysis ...
                .MFAIterationApplicationWorkflow( ...
                MFAIterationService = iterationService, ...
                InstationaryInputFactory = ...
                    instationaryInputFactory);
            analysisMode = openmebius.mfa.MFAAnalysisMode.SteadyState;
            specification = [];

            if options.Instationary
                analysisMode = ...
                    openmebius.mfa.MFAAnalysisMode.Instationary;
                specification = openmebius.mfa ...
                    .InstationaryInputSpecification( ...
                    PoolMetabolites = ["A"; "B"], ...
                    PoolSizes = [2; 4], ...
                    TimePoints = [0; 1]);
            end

            fixture = struct;
            fixture.Workflow = workflow;
            fixture.Model = helpers.FluxDistributionModelStub();
            fixture.Settings = openmebius.mfa.MFAIterationSettings( ...
                AnalysisMode = analysisMode);
            fixture.Specification = specification;
            fixture.Context = context;
            fixture.Session = helpers.MFAResultSessionStub();
            fixture.InputPreparation = inputPreparation;
            fixture.IterationService = iterationService;
            fixture.InstationaryInputFactory = ...
                instationaryInputFactory;
            fixture.Messages = helpers.AnalysisMessageObserverStub();
            fixture.Progress = helpers.MFAWorkflowObserverStub();

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

        function deleteCurrentPool()

            pool = gcp("nocreate");

            if ~isempty(pool)
                delete(pool);
            end

        end

    end

end
