classdef MFAIterationSettingsTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAIterationSettingsTest.sourcePath());

        end

    end

    methods (Test)

        function suppliesTypedDefaults(testCase)

            settings = openmebius.mfa.MFAIterationSettings();

            testCase.verifyEqual( ...
                settings.AnalysisMode, ...
                openmebius.mfa.MFAAnalysisMode.SteadyState);
            testCase.verifyEqual( ...
                settings.OptimizationMethod, ...
                openmebius.mfa.MFAOptimizationMethod.GradientOnly);
            testCase.verifyClass( ...
                settings.SolverOptions, ...
                'openmebius.mfa.SteadyStateOptions');
            testCase.verifyEmpty(settings.OptionWarnings);

        end

        function replacesAnalysisModeWithoutChangingSolverSettings( ...
                testCase)

            settings = openmebius.mfa.MFAIterationSettings( ...
                AnalysisMode = ...
                openmebius.mfa.MFAAnalysisMode.Instationary, ...
                OptimizationMethod = openmebius.mfa ...
                .MFAOptimizationMethod.HybridGAGradient, ...
                SolverOptions = openmebius.mfa.SteadyStateOptions( ...
                MaxIterations = 321), ...
                OptionWarnings = "warning");

            steadySettings = settings.withAnalysisMode( ...
                openmebius.mfa.MFAAnalysisMode.SteadyState);

            testCase.verifyEqual( ...
                steadySettings.AnalysisMode, ...
                openmebius.mfa.MFAAnalysisMode.SteadyState);
            testCase.verifyEqual( ...
                steadySettings.OptimizationMethod, ...
                openmebius.mfa.MFAOptimizationMethod ...
                .HybridGAGradient);
            testCase.verifyEqual( ...
                steadySettings.SolverOptions.MaxIterations, 321);
            testCase.verifyEqual( ...
                steadySettings.OptionWarnings, "warning");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
