classdef MFAIterationServiceTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAIterationServiceTest.sourcePath());

        end

    end

    methods (Test)

        function inputProvidesArrangedSteadyStateData(testCase)

            input = MFAIterationServiceTest.createInput();

            testCase.verifyFalse(input.usesInstationaryMFA());
            testCase.verifyEqual(input.arrangedExperimentalMDV(), 0.8);

        end

        function instationaryInputIsRequiredWhenEnabled(testCase)

            settings = openmebius.mfa.MFAIterationSettings( ...
                UseInstationaryMFA = true);

            testCase.verifyError( ...
                @() MFAIterationServiceTest.createInput( ...
                    Settings = settings), ...
                "OpenMebius2:MFAIterationInput:" + ...
                "MissingInstationaryInput");

        end

        function forcedSteadyStateDoesNotRequireInstationaryInput( ...
                testCase)

            input = MFAIterationServiceTest.createInput( ...
                Settings = openmebius.mfa.MFAIterationSettings( ...
                UseInstationaryMFA = true), ...
                ForceSteadyState = true);

            testCase.verifyFalse(input.usesInstationaryMFA());

        end

        function serviceRunsWithoutApplicationContext(testCase)

            expected = MFAIterationServiceTest.iterationResult();
            runner = helpers.MFAIterationRunnerStub(expected);
            service = openmebius.mfa.MFAIterationService( ...
                Runner = runner, ...
                EffluxPenaltyFactory = ...
                    helpers.EffluxPenaltyFactoryStub());

            actual = service.run( ...
                MFAIterationServiceTest.createInput());

            testCase.verifyEqual(actual, expected);
            testCase.verifyEqual(runner.CallCount, 1);
            testCase.verifyClass( ...
                runner.LastObjective, ...
                'openmebius.mfa.SteadyStateObjective');
            testCase.verifyEqual( ...
                runner.LastRightHandSide, [5; 0]);

        end

        function serviceBuildsInstationaryObjective(testCase)

            expected = MFAIterationServiceTest.iterationResult();
            runner = helpers.MFAIterationRunnerStub(expected);
            service = openmebius.mfa.MFAIterationService( ...
                Runner = runner, ...
                EffluxPenaltyFactory = ...
                    helpers.EffluxPenaltyFactoryStub());
            instationaryInput = openmebius.mfa.InstationaryInput( ...
                PoolSizes = 1, ...
                TimePoints = [0; 1]);
            input = MFAIterationServiceTest.createInput( ...
                Settings = openmebius.mfa.MFAIterationSettings( ...
                UseInstationaryMFA = true), ...
                ExperimentalMDV = [0.8, 0.7], ...
                InstationaryInput = instationaryInput);

            service.run(input);

            testCase.verifyClass( ...
                runner.LastObjective, ...
                'openmebius.mfa.InstationaryObjective');

        end

        function serviceUsesTypedSettings(testCase)

            runner = helpers.MFAIterationRunnerStub( ...
                MFAIterationServiceTest.iterationResult());
            service = openmebius.mfa.MFAIterationService( ...
                Runner = runner, ...
                EffluxPenaltyFactory = ...
                    helpers.EffluxPenaltyFactoryStub());
            observer = helpers.AnalysisMessageObserverStub();
            settings = openmebius.mfa.MFAIterationSettings( ...
                UseInstationaryMFA = false, ...
                OptimizationMethod = "custom", ...
                SolverOptions = openmebius.mfa.SteadyStateOptions( ...
                MaxIterations = 321), ...
                OptionWarnings = "solver option warning");

            service.run( ...
                MFAIterationServiceTest.createInput( ...
                Settings = settings), ...
                MessageReporter = @(level, message) ...
                observer.report(level, message));

            testCase.verifyEqual(runner.LastOptions.MaxIterations, 321);
            testCase.verifyEqual( ...
                observer.Levels(1:2), ["warning"; "warning"]);
            testCase.verifyEqual( ...
                observer.Messages(1), ...
                "Unknown optimizationMethod 'custom'. " + ...
                "Using FMINCON only.");
            testCase.verifyEqual( ...
                observer.Messages(2), "solver option warning");

        end

        function serviceSourceHasNoApplicationDependency(testCase)

            serviceFile = which( ...
                'openmebius.mfa.MFAIterationService');
            source = fileread(serviceFile);

            testCase.verifyFalse(contains( ...
                string(source), 'openmebius.application'));
            testCase.verifyFalse(contains( ...
                string(source), 'MFAAnalysisRunContext'));
            testCase.verifyFalse(contains( ...
                string(source), 'SteadyStateObjective('));
            testCase.verifyFalse(contains( ...
                string(source), 'InstationaryObjective('));

        end

    end

    methods (Static, Access = private)

        function input = createInput(options)

            arguments
                options.Settings (1, 1) ...
                    openmebius.mfa.MFAIterationSettings = ...
                    openmebius.mfa.MFAIterationSettings( ...
                    UseInstationaryMFA = false)
                options.ForceSteadyState (1, 1) logical = false
                options.ExperimentalMDV double = 0.8
                options.InstationaryInput = []
            end

            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = options.ExperimentalMDV, ...
                FragmentLabels = "M0", ...
                FragmentMask = true);
            input = openmebius.mfa.MFAIterationInput( ...
                Settings = options.Settings, ...
                Problem = MFAIterationServiceTest.problem(), ...
                Model = helpers.InitialFluxModelStub(), ...
                ExperimentalData = data, ...
                ExperimentalMDV = data.ExperimentalMDV, ...
                RightHandSide = [5; 0], ...
                SubstrateEMUs = {1}, ...
                SubstrateList = "A", ...
                Efflux = 1, ...
                EffluxStandardDeviation = 0.1, ...
                EffluxFree = false, ...
                InstationaryInput = options.InstationaryInput, ...
                ForceSteadyState = options.ForceSteadyState);

        end

        function problem = problem()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);

        end

        function result = iterationResult()

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 0.5, ...
                Flux = [5; 0.5], ...
                MDV = 0.8, ...
                ObjectiveValue = 1, ...
                ExitFlag = 1);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
