classdef MFAIterationSettingsMapperTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAIterationSettingsMapperTest.sourcePath());

        end

    end

    methods (Test)

        function mapsBatchConfigToTypedSettings(testCase)

            config = struct;
            config.isINSTMFA = true;
            config.optimizationMethod = "hybrid";
            config.algorithm = "IPMs";
            config.fmincon.maxIterations = 321;
            config.fmincon.enforceFluxBounds = true;

            settings = openmebius.application.analysis ...
                .MFAIterationSettingsMapper.fromBatchConfig(config);

            testCase.verifyEqual( ...
                settings.AnalysisMode, ...
                openmebius.mfa.MFAAnalysisMode.Instationary);
            testCase.verifyTrue(settings.AnalysisMode.isInstationary());
            testCase.verifyEqual( ...
                settings.OptimizationMethod, ...
                openmebius.mfa.MFAOptimizationMethod ...
                .HybridGAGradient);
            testCase.verifyTrue( ...
                settings.OptimizationMethod.usesHybridGA());
            testCase.verifyEqual( ...
                settings.SolverOptions.Algorithm, "interior-point");
            testCase.verifyEqual( ...
                settings.SolverOptions.MaxIterations, 321);
            testCase.verifyTrue( ...
                settings.SolverOptions.EnforceFluxBounds);
            testCase.verifyEmpty(settings.OptionWarnings);

        end

        function normalizesLocalOptimizationAliases(testCase)

            for method = ["gradient-only", "fmincon", "local"]
                settings = openmebius.application.analysis ...
                    .MFAIterationSettingsMapper.fromBatchConfig( ...
                    struct( ...
                    isINSTMFA = false, ...
                    optimizationMethod = method));

                testCase.verifyEqual( ...
                    settings.OptimizationMethod, ...
                    openmebius.mfa.MFAOptimizationMethod.GradientOnly);
            end

        end

        function mapsUnknownMethodToGradientAndWarnings(testCase)

            settings = openmebius.application.analysis ...
                .MFAIterationSettingsMapper.fromBatchConfig(struct( ...
                isINSTMFA = false, ...
                optimizationMethod = "custom", ...
                algorithm = "not-an-algorithm"));

            testCase.verifyEqual( ...
                settings.OptimizationMethod, ...
                openmebius.mfa.MFAOptimizationMethod.GradientOnly);
            testCase.verifyEqual( ...
                settings.OptionWarnings, ...
                ["Unknown optimizationMethod 'custom'. " + ...
                "Using FMINCON only."; ...
                "Unknown FMINCON algorithm 'not-an-algorithm'. " + ...
                "Using sqp."]);

        end

        function requiresExplicitAnalysisMode(testCase)

            testCase.verifyError( ...
                @() openmebius.application.analysis ...
                .MFAIterationSettingsMapper.fromBatchConfig(struct), ...
                "OpenMebius2:MFAIterationSettingsMapper:" + ...
                "InvalidAnalysisMode");

        end

        function rejectsNonlogicalNumericAnalysisMode(testCase)

            testCase.verifyError( ...
                @() openmebius.application.analysis ...
                .MFAIterationSettingsMapper.fromBatchConfig( ...
                struct(isINSTMFA = 2)), ...
                "OpenMebius2:MFAIterationSettingsMapper:" + ...
                "InvalidAnalysisMode");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
