classdef MFAInitialFluxApplicationWorkflowTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAInitialFluxApplicationWorkflowTest.sourcePath());

        end

    end

    methods (Test)

        function preparesTypedInputAndStoresSuccessfulResult(testCase)

            fixture = ...
                MFAInitialFluxApplicationWorkflowTest.createFixture();

            result = fixture.Workflow.run( ...
                fixture.Model, ...
                [], ...
                [1; 2], ...
                openmebius.mfa.InitialFluxSettings( ...
                IterationCount = 1), ...
                fixture.Context, ...
                fixture.InputPreparation, ...
                MessageReporter = ...
                @(level, message) ...
                fixture.Messages.report(level, message));

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(fixture.InitialWorkflow.CallCount, 1);
            testCase.verifyEqual( ...
                fixture.Context.SubstrateEMUs, {1; 2});
            testCase.verifyEqual( ...
                fixture.Context.InitialResult, result);
            testCase.verifyEqual( ...
                fixture.InitialWorkflow.LastInput.RightHandSide, [4; 5]);
            testCase.verifyEqual( ...
                fixture.InitialWorkflow.LastInput.LowerBounds, [0; 1]);
            testCase.verifyEqual( ...
                fixture.InitialWorkflow.LastInput.UpperBounds, [2; 3]);
            testCase.verifyEqual( ...
                fixture.InitialWorkflow.LastInput.SubstrateEMUs, {1; 2});
            testCase.verifyClass( ...
                fixture.InitialWorkflow.LastInput.Settings, ...
            'openmebius.mfa.InitialFluxSettings');
            testCase.verifyClass( ...
                fixture.InitialWorkflow.LastInput.EffluxProfile, ...
            'openmebius.mfa.EffluxPerturbationProfile');
            testCase.verifyEmpty( ...
                fixture.InitialWorkflow.LastInput ...
                .ReversibleReactionIndices);
            testCase.verifyEmpty(fixture.Messages.Messages);

        end

        function reportsInvalidInitialFluxInput(testCase)

            fixture = ...
                MFAInitialFluxApplicationWorkflowTest.createFixture();
            fixture.Context.setRightHandSide(4);

            result = fixture.Workflow.run( ...
                fixture.Model, ...
                [], ...
                1, ...
                openmebius.mfa.InitialFluxSettings( ...
                IterationCount = 1), ...
                fixture.Context, ...
                fixture.InputPreparation, ...
                MessageReporter = ...
                @(level, message) ...
                fixture.Messages.report(level, message));

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(fixture.InitialWorkflow.CallCount, 0);
            testCase.verifyEmpty(fixture.Context.InitialResult);
            testCase.verifyEqual(fixture.Messages.Levels, "error");
            testCase.verifyTrue(contains( ...
                fixture.Messages.Messages, ...
            "vectors must match"));

        end

        function doesNotStoreCanceledResult(testCase)

            fixture = ...
                MFAInitialFluxApplicationWorkflowTest.createFixture( ...
                IsCanceled = true);

            result = fixture.Workflow.run( ...
                fixture.Model, ...
                [], ...
                1, ...
                openmebius.mfa.InitialFluxSettings( ...
                IterationCount = 1), ...
                fixture.Context, ...
                fixture.InputPreparation);

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyEmpty(fixture.Context.InitialResult);

        end

    end

    methods (Static, Access = private)

        function fixture = createFixture(options)

            arguments
                options.IsCanceled (1, 1) logical = false
            end

            model = helpers.FluxDistributionModelStub();
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = [0.2; 0.8], ...
                FragmentLabels = ["fragment"; "fragment"], ...
                FragmentMask = [true; true]);
            inputPreparation = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = 0.1, ...
                SubstrateList = "A", ...
                Efflux = 10, ...
                EffluxStandardDeviation = 1, ...
                EffluxFree = false, ...
                ExperimentalData = data);
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            context.setExperimentalData(data);
            context.setRightHandSide([4; 5]);
            context.setBounds([0; 1], [2; 3]);
            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [4; 5], ...
                LowerBounds = [0; 1], ...
                UpperBounds = [2; 3], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);

            if options.IsCanceled
                initialResult = openmebius.mfa ...
                    .InitialFluxWorkflowResult.canceled( ...
                    Problem = problem);
            else
                initialResult = openmebius.mfa ...
                    .InitialFluxWorkflowResult.success( ...
                    Problem = problem, ...
                    Fluxes = [1; 2], ...
                    RightHandSides = [4; 5], ...
                    ObjectiveValues = 5);
            end

            initialWorkflow = ...
                helpers.InitialFluxWorkflowSpy(initialResult);
            workflow = openmebius.application.analysis ...
                .MFAInitialFluxApplicationWorkflow( ...
                InitialFluxWorkflow = initialWorkflow, ...
                SubstrateEMUFactory = ...
                helpers.SubstrateEMUFactoryStub(), ...
                EffluxPenaltyFactory = ...
                helpers.EffluxPenaltyFactoryStub());
            fixture = struct( ...
                Workflow = workflow, ...
                InitialWorkflow = initialWorkflow, ...
                Model = model, ...
                Context = context, ...
                InputPreparation = inputPreparation, ...
                Messages = helpers.AnalysisMessageObserverStub());

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
            'src');

        end

    end

end
