classdef MFAInputPreparationWorkflowTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAInputPreparationWorkflowTest.sourcePath());

        end

    end

    methods (Test)

        function preparesValidatedInputsAndExperimentalData(testCase)

            [workflow, validator, builder, observer, data] = ...
                MFAInputPreparationWorkflowTest.createWorkflow();

            result = workflow.run( ...
                1, 2, "E1", ...
                MFAInputPreparationWorkflowTest.config(false), ...
                MessageReporter = ...
                @(level, message) observer.report(level, message));

            testCase.verifyTrue(result.IsValid);
            testCase.verifyEqual(result.GrowthRate, 0.2);
            testCase.verifyEqual(result.SubstrateList, ["A"; "B"]);
            testCase.verifyEqual(result.Efflux, [10; 2]);
            testCase.verifyEqual(result.ExperimentalData, data);
            testCase.verifyEmpty(result.EffluxFreeSession);
            testCase.verifyEqual(validator.EffluxCallCount, 1);
            testCase.verifyEqual(validator.MDVCallCount, 1);
            testCase.verifyEqual(builder.CallCount, 1);
            testCase.verifyEmpty(observer.Messages);

        end

        function stopsAfterEffluxValidationFailure(testCase)

            failure = openmebius.mfa.MFAInputValidationResult ...
                .failure("efflux invalid");
            validator = helpers.MFAInputValidatorStub( ...
                failure, ...
                openmebius.mfa.MFAInputValidationResult.success());
            builder = helpers.MFAExperimentalDataBuilderStub([]);
            observer = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.application.analysis ...
                .MFAInputPreparationWorkflow( ...
                Validator = validator, ...
                ExperimentalDataBuilder = builder);

            result = workflow.run( ...
                1, 2, "E1", ...
                MFAInputPreparationWorkflowTest.config(false), ...
                MessageReporter = ...
                @(level, message) observer.report(level, message));

            testCase.verifyFalse(result.IsValid);
            testCase.verifyEqual(result.FailureStage, "efflux");
            testCase.verifyEqual(result.ErrorMessage, "efflux invalid");
            testCase.verifyEqual(builder.CallCount, 0);
            testCase.verifyEqual(validator.MDVCallCount, 0);
            testCase.verifyEqual(observer.Levels, "error");
            testCase.verifyEqual(observer.Messages, "efflux invalid");

        end

        function ownsAndRestoresEffluxFreeSession(testCase)

            session = helpers.EffluxFreeSessionStub();
            factory = helpers.EffluxFreeSessionFactoryStub(session);
            observer = helpers.AnalysisMessageObserverStub();
            [workflow, ~, ~] = ...
                MFAInputPreparationWorkflowTest.createWorkflow( ...
                EffluxFreeSessionFactory = ...
                @(model, substrates, reporter) ...
                factory.create(model, substrates, reporter));

            result = workflow.run( ...
                1, 2, "E1", ...
                MFAInputPreparationWorkflowTest.config(true), ...
                MessageReporter = ...
                @(level, message) observer.report(level, message));

            testCase.verifyTrue(result.IsValid);
            testCase.verifyEqual(factory.CallCount, 1);
            testCase.verifyEqual(factory.Substrates, "B");
            testCase.verifyEqual(observer.Levels, "info");
            testCase.verifyEqual( ...
                observer.Messages, ...
                "Efflux reactions were set as free variables: B.");

            result.restoreModel();
            result.restoreModel();

            testCase.verifyTrue(session.IsRestored);
            testCase.verifyEqual(session.RestoreCount, 1);

        end

        function reportsMDVValidationFailure(testCase)

            mdvFailure = openmebius.mfa.MFAInputValidationResult ...
                .failure("mdv invalid");
            [workflow, validator, builder, observer, data] = ...
                MFAInputPreparationWorkflowTest.createWorkflow( ...
                MDVResult = mdvFailure);

            result = workflow.run( ...
                1, 2, "E1", ...
                MFAInputPreparationWorkflowTest.config(false), ...
                MessageReporter = ...
                @(level, message) observer.report(level, message));

            testCase.verifyFalse(result.IsValid);
            testCase.verifyEqual(result.FailureStage, "mdv");
            testCase.verifyEqual(result.ErrorMessage, "mdv invalid");
            testCase.verifyEqual(result.ExperimentalData, data);
            testCase.verifyEqual(validator.MDVCallCount, 1);
            testCase.verifyEqual(builder.CallCount, 1);
            testCase.verifyEqual(observer.Levels, "error");
            testCase.verifyEqual(observer.Messages, "mdv invalid");

        end

        function restoresSessionWhenMDVConstructionThrows(testCase)

            session = helpers.EffluxFreeSessionStub();
            factory = helpers.EffluxFreeSessionFactoryStub(session);
            [workflow, ~, builder] = ...
                MFAInputPreparationWorkflowTest.createWorkflow( ...
                EffluxFreeSessionFactory = ...
                @(model, substrates, reporter) ...
                factory.create(model, substrates, reporter));
            builder.ErrorIdentifier = ...
                "helpers:MFAExperimentalDataBuilderStub:Failure";

            testCase.verifyError( ...
                @() workflow.run( ...
                1, 2, "E1", ...
                MFAInputPreparationWorkflowTest.config(true)), ...
                "helpers:MFAExperimentalDataBuilderStub:Failure");
            testCase.verifyTrue(session.IsRestored);

        end

        function rejectsInconsistentPreparationResult(testCase)

            testCase.verifyError( ...
                @() openmebius.application.analysis ...
                .MFAInputPreparationResult(IsValid = false), ...
                "OpenMebius2:MFAInputPreparation:InconsistentResult");

        end

    end

    methods (Static, Access = private)

        function [workflow, validator, builder, observer, data] = ...
                createWorkflow(options)

            arguments
                options.MDVResult = ...
                    openmebius.mfa.MFAInputValidationResult.success()
                options.EffluxFreeSessionFactory (1, 1) ...
                    function_handle = @(~, ~, ~) []
            end

            value = struct( ...
                GrowthRate = 0.2, ...
                SubstrateList = ["A"; "B"], ...
                Efflux = [10; 2], ...
                EffluxStandardDeviation = [0.1; 0.2], ...
                EffluxFree = [false; true]);
            validator = helpers.MFAInputValidatorStub( ...
                openmebius.mfa.MFAInputValidationResult.success(value), ...
                options.MDVResult);
            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = [0.2; 0.8], ...
                FragmentLabels = ["M0"; "M1"], ...
                FragmentMask = [true; true]);
            builder = helpers.MFAExperimentalDataBuilderStub(data);
            observer = helpers.AnalysisMessageObserverStub();
            workflow = openmebius.application.analysis ...
                .MFAInputPreparationWorkflow( ...
                Validator = validator, ...
                ExperimentalDataBuilder = builder, ...
                EffluxFreeSessionFactory = ...
                options.EffluxFreeSessionFactory);

        end

        function config = config(isPerturbated)

            config = struct( ...
                perturbateEfflux = isPerturbated, ...
                MS = struct);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
