classdef MFAObjectiveFactoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAObjectiveFactoryTest.sourcePath());

        end

    end

    methods (Test)

        function createsSteadyStateObjective(testCase)

            penaltyFactory = helpers.EffluxPenaltyFactorySpy();
            input = MFAObjectiveFactoryTest.createInput();
            objective = openmebius.mfa.MFAObjectiveFactory( ...
                EffluxPenaltyFactory = penaltyFactory).create(input);

            testCase.verifyClass( ...
                objective, 'openmebius.mfa.SteadyStateObjective');
            testCase.verifyEqual(objective.ExperimentalMDV, 0.8);
            testCase.verifyEqual(objective.RightHandSide, [5; 0]);
            testCase.verifyEqual( ...
                objective.EffluxPenalty, penaltyFactory.Penalty);
            testCase.verifyEqual(penaltyFactory.CallCount, 1);
            testCase.verifyEqual(penaltyFactory.LastModel, input.Model);
            testCase.verifyEqual( ...
                penaltyFactory.LastSubstrateList, "A");
            testCase.verifyEqual(penaltyFactory.LastValues, 1);
            testCase.verifyEqual( ...
                penaltyFactory.LastStandardDeviations, 0.1);
            testCase.verifyFalse(penaltyFactory.LastFreeMask);

        end

        function createsInstationaryObjective(testCase)

            instationaryInput = openmebius.mfa.InstationaryInput( ...
                PoolSizes = 1, ...
                TimePoints = [0; 1]);
            input = MFAObjectiveFactoryTest.createInput( ...
                Settings = openmebius.mfa.MFAIterationSettings( ...
                AnalysisMode = ...
                openmebius.mfa.MFAAnalysisMode.Instationary), ...
                ExperimentalMDV = [0.8, 0.7], ...
                InstationaryInput = instationaryInput);

            objective = openmebius.mfa.MFAObjectiveFactory().create( ...
                input);

            testCase.verifyClass( ...
                objective, 'openmebius.mfa.InstationaryObjective');
            testCase.verifyEqual(objective.Input, instationaryInput);
            testCase.verifyEqual(objective.ExperimentalMDV, [0.8, 0.7]);

        end

    end

    methods (Static, Access = private)

        function input = createInput(options)

            arguments
                options.Settings (1, 1) ...
                    openmebius.mfa.MFAIterationSettings = ...
                    openmebius.mfa.MFAIterationSettings( ...
                    AnalysisMode = ...
                    openmebius.mfa.MFAAnalysisMode.SteadyState)
                options.ExperimentalMDV double = 0.8
                options.InstationaryInput = []
            end

            data = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = options.ExperimentalMDV, ...
                FragmentLabels = "M0", ...
                FragmentMask = true);
            input = openmebius.mfa.MFAIterationInput( ...
                Settings = options.Settings, ...
                Problem = MFAObjectiveFactoryTest.problem(), ...
                Model = helpers.InitialFluxModelStub(), ...
                ExperimentalData = data, ...
                ExperimentalMDV = data.ExperimentalMDV, ...
                RightHandSide = [5; 0], ...
                SubstrateEMUs = {1}, ...
                SubstrateList = "A", ...
                Efflux = 1, ...
                EffluxStandardDeviation = 0.1, ...
                EffluxFree = false, ...
                InstationaryInput = options.InstationaryInput);

        end

        function problem = problem()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = [5; 0], ...
                LowerBounds = [0; 0], ...
                UpperBounds = [10; 1], ...
                IndependentMask = [false; true], ...
                BoundaryReactionMask = [false; true]);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
