classdef MFAProblemFactoryTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAProblemFactoryTest.sourcePath());

        end

    end

    methods (Test)

        function mapsIndependentRowsToNamedReactionColumns(testCase)

            stoichiometry = array2table( ...
                eye(3), ...
                'RowNames', {'constraint', 'C', 'A'}, ...
                'VariableNames', {'A', 'B', 'C'});
            factory = openmebius.mfa.MFAProblemFactory();

            problem = factory.create( ...
                stoichiometry, ...
                ["dependent"; "independent"; "independent"], ...
                zeros(3, 1), ...
                zeros(3, 1), ...
                ones(3, 1));

            testCase.verifyEqual( ...
                problem.IndependentMask, ...
                [false; true; true]);
            testCase.verifyEqual( ...
                problem.BoundaryReactionMask, ...
                [true; false; true]);

        end

        function rejectsSystemTypeDimensionMismatch(testCase)

            stoichiometry = array2table( ...
                eye(2), ...
                'RowNames', {'A', 'B'}, ...
                'VariableNames', {'A', 'B'});
            factory = openmebius.mfa.MFAProblemFactory();

            testCase.verifyError( ...
                @() factory.create( ...
                stoichiometry, ...
                "independent", ...
                zeros(2, 1), ...
                zeros(2, 1), ...
                ones(2, 1)), ...
                "OpenMebius2:MFAProblem:SystemTypeDimensionMismatch");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
