classdef MFAResultCheckpointWriterTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAResultCheckpointWriterTest.sourcePath());

        end

    end

    methods (Test)

        function createsBackwardCompatibleIterationCheckpoint(testCase)

            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter();
            checkpoint = writer.createIterationCheckpoint( ...
                3, ...
                MFAResultCheckpointWriterTest.createIterationResult(), ...
                [1, 2], ...
                TimestampUnix = 123.75);

            testCase.verifyEqual(checkpoint.FieldName, "fluxResult0003");
            testCase.verifyEqual(checkpoint.DataPath, "/fluxResult/0003");
            testCase.verifyEqual(checkpoint.Value.flux, [5; 2; 7]);
            testCase.verifyEqual(checkpoint.Value.fluxFwd, [3; 7]);
            testCase.verifyEqual(checkpoint.Value.RSS, 4.5);
            testCase.verifyEqual( ...
                checkpoint.Value.finiteDifferenceStepSize, 1e-5);
            testCase.verifyEqual( ...
                checkpoint.Value.finiteDifferenceStepSizeCandidates, ...
                [1e-4; 1e-5]);
            testCase.verifyEqual(checkpoint.Value.time, 123.75);

        end

        function writesIterationDatasetsAndTypes(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createIterationCheckpoint( ...
                3, ...
                MFAResultCheckpointWriterTest.createIterationResult(), ...
                [1, 2], ...
                TimestampUnix = 123.75);

            [isSuccess, message] = writer.writeIteration( ...
                "result.h5", checkpoint);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths(1), ...
                "/fluxResult/0003/flux");
            testCase.verifyEqual(repository.Paths(end), ...
                "/fluxResult/0003/time");
            testCase.verifyEqual(repository.Values{end}, int32(123.75));
            testCase.verifyEqual(repository.DataTypes(end), "int32");
            testCase.verifyEqual(numel(repository.Paths), 10);

        end

        function createsBackwardCompatibleFluxVariabilityCheckpoint( ...
                testCase)

            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter();
            checkpoint = writer.createFluxVariabilityCheckpoint( ...
                [1; 0; 4], ...
                [5; 2; 8], ...
                [1, 2], ...
                TimestampUnix = 10.25);

            testCase.verifyEqual(checkpoint.DataPath, "/fluxVariability");
            testCase.verifyEqual(checkpoint.Value.fluxLB, [1; 0; 4]);
            testCase.verifyEqual(checkpoint.Value.fluxUB, [5; 2; 8]);
            testCase.verifyEqual(checkpoint.Value.fluxLBFwd, [-1; 4]);
            testCase.verifyEqual(checkpoint.Value.fluxUBFwd, [5; 8]);
            testCase.verifyEqual(checkpoint.Value.time, 10.25);

        end

        function writesFluxVariabilityDatasetsAndStatus(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createFluxVariabilityCheckpoint( ...
                [1; 0; 4], [5; 2; 8], [1, 2], ...
                TimestampUnix = 10.25);

            [isSuccess, message] = writer.writeFluxVariability( ...
                "result.h5", checkpoint, [0, 0, 0, 0]);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/fluxVariability/fluxLB"; ...
                "/fluxVariability/fluxUB"; ...
                "/fluxVariability/fluxLBFwd"; ...
                "/fluxVariability/fluxUBFwd"; ...
                "/fluxVariability/time"; ...
                "/status"]);
            testCase.verifyEqual(repository.Values{5}, int32(10.25));
            testCase.verifyEqual(repository.Values{6}, int8([0, 0, 0, 0]));
            testCase.verifyEqual(repository.DataTypes, [ ...
                "double"; "double"; "double"; "double"; ...
                "int32"; "int8"]);

        end

        function createsBackwardCompatibleInitialFluxCheckpoint(testCase)

            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter();
            checkpoint = writer.createInitialFluxCheckpoint( ...
                [5, 6; 2, 1; 7, 8], ...
                [0.1, 0.2], ...
                [4.5, 5], ...
                [1, 2], ...
                TimestampUnix = 20.75);

            testCase.verifyEqual(checkpoint.DataPath, "/initialFlux");
            testCase.verifyEqual( ...
                checkpoint.Value.flux, [5, 6; 2, 1; 7, 8]);
            testCase.verifyEqual(checkpoint.Value.fluxFwd, [3, 5; 7, 8]);
            testCase.verifyEqual(checkpoint.Value.rhs, [0.1, 0.2]);
            testCase.verifyEqual(checkpoint.Value.RSS, [4.5, 5]);
            testCase.verifyEqual(checkpoint.Value.time, 20.75);

        end

        function writesInitialFluxDatasetsAndStatus(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createInitialFluxCheckpoint( ...
                [5, 6; 2, 1; 7, 8], ...
                [0.1, 0.2], ...
                [4.5, 5], ...
                [1, 2], ...
                TimestampUnix = 20.75);

            [isSuccess, message] = writer.writeInitialFlux( ...
                "result.h5", checkpoint, [1, 0, 0, 0]);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/initialFlux/flux"; ...
                "/initialFlux/fluxFwd"; ...
                "/initialFlux/rhs"; ...
                "/initialFlux/RSS"; ...
                "/initialFlux/time"; ...
                "/status"]);
            testCase.verifyEqual(repository.Values{5}, int32(20.75));
            testCase.verifyEqual(repository.Values{6}, int8([1, 0, 0, 0]));
            testCase.verifyEqual(repository.DataTypes, [ ...
                "double"; "double"; "double"; "double"; ...
                "int32"; "int8"]);

        end

        function writesWorkflowSummary(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);

            [isSuccess, message] = writer.writeSummary( ...
                "result.h5", [1, 2], [2, 1], [1, 1, 0, 0], 3.84);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual( ...
                repository.Paths, ...
                ["/RSS"; "/RSSIndex"; "/status"; "/threshold"]);
            testCase.verifyEqual(repository.Values{2}, int32([2, 1]));
            testCase.verifyEqual(repository.Values{3}, int8([1, 1, 0, 0]));
            testCase.verifyEqual( ...
                repository.DataTypes, ...
                ["double"; "int32"; "int8"; "double"]);

        end

        function stopsAtFirstRepositoryFailure(testCase)

            repository = helpers.RecordingDatasetRepository();
            repository.FailAt = 2;
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createIterationCheckpoint( ...
                1, MFAResultCheckpointWriterTest.createIterationResult());

            [isSuccess, message] = writer.writeIteration( ...
                "result.h5", checkpoint);

            testCase.verifyFalse(isSuccess);
            testCase.verifyEqual(numel(repository.Paths), 2);
            testCase.verifySubstring(message, repository.Paths(2));

        end

    end

    methods (Static, Access = private)

        function result = createIterationResult()

            search = struct( ...
                candidates = [1e-4; 1e-5], ...
                objectives = [5; 4.5], ...
                exitflags = [1; 1]);
            output = struct( ...
                fminconFiniteDifferenceStepSize = 1e-5, ...
                fminconFiniteDifferenceStepSizeSearch = search);
            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = [5; 2; 7], ...
                Flux = [5; 2; 7], ...
                MDV = [0.2; 0.8], ...
                ObjectiveValue = 4.5, ...
                ExitFlag = 1, ...
                Output = output);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
