classdef MFAResultCheckpointWriterTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(MFAResultCheckpointWriterTest.sourcePath());

        end

    end

    methods (Test)

        function createsBackwardCompatibleIterationCheckpoint(testCase)

            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter();
            checkpoint = writer.createIterationCheckpoint( ...
                3, ...
                MFAResultCheckpointWriterTest.createIterationResult(), ...
                [1, 2], ...
                TimestampUnix = 123.75);

            testCase.verifyEqual(checkpoint.FieldName, "fluxResult0003");
            testCase.verifyEqual(checkpoint.DataPath, "/fluxResult/0003");
            testCase.verifyEqual(checkpoint.Value.flux, [5; 2; 7]);
            testCase.verifyEqual(checkpoint.Value.fluxFwd, [3; 7]);
            testCase.verifyEqual(checkpoint.Value.RSS, 4.5);
            testCase.verifyEqual( ...
                checkpoint.Value.finiteDifferenceStepSize, 1e-5);
            testCase.verifyEqual( ...
                checkpoint.Value.finiteDifferenceStepSizeCandidates, ...
                [1e-4; 1e-5]);
            testCase.verifyEqual(checkpoint.Value.time, 123.75);

        end

        function writesIterationDatasetsAndTypes(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createIterationCheckpoint( ...
                3, ...
                MFAResultCheckpointWriterTest.createIterationResult(), ...
                [1, 2], ...
                TimestampUnix = 123.75);

            [isSuccess, message] = writer.writeIteration( ...
                "result.h5", checkpoint);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths(1), ...
                "/fluxResult/0003/flux");
            testCase.verifyEqual(repository.Paths(end), ...
                "/fluxResult/0003/time");
            testCase.verifyEqual(repository.Values{end}, int32(123.75));
            testCase.verifyEqual(repository.DataTypes(end), "int32");
            testCase.verifyEqual(numel(repository.Paths), 10);

        end

        function createsBackwardCompatibleFluxVariabilityCheckpoint( ...
                testCase)

            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter();
            checkpoint = writer.createFluxVariabilityCheckpoint( ...
                [1; 0; 4], ...
                [5; 2; 8], ...
                [1, 2], ...
                TimestampUnix = 10.25);

            testCase.verifyEqual(checkpoint.DataPath, "/fluxVariability");
            testCase.verifyEqual(checkpoint.Value.fluxLB, [1; 0; 4]);
            testCase.verifyEqual(checkpoint.Value.fluxUB, [5; 2; 8]);
            testCase.verifyEqual(checkpoint.Value.fluxLBFwd, [-1; 4]);
            testCase.verifyEqual(checkpoint.Value.fluxUBFwd, [5; 8]);
            testCase.verifyEqual(checkpoint.Value.time, 10.25);

        end

        function writesFluxVariabilityDatasetsAndStatus(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createFluxVariabilityCheckpoint( ...
                [1; 0; 4], [5; 2; 8], [1, 2], ...
                TimestampUnix = 10.25);

            [isSuccess, message] = writer.writeFluxVariability( ...
                "result.h5", checkpoint, [0, 0, 0, 0]);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/fluxVariability/fluxLB"; ...
                "/fluxVariability/fluxUB"; ...
                "/fluxVariability/fluxLBFwd"; ...
                "/fluxVariability/fluxUBFwd"; ...
                "/fluxVariability/time"; ...
                "/status"]);
            testCase.verifyEqual(repository.Values{5}, int32(10.25));
            testCase.verifyEqual(repository.Values{6}, int8([0, 0, 0, 0]));
            testCase.verifyEqual(repository.DataTypes, [ ...
                "double"; "double"; "double"; "double"; ...
                "int32"; "int8"]);

        end

        function createsBackwardCompatibleInitialFluxCheckpoint(testCase)

            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter();
            checkpoint = writer.createInitialFluxCheckpoint( ...
                [5, 6; 2, 1; 7, 8], ...
                [0.1, 0.2], ...
                [4.5, 5], ...
                [1, 2], ...
                TimestampUnix = 20.75);

            testCase.verifyEqual(checkpoint.DataPath, "/initialFlux");
            testCase.verifyEqual( ...
                checkpoint.Value.flux, [5, 6; 2, 1; 7, 8]);
            testCase.verifyEqual(checkpoint.Value.fluxFwd, [3, 5; 7, 8]);
            testCase.verifyEqual(checkpoint.Value.rhs, [0.1, 0.2]);
            testCase.verifyEqual(checkpoint.Value.RSS, [4.5, 5]);
            testCase.verifyEqual(checkpoint.Value.time, 20.75);

        end

        function writesInitialFluxDatasetsAndStatus(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createInitialFluxCheckpoint( ...
                [5, 6; 2, 1; 7, 8], ...
                [0.1, 0.2], ...
                [4.5, 5], ...
                [1, 2], ...
                TimestampUnix = 20.75);

            [isSuccess, message] = writer.writeInitialFlux( ...
                "result.h5", checkpoint, [1, 0, 0, 0]);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/initialFlux/flux"; ...
                "/initialFlux/fluxFwd"; ...
                "/initialFlux/rhs"; ...
                "/initialFlux/RSS"; ...
                "/initialFlux/time"; ...
                "/status"]);
            testCase.verifyEqual(repository.Values{5}, int32(20.75));
            testCase.verifyEqual(repository.Values{6}, int8([1, 0, 0, 0]));
            testCase.verifyEqual(repository.DataTypes, [ ...
                "double"; "double"; "double"; "double"; ...
                "int32"; "int8"]);

        end

        function createsBackwardCompatibleMonteCarloCheckpoint(testCase)

            settings = openmebius.mfa.ConfidenceIntervalSettings();
            output = struct(flux = [9; 10], MDV = [0.2; 0.8]);
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter();
            checkpoint = ...
                writer.createMonteCarloConfidenceIntervalCheckpoint( ...
                [1, 2; 3, 4], ...
                [5, 6; 7, 8], ...
                settings, ...
                output, ...
                TimestampUnix = 30.5);

            testCase.verifyEqual(checkpoint.DataPath, "/CI");
            testCase.verifyEqual(checkpoint.FinalFluxLB, [2; 4]);
            testCase.verifyEqual(checkpoint.FinalFluxUB, [6; 8]);
            testCase.verifyEqual(checkpoint.Value.time, 30.5);
            testCase.verifyEqual(checkpoint.Value.fluxLB, [1, 2; 3, 4]);
            testCase.verifyEqual(checkpoint.Value.fluxUB, [5, 6; 7, 8]);
            testCase.verifyEqual( ...
                checkpoint.Value.algorithm, ...
                settings.Method.displayName());
            testCase.verifyEqual( ...
                checkpoint.Value.TT, ...
                settings.MonteCarloSettings.TerminationTolerance);
            testCase.verifyEqual(checkpoint.Fluxes, output.flux);
            testCase.verifyEqual(checkpoint.MDV, output.MDV);

        end

        function writesMonteCarloDatasetsAndStatus(testCase)

            settings = openmebius.mfa.ConfidenceIntervalSettings();
            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = ...
                writer.createMonteCarloConfidenceIntervalCheckpoint( ...
                [1, 2; 3, 4], ...
                [5, 6; 7, 8], ...
                settings, ...
                struct(flux = [9; 10], MDV = [0.2; 0.8]), ...
                TimestampUnix = 30.5);

            [isSuccess, message] = ...
                writer.writeMonteCarloConfidenceInterval( ...
                "result.h5", checkpoint, [1, 1, 1, 0]);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/fluxLB"; ...
                "/fluxUB"; ...
                "/CI/fluxLB"; ...
                "/CI/fluxUB"; ...
                "/CI/algorithm"; ...
                "/CI/iteration"; ...
                "/CI/MIDSD"; ...
                "/CI/optimizationProcedure"; ...
                "/CI/TT"; ...
                "/CI/proximityThreshold"; ...
                "/CI/certainThreshold"; ...
                "/CI/theNumberOfRuns"; ...
                "/CI/calculationMethod"; ...
                "/CI/fluxes"; ...
                "/CI/MDV"; ...
                "/status"; ...
                "/CI/time"]);
            testCase.verifyEqual(repository.Values{6}, int32(500));
            testCase.verifyEqual(repository.Values{12}, int32(50));
            testCase.verifyEqual(repository.Values{16}, int8([1, 1, 1, 0]));
            testCase.verifyEqual(repository.Values{17}, int32(30.5));
            testCase.verifyEqual(repository.DataTypes, [ ...
                "double"; "double"; "double"; "double"; ...
                "string"; "int32"; "double"; "string"; ...
                "double"; "double"; "double"; "int32"; ...
                "string"; "double"; "double"; "int8"; "int32"]);

        end

        function createsGridSearchCheckpoint(testCase)

            profile = openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = [1; 3], ...
                FixedFluxValues = cat( ...
                3, [1, 2; 4, 5], [1, 2; 4, 5]), ...
                MinimumSumOfSquares = cat( ...
                3, [7, 4; 9, 6], [6, 5; 8, 7]));
            output = struct( ...
                profile = profile, ...
                time = 12.5, ...
                bestObjective = 3.5, ...
                objectiveThreshold = 6.5);
            settings = openmebius.mfa.ConfidenceIntervalSettings( ...
                Enabled = true, ...
                Method = openmebius.mfa ...
                .ConfidenceIntervalMethod.GridSearch);
            writer = openmebius.infrastructure.result ...
                .MFAResultCheckpointWriter();

            checkpoint = writer ...
                .createGridSearchConfidenceIntervalCheckpoint( ...
                [0.5; 3.5], ...
                [2.5; 5.5], ...
                settings, ...
                output, ...
                ["R1"; "R2"; "R3"; "biomass"], ...
                TimestampUnix = 40.25);

            testCase.verifyEqual( ...
                checkpoint.Value.algorithm, "Grid search");
            testCase.verifyEqual( ...
                checkpoint.FinalFluxLB, [0.5; NaN; 3.5; NaN]);
            testCase.verifyEqual( ...
                checkpoint.FinalFluxUB, [2.5; NaN; 5.5; NaN]);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.reactionIDs, ["R1"; "R3"]);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.fixedFlux, [1, 2; 4, 5]);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.minimumRSS, [6, 4; 8, 6]);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.bestObjective, 3.5);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.maximumTrial, 15);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.workerCount, 8);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.minimumFluxRange, 1e-6);
            testCase.verifyEqual( ...
                checkpoint.Value.gridSearch.elapsedTime, 12.5);
            testCase.verifyEqual(checkpoint.Value.time, 40.25);

        end

        function writesGridSearchDatasetsAndStatus(testCase)

            profile = openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = 2, ...
                FixedFluxValues = reshape([1, 2], 1, 2, 1), ...
                MinimumSumOfSquares = reshape([5, 4], 1, 2, 1));
            output = struct( ...
                profile = profile, ...
                time = 2, ...
                bestObjective = 3.5, ...
                objectiveThreshold = 4.5);
            settings = openmebius.mfa.ConfidenceIntervalSettings( ...
                Enabled = true, ...
                Method = openmebius.mfa ...
                .ConfidenceIntervalMethod.GridSearch);
            repository = helpers.RecordingDatasetRepository();
            writer = openmebius.infrastructure.result ...
                .MFAResultCheckpointWriter(Repository = repository);
            checkpoint = writer ...
                .createGridSearchConfidenceIntervalCheckpoint( ...
                0.5, ...
                2.5, ...
                settings, ...
                output, ...
                ["R1"; "R2"; "biomass"], ...
                TimestampUnix = 40.25);

            [isSuccess, message] = ...
                writer.writeGridSearchConfidenceInterval( ...
                "result.h5", checkpoint, [1, 1, 1, 0]);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/fluxLB"; ...
                "/fluxUB"; ...
                "/CI/fluxLB"; ...
                "/CI/fluxUB"; ...
                "/CI/algorithm"; ...
                "/CI/gridSearch/fluxIndices"; ...
                "/CI/gridSearch/reactionIDs"; ...
                "/CI/gridSearch/fixedFlux"; ...
                "/CI/gridSearch/RSS"; ...
                "/CI/gridSearch/minimumRSS"; ...
                "/CI/gridSearch/bestObjective"; ...
                "/CI/gridSearch/objectiveThreshold"; ...
                "/CI/gridSearch/pointCount"; ...
                "/CI/gridSearch/trialCount"; ...
                "/CI/gridSearch/workerCount"; ...
                "/CI/gridSearch/maximumTrial"; ...
                "/CI/gridSearch/minimumFluxRange"; ...
                "/CI/gridSearch/alpha"; ...
                "/CI/gridSearch/thresholdType"; ...
                "/CI/gridSearch/intervalMode"; ...
                "/CI/gridSearch/executionMode"; ...
                "/CI/gridSearch/delta"; ...
                "/CI/gridSearch/elapsedTime"; ...
                "/status"; ...
                "/CI/time"]);
            testCase.verifyEqual( ...
                repository.Values{6}, int32(2));
            testCase.verifyEqual( ...
                repository.Values{24}, int8([1, 1, 1, 0]));
            testCase.verifyEqual(repository.DataTypes(7), "string");
            testCase.verifyEqual(repository.DataTypes(25), "int32");

        end

        function writesWorkflowSummary(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);

            [isSuccess, message] = writer.writeSummary( ...
                "result.h5", [1, 2], [2, 1], [1, 1, 0, 0], 3.84);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual( ...
                repository.Paths, ...
                ["/RSS"; "/RSSIndex"; "/status"; "/threshold"]);
            testCase.verifyEqual(repository.Values{2}, int32([2, 1]));
            testCase.verifyEqual(repository.Values{3}, int8([1, 1, 0, 0]));
            testCase.verifyEqual( ...
                repository.DataTypes, ...
                ["double"; "int32"; "int8"; "double"]);

        end

        function stopsAtFirstRepositoryFailure(testCase)

            repository = helpers.RecordingDatasetRepository();
            repository.FailAt = 2;
            writer = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter( ...
                Repository = repository);
            checkpoint = writer.createIterationCheckpoint( ...
                1, MFAResultCheckpointWriterTest.createIterationResult());

            [isSuccess, message] = writer.writeIteration( ...
                "result.h5", checkpoint);

            testCase.verifyFalse(isSuccess);
            testCase.verifyEqual(numel(repository.Paths), 2);
            testCase.verifySubstring(message, repository.Paths(2));

        end

    end

    methods (Static, Access = private)

        function result = createIterationResult()

            search = struct( ...
                candidates = [1e-4; 1e-5], ...
                objectives = [5; 4.5], ...
                exitflags = [1; 1]);
            output = struct( ...
                fminconFiniteDifferenceStepSize = 1e-5, ...
                fminconFiniteDifferenceStepSizeSearch = search);
            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = [5; 2; 7], ...
                Flux = [5; 2; 7], ...
                MDV = [0.2; 0.8], ...
                ObjectiveValue = 4.5, ...
                ExitFlag = 1, ...
                Output = output);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
