classdef MFAStoichiometricNetworkTest < matlab.unittest.TestCase
    % MFASTOICHIOMETRICNETWORKTEST Characterizes the K1 decomposition.

    methods (Test)
        function expandsReversibleReactionAndBuildsSquareSystem(testCase)
            [modelTable, reactions, transitions, metabolites, biomass] = ...
                MFAStoichiometricNetworkTest.fixture();
            index = openmebius.domain.model.StoichiometricReactionIndex( ...
                modelTable, reactions, transitions);
            constraints = openmebius.mfa.StoichiometricMatrixBuilder() ...
                .build(index, metabolites, biomass);
            network = openmebius.domain.model.StoichiometricNetwork( ...
                index, constraints, metabolites);

            testCase.verifyEqual(index.ReversiblePairs, [2 3]);
            testCase.verifyEqual( ...
                string(index.Reactions.Properties.RowNames), ...
                ["r1"; "r2"; "r2_rev"; "r3"]);
            testCase.verifyEqual(index.Reactions.Reactants{3}, {'B'});
            testCase.verifyEqual(index.Reactions.Products{3}, {'A'});
            testCase.verifyEqual( ...
                index.ModelTable.Reaction{3}, ...
                'B <=> A');
            testCase.verifyEqual( ...
                index.ModelTable.Transition{3}, ...
                'a <=> a');
            testCase.verifyEqual(height(network.getSBefore()), 4);
            testCase.verifyEqual(size(network.getS()), [5 5]);
            testCase.verifyEqual( ...
                string(network.getConstraintTypes()), ...
                ["metabolite"; "metabolite"; "biomass"; "efflux"]);
            testCase.verifyEqual(network.findCounterReaction("r2"), 3);
            testCase.verifyEqual(network.findCounterReaction("r2_rev"), 2);
            testCase.verifyEqual( ...
                network.findSubstrateRxnIDFromMetaboliteIrrev("Subs_A"), ...
                "r1");
        end

        function rejectsNonSquareSystem(testCase)
            constraint = array2table(eye(2));
            system = array2table(ones(2, 3));

            testCase.verifyError( ...
                @() openmebius.domain.model ...
                    .StoichiometricConstraintModel( ...
                        constraint, system, ["metabolite"; "metabolite"]), ...
                "OpenMebius2:StoichiometricConstraintModel:NonSquareSystem");
        end
    end

    methods (Static, Access = private)
        function [modelTable, reactions, transitions, metabolites, biomass] = ...
                fixture()
            rowNames = {'r1'; 'r2'; 'r3'};
            modelTable = table( ...
                {'Subs_A --> A'; 'A <=> B'; 'B --> Product'}, ...
                {'a --> a'; 'a <=> a'; 'a --> a'}, ...
                false(3, 1), ...
                VariableNames = ["Reaction", "Transition", "Independent"], ...
                RowNames = rowNames);
            reactions = table( ...
                {{'Subs_A'}; {'A'}; {'B'}}, ...
                {{'A'}; {'B'}; {'Product'}}, ...
                [false; true; false], ...
                false(3, 1), ...
                VariableNames = [ ...
                    "Reactants", "Products", "Reversible", "Independent"], ...
                RowNames = rowNames);
            transitions = table( ...
                {{'a'}; {'a'}; {'a'}}, ...
                {{'a'}; {'a'}; {'a'}}, ...
                [false; true; false], ...
                VariableNames = ["Reactants", "Products", "Reversible"], ...
                RowNames = rowNames);
            metabolites = table( ...
                ["A"; "B"; "Subs_A"; "Product"], ...
                ["metabolite"; "metabolite"; "substrate"; "product"], ...
                VariableNames = ["Metabolite", "Type"]);
            biomass = table({'A'}, 1, ...
                VariableNames = ["Precursor", "Biomass"]);
        end
    end
end
