classdef MonteCarloConfidenceIntervalSolverTest < ...
        matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath( ...
                MonteCarloConfidenceIntervalSolverTest.sourcePath());

        end

    end

    methods (Test)

        function runsSingleProcedureAndCalculatesCumulativeBounds( ...
                testCase)

            stub = helpers.MonteCarloIterationStub( ...
                [1, 4, 2, 3; 0, 1, 0, 0; 10, 20, 30, 40], ...
                [4, 3, 2, 1]);
            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 4, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                    .MonteCarloOptimizationProcedure.SingleRun);

            result = solver.solve( ...
                [0.2; 0.8], ...
                3, ...
                settings, ...
                @(mdv) stub.run(mdv), ...
                [1, 2], ...
                UseParallel = false, ...
                ConfidenceLevel = 0.5);

            testCase.verifyEqual(stub.CallCount, 4);
            testCase.verifyEqual( ...
                result.PerturbedMDVs, ...
                repmat([0.2; 0.8], 1, 1, 4));
            testCase.verifyEqual( ...
                result.Fluxes, ...
                [1, 3, 2, 3; 10, 20, 30, 40]);
            testCase.verifyEqual( ...
                result.LowerBounds, ...
                [1, 1, 1, 2; 10, 10, 10, 20]);
            testCase.verifyEqual( ...
                result.UpperBounds, ...
                [1, 3, 3, 3; 10, 20, 30, 30]);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.IterationCount, 4);

        end

        function multipleProcedureSelectsLowestObjectiveTrial(testCase)

            stub = helpers.MonteCarloIterationStub( ...
                [5, 1, 3; 50, 10, 30], [5, 1, 3]);
            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 1, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                    .MonteCarloOptimizationProcedure.MultipleRun, ...
                TrialCount = 3, ...
                CertainThreshold = 3, ...
                ProximityThreshold = 0);

            result = solver.solve( ...
                [0.25; 0.75], ...
                2, ...
                settings, ...
                @(mdv) stub.run(mdv), ...
                UseParallel = false);

            testCase.verifyEqual(stub.CallCount, 3);
            testCase.verifyEqual(result.Fluxes, [1; 10]);
            testCase.verifyEqual(result.LowerBounds, [1; 10]);
            testCase.verifyEqual(result.UpperBounds, [1; 10]);

        end

        function honorsCancellationWhileAccumulatingBounds(testCase)

            stub = helpers.MonteCarloIterationStub( ...
                [1, 2, 3; 10, 20, 30], [1, 2, 3]);
            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 3, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                    .MonteCarloOptimizationProcedure.SingleRun);

            result = solver.solve( ...
                [0.1; 0.9], ...
                2, ...
                settings, ...
                @(mdv) stub.run(mdv), ...
                UseParallel = false, ...
                CancellationRequested = ...
                    @() stub.CallCount >= 3);

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyEqual(result.LowerBounds(:, 1), [1; 10]);
            testCase.verifyTrue( ...
                all(isnan(result.LowerBounds(:, 2:end)), "all"));

        end

        function rejectsUnimplementedCalculationMethod(testCase)

            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 1, ...
                CalculationMethod = openmebius.mfa ...
                    .ConfidenceIntervalCalculationMethod.MeanVarianced);

            testCase.verifyError( ...
                @() solver.solve( ...
                1, 1, settings, @(~) struct, ...
                UseParallel = false), ...
                "OpenMebius2:MonteCarloCI:MethodNotImplemented");

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
