classdef MonteCarloConfidenceIntervalSolverTest < ...
        matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath( ...
                MonteCarloConfidenceIntervalSolverTest.sourcePath());

        end

    end

    methods (Test)

        function runsSingleProcedureAndCalculatesCumulativeBounds( ...
                testCase)

            stub = helpers.MonteCarloIterationStub( ...
                [1, 4, 2, 3; 0, 1, 0, 0; 10, 20, 30, 40], ...
                [4, 3, 2, 1]);
            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 4, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                .MonteCarloOptimizationProcedure.SingleRun);
            progress = helpers.AnalysisProgressRecorder();

            result = solver.solve( ...
                [0.2; 0.8], ...
                3, ...
                settings, ...
                @(mdv) stub.run(mdv), ...
                [1, 2], ...
                UseParallel = false, ...
                ProgressReporter = @(completed, total) ...
                progress.record(completed, total), ...
                ConfidenceLevel = 0.5);

            testCase.verifyEqual(stub.CallCount, 4);
            testCase.verifyEqual( ...
                result.PerturbedMDVs, ...
                repmat([0.2; 0.8], 1, 1, 4));
            testCase.verifyEqual( ...
                result.Fluxes, ...
                [1, 3, 2, 3; 10, 20, 30, 40]);
            testCase.verifyEqual( ...
                result.LowerBounds, ...
                [1, 1, 1, 2; 10, 10, 10, 20]);
            testCase.verifyEqual( ...
                result.UpperBounds, ...
                [1, 3, 3, 3; 10, 20, 30, 30]);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.IterationCount, 4);
            testCase.verifyEqual(progress.Completed, (0:4)');
            testCase.verifyEqual(progress.Total, repmat(4, 5, 1));

        end

        function multipleProcedureSelectsLowestObjectiveTrial(testCase)

            stub = helpers.MonteCarloIterationStub( ...
                [5, 1, 3; 50, 10, 30], [5, 1, 3]);
            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 1, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                .MonteCarloOptimizationProcedure.MultipleRun, ...
                TrialCount = 3, ...
                CertainThreshold = 3, ...
                ProximityThreshold = 0);

            result = solver.solve( ...
                [0.25; 0.75], ...
                2, ...
                settings, ...
                @(mdv) stub.run(mdv), ...
                UseParallel = false);

            testCase.verifyEqual(stub.CallCount, 3);
            testCase.verifyEqual(result.Fluxes, [1; 10]);
            testCase.verifyEqual(result.LowerBounds, [1; 10]);
            testCase.verifyEqual(result.UpperBounds, [1; 10]);

        end

        function honorsCancellationWhileAccumulatingBounds(testCase)

            stub = helpers.MonteCarloIterationStub( ...
                [1, 2, 3; 10, 20, 30], [1, 2, 3]);
            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 3, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                .MonteCarloOptimizationProcedure.SingleRun);

            result = solver.solve( ...
                [0.1; 0.9], ...
                2, ...
                settings, ...
                @(mdv) stub.run(mdv), ...
                UseParallel = false, ...
                CancellationRequested = ...
                @() stub.CallCount >= 3);

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyEqual(result.LowerBounds(:, 1), [1; 10]);
            testCase.verifyTrue( ...
                all(isnan(result.LowerBounds(:, 2:end)), "all"));

        end

        function rejectsUnimplementedCalculationMethod(testCase)

            solver = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 1, ...
                CalculationMethod = openmebius.mfa ...
                .ConfidenceIntervalCalculationMethod.MeanVarianced);

            testCase.verifyError( ...
                @() solver.solve( ...
                1, 1, settings, @(~) struct, ...
                UseParallel = false), ...
                "OpenMebius2:MonteCarloCI:MethodNotImplemented");

        end

        function settingsRejectInvalidWorkerCount(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings(WorkerCount = 0), ...
                "OpenMebius2:" + ...
                "MonteCarloConfidenceIntervalSettings:" + ...
                "InvalidPositiveInteger");

        end

        function reportsExecutionResources(testCase)

            stub = helpers.MonteCarloIterationStub( ...
                [1, 2; 10, 20], [1, 2]);
            observer = helpers.AnalysisMessageObserverStub();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 2, ...
                WorkerCount = 12, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                .MonteCarloOptimizationProcedure.SingleRun);

            openmebius.mfa.MonteCarloConfidenceIntervalSolver().solve( ...
                [0.2; 0.8], ...
                2, ...
                settings, ...
                @(mdv) stub.run(mdv), ...
                UseParallel = false, ...
                MessageReporter = @(level, message) ...
                observer.report(level, message));

            resourceMessage = observer.Messages(contains( ...
                observer.Messages, "Monte Carlo resources:"));
            testCase.verifyNumElements(resourceMessage, 1);
            testCase.verifyTrue(contains( ...
                resourceMessage, "configuredWorkers=12"));
            testCase.verifyTrue(contains(resourceMessage, "workers=1"));
            testCase.verifyTrue(contains(resourceMessage, "iterations=2"));

        end

        function parallelRunLimitsWorkersToIterationCount(testCase)

            cleanup = onCleanup(@() ...
                MonteCarloConfidenceIntervalSolverTest ...
                .deleteCurrentPool());
            observer = helpers.AnalysisMessageObserverStub();
            progress = helpers.AnalysisProgressRecorder();
            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = 2, ...
                WorkerCount = 20, ...
                StandardDeviation = 0, ...
                Procedure = openmebius.mfa ...
                .MonteCarloOptimizationProcedure.SingleRun);
            [~, logicalProcessors] = openmebius.mfa ...
                .GridSearchParallelPoolManager.processorCounts();
            expectedWorkers = min([logicalProcessors, 20, 2]);

            result = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSolver().solve( ...
                [0.2; 0.8], ...
                2, ...
                settings, ...
                @(mdv) MonteCarloConfidenceIntervalSolverTest ...
                .createIterationResult(mdv), ...
                UseParallel = true, ...
                MessageReporter = @(level, message) ...
                observer.report(level, message), ...
                ProgressReporter = @(completed, total) ...
                progress.record(completed, total));

            pool = gcp("nocreate");
            testCase.verifyEqual(pool.NumWorkers, expectedWorkers);
            testCase.verifyEqual(result.IterationCount, 2);
            resourceMessage = observer.Messages(contains( ...
                observer.Messages, "Monte Carlo resources:"));
            testCase.verifyTrue(contains( ...
                resourceMessage, "workers=" + string(expectedWorkers)));
            testCase.verifyEqual(progress.Completed, (0:2)');
            testCase.verifyEqual(progress.Total, repmat(2, 3, 1));

        end

    end

    methods (Static, Access = private)

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

        function result = createIterationResult(mdv)

            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 1, ...
                Flux = [1; 2], ...
                MDV = mdv, ...
                ObjectiveValue = 1, ...
                ExitFlag = 1);

        end

        function deleteCurrentPool()

            pool = gcp("nocreate");

            if ~isempty(pool)
                delete(pool);
            end

        end

    end

end
