classdef MSFragmentTableMapperTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            sourcePath = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');
            addpath(sourcePath);

        end % addSourcePath

    end % methods

    methods (Test)

        function createsUniqueVariablesForDuplicateExperimentNames(testCase)

            selections = [
                MSFragmentTableMapperTest.createSelection( ...
                "batch-a", ...
                "WT_ecoli", ...
                [true; false; true])
                MSFragmentTableMapperTest.createSelection( ...
                "batch-b", ...
                "WT_ecoli", ...
                [false; true; false])
                ];

            viewModel = ...
                openmebius.presentation.batch.MSFragmentTableMapper.toViewModel( ...
                selections);

            testCase.verifyEqual(width(viewModel.Data), 2);
            testCase.verifyEqual( ...
                numel(unique(string(viewModel.Data.Properties.VariableNames))), ...
                width(viewModel.Data));
            testCase.verifyEqual( ...
                string(viewModel.ColumnName), ...
                ["WT_ecoli", "WT_ecoli"]);
            testCase.verifyEqual(viewModel.RowName(:), {'fragment_1'; 'fragment_2'; 'fragment_3'});

        end % createsUniqueVariablesForDuplicateExperimentNames

        function mapsEditedViewTableBackToBatchSelections(testCase)

            selections = [
                MSFragmentTableMapperTest.createSelection( ...
                "batch-a", ...
                ["WT_ecoli", "pgi_ecoli"], ...
                [true false; false true; true true])
                MSFragmentTableMapperTest.createSelection( ...
                "batch-b", ...
                "WT_ecoli", ...
                [false; true; false])
                ];

            viewModel = ...
                openmebius.presentation.batch.MSFragmentTableMapper.toViewModel( ...
                selections);

            viewTable = viewModel.Data;
            variableNames = viewTable.Properties.VariableNames;
            viewTable{2, variableNames{1}} = true;
            viewTable{1, variableNames{3}} = true;

            actual = ...
                openmebius.presentation.batch.MSFragmentTableMapper.fromViewTable( ...
                viewTable, ...
                viewModel.Metadata);

            testCase.verifyEqual([actual.BatchID], ["batch-a", "batch-b"]);
            testCase.verifyEqual(actual(1).ExperimentNames, ["WT_ecoli", "pgi_ecoli"]);
            testCase.verifyEqual(actual(2).ExperimentNames, "WT_ecoli");
            testCase.verifyEqual( ...
                actual(1).Selection, ...
                [true false; true true; true true]);
            testCase.verifyEqual( ...
                actual(2).Selection, ...
                [true; true; false]);

        end % mapsEditedViewTableBackToBatchSelections

    end % methods

    methods (Static, Access = private)

        function selection = createSelection(batchID, experimentNames, selectionData)

            selection = struct( ...
                'BatchID', string(batchID), ...
                'ExperimentNames', string(experimentNames), ...
                'FragmentNames', ["fragment_1"; "fragment_2"; "fragment_3"], ...
                'Selection', logical(selectionData) ...
                );

        end % createSelection

    end % methods

end % classdef
