classdef NextLabelResultCheckpointWriterTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(NextLabelResultCheckpointWriterTest.sourcePath());

        end

    end

    methods (Test)

        function writesSuggestionTable(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = NextLabelResultCheckpointWriterTest.writer(repository);
            checkpoint = writer.createSuggestionTableCheckpoint( ...
                ["Glucose", "1"; "Acetate", "0"], ...
                ["Tracer", "Selected"]);

            [isSuccess, message] = writer.writeSuggestionTable( ...
                "result.h5", checkpoint);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/nextLabelPattern/suggestionTable/colName"; ...
                "/nextLabelPattern/suggestionTable/data"]);
            testCase.verifyEqual( ...
                repository.Values{1}, ["Tracer", "Selected"]);
            testCase.verifyEqual(repository.DataTypes, ["string"; "string"]);

        end

        function createsInitialFluxCheckpoint(testCase)

            writer = ...
                openmebius.infrastructure.result ...
                .NextLabelResultCheckpointWriter();
            checkpoint = writer.createInitialFluxCheckpoint( ...
                ["Glucose", "Acetate"], ...
                [5, 6; 2, 1; 7, 8], ...
                [0.1, 0.2], ...
                [4.5, 5], ...
                [1, 2], ...
                TimestampUnix = 40.25);

            testCase.verifyEqual(checkpoint.FieldName, "Glucose_Acetate");
            testCase.verifyEqual( ...
                checkpoint.DataPath, ...
                "/nextLabelPattern/Glucose_Acetate");
            testCase.verifyEqual(checkpoint.Value.fluxFwd, [3, 5; 7, 8]);
            testCase.verifyEqual(checkpoint.Value.time, 40.25);

        end

        function writesInitialFluxCheckpoint(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = NextLabelResultCheckpointWriterTest.writer(repository);
            checkpoint = writer.createInitialFluxCheckpoint( ...
                ["Glucose", "Acetate"], ...
                [5; 2; 7], 0.1, 4.5, [1, 2], ...
                TimestampUnix = 40.25);

            [isSuccess, message] = writer.writeInitialFlux( ...
                "result.h5", checkpoint);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/nextLabelPattern/Glucose_Acetate/flux"; ...
                "/nextLabelPattern/Glucose_Acetate/fluxFwd"; ...
                "/nextLabelPattern/Glucose_Acetate/rhs"; ...
                "/nextLabelPattern/Glucose_Acetate/RSS"; ...
                "/nextLabelPattern/Glucose_Acetate/time"]);
            testCase.verifyEqual(repository.Values{5}, int32(40.25));

        end

        function createsConfidenceIntervalCheckpoint(testCase)

            writer = ...
                openmebius.infrastructure.result ...
                .NextLabelResultCheckpointWriter();
            checkpoint = writer.createConfidenceIntervalCheckpoint( ...
                ["Glucose", "Acetate"], ...
                [1, 2; 3, 4], ...
                [5, 6; 7, 8], ...
                TimestampUnix = 50.75);

            testCase.verifyEqual(checkpoint.FieldName, "Glucose_Acetate");
            testCase.verifyEqual(checkpoint.Value.fluxLB, [2; 4]);
            testCase.verifyEqual(checkpoint.Value.fluxUB, [6; 8]);
            testCase.verifyEqual( ...
                checkpoint.Value.CI.fluxLB, [1, 2; 3, 4]);
            testCase.verifyEqual(checkpoint.Value.CI.time, 50.75);

        end

        function writesConfidenceIntervalCheckpoint(testCase)

            repository = helpers.RecordingDatasetRepository();
            writer = NextLabelResultCheckpointWriterTest.writer(repository);
            checkpoint = writer.createConfidenceIntervalCheckpoint( ...
                ["Glucose", "Acetate"], ...
                [1, 2; 3, 4], ...
                [5, 6; 7, 8], ...
                TimestampUnix = 50.75);

            [isSuccess, message] = writer.writeConfidenceInterval( ...
                "result.h5", checkpoint);

            testCase.verifyTrue(isSuccess, message);
            testCase.verifyEqual(repository.Paths, [ ...
                "/nextLabelPattern/Glucose_Acetate/fluxLB"; ...
                "/nextLabelPattern/Glucose_Acetate/fluxUB"; ...
                "/nextLabelPattern/Glucose_Acetate/CI/fluxLB"; ...
                "/nextLabelPattern/Glucose_Acetate/CI/fluxUB"; ...
                "/nextLabelPattern/Glucose_Acetate/CI/time"]);
            testCase.verifyEqual(repository.Values{5}, int32(50.75));

        end

    end

    methods (Static, Access = private)

        function writer = writer(repository)

            writer = ...
                openmebius.infrastructure.result ...
                .NextLabelResultCheckpointWriter( ...
                Repository = repository);

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
