classdef NextFluxExperimentWorkflowTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(NextFluxExperimentWorkflowTest.sourcePath());

        end

    end

    methods (Test)

        function successfulRunPersistsSuggestionAndCandidate(testCase)

            confidenceWorkflow = helpers.WorkflowResultStub( ...
                NextFluxExperimentWorkflowTest.confidenceResult());
            workflow = NextFluxExperimentWorkflowTest.createWorkflow( ...
                confidenceWorkflow);
            context = NextFluxExperimentWorkflowTest.createContext();
            session = helpers.MFAResultSessionStub();

            result = workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                [], ...
                1, ...
                NextFluxExperimentWorkflowTest.config(), ...
                context, ...
                session, ...
                []);

            testCase.verifyFalse(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.LowerBounds, [0; 10]);
            testCase.verifyEqual(result.UpperBounds, [2; 12]);
            testCase.verifyEqual(context.LowerBounds, [0; 10]);
            testCase.verifyEqual(context.UpperBounds, [2; 12]);
            testCase.verifyEqual( ...
                session.Calls, ...
                ["monte-carlo"; "suggestion"; "next-label"]);
            testCase.verifyEqual(confidenceWorkflow.CallCount, 2);
            testCase.verifyEqual( ...
                numel(result.SuggestionResult.Patterns), 1);

        end

        function canceledBaseConfidenceIntervalStopsSuggestion(testCase)

            confidenceResult = ...
                NextFluxExperimentWorkflowTest.confidenceResult( ...
                IsCanceled = true);
            confidenceWorkflow = ...
                helpers.WorkflowResultStub(confidenceResult);
            workflow = NextFluxExperimentWorkflowTest.createWorkflow( ...
                confidenceWorkflow);
            session = helpers.MFAResultSessionStub();

            result = workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                [], ...
                1, ...
                NextFluxExperimentWorkflowTest.config(), ...
                NextFluxExperimentWorkflowTest.createContext(), ...
                session, ...
                []);

            testCase.verifyTrue(result.IsCanceled);
            testCase.verifyFalse(result.IsError);
            testCase.verifyEqual(session.Calls, "monte-carlo");
            testCase.verifyEqual(confidenceWorkflow.CallCount, 1);

        end

        function confidenceIntervalFailureIsReturned(testCase)

            confidenceResult = openmebius.mfa ...
                .ConfidenceIntervalWorkflowResult( ...
                Method = "Monte Carlo", ...
                IsError = true, ...
                ErrorMessage = "CI failed.");
            workflow = NextFluxExperimentWorkflowTest.createWorkflow( ...
                helpers.WorkflowResultStub(confidenceResult));
            session = helpers.MFAResultSessionStub();

            result = workflow.run( ...
                helpers.FluxDistributionModelStub(), ...
                [], ...
                1, ...
                NextFluxExperimentWorkflowTest.config(), ...
                NextFluxExperimentWorkflowTest.createContext(), ...
                session, ...
                []);

            testCase.verifyTrue(result.IsError);
            testCase.verifyFalse(result.IsCanceled);
            testCase.verifyEqual(result.ErrorMessage, "CI failed.");
            testCase.verifyEmpty(session.Calls);

        end

    end

    methods (Static, Access = private)

        function workflow = createWorkflow(confidenceWorkflow)

            nextLabelWorkflow = ...
                openmebius.mfa.NextLabelExperimentWorkflow( ...
                SubstrateEMUFactory = ...
                    helpers.SubstrateEMUFactoryStub(), ...
                MDVPredictor = helpers.MDVPredictorStub());
            workflow = openmebius.application.analysis ...
                .NextFluxExperimentWorkflow( ...
                ConfidenceIntervalApplicationWorkflow = ...
                    confidenceWorkflow, ...
                NextLabelExperimentWorkflow = nextLabelWorkflow);

        end

        function result = confidenceResult(options)

            arguments
                options.IsCanceled (1, 1) logical = false
            end

            result = openmebius.mfa ...
                .ConfidenceIntervalWorkflowResult( ...
                LowerBounds = [0; 10], ...
                UpperBounds = [2; 12], ...
                Output = struct(Iteration = 1), ...
                Method = "Monte Carlo", ...
                IsCalculated = true, ...
                IsCanceled = options.IsCanceled);

        end

        function context = createContext()

            iterationResult = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = 1, ...
                Flux = [7; 8], ...
                MDV = [0.3; 0.7], ...
                ObjectiveValue = 6, ...
                ExitFlag = 1);
            fitted = openmebius.mfa.MFAWorkflowResult( ...
                ObjectiveValues = 6, ...
                Fluxes = [7; 8], ...
                MDVs = reshape([0.3; 0.7], 2, 1, 1), ...
                Order = 1, ...
                IterationResults = {iterationResult});
            context = openmebius.application.analysis ...
                .MFAAnalysisRunContext();
            context.setWorkflowResult(fitted);

        end

        function value = config()

            value = struct;
            value.isCalcCI = true;
            value.isINSTMFA = false;
            value.CIConf = struct(MC = struct);
            value.suggestionTable = {'A'};
            value.suggestionTableVarNames = {'Tracer'};
            value.suggestionTableRowNames = {'candidate'};

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
