classdef RangePlotPatternTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));

        end

    end

    methods (Test)

        function drawsConfiguredPatterns(testCase)

            figureObject = figure('Visible', 'off');
            testCase.addTeardown(@() close(figureObject));
            axesObject = axes(figureObject);
            lower = array2table( ...
                [0 0], ...
                'VariableNames', {'solid', 'hatched'}, ...
                'RowNames', {'r1'});
            upper = array2table( ...
                [1 1], ...
                'VariableNames', {'solid', 'hatched'}, ...
                'RowNames', {'r1'});
            bestfit = array2table( ...
                [0.25 0.75], ...
                'VariableNames', {'solid', 'hatched'}, ...
                'RowNames', {'r1'});

            RangePlot( ...
                axesObject, ...
                upper, ...
                lower, ...
                Bestfit = bestfit, ...
                BestfitColors = ["#AA0000"; "#00AA00"], ...
                BestfitDiamondMarkerSize = 11, ...
                Colors = ["#112233"; "#445566"], ...
                Patterns = ["solid"; "crosshatch"]);

            dataGroup = findobj( ...
                axesObject, 'Type', 'hggroup', 'Tag', 'RangePlotGroup');
            testCase.verifyNotEmpty(dataGroup);
            testCase.verifyGreaterThan( ...
                numel(findall(dataGroup, 'Type', 'line')), 2);
            bestfitGroup = findobj( ...
                axesObject, 'Type', 'hggroup', ...
                'Tag', 'RangePlotBestfitGroup');
            bestfitMarkers = findall(bestfitGroup, 'Type', 'line');
            testCase.verifyNumElements(bestfitMarkers, 2);
            testCase.verifyEqual( ...
                [bestfitMarkers.MarkerSize], [11 11]);
            markerColors = vertcat(bestfitMarkers.MarkerFaceColor);
            testCase.verifyEqual( ...
                sortrows(markerColors), ...
                sortrows([170 0 0; 0 170 0] / 255), ...
                'AbsTol', 1e-12);

        end

        function rejectsUnknownPattern(testCase)

            figureObject = figure('Visible', 'off');
            testCase.addTeardown(@() close(figureObject));
            axesObject = axes(figureObject);
            lower = array2table(0, ...
                'VariableNames', {'A'}, 'RowNames', {'r1'});
            upper = array2table(1, ...
                'VariableNames', {'A'}, 'RowNames', {'r1'});

            testCase.verifyError( ...
                @() RangePlot( ...
                axesObject, upper, lower, Patterns = "unknown"), ...
            "OpenMebius2:RangePlot:InvalidPattern");

        end

    end

end
