classdef ReportResultTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(testCase)

            addpath(ReportResultTest.sourcePath());
            addpath(ReportResultTest.testsPath());
            testCase.assumeFalse(isempty( ...
                meta.class.fromName("mlreportgen.report.Report")), ...
                "MATLAB Report Generator is not available.");

        end

    end

    methods (Test)

        function buildsCompleteSingleFileReport(testCase)

            resultDirectory = ReportResultTest.createResultDirectory();
            cleanup = onCleanup(@() ...
                ReportResultTest.removeDirectory(resultDirectory));
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            resultID = "batch-1";
            ReportResultTest.writeBytes( ...
                resultLocation.resultFile(resultID), ...
                uint8(1:8));
            openmebius.infrastructure.filesystem.JsonFileStore() ...
                .writeAtomically( ...
                resultLocation.manifestFile(resultID), ...
                ReportResultTest.manifest(resultID));

            report = ReportResult( ...
                resultLocation, ...
                helpers.ReportModelStub(), ...
                helpers.ReportExperimentsStub(), ...
                helpers.ReportResultDataStub(), ...
                OpenAfterBuild = false);

            outputPath = report.getOutputPath();
            testCase.verifyEqual( ...
                outputPath, ...
                fullfile(resultDirectory, "summary.html"));
            testCase.verifyTrue(isfile(outputPath));
            output = string(fileread(outputPath));
            testCase.verifyTrue(contains(output, "OpenMebius2 Analysis Report"));
            testCase.verifyTrue(contains(output, "openmebius-report-style"));
            testCase.verifyTrue(contains(output, "--om-accent: #087f72"));
            testCase.verifyTrue(contains(output, "@media (max-width: 720px)"));
            testCase.verifyTrue(contains(output, "overflow-x: auto"));
            testCase.verifyTrue(contains(output, "openmebius-report-table"));
            testCase.verifyTrue(contains(output, "Overview"));
            testCase.verifyTrue(contains( ...
                output, ...
                "Analysis Results and Reproducibility"));
            testCase.verifyTrue(contains(output, "Experimental Data"));
            testCase.verifyTrue(contains(output, "Model Information"));
            testCase.verifyTrue(contains(output, resultID));
            testCase.verifyTrue(contains(output, "2.4.3"));
            testCase.verifyTrue(contains(output, "model-sha256"));
            testCase.verifyTrue(contains(output, "<span>Test model</span>"));
            testCase.verifyFalse(contains( ...
                output, ...
                "<span>""Test model""</span>"));
            testCase.verifyTrue(contains(output, "<span>0.8</span>"));
            testCase.verifyFalse(contains(output, "0.80000000000000004"));
            testCase.verifyTrue(contains(output, "<span>Row</span>"));
            generatedFiles = dir(resultDirectory);
            generatedNames = string({generatedFiles(~[generatedFiles.isdir]).name});
            testCase.verifyFalse(any(endsWith(generatedNames, ".tmp")));

            clear cleanup

        end

        function reportsLegacyResultWithoutManifest(testCase)

            resultDirectory = ReportResultTest.createResultDirectory();
            cleanup = onCleanup(@() ...
                ReportResultTest.removeDirectory(resultDirectory));
            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            ReportResultTest.writeBytes( ...
                resultLocation.resultFile("legacy-result"), ...
                uint8(1:4));

            report = ReportResult( ...
                resultLocation, ...
                helpers.ReportModelStub(), ...
                helpers.ReportExperimentsStub(), ...
                helpers.ReportResultDataStub(), ...
                OpenAfterBuild = false);

            output = string(fileread(report.getOutputPath()));
            testCase.verifyTrue(contains(output, "legacy-result"));
            testCase.verifyTrue(contains(output, "Manifest is not available"));

            clear cleanup

        end

        function rejectsErroredInput(testCase)

            resultDirectory = ReportResultTest.createResultDirectory();
            cleanup = onCleanup(@() ...
                ReportResultTest.removeDirectory(resultDirectory));
            model = helpers.ReportModelStub();
            model.isError = true;

            testCase.verifyError( ...
                @() ReportResult( ...
                resultDirectory, ...
                model, ...
                helpers.ReportExperimentsStub(), ...
                helpers.ReportResultDataStub(), ...
                OpenAfterBuild = false), ...
                "OpenMebius2:Report:DataUnavailable");

            clear cleanup

        end

        function publicEntryPointReturnsGenerationResult(testCase)

            resultDirectory = ReportResultTest.createResultDirectory();
            cleanup = onCleanup(@() ...
                ReportResultTest.removeDirectory(resultDirectory));

            service = openmebius.application.report ...
                .ReportGenerationService();
            generationResult = service.generate( ...
                openmebius.domain.result.ResultLocation.fromDirectory( ...
                    resultDirectory), ...
                helpers.ReportModelStub(), ...
                helpers.ReportExperimentsStub(), ...
                helpers.ReportResultDataStub(), ...
                IsDeployed = false, ...
                OpenReport = false);

            testCase.verifyClass( ...
                generationResult, ...
                "openmebius.application.report.ReportGenerationResult");
            testCase.verifyEqual( ...
                generationResult.OutputPath, ...
                fullfile(resultDirectory, "summary.html"));
            testCase.verifyTrue(isfile(generationResult.OutputPath));

            clear cleanup

        end

    end

    methods (Static, Access = private)

        function document = manifest(resultID)

            document = struct( ...
                'schemaVersion', 1, ...
                'batch', struct( ...
                    'id', resultID, ...
                    'contentHash', "sha256:content", ...
                    'contentHashVersion', 1), ...
                'result', struct( ...
                    'file', resultID + ".h5", ...
                    'sha256', "result-sha256", ...
                    'sizeBytes', 8, ...
                    'status', "finished"), ...
                'software', struct( ...
                    'openMebius2Version', "2.4.3", ...
                    'matlabRelease', "R2026a", ...
                    'matlabVersion', "26.1", ...
                    'toolboxes', struct.empty(0, 1)), ...
                'model', struct( ...
                    'fileName', "model.xlsx", ...
                    'sha256', "model-sha256"), ...
                'experiments', struct( ...
                    'name', "experiment-a", ...
                    'fileName', "experiment-a.xlsx", ...
                    'sha256', "experiment-sha256"), ...
                'analysis', struct( ...
                    'metadataSchemaVersion', 1, ...
                    'config', struct( ...
                        'iteration', 30, ...
                        'algorithm', "interior-point")), ...
                'random', struct( ...
                    'type', "twister", ...
                    'seed', 42, ...
                    'state', [1; 2; 3]), ...
                'run', struct( ...
                    'startedAtUtc', "2026-07-14T00:00:00.000Z", ...
                    'finishedAtUtc', "2026-07-14T00:01:00.000Z", ...
                    'isError', false, ...
                    'isCanceled', false));

        end

        function directory = createResultDirectory()

            directory = string(tempname);
            mkdir(directory);

        end

        function writeBytes(pathFile, bytes)

            fid = fopen(pathFile, 'wb');

            if fid < 0
                error( ...
                    "ReportResultTest:OpenFailed", ...
                    "Unable to create result fixture: %s", ...
                    pathFile);
            end

            cleanup = onCleanup(@() fclose(fid));
            fwrite(fid, bytes, 'uint8');
            clear cleanup

        end

        function path = sourcePath()

            path = fullfile(ReportResultTest.repositoryRoot(), "src");

        end

        function path = testsPath()

            path = fullfile(ReportResultTest.repositoryRoot(), "tests");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, "s");
            end

        end

    end

end
