classdef ReportGenerationServiceTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(ReportGenerationServiceTest.sourcePath());

        end

    end

    methods (Test)

        function generateUsesReportRepository(testCase)

            resultDirectory = string(tempname);
            mkdir(resultDirectory);
            cleanup = onCleanup(@() ...
                ReportGenerationServiceTest.removeDirectory(resultDirectory));

            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(resultDirectory);
            outputPath = fullfile(resultDirectory, "summary");

            service = openmebius.application.report.ReportGenerationService( ...
                ReportRepository = ReportGenerationServiceTest ...
                .fakeRepository( ...
                Create = @(location, model, experiments, result) ...
                struct("Directory", location.Directory, "Created", true), ...
                View = @(report) error("Test:UnexpectedViewer", ...
                "Report viewer should not be called."), ...
                OutputPath = @(report, location) outputPath));

            generationResult = service.generate( ...
                resultLocation, ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                IsDeployed = false, ...
                OpenReport = false);

            testCase.verifyClass( ...
                generationResult, ...
                "openmebius.application.report.ReportGenerationResult");
            testCase.verifyTrue(generationResult.Report.Created);
            testCase.verifyEqual( ...
                generationResult.Report.Directory, ...
                resultDirectory);
            testCase.verifyEqual(generationResult.OutputPath, outputPath);
            testCase.verifyTrue( ...
                any(contains(generationResult.Messages, outputPath)));
            testCase.verifyGreaterThanOrEqual( ...
                numel(generationResult.Messages), ...
                2);

        end

        function generateOpensReportWhenRequested(testCase)

            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(tempdir);

            viewCount = 0;
            viewedReport = struct();

            service = openmebius.application.report.ReportGenerationService( ...
                ReportRepository = ReportGenerationServiceTest ...
                .fakeRepository( ...
                Create = @(location, model, experiments, result) ...
                struct("Directory", location.Directory, "Created", true), ...
                View = @captureReport));

            generationResult = service.generate( ...
                resultLocation, ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                IsDeployed = false, ...
                OpenReport = true);

            testCase.verifyEqual(viewCount, 1);
            testCase.verifyTrue(viewedReport.Created);
            testCase.verifyEqual(generationResult.Report, viewedReport);

            function captureReport(report)

                viewCount = viewCount + 1;
                viewedReport = report;

            end

        end

        function generateRejectsDeployedRuntime(testCase)

            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(tempdir);

            service = openmebius.application.report.ReportGenerationService( ...
                ReportRepository = ReportGenerationServiceTest.fakeRepository());

            testCase.verifyError( ...
                @() service.generate( ...
                resultLocation, ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                IsDeployed = true), ...
                "OpenMebius2:Report:UnavailableInDeployed");

        end

        function generateRejectsUnavailableData(testCase)

            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(tempdir);

            service = openmebius.application.report.ReportGenerationService( ...
                ReportRepository = ReportGenerationServiceTest.fakeRepository());

            testCase.verifyError( ...
                @() service.generate( ...
                resultLocation, ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.erroredData(), ...
                IsDeployed = false), ...
                "OpenMebius2:Report:DataUnavailable");

        end

        function generateRejectsMissingResultDirectory(testCase)

            resultLocation = openmebius.domain.result.ResultLocation ...
                .fromDirectory(fullfile(tempdir, "missing-openmebius-report"));

            service = openmebius.application.report.ReportGenerationService( ...
                ReportRepository = ReportGenerationServiceTest.fakeRepository());

            testCase.verifyError( ...
                @() service.generate( ...
                resultLocation, ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                ReportGenerationServiceTest.availableData(), ...
                IsDeployed = false), ...
                "OpenMebius2:Report:ResultDirectoryNotFound");

        end

    end

    methods (Static, Access = private)

        function data = availableData()

            data = struct("isError", false);

        end

        function data = erroredData()

            data = struct("isError", true);

        end

        function repository = fakeRepository(options)

            arguments
                options.Create (1, 1) function_handle = ...
                    @(location, model, experiments, result) []
                options.View (1, 1) function_handle = @(report) []
                options.OutputPath (1, 1) function_handle = ...
                    @(report, location) location.summaryReportFile()
            end

            repository = struct( ...
                "create", options.Create, ...
                "view", options.View, ...
                "outputPath", options.OutputPath);

        end

        function path = sourcePath()

            path = fullfile( ...
                ReportGenerationServiceTest.repositoryRoot(), ...
                "src");

        end

        function path = repositoryRoot()

            path = fileparts(fileparts(mfilename("fullpath")));

        end

        function removeDirectory(directory)

            if isfolder(directory)
                rmdir(directory, "s");
            end

        end

    end

end
