classdef ResultRangePlotServiceTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));
            addpath(fullfile(root, "tests"));

        end

    end

    methods (Test)

        function preparesAlignedBoundsAndBestFits(testCase)

            workspace = helpers.ResultRangePlotWorkspaceStub();
            workspace.addOverview( ...
                "batch-a", testCase.overview( ...
                ["r1"; "r2"], ["First"; "Second"], ...
                [1; 2], [0.8; NaN], [1.2; NaN], ...
                [0.5; 1.5], [1.5; 2.5]));
            workspace.addOverview( ...
                "batch-b", testCase.overview( ...
                ["r2"; "r1"], ["Second"; "First"], ...
                [3; 4], [2.5; 3.5], [3.5; 4.5], ...
                [2; 3], [4; 5]));
            service = openmebius.application.result ...
                .ResultRangePlotService();

            result = service.prepare( ...
                workspace, ["batch-a"; "batch-b"], ...
                ["Batch A"; "Batch B"]);

            testCase.verifyEqual( ...
                result.LowerBounds{:, :}, [0.8 3.5; 1.5 2.5]);
            testCase.verifyEqual( ...
                result.UpperBounds{:, :}, [1.2 4.5; 2.5 3.5]);
            testCase.verifyEqual( ...
                result.BestFits{:, :}, [1 4; 2 3]);
            testCase.verifyEqual( ...
                string(result.LowerBounds.Properties.RowNames), ...
                ["r1"; "r2"]);
            testCase.verifyEqual( ...
                result.ReactionNames, ...
                ["r1 : First"; "r2 : Second"]);
            testCase.verifyEqual( ...
                result.Messages, ...
                "FVA bounds were used where confidence intervals " + ...
                "were unavailable.");

        end

        function excludesRowsWithoutAnyFiniteBounds(testCase)

            workspace = helpers.ResultRangePlotWorkspaceStub();
            workspace.addOverview( ...
                "batch-a", testCase.overview( ...
                ["r1"; "r2"], ["First"; "Second"], ...
                [1; NaN], [0; NaN], [2; NaN], ...
                [-1; NaN], [3; NaN]));
            service = openmebius.application.result ...
                .ResultRangePlotService();

            result = service.prepare( ...
                workspace, "batch-a", "Batch A");

            testCase.verifyEqual(height(result.LowerBounds), 1);
            testCase.verifyEqual( ...
                result.Messages, ...
                "1 reactions without finite bounds were excluded.");

        end

        function requiresSelection(testCase)

            service = openmebius.application.result ...
                .ResultRangePlotService();
            workspace = helpers.ResultRangePlotWorkspaceStub();

            testCase.verifyError( ...
                @() service.prepare( ...
                workspace, strings(0, 1), strings(0, 1)), ...
                "OpenMebius2:ResultRangePlot:SelectionRequired");

        end

        function rejectsMismatchedReactions(testCase)

            workspace = helpers.ResultRangePlotWorkspaceStub();
            workspace.addOverview( ...
                "batch-a", testCase.overview( ...
                "r1", "First", 1, 0, 2, -1, 3));
            workspace.addOverview( ...
                "batch-b", testCase.overview( ...
                "r2", "Second", 1, 0, 2, -1, 3));
            service = openmebius.application.result ...
                .ResultRangePlotService();

            testCase.verifyError( ...
                @() service.prepare( ...
                workspace, ["batch-a"; "batch-b"], ...
                ["A"; "B"]), ...
                "OpenMebius2:ResultRangePlot:ReactionMismatch");

        end

        function reportsUnavailableBounds(testCase)

            workspace = helpers.ResultRangePlotWorkspaceStub();
            workspace.addOverview( ...
                "batch-a", testCase.overview( ...
                "r1", "First", NaN, NaN, NaN, NaN, NaN));
            service = openmebius.application.result ...
                .ResultRangePlotService();

            testCase.verifyError( ...
                @() service.prepare(workspace, "batch-a", "A"), ...
                "OpenMebius2:ResultRangePlot:DataUnavailable");

        end

        function reversesPredominantlyNegativeReversibleRanges(testCase)

            workspace = helpers.ResultRangePlotWorkspaceStub();
            workspace.addOverview( ...
                "batch-a", testCase.overview( ...
                ["r1"; "r2"; "r3"], ...
                ["A <=> B"; "C <=> D"; "E <=> F"], ...
                [-3; 1; -2], [-5; -1; -4], [2; 3; -1], ...
                [-5; -1; -4], [2; 3; -1]));
            service = openmebius.application.result ...
                .ResultRangePlotService();

            result = service.prepare( ...
                workspace, "batch-a", "Batch A");

            testCase.verifyEqual( ...
                result.LowerBounds{:, :}, [-2; -1; 1]);
            testCase.verifyEqual(result.UpperBounds{:, :}, [5; 3; 4]);
            testCase.verifyEqual(result.BestFits{:, :}, [3; 1; 2]);
            testCase.verifyEqual( ...
                result.ReactionNames, ...
                ["r1 : B <=> A"; "r2 : C <=> D"; "r3 : F <=> E"]);

        end

    end % methods (Test)

    methods (Static, Access = private)

        function data = overview( ...
                ids, reactions, flux, lower, upper, fvaLower, fvaUpper)

            data = table( ...
                string(reactions(:)), ...
                double(flux(:)), ...
                double(lower(:)), ...
                double(upper(:)), ...
                double(fvaLower(:)), ...
                double(fvaUpper(:)), ...
                'VariableNames', [ ...
                "Reaction", "Flux", "LB", "UB", ...
                "LB (FVA)", "UB (FVA)"], ...
                'RowNames', cellstr(string(ids(:))));

        end

    end % methods (Static, Access = private)

end % classdef
