classdef ResultOperationControllerTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));
            addpath(fullfile(root, "tests"));

        end

    end

    methods (Test)

        function generatesReport(testCase)

            reportService = helpers.ReportGenerationServiceStub();
            reportService.Result = struct("Messages", "Generated.");
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = ...
                helpers.ResultExportServiceStub(), ...
                ReportGenerationService = reportService);
            location = openmebius.domain.result ...
                .ResultLocation.fromDirectory(tempdir);

            outcome = controller.generateReport( ...
                location, "model", "experiments", "result", ...
                IsDeployed = false);

            testCase.verifyTrue(outcome.isSuccess());
            testCase.verifyEqual(outcome.Result, reportService.Result);
            testCase.verifyTrue(reportService.Called);
            testCase.verifyEqual(reportService.Inputs{1}, location);
            testCase.verifyEmpty(outcome.Exception);

        end

        function exportsSelectedResults(testCase)

            exportService = helpers.ResultExportServiceStub();
            exportService.Result = struct("Messages", "Exported.");
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = exportService, ...
                ReportGenerationService = ...
                helpers.ReportGenerationServiceStub());
            location = openmebius.domain.result ...
                .ResultLocation.fromDirectory(tempdir);

            outcome = controller.exportResults( ...
                "result", ["batch-1"; "batch-2"], ...
                ["First"; "Second"], location);

            testCase.verifyTrue(outcome.isSuccess());
            testCase.verifyTrue(exportService.Called);
            testCase.verifyEqual( ...
                exportService.Inputs{2}, ["batch-1"; "batch-2"]);
            testCase.verifyEqual( ...
                exportService.Inputs{3}, ["First"; "Second"]);

        end

        function capturesOperationFailure(testCase)

            exportService = helpers.ResultExportServiceStub();
            exportService.Exception = MException( ...
                "OpenMebius2:ResultExport:ResultUnavailable", ...
                "Result data is not available.");
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = exportService, ...
                ReportGenerationService = ...
                helpers.ReportGenerationServiceStub());
            location = openmebius.domain.result ...
                .ResultLocation.fromDirectory(tempdir);

            outcome = controller.exportResults( ...
                [], "batch-1", "First", location);

            testCase.verifyTrue(outcome.isFailure());
            testCase.verifyEqual( ...
                outcome.ErrorMessage, ...
                "Result data is not available.");
            testCase.verifyEqual( ...
                string(outcome.Exception.identifier), ...
                "OpenMebius2:ResultExport:ResultUnavailable");

        end

        function loadsResultSuggestion(testCase)

            suggestionService = helpers.ResultSuggestionServiceStub();
            suggestionService.Result = openmebius.application.result ...
                .ResultSuggestionResult( ...
                Suggestion = struct("Value", 1), ...
                BatchID = "batch-1", ...
                BatchName = "First");
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = ...
                helpers.ResultExportServiceStub(), ...
                ReportGenerationService = ...
                helpers.ReportGenerationServiceStub(), ...
                ResultSuggestionService = suggestionService);
            resultData = helpers.ResultSuggestionWorkspaceStub();

            outcome = controller.loadSuggestion( ...
                resultData, "batch-1", "First");

            testCase.verifyTrue(outcome.isSuccess());
            testCase.verifyTrue(suggestionService.Called);
            testCase.verifyEqual( ...
                suggestionService.ResultData, resultData);
            testCase.verifyEqual( ...
                suggestionService.BatchIDs, "batch-1");
            testCase.verifyEqual( ...
                outcome.Result, suggestionService.Result);

        end

        function capturesSuggestionFailure(testCase)

            suggestionService = helpers.ResultSuggestionServiceStub();
            suggestionService.Exception = MException( ...
                "OpenMebius2:ResultSuggestion:NotAvailable", ...
                "No suggestion is available.");
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = ...
                helpers.ResultExportServiceStub(), ...
                ReportGenerationService = ...
                helpers.ReportGenerationServiceStub(), ...
                ResultSuggestionService = suggestionService);

            outcome = controller.loadSuggestion( ...
                "result", "batch-1", "First");

            testCase.verifyTrue(outcome.isFailure());
            testCase.verifyEqual( ...
                outcome.ErrorMessage, "No suggestion is available.");

        end

        function preparesResultRangePlot(testCase)

            rangeService = helpers.ResultRangePlotServiceStub();
            rangeService.Result = "prepared-range";
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = ...
                helpers.ResultExportServiceStub(), ...
                ReportGenerationService = ...
                helpers.ReportGenerationServiceStub(), ...
                ResultRangePlotService = rangeService);

            outcome = controller.prepareRangePlot( ...
                "result", ["batch-1"; "batch-2"], ...
                ["First"; "Second"]);

            testCase.verifyTrue(outcome.isSuccess());
            testCase.verifyTrue(rangeService.Called);
            testCase.verifyEqual( ...
                rangeService.BatchIDs, ["batch-1"; "batch-2"]);
            testCase.verifyEqual(outcome.Result, "prepared-range");

        end

        function capturesRangePlotFailure(testCase)

            rangeService = helpers.ResultRangePlotServiceStub();
            rangeService.Exception = MException( ...
                "OpenMebius2:ResultRangePlot:SelectionRequired", ...
                "Select a result.");
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = ...
                helpers.ResultExportServiceStub(), ...
                ReportGenerationService = ...
                helpers.ReportGenerationServiceStub(), ...
                ResultRangePlotService = rangeService);

            outcome = controller.prepareRangePlot( ...
                "result", strings(0, 1), strings(0, 1));

            testCase.verifyTrue(outcome.isFailure());
            testCase.verifyEqual( ...
                string(outcome.Exception.identifier), ...
                "OpenMebius2:ResultRangePlot:SelectionRequired");

        end

        function comparesResultSettings(testCase)

            diffService = helpers.ResultDiffServiceStub();
            diffService.Result = openmebius.application.result.ResultDiff( ...
                BatchIDs = ["batch-1"; "batch-2"], ...
                BatchNames = ["First"; "Second"], ...
                Differences = "iteration: 12 -> 30");
            controller = openmebius.application.result ...
                .ResultOperationController( ...
                ResultExportService = ...
                helpers.ResultExportServiceStub(), ...
                ReportGenerationService = ...
                helpers.ReportGenerationServiceStub(), ...
                ResultDiffService = diffService);

            outcome = controller.compareSettings( ...
                "result", ...
                ["batch-1"; "batch-2"], ...
                ["First"; "Second"]);

            testCase.verifyTrue(outcome.isSuccess());
            testCase.verifyTrue(diffService.Called);
            testCase.verifyEqual(diffService.ResultData, "result");
            testCase.verifyEqual( ...
                diffService.BatchIDs, ["batch-1"; "batch-2"]);
            testCase.verifyEqual(outcome.Result, diffService.Result);

        end

    end % methods (Test)

end % classdef
