classdef ResultPresenterTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));

        end

    end

    methods (Test)

        function abbreviatesResultIdAndPreservesRawId(testCase)

            batch = helpers.BatchOperationStub();
            batch.Data.ID = "bat_dd0eff6798474f24b58b6657e5dd0354";
            batch.Status = "finished";
            presenter = openmebius.presentation.result.ResultPresenter();

            viewModel = presenter.presentIndex( ...
                helpers.ResultIndexStub(), batch);

            testCase.verifyEqual(viewModel.Data.ID, "bat_dd0eff");
            testCase.verifyEqual( ...
                viewModel.RawData.ID, ...
                "bat_dd0eff6798474f24b58b6657e5dd0354");

        end

        function presentsMDVMode(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            result = helpers.ReportResultDataStub();

            viewModel = presenter.presentMain(result, "MDV", "batch-1");

            testCase.verifyEqual(viewModel.RawData.Fragment, "Ala159");
            testCase.verifyEqual(viewModel.RawData.Estimated, 0.79);

        end

        function mapsLegacyDetailsModeToMDV(testCase)

            mode = openmebius.presentation.result ...
                .ResultViewMode.normalize("Details");

            testCase.verifyEqual(mode, "MDV");

        end

        function presentsMDVSummaryMode(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            result = helpers.ReportResultDataStub();

            viewModel = presenter.presentMain( ...
                result, "MDV (Summary)", "batch-1");

            testCase.verifyEqual(viewModel.RawData.Metabolite, "Ala159");
            testCase.verifyEqual( ...
                viewModel.RawData.("E[MDV_e] - E[MDV_s]"), -0.01);
            testCase.verifyEqual( ...
                viewModel.RawData.("W_1(MDV_e, MDV_s)"), 0.01);
            testCase.verifyEqual(viewModel.RawData.("χ^2"), 2);
            testCase.verifyEqual( ...
                viewModel.Data.("E[MDV_e] - E[MDV_s]"), "-1%");
            testCase.verifyEqual( ...
                viewModel.Data.("W_1(MDV_e, MDV_s)"), "0.010");
            testCase.verifyEqual(viewModel.Data.("χ^2"), "2.00");

            backgroundRule = viewModel.StyleRules( ...
                string({viewModel.StyleRules.StyleKey}) == "background");
            testCase.verifyNumElements(backgroundRule, 1);
            testCase.verifyEqual(backgroundRule.Target, "cell");
            testCase.verifyEqual(backgroundRule.Rows, 1);
            testCase.verifyEqual(backgroundRule.Columns, 4);
            testCase.verifyNotEqual(backgroundRule.Value, "");

        end

        function presentsGeneratedReport(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            report = struct("Created", true);
            operationResult = struct( ...
                "Report", report, ...
                "Messages", ["Generated."; "Opened."]);
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                true, Result = operationResult);

            viewModel = presenter.presentReportOutcome(outcome);
            messages = cellfun( ...
                @(notification) notification.Message, ...
                viewModel.Notifications);

            testCase.verifyEqual(viewModel.Report, report);
            testCase.verifyEqual(messages, ["Generated."; "Opened."]);

        end

        function presentsUnexpectedReportFailureAsAlert(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:Test:Unexpected", ...
                "Unexpected failure.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentReportOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "error");
            testCase.verifyEqual( ...
                notification.Title, "Report generation failed");
            testCase.verifyTrue(notification.ShowAlert);

        end

        function presentsKnownExportFailureWithoutAlert(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:ResultExport:EmptySelection", ...
                "Please select a result to save.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentExportOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "error");
            testCase.verifyFalse(notification.ShowAlert);

        end

        function presentsReloadAndMissingSelection(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();

            reloadViewModel = presenter.presentReloaded();
            selectionViewModel = ...
                presenter.presentExportSelectionRequired();

            testCase.verifyEqual( ...
                reloadViewModel.Notifications{1}.Message, ...
                "Result data reloaded");
            testCase.verifyEqual( ...
                selectionViewModel.Notifications{1}.Level, ...
                "warning");

        end

        function presentsResultSuggestion(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            suggestion = struct("Value", 1);
            result = openmebius.application.result ...
                .ResultSuggestionResult( ...
                Suggestion = suggestion, ...
                BatchID = "batch-1", ...
                BatchName = "First");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome(true, Result = result);

            viewModel = presenter.presentSuggestionOutcome(outcome);

            testCase.verifyEqual(viewModel.Suggestion, suggestion);
            testCase.verifyEmpty(viewModel.Notifications);

        end

        function presentsSuggestionSelectionErrorAsWarning(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:ResultSuggestion:SelectionRequired", ...
                "Please select one result.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentSuggestionOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "warning");
            testCase.verifyFalse(notification.ShowAlert);

        end

        function presentsUnexpectedSuggestionFailureAsAlert(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:Test:Unexpected", ...
                "Unexpected failure.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentSuggestionOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "error");
            testCase.verifyEqual( ...
                notification.Title, "Suggestion load failed");
            testCase.verifyTrue(notification.ShowAlert);

        end

        function presentsRelativeFluxSelection(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();

            viewModel = presenter.presentRelativeSelection( ...
                ["R1"; "R2"], 2);

            testCase.verifyEqual(viewModel.RelativeTo, "R2");
            testCase.verifyEmpty(viewModel.Notifications);

        end

        function presentsMissingRelativeFluxSelection(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();

            viewModel = presenter.presentRelativeSelection( ...
                ["R1"; "R2"], zeros(0, 1));
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(viewModel.RelativeTo, "");
            testCase.verifyEqual(notification.Level, "warning");
            testCase.verifyEqual( ...
                notification.Message, ...
                "Please select a flux to set relative values.");

        end

        function rejectsUnavailableRelativeReactionName(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();

            viewModel = presenter.presentRelativeSelection( ...
                strings(0, 1), 1);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(viewModel.RelativeTo, "");
            testCase.verifyEqual(notification.Level, "warning");
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "Reaction identifiers"));

        end

        function presentsPreparedRangePlot(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            upper = array2table(2, ...
                'VariableNames', {'Batch'}, 'RowNames', {'r1'});
            lower = array2table(0, ...
                'VariableNames', {'Batch'}, 'RowNames', {'r1'});
            bestFit = array2table(1, ...
                'VariableNames', {'Batch'}, 'RowNames', {'r1'});
            result = openmebius.application.result ...
                .ResultRangePlotResult( ...
                UpperBounds = upper, ...
                LowerBounds = lower, ...
                BestFits = bestFit, ...
                ReactionNames = "r1 : First", ...
                Messages = "FVA bounds were used.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome(true, Result = result);

            viewModel = presenter.presentRangePlotOutcome(outcome);

            testCase.verifyEqual(viewModel.UpperBounds, upper);
            testCase.verifyEqual(viewModel.LowerBounds, lower);
            testCase.verifyEqual(viewModel.BestFits, bestFit);
            testCase.verifyEqual( ...
                viewModel.Notifications{1}.Message, ...
                "FVA bounds were used.");

        end

        function presentsRangePlotSelectionErrorAsWarning(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:ResultRangePlot:SelectionRequired", ...
                "Please select a result.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentRangePlotOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEmpty(viewModel.UpperBounds);
            testCase.verifyEqual(notification.Level, "warning");
            testCase.verifyFalse(notification.ShowAlert);

        end

        function presentsUnexpectedRangePlotFailureAsAlert(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:Test:Unexpected", ...
                "Unexpected failure.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentRangePlotOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "error");
            testCase.verifyEqual(notification.Title, "Range plot failed");
            testCase.verifyTrue(notification.ShowAlert);

        end

        function presentsBatchInformationForTheUiConsole(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            information = openmebius.application.result ...
                .ResultInformation( ...
                BatchID = "batch-1", ...
                BatchName = "First", ...
                Description = "Description", ...
                ExperimentNames = ["exp-a"; "exp-b"], ...
                StartedAtUtc = "2026-08-18T01:02:03.000Z", ...
                FinishedAtUtc = "2026-08-18T01:03:05.500Z", ...
                ElapsedSeconds = 62.5, ...
                DifferentSettings = ...
                "iteration: 12 (default: 30)", ...
                SettingsAvailable = true, ...
                MDVDegreesOfFreedom = 4, ...
                EffluxDegreesOfFreedom = 2, ...
                ModelDegreesOfFreedom = 3, ...
                HasEffluxContribution = true, ...
                MDVRSSContribution = 8, ...
                EffluxRSSContribution = 2, ...
                ChiSquareThreshold = 9.49);
            outcome = openmebius.application.result ...
                .ResultOperationOutcome(true, Result = information);

            viewModel = presenter.presentInformationOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "info");
            testCase.verifyFalse(notification.ShowAlert);
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "Elapsed time: 00:01:02.500"));
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "iteration: 12 (default: 30)"));
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "Efflux: 2"));
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "Chi-square test threshold: 9.49"));

        end

        function presentsInformationSelectionErrorAsWarning(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:ResultInformation:SelectionRequired", ...
                "Please select exactly one result.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentInformationOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "warning");
            testCase.verifyFalse(notification.ShowAlert);

        end

        function presentsAnalysisConditionDiffForTheUiConsole(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            comparison = openmebius.application.result.ResultDiff( ...
                BatchIDs = ["batch-1"; "batch-2"], ...
                BatchNames = ["First"; "Second"], ...
                Differences = [ ...
                "iteration: 12 -> 30"; ...
                "MS.fragmentList: ""frag-a"" -> ""frag-b"""]);
            outcome = openmebius.application.result ...
                .ResultOperationOutcome(true, Result = comparison);

            viewModel = presenter.presentDiffOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "info");
            testCase.verifyFalse(notification.ShowAlert);
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "First: First (batch-1)"));
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "iteration: 12 -> 30"));
            testCase.verifyThat( ...
                notification.Message, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                "MS.fragmentList"));

        end

        function presentsDiffMetadataErrorAsWarning(testCase)

            presenter = openmebius.presentation.result.ResultPresenter();
            exception = MException( ...
                "OpenMebius2:ResultDiff:DataUnavailable", ...
                "Saved settings are unavailable.");
            outcome = openmebius.application.result ...
                .ResultOperationOutcome( ...
                false, ...
                ErrorMessage = string(exception.message), ...
                Exception = exception);

            viewModel = presenter.presentDiffOutcome(outcome);
            notification = viewModel.Notifications{1};

            testCase.verifyEqual(notification.Level, "warning");
            testCase.verifyFalse(notification.ShowAlert);

        end

    end % methods (Test)

end % classdef
