classdef RunConfigBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function appDoesNotLoadBatchTablesDirectly(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "RunConfig_exported.m")));
            directCalls = [ ...
                "Session.effluxTable", ...
                "Session.suggestionTable", ...
                "Session.instPoolTable", ...
                "Session.instTimePointTable", ...
                "Session.msFragmentSelections", ...
                "Session.BatchIds", ...
                "Session.experimentNames", ...
                "Session.loadTracerConfiguration"];

            for call = directCalls
                testCase.verifyFalse(contains(source, call));
            end

            testCase.verifyFalse(contains(source, "uialert("));
            testCase.verifyFalse(contains(source, "Session.apply("));
            testCase.verifyFalse(contains(source, "Session.primaryConfig("));
            testCase.verifyFalse(contains(source, "MSFragmentTableMapper"));
            testCase.verifyTrue(contains(source, "RunConfigPresenter"));
            testCase.verifyTrue(contains(source, "RunConfigTableViewModel"));
            testCase.verifyTrue( ...
                contains(source, "BatchConfigurationController"));
            testCase.verifyTrue( ...
                contains(source, ...
                    "BatchExperimentSelectionEditorController"));
            testCase.verifyTrue( ...
                contains(source, ...
                    "BatchExperimentSelectionEditorPresenter"));
            testCase.verifyTrue( ...
                contains(source, "startupFcn(app, context)"));
            testCase.verifyFalse( ...
                contains(source, ...
                    "experimentController, experimentPresenter"));

        end

        function parentUsesLaunchBoundaryBeforeChildApp(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            testCase.verifyFalse( ...
                contains(source, "BatchConfigurationSession("));
            testCase.verifyFalse( ...
                contains(source, "selectionRows = unique"));
            testCase.verifyFalse( ...
                contains(source, ...
                    "Please select a batch to configure."));
            testCase.verifyTrue( ...
                contains(source, ".createLaunchRequest("));
            testCase.verifyTrue( ...
                contains(source, ...
                    ".prepareBatchConfiguration(requestFactory)"));
            testCase.verifyTrue( ...
                contains(source, ".presentLaunchOutcome(outcome)"));
            testCase.verifyTrue( ...
                contains(source, ...
                    "renderRunConfigLaunchViewModel(viewModel)"));
            testCase.verifyTrue( ...
                contains(source, "app.closeRunConfigApp()"));
            testCase.verifyTrue( ...
                contains(source, ".RunConfigContext("));
            testCase.verifyTrue( ...
                contains(source, "RunConfig(context)"));
            testCase.verifyTrue( ...
                contains(source, "app.ExperimentEditController"));
            testCase.verifyTrue( ...
                contains(source, "app.ExperimentPresenter"));
            testCase.verifyTrue( ...
                contains(source, ...
                    "app.BatchExperimentSelectionEditorController"));
            testCase.verifyTrue( ...
                contains(source, ...
                    "app.BatchExperimentSelectionEditorPresenter"));
            testCase.verifyTrue(contains( ...
                source, ".RunAddBatchContext(Editor = viewModel)"));
            testCase.verifyTrue(contains( ...
                source, "RunAddBatch(context)"));

        end

        function mainAppUsesTypedExperimentSelectionEditorBoundary( ...
                testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));

            testCase.verifyFalse( ...
                contains(source, "getExpList(app.exp)"));
            testCase.verifyTrue( ...
                contains(source, ...
                    ".prepareParallelBatch()"));
            testCase.verifyTrue( ...
                contains(source, ".presentParallelEditor(outcome)"));
            testCase.verifyTrue( ...
                contains(source, "app.closeRunAddBatchApp()"));

        end

    end % methods (Test)

end % classdef
