classdef RunConfigContextTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));
            addpath(fullfile(root, "tests"));

        end

    end

    methods (Test)

        function storesTypedDependencies(testCase)

            session = openmebius.application.batch ...
                .BatchConfigurationSession( ...
                helpers.RunConfigBatchStub(), [], "batch-a");
            presenter = openmebius.presentation.batch ...
                .RunConfigPresenter();
            editor = presenter.presentEditor(session);
            configurationController = openmebius.application.batch ...
                .BatchConfigurationController();
            experimentEditController = ...
                openmebius.application.experiment ...
                .ExperimentEditController();
            experimentPresenter = openmebius.presentation.experiment ...
                .ExperimentPresenter();
            selectionController = openmebius.application.batch ...
                .BatchExperimentSelectionEditorController();
            selectionPresenter = openmebius.presentation.batch ...
                .BatchExperimentSelectionEditorPresenter();

            context = openmebius.presentation.batch ...
                .RunConfigContext( ...
                Session = session, ...
                Presenter = presenter, ...
                Editor = editor, ...
                ConfigurationController = ...
                configurationController, ...
                ExperimentEditController = ...
                experimentEditController, ...
                ExperimentPresenter = experimentPresenter, ...
                ExperimentSelectionController = ...
                selectionController, ...
                ExperimentSelectionPresenter = ...
                selectionPresenter);

            testCase.verifyEqual(context.Session, session);
            testCase.verifyEqual(context.Presenter, presenter);
            testCase.verifyEqual(context.Editor, editor);
            testCase.verifyEqual( ...
                context.ConfigurationController, ...
                configurationController);
            testCase.verifyEqual( ...
                context.ExperimentSelectionPresenter, ...
                selectionPresenter);

        end

    end % methods (Test)

end % classdef
