classdef RunConfigMapperTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            sourcePath = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');
            addpath(sourcePath);

        end % addSourcePath

    end % methods

    methods (Test)

        function mapsAlgorithmLabels(testCase)

            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.algorithmToView('interior-point'), ...
                'IPMs');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.algorithmToView('sqp'), ...
                'SQP');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.algorithmToConfig('IPMs'), ...
                'interior-point');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.algorithmToConfig('SQP'), ...
                'sqp');

        end % mapsAlgorithmLabels

        function mapsMonteCarloLabels(testCase)

            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.mcOptimizationProcedureToView('single'), ...
                'Single run');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.mcOptimizationProcedureToConfig('Multiple run'), ...
                'multiple');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.mcCalculationMethodToView('discarding'), ...
                'Discarding');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.mcCalculationMethodToConfig('Mean-varianced'), ...
                'mean-varianced');

        end % mapsMonteCarloLabels

        function mapsCIAndGridLabels(testCase)

            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.ciAlgorithmToView('grid search'), ...
                'Grid search');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.ciAlgorithmToConfig('Monte Carlo'), ...
                'Monte Carlo');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.gridThresholdToView('chi-sq'), ...
                'Chi-squared');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.gridThresholdToView('F-dist'), ...
                'F-distribution');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.gridThresholdToConfig('Chi-squared'), ...
                'chi-sq');
            testCase.verifyEqual( ...
                openmebius.presentation.batch.RunConfigMapper.gridThresholdToConfig('F-distribution'), ...
                'f-distribution');

        end % mapsCIAndGridLabels

        function mapsConfigToAndFromViewModel(testCase)

            config = openmebius.domain.batch.BatchConfig.defaultConfig();
            config.algorithm = 'interior-point';
            config.CIConf.algorithm = 'Grid search';
            config.CIConf.grid.threshold = 'chi-sq';
            config.CIConf.MC.optimizationProcedure = 'multiple';
            config.CIConf.MC.calculationMethod = 'discarding';

            viewModel = ...
                openmebius.presentation.batch.RunConfigMapper.toViewModel( ...
                config);

            testCase.verifyEqual(viewModel.Algorithm, 'IPMs');
            testCase.verifyEqual(viewModel.CIAlgorithm, 'Grid search');
            testCase.verifyEqual(viewModel.GridThreshold, 'Chi-squared');
            testCase.verifyEqual( ...
                viewModel.MCOptimizationProcedure, ...
                'Multiple run');
            testCase.verifyEqual(viewModel.MCCalculationMethod, 'Discarding');

            viewModel.Algorithm = 'SQP';
            viewModel.CIAlgorithm = 'Monte Carlo';
            viewModel.GridThreshold = 'F-distribution';
            viewModel.MCOptimizationProcedure = 'Single run';
            viewModel.MCCalculationMethod = 'Mean-varianced';

            updatedConfig = ...
                openmebius.presentation.batch.RunConfigMapper.fromViewModel( ...
                viewModel, ...
                config);

            testCase.verifyEqual(updatedConfig.algorithm, 'sqp');
            testCase.verifyEqual(updatedConfig.CIConf.algorithm, 'Monte Carlo');
            testCase.verifyEqual( ...
                updatedConfig.CIConf.grid.threshold, ...
                'f-distribution');
            testCase.verifyEqual( ...
                updatedConfig.CIConf.MC.optimizationProcedure, ...
                'single');
            testCase.verifyEqual( ...
                updatedConfig.CIConf.MC.calculationMethod, ...
                'mean-varianced');
            openmebius.domain.batch.BatchConfig.validate(updatedConfig);

        end % mapsConfigToAndFromViewModel

        function rejectsUnknownValue(testCase)

            testCase.verifyError( ...
                @() openmebius.presentation.batch.RunConfigMapper.algorithmToConfig('unknown'), ...
                'OpenMebius2:RunConfigMapper:UnsupportedValue');

        end % rejectsUnknownValue

    end % methods

end % classdef
