classdef SteadyStateObjectiveTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(SteadyStateObjectiveTest.sourcePath());

        end

    end

    methods (Test)

        function evaluatesMDVAndEffluxResiduals(testCase)

            problem = SteadyStateObjectiveTest.createProblem();
            model = helpers.SteadyStateModelStub();
            penalty = openmebius.mfa.EffluxPenalty( ...
                ReactionIndices = 2, ...
                ExperimentalValues = 0.5, ...
                StandardDeviations = 0.1);
            objective = openmebius.mfa.SteadyStateObjective( ...
                Problem = problem, ...
                RightHandSide = zeros(2, 1), ...
                Model = model, ...
                SubstrateEMUs = {eye(2), 2 * eye(2)}, ...
                ExperimentalMDV = [0.3, 0.4; 0.8, 1.6], ...
                FragmentMask = [true; false], ...
                EffluxPenalty = penalty, ...
                MeasurementStandardDeviation = 0.1);

            rss = objective.evaluate([0.2; 0.7]);

            testCase.verifyEqual(rss, 5, 'AbsTol', 1e-12);

        end

        function predictsConcatenatedMDV(testCase)

            objective = openmebius.mfa.SteadyStateObjective( ...
                Problem = SteadyStateObjectiveTest.createProblem(), ...
                RightHandSide = zeros(2, 1), ...
                Model = helpers.SteadyStateModelStub(), ...
                SubstrateEMUs = {eye(2), 2 * eye(2)}, ...
                ExperimentalMDV = zeros(2, 2), ...
                FragmentMask = true(2, 1));

            testCase.verifyEqual( ...
                objective.predictFlux([0.2; 0.7]), ...
                [0.2; 0.7; 0.4; 1.4], ...
                'AbsTol', 1e-12);

        end

        function rejectsExperimentCountMismatch(testCase)

            testCase.verifyError( ...
                @() openmebius.mfa.SteadyStateObjective( ...
                Problem = SteadyStateObjectiveTest.createProblem(), ...
                RightHandSide = zeros(2, 1), ...
                Model = helpers.SteadyStateModelStub(), ...
                SubstrateEMUs = {eye(2), eye(2)}, ...
                ExperimentalMDV = zeros(2, 1), ...
                FragmentMask = true(2, 1)), ...
                "OpenMebius2:SteadyStateObjective:ExperimentCountMismatch");

        end

    end

    methods (Static, Access = private)

        function problem = createProblem()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = zeros(2, 1), ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = ones(2, 1), ...
                IndependentMask = true(2, 1), ...
                BoundaryReactionMask = true(2, 1));

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
