classdef SteadyStateSolverTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addSourcePath(~)

            addpath(SteadyStateSolverTest.sourcePath());

        end

    end

    methods (Test)

        function solvesConstrainedObjective(testCase)

            problem = SteadyStateSolverTest.createProblem();
            solver = openmebius.mfa.SteadyStateSolver();
            target = [0.25; 0.75];

            result = solver.solve( ...
                problem, ...
                zeros(2, 1), ...
                @(x) sum((x - target) .^ 2), ...
                SteadyStateSolverTest.solverOptions());

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyEqual( ...
                result.IndependentValues, target, 'AbsTol', 1e-5);
            testCase.verifyEqual(result.Flux, target, 'AbsTol', 1e-5);
            testCase.verifyLessThan(result.ObjectiveValue, 1e-8);
            testCase.verifyEqual( ...
                result.Output.fminconFiniteDifferenceStepSizeSearch ...
                .candidates, ...
                1e-6);

        end

        function enforcesConfiguredFluxBounds(testCase)

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = zeros(2, 1), ...
                LowerBounds = [-2; 0.25], ...
                UpperBounds = [-1; 0.75], ...
                IndependentMask = true(2, 1), ...
                BoundaryReactionMask = true(2, 1));
            solver = openmebius.mfa.SteadyStateSolver();

            result = solver.solve( ...
                problem, ...
                [-1.5; 0.5], ...
                @(x) sum((x - [-3; 2]) .^ 2), ...
                SteadyStateSolverTest.solverOptions());

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyEqual( ...
                result.Flux, [-2; 0.75], 'AbsTol', 1e-5);
            testCase.verifyGreaterThanOrEqual( ...
                result.Flux, problem.LowerBounds - 1e-6);
            testCase.verifyLessThanOrEqual( ...
                result.Flux, problem.UpperBounds + 1e-6);

        end

        function enforcesNonnegativeFlux(testCase)

            problem = SteadyStateSolverTest.createProblem();
            solver = openmebius.mfa.SteadyStateSolver();

            result = solver.solve( ...
                problem, ...
                zeros(2, 1), ...
                @(x) sum((x + 1) .^ 2), ...
                SteadyStateSolverTest.solverOptions());

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyGreaterThanOrEqual( ...
                result.Flux, -1e-7 * ones(2, 1));

        end

        function enforcesLinearEquality(testCase)

            problem = SteadyStateSolverTest.createProblem();
            solver = openmebius.mfa.SteadyStateSolver();

            result = solver.solve( ...
                problem, ...
                zeros(2, 1), ...
                @(x) sum((x - [0.25; 0.75]) .^ 2), ...
                SteadyStateSolverTest.solverOptions(), ...
                LinearEqualityMatrix = [1, -1], ...
                LinearEqualityRightHandSide = 0);

            testCase.verifyFalse(result.IsError, result.ErrorMessage);
            testCase.verifyEqual( ...
                result.IndependentValues(1), ...
                result.IndependentValues(2), ...
                'AbsTol', 1e-6);
            testCase.verifyLessThanOrEqual( ...
                result.Output ...
                .fminconFiniteDifferenceStepSizeSearch ...
                .constraintViolations, ...
                1e-6);

        end

        function searchesConfiguredFiniteDifferenceSteps(testCase)

            problem = SteadyStateSolverTest.createProblem();
            solver = openmebius.mfa.SteadyStateSolver();
            options = openmebius.mfa.SteadyStateOptions( ...
                StepSizeSearchEnabled = true, ...
                IncludeConfiguredStep = false, ...
                MaxStepSizeCandidates = 2, ...
                StepSizeCandidates = [1e-4; 1e-6], ...
                MaxIterations = 100);

            result = solver.solve( ...
                problem, ...
                zeros(2, 1), ...
                @(x) sum((x - 0.5) .^ 2), ...
                options);
            search = result.Output.fminconFiniteDifferenceStepSizeSearch;

            testCase.verifyEqual(search.candidates, [1e-4; 1e-6]);
            testCase.verifySize(search.objectives, [2, 1]);
            testCase.verifyGreaterThanOrEqual(search.bestIndex, 1);
            testCase.verifyLessThanOrEqual(search.bestIndex, 2);

        end

        function convertsOptimizerExceptionToResult(testCase)

            problem = SteadyStateSolverTest.createProblem();
            solver = openmebius.mfa.SteadyStateSolver();

            result = solver.solve( ...
                problem, ...
                zeros(2, 1), ...
                @(x) SteadyStateSolverTest.throwObjectiveError(x), ...
                SteadyStateSolverTest.solverOptions());

            testCase.verifyTrue(result.IsError);
            testCase.verifyEqual(result.ExitFlag, -102);
            testCase.verifyEqual(result.ObjectiveValue, inf);
            testCase.verifyTrue(result.Output.fminconExecutionFailed);

        end

    end

    methods (Static, Access = private)

        function problem = createProblem()

            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = eye(2), ...
                RightHandSide = zeros(2, 1), ...
                LowerBounds = zeros(2, 1), ...
                UpperBounds = ones(2, 1), ...
                IndependentMask = true(2, 1), ...
                BoundaryReactionMask = true(2, 1));

        end

        function options = solverOptions()

            options = openmebius.mfa.SteadyStateOptions( ...
                MaxIterations = 100, ...
                StepSizeSearchEnabled = false);

        end

        function value = throwObjectiveError(~)

            error( ...
                "OpenMebius2:Test:ObjectiveFailure", ...
                "Objective failure.");
            value = NaN;

        end

        function path = sourcePath()

            path = fullfile( ...
                fileparts(fileparts(mfilename('fullpath'))), ...
                'src');

        end

    end

end
