function testFiles = testProfileFiles(profile)
%TESTPROFILEFILES Return the disjoint set of tests assigned to a profile.

arguments
    profile (1, 1) string {mustBeMember( ...
        profile, ["fast", "domain", "numerical", "integration", "all"])}
end

testDirectory = string(fileparts(mfilename("fullpath")));
root = string(fileparts(testDirectory));
testFiles = discoverTests(testDirectory);

appTests = [ ...
    fullfile(root, "src", "OpenMebius2Test.m"); ...
    fullfile(root, "src", "OpenMebius2IntegratedTest.m")];
testFiles = sort(unique([testFiles; appTests(isfile(appTests))]));
fileNames = namesOf(testFiles);

requiredFastTests = [ ...
    "CIFastTestSuiteTest.m"; ...
    "MainAppCompositionRootTest.m"; ...
    "MainApplicationSessionTest.m"; ...
    "OpenMebius2SourceSyncTest.m"; ...
    "TestProfileCatalogTest.m"];
assertTestsExist(fileNames, requiredFastTests, "fast");
fastMask = endsWith(fileNames, "BoundaryTest.m") | ...
    endsWith(fileNames, "ContextTest.m") | ...
    ismember(fileNames, requiredFastTests);

integrationMask = contains(fileNames, "IntegrationTest.m") | ...
    contains(fileNames, "IntegratedTest.m") | ...
    contains(fileNames, "WorkflowSmokeTest.m") | ...
    fileNames == "OpenMebius2Test.m";
assertTestsExist( ...
    fileNames, ...
    ["OpenMebius2Test.m"; "OpenMebius2IntegratedTest.m"; ...
    "OpenMebius2WorkflowSmokeTest.m"], ...
    "integration");

numericalPrefixes = [ ...
    "ConfidenceInterval"; ...
    "Efflux"; ...
    "EMU"; ...
    "ExperimentMDV"; ...
    "Flux"; ...
    "InitialFlux"; ...
    "InitialPoint"; ...
    "Instationary"; ...
    "MFA"; ...
    "MonteCarlo"; ...
    "NextFlux"; ...
    "NextLabel"; ...
    "ReversibleFlux"; ...
    "SteadyState"; ...
    "SubstrateEMU"];
numericalMask = false(size(testFiles));

for prefix = numericalPrefixes'
    numericalMask = numericalMask | startsWith(fileNames, prefix);
end

fastMask = fastMask & ~integrationMask;
numericalMask = numericalMask & ~fastMask & ~integrationMask;
domainMask = ~(fastMask | numericalMask | integrationMask);

switch profile
    case "fast"
        testFiles = testFiles(fastMask);
    case "domain"
        testFiles = testFiles(domainMask);
    case "numerical"
        testFiles = testFiles(numericalMask);
    case "integration"
        testFiles = testFiles(integrationMask);
    case "all"
        testFiles = [ ...
            testFiles(fastMask); ...
            testFiles(domainMask); ...
            testFiles(numericalMask); ...
            testFiles(integrationMask)];
end

if isempty(testFiles)
    error( ...
        "OpenMebius2:Test:EmptyProfile", ...
        "No tests were selected for profile '%s'.", ...
        profile);
end

end

function assertTestsExist(fileNames, requiredTests, profile)

missingTests = requiredTests(~ismember(requiredTests, fileNames));

if ~isempty(missingTests)
    error( ...
        "OpenMebius2:Test:MissingProfileTest", ...
        "Required %s profile tests are missing: %s", ...
        profile, strjoin(missingTests, ", "));
end

end

function testFiles = discoverTests(testDirectory)

matches = dir(fullfile(testDirectory, "*Test.m"));
testFiles = strings(numel(matches), 1);

for matchIndex = 1:numel(matches)
    testFiles(matchIndex) = fullfile( ...
        string(matches(matchIndex).folder), ...
        string(matches(matchIndex).name));
end

end

function fileNames = namesOf(testFiles)

fileNames = strings(size(testFiles));

for fileIndex = 1:numel(testFiles)
    [~, name, extension] = fileparts(testFiles(fileIndex));
    fileNames(fileIndex) = name + extension;
end

end
