classdef ViewComparisonAppTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));
            addpath(fullfile(root, "tests"));

        end

    end

    methods (Test)

        function opensWithOnlyRequestedBatchSelected(testCase)

            [presenter, rangeService, catalog] = ...
                ViewComparisonAppTest.presenter();
            context = openmebius.presentation.result ...
                .ViewComparisonContext( ...
                Presenter = presenter, ...
                InitialCatalog = catalog, ...
                InitialBatchIDs = "batch-000000000002");
            app = ViewComparison_exported(context);
            cleanup = onCleanup( ...
                @() ViewComparisonAppTest.deleteIfValid(app));

            testCase.verifyEqual(app.BatchUITable.Selection, 2);
            testCase.verifyEqual( ...
                string(app.BatchUITable.Data.ID), ...
                ["batch-0000"; "batch-0000"]);
            testCase.verifyEqual( ...
                rangeService.BatchIDs, "batch-000000000002");
            testCase.verifyEqual(height(app.ColorUITable.Data), 1);
            testCase.verifyEqual( ...
                string(app.ColorUITable.Data.BatchID), "batch-0000");
            testCase.verifyEqual( ...
                string(app.ColorUITable.Data.Name), "Second batch");

            legendDummy = findobj( ...
                app.UIAxes, 'Tag', 'RangePlotLegendDummy_0001');
            testCase.verifyEqual( ...
                string(legendDummy.DisplayName), "Second batch");

            data = app.ColorUITable.Data;
            data.Name(1) = "Custom legend";
            app.ColorUITable.Data = data;
            callback = app.ColorUITable.CellEditCallback;
            callback([], struct( ...
                'Indices', [1 2], ...
                'PreviousData', "Second batch"));
            legendDummy = findobj( ...
                app.UIAxes, 'Tag', 'RangePlotLegendDummy_0001');
            testCase.verifyEqual( ...
                string(legendDummy.DisplayName), "Custom legend");

        end

        function opensWithoutSelectionWhenNoBatchWasSelected(testCase)

            [presenter, rangeService, catalog] = ...
                ViewComparisonAppTest.presenter();
            context = openmebius.presentation.result ...
                .ViewComparisonContext( ...
                Presenter = presenter, ...
                InitialCatalog = catalog);
            app = ViewComparison_exported(context);
            cleanup = onCleanup( ...
                @() ViewComparisonAppTest.deleteIfValid(app));

            testCase.verifyEmpty(app.BatchUITable.Selection);
            testCase.verifyFalse(rangeService.Called);
            testCase.verifyEmpty(app.ColorUITable.Data);

        end

        function displaysPlotOptionsInDedicatedPanel(testCase)

            [presenter, ~, catalog] = ViewComparisonAppTest.presenter();
            context = openmebius.presentation.result ...
                .ViewComparisonContext( ...
                Presenter = presenter, ...
                InitialCatalog = catalog);
            app = ViewComparison_exported(context);
            cleanup = onCleanup( ...
                @() ViewComparisonAppTest.deleteIfValid(app));

            testCase.verifyEqual(numel(app.GridLayout2.Children), 2);
            testCase.verifyEqual(numel(app.GridLayout5.Children), 5);
            testCase.verifyTrue( ...
                app.UIfontDropDown.Parent == app.GridLayout6);
            testCase.verifyTrue( ...
                app.FontsizeEditField.Parent == app.GridLayout7);
            testCase.verifyTrue( ...
                app.BestfitStyleDropDown.Parent == app.GridLayout8);
            testCase.verifyTrue( ...
                app.BestfitColorEditField.Parent == app.GridLayout9);
            testCase.verifyTrue( ...
                app.BestfitSizeEditField.Parent == app.GridLayout10);
            testCase.verifyEqual( ...
                app.BestfitStyleDropDown.Items, ...
                {'triangle', 'diamond', 'none'});
            testCase.verifyEqual(app.BestfitStyleDropDown.Value, ...
                'triangle');
            testCase.verifyEqual(app.BestfitColorEditField.Value, ...
                'series');
            testCase.verifyEqual(app.FontsizeEditField.Limits, [6 72]);
            testCase.verifyEqual(app.FontsizeEditField.Value, 10);
            testCase.verifyEqual(app.BestfitSizeEditField.Limits, [1 40]);
            testCase.verifyEqual(app.BestfitSizeEditField.Value, 8);
            testCase.verifyNotEmpty( ...
                app.UIfontDropDown.ValueChangedFcn);
            testCase.verifyNotEmpty( ...
                app.BestfitColorEditField.ValueChangedFcn);

        end

    end

    methods (Static, Access = private)

        function [presenter, rangeService, catalogViewModel] = presenter()

            catalogService = helpers.ResultComparisonCatalogServiceStub();
            catalogService.Catalog = openmebius.application.result ...
                .ResultComparisonCatalog( ...
                BatchIDs = [ ...
                "batch-000000000001"; "batch-000000000002"], ...
                BatchNames = ["First batch"; "Second batch"], ...
                ExperimentNames = ["exp-a"; "exp-b"], ...
                Contents = ["CI"; "FVA"]);
            lower = array2table(0, ...
                'VariableNames', {'Second_batch'}, ...
                'RowNames', {'r1'});
            upper = array2table(2, ...
                'VariableNames', {'Second_batch'}, ...
                'RowNames', {'r1'});
            bestFits = array2table(1, ...
                'VariableNames', {'Second_batch'}, ...
                'RowNames', {'r1'});
            rangeService = helpers.ResultRangePlotServiceStub();
            rangeService.Result = openmebius.application.result ...
                .ResultRangePlotResult( ...
                UpperBounds = upper, ...
                LowerBounds = lower, ...
                BestFits = bestFits, ...
                ReactionNames = "r1 : A <=> B");
            presenter = openmebius.presentation.result ...
                .ViewComparisonPresenter( ...
                1, ...
                2, ...
                CatalogService = catalogService, ...
                RangePlotService = rangeService);
            catalogViewModel = presenter.presentCatalog();

        end

        function deleteIfValid(app)

            if ~isempty(app) && isvalid(app)
                delete(app);
            end

        end

    end

end
