classdef ViewComparisonPresenterTest < matlab.unittest.TestCase

    methods (TestMethodSetup)

        function addPaths(~)

            root = fileparts(fileparts(mfilename("fullpath")));
            addpath(fullfile(root, "src"));
            addpath(fullfile(root, "tests"));

        end

    end

    methods (Test)

        function presentsCatalogAndSelectedRanges(testCase)

            catalogService = helpers.ResultComparisonCatalogServiceStub();
            catalogService.Catalog = openmebius.application.result ...
                .ResultComparisonCatalog( ...
                BatchIDs = ["batch-a"; "batch-b"], ...
                BatchNames = ["A"; "B"], ...
                ExperimentNames = ["exp-a"; "exp-b"], ...
                Contents = ["FVA"; "CI"]);
            lower = array2table( ...
                [0 1; 2 3], ...
                'VariableNames', {'A', 'B'}, ...
                'RowNames', {'r1', 'r2'});
            upper = array2table( ...
                [1 2; 3 4], ...
                'VariableNames', {'A', 'B'}, ...
                'RowNames', {'r1', 'r2'});
            bestFits = array2table( ...
                [0.5 1.5; 2.5 3.5], ...
                'VariableNames', {'A', 'B'}, ...
                'RowNames', {'r1', 'r2'});
            rangeService = helpers.ResultRangePlotServiceStub();
            rangeService.Result = openmebius.application.result ...
                .ResultRangePlotResult( ...
                UpperBounds = upper, ...
                LowerBounds = lower, ...
                BestFits = bestFits, ...
                ReactionNames = ["r1 : First"; "r2"]);
            presenter = openmebius.presentation.result ...
                .ViewComparisonPresenter( ...
                1, ...
                2, ...
                CatalogService = catalogService, ...
                RangePlotService = rangeService);

            catalogViewModel = presenter.presentCatalog();
            plotViewModel = presenter.presentSelection( ...
                ["batch-b"; "batch-a"]);

            testCase.verifyTrue(catalogViewModel.IsAvailable);
            testCase.verifyEqual(catalogViewModel.BatchNames, ["A"; "B"]);
            testCase.verifyEqual(catalogViewModel.Contents, ...
                ["FVA"; "CI"]);
            testCase.verifyTrue(plotViewModel.IsAvailable);
            testCase.verifyEqual(rangeService.BatchNames, ["B"; "A"]);
            testCase.verifyEqual(plotViewModel.ReactionIDs, ["r1"; "r2"]);
            testCase.verifyEqual(plotViewModel.ReactionNames, ["First"; ""]);
            testCase.verifyEqual(plotViewModel.ReactionLabels, ...
                ["r1 : First"; "r2"]);

        end

        function reportsEmptyCatalog(testCase)

            catalogService = helpers.ResultComparisonCatalogServiceStub();
            presenter = openmebius.presentation.result ...
                .ViewComparisonPresenter( ...
                1, 2, CatalogService = catalogService);

            viewModel = presenter.presentCatalog();

            testCase.verifyFalse(viewModel.IsAvailable);
            testCase.verifyNumElements(viewModel.Notifications, 1);

        end

    end

end
