classdef WorkspaceDecompositionBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function modelWorkspaceUsesDedicatedComponents(testCase)
            source = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+application", "+model", "ModelWorkspace.m");
            WorkspaceDecompositionBoundaryTest.verifyContainsAll( ...
                testCase, source, [ ...
                    "ModelReactionParser"; ...
                    "ModelWorkspaceValidator"; ...
                    "ModelAggregate"]);
        end

        function experimentWorkspaceUsesCollectionAndResolver(testCase)
            source = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+application", "+experiment", "ExperimentWorkspace.m");
            WorkspaceDecompositionBoundaryTest.verifyContainsAll( ...
                testCase, source, [ ...
                    "ExperimentCollection"; ...
                    "ExperimentModelResolver"; ...
                    "ExperimentComparisonBuilder"; ...
                    "ExperimentEditMapper"; ...
                    "ExperimentEditValidator"; ...
                    "ExperimentTableAssembler"]);
        end

        function resultWorkspaceUsesQueryServices(testCase)
            source = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+application", "+result", "ResultWorkspace.m");
            WorkspaceDecompositionBoundaryTest.verifyContainsAll( ...
                testCase, source, [ ...
                    "ResultQueryService"; ...
                    "ResultTableBuilder"]);
            testCase.verifyFalse(contains( ...
                source, "obj.Hdf5ResultRepository"));

            query = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+application", "+result", "ResultQueryService.m");
            WorkspaceDecompositionBoundaryTest.verifyContainsAll( ...
                testCase, query, [ ...
                    "readConfidenceInterval"; ...
                    "readNextLabelSuggestion"]);

            controller = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+application", "+result", ...
                "ResultOperationController.m");
            testCase.verifyTrue(contains( ...
                controller, "ResultRangePlotService"));
        end

        function batchAndRawImportUseOfficialBoundaries(testCase)
            batch = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+application", "+batch", "BatchSession.m");
            WorkspaceDecompositionBoundaryTest.verifyContainsAll( ...
                testCase, batch, [ ...
                    "BatchCollection"; ...
                    "BatchConfigEditor"; ...
                    "BatchExecutionCoordinator"; ...
                    "BatchJsonRepository"]);

            raw = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+infrastructure", "+experiment", ...
                "RawMSDataRepository.m");
            WorkspaceDecompositionBoundaryTest.verifyContainsAll( ...
                testCase, raw, [ ...
                    "ShimadzuAsciiParser"; ...
                    "RawMSFragmentMapper"; ...
                    "RawMSWorkbookExporter"]);
        end

        function projectLoadingUsesRepositoryAndMigration(testCase)
            source = WorkspaceDecompositionBoundaryTest.readSource( ...
                "+application", "+project", ...
                "ProjectOperationController.m");
            WorkspaceDecompositionBoundaryTest.verifyContainsAll( ...
                testCase, source, [ ...
                    "ProjectArtifactRepository"; ...
                    "ProjectMigrationService"]);
            testCase.verifyFalse(contains(source, "LegacyProject"));
        end

    end

    methods (Static, Access = private)

        function source = readSource(varargin)
            root = fileparts(fileparts(mfilename("fullpath")));
            path = fullfile(root, "src", "+openmebius", varargin{:});
            source = string(fileread(path));
        end

        function verifyContainsAll(testCase, source, values)
            for value = values'
                testCase.verifyTrue(contains(source, value));
            end
        end

    end

end
