classdef WorkspaceTableBoundaryTest < matlab.unittest.TestCase

    methods (Test)

        function mainAppDoesNotReadWorkspaceTablesDirectly(testCase)

            root = fileparts(fileparts(mfilename("fullpath")));
            source = string(fileread( ...
                fullfile(root, "src", "OpenMebius2_exported.m")));
            directCalls = [ ...
                "app.model.getModelTableGUI", ...
                "app.model.getMSTable", ...
                "app.model.getAtomTable", ...
                "app.model.getBiomassTable", ...
                "app.model.getInvalidModelRowIdx", ...
                "app.model.getInvalidMSRowIdx", ...
                "app.model.getInvalidAtomRowIdx", ...
                "getInfoTable(app.exp)", ...
                "app.exp.getTracerTable", ...
                "app.exp.getUptakeTable"];

            for call = directCalls
                testCase.verifyFalse(contains(source, call));
            end

            testCase.verifyTrue( ...
                contains(source, ".presentWorkspaceTables(app.model)"));
            testCase.verifyTrue( ...
                contains(source, ".presentWorkspaceTables(app.exp)"));
            testCase.verifyTrue( ...
                contains(source, "renderWorkspaceTable"));

        end

    end % methods (Test)

end % classdef
