classdef ConfidenceIntervalSolverStub < handle

    properties (SetAccess = private)
        CallCount (1, 1) double = 0
    end

    methods

        function result = solve( ...
                obj, experimentalMDV, fluxCount, ~, ...
                iterationFunction, ~, varargin)

            obj.CallCount = obj.CallCount + 1;
            iterationFunction(experimentalMDV);

            for index = 1:numel(varargin) - 1
                name = varargin{index};

                if (ischar(name) || isstring(name)) && ...
                        isscalar(string(name)) && ...
                        string(name) == "ProgressReporter"
                    varargin{index + 1}(1, 1);
                    break
                end

            end

            result = ...
                openmebius.mfa.MonteCarloConfidenceIntervalResult( ...
                LowerBounds = zeros(fluxCount, 1), ...
                UpperBounds = ones(fluxCount, 1), ...
                PerturbedMDVs = reshape( ...
                experimentalMDV, ...
                size(experimentalMDV, 1), ...
                size(experimentalMDV, 2), ...
                1), ...
                Fluxes = zeros(fluxCount, 1), ...
                IterationCount = 1, ...
                ElapsedTime = 2);

        end

    end

end
