classdef ConfidenceIntervalSolverStub < handle

    properties (SetAccess = private)
        CallCount (1, 1) double = 0
    end

    methods

        function result = solve( ...
                obj, experimentalMDV, fluxCount, ~, ...
                iterationFunction, ~, varargin)

            obj.CallCount = obj.CallCount + 1;
            iterationFunction(experimentalMDV);
            result = ...
                openmebius.mfa.MonteCarloConfidenceIntervalResult( ...
                LowerBounds = zeros(fluxCount, 1), ...
                UpperBounds = ones(fluxCount, 1), ...
                PerturbedMDVs = reshape( ...
                experimentalMDV, ...
                size(experimentalMDV, 1), ...
                size(experimentalMDV, 2), ...
                1), ...
                Fluxes = zeros(fluxCount, 1), ...
                IterationCount = 1, ...
                ElapsedTime = 2);

        end

    end

end
