classdef GridSearchConfidenceIntervalSolverStub < handle

    properties (SetAccess = private)
        CallCount (1, 1) double = 0
        LastBaseRightHandSide double = []
        LastEvaluationResult = []
        LastEqualityMatrix double = zeros(0, 0)
        LastEqualityRightHandSide double = zeros(0, 1)
        LastInitialIndependentValues double = []
    end

    methods

        function result = solve( ...
                obj, problem, bestFlux, baseRightHandSide, ~, ...
                evaluationFunction, ~, varargin)

            obj.CallCount = obj.CallCount + 1;
            obj.LastBaseRightHandSide = baseRightHandSide;
            obj.LastInitialIndependentValues = ...
                problem.extractIndependentValues(baseRightHandSide);
            obj.LastEqualityMatrix = ...
                ones(1, numel(obj.LastInitialIndependentValues));
            obj.LastEqualityRightHandSide = ...
                obj.LastEqualityMatrix * ...
                obj.LastInitialIndependentValues;
            obj.LastEvaluationResult = evaluationFunction( ...
                obj.LastEqualityMatrix, ...
                obj.LastEqualityRightHandSide, ...
                obj.LastInitialIndependentValues);

            fluxCount = size(bestFlux, 1);
            profile = openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = (1:fluxCount).', ...
                FixedFluxValues = zeros(fluxCount, 1, 1), ...
                MinimumSumOfSquares = zeros(fluxCount, 1, 1));
            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalResult( ...
                LowerBounds = zeros(fluxCount, 1), ...
                UpperBounds = ones(fluxCount, 1), ...
                ProfileData = profile, ...
                ElapsedTime = 3);

        end

    end

end
