classdef ReportResultDataStub < handle

    properties
        isError (1, 1) logical = false
    end

    methods

        function value = getFluxOverView(~, resultID)

            value = table( ...
                resultID, ...
                "Reaction 1", ...
                12.5, ...
                'VariableNames', ["ResultID", "Reaction", "Flux"], ...
                'RowNames', {"R1"});

        end

        function value = getFluxDetailed(~, resultID)

            value = table( ...
                resultID, ...
                "Ala159", ...
                "M+0", ...
                0.8, ...
                0.79, ...
                'VariableNames', ...
                ["ResultID", "Fragment", "Isotopomer", ...
                 "Measured", "Estimated"]);

        end

    end

end
