classdef ReportResultDataStub < handle

    properties
        isError (1, 1) logical = false
    end

    methods

        function value = getFluxOverView(~, resultID)

            value = table( ...
                resultID, ...
                "Reaction 1", ...
                12.5, ...
                'VariableNames', ["ResultID", "Reaction", "Flux"], ...
                'RowNames', {'R1'});

        end

        function value = getFluxDetailed(~, resultID)

            value = table( ...
                resultID, ...
                "Ala159", ...
                "M+0", ...
                0.8, ...
                0.79, ...
                'VariableNames', ...
                ["ResultID", "Fragment", "Isotopomer", ...
                "Measured", "Estimated"]);

        end

        function value = getMDV(obj, resultID)

            value = obj.getFluxDetailed(resultID);

        end

        function value = getMDVSummary(~, ~)

            value = table( ...
                "Ala159", ...
                -0.01, ...
                0.01, ...
                2, ...
                'VariableNames', [ ...
                "Metabolite", ...
                "E[MDV_e] - E[MDV_s]", ...
                "W_1(MDV_e, MDV_s)", ...
                "χ^2"]);

        end

    end

end
