classdef ReportExperimentsStub < handle

    properties
        isError (1, 1) logical = false
    end

    methods

        function value = getExpList(~)

            value = "experiment-a";

        end

        function value = getInfoTable(~)

            value = table( ...
                "experiment-a", ...
                "Test experiment", ...
                'VariableNames', ["Experiment", "Description"]);

        end

        function value = getTracerTable(~)

            value = table( ...
                "experiment-a", ...
                "Glucose", ...
                "U-13C", ...
                1, ...
                'VariableNames', ...
                ["Experiment", "Substrate", "Label", "Ratio"]);

        end

        function value = getUptakeTable(~)

            value = table( ...
                "experiment-a", ...
                "Glucose", ...
                10, ...
                'VariableNames', ["Experiment", "Metabolite", "Flux"]);

        end

        function value = getMSTable(~, experimentName)

            value = table( ...
                experimentName, ...
                "Ala159", ...
                0.8, ...
                'VariableNames', ["Experiment", "Fragment", "M0"]);

        end

        function value = getMSNormalizedTable(~, experimentName)

            value = table( ...
                experimentName, ...
                "Ala159", ...
                1, ...
                'VariableNames', ["Experiment", "Fragment", "Total"]);

        end

        function value = getMDVTable(~, experimentName)

            value = table( ...
                experimentName, ...
                "Ala159", ...
                "M+0", ...
                0.8, ...
                'VariableNames', ...
                ["Experiment", "Fragment", "Isotopomer", "MDV"]);

        end

    end

end
