classdef EMUNetworkSnapshot
    % EMUNETWORKSNAPSHOT
    % Serializable state required to restore a constructed EMU network.

    properties (SetAccess = private)
        TableEMU table = table()
        TableEMUReaction table = table()
        TableEMUSizeInfo table = table()
        SearchedProduct = {}
        GlobalAn = []
        GlobalAnEMUName = {}
        GlobalAnEMUNameMetabolite = {}
        GlobalAnList = []
        GlobalBn = []
        GlobalBnEMUName = {}
        GlobalBnEMUNameMetabolite = {}
        GlobalBnList = []
        GlobalCn = []
        GlobalCnDiag = []
        GlobalXn = []
        GlobalXnList = []
        GlobalYn = []
        GlobalYnList = []
        GlobalMDVInfo = []
        GlobalMDVList = []
        GlobalMDVSize = 0
    end

    methods

        function obj = EMUNetworkSnapshot(payload)

            arguments
                payload (1, 1) struct
            end

            requiredFields = [ ...
                "tableEMU", ...
                "tableEMUReaction", ...
                "tableEMUSizeInfo" ...
                ];
            missingFields = requiredFields(~isfield(payload, requiredFields));

            if ~isempty(missingFields)
                error( ...
                    "OpenMebius2:EMUNetworkSnapshot:MissingField", ...
                    "The EMU cache is missing required fields: %s", ...
                    strjoin(missingFields, ", "));
            end

            obj.TableEMU = payload.tableEMU;
            obj.TableEMUReaction = payload.tableEMUReaction;
            obj.TableEMUSizeInfo = payload.tableEMUSizeInfo;
            obj.SearchedProduct = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "searchedProduct", {});
            obj.GlobalAn = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalAn", []);
            obj.GlobalAnEMUName = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalAnEMUName", {});
            obj.GlobalAnEMUNameMetabolite = ...
                openmebius.domain.model.EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalAnEMUNameMetabolite", {});
            obj.GlobalAnList = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalAnList", []);
            obj.GlobalBn = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalBn", []);
            obj.GlobalBnEMUName = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalBnEMUName", {});
            obj.GlobalBnEMUNameMetabolite = ...
                openmebius.domain.model.EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalBnEMUNameMetabolite", {});
            obj.GlobalBnList = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalBnList", []);
            obj.GlobalCn = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalCn", []);
            obj.GlobalCnDiag = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalCnDiag", []);
            obj.GlobalXn = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalXn", []);
            obj.GlobalXnList = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalXnList", []);
            obj.GlobalYn = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalYn", []);
            obj.GlobalYnList = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalYnList", []);
            obj.GlobalMDVInfo = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalMDVInfo", []);
            obj.GlobalMDVList = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalMDVList", []);
            obj.GlobalMDVSize = openmebius.domain.model ...
                .EMUNetworkSnapshot.valueOrDefault( ...
                payload, "globalMDVSize", 0);

        end % constructor

        function payload = toStruct(obj)

            payload = struct( ...
                "tableEMU", obj.TableEMU, ...
                "tableEMUReaction", obj.TableEMUReaction, ...
                "tableEMUSizeInfo", obj.TableEMUSizeInfo, ...
                "searchedProduct", {obj.SearchedProduct}, ...
                "globalAn", obj.GlobalAn, ...
                "globalAnEMUName", {obj.GlobalAnEMUName}, ...
                "globalAnEMUNameMetabolite", ...
                {obj.GlobalAnEMUNameMetabolite}, ...
                "globalAnList", obj.GlobalAnList, ...
                "globalBn", obj.GlobalBn, ...
                "globalBnEMUName", {obj.GlobalBnEMUName}, ...
                "globalBnEMUNameMetabolite", ...
                {obj.GlobalBnEMUNameMetabolite}, ...
                "globalBnList", obj.GlobalBnList, ...
                "globalCn", obj.GlobalCn, ...
                "globalCnDiag", obj.GlobalCnDiag, ...
                "globalXn", obj.GlobalXn, ...
                "globalXnList", obj.GlobalXnList, ...
                "globalYn", obj.GlobalYn, ...
                "globalYnList", obj.GlobalYnList, ...
                "globalMDVInfo", obj.GlobalMDVInfo, ...
                "globalMDVList", obj.GlobalMDVList, ...
                "globalMDVSize", obj.GlobalMDVSize);

        end % toStruct

    end % methods

    methods (Static, Access = private)

        function value = valueOrDefault(payload, fieldName, defaultValue)

            if isfield(payload, fieldName)
                value = payload.(fieldName);
            else
                value = defaultValue;
            end

        end % valueOrDefault

    end % methods (Static, Access = private)

end % classdef
