classdef AnalysisRunRepository < handle
    % ANALYSISRUNREPOSITORY
    % Coordinates reproducibility metadata across result artifacts.

    properties (Access = private)
        Hdf5ResultRepository
        ResultManifestRepository
    end

    methods

        function obj = AnalysisRunRepository(options)

            arguments
                options.Hdf5ResultRepository = ...
                    openmebius.infrastructure.result.Hdf5ResultRepository()
                options.ResultManifestRepository = ...
                    openmebius.infrastructure.result.ResultManifestRepository()
            end

            obj.Hdf5ResultRepository = options.Hdf5ResultRepository;
            obj.ResultManifestRepository = options.ResultManifestRepository;

        end % constructor

        function [isSuccess, msg] = writeStarted( ...
                obj, resultLocation, resultFile, metadata)

            [isSuccess, msg] = ...
                obj.Hdf5ResultRepository.writeAnalysisMetadata( ...
                resultFile, ...
                metadata);

            if ~isSuccess
                msg = "Failed to write analysis metadata: " + msg;
                return
            end

            [isSuccess, msg] = ...
                obj.ResultManifestRepository.writeStarted( ...
                resultLocation, ...
                metadata);

            if ~isSuccess
                msg = "Failed to write result manifest: " + msg;
            end

        end % writeStarted

        function errors = writeCompleted( ...
                obj, ...
                resultLocation, ...
                resultFile, ...
                metadata, ...
                finishedAtUtc, ...
                isError, ...
                isCanceled)

            errors = strings(0, 1);
            [hdf5Success, hdf5Message] = ...
                obj.Hdf5ResultRepository.writeRunCompletion( ...
                resultFile, ...
                finishedAtUtc, ...
                isError, ...
                isCanceled);
            effectiveIsError = isError || ~hdf5Success;

            if ~hdf5Success
                errors(end + 1, 1) = ...
                    "Failed to finalize analysis metadata: " + hdf5Message;
            end

            [manifestSuccess, manifestMessage] = ...
                obj.ResultManifestRepository.writeCompleted( ...
                resultLocation, ...
                metadata, ...
                finishedAtUtc, ...
                effectiveIsError, ...
                isCanceled);

            if ~manifestSuccess
                errors(end + 1, 1) = ...
                    "Failed to finalize result manifest: " + manifestMessage;
                obj.Hdf5ResultRepository.writeRunCompletion( ...
                    resultFile, ...
                    finishedAtUtc, ...
                    true, ...
                    isCanceled);
            end

        end % writeCompleted

    end % methods

end % classdef
