classdef Hdf5ResultRepository < handle
    % HDF5RESULTREPOSITORY
    % Writes flux analysis result datasets to HDF5.

    methods

        function assertResultDirectory(~, resultLocation)

            arguments
                ~
                resultLocation openmebius.domain.result.ResultLocation
            end

            if ~resultLocation.directoryExists()
                error( ...
                    "OpenMebius2:Hdf5ResultRepository:DirectoryNotFound", ...
                    "Result directory does not exist: %s", ...
                    resultLocation.Directory);
            end

        end % assertResultDirectory

        function [isSuccess, msg] = writeDataset(~, pathFile, pathData, data, options)

            arguments
                ~
                pathFile (1, 1) string
                pathData (1, 1) string
                data
                options.DataType (1, 1) string = "double"
            end

            [isSuccess, msg] = openmebius.infrastructure.filesystem.Hdf5FileStore ...
                .writeDataset( ...
                pathFile, ...
                pathData, ...
                data, ...
                DataType = options.DataType);

        end % writeDataset

        function [isSuccess, msg] = writeAnalysisMetadata(obj, pathFile, metadata)

            arguments
                obj
                pathFile (1, 1) string
                metadata (1, 1) struct
            end

            paths = { ...
                "/metadata/schemaVersion"; ...
                "/metadata/batch/id"; ...
                "/metadata/batch/contentHash"; ...
                "/metadata/batch/contentHashVersion"; ...
                "/metadata/batch/configJson"; ...
                "/metadata/software/openMebius2Version"; ...
                "/metadata/software/matlabRelease"; ...
                "/metadata/software/matlabVersion"; ...
                "/metadata/software/toolboxesJson"; ...
                "/metadata/model/fileName"; ...
                "/metadata/model/sha256"; ...
                "/metadata/experiments/names"; ...
                "/metadata/experiments/fileNames"; ...
                "/metadata/experiments/sha256"; ...
                "/metadata/random/type"; ...
                "/metadata/random/seed"; ...
                "/metadata/random/state"; ...
                "/metadata/run/startedAtUtc"};
            values = { ...
                int32(metadata.schemaVersion); ...
                string(metadata.batchId); ...
                string(metadata.contentHash); ...
                int32(metadata.contentHashVersion); ...
                string(metadata.configJson); ...
                string(metadata.openMebius2Version); ...
                string(metadata.matlabRelease); ...
                string(metadata.matlabVersion); ...
                string(metadata.toolboxesJson); ...
                string(metadata.modelFileName); ...
                string(metadata.modelSha256); ...
                string(metadata.experimentNames(:)); ...
                string(metadata.experimentFileNames(:)); ...
                string(metadata.experimentSha256(:)); ...
                string(metadata.randomType); ...
                uint32(metadata.randomSeed); ...
                uint32(metadata.randomState(:)); ...
                string(metadata.startedAtUtc)};
            dataTypes = { ...
                "int32"; "string"; "string"; "int32"; "string"; ...
                "string"; "string"; "string"; "string"; ...
                "string"; "string"; "string"; "string"; "string"; ...
                "string"; "uint32"; "uint32"; "string"};

            isSuccess = true;
            msg = "";

            for i = 1:numel(paths)
                if isempty(values{i})
                    continue
                end

                [isSuccess, msg] = obj.writeDataset( ...
                    pathFile, ...
                    paths{i}, ...
                    values{i}, ...
                    DataType = dataTypes{i});

                if ~isSuccess
                    return
                end
            end

        end % writeAnalysisMetadata

        function [isSuccess, msg] = writeRunCompletion( ...
                obj, pathFile, finishedAtUtc, isError, isCanceled)

            [isSuccess, msg] = obj.writeDataset( ...
                pathFile, ...
                "/metadata/run/finishedAtUtc", ...
                string(finishedAtUtc), ...
                DataType = "string");

            if ~isSuccess
                return
            end

            [isSuccess, msg] = obj.writeDataset( ...
                pathFile, ...
                "/metadata/run/isError", ...
                int8(isError), ...
                DataType = "int8");

            if ~isSuccess
                return
            end

            [isSuccess, msg] = obj.writeDataset( ...
                pathFile, ...
                "/metadata/run/isCanceled", ...
                int8(isCanceled), ...
                DataType = "int8");

        end % writeRunCompletion

    end % methods

end % classdef
