classdef MFAInputSnapshotWriter
    % MFAINPUTSNAPSHOTWRITER Maps and persists MFA input snapshots.

    properties (SetAccess = private)
        Repository
    end

    methods

        function obj = MFAInputSnapshotWriter(options)

            arguments
                options.Repository = ...
                    openmebius.infrastructure.result.Hdf5ResultRepository()
            end

            obj.Repository = options.Repository;

        end % constructor

        function checkpoint = createGeneralCheckpoint( ...
                ~, status, resultID, experimentalMDV, ...
                fragmentList, fragmentMask)

            value = struct;
            value.status = status;
            value.ID = resultID;
            value.MDVExp = experimentalMDV;
            value.MDVFragList = fragmentList;
            value.MDVFragMask = fragmentMask;
            checkpoint = struct(Value = value);

        end % createGeneralCheckpoint

        function checkpoint = createModelCheckpoint( ...
                ~, modelTable, reversibleModelTable)

            arguments
                ~
                modelTable table
                reversibleModelTable table
            end

            checkpoint = struct( ...
                DataPath = "/model", ...
                Value = struct( ...
                modelID = string(modelTable.Properties.RowNames), ...
                modelReaction = string(modelTable.Reaction), ...
                modelTransition = string(modelTable.Transition), ...
                modelIndependent = modelTable.Independent, ...
                modelRevID = string( ...
                reversibleModelTable.Properties.RowNames), ...
                modelReactionRev = string( ...
                reversibleModelTable.Reaction), ...
                modelTransitionRev = string( ...
                reversibleModelTable.Transition), ...
                modelIndependentRev = ...
                reversibleModelTable.Independent));

        end % createModelCheckpoint

        function [isSuccess, message] = writeGeneral( ...
                obj, resultFile, checkpoint)

            value = checkpoint.Value;
            paths = [ ...
                         "/status"; ...
                         "/ID"; ...
                         "/MDVExp"; ...
                         "/MDVFragList"; ...
                     "/MDVFragMask"];
            values = { ...
                          int8(value.status); ...
                          string(value.ID); ...
                          value.MDVExp; ...
                          string(value.MDVFragList); ...
                          int8(value.MDVFragMask)};
            dataTypes = [ ...
                             "int8"; "string"; "double"; "string"; "int8"];
            [isSuccess, message] = ...
                openmebius.infrastructure.result.DatasetWriteSequence ...
                .write( ...
                obj.Repository, resultFile, paths, values, dataTypes);

        end % writeGeneral

        function [isSuccess, message] = writeModel( ...
                obj, resultFile, checkpoint)

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            paths = [ ...
                         basePath + "/modelID"; ...
                         basePath + "/modelReaction"; ...
                         basePath + "/modelTransition"; ...
                         basePath + "/modelIndependent"; ...
                         basePath + "/modelRevID"; ...
                         basePath + "/modelReactionRev"; ...
                         basePath + "/modelTransitionRev"; ...
                         basePath + "/modelIndependentRev"];
            values = { ...
                          value.modelID; ...
                          value.modelReaction; ...
                          value.modelTransition; ...
                          int8(value.modelIndependent); ...
                          value.modelRevID; ...
                          value.modelReactionRev; ...
                          value.modelTransitionRev; ...
                          int8(value.modelIndependentRev)};
            dataTypes = [ ...
                             "string"; "string"; "string"; "int8"; ...
                             "string"; "string"; "string"; "int8"];
            [isSuccess, message] = ...
                openmebius.infrastructure.result.DatasetWriteSequence ...
                .write( ...
                obj.Repository, resultFile, paths, values, dataTypes);

        end % writeModel

    end % methods

end % classdef
