classdef MFAResultCheckpointWriter
    % MFARESULTCHECKPOINTWRITER
    % Maps and persists MFA iteration checkpoints and workflow summaries.

    properties (SetAccess = private)
        Repository
    end

    methods

        function obj = MFAResultCheckpointWriter(options)

            arguments
                options.Repository = ...
                    openmebius.infrastructure.result.Hdf5ResultRepository()
            end

            obj.Repository = options.Repository;

        end % constructor

        function checkpoint = createIterationCheckpoint( ...
                ~, iteration, iterationResult, reversibleReactionIndices, ...
                options)

            arguments
                ~
                iteration (1, 1) double {mustBeInteger, mustBePositive}
                iterationResult (1, 1) openmebius.mfa.MFAIterationResult
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.TimestampUnix (1, 1) double = ...
                    posixtime(datetime("now", "TimeZone", "UTC"))
            end

            flux = iterationResult.Flux;
            forwardFlux = openmebius.mfa.ReversibleFluxMapper.mapFlux( ...
                flux, reversibleReactionIndices);

            [stepSize, candidates, objectives, exitFlags] = ...
                openmebius.infrastructure.result.MFAResultCheckpointWriter ...
                .extractStepSizeOutput(iterationResult.Output);
            iterationText = string(sprintf("%04d", iteration));
            value = struct;
            value.flux = flux;
            value.fluxFwd = forwardFlux;
            value.RSS = iterationResult.ObjectiveValue;
            value.MDV = iterationResult.MDV;
            value.exitflag = iterationResult.ExitFlag;
            value.finiteDifferenceStepSize = stepSize;
            value.finiteDifferenceStepSizeCandidates = candidates;
            value.finiteDifferenceStepSizeObjectives = objectives;
            value.finiteDifferenceStepSizeExitflags = exitFlags;
            value.time = options.TimestampUnix;
            checkpoint = struct( ...
                FieldName = "fluxResult" + iterationText, ...
                DataPath = "/fluxResult/" + iterationText, ...
                Value = value);

        end % createIterationCheckpoint

        function checkpoint = createFluxVariabilityCheckpoint( ...
                ~, lowerBounds, upperBounds, reversibleReactionIndices, ...
                options)

            arguments
                ~
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.TimestampUnix (1, 1) double = ...
                    posixtime(datetime("now", "TimeZone", "UTC"))
            end

            [forwardLowerBounds, forwardUpperBounds] = ...
                openmebius.mfa.ReversibleFluxMapper.mapBounds( ...
                lowerBounds, upperBounds, reversibleReactionIndices);
            value = struct( ...
                fluxLB = lowerBounds, ...
                fluxUB = upperBounds, ...
                fluxLBFwd = forwardLowerBounds, ...
                fluxUBFwd = forwardUpperBounds, ...
                time = options.TimestampUnix);
            checkpoint = struct( ...
                DataPath = "/fluxVariability", ...
                Value = value);

        end % createFluxVariabilityCheckpoint

        function checkpoint = createInitialFluxCheckpoint( ...
                ~, flux, rightHandSide, objectiveValues, ...
                reversibleReactionIndices, options)

            arguments
                ~
                flux double
                rightHandSide double
                objectiveValues double
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.TimestampUnix (1, 1) double = ...
                    posixtime(datetime("now", "TimeZone", "UTC"))
            end

            forwardFlux = openmebius.mfa.ReversibleFluxMapper.mapFlux( ...
                flux, reversibleReactionIndices);
            value = struct( ...
                flux = flux, ...
                fluxFwd = forwardFlux, ...
                rhs = rightHandSide, ...
                RSS = objectiveValues, ...
                time = options.TimestampUnix);
            checkpoint = struct( ...
                DataPath = "/initialFlux", ...
                Value = value);

        end % createInitialFluxCheckpoint

        function checkpoint = ...
                createMonteCarloConfidenceIntervalCheckpoint( ...
                ~, lowerBounds, upperBounds, confidenceIntervalConfig, ...
                output, options)

            arguments
                ~
                lowerBounds double
                upperBounds double
                confidenceIntervalConfig (1, 1) openmebius.mfa ...
                    .ConfidenceIntervalSettings
                output (1, 1) struct
                options.TimestampUnix (1, 1) double = ...
                    posixtime(datetime("now", "TimeZone", "UTC"))
            end

            if isempty(lowerBounds) || ...
                    ~isequal(size(lowerBounds), size(upperBounds))
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "ConfidenceIntervalSizeMismatch", ...
                    "Confidence interval bounds must be nonempty and " + ...
                "have the same size.");
            end

            monteCarloConfig = ...
                confidenceIntervalConfig.MonteCarloSettings;
            value = struct( ...
                time = options.TimestampUnix, ...
                fluxLB = lowerBounds, ...
                fluxUB = upperBounds, ...
                algorithm = ...
                confidenceIntervalConfig.Method.displayName(), ...
                iteration = monteCarloConfig.IterationCount, ...
                MIDSD = monteCarloConfig.StandardDeviation, ...
                optimizationProcedure = ...
                monteCarloConfig.Procedure.configValue(), ...
                TT = monteCarloConfig.TerminationTolerance, ...
                proximityThreshold = ...
                monteCarloConfig.ProximityThreshold, ...
                certainThreshold = monteCarloConfig.CertainThreshold, ...
                theNumberOfRuns = monteCarloConfig.TrialCount, ...
                calculationMethod = ...
                monteCarloConfig.CalculationMethod.configValue());
            checkpoint = struct( ...
                DataPath = "/CI", ...
                FinalFluxLB = lowerBounds(:, end), ...
                FinalFluxUB = upperBounds(:, end), ...
                Value = value, ...
                Fluxes = output.flux, ...
                MDV = output.MDV);

        end % createMonteCarloConfidenceIntervalCheckpoint

        function checkpoint = ...
                createGridSearchConfidenceIntervalCheckpoint( ...
                ~, lowerBounds, upperBounds, confidenceIntervalConfig, ...
                output, reactionIDs, options)

            arguments
                ~
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                confidenceIntervalConfig (1, 1) openmebius.mfa ...
                    .ConfidenceIntervalSettings
                output (1, 1) struct
                reactionIDs (:, 1) string
                options.TimestampUnix (1, 1) double = ...
                    posixtime(datetime("now", "TimeZone", "UTC"))
            end

            if isempty(lowerBounds) || ...
                    ~isequal(size(lowerBounds), size(upperBounds))
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "ConfidenceIntervalSizeMismatch", ...
                    "Grid-search confidence interval bounds must be " + ...
                "nonempty and have the same size.");
            end

            if ~isfield(output, "profile") || ...
                    ~isa(output.profile, ...
                "openmebius.mfa.GridSearchProfileData")
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "InvalidGridSearchProfile", ...
                "Grid-search output must contain profile data.");
            end

            if ~isfield(output, "objectiveThreshold") || ...
                    ~isscalar(output.objectiveThreshold) || ...
                    ~isfinite(output.objectiveThreshold) || ...
                    output.objectiveThreshold < 0
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "InvalidGridSearchThreshold", ...
                    "Grid-search output must contain a finite, " + ...
                "nonnegative objective threshold.");
            end

            if ~isfield(output, "bestObjective") || ...
                    ~isscalar(output.bestObjective) || ...
                    ~isfinite(output.bestObjective) || ...
                    output.bestObjective < 0 || ...
                    output.bestObjective > output.objectiveThreshold
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "InvalidGridSearchBestObjective", ...
                    "Grid-search output must contain a finite, " + ...
                    "nonnegative best objective that does not exceed " + ...
                "the objective threshold.");
            end

            profile = output.profile;
            fluxIndices = profile.FluxIndices(:);
            profileCount = numel(fluxIndices);

            if profileCount ~= numel(lowerBounds)
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "GridSearchProfileSizeMismatch", ...
                    "Grid-search profile data and confidence interval " + ...
                "bounds must have the same flux count.");
            end

            if isempty(reactionIDs) || ...
                    any(fluxIndices > numel(reactionIDs))
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "InvalidGridSearchReactionIDs", ...
                    "Grid-search flux indices must map to the supplied " + ...
                "reaction IDs.");
            end

            fixedFlux = profile.FixedFluxValues(:, :, 1);
            rss = profile.MinimumSumOfSquares;

            if size(fixedFlux, 1) ~= profileCount || ...
                    size(rss, 1) ~= profileCount || ...
                    size(fixedFlux, 2) ~= size(rss, 2)
                error( ...
                    "OpenMebius2:MFAResultCheckpointWriter:" + ...
                    "InvalidGridSearchDimensions", ...
                    "Grid-search fixed flux and RSS dimensions are " + ...
                "inconsistent.");
            end

            minimumRSS = min(rss, [], 3, "omitnan");
            fullLowerBounds = nan(numel(reactionIDs), 1);
            fullUpperBounds = nan(numel(reactionIDs), 1);
            fullLowerBounds(fluxIndices) = lowerBounds;
            fullUpperBounds(fluxIndices) = upperBounds;
            settings = confidenceIntervalConfig.GridSearchSettings;
            elapsedTime = NaN;

            if isfield(output, "time") && ...
                    isscalar(output.time) && isfinite(output.time)
                elapsedTime = output.time;
            end

            gridSearch = struct( ...
                fluxIndices = fluxIndices, ...
                reactionIDs = reactionIDs(fluxIndices), ...
                fixedFlux = fixedFlux, ...
                RSS = rss, ...
                minimumRSS = minimumRSS, ...
                bestObjective = output.bestObjective, ...
                objectiveThreshold = output.objectiveThreshold, ...
                pointCount = size(fixedFlux, 2), ...
                trialCount = size(rss, 3), ...
                maximumTrial = settings.MaximumTrial, ...
                minimumFluxRange = settings.MinimumFluxRange, ...
                alpha = settings.Alpha, ...
                thresholdType = settings.Threshold, ...
                intervalMode = settings.IntervalMode.configValue(), ...
                executionMode = settings.ExecutionMode.configValue(), ...
                delta = settings.Delta, ...
                elapsedTime = elapsedTime);
            value = struct( ...
                time = options.TimestampUnix, ...
                fluxLB = fullLowerBounds, ...
                fluxUB = fullUpperBounds, ...
                algorithm = ...
                confidenceIntervalConfig.Method.displayName(), ...
                gridSearch = gridSearch);
            checkpoint = struct( ...
                DataPath = "/CI", ...
                FinalFluxLB = fullLowerBounds, ...
                FinalFluxUB = fullUpperBounds, ...
                Value = value);

        end % createGridSearchConfidenceIntervalCheckpoint

        function [isSuccess, message] = writeIteration( ...
                obj, resultFile, checkpoint)

            arguments
                obj (1, 1) ...
                    openmebius.infrastructure.result.MFAResultCheckpointWriter
                resultFile (1, 1) string
                checkpoint (1, 1) struct
            end

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            paths = [ ...
                         basePath + "/flux"; ...
                         basePath + "/fluxFwd"; ...
                         basePath + "/RSS"; ...
                         basePath + "/MDV"; ...
                         basePath + "/exitflag"; ...
                         basePath + "/finiteDifferenceStepSize"];
            values = { ...
                          value.flux; ...
                          value.fluxFwd; ...
                          value.RSS; ...
                          value.MDV; ...
                          value.exitflag; ...
                          value.finiteDifferenceStepSize};
            dataTypes = repmat("double", numel(paths), 1);

            if ~isempty(value.finiteDifferenceStepSizeCandidates)
                paths = [paths; ...
                             basePath + "/finiteDifferenceStepSizeCandidates"; ...
                             basePath + "/finiteDifferenceStepSizeObjectives"; ...
                             basePath + "/finiteDifferenceStepSizeExitflags"];
                values = [values; { ...
                              value.finiteDifferenceStepSizeCandidates; ...
                              value.finiteDifferenceStepSizeObjectives; ...
                              value.finiteDifferenceStepSizeExitflags}];
                dataTypes = [dataTypes; repmat("double", 3, 1)];
            end

            paths(end + 1, 1) = basePath + "/time";
            values{end + 1, 1} = int32(value.time);
            dataTypes(end + 1, 1) = "int32";
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeIteration

        function [isSuccess, message] = writeFluxVariability( ...
                obj, resultFile, checkpoint, status)

            arguments
                obj (1, 1) ...
                    openmebius.infrastructure.result.MFAResultCheckpointWriter
                resultFile (1, 1) string
                checkpoint (1, 1) struct
                status double
            end

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            paths = [ ...
                         basePath + "/fluxLB"; ...
                         basePath + "/fluxUB"; ...
                         basePath + "/fluxLBFwd"; ...
                         basePath + "/fluxUBFwd"; ...
                         basePath + "/time"; ...
                     "/status"];
            values = { ...
                          value.fluxLB; ...
                          value.fluxUB; ...
                          value.fluxLBFwd; ...
                          value.fluxUBFwd; ...
                          int32(value.time); ...
                          int8(status)};
            dataTypes = [ ...
                             "double"; "double"; "double"; "double"; ...
                             "int32"; "int8"];
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeFluxVariability

        function [isSuccess, message] = writeInitialFlux( ...
                obj, resultFile, checkpoint, status)

            arguments
                obj (1, 1) ...
                    openmebius.infrastructure.result.MFAResultCheckpointWriter
                resultFile (1, 1) string
                checkpoint (1, 1) struct
                status double
            end

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            paths = [ ...
                         basePath + "/flux"; ...
                         basePath + "/fluxFwd"; ...
                         basePath + "/rhs"; ...
                         basePath + "/RSS"; ...
                         basePath + "/time"; ...
                     "/status"];
            values = { ...
                          value.flux; ...
                          value.fluxFwd; ...
                          value.rhs; ...
                          value.RSS; ...
                          int32(value.time); ...
                          int8(status)};
            dataTypes = [ ...
                             "double"; "double"; "double"; "double"; ...
                             "int32"; "int8"];
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeInitialFlux

        function [isSuccess, message] = ...
                writeMonteCarloConfidenceInterval( ...
                obj, resultFile, checkpoint, status)

            arguments
                obj (1, 1) ...
                    openmebius.infrastructure.result.MFAResultCheckpointWriter
                resultFile (1, 1) string
                checkpoint (1, 1) struct
                status double
            end

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            paths = [ ...
                         "/fluxLB"; ...
                         "/fluxUB"; ...
                         basePath + "/fluxLB"; ...
                         basePath + "/fluxUB"; ...
                         basePath + "/algorithm"; ...
                         basePath + "/iteration"; ...
                         basePath + "/MIDSD"; ...
                         basePath + "/optimizationProcedure"; ...
                         basePath + "/TT"; ...
                         basePath + "/proximityThreshold"; ...
                         basePath + "/certainThreshold"; ...
                         basePath + "/theNumberOfRuns"; ...
                         basePath + "/calculationMethod"; ...
                         basePath + "/fluxes"; ...
                         basePath + "/MDV"; ...
                         "/status"; ...
                         basePath + "/time"];
            values = { ...
                          checkpoint.FinalFluxLB; ...
                          checkpoint.FinalFluxUB; ...
                          value.fluxLB; ...
                          value.fluxUB; ...
                          string(value.algorithm); ...
                          int32(value.iteration); ...
                          value.MIDSD; ...
                          string(value.optimizationProcedure); ...
                          value.TT; ...
                          value.proximityThreshold; ...
                          value.certainThreshold; ...
                          int32(value.theNumberOfRuns); ...
                          string(value.calculationMethod); ...
                          checkpoint.Fluxes; ...
                          checkpoint.MDV; ...
                          int8(status); ...
                          int32(value.time)};
            dataTypes = [ ...
                             "double"; "double"; "double"; "double"; ...
                             "string"; "int32"; "double"; "string"; ...
                             "double"; "double"; "double"; "int32"; ...
                             "string"; "double"; "double"; "int8"; "int32"];
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeMonteCarloConfidenceInterval

        function [isSuccess, message] = ...
                writeGridSearchConfidenceInterval( ...
                obj, resultFile, checkpoint, status)

            arguments
                obj (1, 1) ...
                    openmebius.infrastructure.result.MFAResultCheckpointWriter
                resultFile (1, 1) string
                checkpoint (1, 1) struct
                status double
            end

            value = checkpoint.Value;
            gridSearch = value.gridSearch;
            basePath = string(checkpoint.DataPath);
            gridPath = basePath + "/gridSearch";
            paths = [ ...
                         "/fluxLB"; ...
                         "/fluxUB"; ...
                         basePath + "/fluxLB"; ...
                         basePath + "/fluxUB"; ...
                         basePath + "/algorithm"; ...
                         gridPath + "/fluxIndices"; ...
                         gridPath + "/reactionIDs"; ...
                         gridPath + "/fixedFlux"; ...
                         gridPath + "/RSS"; ...
                         gridPath + "/minimumRSS"; ...
                         gridPath + "/bestObjective"; ...
                         gridPath + "/objectiveThreshold"; ...
                         gridPath + "/pointCount"; ...
                         gridPath + "/trialCount"; ...
                         gridPath + "/maximumTrial"; ...
                         gridPath + "/minimumFluxRange"; ...
                         gridPath + "/alpha"; ...
                         gridPath + "/thresholdType"; ...
                         gridPath + "/intervalMode"; ...
                         gridPath + "/executionMode"; ...
                         gridPath + "/delta"; ...
                         gridPath + "/elapsedTime"; ...
                         "/status"; ...
                         basePath + "/time"];
            values = { ...
                          checkpoint.FinalFluxLB; ...
                          checkpoint.FinalFluxUB; ...
                          value.fluxLB; ...
                          value.fluxUB; ...
                          string(value.algorithm); ...
                          int32(gridSearch.fluxIndices); ...
                          string(gridSearch.reactionIDs); ...
                          gridSearch.fixedFlux; ...
                          gridSearch.RSS; ...
                          gridSearch.minimumRSS; ...
                          gridSearch.bestObjective; ...
                          gridSearch.objectiveThreshold; ...
                          int32(gridSearch.pointCount); ...
                          int32(gridSearch.trialCount); ...
                          int32(gridSearch.maximumTrial); ...
                          gridSearch.minimumFluxRange; ...
                          gridSearch.alpha; ...
                          string(gridSearch.thresholdType); ...
                          string(gridSearch.intervalMode); ...
                          string(gridSearch.executionMode); ...
                          gridSearch.delta; ...
                          gridSearch.elapsedTime; ...
                          int8(status); ...
                          int32(value.time)};
            dataTypes = [ ...
                             "double"; "double"; "double"; "double"; ...
                             "string"; "int32"; "string"; "double"; ...
                             "double"; "double"; "double"; "double"; ...
                             "int32"; "int32"; "int32"; "double"; ...
                             "double"; "string"; "string"; "string"; ...
                             "double"; ...
                             "double"; "int8"; "int32"];
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeGridSearchConfidenceInterval

        function [isSuccess, message] = writeSummary( ...
                obj, resultFile, objectiveValues, order, status, threshold)

            arguments
                obj (1, 1) ...
                    openmebius.infrastructure.result.MFAResultCheckpointWriter
                resultFile (1, 1) string
                objectiveValues (1, :) double
                order double
                status double
                threshold (1, 1) double
            end

            paths = ["/RSS"; "/RSSIndex"; "/status"; "/threshold"];
            values = { ...
                          objectiveValues; ...
                          int32(order); ...
                          int8(status); ...
                          threshold};
            dataTypes = ["double"; "int32"; "int8"; "double"];
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeSummary

    end % methods

    methods (Access = private)

        function [isSuccess, message] = writeDatasets( ...
                obj, resultFile, paths, values, dataTypes)

            [isSuccess, message] = ...
                openmebius.infrastructure.result.DatasetWriteSequence ...
                .write( ...
                obj.Repository, resultFile, paths, values, dataTypes);

        end % writeDatasets

    end % methods (Access = private)

    methods (Static, Access = private)

        function [stepSize, candidates, objectives, exitFlags] = ...
                extractStepSizeOutput(optimizationOutput)

            stepSize = NaN;
            candidates = [];
            objectives = [];
            exitFlags = [];

            if ~isstruct(optimizationOutput)
                return;
            end

            if isfield(optimizationOutput, ...
                'fminconFiniteDifferenceStepSize') && ...
                    ~isempty( ...
                    optimizationOutput.fminconFiniteDifferenceStepSize)
                stepSize = double( ...
                    optimizationOutput ...
                    .fminconFiniteDifferenceStepSize(1));
            end

            if ~isfield(optimizationOutput, ...
                'fminconFiniteDifferenceStepSizeSearch') || ...
                    ~isstruct(optimizationOutput ...
                    .fminconFiniteDifferenceStepSizeSearch)
                return;
            end

            searchOutput = optimizationOutput ...
                .fminconFiniteDifferenceStepSizeSearch;

            if isfield(searchOutput, 'candidates')
                candidates = double(searchOutput.candidates(:));
            end

            if isfield(searchOutput, 'objectives')
                objectives = double(searchOutput.objectives(:));
            end

            if isfield(searchOutput, 'exitflags')
                exitFlags = double(searchOutput.exitflags(:));
            end

        end % extractStepSizeOutput

    end % methods (Static, Access = private)

end % classdef
