classdef NextLabelResultCheckpointWriter
    % NEXTLABELRESULTCHECKPOINTWRITER
    % Maps and persists result checkpoints for labeling suggestions.

    properties (SetAccess = private)
        Repository
    end

    methods

        function obj = NextLabelResultCheckpointWriter(options)

            arguments
                options.Repository = ...
                    openmebius.infrastructure.result.Hdf5ResultRepository()
            end

            obj.Repository = options.Repository;

        end % constructor

        function checkpoint = createSuggestionTableCheckpoint( ...
                ~, suggestionData, columnNames)

            checkpoint = struct( ...
                DataPath = "/nextLabelPattern/suggestionTable", ...
                Value = struct( ...
                colName = string(columnNames), ...
                data = suggestionData));

        end % createSuggestionTableCheckpoint

        function checkpoint = createInitialFluxCheckpoint( ...
                ~, pattern, flux, rightHandSide, objectiveValues, ...
                reversibleReactionIndices, options)

            arguments
                ~
                pattern
                flux double
                rightHandSide double
                objectiveValues double
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.TimestampUnix (1, 1) double = ...
                    posixtime(datetime("now", "TimeZone", "UTC"))
            end

            fieldName = ...
                openmebius.infrastructure.result ...
                .NextLabelResultCheckpointWriter.patternFieldName(pattern);
            forwardFlux = openmebius.mfa.ReversibleFluxMapper.mapFlux( ...
                flux, reversibleReactionIndices);
            checkpoint = struct( ...
                FieldName = fieldName, ...
                DataPath = "/nextLabelPattern/" + fieldName, ...
                Value = struct( ...
                flux = flux, ...
                fluxFwd = forwardFlux, ...
                rhs = rightHandSide, ...
                RSS = objectiveValues, ...
                time = options.TimestampUnix));

        end % createInitialFluxCheckpoint

        function checkpoint = createConfidenceIntervalCheckpoint( ...
                ~, pattern, lowerBounds, upperBounds, options)

            arguments
                ~
                pattern
                lowerBounds double
                upperBounds double
                options.TimestampUnix (1, 1) double = ...
                    posixtime(datetime("now", "TimeZone", "UTC"))
            end

            if isempty(lowerBounds) || ...
                    ~isequal(size(lowerBounds), size(upperBounds))
                error( ...
                    "OpenMebius2:NextLabelResultCheckpointWriter:" + ...
                    "ConfidenceIntervalSizeMismatch", ...
                    "Confidence interval bounds must be nonempty and " + ...
                    "have the same size.");
            end

            fieldName = ...
                openmebius.infrastructure.result ...
                .NextLabelResultCheckpointWriter.patternFieldName(pattern);
            checkpoint = struct( ...
                FieldName = fieldName, ...
                DataPath = "/nextLabelPattern/" + fieldName, ...
                Value = struct( ...
                fluxLB = lowerBounds(:, end), ...
                fluxUB = upperBounds(:, end), ...
                CI = struct( ...
                fluxLB = lowerBounds, ...
                fluxUB = upperBounds, ...
                time = options.TimestampUnix)));

        end % createConfidenceIntervalCheckpoint

        function [isSuccess, message] = writeSuggestionTable( ...
                obj, resultFile, checkpoint)

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, ...
                [basePath + "/colName"; basePath + "/data"], ...
                {value.colName; value.data}, ...
                ["string"; "string"]);

        end % writeSuggestionTable

        function [isSuccess, message] = writeInitialFlux( ...
                obj, resultFile, checkpoint)

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            paths = [ ...
                basePath + "/flux"; ...
                basePath + "/fluxFwd"; ...
                basePath + "/rhs"; ...
                basePath + "/RSS"; ...
                basePath + "/time"];
            values = { ...
                value.flux; ...
                value.fluxFwd; ...
                value.rhs; ...
                value.RSS; ...
                int32(value.time)};
            dataTypes = [ ...
                "double"; "double"; "double"; "double"; "int32"];
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeInitialFlux

        function [isSuccess, message] = writeConfidenceInterval( ...
                obj, resultFile, checkpoint)

            value = checkpoint.Value;
            basePath = string(checkpoint.DataPath);
            ciPath = basePath + "/CI";
            paths = [ ...
                basePath + "/fluxLB"; ...
                basePath + "/fluxUB"; ...
                ciPath + "/fluxLB"; ...
                ciPath + "/fluxUB"; ...
                ciPath + "/time"];
            values = { ...
                value.fluxLB; ...
                value.fluxUB; ...
                value.CI.fluxLB; ...
                value.CI.fluxUB; ...
                int32(value.CI.time)};
            dataTypes = [ ...
                "double"; "double"; "double"; "double"; "int32"];
            [isSuccess, message] = obj.writeDatasets( ...
                resultFile, paths, values, dataTypes);

        end % writeConfidenceInterval

    end % methods

    methods (Access = private)

        function [isSuccess, message] = writeDatasets( ...
                obj, resultFile, paths, values, dataTypes)

            [isSuccess, message] = ...
                openmebius.infrastructure.result.DatasetWriteSequence ...
                .write( ...
                obj.Repository, resultFile, paths, values, dataTypes);

        end % writeDatasets

    end % methods (Access = private)

    methods (Static, Access = private)

        function fieldName = patternFieldName(pattern)

            joinedPattern = strjoin(string(pattern), "_");
            fieldName = string(matlab.lang.makeValidName(joinedPattern));

        end % patternFieldName

    end % methods (Static, Access = private)

end % classdef
