classdef ResultManifestRepository < handle
    % RESULTMANIFESTREPOSITORY
    % Stores one atomic JSON manifest beside each HDF5 result file.

    properties (Constant)
        SchemaVersion = 1
    end

    properties (Access = private)
        JsonFileStore
    end

    methods

        function obj = ResultManifestRepository(options)

            arguments
                options.JsonFileStore = ...
                    openmebius.infrastructure.filesystem.JsonFileStore()
            end

            obj.JsonFileStore = options.JsonFileStore;

        end % constructor

        function [isSuccess, msg] = writeStarted(obj, resultLocation, metadata)

            arguments
                obj
                resultLocation openmebius.domain.result.ResultLocation
                metadata (1, 1) struct
            end

            document = obj.createDocument( ...
                resultLocation, ...
                metadata, ...
                "running", ...
                "", ...
                0, ...
                "", ...
                false, ...
                false);
            [isSuccess, msg] = obj.writeDocument( ...
                resultLocation.manifestFile(metadata.batchId), ...
                document);

        end % writeStarted

        function [isSuccess, msg] = writeCompleted( ...
                obj, ...
                resultLocation, ...
                metadata, ...
                finishedAtUtc, ...
                isError, ...
                isCanceled)

            arguments
                obj
                resultLocation openmebius.domain.result.ResultLocation
                metadata (1, 1) struct
                finishedAtUtc (1, 1) string
                isError (1, 1) logical
                isCanceled (1, 1) logical
            end

            if isCanceled
                status = "canceled";
            elseif isError
                status = "error";
            else
                status = "finished";
            end

            resultFile = resultLocation.resultFile(metadata.batchId);
            resultSha256 = ...
                openmebius.infrastructure.filesystem.FileHasher.hashFile( ...
                resultFile);
            resultSizeBytes = 0;
            resultFileInfo = dir(resultFile);

            if ~isempty(resultFileInfo)
                resultSizeBytes = double(resultFileInfo(1).bytes);
            end

            document = obj.createDocument( ...
                resultLocation, ...
                metadata, ...
                status, ...
                resultSha256, ...
                resultSizeBytes, ...
                finishedAtUtc, ...
                isError, ...
                isCanceled);
            [isSuccess, msg] = obj.writeDocument( ...
                resultLocation.manifestFile(metadata.batchId), ...
                document);

        end % writeCompleted

        function document = read(obj, resultLocation, batchId)

            arguments
                obj
                resultLocation openmebius.domain.result.ResultLocation
                batchId (1, 1) string
            end

            document = obj.JsonFileStore.read( ...
                resultLocation.manifestFile(batchId));
            document = openmebius.infrastructure.result ...
                .ResultManifestMigration.toCurrentDocument(document);

        end % read

    end % methods

    methods (Access = private)

        function document = createDocument( ...
                obj, ...
                resultLocation, ...
                metadata, ...
                status, ...
                resultSha256, ...
                resultSizeBytes, ...
                finishedAtUtc, ...
                isError, ...
                isCanceled)

            obj.validateMetadata(metadata);
            [~, resultName, resultExtension] = fileparts( ...
                resultLocation.resultFile(metadata.batchId));
            experiments = obj.createExperiments(metadata);
            config = obj.decodeJson(metadata.configJson, struct);
            toolboxes = obj.decodeJson(metadata.toolboxesJson, struct.empty(0, 1));

            document = struct( ...
                'schemaVersion', obj.SchemaVersion, ...
                'batch', struct( ...
                'id', string(metadata.batchId), ...
                'name', string(obj.metadataValue( ...
                metadata, 'batchName', "")), ...
                'description', string(obj.metadataValue( ...
                metadata, 'batchDescription', "")), ...
                'contentHash', string(metadata.contentHash), ...
                'contentHashVersion', double(metadata.contentHashVersion)), ...
                'result', struct( ...
                'file', string(resultName) + string(resultExtension), ...
                'sha256', string(resultSha256), ...
                'sizeBytes', double(resultSizeBytes), ...
                'status', string(status)), ...
                'software', struct( ...
                'openMebius2Version', string(metadata.openMebius2Version), ...
                'matlabRelease', string(metadata.matlabRelease), ...
                'matlabVersion', string(metadata.matlabVersion), ...
                'toolboxes', toolboxes), ...
                'model', struct( ...
                'fileName', string(metadata.modelFileName), ...
                'sha256', string(metadata.modelSha256)), ...
                'experiments', experiments, ...
                'analysis', struct( ...
                'metadataSchemaVersion', double(metadata.schemaVersion), ...
                'config', config), ...
                'random', struct( ...
                'type', string(metadata.randomType), ...
                'seed', double(metadata.randomSeed), ...
                'state', double(metadata.randomState(:))), ...
                'run', struct( ...
                'startedAtUtc', string(metadata.startedAtUtc), ...
                'finishedAtUtc', string(finishedAtUtc), ...
                'isError', logical(isError), ...
                'isCanceled', logical(isCanceled)));

        end % createDocument

        function experiments = createExperiments(~, metadata)

            names = string(metadata.experimentNames(:));
            fileNames = string(metadata.experimentFileNames(:));
            hashes = string(metadata.experimentSha256(:));

            if numel(names) ~= numel(fileNames) || numel(names) ~= numel(hashes)
                error( ...
                    "OpenMebius2:ResultManifest:ExperimentMetadataMismatch", ...
                    "Experiment names, files, and hashes must have equal lengths.");
            end

            experiments = repmat( ...
                struct('name', "", 'fileName', "", 'sha256', ""), ...
                numel(names), ...
                1);

            for i = 1:numel(names)
                experiments(i).name = names(i);
                experiments(i).fileName = fileNames(i);
                experiments(i).sha256 = hashes(i);
            end

        end % createExperiments

        function value = decodeJson(~, json, defaultValue)

            value = defaultValue;

            if strlength(string(json)) == 0
                return
            end

            value = jsondecode(char(string(json)));

        end % decodeJson

        function [isSuccess, msg] = writeDocument(obj, pathFile, document)

            try
                obj.JsonFileStore.writeAtomically(pathFile, document);
                isSuccess = true;
                msg = "";
            catch ME
                isSuccess = false;
                msg = string(ME.message);
            end

        end % writeDocument

        function validateMetadata(~, metadata)

            requiredFields = [ ...
                "schemaVersion", "batchId", "contentHash", ...
                "contentHashVersion", "configJson", ...
                "openMebius2Version", "matlabRelease", "matlabVersion", ...
                "toolboxesJson", "modelFileName", "modelSha256", ...
                "experimentNames", "experimentFileNames", ...
                "experimentSha256", "randomType", "randomSeed", ...
                "randomState", "startedAtUtc"];
            missingFields = requiredFields(~isfield(metadata, requiredFields));

            if ~isempty(missingFields)
                error( ...
                    "OpenMebius2:ResultManifest:MissingMetadata", ...
                    "Result metadata is missing fields: %s", ...
                    strjoin(missingFields, ", "));
            end

        end % validateMetadata

        function value = metadataValue(~, metadata, fieldName, defaultValue)

            value = defaultValue;

            if isfield(metadata, fieldName) && ...
                    ~isempty(metadata.(fieldName))
                value = metadata.(fieldName);
            end

        end % metadataValue

    end % methods (Access = private)

end % classdef
