classdef ConfidenceIntervalWorkflow
    % CONFIDENCEINTERVALWORKFLOW
    % Selects and executes the configured confidence-interval method.

    properties (SetAccess = private)
        MonteCarloSolver
    end

    methods

        function obj = ConfidenceIntervalWorkflow(options)

            arguments
                options.MonteCarloSolver = ...
                    openmebius.mfa.MonteCarloConfidenceIntervalSolver()
            end

            obj.MonteCarloSolver = options.MonteCarloSolver;

        end

        function result = run( ...
                obj, settings, experimentalMDV, fittedFluxes, ...
                statusFlag, problem, initialRightHandSides, ...
                reversibleReactionIndices, iterationFunction, options)

            arguments
                obj (1, 1) openmebius.mfa.ConfidenceIntervalWorkflow
                settings (1, 1) openmebius.mfa ...
                    .ConfidenceIntervalSettings
                experimentalMDV double
                fittedFluxes (:, :) double
                statusFlag (1, :) double
                problem
                initialRightHandSides double
                reversibleReactionIndices (:, 2) double
                iterationFunction (1, 1) function_handle
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            report = options.MessageReporter;
            report("info", "Calculating confidence interval...");

            if ~settings.Enabled
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult();
                return
            end

            method = settings.Method.displayName();

            if ~settings.Method.isMonteCarlo()
                message = ...
                    "Unknown method for calculating confidence interval.";
                report("error", message);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = method, ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            result = obj.runMonteCarlo( ...
                settings.MonteCarloSettings, ...
                experimentalMDV, ...
                fittedFluxes, ...
                statusFlag, ...
                problem, ...
                initialRightHandSides, ...
                reversibleReactionIndices, ...
                iterationFunction, ...
                report, ...
                options.CancellationRequested);

            if ~result.IsError
                report( ...
                    "info", ...
                    "Confidence interval calculated using Monte " + ...
                    "Carlo method.");
            end

        end

    end

    methods (Access = private)

        function result = runMonteCarlo( ...
                obj, config, experimentalMDV, fittedFluxes, ...
                statusFlag, problem, initialRightHandSides, ...
                reversibleReactionIndices, iterationFunction, ...
                report, cancellationRequested)

            report( ...
                "info", ...
                "Calculating confidence interval using Monte Carlo " + ...
                "method. It may take a while " + ...
                "(Cancel button is not available).");

            if numel(statusFlag) < 2 || statusFlag(2) ~= 1
                message = "Flux distribution is not calculated.";
                report("error", message);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Monte Carlo", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            bestFlux = fittedFluxes(:, 1);
            rightHandSide = problem.RightHandSide;

            if ~isempty(initialRightHandSides)
                rightHandSide = initialRightHandSides(:, end);
            end

            independentValues = ...
                bestFlux(problem.BoundaryReactionMask);
            rightHandSide = problem.composeRightHandSide( ...
                independentValues, ...
                BaseRightHandSide = rightHandSide);

            try
                solverResult = obj.MonteCarloSolver.solve( ...
                    experimentalMDV, ...
                    size(fittedFluxes, 1), ...
                    config, ...
                    @(mdv) iterationFunction(mdv, rightHandSide), ...
                    reversibleReactionIndices, ...
                    MessageReporter = report, ...
                    CancellationRequested = cancellationRequested);
            catch ME
                message = "Confidence interval calculation failed. " + ...
                    string(ME.message);
                report("error", message);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Monte Carlo", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            output = struct;
            output.MDV = solverResult.PerturbedMDVs;
            output.flux = solverResult.Fluxes;
            output.iteration = solverResult.IterationCount;
            output.time = solverResult.ElapsedTime;

            if solverResult.IsCanceled
                report( ...
                    "info", ...
                    "Confidence interval calculation canceled.");
            else
                report( ...
                    "info", ...
                    "Confidence interval calculated successfully." + ...
                    " (Elapsed time: " + ...
                    string(seconds(output.time), "hh:mm:ss") + ")");
            end

            result = ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                LowerBounds = solverResult.LowerBounds, ...
                UpperBounds = solverResult.UpperBounds, ...
                Output = output, ...
                Method = "Monte Carlo", ...
                IsCalculated = true, ...
                IsCanceled = solverResult.IsCanceled);

        end

    end

end
