classdef ConfidenceIntervalWorkflow
    % CONFIDENCEINTERVALWORKFLOW
    % Selects and executes the configured confidence-interval method.

    properties (SetAccess = private)
        MonteCarloSolver
        GridSearchSolver
    end

    methods

        function obj = ConfidenceIntervalWorkflow(options)

            arguments
                options.MonteCarloSolver = ...
                    openmebius.mfa.MonteCarloConfidenceIntervalSolver()
                options.GridSearchSolver = ...
                    openmebius.mfa.GridSearchConfidenceIntervalSolver()
            end

            obj.MonteCarloSolver = options.MonteCarloSolver;
            obj.GridSearchSolver = options.GridSearchSolver;

        end

        function result = run( ...
                obj, settings, experimentalMDV, fittedFluxes, ...
                hasFluxDistribution, problem, initialRightHandSides, ...
                reversibleReactionIndices, iterationFunction, options)

            arguments
                obj (1, 1) openmebius.mfa.ConfidenceIntervalWorkflow
                settings (1, 1) openmebius.mfa ...
                    .ConfidenceIntervalSettings
                experimentalMDV double
                fittedFluxes (:, :) double
                hasFluxDistribution (1, 1) logical
                problem
                initialRightHandSides double
                reversibleReactionIndices (:, 2) double
                iterationFunction (1, 1) function_handle
                options.ProfileIterationFunction = []
                options.GridSearchProfileFluxIndices ...
                    (:, 1) double = zeros(0, 1)
                options.GridSearchObjectiveThreshold ...
                    (1, 1) double = NaN
                options.GridSearchBestObjective ...
                    (1, 1) double = NaN
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.ProgressReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            report = options.MessageReporter;
            report("info", "Calculating confidence interval...");

            if ~settings.Enabled
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult();
                return
            end

            if settings.Method == ...
                    openmebius.mfa.ConfidenceIntervalMethod.GridSearch

                if isempty(options.ProfileIterationFunction) || ...
                        ~isa(options.ProfileIterationFunction, ...
                        "function_handle")

                    error( ...
                        "OpenMebius2:ConfidenceIntervalWorkflow:" + ...
                        "MissingProfileIterationFunction", ...
                        "Grid search requires a profile iteration function.");
                end

            end

            if settings.Method.isMonteCarlo()

                result = obj.runMonteCarlo( ...
                    settings.MonteCarloSettings, ...
                    experimentalMDV, ...
                    fittedFluxes, ...
                    hasFluxDistribution, ...
                    problem, ...
                    initialRightHandSides, ...
                    reversibleReactionIndices, ...
                    iterationFunction, ...
                    report, ...
                    options.ProgressReporter, ...
                    options.CancellationRequested);

            else

                result = obj.runGridSearch( ...
                    settings.GridSearchSettings, ...
                    fittedFluxes, ...
                    hasFluxDistribution, ...
                    problem, ...
                    initialRightHandSides, ...
                    reversibleReactionIndices, ...
                    options.ProfileIterationFunction, ...
                    options.GridSearchProfileFluxIndices, ...
                    options.GridSearchObjectiveThreshold, ...
                    options.GridSearchBestObjective, ...
                    report, ...
                    options.ProgressReporter, ...
                    options.CancellationRequested);

            end

            if ~result.IsError
                report( ...
                    "info", ...
                    "Confidence interval calculated using " + ...
                    result.Method + " method.");
            end

        end

    end

    methods (Access = private)

        function result = runMonteCarlo( ...
                obj, config, experimentalMDV, fittedFluxes, ...
                hasFluxDistribution, problem, initialRightHandSides, ...
                reversibleReactionIndices, iterationFunction, ...
                report, progressReporter, cancellationRequested)

            report( ...
                "info", ...
                "Calculating confidence interval using Monte Carlo " + ...
                "method. It may take a while " + ...
                "(Cancel button is not available).");

            if ~hasFluxDistribution
                message = "Flux distribution is not calculated.";
                report("error", message);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Monte Carlo", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            bestFlux = fittedFluxes(:, 1);
            requiredInitialPointCount = 1;

            if config.Procedure.isMultipleRun()
                requiredInitialPointCount = max( ...
                    config.TrialCount, config.CertainThreshold);
            end

            [initialPointSchedule, distinctInitialPointCount] = ...
                openmebius.mfa.ConfidenceIntervalWorkflow ...
                .buildMonteCarloInitialPointSchedule( ...
                problem, bestFlux, initialRightHandSides, ...
                requiredInitialPointCount);
            rightHandSide = initialPointSchedule(:, 1);

            if config.Procedure.isMultipleRun() && ...
                    distinctInitialPointCount == 1 && ...
                    requiredInitialPointCount > 1
                report( ...
                    "warning", ...
                    "Only one distinct feasible Monte Carlo initial " + ...
                    "point is available; multiple runs will reuse it.");
            end

            try
                solverResult = obj.MonteCarloSolver.solve( ...
                    experimentalMDV, ...
                    size(fittedFluxes, 1), ...
                    config, ...
                    @(mdv) iterationFunction(mdv, rightHandSide), ...
                    reversibleReactionIndices, ...
                    TrialIterationFunction = ...
                    @(mdv, ~, trial) iterationFunction( ...
                    mdv, initialPointSchedule(:, trial)), ...
                    MessageReporter = report, ...
                    ProgressReporter = progressReporter, ...
                    CancellationRequested = cancellationRequested);
            catch ME
                message = "Confidence interval calculation failed. " + ...
                    string(ME.message);
                diagnostic = ...
                    openmebius.mfa.ConfidenceIntervalWorkflow ...
                    .exceptionDiagnostic(ME);
                report("error", message + diagnostic);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Monte Carlo", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            output = struct;
            output.MDV = solverResult.PerturbedMDVs;
            output.flux = solverResult.Fluxes;
            output.iteration = solverResult.IterationCount;
            output.time = solverResult.ElapsedTime;

            if solverResult.IsCanceled
                report( ...
                    "info", ...
                    "Confidence interval calculation canceled.");
            else
                report( ...
                    "info", ...
                    "Confidence interval calculated successfully." + ...
                    " (Elapsed time: " + ...
                    string(seconds(output.time), "hh:mm:ss") + ")");
            end

            result = ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                LowerBounds = solverResult.LowerBounds, ...
                UpperBounds = solverResult.UpperBounds, ...
                Output = output, ...
                Method = "Monte Carlo", ...
                IsCalculated = true, ...
                IsCanceled = solverResult.IsCanceled);

        end % method runMonteCarlo

        function result = runGridSearch( ...
                obj, config, fittedFluxes, hasFluxDistribution, ...
                problem, initialRightHandSides, ...
                reversibleReactionIndices, ...
                profileIterationFunction, ...
                selectedFluxIndices, objectiveThreshold, bestObjective, ...
                report, progressReporter, cancellationRequested)

            if ~hasFluxDistribution
                message = "Flux distribution is not calculated.";

                report("error", message);

                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Grid search", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            if isempty(problem)
                message = "The MFA problem is not available.";

                report("error", message);

                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Grid search", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            if ~isfinite(objectiveThreshold) || ...
                    objectiveThreshold < 0
                message = ...
                    "A finite, nonnegative grid-search objective " + ...
                    "threshold is required.";
                report("error", message);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Grid search", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            if ~isfinite(bestObjective) || bestObjective < 0 || ...
                    bestObjective > objectiveThreshold
                message = ...
                    "A finite, nonnegative grid-search best objective " + ...
                    "not exceeding the threshold is required.";
                report("error", message);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Grid search", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            bestFlux = fittedFluxes(:, 1);

            rightHandSide = problem.RightHandSide;

            if ~isempty(initialRightHandSides)
                rightHandSide = initialRightHandSides(:, end);
            end

            independentValues = ...
                bestFlux(problem.BoundaryReactionMask);

            initialIndependentValues = ...
                fittedFluxes(problem.BoundaryReactionMask, :);

            rightHandSide = problem.composeRightHandSide( ...
                independentValues, ...
                BaseRightHandSide = rightHandSide);

            evaluationFunction = ...
                @(equalityMatrix, equalityRightHandSide, ...
                initialIndependentValues) ...
                profileIterationFunction( ...
                rightHandSide, ...
                equalityMatrix, ...
                equalityRightHandSide, ...
                initialIndependentValues);

            try
                solverResult = obj.GridSearchSolver.solve( ...
                    problem, ...
                    bestFlux, ...
                    rightHandSide, ...
                    config, ...
                    evaluationFunction, ...
                    reversibleReactionIndices, ...
                    ProfileFluxIndices = selectedFluxIndices, ...
                    ObjectiveThreshold = objectiveThreshold, ...
                    BestObjective = bestObjective, ...
                    InitialIndependentValues = initialIndependentValues, ...
                    MessageReporter = report, ...
                    ProgressReporter = progressReporter, ...
                    CancellationRequested = cancellationRequested);
            catch ME
                message = "Confidence interval calculation failed. " + ...
                    string(ME.message);
                diagnostic = ...
                    openmebius.mfa.ConfidenceIntervalWorkflow ...
                    .exceptionDiagnostic(ME);
                report("error", message + diagnostic);
                result = ...
                    openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                    Method = "Grid search", ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            output = struct;
            output.profile = solverResult.ProfileData;
            output.time = solverResult.ElapsedTime;
            output.objectiveThreshold = objectiveThreshold;
            output.bestObjective = bestObjective;

            if solverResult.IsCanceled
                report( ...
                    "info", ...
                    "Confidence interval calculation canceled.");
            else
                report( ...
                    "info", ...
                    "Confidence interval calculated successfully." + ...
                    " (Elapsed time: " + ...
                    string(seconds(output.time), "hh:mm:ss") + ")");
            end

            result = ...
                openmebius.mfa.ConfidenceIntervalWorkflowResult( ...
                LowerBounds = solverResult.LowerBounds, ...
                UpperBounds = solverResult.UpperBounds, ...
                Output = output, ...
                Method = "Grid search", ...
                IsCalculated = true, ...
                IsCanceled = solverResult.IsCanceled);

        end % method runGridSearch

    end % methods (Access = private)

    methods (Static, Access = private)

        function [schedule, distinctPointCount] = ...
                buildMonteCarloInitialPointSchedule( ...
                problem, bestFlux, initialRightHandSides, ...
                requiredPointCount)

            baseRightHandSide = problem.RightHandSide;

            if ~isempty(initialRightHandSides)
                baseRightHandSide = initialRightHandSides(:, end);
            end

            independentValues = ...
                bestFlux(problem.BoundaryReactionMask);
            bestRightHandSide = problem.composeRightHandSide( ...
                independentValues, ...
                BaseRightHandSide = baseRightHandSide);
            candidates = [bestRightHandSide, initialRightHandSides];
            candidates = unique(candidates.', "rows", "stable").';
            distinctPointCount = size(candidates, 2);

            if distinctPointCount == 0
                error( ...
                    "OpenMebius2:ConfidenceIntervalWorkflow:" + ...
                    "MissingMonteCarloInitialPoint", ...
                    "At least one feasible Monte Carlo initial point " + ...
                    "is required.");
            end

            scheduledCandidateCount = min( ...
                distinctPointCount, requiredPointCount);
            schedule = candidates(:, 1:scheduledCandidateCount);
            remainingCount = requiredPointCount - ...
                scheduledCandidateCount;

            if remainingCount == 0
                return
            end

            if distinctPointCount == 1
                schedule(:, end + 1:requiredPointCount) = repmat( ...
                    candidates(:, 1), 1, remainingCount);
                return
            end

            % Convex combinations of feasible initial points remain
            % feasible for the linear steady-state and flux constraints.
            levelCount = ceil(remainingCount / distinctPointCount);

            for index = 1:remainingCount
                leftIndex = mod(index - 1, distinctPointCount) + 1;
                rightIndex = mod(leftIndex, distinctPointCount) + 1;
                level = floor((index - 1) / distinctPointCount) + 1;
                weight = level / (levelCount + 1);
                schedule(:, scheduledCandidateCount + index) = ...
                    (1 - weight) * candidates(:, leftIndex) + ...
                    weight * candidates(:, rightIndex);
            end

        end % buildMonteCarloInitialPointSchedule

        function diagnostic = exceptionDiagnostic(exception)

            diagnostic = "";

            if strlength(string(exception.identifier)) > 0
                diagnostic = diagnostic + ...
                    " [" + string(exception.identifier) + "]";
            end

            if ~isempty(exception.stack)
                frame = exception.stack(1);
                diagnostic = diagnostic + ...
                    " (" + string(frame.name) + ...
                    ", line " + string(frame.line) + ")";
            end

        end

    end

end % classdef ConfidenceIntervalWorkflow
