classdef EffluxPerturbationProfileFactory
    % EFFLUXPERTURBATIONPROFILEFACTORY
    % Maps selected substrate effluxes to internal flux indices.

    methods

        function profile = create( ...
                ~, model, substrateList, experimentalValues, ...
                standardDeviations, freeMask)

            arguments
                ~
                model
                substrateList
                experimentalValues double
                standardDeviations double
                freeMask
            end

            substrateList = string(substrateList(:));
            experimentalValues = experimentalValues(:);
            standardDeviations = standardDeviations(:);
            freeMask = logical(freeMask(:));
            itemCount = numel(substrateList);

            if isempty(freeMask)
                profile = ...
                    openmebius.mfa.EffluxPerturbationProfile();
                return
            end

            if numel(freeMask) ~= itemCount
                error( ...
                    "OpenMebius2:EffluxPerturbationProfileFactory:" + ...
                    "DimensionMismatch", ...
                "Efflux data must match the substrate list length.");
            end

            selectedIndices = find(freeMask);

            if isempty(selectedIndices)
                profile = ...
                    openmebius.mfa.EffluxPerturbationProfile();
                return
            end

            if numel(experimentalValues) ~= itemCount || ...
                    numel(standardDeviations) ~= itemCount
                error( ...
                    "OpenMebius2:EffluxPerturbationProfileFactory:" + ...
                    "DimensionMismatch", ...
                "Efflux data must match the substrate list length.");
            end

            if ~ismethod(model, 'getSBefore') || ...
                    ~ismethod( ...
                    model, 'findSubstrateRxnIDFromMetaboliteIrrev')
                error( ...
                    "OpenMebius2:EffluxPerturbationProfileFactory:" + ...
                    "InvalidModel", ...
                    "The model must expose efflux-reaction mapping " + ...
                "methods.");
            end

            stoichiometry = model.getSBefore();

            if ~istable(stoichiometry)
                error( ...
                    "OpenMebius2:EffluxPerturbationProfileFactory:" + ...
                    "InvalidStoichiometry", ...
                "The model stoichiometry must be a table.");
            end

            reactionNames = ...
                string(stoichiometry.Properties.VariableNames);
            reactionIndices = nan(numel(selectedIndices), 1);
            selectedReactionIDs = strings(numel(selectedIndices), 1);

            for i = 1:numel(selectedIndices)
                substrate = substrateList(selectedIndices(i));
                reactionID = string( ...
                    model.findSubstrateRxnIDFromMetaboliteIrrev( ...
                    substrate));

                if ~isscalar(reactionID) || ismissing(reactionID) || ...
                        strlength(reactionID) == 0
                    error( ...
                        "OpenMebius2:" + ...
                        "EffluxPerturbationProfileFactory:" + ...
                        "InvalidReactionID", ...
                        "The model returned an invalid efflux reaction " + ...
                        "ID for substrate: %s.", ...
                        substrate);
                end

                reactionIndex = find(reactionNames == reactionID, 1);

                if isempty(reactionIndex)
                    error( ...
                        "OpenMebius2:" + ...
                        "EffluxPerturbationProfileFactory:" + ...
                        "ReactionNotFound", ...
                        "Selected efflux reaction was not found in the " + ...
                        "stoichiometry matrix: %s.", ...
                        reactionID);
                end

                reactionIndices(i) = reactionIndex;
                selectedReactionIDs(i) = reactionID;
            end

            profile = openmebius.mfa.EffluxPerturbationProfile( ...
                ReactionIDs = selectedReactionIDs, ...
                ReactionIndices = reactionIndices, ...
                ExperimentalValues = ...
                experimentalValues(selectedIndices), ...
                StandardDeviations = ...
                standardDeviations(selectedIndices));

        end % create

    end % methods

end % classdef
