classdef FluxBoundNormalizer
    % FLUXBOUNDNORMALIZER Repairs numerical bound inversions in tolerance.

    methods

        function [lowerBounds, upperBounds, adjustedMask] = normalize( ...
                ~, lowerBounds, upperBounds, options)

            arguments
                ~
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                options.AbsoluteTolerance (1, 1) double = 1e-12
                options.RelativeTolerance (1, 1) double = 1e-12
            end

            if numel(lowerBounds) ~= numel(upperBounds)
                error( ...
                    "OpenMebius2:FluxBoundNormalizer:DimensionMismatch", ...
                    "Lower and upper flux bounds must have the same size.");
            end

            if options.AbsoluteTolerance < 0 || ...
                    options.RelativeTolerance < 0 || ...
                    ~isfinite(options.AbsoluteTolerance) || ...
                    ~isfinite(options.RelativeTolerance)
                error( ...
                    "OpenMebius2:FluxBoundNormalizer:InvalidTolerance", ...
                    "Flux bound tolerances must be finite and nonnegative.");
            end

            scale = max( ...
                [ones(numel(lowerBounds), 1), ...
                abs(lowerBounds), abs(upperBounds)], ...
                [], ...
                2);
            tolerance = options.AbsoluteTolerance + ...
                options.RelativeTolerance .* scale;
            inversion = lowerBounds - upperBounds;
            adjustedMask = ...
                isfinite(inversion) & inversion > 0 & ...
                inversion <= tolerance;
            midpoint = ...
                (lowerBounds(adjustedMask) + ...
                upperBounds(adjustedMask)) ./ 2;
            lowerBounds(adjustedMask) = midpoint;
            upperBounds(adjustedMask) = midpoint;

        end % normalize

    end % methods

end % classdef
