classdef FluxVariabilitySolver
    % FLUXVARIABILITYSOLVER
    % Solves flux-wise linear programs without model or UI dependencies.

    properties (Access = private)
        BoundNormalizer openmebius.mfa.FluxBoundNormalizer
    end

    methods

        function obj = FluxVariabilitySolver(options)

            arguments
                options.BoundNormalizer (1, 1) ...
                    openmebius.mfa.FluxBoundNormalizer = ...
                    openmebius.mfa.FluxBoundNormalizer()
            end

            obj.BoundNormalizer = options.BoundNormalizer;

        end % constructor

        function result = solve( ...
                obj, ...
                equalityMatrix, ...
                equalityRightHandSide, ...
                lowerBounds, ...
                upperBounds, ...
                reverseCounterpartIndices)

            arguments
                obj
                equalityMatrix double
                equalityRightHandSide (:, 1) double
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                reverseCounterpartIndices (:, 1) double
            end

            numFlux = size(equalityMatrix, 2);
            openmebius.mfa.FluxVariabilitySolver.validateDimensions( ...
                equalityMatrix, ...
                equalityRightHandSide, ...
                lowerBounds, ...
                upperBounds, ...
                reverseCounterpartIndices);

            fluxUpperBounds = nan(numFlux, 1);
            fluxLowerBounds = nan(numFlux, 1);
            exitFlag = 0;
            errorMessage = "";
            linearOptions = optimoptions( ...
                @linprog, ...
                "Display", "off", ...
                "Algorithm", "dual-simplex-highs");

            for iFlux = 1:numFlux
                objective = zeros(numFlux, 1);
                objective(iFlux) = 1;

                [~, minimumValue, exitFlag] = linprog( ...
                    objective, ...
                    [], ...
                    [], ...
                    equalityMatrix, ...
                    equalityRightHandSide, ...
                    lowerBounds, ...
                    upperBounds, ...
                    linearOptions);

                if exitFlag < 0
                    errorMessage = ...
                        openmebius.mfa.FluxVariabilitySolver ...
                        .errorMessage(exitFlag);
                    break
                end

                fluxLowerBounds(iFlux) = minimumValue;
                [~, maximumValue] = linprog( ...
                    -objective, ...
                    [], ...
                    [], ...
                    equalityMatrix, ...
                    equalityRightHandSide, ...
                    lowerBounds, ...
                    upperBounds, ...
                    linearOptions);
                fluxUpperBounds(iFlux) = -maximumValue;

                counterpartIndex = reverseCounterpartIndices(iFlux);

                if ~isnan(counterpartIndex)
                    fluxLowerBounds(iFlux) = ...
                        -fluxUpperBounds(counterpartIndex);
                    fluxUpperBounds(iFlux) = ...
                        -fluxLowerBounds(counterpartIndex);
                    fluxLowerBounds(iFlux) = fluxLowerBounds(iFlux) / 2;
                    fluxUpperBounds(iFlux) = fluxUpperBounds(iFlux) / 2;
                    fluxLowerBounds(counterpartIndex) = ...
                        -fluxUpperBounds(iFlux);
                    fluxUpperBounds(counterpartIndex) = ...
                        -fluxLowerBounds(iFlux);
                end
            end

            [fluxLowerBounds, fluxUpperBounds] = ...
                obj.BoundNormalizer.normalize( ...
                fluxLowerBounds, fluxUpperBounds);

            result = openmebius.mfa.FluxVariabilityResult( ...
                UpperBounds = fluxUpperBounds, ...
                LowerBounds = fluxLowerBounds, ...
                ExitFlag = exitFlag, ...
                ErrorMessage = errorMessage);

        end % solve

    end % methods

    methods (Static, Access = private)

        function validateDimensions( ...
                equalityMatrix, ...
                equalityRightHandSide, ...
                lowerBounds, ...
                upperBounds, ...
                reverseCounterpartIndices)

            numFlux = size(equalityMatrix, 2);

            if size(equalityMatrix, 1) ~= numel(equalityRightHandSide)
                error( ...
                    "OpenMebius2:FVA:EqualityDimensionMismatch", ...
                    "The equality matrix and right-hand side must have equal row counts.");
            end

            if numFlux == 0 || numel(lowerBounds) ~= numFlux || ...
                    numel(upperBounds) ~= numFlux
                error( ...
                    "OpenMebius2:FVA:BoundaryDimensionMismatch", ...
                    "Each flux must have one lower and one upper boundary.");
            end

            if any(lowerBounds > upperBounds)
                error( ...
                    "OpenMebius2:FVA:InvalidBoundary", ...
                    "Flux lower boundaries must not exceed upper boundaries.");
            end

            if numel(reverseCounterpartIndices) ~= numFlux
                error( ...
                    "OpenMebius2:FVA:ReverseIndexDimensionMismatch", ...
                    "Each flux must have one reverse counterpart index or NaN.");
            end

            isInvalidIndex = ~isnan(reverseCounterpartIndices) & ...
                (~isfinite(reverseCounterpartIndices) | ...
                reverseCounterpartIndices < 1 | ...
                reverseCounterpartIndices > numFlux | ...
                fix(reverseCounterpartIndices) ~= reverseCounterpartIndices);

            if any(isInvalidIndex)
                error( ...
                    "OpenMebius2:FVA:InvalidReverseIndex", ...
                    "Reverse counterpart indices must reference an existing flux.");
            end

        end % validateDimensions

        function msg = errorMessage(exitFlag)

            switch exitFlag
                case -2
                    msg = "FVA error. No feasible point was found.";
                case -3
                    msg = "FVA error. Problem is unbounded.";
                case -4
                    msg = "FVA error. NaN value was encountered during execution of the algorithm.";
                case -5
                    msg = "FVA error. Both primal and dual problems are infeasible.";
                case -6
                    msg = "FVA error. Search direction became too small. No further progress could be made.";
                case -7
                    msg = "FVA error. Solver lost feasibility.";
                otherwise
                    msg = "Unknown error.";
            end

        end % errorMessage

    end % methods (Static, Access = private)

end % classdef
