classdef FluxVariabilityProblemFactory
    % FLUXVARIABILITYPROBLEMFACTORY
    % Builds FVA matrices, bounds, and reverse-reaction mappings.

    properties (SetAccess = private)
        ConstraintBuilder
    end

    methods

        function obj = FluxVariabilityProblemFactory(options)

            arguments
                options.ConstraintBuilder = ...
                    openmebius.mfa.MFAConstraintBuilder()
            end

            obj.ConstraintBuilder = options.ConstraintBuilder;

        end % constructor

        function problem = create( ...
                obj, model, rightHandSide, maximumEfflux, ...
                substrateList, freeEffluxMask, options)

            arguments
                obj (1, 1) ...
                    openmebius.mfa.FluxVariabilityProblemFactory
                model
                rightHandSide (:, 1) double
                maximumEfflux double
                substrateList
                freeEffluxMask
                options.UseCustomBounds (1, 1) logical = false
                options.LowerBounds double = []
                options.UpperBounds double = []
                options.FreeGrowthRate (1, 1) logical = false
            end

            stoichiometry = model.getSBefore();
            fluxCount = size(stoichiometry, 2);
            rowCount = size(stoichiometry, 1);
            usedDefaultMaximumEfflux = isempty(maximumEfflux) || ...
                ~isscalar(maximumEfflux) || ...
                ~isfinite(maximumEfflux) || ...
                maximumEfflux <= 0;

            if usedDefaultMaximumEfflux
                maximumEfflux = 1000;
            end

            lowerBounds = repmat( ...
                -maximumEfflux * 1000, fluxCount, 1);
            upperBounds = repmat( ...
                maximumEfflux * 1000, fluxCount, 1);

            if options.UseCustomBounds
                lowerBounds = options.LowerBounds(:);
                upperBounds = options.UpperBounds(:);

                if isscalar(lowerBounds)
                    lowerBounds = repmat(lowerBounds, fluxCount, 1);
                end

                if isscalar(upperBounds)
                    upperBounds = repmat(upperBounds, fluxCount, 1);
                end

                if numel(lowerBounds) ~= fluxCount || ...
                        numel(upperBounds) ~= fluxCount
                    error( ...
                        "OpenMebius2:FluxVariabilityProblemFactory:" + ...
                        "CustomBoundsDimensionMismatch", ...
                        "Custom FVA bounds must match the flux count.");
                end

            end

            reversibleIndices = model.getIdxRev();
            irreversibleMask = ...
                ~ismember((1:fluxCount).', reversibleIndices(:));
            lowerBounds(irreversibleMask) = max( ...
                lowerBounds(irreversibleMask), 0);

            if numel(rightHandSide) < rowCount
                error( ...
                    "OpenMebius2:FluxVariabilityProblemFactory:" + ...
                    "RightHandSideDimensionMismatch", ...
                    "The MFA right-hand side does not contain all FVA " + ...
                    "constraint rows.");
            end

            equalityRightHandSide = rightHandSide(1:rowCount);
            reactionNames = string( ...
                stoichiometry.Properties.VariableNames);
            reverseMask = endsWith(reactionNames, "_rev");
            stoichiometry{:, reverseMask} = 0;
            freeRowMask = obj.ConstraintBuilder ...
                .effluxFreeConstraintRowMask( ...
                model, ...
                stoichiometry, ...
                substrateList, ...
                freeEffluxMask, ...
                FreeGrowthRate = options.FreeGrowthRate);
            freeConstraintIDs = string( ...
                stoichiometry.Properties.RowNames(freeRowMask));
            equalityMatrix = table2array(stoichiometry);
            equalityMatrix(freeRowMask, :) = [];
            equalityRightHandSide(freeRowMask) = [];
            reverseCounterpartIndices = nan(fluxCount, 1);

            for reverseIndex = reshape(find(reverseMask), 1, [])
                counterpartIndex = model.findCounterReaction( ...
                    reactionNames(reverseIndex));

                if ~isscalar(counterpartIndex) || ...
                        ~isfinite(counterpartIndex) || ...
                        counterpartIndex < 1 || ...
                        counterpartIndex > fluxCount || ...
                        fix(counterpartIndex) ~= counterpartIndex
                    error( ...
                        "OpenMebius2:FluxVariabilityProblemFactory:" + ...
                        "InvalidReverseCounterpart", ...
                        "Each reverse reaction must reference one existing " + ...
                        "counterpart flux.");
                end

                reverseCounterpartIndices(reverseIndex) = ...
                    counterpartIndex;
            end

            problem = openmebius.mfa.FluxVariabilityProblem( ...
                EqualityMatrix = equalityMatrix, ...
                EqualityRightHandSide = equalityRightHandSide, ...
                LowerBounds = lowerBounds, ...
                UpperBounds = upperBounds, ...
                ReverseCounterpartIndices = ...
                reverseCounterpartIndices, ...
                UsedDefaultMaximumEfflux = ...
                usedDefaultMaximumEfflux, ...
                MaximumEfflux = maximumEfflux, ...
                FreeConstraintIDs = freeConstraintIDs);

        end % create

    end % methods

end % classdef
