classdef FluxVariabilityWorkflow
    % FLUXVARIABILITYWORKFLOW
    % Builds and solves one flux variability analysis problem.

    properties (SetAccess = private)
        ConstraintBuilder
        ProblemFactory
        Solver
    end

    methods

        function obj = FluxVariabilityWorkflow(options)

            arguments
                options.ConstraintBuilder = ...
                    openmebius.mfa.MFAConstraintBuilder()
                options.ProblemFactory = []
                options.Solver = ...
                    openmebius.mfa.FluxVariabilitySolver()
            end

            obj.ConstraintBuilder = options.ConstraintBuilder;
            obj.ProblemFactory = options.ProblemFactory;

            if isempty(obj.ProblemFactory)
                obj.ProblemFactory = ...
                    openmebius.mfa.FluxVariabilityProblemFactory( ...
                    ConstraintBuilder = obj.ConstraintBuilder);
            end

            obj.Solver = options.Solver;

        end % constructor

        function result = run( ...
                obj, model, growthRate, substrateList, efflux, ...
                freeEffluxMask, options)

            arguments
                obj (1, 1) openmebius.mfa.FluxVariabilityWorkflow
                model
                growthRate (1, 1) double
                substrateList
                efflux (:, 1) double
                freeEffluxMask
                options.UseCustomBounds (1, 1) logical = false
                options.LowerBounds double = []
                options.UpperBounds double = []
                options.FreeGrowthRate (1, 1) logical = false
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            rightHandSide = obj.ConstraintBuilder ...
                .buildRightHandSide( ...
                model, growthRate, substrateList, efflux);
            problem = obj.ProblemFactory.create( ...
                model, ...
                rightHandSide, ...
                max(efflux), ...
                substrateList, ...
                freeEffluxMask, ...
                UseCustomBounds = options.UseCustomBounds, ...
                LowerBounds = options.LowerBounds, ...
                UpperBounds = options.UpperBounds, ...
                FreeGrowthRate = options.FreeGrowthRate);

            if problem.UsedDefaultMaximumEfflux
                message = "Maximum efflux is not set or non-positive. " + ...
                    "Using default value: " + ...
                    string(problem.MaximumEfflux) + ".";
                options.MessageReporter("warning", message);
            end

            if ~isempty(problem.FreeConstraintIDs)

                if options.FreeGrowthRate
                    message = "FVA will not fix perturbed constraints: " + ...
                        strjoin(problem.FreeConstraintIDs, ", ") + ".";
                else
                    message = "FVA will not fix efflux-free reactions: " + ...
                        strjoin(problem.FreeConstraintIDs, ", ") + ".";
                end

                options.MessageReporter("info", message);
            end

            solverResult = obj.Solver.solve( ...
                problem.EqualityMatrix, ...
                problem.EqualityRightHandSide, ...
                problem.LowerBounds, ...
                problem.UpperBounds, ...
                problem.ReverseCounterpartIndices);

            if solverResult.IsError
                options.MessageReporter( ...
                    "error", solverResult.ErrorMessage);
            end

            result = openmebius.mfa.FluxVariabilityWorkflowResult( ...
                RightHandSide = rightHandSide, ...
                Problem = problem, ...
                UpperBounds = solverResult.UpperBounds, ...
                LowerBounds = solverResult.LowerBounds, ...
                ExitFlag = solverResult.ExitFlag, ...
                ErrorMessage = solverResult.ErrorMessage, ...
                IsError = solverResult.IsError);

        end % run

    end % methods

end % classdef
