classdef GridSearchConfidenceIntervalSolver

    methods

        function result = solve( ...
                ~, ...
                problem, ...
                bestFlux, ...
                baseRightHandSide, ...
                settings, ...
                evaluationFunction, ...
                reversibleReactionIndices, ...
                options ...
            )

            arguments
                ~
                problem
                bestFlux (:, 1) double
                baseRightHandSide (:, 1) double
                settings (1, 1) openmebius.mfa ...
                    .GridSearchConfidenceIntervalSettings
                evaluationFunction (1, 1) function_handle
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end % arguments

            error( ...
                "OpenMebius:GridSearchConfidenceIntervalSolver:NotImplemented", ...
            "Grid search confidence interval solver is not implemented yet.");

        end % solve

    end % methods

end % classdef
