classdef GridSearchConfidenceIntervalSolver

    methods

        function result = solve( ...
                ~, ...
                problem, ...
                bestFlux, ...
                baseRightHandSide, ...
                settings, ...
                evaluationFunction, ...
                reversibleReactionIndices, ...
                options ...
            )

            arguments
                ~
                problem (1, 1) openmebius.mfa.MFAProblem
                bestFlux (:, 1) double
                baseRightHandSide (:, 1) double
                settings (1, 1) openmebius.mfa ...
                    .GridSearchConfidenceIntervalSettings
                evaluationFunction (1, 1) function_handle
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.ProfileFluxIndices (:, 1) double = zeros(0, 1)
                options.ObjectiveThreshold (1, 1) double ...
                    {mustBeFinite, mustBeNonnegative}
                options.InitialIndependentValues double = []
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            startedAt = tic;
            report = options.MessageReporter;

            [forwardBest, forwardLower, forwardUpper] = ...
                openmebius.mfa.GridSearchConfidenceIntervalSolver ...
                .forwardFluxData( ...
                problem, bestFlux, reversibleReactionIndices);

            profileIndices = options.ProfileFluxIndices;

            if isempty(profileIndices)
                profileIndices = (1:numel(forwardBest)).';
            end

            openmebius.mfa.GridSearchConfidenceIntervalSolver ...
                .validateProfileIndices( ...
                profileIndices, numel(forwardBest));

            initialValues = options.InitialIndependentValues;

            if isempty(initialValues)
                initialValues = ...
                    problem.extractIndependentValues(baseRightHandSide);
            end

            profileCount = numel(profileIndices);
            fixedCells = cell(profileCount, 1);
            objectiveCells = cell(profileCount, 1);
            canceled = false;

            report( ...
                "info", ...
                "Calculating grid-search profiles for " + ...
                string(profileCount) + " fluxes.");

            if settings.ExecutionMode.isParallel()

                parfor profileNumber = 1:profileCount
                    fluxIndex = profileIndices(profileNumber);

                    [fixedCells{profileNumber}, ...
                         objectiveCells{profileNumber}] = ...
                        openmebius.mfa ...
                        .GridSearchConfidenceIntervalSolver ...
                        .evaluateProfile( ...
                        problem, ...
                        baseRightHandSide, ...
                        settings, ...
                        evaluationFunction, ...
                        reversibleReactionIndices, ...
                        fluxIndex, ...
                        forwardBest(fluxIndex), ...
                        forwardLower(fluxIndex), ...
                        forwardUpper(fluxIndex), ...
                        initialValues, ...
                        @() false);
                end

                canceled = logical(options.CancellationRequested());

            else

                for profileNumber = 1:profileCount

                    if logical(options.CancellationRequested())
                        canceled = true;
                        break
                    end

                    fluxIndex = profileIndices(profileNumber);

                    report( ...
                        "info", ...
                        "Grid-search profile: " + ...
                        string(profileNumber) + "/" + ...
                        string(profileCount));

                    [fixedCells{profileNumber}, ...
                         objectiveCells{profileNumber}] = ...
                        openmebius.mfa ...
                        .GridSearchConfidenceIntervalSolver ...
                        .evaluateProfile( ...
                        problem, ...
                        baseRightHandSide, ...
                        settings, ...
                        evaluationFunction, ...
                        reversibleReactionIndices, ...
                        fluxIndex, ...
                        forwardBest(fluxIndex), ...
                        forwardLower(fluxIndex), ...
                        forwardUpper(fluxIndex), ...
                        initialValues, ...
                        options.CancellationRequested);
                end

            end

            completed = ~cellfun(@isempty, fixedCells);
            profileIndices = profileIndices(completed);
            fixedCells = fixedCells(completed);
            objectiveCells = objectiveCells(completed);

            fixedFluxValues = cat(1, fixedCells{:});
            objectiveValues = cat(1, objectiveCells{:});
            minimumObjectives = min( ...
                objectiveValues, [], 3, "omitnan");

            lowerBounds = nan(numel(profileIndices), 1);
            upperBounds = nan(numel(profileIndices), 1);

            for profileNumber = 1:numel(profileIndices)
                fluxIndex = profileIndices(profileNumber);
                targets = fixedFluxValues(profileNumber, :, 1);

                [lowerBounds(profileNumber), ...
                     upperBounds(profileNumber)] = ...
                    openmebius.mfa ...
                    .GridSearchConfidenceIntervalSolver ...
                    .estimateBounds( ...
                    targets(:), ...
                    minimumObjectives(profileNumber, :).', ...
                    forwardBest(fluxIndex), ...
                    options.ObjectiveThreshold);
            end

            profileData = openmebius.mfa.GridSearchProfileData( ...
                FluxIndices = profileIndices, ...
                FixedFluxValues = fixedFluxValues, ...
                MinimumSumOfSquares = objectiveValues);

            result = openmebius.mfa ...
                .GridSearchConfidenceIntervalResult( ...
                LowerBounds = lowerBounds, ...
                UpperBounds = upperBounds, ...
                ProfileData = profileData, ...
                ElapsedTime = toc(startedAt), ...
                IsCanceled = canceled);

        end % method solve

    end % methods

    methods (Static, Access = private)

        function [fixedValues, objectives] = evaluateProfile( ...
                problem, ...
                baseRightHandSide, ...
                settings, ...
                evaluationFunction, ...
                reversiblePairs, ...
                fluxIndex, ...
                bestValue, ...
                lowerBound, ...
                upperBound, ...
                initialCandidates, ...
                cancellationRequested ...
            )

            targets = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver.buildTargets( ...
                bestValue, lowerBound, upperBound, settings);

            pointCount = numel(targets);
            trialCount = settings.IterationCount;
            fixedValues = repmat( ...
                reshape(targets, 1, pointCount, 1), ...
                1, 1, trialCount);
            objectives = nan(1, pointCount, trialCount);

            fluxWeights = openmebius.mfa ...
                .GridSearchConfidenceIntervalSolver.profileWeights( ...
                size(problem.Stoichiometry, 2), ...
                fluxIndex, ...
                reversiblePairs);

            candidateCount = size(initialCandidates, 2);

            for point = 1:pointCount

                if logical(cancellationRequested())
                    return
                end

                [equalityMatrix, equalityRightHandSide] = ...
                    problem.fixedFluxEqualities( ...
                    fluxWeights, ...
                    targets(point), ...
                    BaseRightHandSide = baseRightHandSide);

                for trial = 1:trialCount
                    candidate = initialCandidates( ...
                        :, mod(trial - 1, candidateCount) + 1);

                    iterationResult = evaluationFunction( ...
                        equalityMatrix, ...
                        equalityRightHandSide, ...
                        candidate);

                    if ~isa(iterationResult, ...
                        "openmebius.mfa.MFAIterationResult") || ...
                            iterationResult.IsError || ...
                            ~isfinite(iterationResult.ObjectiveValue)
                        continue
                    end

                    objectives(1, point, trial) = ...
                        iterationResult.ObjectiveValue;
                end

            end

        end % method evaluateProfile

        function targets = buildTargets( ...
                bestValue, lowerBound, upperBound, settings)

            count = settings.PointCount;
            lowerCount = floor((count - 1) / 2);
            upperCount = count - lowerCount - 1;

            if settings.IntervalMode.isAutomatic()
                lowerTargets = linspace( ...
                    lowerBound, bestValue, lowerCount + 1);
                upperTargets = linspace( ...
                    bestValue, upperBound, upperCount + 1);

                lowerTargets(end) = [];
                upperTargets(1) = [];
                targets = [lowerTargets, bestValue, upperTargets];
            else
                offsets = -lowerCount:upperCount;
                targets = bestValue + offsets * settings.Delta;
                targets = min(max(targets, lowerBound), upperBound);
            end

            targets = sort(targets);

        end % method buildTargets

        function weights = profileWeights( ...
                fullFluxCount, outputIndex, reversiblePairs)

            reverseIndices = reversiblePairs(:, 2);
            retainedIndices = setdiff( ...
                (1:fullFluxCount).', reverseIndices, "stable");
            expandedIndex = retainedIndices(outputIndex);
            weights = zeros(fullFluxCount, 1);
            weights(expandedIndex) = 1;

            pair = find( ...
                reversiblePairs(:, 1) == expandedIndex, 1);

            if ~isempty(pair)
                weights(reversiblePairs(pair, 2)) = -1;
            end

        end % method profileWeights

        function [lowerBound, upperBound] = estimateBounds( ...
                targets, objectives, bestValue, threshold)

            [targets, order] = sort(targets);
            objectives = objectives(order);
            accepted = isfinite(objectives) & ...
                objectives <= threshold;
            [~, center] = min(abs(targets - bestValue));

            if ~accepted(center)
                lowerBound = NaN;
                upperBound = NaN;
                return
            end

            first = center;
            last = center;

            while first > 1 && accepted(first - 1)
                first = first - 1;
            end

            while last < numel(targets) && accepted(last + 1)
                last = last + 1;
            end

            lowerBound = targets(first);
            upperBound = targets(last);

            if first > 1 && isfinite(objectives(first - 1))
                lowerBound = openmebius.mfa ...
                    .GridSearchConfidenceIntervalSolver.interpolateCrossing( ...
                    targets(first - 1), objectives(first - 1), ...
                    targets(first), objectives(first), threshold);
            end

            if last < numel(targets) && ...
                    isfinite(objectives(last + 1))
                upperBound = openmebius.mfa ...
                    .GridSearchConfidenceIntervalSolver.interpolateCrossing( ...
                    targets(last), objectives(last), ...
                    targets(last + 1), objectives(last + 1), ...
                    threshold);
            end

        end % method estimateBounds

        function value = interpolateCrossing( ...
                x1, y1, x2, y2, threshold)

            if y1 == y2
                value = x2;
                return
            end

            value = x1 + ...
                (threshold - y1) * (x2 - x1) / (y2 - y1);
            value = min(max(value, min(x1, x2)), max(x1, x2));

        end % method interpolateCrossing

        function [best, lower, upper] = forwardFluxData( ...
                problem, bestFlux, reversiblePairs)

            best = openmebius.mfa.ReversibleFluxMapper.mapFlux( ...
                bestFlux, reversiblePairs);
            [lower, upper] = ...
                openmebius.mfa.ReversibleFluxMapper.mapBounds( ...
                problem.LowerBounds, ...
                problem.UpperBounds, ...
                reversiblePairs);

        end % method forwardFluxData

        function validateProfileIndices(indices, fluxCount)

            if isempty(indices) || ...
                    any(~isfinite(indices)) || ...
                    any(indices < 1) || ...
                    any(indices > fluxCount) || ...
                    any(indices ~= fix(indices)) || ...
                    numel(unique(indices)) ~= numel(indices)
                error( ...
                    "OpenMebius2:GridSearchCI:" + ...
                    "InvalidProfileFluxIndices", ...
                "Profile flux indices must be unique valid integers.");
            end

        end % method validateProfileIndices

    end % methods (Static, Access = private)

end % classdef
