classdef InitialFluxWorkflow
    % INITIALFLUXWORKFLOW
    % Creates, samples, scores, and orders feasible initial fluxes.

    properties (SetAccess = private)
        ProblemFactory
        PointGenerator
        FitStatistics
        MDVPredictor
        SeedBoundsPolicy
    end

    methods

        function obj = InitialFluxWorkflow(options)

            arguments
                options.ProblemFactory = ...
                    openmebius.mfa.MFAProblemFactory()
                options.PointGenerator = ...
                    openmebius.mfa.InitialPointGenerator()
                options.FitStatistics = ...
                    openmebius.mfa.MFAFitStatistics()
                options.MDVPredictor = ...
                    openmebius.mfa.SteadyStateMDVPredictor()
                options.SeedBoundsPolicy = ...
                    openmebius.mfa.InitialFluxSeedBoundsPolicy()
            end

            obj.ProblemFactory = options.ProblemFactory;
            obj.PointGenerator = options.PointGenerator;
            obj.FitStatistics = options.FitStatistics;
            obj.MDVPredictor = options.MDVPredictor;
            obj.SeedBoundsPolicy = options.SeedBoundsPolicy;

        end

        function result = run(obj, input, options)

            arguments
                obj (1, 1) openmebius.mfa.InitialFluxWorkflow
                input (1, 1) openmebius.mfa.InitialFluxWorkflowInput
                options.Method (1, 1) string ...
                    {mustBeMember(options.Method, ...
                     ["random", "hit-and-run"])} = "hit-and-run"
                options.ForNextSuggestion (1, 1) logical = false
                options.IterationRate (1, 1) double = 100
                options.MaxSamplingAttempts (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 2
                options.IterationsPerBatch (1, 1) double = 1e5
                options.BurnIn (1, 1) double = 2000
                options.Thinning (1, 1) double = 10
                options.MaxTime (1, 1) double = 3600
                options.Seed (1, 1) double = 0
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            report = options.MessageReporter;
            report("info", "Calculating initial flux distribution...");

            try
                optimizationProblem = obj.ProblemFactory.create( ...
                    input.Model.getS(), ...
                    input.Model.getSType(), ...
                    input.RightHandSide, ...
                    input.LowerBounds, ...
                    input.UpperBounds);
            catch ME
                message = "Failed to create the MFA problem. " + ...
                    string(ME.message);
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message);
                return
            end

            try

                if input.Settings.RestrictFreeEffluxSeeds
                    [seedLowerBounds, seedUpperBounds] = ...
                        obj.SeedBoundsPolicy.apply( ...
                        input.LowerBounds, ...
                        input.UpperBounds, ...
                        input.EffluxProfile, ...
                        SigmaMultiplier = input.Settings ...
                        .FreeEffluxSeedSigmaMultiplier, ...
                        ReversibleReactionIndices = ...
                        input.ReversibleReactionIndices);
                else
                    seedLowerBounds = input.LowerBounds;
                    seedUpperBounds = input.UpperBounds;
                end

                samplingProblem = obj.ProblemFactory.create( ...
                    input.Model.getS(), ...
                    input.Model.getSType(), ...
                    input.RightHandSide, ...
                    seedLowerBounds, ...
                    seedUpperBounds);
                openmebius.mfa.InitialFluxWorkflow.reportSeedBounds( ...
                    report, ...
                    input, ...
                    seedLowerBounds, ...
                    seedUpperBounds);
            catch ME
                message = "Failed to create the initial-flux " + ...
                    "sampling problem. " + string(ME.message);
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult ...
                    .failure( ...
                    message, ...
                    Problem = optimizationProblem);
                return
            end

            requiredCount = ...
                input.IterationCount * options.IterationRate;
            scoringEMUs = input.scoringSubstrateEMUs( ...
                options.ForNextSuggestion);
            arrangedMDV = input.arrangeMDV(numel(scoringEMUs));
            fluxes = zeros(size(input.Model.getS(), 2), 0);
            rightHandSides = zeros(numel(input.RightHandSide), 0);
            objectiveValues = zeros(1, 0);
            validCount = 0;
            samplingAttempt = 0;
            randomStream = RandStream.getGlobalStream();

            if options.Seed ~= 0
                randomStream = RandStream( ...
                    "mt19937ar", "Seed", options.Seed);
            end

            while validCount < input.IterationCount && ...
                    samplingAttempt < options.MaxSamplingAttempts
                samplingAttempt = samplingAttempt + 1;

                if samplingAttempt > 1
                    report( ...
                        "warning", ...
                        "Initial flux distribution contains only " + ...
                        string(validCount) + " valid candidates; " + ...
                        "sampling initial points again (attempt " + ...
                        string(samplingAttempt) + "/" + ...
                        string(options.MaxSamplingAttempts) + ").");
                end

                switch options.Method
                    case "random"
                        generated = obj.PointGenerator.generateRandom( ...
                            samplingProblem, ...
                            requiredCount, ...
                            IterationsPerBatch = ...
                            options.IterationsPerBatch, ...
                            MaxTime = options.MaxTime, ...
                            CancellationRequested = ...
                            options.CancellationRequested, ...
                            ProgressReporter = @(count, elapsed) ...
                            openmebius.mfa.InitialFluxWorkflow ...
                            .reportRandomProgress( ...
                            report, count, elapsed));
                        completionMessage = ...
                            "Initial flux distribution calculated " + ...
                            "randomly.";
                    case "hit-and-run"
                        generated = ...
                            obj.PointGenerator.generateHitAndRun( ...
                            samplingProblem, ...
                            requiredCount, ...
                            input.IterationCount, ...
                            BurnIn = options.BurnIn, ...
                            Thinning = options.Thinning, ...
                            MaxTime = options.MaxTime, ...
                            RandomStream = randomStream, ...
                            CancellationRequested = ...
                            options.CancellationRequested, ...
                            ProgressReporter = report);
                        completionMessage = ...
                            "Initial flux distribution calculated " + ...
                            "using Hit-and-Run.";
                end

                candidateFluxes = [fluxes, generated.Fluxes];
                candidateRightHandSides = [ ...
                                               rightHandSides, generated.RightHandSides];

                if generated.IsCanceled || ...
                        logical(options.CancellationRequested())
                    report( ...
                        "info", ...
                    "Initial flux distribution calculation canceled.");
                    result = openmebius.mfa ...
                        .InitialFluxWorkflowResult.canceled( ...
                        Problem = optimizationProblem, ...
                        Fluxes = candidateFluxes, ...
                        RightHandSides = candidateRightHandSides);
                    return
                end

                if generated.IsError
                    message = generated.ErrorMessage;

                    if strlength(message) == 0
                        message = "Initial point generation failed.";
                    end

                    report("error", message);
                    result = openmebius.mfa ...
                        .InitialFluxWorkflowResult.failure( ...
                        message, ...
                        Problem = optimizationProblem, ...
                        Fluxes = candidateFluxes, ...
                        RightHandSides = candidateRightHandSides);
                    return
                end

                if isempty(generated.Fluxes)
                    message = ...
                        "Initial point generation produced no candidates.";
                    report("error", message);
                    result = openmebius.mfa ...
                        .InitialFluxWorkflowResult.failure( ...
                        message, ...
                        Problem = optimizationProblem, ...
                        Fluxes = candidateFluxes, ...
                        RightHandSides = candidateRightHandSides);
                    return
                end

                openmebius.mfa.InitialFluxWorkflow ...
                    .reportSeedDistribution( ...
                    report, input.EffluxProfile, generated.Fluxes);
                report("info", completionMessage);

                evaluation = obj.FitStatistics.evaluateFluxes( ...
                    generated.Fluxes, ...
                    arrangedMDV, ...
                    input.ExperimentalData.FragmentMask, ...
                    @(flux) obj.MDVPredictor.predictLinearized( ...
                    input.Model, flux, scoringEMUs), ...
                    input.EffluxPenalty, ...
                    CancellationRequested = ...
                    options.CancellationRequested);

                if evaluation.IsCanceled || ...
                        logical(options.CancellationRequested())
                    report( ...
                        "info", ...
                    "Initial flux distribution calculation canceled.");
                    result = openmebius.mfa ...
                        .InitialFluxWorkflowResult.canceled( ...
                        Problem = optimizationProblem, ...
                        Fluxes = candidateFluxes, ...
                        RightHandSides = candidateRightHandSides);
                    return
                end

                order = evaluation.Order;
                fluxes = [ ...
                              fluxes, generated.Fluxes(:, order)]; %#ok<AGROW>
                rightHandSides = [ ...
                                      rightHandSides, ...
                                      generated.RightHandSides(:, order)]; %#ok<AGROW>
                objectiveValues = [ ...
                                       objectiveValues, ...
                                       evaluation.ObjectiveValues]; %#ok<AGROW>
                validCount = validCount + evaluation.ValidCount;
                report( ...
                    "info", ...
                    "Number of valid flux distributions: " + ...
                    string(validCount));
            end

            [objectiveValues, order] = sort( ...
                objectiveValues, "ascend");
            orderedFluxes = fluxes(:, order);
            orderedRightHandSides = rightHandSides(:, order);

            if validCount < input.IterationCount
                message = "Initial flux distribution contains too few " + ...
                    "valid candidates. Required: " + ...
                    string(input.IterationCount) + ", valid: " + ...
                    string(validCount) + ".";
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message, ...
                    Problem = optimizationProblem, ...
                    Fluxes = orderedFluxes, ...
                    RightHandSides = orderedRightHandSides);
                return
            end

            result = openmebius.mfa.InitialFluxWorkflowResult.success( ...
                Problem = optimizationProblem, ...
                Fluxes = orderedFluxes, ...
                RightHandSides = orderedRightHandSides, ...
                ObjectiveValues = objectiveValues);

        end

    end

    methods (Static, Access = private)

        function reportSeedBounds( ...
                report, input, seedLowerBounds, seedUpperBounds)

            profile = input.EffluxProfile;

            if profile.MeasurementCount == 0
                return
            end

            if ~input.Settings.RestrictFreeEffluxSeeds
                report( ...
                    "info", ...
                    "Free-efflux seed restriction is disabled; " + ...
                "physical flux bounds will be used.");
                return
            end

            sigmaMultiplier = input.Settings ...
                .FreeEffluxSeedSigmaMultiplier;

            for i = 1:profile.MeasurementCount
                fluxIndex = profile.ReactionIndices(i);
                reactionID = profile.ReactionIDs(i);

                if strlength(reactionID) == 0
                    reactionID = "<unknown>";
                end

                mean = compose( ...
                    "%.2f", ...
                    openmebius.mfa.InitialFluxWorkflow.formatNumber( ...
                    profile.ExperimentalValues(i)) ...
                );
                sd = compose( ...
                    "%.2f", ...
                    openmebius.mfa.InitialFluxWorkflow.formatNumber( ...
                    profile.StandardDeviations(i)) ...
                );
                sigma = compose( ...
                    "%.0f", ...
                    openmebius.mfa.InitialFluxWorkflow.formatNumber( ...
                    sigmaMultiplier) ...
                );
                bounds = compose( ...
                    "[%.2f, %.2f]", ...
                    openmebius.mfa.InitialFluxWorkflow.formatNumber( ...
                    seedLowerBounds(fluxIndex)), ...
                    openmebius.mfa.InitialFluxWorkflow.formatNumber( ...
                    seedUpperBounds(fluxIndex)) ...
                );

                message = "Perturbate efflux: " + ...
                    "reaction=" + reactionID + ...
                    ", mean=" + mean + ...
                    ", sd=" + sd + ...
                    ", sigma=" + sigma + ...
                    ", samplingBounds=" + bounds + ".";

                report("info", message);
            end

        end

        function reportSeedDistribution(report, profile, fluxes)

            for i = 1:profile.MeasurementCount
                fluxIndex = profile.ReactionIndices(i);
                values = fluxes(fluxIndex, :);
                reactionID = profile.ReactionIDs(i);

                if strlength(reactionID) == 0
                    reactionID = "<unknown>";
                end

                message = "Initial free-efflux seed distribution: " + ...
                    "reaction=" + reactionID + ...
                    ", fluxIndex=" + string(fluxIndex) + ...
                    ", count=" + string(numel(values)) + ...
                    ", minimum=" + openmebius.mfa ...
                    .InitialFluxWorkflow.formatNumber(min(values)) + ...
                    ", median=" + openmebius.mfa ...
                    .InitialFluxWorkflow.formatNumber(median(values)) + ...
                    ", maximum=" + openmebius.mfa ...
                    .InitialFluxWorkflow.formatNumber(max(values)) + ...
                    ".";
                report("info", message);
            end

        end

        function value = formatNumber(value)

            value = string(sprintf('%.15g', value));

        end

        function reportRandomProgress(report, count, elapsedSeconds)

            elapsed = string(seconds(elapsedSeconds), "hh:mm:ss");
            report( ...
                "info", ...
                "Calculating initial flux distribution randomly" + ...
                " (Elapsed time: " + elapsed + ", " + ...
                "Found " + string(count) + ...
            " feasible flux distributions)");

        end

    end

end
