classdef InitialFluxWorkflow
    % INITIALFLUXWORKFLOW
    % Creates, samples, scores, and orders feasible initial fluxes.

    properties (SetAccess = private)
        ProblemFactory
        PointGenerator
        FitStatistics
        MDVPredictor
        SeedBoundsPolicy
    end

    methods

        function obj = InitialFluxWorkflow(options)

            arguments
                options.ProblemFactory = ...
                    openmebius.mfa.MFAProblemFactory()
                options.PointGenerator = ...
                    openmebius.mfa.InitialPointGenerator()
                options.FitStatistics = ...
                    openmebius.mfa.MFAFitStatistics()
                options.MDVPredictor = ...
                    openmebius.mfa.SteadyStateMDVPredictor()
                options.SeedBoundsPolicy = ...
                    openmebius.mfa.InitialFluxSeedBoundsPolicy()
            end

            obj.ProblemFactory = options.ProblemFactory;
            obj.PointGenerator = options.PointGenerator;
            obj.FitStatistics = options.FitStatistics;
            obj.MDVPredictor = options.MDVPredictor;
            obj.SeedBoundsPolicy = options.SeedBoundsPolicy;

        end

        function result = run(obj, input, options)

            arguments
                obj (1, 1) openmebius.mfa.InitialFluxWorkflow
                input (1, 1) openmebius.mfa.InitialFluxWorkflowInput
                options.Method (1, 1) string ...
                    {mustBeMember(options.Method, ...
                     ["random", "hit-and-run"])} = "hit-and-run"
                options.ForNextSuggestion (1, 1) logical = false
                options.IterationRate (1, 1) double = 100
                options.IterationsPerBatch (1, 1) double = 1e5
                options.BurnIn (1, 1) double = 2000
                options.Thinning (1, 1) double = 10
                options.MaxTime (1, 1) double = 3600
                options.Seed (1, 1) double = 0
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            report = options.MessageReporter;
            report("info", "Calculating initial flux distribution...");

            try
                optimizationProblem = obj.ProblemFactory.create( ...
                    input.Model.getS(), ...
                    input.Model.getSType(), ...
                    input.RightHandSide, ...
                    input.LowerBounds, ...
                    input.UpperBounds);
            catch ME
                message = "Failed to create the MFA problem. " + ...
                    string(ME.message);
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message);
                return
            end

            try
                [seedLowerBounds, seedUpperBounds] = ...
                    obj.SeedBoundsPolicy.apply( ...
                    input.LowerBounds, ...
                    input.UpperBounds, ...
                    input.EffluxProfile, ...
                    ReversibleReactionIndices = ...
                    input.ReversibleReactionIndices);
                samplingProblem = obj.ProblemFactory.create( ...
                    input.Model.getS(), ...
                    input.Model.getSType(), ...
                    input.RightHandSide, ...
                    seedLowerBounds, ...
                    seedUpperBounds);
            catch ME
                message = "Failed to create the initial-flux " + ...
                    "sampling problem. " + string(ME.message);
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult ...
                    .failure( ...
                    message, ...
                    Problem = optimizationProblem);
                return
            end

            requiredCount = ...
                input.IterationCount * options.IterationRate;

            switch options.Method
                case "random"
                    generated = obj.PointGenerator.generateRandom( ...
                        samplingProblem, ...
                        requiredCount, ...
                        IterationsPerBatch = ...
                        options.IterationsPerBatch, ...
                        MaxTime = options.MaxTime, ...
                        CancellationRequested = ...
                        options.CancellationRequested, ...
                        ProgressReporter = @(count, elapsed) ...
                        openmebius.mfa.InitialFluxWorkflow ...
                        .reportRandomProgress( ...
                        report, count, elapsed));
                    completionMessage = ...
                        "Initial flux distribution calculated randomly.";
                case "hit-and-run"
                    randomStream = RandStream.getGlobalStream();

                    if options.Seed ~= 0
                        randomStream = RandStream( ...
                            "mt19937ar", "Seed", options.Seed);
                    end

                    generated = obj.PointGenerator.generateHitAndRun( ...
                        samplingProblem, ...
                        requiredCount, ...
                        input.IterationCount, ...
                        BurnIn = options.BurnIn, ...
                        Thinning = options.Thinning, ...
                        MaxTime = options.MaxTime, ...
                        RandomStream = randomStream, ...
                        CancellationRequested = ...
                        options.CancellationRequested, ...
                        ProgressReporter = report);
                    completionMessage = ...
                        "Initial flux distribution calculated using " + ...
                        "Hit-and-Run.";
            end

            if generated.IsCanceled || ...
                    logical(options.CancellationRequested())
                report( ...
                    "info", ...
                "Initial flux distribution calculation canceled.");
                result = openmebius.mfa.InitialFluxWorkflowResult.canceled( ...
                    Problem = optimizationProblem, ...
                    Fluxes = generated.Fluxes, ...
                    RightHandSides = generated.RightHandSides);
                return
            end

            if generated.IsError
                message = generated.ErrorMessage;

                if strlength(message) == 0
                    message = "Initial point generation failed.";
                end

                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message, ...
                    Problem = optimizationProblem, ...
                    Fluxes = generated.Fluxes, ...
                    RightHandSides = generated.RightHandSides);
                return
            end

            if isempty(generated.Fluxes)
                message = ...
                    "Initial point generation produced no candidates.";
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message, ...
                    Problem = optimizationProblem, ...
                    Fluxes = generated.Fluxes, ...
                    RightHandSides = generated.RightHandSides);
                return
            end

            report("info", completionMessage);

            scoringEMUs = input.scoringSubstrateEMUs( ...
                options.ForNextSuggestion);
            arrangedMDV = input.arrangeMDV(numel(scoringEMUs));
            evaluation = obj.FitStatistics.evaluateFluxes( ...
                generated.Fluxes, ...
                arrangedMDV, ...
                input.ExperimentalData.FragmentMask, ...
                @(flux) obj.MDVPredictor.predictLinearized( ...
                input.Model, flux, scoringEMUs), ...
                input.EffluxPenalty, ...
                CancellationRequested = ...
                options.CancellationRequested);
            report( ...
                "info", ...
                "Number of valid flux distributions: " + ...
                string(evaluation.ValidCount));

            if evaluation.IsCanceled || ...
                    logical(options.CancellationRequested())
                report( ...
                    "info", ...
                "Initial flux distribution calculation canceled.");
                result = openmebius.mfa.InitialFluxWorkflowResult.canceled( ...
                    Problem = optimizationProblem, ...
                    Fluxes = generated.Fluxes, ...
                    RightHandSides = generated.RightHandSides);
                return
            end

            order = evaluation.Order;
            orderedFluxes = generated.Fluxes(:, order);
            orderedRightHandSides = ...
                generated.RightHandSides(:, order);

            if evaluation.ValidCount < input.IterationCount
                message = "Initial flux distribution contains too few " + ...
                    "valid candidates. Required: " + ...
                    string(input.IterationCount) + ", valid: " + ...
                    string(evaluation.ValidCount) + ".";
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message, ...
                    Problem = optimizationProblem, ...
                    Fluxes = orderedFluxes, ...
                    RightHandSides = orderedRightHandSides);
                return
            end

            result = openmebius.mfa.InitialFluxWorkflowResult.success( ...
                Problem = optimizationProblem, ...
                Fluxes = orderedFluxes, ...
                RightHandSides = orderedRightHandSides, ...
                ObjectiveValues = evaluation.ObjectiveValues);

        end

    end

    methods (Static, Access = private)

        function reportRandomProgress(report, count, elapsedSeconds)

            elapsed = string(seconds(elapsedSeconds), "hh:mm:ss");
            report( ...
                "info", ...
                "Calculating initial flux distribution randomly" + ...
                " (Elapsed time: " + elapsed + ", " + ...
                "Found " + string(count) + ...
            " feasible flux distributions)");

        end

    end

end
