classdef InitialPointGenerator
    % INITIALPOINTGENERATOR
    % Generates feasible points without model, UI, or persistence access.

    methods

        function result = generateRandom( ...
                ~, ...
                problem, ...
                requiredCount, ...
                options)

            arguments
                ~
                problem (1, 1) openmebius.mfa.MFAProblem
                requiredCount (1, 1) double ...
                    {mustBeInteger, mustBePositive}
                options.IterationsPerBatch (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 1e5
                options.MaxTime (1, 1) double ...
                    {mustBePositive} = 3600
                options.Epsilon (1, 1) double ...
                    {mustBeNonnegative} = 1e-6
                options.RandomStream = RandStream.getGlobalStream()
                options.CancellationRequested (1, 1) function_handle = ...
                    @() false
                options.ProgressReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            fluxes = nan(size(problem.Stoichiometry, 2), 0);
            rightHandSides = nan(numel(problem.RightHandSide), 0);
            isCanceled = false;
            startedAt = tic;

            while toc(startedAt) <= options.MaxTime
                [batchRightHandSides, batchFluxes] = ...
                    openmebius.mfa.InitialPointGenerator.generateRandomBatch( ...
                    problem, ...
                    options.IterationsPerBatch, ...
                    options.Epsilon, ...
                    options.RandomStream);
                generatedCount = size(fluxes, 2) + size(batchFluxes, 2);
                options.ProgressReporter(generatedCount, toc(startedAt));

                if options.CancellationRequested()
                    isCanceled = true;
                    break
                end

                fluxes = [fluxes, batchFluxes]; %#ok<AGROW>
                rightHandSides = [rightHandSides, batchRightHandSides]; %#ok<AGROW>

                if generatedCount >= requiredCount
                    break
                end

            end

            result = openmebius.mfa.InitialPointResult( ...
                Fluxes = fluxes, ...
                RightHandSides = rightHandSides, ...
                IsCanceled = isCanceled);

        end % generateRandom

        function result = generateHitAndRun( ...
                obj, ...
                problem, ...
                requiredCount, ...
                minimumCount, ...
                options)

            arguments
                obj
                problem (1, 1) openmebius.mfa.MFAProblem
                requiredCount (1, 1) double ...
                    {mustBeInteger, mustBePositive}
                minimumCount (1, 1) double ...
                    {mustBeInteger, mustBePositive}
                options.BurnIn (1, 1) double ...
                    {mustBeInteger, mustBeNonnegative} = 2000
                options.Thinning (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 10
                options.MaxStep (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 1e7
                options.MaxTime (1, 1) double ...
                    {mustBePositive} = 3600
                options.FeasibilityTolerance (1, 1) double ...
                    {mustBeNonnegative} = 1e-8
                options.EqualityTolerance (1, 1) double ...
                    {mustBeNonnegative} = 1e-9
                options.MinimumDirectionNorm (1, 1) double ...
                    {mustBeNonnegative} = 1e-12
                options.MaxInvalidRange (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 100000
                options.MaxZeroWidth (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 100000
                options.RandomStream = RandStream.getGlobalStream()
                options.CancellationRequested (1, 1) function_handle = ...
                    @() false
                options.ProgressReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            if minimumCount > requiredCount
                error( ...
                    "OpenMebius2:InitialPoint:InvalidSampleCount", ...
                    "The minimum sample count must not exceed the target count.");
            end

            stoichiometry = problem.Stoichiometry;
            rightHandSide = problem.RightHandSide;
            upperBounds = problem.UpperBounds;
            lowerBounds = problem.LowerBounds;
            independentIndices = problem.IndependentIndices;
            fluxCount = size(stoichiometry, 2);
            independentCount = numel(independentIndices);
            fluxes = nan(fluxCount, 0);
            rightHandSides = nan(numel(rightHandSide), 0);
            fixedRightHandSide = rightHandSide;
            fixedRightHandSide(independentIndices) = 0;
            baseFlux = stoichiometry \ fixedRightHandSide;
            independentBasis = zeros(fluxCount, independentCount);
            independentBasis(sub2ind( ...
                [fluxCount, independentCount], ...
                independentIndices, ...
                (1:independentCount)')) = 1;
            fluxBasis = stoichiometry \ independentBasis;
            [additionalInequalityMatrix, ...
                additionalInequalityRightHandSide] = ...
                problem.fluxInequalitiesInIndependentSpace();
            scaleFlux = max(1, max(abs([upperBounds; lowerBounds])));
            equalityTolerance = max( ...
                options.EqualityTolerance, ...
                1e-6 * scaleFlux);
            fixedFluxMask = ...
                abs(upperBounds - lowerBounds) <= equalityTolerance;
            equalityMatrix = fluxBasis(fixedFluxMask, :);
            equalityRightHandSide = ...
                lowerBounds(fixedFluxMask) - baseFlux(fixedFluxMask);
            inequalityMatrix = [ ...
                fluxBasis; -fluxBasis; ...
                additionalInequalityMatrix];
            inequalityRightHandSide = [ ...
                upperBounds - baseFlux
                - (lowerBounds - baseFlux)
                additionalInequalityRightHandSide];
            linearOptions = optimoptions( ...
                @linprog, ...
                "Display", "off", ...
                "Algorithm", "dual-simplex-highs");

            try
                [initialIndependent, ~, exitFlag] = linprog( ...
                    zeros(independentCount, 1), ...
                    inequalityMatrix, ...
                    inequalityRightHandSide, ...
                    equalityMatrix, ...
                    equalityRightHandSide, ...
                    [], ...
                    [], ...
                    linearOptions);
            catch ME
                errorMessage = ...
                    "Hit-and-Run: failed to solve initial LP. " + ...
                    string(ME.message);
                options.ProgressReporter("error", errorMessage);
                result = ...
                    openmebius.mfa.InitialPointGenerator.failedResult( ...
                    fluxes, rightHandSides, errorMessage, false);
                return
            end

            if exitFlag ~= 1 || isempty(initialIndependent)
                errorMessage = ...
                    "Hit-and-Run: no feasible initial point was found. " + ...
                    "exitflag=" + string(exitFlag);
                options.ProgressReporter("error", errorMessage);
                result = ...
                    openmebius.mfa.InitialPointGenerator.failedResult( ...
                    fluxes, rightHandSides, errorMessage, false);
                return
            end

            initialFlux = baseFlux + fluxBasis * initialIndependent;

            if ~all(initialFlux >= ...
                    lowerBounds - options.FeasibilityTolerance & ...
                    initialFlux <= ...
                    upperBounds + options.FeasibilityTolerance) || ...
                    ~openmebius.mfa.InitialPointGenerator ...
                    .satisfiesFluxInequalities( ...
                    problem, initialFlux, ...
                    options.FeasibilityTolerance)
                errorMessage = "Hit-and-Run: initial point is infeasible.";
                options.ProgressReporter("error", errorMessage);
                result = ...
                    openmebius.mfa.InitialPointGenerator.failedResult( ...
                    fluxes, rightHandSides, errorMessage, false);
                return
            end

            if isempty(equalityMatrix)
                nullBasis = eye(independentCount);
            else
                nullBasis = null(equalityMatrix, "r");
            end

            generatorDimension = size(nullBasis, 2);
            options.ProgressReporter( ...
                "debug", ...
                "Hit-and-Run: z-space dimension=" + ...
                string(generatorDimension) + "/" + ...
                string(independentCount) + ...
                ", equality flux count=" + ...
                string(sum(fixedFluxMask)) + ...
                ", initial min(v-LB)=" + ...
                string(min(initialFlux - lowerBounds)) + ...
                ", initial min(UB-v)=" + ...
                string(min(upperBounds - initialFlux)) + ".");

            if generatorDimension == 0
                options.ProgressReporter( ...
                    "warning", ...
                    "Hit-and-Run: z-space dimension is zero. " + ...
                    "Reusing the feasible point.");
                fluxes = repmat(initialFlux, 1, requiredCount);
                rightHandSides = repmat(rightHandSide, 1, requiredCount);
                rightHandSides(independentIndices, :) = ...
                    repmat(initialIndependent, 1, requiredCount);
                result = openmebius.mfa.InitialPointResult( ...
                    Fluxes = fluxes, ...
                    RightHandSides = rightHandSides);
                return
            end

            generatorMatrix = fluxBasis * nullBasis;
            [currentPoint, isInitialPointFound, initialPointMessage] = ...
                obj.findInitialZ( ...
                lowerBounds, ...
                upperBounds, ...
                initialFlux, ...
                generatorMatrix, ...
                FeasibilityTolerance = options.FeasibilityTolerance, ...
                EqualityTolerance = equalityTolerance, ...
                MinimumMargin = 1e-10, ...
                InequalityMatrix = problem.FluxInequalityMatrix, ...
                InequalityRightHandSide = ...
                problem.FluxInequalityRightHandSide);

            if ~isInitialPointFound
                errorMessage = ...
                    "Hit-and-Run: failed to find initial z. " + ...
                    initialPointMessage;
                options.ProgressReporter("error", errorMessage);
                result = ...
                    openmebius.mfa.InitialPointGenerator.failedResult( ...
                    fluxes, rightHandSides, errorMessage, false);
                return
            end

            currentFlux = initialFlux + generatorMatrix * currentPoint;
            options.ProgressReporter( ...
                "debug", ...
                "Hit-and-Run: initial z found. min(v-LB)=" + ...
                string(min(currentFlux - lowerBounds)) + ...
                ", min(UB-v)=" + ...
                string(min(upperBounds - currentFlux)) + ".");
            savedCount = 0;
            step = 0;
            invalidRangeStreak = 0;
            zeroWidthStreak = 0;
            startedAt = tic;
            options.ProgressReporter( ...
                "debug", ...
                "Hit-and-Run: start in z-space (target=" + ...
                string(requiredCount) + ").");

            while toc(startedAt) <= options.MaxTime && ...
                    ~options.CancellationRequested() && ...
                    savedCount < requiredCount
                step = step + 1;

                if step > options.MaxStep
                    break
                end

                direction = randn( ...
                    options.RandomStream, ...
                    generatorDimension, ...
                    1);
                directionNorm = norm(direction);

                if directionNorm < options.MinimumDirectionNorm
                    continue
                end

                direction = direction / directionNorm;
                [minimumStep, maximumStep, isRangeValid] = obj.stepRange( ...
                    lowerBounds, ...
                    upperBounds, ...
                    initialFlux, ...
                    generatorMatrix, ...
                    currentPoint, ...
                    direction, ...
                    FeasibilityTolerance = options.FeasibilityTolerance, ...
                    InequalityMatrix = problem.FluxInequalityMatrix, ...
                    InequalityRightHandSide = ...
                    problem.FluxInequalityRightHandSide);

                if ~isRangeValid || ~isfinite(minimumStep) || ...
                        ~isfinite(maximumStep)
                    invalidRangeStreak = invalidRangeStreak + 1;

                    if invalidRangeStreak == 1 || ...
                            mod(invalidRangeStreak, 10000) == 0
                        currentFlux = ...
                            initialFlux + generatorMatrix * currentPoint;
                        options.ProgressReporter( ...
                            "warning", ...
                            "Hit-and-Run: invalid range. streak=" + ...
                            string(invalidRangeStreak) + ...
                            ", step=" + string(step) + ...
                            ", min(v-LB)=" + ...
                            string(min(currentFlux - lowerBounds)) + ...
                            ", min(UB-v)=" + ...
                            string(min(upperBounds - currentFlux)) + ".");
                    end

                    if invalidRangeStreak >= options.MaxInvalidRange
                        errorMessage = ...
                            "Hit-and-Run: too many invalid ranges.";
                        options.ProgressReporter("error", errorMessage);
                        result = ...
                            openmebius.mfa.InitialPointGenerator ...
                            .failedResult( ...
                            fluxes, rightHandSides, errorMessage, false);
                        return
                    end

                    continue
                end

                if maximumStep <= minimumStep
                    zeroWidthStreak = zeroWidthStreak + 1;

                    if zeroWidthStreak == 1 || ...
                            mod(zeroWidthStreak, 10000) == 0
                        currentFlux = ...
                            initialFlux + generatorMatrix * currentPoint;
                        options.ProgressReporter( ...
                            "warning", ...
                            "Hit-and-Run: zero-width range. streak=" + ...
                            string(zeroWidthStreak) + ...
                            ", step=" + string(step) + ...
                            ", min(v-LB)=" + ...
                            string(min(currentFlux - lowerBounds)) + ...
                            ", min(UB-v)=" + ...
                            string(min(upperBounds - currentFlux)) + ".");
                    end

                    if zeroWidthStreak >= options.MaxZeroWidth
                        errorMessage = ...
                            "Hit-and-Run: too many zero-width ranges. " + ...
                            "Feasible region may be lower-dimensional " + ...
                            "than z-space.";
                        options.ProgressReporter("error", errorMessage);
                        result = ...
                            openmebius.mfa.InitialPointGenerator ...
                            .failedResult( ...
                            fluxes, rightHandSides, errorMessage, false);
                        return
                    end

                    continue
                end

                invalidRangeStreak = 0;
                zeroWidthStreak = 0;
                distance = minimumStep + ...
                    (maximumStep - minimumStep) * ...
                    rand(options.RandomStream);
                currentPoint = currentPoint + distance * direction;

                if step <= options.BurnIn || ...
                        mod(step - options.BurnIn, options.Thinning) ~= 0
                    continue
                end

                independentFlux = ...
                    initialIndependent + nullBasis * currentPoint;
                candidateFlux = ...
                    baseFlux + fluxBasis * independentFlux;

                if ~all(candidateFlux >= ...
                        lowerBounds - options.FeasibilityTolerance & ...
                        candidateFlux <= ...
                        upperBounds + options.FeasibilityTolerance) || ...
                        ~openmebius.mfa.InitialPointGenerator ...
                        .satisfiesFluxInequalities( ...
                        problem, candidateFlux, ...
                        options.FeasibilityTolerance)
                    continue
                end

                candidateRightHandSide = rightHandSide;
                candidateRightHandSide(independentIndices) = ...
                    independentFlux;
                rightHandSides = [ ...
                    rightHandSides, candidateRightHandSide]; %#ok<AGROW>
                fluxes = [fluxes, candidateFlux]; %#ok<AGROW>
                savedCount = savedCount + 1;

            end

            if options.CancellationRequested()
                errorMessage = "Hit-and-Run: canceled.";
                options.ProgressReporter("info", errorMessage);
                result = ...
                    openmebius.mfa.InitialPointGenerator.failedResult( ...
                    fluxes, rightHandSides, errorMessage, true);
                return
            end

            if savedCount < minimumCount
                errorMessage = ...
                    "Hit-and-Run: insufficient samples. Required at least " + ...
                    string(minimumCount) + ", but generated " + ...
                    string(savedCount) + ".";
                options.ProgressReporter("error", errorMessage);
                result = ...
                    openmebius.mfa.InitialPointGenerator.failedResult( ...
                    fluxes, rightHandSides, errorMessage, false);
                return
            end

            if savedCount < requiredCount
                options.ProgressReporter( ...
                    "warning", ...
                    "Hit-and-Run: generated fewer samples than target. " + ...
                    "Target=" + string(requiredCount) + ...
                    ", generated=" + string(savedCount) + ".");
            end

            options.ProgressReporter( ...
                "debug", ...
                "Hit-and-Run: finished. generated=" + ...
                string(savedCount) + ...
                ", elapsed=" + ...
                string(seconds(toc(startedAt)), "hh:mm:ss") + ".");

            result = openmebius.mfa.InitialPointResult( ...
                Fluxes = fluxes, ...
                RightHandSides = rightHandSides);

        end % generateHitAndRun

        function [z, isSuccess, msg] = findInitialZ( ...
                ~, lowerBounds, upperBounds, baseFlux, generatorMatrix, options)

            arguments
                ~
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                baseFlux (:, 1) double
                generatorMatrix (:, :) double
                options.FeasibilityTolerance (1, 1) double = 1e-8
                options.EqualityTolerance (1, 1) double = 1e-8
                options.MinimumMargin (1, 1) double = 1e-10
                options.InequalityMatrix double = []
                options.InequalityRightHandSide (:, 1) double = ...
                    zeros(0, 1)
            end

            isSuccess = false;
            z = [];
            dimension = size(generatorMatrix, 2);
            scaleFlux = max(1, max(abs([lowerBounds; upperBounds])));
            equalityTolerance = max( ...
                options.EqualityTolerance, ...
                1e-8 * scaleFlux);
            movableMask = ...
                abs(upperBounds - lowerBounds) > equalityTolerance;
            movableGenerator = generatorMatrix(movableMask, :);
            movableLowerBounds = lowerBounds(movableMask);
            movableUpperBounds = upperBounds(movableMask);
            movableBaseFlux = baseFlux(movableMask);

            openmebius.mfa.InitialPointGenerator ...
                .validateFluxInequalities( ...
                options.InequalityMatrix, ...
                options.InequalityRightHandSide, ...
                numel(baseFlux));

            if isempty(movableGenerator) && ...
                    isempty(options.InequalityMatrix)
                z = zeros(dimension, 1);
                isSuccess = true;
                msg = "No movable flux constraints.";
                return
            end

            movableCount = size(movableGenerator, 1);
            inequalityMatrix = [ ...
                movableGenerator, ones(movableCount, 1)
                -movableGenerator, ones(movableCount, 1)];
            inequalityRightHandSide = [ ...
                movableUpperBounds - movableBaseFlux
                - (movableLowerBounds - movableBaseFlux)];

            if ~isempty(options.InequalityMatrix)
                additionalGenerator = ...
                    options.InequalityMatrix * generatorMatrix;
                additionalRightHandSide = ...
                    options.InequalityRightHandSide - ...
                    options.InequalityMatrix * baseFlux;
                inequalityMatrix = [ ...
                    inequalityMatrix; ...
                    additionalGenerator, ...
                    ones(size(additionalGenerator, 1), 1)];
                inequalityRightHandSide = [ ...
                    inequalityRightHandSide; ...
                    additionalRightHandSide];
            end

            objective = [zeros(dimension, 1); -1];
            lowerVariableBounds = [-inf(dimension, 1); 0];
            upperVariableBounds = [inf(dimension, 1); inf];
            linearOptions = optimoptions( ...
                @linprog, ...
                "Display", "off", ...
                "Algorithm", "dual-simplex-highs");

            try
                [solution, ~, exitFlag] = linprog( ...
                    objective, ...
                    inequalityMatrix, ...
                    inequalityRightHandSide, ...
                    [], ...
                    [], ...
                    lowerVariableBounds, ...
                    upperVariableBounds, ...
                    linearOptions);
            catch ME
                msg = "Initial z LP exception: " + string(ME.message);
                return
            end

            if exitFlag ~= 1 || isempty(solution)
                msg = "Initial z LP failed. exitflag=" + string(exitFlag);
                return
            end

            z = solution(1:dimension);
            margin = solution(end);
            flux = baseFlux + generatorMatrix * z;

            if ~all(flux >= lowerBounds - options.FeasibilityTolerance & ...
                    flux <= upperBounds + options.FeasibilityTolerance) || ...
                    (~isempty(options.InequalityMatrix) && ...
                    any(options.InequalityMatrix * flux > ...
                    options.InequalityRightHandSide + ...
                    options.FeasibilityTolerance))
                msg = "Initial z is infeasible.";
                z = [];
                return
            end

            if margin <= options.MinimumMargin
                msg = "Initial z found on boundary. r=" + string(margin);
                isSuccess = true;
                return
            end

            msg = "Initial z found. r=" + string(margin) + ...
                ", movable constraint count=" + string(movableCount);
            isSuccess = true;

        end % findInitialZ

        function [minimumStep, maximumStep, isSuccess] = stepRange( ...
                ~, ...
                lowerBounds, ...
                upperBounds, ...
                baseFlux, ...
                generatorMatrix, ...
                currentPoint, ...
                direction, ...
                options)

            arguments
                ~
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                baseFlux (:, 1) double
                generatorMatrix (:, :) double
                currentPoint (:, 1) double
                direction (:, 1) double
                options.DirectionTolerance (1, 1) double = 1e-12
                options.FeasibilityTolerance (1, 1) double = 1e-8
                options.WidthTolerance (1, 1) double = 1e-12
                options.InequalityMatrix double = []
                options.InequalityRightHandSide (:, 1) double = ...
                    zeros(0, 1)
            end

            isSuccess = true;
            currentFlux = baseFlux + generatorMatrix * currentPoint;
            fluxDirection = generatorMatrix * direction;
            minimumStep = -inf;
            maximumStep = inf;

            openmebius.mfa.InitialPointGenerator ...
                .validateFluxInequalities( ...
                options.InequalityMatrix, ...
                options.InequalityRightHandSide, ...
                numel(baseFlux));

            for iFlux = 1:numel(currentFlux)

                if abs(fluxDirection(iFlux)) <= options.DirectionTolerance

                    if currentFlux(iFlux) < ...
                            lowerBounds(iFlux) - options.FeasibilityTolerance || ...
                            currentFlux(iFlux) > ...
                            upperBounds(iFlux) + options.FeasibilityTolerance
                        isSuccess = false;
                        minimumStep = NaN;
                        maximumStep = NaN;
                        return
                    end

                    continue
                end

                lowerStep = ...
                    (lowerBounds(iFlux) - currentFlux(iFlux)) / ...
                    fluxDirection(iFlux);
                upperStep = ...
                    (upperBounds(iFlux) - currentFlux(iFlux)) / ...
                    fluxDirection(iFlux);
                minimumStep = max( ...
                    minimumStep, ...
                    min(lowerStep, upperStep));
                maximumStep = min( ...
                    maximumStep, ...
                    max(lowerStep, upperStep));

                if maximumStep < minimumStep - options.WidthTolerance
                    isSuccess = false;
                    minimumStep = NaN;
                    maximumStep = NaN;
                    return
                end

            end

            for iConstraint = 1:size(options.InequalityMatrix, 1)
                currentValue = options.InequalityMatrix( ...
                    iConstraint, :) * currentFlux;
                directionValue = options.InequalityMatrix( ...
                    iConstraint, :) * fluxDirection;
                rightHandSide = ...
                    options.InequalityRightHandSide(iConstraint);

                if abs(directionValue) <= options.DirectionTolerance

                    if currentValue > ...
                            rightHandSide + options.FeasibilityTolerance
                        isSuccess = false;
                        minimumStep = NaN;
                        maximumStep = NaN;
                        return
                    end

                    continue
                end

                constraintStep = ...
                    (rightHandSide - currentValue) / directionValue;

                if directionValue > 0
                    maximumStep = min(maximumStep, constraintStep);
                else
                    minimumStep = max(minimumStep, constraintStep);
                end

                if maximumStep < minimumStep - options.WidthTolerance
                    isSuccess = false;
                    minimumStep = NaN;
                    maximumStep = NaN;
                    return
                end

            end

            if ~isfinite(minimumStep) || ~isfinite(maximumStep)
                isSuccess = false;
                minimumStep = NaN;
                maximumStep = NaN;
            end

        end % stepRange

    end % methods

    methods (Static, Access = private)

        function satisfies = satisfiesFluxInequalities( ...
                problem, flux, tolerance)

            satisfies = isempty(problem.FluxInequalityMatrix) || ...
                all(problem.FluxInequalityMatrix * flux <= ...
                problem.FluxInequalityRightHandSide + tolerance, ...
                'all');

        end

        function validateFluxInequalities( ...
                matrix, rightHandSide, fluxCount)

            if isempty(matrix) && isempty(rightHandSide)
                return
            end

            if size(matrix, 2) ~= fluxCount || ...
                    size(matrix, 1) ~= numel(rightHandSide)
                error( ...
                    "OpenMebius2:InitialPoint:" + ...
                    "InequalityDimensionMismatch", ...
                    "Flux inequalities must match the flux dimension.");
            end

        end

        function result = failedResult( ...
                fluxes, rightHandSides, errorMessage, isCanceled)

            result = openmebius.mfa.InitialPointResult( ...
                Fluxes = fluxes, ...
                RightHandSides = rightHandSides, ...
                IsCanceled = isCanceled, ...
                IsError = true, ...
                ErrorMessage = errorMessage);

        end % failedResult

        function [rightHandSides, fluxes] = generateRandomBatch( ...
                problem, ...
                iterations, ...
                epsilon, ...
                randomStream)

            fluxes = nan(size(problem.Stoichiometry, 2), 0);
            rightHandSides = nan(numel(problem.RightHandSide), 0);
            independentCount = nnz(problem.IndependentMask);
            lowerIndependentBounds = ...
                problem.LowerBounds(problem.BoundaryReactionMask);
            upperIndependentBounds = ...
                problem.UpperBounds(problem.BoundaryReactionMask);

            for iIteration = 1:iterations
                candidateRightHandSide = problem.RightHandSide;
                candidateRightHandSide( ...
                    problem.IndependentMask) = ...
                    rand(randomStream, independentCount, 1) .* ...
                    (upperIndependentBounds - lowerIndependentBounds) + ...
                    lowerIndependentBounds;
                candidateFlux = ...
                    problem.Stoichiometry \ candidateRightHandSide;

                if all(candidateFlux >= problem.LowerBounds - epsilon & ...
                        candidateFlux <= problem.UpperBounds + epsilon) && ...
                        openmebius.mfa.InitialPointGenerator ...
                        .satisfiesFluxInequalities( ...
                        problem, candidateFlux, epsilon)
                    fluxes = [fluxes, candidateFlux]; %#ok<AGROW>
                    rightHandSides = [ ...
                        rightHandSides, candidateRightHandSide]; %#ok<AGROW>
                end

            end

        end % generateRandomBatch

    end % methods (Static, Access = private)

end % classdef
