classdef InitialFluxWorkflow
    % INITIALFLUXWORKFLOW
    % Creates, samples, scores, and orders feasible initial fluxes.

    properties (SetAccess = private)
        ProblemFactory
        PointGenerator
        FitStatistics
    end

    methods

        function obj = InitialFluxWorkflow(options)

            arguments
                options.ProblemFactory = ...
                    openmebius.mfa.MFAProblemFactory()
                options.PointGenerator = ...
                    openmebius.mfa.InitialPointGenerator()
                options.FitStatistics = ...
                    openmebius.mfa.MFAFitStatistics()
            end

            obj.ProblemFactory = options.ProblemFactory;
            obj.PointGenerator = options.PointGenerator;
            obj.FitStatistics = options.FitStatistics;

        end

        function result = run( ...
                obj, model, config, rightHandSide, lowerBounds, ...
                upperBounds, substrateEMUs, experimentalData, ...
                optimizationMDV, fragmentMask, mdvPredictor, ...
                effluxPenalty, options)

            arguments
                obj (1, 1) openmebius.mfa.InitialFluxWorkflow
                model
                config
                rightHandSide (:, 1) double
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                substrateEMUs cell
                experimentalData (1, 1) ...
                    openmebius.mfa.MFAExperimentalData
                optimizationMDV double
                fragmentMask
                mdvPredictor
                effluxPenalty
                options.Method (1, 1) string ...
                    {mustBeMember(options.Method, ...
                    ["random", "hit-and-run"])} = "hit-and-run"
                options.ForNextSuggestion (1, 1) logical = false
                options.IterationRate (1, 1) double = 100
                options.IterationsPerBatch (1, 1) double = 1e5
                options.BurnIn (1, 1) double = 2000
                options.Thinning (1, 1) double = 10
                options.MaxTime (1, 1) double = 3600
                options.Seed (1, 1) double = 0
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            report = options.MessageReporter;
            report("info", "Calculating initial flux distribution...");

            try
                problem = obj.ProblemFactory.create( ...
                    model.getS(), ...
                    model.getSType(), ...
                    rightHandSide, ...
                    lowerBounds, ...
                    upperBounds);
            catch ME
                message = "Failed to create the MFA problem. " + ...
                    string(ME.message);
                report("error", message);
                result = openmebius.mfa.InitialFluxWorkflowResult( ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            requiredCount = config.iteration * options.IterationRate;
            switch options.Method
                case "random"
                    generated = obj.PointGenerator.generateRandom( ...
                        problem, ...
                        requiredCount, ...
                        IterationsPerBatch = ...
                        options.IterationsPerBatch, ...
                        MaxTime = options.MaxTime, ...
                        CancellationRequested = ...
                        options.CancellationRequested, ...
                        ProgressReporter = @(count, elapsed) ...
                        openmebius.mfa.InitialFluxWorkflow ...
                        .reportRandomProgress( ...
                        report, count, elapsed));
                    report( ...
                        "info", ...
                        "Initial flux distribution calculated randomly.");
                case "hit-and-run"
                    randomStream = RandStream.getGlobalStream();

                    if options.Seed ~= 0
                        randomStream = RandStream( ...
                            "mt19937ar", "Seed", options.Seed);
                    end

                    generated = obj.PointGenerator.generateHitAndRun( ...
                        problem, ...
                        requiredCount, ...
                        config.iteration, ...
                        BurnIn = options.BurnIn, ...
                        Thinning = options.Thinning, ...
                        MaxTime = options.MaxTime, ...
                        RandomStream = randomStream, ...
                        CancellationRequested = ...
                        options.CancellationRequested, ...
                        ProgressReporter = report);

                    if generated.IsError || generated.IsCanceled
                        result = ...
                            openmebius.mfa.InitialFluxWorkflowResult( ...
                            Problem = problem, ...
                            Fluxes = generated.Fluxes, ...
                            RightHandSides = ...
                            generated.RightHandSides, ...
                            IsCanceled = generated.IsCanceled, ...
                            IsError = true, ...
                            ErrorMessage = generated.ErrorMessage);
                        return
                    end

                    report( ...
                        "info", ...
                        "Initial flux distribution calculated using " + ...
                        "Hit-and-Run.");
            end

            isCanceled = generated.IsCanceled || ...
                logical(options.CancellationRequested());

            if isCanceled
                report( ...
                    "info", ...
                    "Initial flux distribution calculation canceled.");
            end

            scoringEMUs = substrateEMUs;

            if options.ForNextSuggestion
                scoringEMUs = substrateEMUs(1:end - 1);
            end

            arrangedMDV = experimentalData.arrangeMDV( ...
                optimizationMDV, ...
                ExperimentCount = numel(scoringEMUs));
            evaluation = obj.FitStatistics.evaluateFluxes( ...
                generated.Fluxes, ...
                arrangedMDV, ...
                fragmentMask, ...
                @(flux) mdvPredictor.predictLinearized( ...
                model, flux, scoringEMUs), ...
                effluxPenalty, ...
                CancellationRequested = ...
                options.CancellationRequested);
            report( ...
                "info", ...
                "Number of valid flux distributions: " + ...
                string(evaluation.ValidCount));
            order = evaluation.Order;
            result = openmebius.mfa.InitialFluxWorkflowResult( ...
                Problem = problem, ...
                Fluxes = generated.Fluxes(:, order), ...
                RightHandSides = ...
                generated.RightHandSides(:, order), ...
                ObjectiveValues = evaluation.ObjectiveValues, ...
                IsCanceled = isCanceled || evaluation.IsCanceled, ...
                IsError = isCanceled || evaluation.IsCanceled, ...
                ErrorMessage = generated.ErrorMessage);

        end

    end

    methods (Static, Access = private)

        function reportRandomProgress(report, count, elapsedSeconds)

            elapsed = string(seconds(elapsedSeconds), "hh:mm:ss");
            report( ...
                "info", ...
                "Calculating initial flux distribution randomly" + ...
                " (Elapsed time: " + elapsed + ", " + ...
                "Found " + string(count) + ...
                " feasible flux distributions)");

        end

    end

end
