classdef InitialFluxSeedBoundsPolicy
    % INITIALFLUXSEEDBOUNDSPOLICY
    % Restricts free-efflux bounds for initial-point sampling.

    methods

        function [seedLowerBounds, seedUpperBounds, ...
                      inequalityMatrix, inequalityRightHandSide, ...
                      measurementBounds] = apply( ...
            ~, physicalLowerBounds, physicalUpperBounds, ...
            profile, options)

        arguments
            ~
            physicalLowerBounds (:, 1) double
            physicalUpperBounds (:, 1) double
            profile (1, 1) ...
                openmebius.mfa.EffluxPerturbationProfile
            options.SigmaMultiplier (1, 1) double = 3
            options.ReversibleReactionIndices (:, 2) double = ...
                zeros(0, 2)
        end

        fluxCount = numel(physicalLowerBounds);

        if numel(physicalUpperBounds) ~= fluxCount
            error( ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
                "PhysicalDimensionMismatch", ...
                "Physical lower and upper bounds must have the " + ...
            "same length.");
        end

        if any(isnan(physicalLowerBounds)) || ...
                any(isnan(physicalUpperBounds)) || ...
                any(physicalLowerBounds > physicalUpperBounds)
            error( ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
                "InvalidPhysicalBounds", ...
            "Physical flux bounds must be ordered and not NaN.");
        end

        if any(profile.ReactionIndices > fluxCount)
            error( ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
                "InvalidReactionIndex", ...
                "Free-efflux reaction indices must identify " + ...
            "existing fluxes.");
        end

        reversibleIndices = options.ReversibleReactionIndices;

        if any(~isfinite(reversibleIndices), 'all') || ...
                any(reversibleIndices < 1, 'all') || ...
                any(reversibleIndices ~= ...
                fix(reversibleIndices), 'all') || ...
                any(reversibleIndices > fluxCount, 'all') || ...
                any(reversibleIndices(:, 1) == ...
                reversibleIndices(:, 2))
            error( ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
                "InvalidReversibleReactionIndices", ...
                "Reversible reaction pairs must identify two " + ...
            "different existing fluxes.");
        end

        if ~isfinite(options.SigmaMultiplier) || ...
                options.SigmaMultiplier <= 0
            error( ...
                "OpenMebius2:InitialFluxSeedBounds:" + ...
                "InvalidSigmaMultiplier", ...
                "The seed-bound sigma multiplier must be " + ...
            "positive and finite.");
        end

        seedLowerBounds = physicalLowerBounds;
        seedUpperBounds = physicalUpperBounds;
        inequalityMatrix = zeros(0, fluxCount);
        inequalityRightHandSide = zeros(0, 1);
        measurementBounds = nan(profile.MeasurementCount, 2);

        if profile.MeasurementCount == 0
            return
        end

        measurementLowerBounds = profile.ExperimentalValues - ...
            options.SigmaMultiplier .* profile.StandardDeviations;
        measurementUpperBounds = profile.ExperimentalValues + ...
            options.SigmaMultiplier .* profile.StandardDeviations;

        for i = 1:profile.MeasurementCount
            reactionIndex = profile.ReactionIndices(i);
            counterIndex = profile.CounterReactionIndices(i);

            if isnan(counterIndex)
                [pairIndex, pairColumn] = find( ...
                    reversibleIndices == reactionIndex, 1);

                if ~isempty(pairIndex)
                    counterIndex = reversibleIndices( ...
                        pairIndex, 3 - pairColumn);
                end

            end

            if ~isnan(counterIndex) && counterIndex > fluxCount
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidReactionIndex", ...
                    "Free-efflux counter-reaction indices must " + ...
                "identify existing fluxes.");
            end

            if isnan(counterIndex)
                lowerBound = max( ...
                    physicalLowerBounds(reactionIndex), ...
                    measurementLowerBounds(i));
                upperBound = min( ...
                    physicalUpperBounds(reactionIndex), ...
                    measurementUpperBounds(i));
                seedLowerBounds(reactionIndex) = lowerBound;
                seedUpperBounds(reactionIndex) = upperBound;
            else
                physicalNetLowerBound = ...
                    physicalLowerBounds(reactionIndex) - ...
                    physicalUpperBounds(counterIndex);
                physicalNetUpperBound = ...
                    physicalUpperBounds(reactionIndex) - ...
                    physicalLowerBounds(counterIndex);
                lowerBound = max( ...
                    physicalNetLowerBound, ...
                    measurementLowerBounds(i));
                upperBound = min( ...
                    physicalNetUpperBound, ...
                    measurementUpperBounds(i));
                weights = zeros(1, fluxCount);
                weights(reactionIndex) = 1;
                weights(counterIndex) = -1;
                inequalityMatrix = [ ...
                                        inequalityMatrix; weights; -weights]; %#ok<AGROW>
                inequalityRightHandSide = [ ...
                                               inequalityRightHandSide; ...
                                               upperBound; -lowerBound]; %#ok<AGROW>
            end

            if lowerBound > upperBound
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "EmptyIntersection", ...
                    "A free-efflux seed range does not intersect " + ...
                "its physical flux bounds.");
            end

            measurementBounds(i, :) = [lowerBound, upperBound];
        end

    end % apply

end % methods

end % classdef
