classdef InitialFluxSeedBoundsPolicy
    % INITIALFLUXSEEDBOUNDSPOLICY
    % Restricts free-efflux bounds for initial-point sampling.

    methods

        function [seedLowerBounds, seedUpperBounds] = apply( ...
                ~, physicalLowerBounds, physicalUpperBounds, ...
                reactionIndices, experimentalValues, ...
                standardDeviations, options)

            arguments
                ~
                physicalLowerBounds (:, 1) double
                physicalUpperBounds (:, 1) double
                reactionIndices (:, 1) double
                experimentalValues (:, 1) double
                standardDeviations (:, 1) double
                options.SigmaMultiplier (1, 1) double = 3
            end

            fluxCount = numel(physicalLowerBounds);
            measurementCount = numel(reactionIndices);

            if numel(physicalUpperBounds) ~= fluxCount
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "PhysicalDimensionMismatch", ...
                    "Physical lower and upper bounds must have the " + ...
                "same length.");
            end

            if any(isnan(physicalLowerBounds)) || ...
                    any(isnan(physicalUpperBounds)) || ...
                    any(physicalLowerBounds > physicalUpperBounds)
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidPhysicalBounds", ...
                "Physical flux bounds must be ordered and not NaN.");
            end

            if numel(experimentalValues) ~= measurementCount || ...
                    numel(standardDeviations) ~= measurementCount
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "MeasurementDimensionMismatch", ...
                    "Free-efflux indices, values, and standard " + ...
                "deviations must have the same length.");
            end

            if any(~isfinite(reactionIndices)) || ...
                    any(reactionIndices < 1) || ...
                    any(reactionIndices ~= fix(reactionIndices)) || ...
                    any(reactionIndices > fluxCount)
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidReactionIndex", ...
                    "Free-efflux reaction indices must identify " + ...
                "existing fluxes.");
            end

            if numel(unique(reactionIndices)) ~= measurementCount
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "DuplicateReactionIndex", ...
                "Each free-efflux reaction index must be unique.");
            end

            if any(~isfinite(experimentalValues))
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidExperimentalValue", ...
                "Free-efflux experimental values must be finite.");
            end

            if any(~isfinite(standardDeviations)) || ...
                    any(standardDeviations <= 0)
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidStandardDeviation", ...
                    "Free-efflux standard deviations must be " + ...
                "positive and finite.");
            end

            if ~isfinite(options.SigmaMultiplier) || ...
                    options.SigmaMultiplier <= 0
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidSigmaMultiplier", ...
                    "The seed-bound sigma multiplier must be " + ...
                "positive and finite.");
            end

            seedLowerBounds = physicalLowerBounds;
            seedUpperBounds = physicalUpperBounds;

            if measurementCount == 0
                return
            end

            measurementLowerBounds = experimentalValues - ...
                options.SigmaMultiplier .* standardDeviations;
            measurementUpperBounds = experimentalValues + ...
                options.SigmaMultiplier .* standardDeviations;

            seedLowerBounds(reactionIndices) = max( ...
                physicalLowerBounds(reactionIndices), ...
                measurementLowerBounds);
            seedUpperBounds(reactionIndices) = min( ...
                physicalUpperBounds(reactionIndices), ...
                measurementUpperBounds);

            if any(seedLowerBounds(reactionIndices) > ...
                    seedUpperBounds(reactionIndices))
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "EmptyIntersection", ...
                    "A free-efflux seed range does not intersect " + ...
                "its physical flux bounds.");
            end

        end % apply

    end % methods

end % classdef
