classdef InitialFluxSeedBoundsPolicy
    % INITIALFLUXSEEDBOUNDSPOLICY
    % Restricts free-efflux bounds for initial-point sampling.

    methods

        function [seedLowerBounds, seedUpperBounds] = apply( ...
                ~, physicalLowerBounds, physicalUpperBounds, ...
                profile, options)

            arguments
                ~
                physicalLowerBounds (:, 1) double
                physicalUpperBounds (:, 1) double
                profile (1, 1) ...
                    openmebius.mfa.EffluxPerturbationProfile
                options.SigmaMultiplier (1, 1) double = 3
                options.ReversibleReactionIndices (:, 2) double = ...
                    zeros(0, 2)
            end

            fluxCount = numel(physicalLowerBounds);

            if numel(physicalUpperBounds) ~= fluxCount
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "PhysicalDimensionMismatch", ...
                    "Physical lower and upper bounds must have the " + ...
                "same length.");
            end

            if any(isnan(physicalLowerBounds)) || ...
                    any(isnan(physicalUpperBounds)) || ...
                    any(physicalLowerBounds > physicalUpperBounds)
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidPhysicalBounds", ...
                "Physical flux bounds must be ordered and not NaN.");
            end

            if any(profile.ReactionIndices > fluxCount)
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidReactionIndex", ...
                    "Free-efflux reaction indices must identify " + ...
                "existing fluxes.");
            end

            reversibleIndices = options.ReversibleReactionIndices;

            if any(~isfinite(reversibleIndices), 'all') || ...
                    any(reversibleIndices < 1, 'all') || ...
                    any(reversibleIndices ~= ...
                    fix(reversibleIndices), 'all') || ...
                    any(reversibleIndices > fluxCount, 'all') || ...
                    any(reversibleIndices(:, 1) == ...
                    reversibleIndices(:, 2))
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidReversibleReactionIndices", ...
                    "Reversible reaction pairs must identify two " + ...
                "different existing fluxes.");
            end

            reversibleFluxIndices = reversibleIndices(:);

            if any(ismember( ...
                    profile.ReactionIndices, reversibleFluxIndices))
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "ReversibleEffluxNotSupported", ...
                    "Initial seed restriction for a reversible free " + ...
                "efflux requires net-flux inequality constraints.");
            end

            if ~isfinite(options.SigmaMultiplier) || ...
                    options.SigmaMultiplier <= 0
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "InvalidSigmaMultiplier", ...
                    "The seed-bound sigma multiplier must be " + ...
                "positive and finite.");
            end

            seedLowerBounds = physicalLowerBounds;
            seedUpperBounds = physicalUpperBounds;

            if profile.MeasurementCount == 0
                return
            end

            reactionIndices = profile.ReactionIndices;
            measurementLowerBounds = profile.ExperimentalValues - ...
                options.SigmaMultiplier .* profile.StandardDeviations;
            measurementUpperBounds = profile.ExperimentalValues + ...
                options.SigmaMultiplier .* profile.StandardDeviations;

            seedLowerBounds(reactionIndices) = max( ...
                physicalLowerBounds(reactionIndices), ...
                measurementLowerBounds);
            seedUpperBounds(reactionIndices) = min( ...
                physicalUpperBounds(reactionIndices), ...
                measurementUpperBounds);

            if any(seedLowerBounds(reactionIndices) > ...
                    seedUpperBounds(reactionIndices))
                error( ...
                    "OpenMebius2:InitialFluxSeedBounds:" + ...
                    "EmptyIntersection", ...
                    "A free-efflux seed range does not intersect " + ...
                "its physical flux bounds.");
            end

        end % apply

    end % methods

end % classdef
