classdef MFAExperimentalDataBuilder
    % MFAEXPERIMENTALDATABUILDER
    % Builds aligned experimental MDV values from model and experiment data.

    methods

        function result = build( ...
                ~, model, experiments, experimentList, selection)

            arguments
                ~
                model
                experiments
                experimentList
                selection (1, 1) openmebius.mfa.MSFragmentSelection
            end

            fragmentList = string(model.getTargetMetaboliteList());
            fragmentList = fragmentList(:);

            if isempty(fragmentList) || ...
                    numel(unique(fragmentList)) ~= numel(fragmentList)
                error( ...
                    "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                    "InvalidFragmentList", ...
                "Model target fragments must be nonempty and unique.");
            end

            [fragmentList, selectedFragmentList] = ...
                openmebius.mfa.MFAExperimentalDataBuilder ...
                .resolveFragmentSelection( ...
                model, fragmentList, selection);
            massCounts = ...
                openmebius.mfa.MFAExperimentalDataBuilder ...
                .resolveMassCounts(model, fragmentList);
            fragmentLabels = repelem(fragmentList, massCounts);
            fragmentMask = repelem( ...
                ismember(fragmentList, selectedFragmentList), ...
                massCounts);
            rowEnds = cumsum(massCounts);
            rowStarts = [1; rowEnds(1:end - 1) + 1];
            experimentCount = numel(experimentList);
            experimentalMDV = nan(rowEnds(end), experimentCount);

            for experimentIndex = 1:experimentCount
                mdvTable = experiments.getMDVBiomassTable( ...
                    experimentList(experimentIndex));
                variableNames = string( ...
                    mdvTable.Properties.VariableNames);

                for fragmentIndex = 1:numel(fragmentList)
                    tableIndex = find( ...
                        variableNames == fragmentList(fragmentIndex), ...
                        1, ...
                    "first");

                    if isempty(tableIndex)
                        continue;
                    end

                    values = mdvTable{:, tableIndex};
                    massCount = massCounts(fragmentIndex);

                    if ~isnumeric(values) || numel(values) < massCount
                        error( ...
                            "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                            "InvalidFragmentMDV", ...
                            "Experimental MDV values for fragment '%s' " + ...
                            "must be numeric and contain at least %d values.", ...
                            fragmentList(fragmentIndex), ...
                            massCount);
                    end

                    rows = rowStarts(fragmentIndex): ...
                        rowEnds(fragmentIndex);
                    experimentalMDV(rows, experimentIndex) = ...
                        double(values(1:massCount));
                end

            end

            result = openmebius.mfa.MFAExperimentalData( ...
                ExperimentalMDV = experimentalMDV, ...
                FragmentLabels = fragmentLabels, ...
                FragmentMask = fragmentMask);

        end % build

    end % methods

    methods (Static, Access = private)

        function [fragmentList, selectedFragmentList] = ...
                resolveFragmentSelection(model, fragmentList, selection)

            if selection.Mode.usesModelSelection()
                msTable = model.getMSTable();

                if ~ismember('Used', ...
                        msTable.Properties.VariableNames) || ...
                        isempty(msTable.Properties.RowNames)
                    error( ...
                        "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                        "InvalidMSSelectionTable", ...
                        "The model MS table must provide row names and " + ...
                    "a Used column.");
                end

                selectedFragmentList = string( ...
                    msTable.Properties.RowNames(logical(msTable.Used)));
                selectedFragmentList = selectedFragmentList(:);
                return;
            end

            configuredFragments = selection.Fragments;
            configuredMask = selection.SelectedMask;

            if numel(configuredFragments) ~= numel(configuredMask) || ...
                    isempty(configuredFragments) || ...
                    numel(unique(configuredFragments)) ~= ...
                    numel(configuredFragments)
                error( ...
                    "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                    "InvalidCustomFragmentSelection", ...
                    "Custom fragment names and mask must be nonempty, " + ...
                "unique, and have matching dimensions.");
            end

            [fragmentList, order] = sort(configuredFragments);
            selectedFragmentList = fragmentList(configuredMask(order));

        end % resolveFragmentSelection

        function massCounts = resolveMassCounts(model, fragmentList)

            metadata = model.getMSMetaboliteTable();

            if ~all(ismember( ...
                    {'Metabolite', 'Carbon'}, ...
                    metadata.Properties.VariableNames))
                error( ...
                    "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                    "InvalidFragmentMetadata", ...
                    "MS metabolite metadata must provide Metabolite and " + ...
                "Carbon columns.");
            end

            metadataFragments = string(metadata.Metabolite);
            massCounts = zeros(numel(fragmentList), 1);

            for fragmentIndex = 1:numel(fragmentList)
                metadataIndex = find( ...
                    metadataFragments == fragmentList(fragmentIndex));

                if numel(metadataIndex) ~= 1
                    error( ...
                        "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                        "FragmentMetadataMismatch", ...
                        "Fragment '%s' must have exactly one MS metadata " + ...
                        "row.", ...
                        fragmentList(fragmentIndex));
                end

                carbonCount = metadata.Carbon(metadataIndex);

                if iscell(carbonCount)
                    carbonCount = carbonCount{1};
                end

                carbonCount = double(carbonCount);

                if ~isscalar(carbonCount) || ...
                        ~isfinite(carbonCount) || ...
                        carbonCount < 0 || ...
                        fix(carbonCount) ~= carbonCount
                    error( ...
                        "OpenMebius2:MFAExperimentalDataBuilder:" + ...
                        "InvalidCarbonCount", ...
                        "Fragment '%s' must have a nonnegative integer " + ...
                        "carbon count.", ...
                        fragmentList(fragmentIndex));
                end

                massCounts(fragmentIndex) = carbonCount + 1;
            end

        end % resolveMassCounts

    end % methods (Static, Access = private)

end % classdef
