classdef MFAFitStatistics
    % MFAFITSTATISTICS
    % Evaluates candidate flux fits and calculates chi-square thresholds.

    methods

        function result = evaluateFluxes( ...
                ~, fluxes, experimentalMDV, fragmentMask, ...
                mdvFunction, effluxPenalty, options)

            arguments
                ~
                fluxes (:, :) double
                experimentalMDV double
                fragmentMask
                mdvFunction (1, 1) function_handle
                effluxPenalty
                options.MeasurementStandardDeviation ...
                    (1, 1) double = 0.01
                options.ValidityTolerance (1, 1) double = 1e-3
                options.InvalidObjective (1, 1) double = 1e9
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            if options.MeasurementStandardDeviation <= 0 || ...
                    ~isfinite(options.MeasurementStandardDeviation)
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "InvalidMeasurementStandardDeviation", ...
                    "The measurement standard deviation must be " + ...
                    "positive and finite.");
            end

            if options.ValidityTolerance < 0 || ...
                    ~isfinite(options.ValidityTolerance)
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "InvalidValidityTolerance", ...
                    "The MDV validity tolerance must be nonnegative " + ...
                    "and finite.");
            end

            if ~ismethod(effluxPenalty, 'evaluate')
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "InvalidEffluxPenalty", ...
                    "The efflux penalty must implement evaluate.");
            end

            selectedIndices = find(logical(fragmentMask(:)));

            if ~isempty(selectedIndices) && ...
                    max(selectedIndices) > numel(experimentalMDV)
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "ExperimentalMDVDimensionMismatch", ...
                    "The fragment mask exceeds the experimental MDV " + ...
                    "dimensions.");
            end

            candidateCount = size(fluxes, 2);
            objectiveValues = nan(1, candidateCount);
            isCanceled = false;

            for candidate = 1:candidateCount

                if logical(options.CancellationRequested())
                    isCanceled = true;
                    break;
                end

                predictedMDV = mdvFunction(fluxes(:, candidate));

                if any(predictedMDV >= ...
                        1 + options.ValidityTolerance) || ...
                        any(predictedMDV <= ...
                        0 - options.ValidityTolerance)
                    objectiveValues(candidate) = ...
                        options.InvalidObjective;
                    continue;
                end

                if ~isempty(selectedIndices) && ...
                        max(selectedIndices) > numel(predictedMDV)
                    error( ...
                        "OpenMebius2:MFAFitStatistics:" + ...
                        "PredictedMDVDimensionMismatch", ...
                        "The fragment mask exceeds the predicted MDV " + ...
                        "dimensions.");
                end

                residual = ( ...
                    predictedMDV(selectedIndices) - ...
                    experimentalMDV(selectedIndices)) / ...
                    options.MeasurementStandardDeviation;
                objectiveValues(candidate) = ...
                    sum(residual .^ 2, 1) + ...
                    effluxPenalty.evaluate(fluxes(:, candidate));
            end

            [objectiveValues, order] = ...
                sort(objectiveValues, "ascend");
            validCount = sum( ...
                objectiveValues < options.InvalidObjective);
            result = openmebius.mfa.MFAFitEvaluationResult( ...
                ObjectiveValues = objectiveValues, ...
                Order = order, ...
                ValidCount = validCount, ...
                IsCanceled = isCanceled);

        end % evaluateFluxes

        function [threshold, degreesOfFreedom] = ...
                chiSquareThreshold( ...
                ~, modelDegreesOfFreedom, fragmentLabels, ...
                fragmentMask, alpha, options)

            arguments
                ~
                modelDegreesOfFreedom (1, 1) double
                fragmentLabels
                fragmentMask
                alpha (1, 1) double = 0.05
                options.ExperimentCount (1, 1) double = NaN
            end

            if ~isfinite(modelDegreesOfFreedom)
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "InvalidModelDegreesOfFreedom", ...
                    "Model degrees of freedom must be finite.");
            end

            if ~isfinite(alpha) || alpha < 0 || alpha > 1
                error( ...
                    "OpenMebius2:MFAFitStatistics:InvalidAlpha", ...
                    "The significance level must be between zero and " + ...
                    "one.");
            end

            fragmentLabels = string(fragmentLabels);
            fragmentMask = logical(fragmentMask);

            if isvector(fragmentLabels) && isvector(fragmentMask)
                fragmentLabels = fragmentLabels(:);
                fragmentMask = fragmentMask(:);
            end

            if ~isequal(size(fragmentLabels), size(fragmentMask))
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "FragmentDimensionMismatch", ...
                    "Fragment labels and masks must have the same " + ...
                    "dimensions.");
            end

            metadataExperimentCount = size(fragmentMask, 2);
            experimentCount = options.ExperimentCount;

            if isnan(experimentCount)
                experimentCount = metadataExperimentCount;
            elseif ~isfinite(experimentCount) || experimentCount < 1 || ...
                    fix(experimentCount) ~= experimentCount
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "InvalidExperimentCount", ...
                    "The experiment count must be a positive integer.");
            end

            if metadataExperimentCount > 1 && ...
                    metadataExperimentCount ~= experimentCount
                error( ...
                    "OpenMebius2:MFAFitStatistics:" + ...
                    "ExperimentCountMismatch", ...
                    "The experiment count must match the fragment " + ...
                    "metadata columns.");
            end

            fragmentDegreesOfFreedom = 0;

            for labeling = 1:size(fragmentMask, 2)
                labelingMask = fragmentMask(:, labeling);
                selectedLabels = ...
                    fragmentLabels(labelingMask, labeling);
                fragmentCount = numel(unique(selectedLabels));
                dataPointCount = sum(labelingMask);
                fragmentDegreesOfFreedom = ...
                    fragmentDegreesOfFreedom + ...
                    dataPointCount - fragmentCount;
            end

            if metadataExperimentCount == 1
                fragmentDegreesOfFreedom = ...
                    fragmentDegreesOfFreedom * experimentCount;
            end

            degreesOfFreedom = ...
                fragmentDegreesOfFreedom - modelDegreesOfFreedom;
            threshold = chi2inv(1 - alpha, degreesOfFreedom);

        end % chiSquareThreshold

        function threshold = gridSearchObjectiveThreshold( ...
                ~, settings, minimumObjective, ...
                residualDegreesOfFreedom)

            arguments
                ~
                settings (1, 1) openmebius.mfa ...
                    .GridSearchConfidenceIntervalSettings
                minimumObjective (1, 1) double {mustBeFinite, mustBeNonnegative}
                residualDegreesOfFreedom (1, 1) double ...
                    {mustBeInteger, mustBePositive}
            end

            if ~isfinite(minimumObjective) || minimumObjective < 0
                error( ...
                    "OpenMebius2:GridSearchCI:InvalidMinimumObjective", ...
                    "The minimum objective value must be finite and " + ...
                    "nonnegative.");
            end

            if ~isfinite(residualDegreesOfFreedom) || ...
                    residualDegreesOfFreedom <= 0
                error( ...
                    "OpenMebius2:GridSearchCI:InvalidResidualDegreesOfFreedom", ...
                    "The residual degrees of freedom must be finite and " + ...
                    "positive.");
            end

            switch settings.Threshold

                case "chi-sq"
                    threshold = ...
                        minimumObjective + chi2inv( ...
                        1 - settings.Alpha, 1);

                case "f-distribution"
                    threshold = ...
                        minimumObjective + ...
                        (minimumObjective / residualDegreesOfFreedom) * ...
                        finv(1 - settings.Alpha, 1, residualDegreesOfFreedom);

                otherwise
                    error( ...
                        "OpenMebius2:GridSearchCI:UnknownThreshold", ...
                        "Unsupported grid-search threshold: %s.", ...
                        settings.Threshold);

            end

        end % method gridSearchObjectiveThreshold

    end % methods

end % classdef
