classdef MFAIterationRunner
    % MFAITERATIONRUNNER
    % Runs one MFA objective and assembles its flux and MDV result.

    properties (SetAccess = private)
        Solver
    end

    methods

        function obj = MFAIterationRunner(options)

            arguments
                options.Solver = openmebius.mfa.SteadyStateSolver()
            end

            obj.Solver = options.Solver;

        end % constructor

        function result = run( ...
                obj, problem, rightHandSide, objective, solverOptions, ...
                options)

            arguments
                obj (1, 1) openmebius.mfa.MFAIterationRunner
                problem (1, 1) openmebius.mfa.MFAProblem
                rightHandSide (:, 1) double
                objective
                solverOptions (1, 1) openmebius.mfa.SteadyStateOptions
                options.InitialIndependentValues double = []
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            if ~ismethod(objective, 'evaluate') || ...
                    ~ismethod(objective, 'predictFlux')
                error( ...
                    "OpenMebius2:MFAIterationRunner:InvalidObjective", ...
                    "An MFA objective must implement evaluate and " + ...
                    "predictFlux methods.");
            end

            solverResult = obj.Solver.solve( ...
                problem, ...
                rightHandSide, ...
                @(values) objective.evaluate(values), ...
                solverOptions, ...
                InitialIndependentValues = ...
                    options.InitialIndependentValues, ...
                MessageReporter = options.MessageReporter);
            mdv = objective.predictFlux(solverResult.Flux);
            result = openmebius.mfa.MFAIterationResult( ...
                IndependentValues = solverResult.IndependentValues, ...
                Flux = solverResult.Flux, ...
                MDV = mdv, ...
                ObjectiveValue = solverResult.ObjectiveValue, ...
                ExitFlag = solverResult.ExitFlag, ...
                Output = solverResult.Output, ...
                ErrorMessage = solverResult.ErrorMessage);

        end % run

    end % methods

end % classdef
