classdef MFAIterationService
    % MFAITERATIONSERVICE
    % Builds and executes one configured steady or instationary MFA fit.

    properties (SetAccess = private)
        Runner
        MDVPredictor
        EffluxPenaltyFactory
    end

    methods

        function obj = MFAIterationService(options)

            arguments
                options.Runner = openmebius.mfa.MFAIterationRunner()
                options.MDVPredictor = ...
                    openmebius.mfa.SteadyStateMDVPredictor()
                options.EffluxPenaltyFactory = ...
                    openmebius.mfa.EffluxPenaltyFactory()
            end

            obj.Runner = options.Runner;
            obj.MDVPredictor = options.MDVPredictor;
            obj.EffluxPenaltyFactory = options.EffluxPenaltyFactory;

        end

        function iterationResult = run(obj, input, options)

            arguments
                obj (1, 1) openmebius.mfa.MFAIterationService
                input (1, 1) openmebius.mfa.MFAIterationInput
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            reporter = options.MessageReporter;
            penalty = obj.EffluxPenaltyFactory.create( ...
                input.Model, ...
                input.SubstrateList, ...
                input.Efflux, ...
                input.EffluxStandardDeviation, ...
                input.EffluxFree);

            if input.usesInstationaryMFA()
                objective = openmebius.mfa.InstationaryObjective( ...
                    Problem = input.Problem, ...
                    RightHandSide = input.RightHandSide, ...
                    Model = input.Model, ...
                    SubstrateEMU = input.SubstrateEMUs{1}, ...
                    Input = input.InstationaryInput, ...
                    ExperimentalMDV = input.ExperimentalMDV, ...
                    FragmentMask = ...
                    input.ExperimentalData.FragmentMask, ...
                    EffluxPenalty = penalty);
                context = " for instationary MFA";
            else
                objective = openmebius.mfa.SteadyStateObjective( ...
                    Problem = input.Problem, ...
                    RightHandSide = input.RightHandSide, ...
                    Model = input.Model, ...
                    SubstrateEMUs = input.SubstrateEMUs, ...
                    ExperimentalMDV = ...
                    input.arrangedExperimentalMDV(), ...
                    FragmentMask = ...
                    input.ExperimentalData.FragmentMask, ...
                    EffluxPenalty = penalty, ...
                    MDVPredictor = obj.MDVPredictor);
                context = "";
            end

            method = "gradient-only";

            if isfield( ...
                    input.AnalysisConfig, 'optimizationMethod') && ...
                    ~isempty(input.AnalysisConfig.optimizationMethod)
                method = lower(string( ...
                    input.AnalysisConfig.optimizationMethod));
            end

            if ismember( ...
                    method, ...
                    ["hybrid-ga-gradient", "hybrid", "ga-gradient"])
                reporter( ...
                    "info", ...
                    "Hybrid GA optimization is temporarily disabled. " + ...
                    "Using FMINCON only.");
            elseif ~ismember( ...
                    method, ["gradient-only", "fmincon", "local"])
                reporter( ...
                    "warning", ...
                    "Unknown optimizationMethod '" + method + ...
                    "'. Using FMINCON only.");
            end

            [solverOptions, optionWarnings] = ...
                openmebius.mfa.SteadyStateOptions.fromBatchConfig( ...
                input.AnalysisConfig);

            for iWarning = 1:numel(optionWarnings)
                reporter("warning", optionWarnings(iWarning));
            end

            iterationResult = obj.Runner.run( ...
                input.Problem, ...
                input.RightHandSide, ...
                objective, ...
                solverOptions, ...
                MessageReporter = reporter);
            fval = iterationResult.ObjectiveValue;
            subject = "Nonlinear optimization" + context;

            if iterationResult.IsError || ~isfinite(fval)
                message = subject + " failed.";

                if strlength(iterationResult.ErrorMessage) > 0
                    message = message + " " + ...
                        iterationResult.ErrorMessage;
                end

                reporter("error", message);
                return
            end

            stepSizeMessage = "";
            optimizationOutput = iterationResult.Output;

            if isfield( ...
                    optimizationOutput, ...
                    'fminconFiniteDifferenceStepSize')
                stepSizeMessage = " FiniteDifferenceStepSize: " + ...
                    string(optimizationOutput ...
                    .fminconFiniteDifferenceStepSize) + ".";
            end

            reporter( ...
                "info", ...
                subject + " completed. RSS: " + string(fval) + ...
                "." + stepSizeMessage);

        end

    end

end
