classdef MFAIterationService
    % MFAITERATIONSERVICE
    % Builds and executes one configured steady or instationary MFA fit.

    properties (SetAccess = private)
        Runner
        MDVPredictor
        EffluxPenaltyFactory
    end

    methods

        function obj = MFAIterationService(options)

            arguments
                options.Runner = openmebius.mfa.MFAIterationRunner()
                options.MDVPredictor = ...
                    openmebius.mfa.SteadyStateMDVPredictor()
                options.EffluxPenaltyFactory = ...
                    openmebius.mfa.EffluxPenaltyFactory()
            end

            obj.Runner = options.Runner;
            obj.MDVPredictor = options.MDVPredictor;
            obj.EffluxPenaltyFactory = options.EffluxPenaltyFactory;

        end

        function iterationResult = run( ...
                obj, model, analysisConfig, runContext, ...
                experimentalMDV, rightHandSide, substrateList, ...
                efflux, effluxStandardDeviation, effluxFree, options)

            arguments
                obj (1, 1) openmebius.mfa.MFAIterationService
                model
                analysisConfig
                runContext (1, 1) openmebius.application ...
                    .analysis.MFAAnalysisRunContext
                experimentalMDV double
                rightHandSide (:, 1) double
                substrateList
                efflux double
                effluxStandardDeviation double
                effluxFree
                options.SubstrateEMUs cell = ...
                    runContext.SubstrateEMUs
                options.ForceSteadyState (1, 1) logical = false
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            reporter = options.MessageReporter;
            penalty = obj.EffluxPenaltyFactory.create( ...
                model, ...
                substrateList, ...
                efflux, ...
                effluxStandardDeviation, ...
                effluxFree);
            useInstationary = analysisConfig.isINSTMFA && ...
                ~options.ForceSteadyState;

            if useInstationary
                objective = openmebius.mfa.InstationaryObjective( ...
                    Problem = runContext.Problem, ...
                    RightHandSide = rightHandSide, ...
                    Model = model, ...
                    SubstrateEMU = options.SubstrateEMUs{1}, ...
                    Input = runContext.InstationaryInput, ...
                    ExperimentalMDV = experimentalMDV, ...
                    FragmentMask = ...
                    runContext.ExperimentalData.FragmentMask, ...
                    EffluxPenalty = penalty);
                context = " for instationary MFA";
            else
                arrangedMDV = runContext.ExperimentalData.arrangeMDV( ...
                    experimentalMDV, ...
                    ExperimentCount = numel(options.SubstrateEMUs));
                objective = openmebius.mfa.SteadyStateObjective( ...
                    Problem = runContext.Problem, ...
                    RightHandSide = rightHandSide, ...
                    Model = model, ...
                    SubstrateEMUs = options.SubstrateEMUs, ...
                    ExperimentalMDV = arrangedMDV, ...
                    FragmentMask = ...
                    runContext.ExperimentalData.FragmentMask, ...
                    EffluxPenalty = penalty, ...
                    MDVPredictor = obj.MDVPredictor);
                context = "";
            end

            method = "gradient-only";

            if isfield(analysisConfig, 'optimizationMethod') && ...
                    ~isempty(analysisConfig.optimizationMethod)
                method = lower(string( ...
                    analysisConfig.optimizationMethod));
            end

            if ismember( ...
                    method, ...
                    ["hybrid-ga-gradient", "hybrid", "ga-gradient"])
                reporter( ...
                    "info", ...
                    "Hybrid GA optimization is temporarily disabled. " + ...
                    "Using FMINCON only.");
            elseif ~ismember( ...
                    method, ["gradient-only", "fmincon", "local"])
                reporter( ...
                    "warning", ...
                    "Unknown optimizationMethod '" + method + ...
                    "'. Using FMINCON only.");
            end

            [solverOptions, optionWarnings] = ...
                openmebius.mfa.SteadyStateOptions.fromBatchConfig( ...
                analysisConfig);

            for iWarning = 1:numel(optionWarnings)
                reporter("warning", optionWarnings(iWarning));
            end

            iterationResult = obj.Runner.run( ...
                runContext.Problem, ...
                rightHandSide, ...
                objective, ...
                solverOptions, ...
                MessageReporter = reporter);
            fval = iterationResult.ObjectiveValue;
            subject = "Nonlinear optimization" + context;

            if iterationResult.IsError || ~isfinite(fval)
                message = subject + " failed.";

                if strlength(iterationResult.ErrorMessage) > 0
                    message = message + " " + ...
                        iterationResult.ErrorMessage;
                end

                reporter("error", message);
                return
            end

            stepSizeMessage = "";
            optimizationOutput = iterationResult.Output;

            if isfield( ...
                    optimizationOutput, ...
                    'fminconFiniteDifferenceStepSize')
                stepSizeMessage = " FiniteDifferenceStepSize: " + ...
                    string(optimizationOutput ...
                    .fminconFiniteDifferenceStepSize) + ".";
            end

            reporter( ...
                "info", ...
                subject + " completed. RSS: " + string(fval) + ...
                "." + stepSizeMessage);

        end

    end

end
