classdef MFAObjectiveFactory
    % MFAOBJECTIVEFACTORY Builds the objective for one MFA iteration.

    properties (SetAccess = private)
        MDVPredictor
    end

    methods

        function obj = MFAObjectiveFactory(options)

            arguments
                options.MDVPredictor (1, 1) ...
                    openmebius.mfa.SteadyStateMDVPredictor = ...
                    openmebius.mfa.SteadyStateMDVPredictor()
            end

            obj.MDVPredictor = options.MDVPredictor;

        end % constructor

        function objective = create(obj, input, penalty)

            arguments
                obj (1, 1) openmebius.mfa.MFAObjectiveFactory
                input (1, 1) openmebius.mfa.MFAIterationInput
                penalty (1, 1) openmebius.mfa.EffluxPenalty
            end

            if input.usesInstationaryMFA()
                objective = openmebius.mfa.InstationaryObjective( ...
                    Problem = input.Problem, ...
                    RightHandSide = input.RightHandSide, ...
                    Model = input.Model, ...
                    SubstrateEMU = input.SubstrateEMUs{1}, ...
                    Input = input.InstationaryInput, ...
                    ExperimentalMDV = input.ExperimentalMDV, ...
                    FragmentMask = ...
                    input.ExperimentalData.FragmentMask, ...
                    EffluxPenalty = penalty);
                return
            end

            objective = openmebius.mfa.SteadyStateObjective( ...
                Problem = input.Problem, ...
                RightHandSide = input.RightHandSide, ...
                Model = input.Model, ...
                SubstrateEMUs = input.SubstrateEMUs, ...
                ExperimentalMDV = input.arrangedExperimentalMDV(), ...
                FragmentMask = input.ExperimentalData.FragmentMask, ...
                EffluxPenalty = penalty, ...
                MDVPredictor = obj.MDVPredictor);

        end % create

    end % methods

end % classdef
