classdef MFAProblemFactory
    % MFAPROBLEMFACTORY
    % Maps named stoichiometry data to a validated MFAProblem.

    methods

        function problem = create( ...
                ~, stoichiometryTable, systemType, rightHandSide, ...
                lowerBounds, upperBounds, options)

            arguments
                ~
                stoichiometryTable table
                systemType
                rightHandSide (:, 1) double
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                options.FreeConstraintIDs string = strings(0, 1)
                options.FluxInequalityMatrix double = []
                options.FluxInequalityRightHandSide (:, 1) double = ...
                    zeros(0, 1)
            end

            systemType = string(systemType(:));
            rowNames = string(stoichiometryTable.Properties.RowNames);
            reactionNames = ...
                string(stoichiometryTable.Properties.VariableNames);
            fluxInequalityMatrix = options.FluxInequalityMatrix;

            if isempty(fluxInequalityMatrix)
                fluxInequalityMatrix = zeros( ...
                    0, width(stoichiometryTable));
            end

            if numel(systemType) ~= height(stoichiometryTable)
                error( ...
                    "OpenMebius2:MFAProblem:SystemTypeDimensionMismatch", ...
                    "System types must match stoichiometry rows.");
            end

            if numel(rowNames) ~= height(stoichiometryTable)
                error( ...
                    "OpenMebius2:MFAProblem:MissingRowNames", ...
                    "Stoichiometry rows must have reaction names.");
            end

            freeConstraintIDs = string(options.FreeConstraintIDs(:));

            if any(ismissing(freeConstraintIDs)) || ...
                    any(strlength(freeConstraintIDs) == 0) || ...
                    numel(unique(freeConstraintIDs)) ~= ...
                    numel(freeConstraintIDs)
                error( ...
                    "OpenMebius2:MFAProblem:InvalidFreeConstraintID", ...
                    "Free constraint IDs must be nonempty and unique.");
            end

            [foundFreeConstraints, freeConstraintIndices] = ...
                ismember(freeConstraintIDs, rowNames);

            if any(~foundFreeConstraints)
                error( ...
                    "OpenMebius2:MFAProblem:FreeConstraintNotFound", ...
                    "Free constraints were not found in the " + ...
                    "stoichiometry: %s.", ...
                    strjoin(freeConstraintIDs(~foundFreeConstraints), ...
                    ", "));
            end

            systemType(freeConstraintIndices) = "independent";

            independentMask = systemType == "independent";
            independentReactionNames = rowNames(independentMask);
            boundaryReactionMask = ...
                ismember(reactionNames, independentReactionNames)';
            problem = openmebius.mfa.MFAProblem( ...
                Stoichiometry = table2array(stoichiometryTable), ...
                RightHandSide = rightHandSide, ...
                LowerBounds = lowerBounds, ...
                UpperBounds = upperBounds, ...
                IndependentMask = independentMask, ...
                BoundaryReactionMask = boundaryReactionMask, ...
                FluxInequalityMatrix = ...
                fluxInequalityMatrix, ...
                FluxInequalityRightHandSide = ...
                options.FluxInequalityRightHandSide);

        end % create

    end % methods

end % classdef
