classdef MonteCarloConfidenceIntervalSolver
    % MONTECARLOCONFIDENCEINTERVALSOLVER
    % Runs perturbed-MDV optimizations and calculates cumulative bounds.

    methods

        function result = solve( ...
                ~, experimentalMDV, fluxCount, config, ...
                iterationFunction, reversibleReactionIndices, options)

            arguments
                ~
                experimentalMDV (:, :) double
                fluxCount (1, 1) double
                config (1, 1) struct
                iterationFunction (1, 1) function_handle
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.UseParallel (1, 1) logical = true
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested (1, 1) function_handle = ...
                    @() false
                options.ConfidenceLevel (1, 1) double = 0.95
            end

            settings = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver ...
                .validateConfiguration( ...
                config, fluxCount, options.ConfidenceLevel);
            tStart = tic;
            iterationCount = settings.IterationCount;
            perturbedMDVs = nan( ...
                size(experimentalMDV, 1), ...
                size(experimentalMDV, 2), ...
                iterationCount);
            sampledFluxes = nan(fluxCount, iterationCount);
            messageReporter = options.MessageReporter;
            cancellationRequested = options.CancellationRequested;

            if options.UseParallel
                parfor i = 1:iterationCount
                    [perturbedMDVs(:, :, i), sampledFluxes(:, i)] = ...
                        openmebius.mfa ...
                        .MonteCarloConfidenceIntervalSolver.solveSample( ...
                        experimentalMDV, ...
                        settings, ...
                        iterationFunction, ...
                        fluxCount, ...
                        i, ...
                        messageReporter);
                end
            else
                for i = 1:iterationCount
                    [perturbedMDVs(:, :, i), sampledFluxes(:, i)] = ...
                        openmebius.mfa ...
                        .MonteCarloConfidenceIntervalSolver.solveSample( ...
                        experimentalMDV, ...
                        settings, ...
                        iterationFunction, ...
                        fluxCount, ...
                        i, ...
                        messageReporter);
                end
            end

            forwardFluxes = ...
                openmebius.mfa.ReversibleFluxMapper.mapFlux( ...
                sampledFluxes, reversibleReactionIndices);
            messageReporter( ...
                "info", ...
                "Calculating confidence interval using " + ...
                settings.CalculationMethod + " method.");
            [lowerBounds, upperBounds, isCanceled] = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver ...
                .calculateCumulativeBounds( ...
                forwardFluxes, ...
                settings.CalculationMethod, ...
                options.ConfidenceLevel, ...
                cancellationRequested);
            result = ...
                openmebius.mfa.MonteCarloConfidenceIntervalResult( ...
                LowerBounds = lowerBounds, ...
                UpperBounds = upperBounds, ...
                PerturbedMDVs = perturbedMDVs, ...
                Fluxes = forwardFluxes, ...
                IterationCount = iterationCount, ...
                ElapsedTime = toc(tStart), ...
                IsCanceled = isCanceled);

        end % solve

    end % methods

    methods (Static, Access = private)

        function [perturbedMDV, selectedFlux] = solveSample( ...
                experimentalMDV, settings, iterationFunction, ...
                fluxCount, iteration, messageReporter)

            perturbedMDV = experimentalMDV + ...
                randn(size(experimentalMDV)) * settings.StandardDeviation;

            switch settings.Procedure
                case "Single run"
                    iterationResult = iterationFunction(perturbedMDV);
                    selectedFlux = openmebius.mfa ...
                        .MonteCarloConfidenceIntervalSolver.extractFlux( ...
                        iterationResult, fluxCount);
                case "Multiple run"
                    messageReporter( ...
                        "info", ...
                        "Monte Carlo iteration: " + ...
                        string(iteration) + "/" + ...
                        string(settings.IterationCount));
                    selectedFlux = openmebius.mfa ...
                        .MonteCarloConfidenceIntervalSolver ...
                        .solveMultipleTrials( ...
                        perturbedMDV, ...
                        settings, ...
                        iterationFunction, ...
                        fluxCount, ...
                        iteration, ...
                        messageReporter);
            end

        end % solveSample

        function selectedFlux = solveMultipleTrials( ...
                perturbedMDV, settings, iterationFunction, ...
                fluxCount, iteration, messageReporter)

            maxStoredTrialCount = 2 * max( ...
                settings.TrialCount, settings.CertainThreshold);
            temporaryFluxes = nan( ...
                fluxCount, maxStoredTrialCount);
            temporaryObjectives = nan(1, maxStoredTrialCount);
            storedTrialCount = 0;
            trial = 1;
            bestObjective = inf;

            while trial <= settings.TrialCount || ...
                    storedTrialCount < ...
                    settings.CertainThreshold
                messageReporter( ...
                    "info", ...
                    "Monte Carlo iteration: " + ...
                    string(iteration) + "/" + ...
                    string(settings.IterationCount) + ...
                    ", Trial: " + string(trial) + "/" + ...
                    string(settings.TrialCount));
                iterationResult = iterationFunction(perturbedMDV);
                currentFlux = openmebius.mfa ...
                    .MonteCarloConfidenceIntervalSolver.extractFlux( ...
                    iterationResult, fluxCount);
                currentObjective = iterationResult.ObjectiveValue;
                storedTrialCount = storedTrialCount + 1;
                temporaryFluxes(:, storedTrialCount) = currentFlux;
                temporaryObjectives(storedTrialCount) = ...
                    currentObjective;
                proximity = openmebius.mfa ...
                    .MonteCarloConfidenceIntervalSolver ...
                    .calculateProximity( ...
                    bestObjective, currentObjective);

                % Preserve the legacy accepted-trial weighting. Accepted
                % trials are stored a second time and therefore also count
                % toward CertainThreshold.
                if proximity < settings.ProximityThreshold || ...
                        isinf(bestObjective)
                    storedTrialCount = storedTrialCount + 1;
                    temporaryFluxes(:, storedTrialCount) = currentFlux;
                    temporaryObjectives(storedTrialCount) = ...
                        currentObjective;
                    bestObjective = min( ...
                        temporaryObjectives(1:storedTrialCount));
                end

                trial = trial + 1;
            end

            temporaryObjectives = ...
                temporaryObjectives(1:storedTrialCount);
            [~, bestIndex] = min(temporaryObjectives);
            selectedFlux = temporaryFluxes(:, bestIndex);

        end % solveMultipleTrials

        function settings = validateConfiguration( ...
                config, fluxCount, confidenceLevel)

            if ~isscalar(fluxCount) || ~isfinite(fluxCount) || ...
                    fluxCount < 1 || fix(fluxCount) ~= fluxCount
                error( ...
                    "OpenMebius2:MonteCarloCI:InvalidFluxCount", ...
                    "The sampled flux count must be a positive integer.");
            end

            if ~isscalar(confidenceLevel) || ...
                    ~isfinite(confidenceLevel) || ...
                    confidenceLevel < 0 || confidenceLevel > 1
                error( ...
                    "OpenMebius2:MonteCarloCI:" + ...
                    "InvalidConfidenceLevel", ...
                    "The confidence level must be between zero and one.");
            end

            requiredFields = ["iteration", "MIDSD", ...
                "calculationMethod"];

            for fieldName = requiredFields
                if ~isfield(config, fieldName)
                    error( ...
                        "OpenMebius2:MonteCarloCI:" + ...
                        "MissingConfiguration", ...
                        "Missing Monte Carlo configuration field: " + ...
                        fieldName + ".");
                end
            end

            iterationCount = double(config.iteration);
            standardDeviation = double(config.MIDSD);

            if ~isscalar(iterationCount) || ...
                    ~isfinite(iterationCount) || ...
                    iterationCount < 1 || ...
                    fix(iterationCount) ~= iterationCount
                error( ...
                    "OpenMebius2:MonteCarloCI:" + ...
                    "InvalidIterationCount", ...
                    "The Monte Carlo iteration count must be a " + ...
                    "positive integer.");
            end

            if ~isscalar(standardDeviation) || ...
                    ~isfinite(standardDeviation) || ...
                    standardDeviation < 0
                error( ...
                    "OpenMebius2:MonteCarloCI:" + ...
                    "InvalidStandardDeviation", ...
                    "The MDV standard deviation must be a finite, " + ...
                    "nonnegative scalar.");
            end

            if isfield(config, "procedure")
                procedure = string(config.procedure);
            else
                procedure = "Single run";
            end

            if ~isscalar(procedure) || ...
                    ~ismember(procedure, ["Single run", "Multiple run"])
                error( ...
                    "OpenMebius2:MonteCarloCI:UnknownProcedure", ...
                    "Unknown Monte Carlo procedure: " + ...
                    strjoin(procedure, ", ") + ".");
            end

            calculationMethod = string(config.calculationMethod);

            if ~isscalar(calculationMethod) || ...
                    calculationMethod ~= "discarding"
                if isscalar(calculationMethod) && ...
                        calculationMethod == "mean-varianced"
                    error( ...
                        "OpenMebius2:MonteCarloCI:" + ...
                        "MethodNotImplemented", ...
                        "Mean-varianced confidence intervals are " + ...
                        "not implemented yet.");
                end

                error( ...
                    "OpenMebius2:MonteCarloCI:UnknownMethod", ...
                    "Unknown confidence-interval calculation method.");
            end

            trialCount = 1;
            certainThreshold = 1;
            proximityThreshold = 0;

            if procedure == "Multiple run"
                multiRunFields = ["theNumberOfRuns", ...
                    "certainThreshold", "proximityThreshold"];

                for fieldName = multiRunFields
                    if ~isfield(config, fieldName)
                        error( ...
                            "OpenMebius2:MonteCarloCI:" + ...
                            "MissingConfiguration", ...
                            "Missing Monte Carlo configuration field: " + ...
                            fieldName + ".");
                    end
                end

                trialCount = double(config.theNumberOfRuns);
                certainThreshold = double(config.certainThreshold);
                proximityThreshold = ...
                    double(config.proximityThreshold);

                if ~isscalar(trialCount) || ...
                        ~isfinite(trialCount) || trialCount < 1 || ...
                        fix(trialCount) ~= trialCount || ...
                        ~isscalar(certainThreshold) || ...
                        ~isfinite(certainThreshold) || ...
                        certainThreshold < 1 || ...
                        fix(certainThreshold) ~= certainThreshold || ...
                        ~isscalar(proximityThreshold) || ...
                        ~isfinite(proximityThreshold) || ...
                        proximityThreshold < 0
                    error( ...
                        "OpenMebius2:MonteCarloCI:" + ...
                        "InvalidMultipleRunConfiguration", ...
                        "Multiple-run counts must be positive integers " + ...
                        "and the proximity threshold must be " + ...
                        "nonnegative.");
                end
            end

            settings = struct;
            settings.IterationCount = iterationCount;
            settings.StandardDeviation = standardDeviation;
            settings.Procedure = procedure;
            settings.CalculationMethod = calculationMethod;
            settings.TrialCount = trialCount;
            settings.CertainThreshold = certainThreshold;
            settings.ProximityThreshold = proximityThreshold;

        end % validateConfiguration

        function flux = extractFlux(iterationResult, fluxCount)

            if ~isa(iterationResult, ...
                    'openmebius.mfa.MFAIterationResult')
                error( ...
                    "OpenMebius2:MonteCarloCI:" + ...
                    "InvalidIterationResult", ...
                    "The iteration function must return an " + ...
                    "MFAIterationResult.");
            end

            flux = iterationResult.Flux(:);

            if numel(flux) ~= fluxCount
                error( ...
                    "OpenMebius2:MonteCarloCI:FluxSizeMismatch", ...
                    "Each Monte Carlo iteration must return the " + ...
                    "configured number of fluxes.");
            end

        end % extractFlux

        function proximity = calculateProximity( ...
                oldObjective, newObjective)

            proximity = abs(newObjective - oldObjective) / ...
                oldObjective;

        end % calculateProximity

        function [lowerBounds, upperBounds, isCanceled] = ...
                calculateCumulativeBounds( ...
                fluxes, calculationMethod, confidenceLevel, ...
                cancellationRequested)

            if calculationMethod ~= "discarding"
                error( ...
                    "OpenMebius2:MonteCarloCI:UnknownMethod", ...
                    "Unknown confidence-interval calculation method.");
            end

            fluxes = rmmissing(fluxes, 2);
            fluxCount = size(fluxes, 1);
            sampleCount = size(fluxes, 2);
            lowerBounds = nan(fluxCount, sampleCount);
            upperBounds = nan(fluxCount, sampleCount);
            threshold = (1 - confidenceLevel) / 2;
            isCanceled = false;

            for sample = 1:sampleCount
                sampledFluxes = fluxes(:, 1:sample);
                rank = fix(threshold * sample) + 1;

                for fluxIndex = 1:fluxCount
                    sortedFlux = sort( ...
                        sampledFluxes(fluxIndex, :), 2);

                    if rank <= numel(sortedFlux)
                        lowerBounds(fluxIndex, sample) = ...
                            sortedFlux(rank);
                        upperBounds(fluxIndex, sample) = ...
                            sortedFlux(end - rank + 1);
                    end
                end

                if logical(cancellationRequested())
                    isCanceled = true;
                    return;
                end
            end

        end % calculateCumulativeBounds

    end % methods (Static, Access = private)

end % classdef
