classdef MonteCarloConfidenceIntervalSolver
    % MONTECARLOCONFIDENCEINTERVALSOLVER
    % Runs perturbed-MDV optimizations and calculates cumulative bounds.

    methods

        function result = solve( ...
                ~, experimentalMDV, fluxCount, settings, ...
                iterationFunction, reversibleReactionIndices, options)

            arguments
                ~
                experimentalMDV (:, :) double
                fluxCount (1, 1) double
                settings (1, 1) openmebius.mfa ...
                    .MonteCarloConfidenceIntervalSettings
                iterationFunction (1, 1) function_handle
                reversibleReactionIndices (:, 2) double = zeros(0, 2)
                options.UseParallel (1, 1) logical = true
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested (1, 1) function_handle = ...
                    @() false
                options.ConfidenceLevel (1, 1) double = 0.95
            end

            openmebius.mfa.MonteCarloConfidenceIntervalSolver ...
                .validateInputs( ...
                settings, fluxCount, options.ConfidenceLevel);
            tStart = tic;
            iterationCount = settings.IterationCount;
            perturbedMDVs = nan( ...
                size(experimentalMDV, 1), ...
                size(experimentalMDV, 2), ...
                iterationCount);
            sampledFluxes = nan(fluxCount, iterationCount);
            messageReporter = options.MessageReporter;
            cancellationRequested = options.CancellationRequested;

            if options.UseParallel
                % Callbacks supplied by the desktop application can close
                % over UI handles. Do not invoke them after serialization
                % to a parallel worker; client-side lifecycle messages are
                % still reported before and after this sampling phase.
                workerMessageReporter = @(~, ~) [];

                parfor i = 1:iterationCount
                    [perturbedMDVs(:, :, i), sampledFluxes(:, i)] = ...
                        openmebius.mfa ...
                        .MonteCarloConfidenceIntervalSolver.solveSample( ...
                        experimentalMDV, ...
                        settings, ...
                        iterationFunction, ...
                        fluxCount, ...
                        i, ...
                        workerMessageReporter);
                end

            else

                for i = 1:iterationCount
                    [perturbedMDVs(:, :, i), sampledFluxes(:, i)] = ...
                        openmebius.mfa ...
                        .MonteCarloConfidenceIntervalSolver.solveSample( ...
                        experimentalMDV, ...
                        settings, ...
                        iterationFunction, ...
                        fluxCount, ...
                        i, ...
                        messageReporter);
                end

            end

            forwardFluxes = ...
                openmebius.mfa.ReversibleFluxMapper.mapFlux( ...
                sampledFluxes, reversibleReactionIndices);
            messageReporter( ...
                "info", ...
                "Calculating confidence interval using " + ...
                settings.CalculationMethod.configValue() + " method.");
            [lowerBounds, upperBounds, isCanceled] = ...
                openmebius.mfa.MonteCarloConfidenceIntervalSolver ...
                .calculateCumulativeBounds( ...
                forwardFluxes, ...
                settings.CalculationMethod, ...
                options.ConfidenceLevel, ...
                cancellationRequested);
            result = ...
                openmebius.mfa.MonteCarloConfidenceIntervalResult( ...
                LowerBounds = lowerBounds, ...
                UpperBounds = upperBounds, ...
                PerturbedMDVs = perturbedMDVs, ...
                Fluxes = forwardFluxes, ...
                IterationCount = iterationCount, ...
                ElapsedTime = toc(tStart), ...
                IsCanceled = isCanceled);

        end % solve

    end % methods

    methods (Static, Access = private)

        function [perturbedMDV, selectedFlux] = solveSample( ...
                experimentalMDV, settings, iterationFunction, ...
                fluxCount, iteration, messageReporter)

            perturbedMDV = experimentalMDV + ...
                randn(size(experimentalMDV)) * settings.StandardDeviation;

            if settings.Procedure.isMultipleRun()
                messageReporter( ...
                    "info", ...
                    "Monte Carlo iteration: " + ...
                    string(iteration) + "/" + ...
                    string(settings.IterationCount));
                selectedFlux = openmebius.mfa ...
                    .MonteCarloConfidenceIntervalSolver ...
                    .solveMultipleTrials( ...
                    perturbedMDV, ...
                    settings, ...
                    iterationFunction, ...
                    fluxCount, ...
                    iteration, ...
                    messageReporter);
            else
                iterationResult = iterationFunction(perturbedMDV);
                selectedFlux = openmebius.mfa ...
                    .MonteCarloConfidenceIntervalSolver.extractFlux( ...
                    iterationResult, fluxCount);
            end

        end % solveSample

        function selectedFlux = solveMultipleTrials( ...
                perturbedMDV, settings, iterationFunction, ...
                fluxCount, iteration, messageReporter)

            maxStoredTrialCount = 2 * max( ...
                settings.TrialCount, settings.CertainThreshold);
            temporaryFluxes = nan( ...
                fluxCount, maxStoredTrialCount);
            temporaryObjectives = nan(1, maxStoredTrialCount);
            storedTrialCount = 0;
            trial = 1;
            bestObjective = inf;

            while trial <= settings.TrialCount || ...
                    storedTrialCount < ...
                    settings.CertainThreshold
                messageReporter( ...
                    "info", ...
                    "Monte Carlo iteration: " + ...
                    string(iteration) + "/" + ...
                    string(settings.IterationCount) + ...
                    ", Trial: " + string(trial) + "/" + ...
                    string(settings.TrialCount));
                iterationResult = iterationFunction(perturbedMDV);
                currentFlux = openmebius.mfa ...
                    .MonteCarloConfidenceIntervalSolver.extractFlux( ...
                    iterationResult, fluxCount);
                currentObjective = iterationResult.ObjectiveValue;
                storedTrialCount = storedTrialCount + 1;
                temporaryFluxes(:, storedTrialCount) = currentFlux;
                temporaryObjectives(storedTrialCount) = ...
                    currentObjective;
                proximity = openmebius.mfa ...
                    .MonteCarloConfidenceIntervalSolver ...
                    .calculateProximity( ...
                    bestObjective, currentObjective);

                % Preserve the legacy accepted-trial weighting. Accepted
                % trials are stored a second time and therefore also count
                % toward CertainThreshold.
                if proximity < settings.ProximityThreshold || ...
                        isinf(bestObjective)
                    storedTrialCount = storedTrialCount + 1;
                    temporaryFluxes(:, storedTrialCount) = currentFlux;
                    temporaryObjectives(storedTrialCount) = ...
                        currentObjective;
                    bestObjective = min( ...
                        temporaryObjectives(1:storedTrialCount));
                end

                trial = trial + 1;
            end

            temporaryObjectives = ...
                temporaryObjectives(1:storedTrialCount);
            [~, bestIndex] = min(temporaryObjectives);
            selectedFlux = temporaryFluxes(:, bestIndex);

        end % solveMultipleTrials

        function validateInputs(settings, fluxCount, confidenceLevel)

            if ~isscalar(fluxCount) || ~isfinite(fluxCount) || ...
                    fluxCount < 1 || fix(fluxCount) ~= fluxCount
                error( ...
                    "OpenMebius2:MonteCarloCI:InvalidFluxCount", ...
                "The sampled flux count must be a positive integer.");
            end

            if ~isscalar(confidenceLevel) || ...
                    ~isfinite(confidenceLevel) || ...
                    confidenceLevel < 0 || confidenceLevel > 1
                error( ...
                    "OpenMebius2:MonteCarloCI:" + ...
                    "InvalidConfidenceLevel", ...
                "The confidence level must be between zero and one.");
            end

            if ~settings.CalculationMethod.isDiscarding()
                error( ...
                    "OpenMebius2:MonteCarloCI:" + ...
                    "MethodNotImplemented", ...
                    "Mean-varianced confidence intervals are " + ...
                "not implemented yet.");
            end

        end % validateInputs

        function flux = extractFlux(iterationResult, fluxCount)

            if ~isa(iterationResult, ...
                'openmebius.mfa.MFAIterationResult')
                error( ...
                    "OpenMebius2:MonteCarloCI:" + ...
                    "InvalidIterationResult", ...
                    "The iteration function must return an " + ...
                "MFAIterationResult.");
            end

            flux = iterationResult.Flux(:);

            if numel(flux) ~= fluxCount
                error( ...
                    "OpenMebius2:MonteCarloCI:FluxSizeMismatch", ...
                    "Each Monte Carlo iteration must return the " + ...
                "configured number of fluxes.");
            end

        end % extractFlux

        function proximity = calculateProximity( ...
                oldObjective, newObjective)

            proximity = abs(newObjective - oldObjective) / ...
                oldObjective;

        end % calculateProximity

        function [lowerBounds, upperBounds, isCanceled] = ...
                calculateCumulativeBounds( ...
                fluxes, calculationMethod, confidenceLevel, ...
                cancellationRequested)

            if ~calculationMethod.isDiscarding()
                error( ...
                    "OpenMebius2:MonteCarloCI:UnknownMethod", ...
                "Unknown confidence-interval calculation method.");
            end

            fluxes = rmmissing(fluxes, 2);
            fluxCount = size(fluxes, 1);
            sampleCount = size(fluxes, 2);
            lowerBounds = nan(fluxCount, sampleCount);
            upperBounds = nan(fluxCount, sampleCount);
            threshold = (1 - confidenceLevel) / 2;
            isCanceled = false;

            for sample = 1:sampleCount
                sampledFluxes = fluxes(:, 1:sample);
                rank = fix(threshold * sample) + 1;

                for fluxIndex = 1:fluxCount
                    sortedFlux = sort( ...
                        sampledFluxes(fluxIndex, :), 2);

                    if rank <= numel(sortedFlux)
                        lowerBounds(fluxIndex, sample) = ...
                            sortedFlux(rank);
                        upperBounds(fluxIndex, sample) = ...
                            sortedFlux(end - rank + 1);
                    end

                end

                if logical(cancellationRequested())
                    isCanceled = true;
                    return;
                end

            end

        end % calculateCumulativeBounds

    end % methods (Static, Access = private)

end % classdef
