classdef SteadyStateSolver
    % STEADYSTATESOLVER
    % Runs guarded steady-state FMINCON finite-difference trials.

    methods

        function result = solve( ...
                ~, problem, rightHandSide, objectiveFunction, ...
                solverOptions, options)

            arguments
                ~
                problem (1, 1) openmebius.mfa.MFAProblem
                rightHandSide (:, 1) double
                objectiveFunction (1, 1) function_handle
                solverOptions (1, 1) openmebius.mfa.SteadyStateOptions
                options.InitialIndependentValues double = []
                options.LinearEqualityMatrix double = zeros(0, 0)
                options.LinearEqualityRightHandSide (:, 1) double = zeros(0, 1)
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            if isempty(options.InitialIndependentValues)
                initialIndependentValues = ...
                    problem.extractIndependentValues(rightHandSide);
            else
                initialIndependentValues = ...
                    options.InitialIndependentValues(:);
            end

            feasibilityTolerance = max([ ...
                solverOptions.ConstraintTolerance, ...
                solverOptions.InitialFeasibilityTolerance, ...
                eps]);

            boundEqualityMatrix = zeros( ...
                0, nnz(problem.IndependentMask));
            boundEqualityRightHandSide = zeros(0, 1);

            if solverOptions.EnforceFluxBounds
                [boundEqualityMatrix, boundEqualityRightHandSide] = ...
                    problem.fluxBoundEqualities( ...
                    BaseRightHandSide = rightHandSide);
            end

            if isempty(options.LinearEqualityMatrix)
                equalityMatrix = boundEqualityMatrix;
                equalityRightHandSide = boundEqualityRightHandSide;
            elseif isempty(boundEqualityMatrix)
                equalityMatrix = options.LinearEqualityMatrix;
                equalityRightHandSide = ...
                    options.LinearEqualityRightHandSide;
            else
                equalityMatrix = [ ...
                    options.LinearEqualityMatrix; ...
                    boundEqualityMatrix];
                equalityRightHandSide = [ ...
                    options.LinearEqualityRightHandSide; ...
                    boundEqualityRightHandSide];
            end

            [equalityMatrix, equalityRightHandSide] = ...
                openmebius.mfa.SteadyStateSolver ...
                .reduceLinearEqualities( ...
                equalityMatrix, equalityRightHandSide, ...
                feasibilityTolerance);

            initialObjective = ...
                openmebius.mfa.SteadyStateSolver.evaluateObjective( ...
                objectiveFunction, initialIndependentValues);
            initialViolation = ...
                openmebius.mfa.SteadyStateSolver.constraintViolation( ...
                problem, ...
                rightHandSide, ...
                initialIndependentValues, ...
                equalityMatrix, ...
                equalityRightHandSide, ...
                solverOptions.EnforceFluxBounds);
            stepSizes = solverOptions.finiteDifferenceStepSizes();
            trialCount = numel(stepSizes);
            trialObjectives = inf(trialCount, 1);
            trialExitFlags = nan(trialCount, 1);
            trialViolations = inf(trialCount, 1);
            trialGuardTriggered = false(trialCount, 1);
            trialExecutionFailed = false(trialCount, 1);
            trialMessages = strings(trialCount, 1);
            trialOutputs = cell(trialCount, 1);
            trialValues = cell(trialCount, 1);
            suppressGuardMessage = trialCount > 1;
            bestIndex = 1;
            bestScore = inf;
            bestValues = initialIndependentValues;
            bestObjective = initialObjective;
            bestExitFlag = -101;
            bestOutput = struct;

            for iTrial = 1:trialCount
                stepSize = stepSizes(iTrial);
                fminconOptions = solverOptions.buildFminconOptions( ...
                    initialIndependentValues, stepSize);
                trialResult = ...
                    openmebius.mfa.SteadyStateSolver.runTrial( ...
                    problem, ...
                    rightHandSide, ...
                    objectiveFunction, ...
                    initialIndependentValues, ...
                    fminconOptions, ...
                    stepSize, ...
                    equalityMatrix, ...
                    equalityRightHandSide, ...
                    solverOptions.EnforceFluxBounds ...
                    );
                trialIndependentValues = trialResult.IndependentValues;
                trialObjective = trialResult.ObjectiveValue;
                trialExitFlag = trialResult.ExitFlag;
                trialOutput = trialResult.Output;
                trialOutput.fminconFiniteDifferenceStepSize = stepSize;
                trialOutput.fminconInitialObjective = initialObjective;
                trialOutput.fminconInitialConstraintViolation = ...
                    initialViolation;
                trialOutput.fminconFinalObjectiveBeforeGuard = ...
                    trialObjective;
                trialOutput.fminconObjectiveGuardTriggered = false;
                [trialIndependentValues, trialObjective, ...
                    trialExitFlag, trialOutput] = ...
                    openmebius.mfa.SteadyStateSolver.applyObjectiveGuard( ...
                    trialIndependentValues, ...
                    trialObjective, ...
                    trialExitFlag, ...
                    trialOutput, ...
                    initialIndependentValues, ...
                    initialObjective, ...
                    initialViolation, ...
                    solverOptions, ...
                    suppressGuardMessage, ...
                    options.MessageReporter);
                trialViolation = ...
                    openmebius.mfa.SteadyStateSolver.constraintViolation( ...
                    problem, ...
                    rightHandSide, ...
                    trialIndependentValues, ...
                    equalityMatrix, ...
                    equalityRightHandSide, ...
                    solverOptions.EnforceFluxBounds);
                trialObjectives(iTrial) = trialObjective;
                trialExitFlags(iTrial) = trialExitFlag;
                trialViolations(iTrial) = trialViolation;
                trialGuardTriggered(iTrial) = ...
                    trialOutput.fminconObjectiveGuardTriggered;
                trialExecutionFailed(iTrial) = ...
                    isfield(trialOutput, 'fminconExecutionFailed') && ...
                    logical(trialOutput.fminconExecutionFailed);

                if isfield(trialOutput, 'message') && ...
                        ~isempty(trialOutput.message)
                    trialMessages(iTrial) = string(trialOutput.message);
                end

                trialOutputs{iTrial} = trialOutput;
                trialValues{iTrial} = trialIndependentValues;

                if isfinite(trialObjective) && ...
                        trialViolation <= 10 * feasibilityTolerance
                    score = trialObjective;
                else
                    score = inf;
                end

                if score < bestScore
                    bestIndex = iTrial;
                    bestScore = score;
                    bestValues = trialIndependentValues;
                    bestObjective = trialObjective;
                    bestExitFlag = trialExitFlag;
                    bestOutput = trialOutput;
                end

            end

            if ~isfinite(bestScore)

                if isfinite(initialObjective) && ...
                        initialViolation <= 10 * feasibilityTolerance
                    bestIndex = 1;
                    bestValues = initialIndependentValues;
                    bestObjective = initialObjective;
                    bestExitFlag = -103;
                    bestOutput = struct;
                    bestOutput.message = ...
                        "No FMINCON finite-difference step-size trial " + ...
                        "improved a feasible initial point.";
                    bestOutput.fminconExecutionFailed = false;
                else
                    finiteMask = isfinite(trialObjectives);

                    if any(finiteMask)
                        finiteObjectives = trialObjectives;
                        finiteObjectives(~finiteMask) = inf;
                        [~, bestIndex] = min(finiteObjectives);
                        bestValues = trialValues{bestIndex};
                        bestObjective = trialObjectives(bestIndex);
                        bestExitFlag = trialExitFlags(bestIndex);
                        bestOutput = trialOutputs{bestIndex};
                    else
                        bestIndex = 1;
                        bestValues = initialIndependentValues;
                        bestObjective = initialObjective;
                        bestExitFlag = -102;
                        bestOutput = struct;
                        bestOutput.message = ...
                            "All FMINCON finite-difference " + ...
                            "step-size trials failed.";
                        bestOutput.fminconExecutionFailed = true;
                    end

                end

            end

            searchOutput = struct;
            searchOutput.enabled = solverOptions.StepSizeSearchEnabled;
            searchOutput.candidates = stepSizes(:);
            searchOutput.objectives = trialObjectives;
            searchOutput.exitflags = trialExitFlags;
            searchOutput.constraintViolations = trialViolations;
            searchOutput.objectiveGuardTriggered = trialGuardTriggered;
            searchOutput.executionFailed = trialExecutionFailed;
            searchOutput.messages = trialMessages;
            searchOutput.bestIndex = bestIndex;
            searchOutput.bestFiniteDifferenceStepSize = ...
                stepSizes(bestIndex);
            searchOutput.bestObjective = bestObjective;
            output = bestOutput;

            if ~isfield(output, 'fminconInitialObjective')
                output.fminconInitialObjective = initialObjective;
            end

            if ~isfield(output, 'fminconInitialConstraintViolation')
                output.fminconInitialConstraintViolation = initialViolation;
            end

            if ~isfield(output, 'fminconFinalObjectiveBeforeGuard')
                output.fminconFinalObjectiveBeforeGuard = bestObjective;
            end

            if ~isfield(output, 'fminconObjectiveGuardTriggered')
                output.fminconObjectiveGuardTriggered = false;
            end

            output.fminconFiniteDifferenceStepSize = stepSizes(bestIndex);
            output.fminconFiniteDifferenceStepSizeSearch = searchOutput;

            if isfield(output, 'fminconExecutionFailed') && ...
                    logical(output.fminconExecutionFailed)
                errorMessage = string(output.message);
            else
                errorMessage = "";
            end

            flux = problem.solveFlux( ...
                bestValues, ...
                BaseRightHandSide = rightHandSide);
            result = openmebius.mfa.SteadyStateResult( ...
                IndependentValues = bestValues, ...
                Flux = flux, ...
                ObjectiveValue = bestObjective, ...
                ExitFlag = bestExitFlag, ...
                Output = output, ...
                ErrorMessage = errorMessage);

        end % solve

    end % methods

    methods (Static, Access = private)

        function result = runTrial( ...
                problem, rightHandSide, objectiveFunction, ...
                initialIndependentValues, fminconOptions, stepSize, ...
                equalityMatrix, equalityRightHandSide, ...
                enforceFluxBounds)

            try
                if enforceFluxBounds
                    [inequalityMatrix, inequalityRightHandSide] = ...
                        problem.fluxBoundInequalities( ...
                        BaseRightHandSide = rightHandSide);
                else
                    [inequalityMatrix, inequalityRightHandSide] = ...
                        problem.nonnegativeFluxInequalities( ...
                        BaseRightHandSide = rightHandSide);
                end

                [independentValues, objectiveValue, exitFlag, output] = ...
                    fmincon( ...
                    objectiveFunction, ...
                    initialIndependentValues, ...
                    inequalityMatrix, ...
                    inequalityRightHandSide, ...
                    equalityMatrix, ...
                    equalityRightHandSide, ...
                    [], ...
                    [], ...
                    [], ...
                    fminconOptions ...
                    );

                if ~isscalar(objectiveValue) || ~isfinite(objectiveValue)
                    objectiveValue = inf;
                end

                output.fminconExecutionFailed = false;
                errorMessage = "";
            catch ME
                independentValues = initialIndependentValues;
                objectiveValue = inf;
                exitFlag = -200;
                output = struct;
                output.message = ...
                    "FMINCON failed at FiniteDifferenceStepSize=" + ...
                    string(stepSize) + ": " + string(ME.message);
                output.fminconExecutionFailed = true;
                output.fminconExceptionIdentifier = string(ME.identifier);
                errorMessage = string(ME.message);
            end

            flux = problem.solveFlux( ...
                independentValues, ...
                BaseRightHandSide = rightHandSide);
            result = openmebius.mfa.SteadyStateResult( ...
                IndependentValues = independentValues, ...
                Flux = flux, ...
                ObjectiveValue = objectiveValue, ...
                ExitFlag = exitFlag, ...
                Output = output, ...
                ErrorMessage = errorMessage);

        end % runTrial

        function value = evaluateObjective(objectiveFunction, values)

            try
                value = objectiveFunction(values);

                if ~isscalar(value) || ~isfinite(value)
                    value = inf;
                end

            catch
                value = inf;
            end

        end % evaluateObjective

        function violation = constraintViolation( ...
                problem, rightHandSide, independentValues, ...
                equalityMatrix, equalityRightHandSide, ...
                enforceFluxBounds)

            try
                flux = problem.solveFlux( ...
                    independentValues, ...
                    BaseRightHandSide = rightHandSide);
                if enforceFluxBounds
                    boundViolation = max([ ...
                        0; ...
                        problem.LowerBounds - flux; ...
                        flux - problem.UpperBounds]);
                else
                    boundViolation = max([0; -flux(:)]);
                end
                fluxInequalityViolation = max([ ...
                    0; ...
                    problem.FluxInequalityMatrix * flux - ...
                    problem.FluxInequalityRightHandSide]);

                if isempty(equalityMatrix)
                    equalityViolation = 0;
                else
                    equalityResidual = ...
                        equalityMatrix * independentValues - ...
                        equalityRightHandSide;
                    equalityViolation = norm(equalityResidual, inf);
                end

                violation = max( ...
                    [boundViolation; fluxInequalityViolation; ...
                    equalityViolation]);

                if ~isfinite(violation)
                    violation = inf;
                end

            catch
                violation = inf;
            end

        end % constraintViolation

        function [matrix, rightHandSide] = ...
                reduceLinearEqualities( ...
                matrix, rightHandSide, tolerance)

            if isempty(matrix)
                return
            end

            rowScales = vecnorm(matrix, inf, 2);
            zeroRowMask = rowScales <= tolerance;

            if any(abs(rightHandSide(zeroRowMask)) > tolerance)
                error( ...
                    "OpenMebius2:SteadyStateSolver:" + ...
                    "InconsistentLinearEqualities", ...
                    "Linear equality constraints are inconsistent.");
            end

            matrix(zeroRowMask, :) = [];
            rightHandSide(zeroRowMask) = [];
            rowScales(zeroRowMask) = [];

            if isempty(matrix)
                matrix = zeros(0, size(matrix, 2));
                rightHandSide = zeros(0, 1);
                return
            end

            matrix = matrix ./ rowScales;
            rightHandSide = rightHandSide ./ rowScales;
            coefficientRank = rank(matrix, tolerance);
            augmentedRank = rank( ...
                [matrix, rightHandSide], tolerance);

            if augmentedRank > coefficientRank
                error( ...
                    "OpenMebius2:SteadyStateSolver:" + ...
                    "InconsistentLinearEqualities", ...
                    "Linear equality constraints are inconsistent.");
            end

            if coefficientRank == 0
                matrix = zeros(0, size(matrix, 2));
                rightHandSide = zeros(0, 1);
                return
            end

            [~, ~, permutation] = qr(matrix.', "vector");
            independentRows = sort(permutation(1:coefficientRank));
            matrix = matrix(independentRows, :);
            rightHandSide = rightHandSide(independentRows);

        end % reduceLinearEqualities

        function [values, objective, exitFlag, output] = ...
                applyObjectiveGuard( ...
                values, objective, exitFlag, output, ...
                initialValues, initialObjective, initialViolation, ...
                solverOptions, suppressMessage, messageReporter)

            if ~solverOptions.RejectWorseThanInitial || ...
                    ~isfinite(initialObjective) || ...
                    initialViolation > ...
                    solverOptions.InitialFeasibilityTolerance
                return
            end

            allowedObjective = initialObjective + ...
                solverOptions.ObjectiveIncreaseTolerance * ...
                max(1, abs(initialObjective));

            if isfinite(objective) && objective <= allowedObjective
                return
            end

            output.fminconObjectiveGuardTriggered = true;
            output.fminconRejectedObjective = objective;
            output.fminconRejectedExitflag = exitFlag;
            output.fminconRejectedMessage = ...
                "FMINCON returned a worse objective than the " + ...
                "feasible initial point.";

            if ~suppressMessage
                messageReporter( ...
                    "warning", ...
                    "FMINCON returned a worse objective (" + ...
                    string(objective) + ") than the feasible " + ...
                    "initial objective (" + string(initialObjective) + ...
                    "). Reverting to the initial point for this trial.");
            end

            values = initialValues;
            objective = initialObjective;
            exitFlag = -100;

        end % applyObjectiveGuard

    end % methods (Static, Access = private)

end % classdef
