classdef LabelConfigurationLaunchController < handle
    % LABELCONFIGURATIONLAUNCHCONTROLLER Prepares a LabelConfig session.

    methods

        function outcome = prepare(~, model)

            try
                openmebius.application.model ...
                    .LabelConfigurationLaunchController ...
                    .validateModelSource(model);
                state = openmebius.application.model ...
                    .LabelConfigurationEditorState( ...
                    model.getTableLabelView(), ...
                    model.getLabelStructView());
                outcome = openmebius.application.model ...
                    .LabelConfigurationLaunchOutcome( ...
                    true, State = state);
            catch exception
                outcome = openmebius.application.model ...
                    .LabelConfigurationLaunchOutcome( ...
                    false, ...
                    ErrorMessage = string(exception.message), ...
                    Exception = exception);
            end

        end % prepare

    end % methods

    methods (Static, Access = private)

        function validateModelSource(model)

            requiredMethods = [ ...
                                   "getTableLabelView", ...
                               "getLabelStructView"];
            isSupported = ~isempty(model) && isobject(model);

            if isSupported

                for methodIndex = 1:numel(requiredMethods)
                    isSupported = isSupported && ismethod( ...
                        model, requiredMethods(methodIndex));
                end

            end

            if ~isSupported
                error( ...
                    "OpenMebius2:" + ...
                    "LabelConfigurationLaunchController:" + ...
                    "InvalidModel", ...
                    "A loaded model with label configuration " + ...
                "accessors is required.");
            end

        end % validateModelSource

    end % methods (Static, Access = private)

end % classdef
