classdef MainAppDependencies
    % MAINAPPDEPENDENCIES Stable controllers and presenters for the main app.

    properties (SetAccess = private)
        ApplicationController openmebius.application.main ...
            .MainApplicationController
        MainPresenter openmebius.presentation.main.MainPresenter
        ProjectPresenter openmebius.presentation.project.ProjectPresenter
        ModelPresenter openmebius.presentation.model.ModelPresenter
        LabelConfigPresenter openmebius.presentation.model.LabelConfigPresenter
        BatchPresenter openmebius.presentation.batch.BatchPresenter
        RunConfigPresenter openmebius.presentation.batch.RunConfigPresenter
        BatchExperimentSelectionEditorPresenter ...
            openmebius.presentation.batch ...
            .BatchExperimentSelectionEditorPresenter
        ExperimentPresenter openmebius.presentation.experiment ...
            .ExperimentPresenter
        ResultPresenter openmebius.presentation.result.ResultPresenter
        ResultPlotPresenter openmebius.presentation.result.ResultPlotPresenter
        ProgressBarFactory openmebius.presentation.main.ProgressBarFactory
        ChildAppHost openmebius.presentation.lifecycle.ChildAppHost
        BatchConfigurationController openmebius.application.batch ...
            .BatchConfigurationController
        BatchExperimentSelectionEditorController ...
            openmebius.application.batch ...
            .BatchExperimentSelectionEditorController
        ExperimentEditController openmebius.application.experiment ...
            .ExperimentEditController
        SlackNotifier openmebius.infrastructure.notification ...
            .SlackWebhookNotifier
        NotificationDispatcher openmebius.infrastructure.notification ...
            .NotificationDispatcher
    end

    methods

        function obj = MainAppDependencies(options)

            arguments
                options.ApplicationController (1, 1) ...
                    openmebius.application.main.MainApplicationController
                options.MainPresenter (1, 1) openmebius.presentation ...
                    .main.MainPresenter
                options.ProjectPresenter (1, 1) openmebius.presentation ...
                    .project.ProjectPresenter
                options.ModelPresenter (1, 1) openmebius.presentation ...
                    .model.ModelPresenter
                options.LabelConfigPresenter (1, 1) ...
                    openmebius.presentation.model.LabelConfigPresenter
                options.BatchPresenter (1, 1) openmebius.presentation ...
                    .batch.BatchPresenter
                options.RunConfigPresenter (1, 1) openmebius.presentation ...
                    .batch.RunConfigPresenter
                options.BatchExperimentSelectionEditorPresenter (1, 1) ...
                    openmebius.presentation.batch ...
                    .BatchExperimentSelectionEditorPresenter
                options.ExperimentPresenter (1, 1) ...
                    openmebius.presentation.experiment.ExperimentPresenter
                options.ResultPresenter (1, 1) openmebius.presentation ...
                    .result.ResultPresenter
                options.ResultPlotPresenter (1, 1) ...
                    openmebius.presentation.result.ResultPlotPresenter
                options.ProgressBarFactory (1, 1) ...
                    openmebius.presentation.main.ProgressBarFactory
                options.ChildAppHost (1, 1) ...
                    openmebius.presentation.lifecycle.ChildAppHost
                options.BatchConfigurationController (1, 1) ...
                    openmebius.application.batch.BatchConfigurationController
                options.BatchExperimentSelectionEditorController (1, 1) ...
                    openmebius.application.batch ...
                    .BatchExperimentSelectionEditorController
                options.ExperimentEditController (1, 1) ...
                    openmebius.application.experiment ...
                    .ExperimentEditController
                options.SlackNotifier (1, 1) ...
                    openmebius.infrastructure.notification ...
                    .SlackWebhookNotifier
                options.NotificationDispatcher (1, 1) ...
                    openmebius.infrastructure.notification ...
                    .NotificationDispatcher
            end

            names = string(fieldnames(options));

            for nameIndex = 1:numel(names)
                name = names(nameIndex);
                obj.(name) = options.(name);
            end

        end % constructor

    end % methods

end % classdef
