classdef MainAppCompositionRoot
    % MAINAPPCOMPOSITIONROOT Constructs stable main application dependencies.

    methods (Static)

        function dependencies = create()

            dependencies = openmebius.bootstrap.MainAppDependencies( ...
                Session = openmebius.application.session ...
                    .MainApplicationSession(), ...
                MainPresenter = openmebius.presentation.main ...
                    .MainPresenter(), ...
                ProjectPresenter = openmebius.presentation.project ...
                    .ProjectPresenter(), ...
                ModelPresenter = openmebius.presentation.model ...
                    .ModelPresenter(), ...
                LabelConfigPresenter = openmebius.presentation.model ...
                    .LabelConfigPresenter(), ...
                BatchPresenter = openmebius.presentation.batch ...
                    .BatchPresenter(), ...
                RunConfigPresenter = openmebius.presentation.batch ...
                    .RunConfigPresenter(), ...
                BatchExperimentSelectionEditorPresenter = ...
                    openmebius.presentation.batch ...
                    .BatchExperimentSelectionEditorPresenter(), ...
                ExperimentPresenter = openmebius.presentation.experiment ...
                    .ExperimentPresenter(), ...
                ResultPresenter = openmebius.presentation.result ...
                    .ResultPresenter(), ...
                ResultPlotPresenter = openmebius.presentation.result ...
                    .ResultPlotPresenter(), ...
                ProgressBarFactory = openmebius.presentation.main ...
                    .ProgressBarFactory(), ...
                ProjectOperationController = openmebius.application ...
                    .project.ProjectOperationController(), ...
                ModelOperationController = openmebius.application.model ...
                    .ModelOperationController(), ...
                LabelConfigurationLaunchController = ...
                    openmebius.application.model ...
                    .LabelConfigurationLaunchController(), ...
                BatchOperationController = openmebius.application.batch ...
                    .BatchOperationController(), ...
                BatchConfigurationController = ...
                    openmebius.application.batch ...
                    .BatchConfigurationController(), ...
                BatchConfigurationLaunchController = ...
                    openmebius.application.batch ...
                    .BatchConfigurationLaunchController(), ...
                BatchExperimentSelectionEditorController = ...
                    openmebius.application.batch ...
                    .BatchExperimentSelectionEditorController(), ...
                BatchRunController = openmebius.application.batch ...
                    .BatchRunController(), ...
                ResultOperationController = openmebius.application.result ...
                    .ResultOperationController(), ...
                ExperimentImportController = ...
                    openmebius.application.experiment ...
                    .ExperimentImportController(), ...
                ExperimentCalculationController = ...
                    openmebius.application.experiment ...
                    .ExperimentCalculationController(), ...
                ExperimentEditController = ...
                    openmebius.application.experiment ...
                    .ExperimentEditController(), ...
                SlackNotifier = openmebius.infrastructure.notification ...
                    .SlackWebhookNotifier());

        end % create

    end % methods (Static)

end % classdef
