classdef MainAppDependencies
    % MAINAPPDEPENDENCIES Stable controllers and presenters for the main app.

    properties (SetAccess = private)
        Session openmebius.application.session.MainApplicationSession
        MainPresenter openmebius.presentation.main.MainPresenter
        ProjectPresenter openmebius.presentation.project.ProjectPresenter
        ModelPresenter openmebius.presentation.model.ModelPresenter
        LabelConfigPresenter openmebius.presentation.model.LabelConfigPresenter
        BatchPresenter openmebius.presentation.batch.BatchPresenter
        RunConfigPresenter openmebius.presentation.batch.RunConfigPresenter
        BatchExperimentSelectionEditorPresenter ...
            openmebius.presentation.batch ...
            .BatchExperimentSelectionEditorPresenter
        ExperimentPresenter openmebius.presentation.experiment ...
            .ExperimentPresenter
        ResultPresenter openmebius.presentation.result.ResultPresenter
        ResultPlotPresenter openmebius.presentation.result.ResultPlotPresenter
        ProgressBarFactory openmebius.presentation.main.ProgressBarFactory
        ProjectOperationController openmebius.application.project ...
            .ProjectOperationController
        ModelOperationController openmebius.application.model ...
            .ModelOperationController
        LabelConfigurationLaunchController openmebius.application.model ...
            .LabelConfigurationLaunchController
        BatchOperationController openmebius.application.batch ...
            .BatchOperationController
        BatchConfigurationController openmebius.application.batch ...
            .BatchConfigurationController
        BatchConfigurationLaunchController openmebius.application.batch ...
            .BatchConfigurationLaunchController
        BatchExperimentSelectionEditorController ...
            openmebius.application.batch ...
            .BatchExperimentSelectionEditorController
        BatchRunController openmebius.application.batch.BatchRunController
        ResultOperationController openmebius.application.result ...
            .ResultOperationController
        ExperimentImportController openmebius.application.experiment ...
            .ExperimentImportController
        ExperimentCalculationController openmebius.application.experiment ...
            .ExperimentCalculationController
        ExperimentEditController openmebius.application.experiment ...
            .ExperimentEditController
        SlackNotifier openmebius.infrastructure.notification ...
            .SlackWebhookNotifier
    end

    methods

        function obj = MainAppDependencies(options)

            arguments
                options.Session (1, 1) openmebius.application.session ...
                    .MainApplicationSession
                options.MainPresenter (1, 1) openmebius.presentation ...
                    .main.MainPresenter
                options.ProjectPresenter (1, 1) openmebius.presentation ...
                    .project.ProjectPresenter
                options.ModelPresenter (1, 1) openmebius.presentation ...
                    .model.ModelPresenter
                options.LabelConfigPresenter (1, 1) ...
                    openmebius.presentation.model.LabelConfigPresenter
                options.BatchPresenter (1, 1) openmebius.presentation ...
                    .batch.BatchPresenter
                options.RunConfigPresenter (1, 1) openmebius.presentation ...
                    .batch.RunConfigPresenter
                options.BatchExperimentSelectionEditorPresenter (1, 1) ...
                    openmebius.presentation.batch ...
                    .BatchExperimentSelectionEditorPresenter
                options.ExperimentPresenter (1, 1) ...
                    openmebius.presentation.experiment.ExperimentPresenter
                options.ResultPresenter (1, 1) openmebius.presentation ...
                    .result.ResultPresenter
                options.ResultPlotPresenter (1, 1) ...
                    openmebius.presentation.result.ResultPlotPresenter
                options.ProgressBarFactory (1, 1) ...
                    openmebius.presentation.main.ProgressBarFactory
                options.ProjectOperationController (1, 1) ...
                    openmebius.application.project.ProjectOperationController
                options.ModelOperationController (1, 1) ...
                    openmebius.application.model.ModelOperationController
                options.LabelConfigurationLaunchController (1, 1) ...
                    openmebius.application.model ...
                    .LabelConfigurationLaunchController
                options.BatchOperationController (1, 1) ...
                    openmebius.application.batch.BatchOperationController
                options.BatchConfigurationController (1, 1) ...
                    openmebius.application.batch.BatchConfigurationController
                options.BatchConfigurationLaunchController (1, 1) ...
                    openmebius.application.batch ...
                    .BatchConfigurationLaunchController
                options.BatchExperimentSelectionEditorController (1, 1) ...
                    openmebius.application.batch ...
                    .BatchExperimentSelectionEditorController
                options.BatchRunController (1, 1) ...
                    openmebius.application.batch.BatchRunController
                options.ResultOperationController (1, 1) ...
                    openmebius.application.result.ResultOperationController
                options.ExperimentImportController (1, 1) ...
                    openmebius.application.experiment ...
                    .ExperimentImportController
                options.ExperimentCalculationController (1, 1) ...
                    openmebius.application.experiment ...
                    .ExperimentCalculationController
                options.ExperimentEditController (1, 1) ...
                    openmebius.application.experiment ...
                    .ExperimentEditController
                options.SlackNotifier (1, 1) ...
                    openmebius.infrastructure.notification ...
                    .SlackWebhookNotifier
            end

            names = string(fieldnames(options));

            for nameIndex = 1:numel(names)
                name = names(nameIndex);
                obj.(name) = options.(name);
            end

        end % constructor

    end % methods

end % classdef
