classdef MainAppCompositionRoot
    % MAINAPPCOMPOSITIONROOT Constructs stable main application dependencies.

    methods (Static)

        function dependencies = create()

            session = openmebius.application.session ...
                .MainApplicationSession();
            projectController = openmebius.application.project ...
                .ProjectOperationController();
            modelController = openmebius.application.model ...
                .ModelOperationController();
            labelLaunchController = openmebius.application.model ...
                .LabelConfigurationLaunchController();
            batchController = openmebius.application.batch ...
                .BatchOperationController();
            batchLaunchController = openmebius.application.batch ...
                .BatchConfigurationLaunchController();
            batchSelectionController = openmebius.application.batch ...
                .BatchExperimentSelectionEditorController();
            batchRunController = openmebius.application.batch ...
                .BatchRunController();
            resultController = openmebius.application.result ...
                .ResultOperationController();
            experimentImportController = ...
                openmebius.application.experiment ...
                    .ExperimentImportController();
            experimentCalculationController = ...
                openmebius.application.experiment ...
                    .ExperimentCalculationController();
            experimentEditController = ...
                openmebius.application.experiment ...
                    .ExperimentEditController();
            applicationController = openmebius.application.main ...
                .MainApplicationController( ...
                    Session = session, ...
                    ProjectController = projectController, ...
                    ModelController = modelController, ...
                    LabelLaunchController = labelLaunchController, ...
                    ExperimentImportController = ...
                        experimentImportController, ...
                    ExperimentCalculationController = ...
                        experimentCalculationController, ...
                    ExperimentEditController = experimentEditController, ...
                    BatchController = batchController, ...
                    BatchLaunchController = batchLaunchController, ...
                    BatchSelectionController = batchSelectionController, ...
                    BatchRunController = batchRunController, ...
                    ResultController = resultController);

            dependencies = openmebius.bootstrap.MainAppDependencies( ...
                ApplicationController = applicationController, ...
                MainPresenter = openmebius.presentation.main ...
                    .MainPresenter(), ...
                ProjectPresenter = openmebius.presentation.project ...
                    .ProjectPresenter(), ...
                ModelPresenter = openmebius.presentation.model ...
                    .ModelPresenter(), ...
                LabelConfigPresenter = openmebius.presentation.model ...
                    .LabelConfigPresenter(), ...
                BatchPresenter = openmebius.presentation.batch ...
                    .BatchPresenter(), ...
                RunConfigPresenter = openmebius.presentation.batch ...
                    .RunConfigPresenter(), ...
                BatchExperimentSelectionEditorPresenter = ...
                    openmebius.presentation.batch ...
                    .BatchExperimentSelectionEditorPresenter(), ...
                ExperimentPresenter = openmebius.presentation.experiment ...
                    .ExperimentPresenter(), ...
                ResultPresenter = openmebius.presentation.result ...
                    .ResultPresenter(), ...
                ResultPlotPresenter = openmebius.presentation.result ...
                    .ResultPlotPresenter(), ...
                ProgressBarFactory = openmebius.presentation.main ...
                    .ProgressBarFactory(), ...
                ChildAppHost = openmebius.presentation.lifecycle ...
                    .ChildAppHost(), ...
                BatchConfigurationController = ...
                    openmebius.application.batch ...
                    .BatchConfigurationController(), ...
                BatchExperimentSelectionEditorController = ...
                    batchSelectionController, ...
                ExperimentEditController = experimentEditController, ...
                SlackNotifier = openmebius.infrastructure.notification ...
                    .SlackWebhookNotifier());

        end % create

    end % methods (Static)

end % classdef
