classdef MainAppCompositionRoot
    % MAINAPPCOMPOSITIONROOT Constructs stable main application dependencies.

    methods (Static)

        function dependencies = create(options)

            arguments
                options.BatchRunController (1, 1) ...
                    openmebius.application.batch.BatchRunController = ...
                    openmebius.application.batch.BatchRunController()
                options.ResultController (1, 1) ...
                    openmebius.application.result ...
                    .ResultOperationController = ...
                    openmebius.application.result ...
                    .ResultOperationController()
                options.NotificationDispatcher = []
                options.SlackNotifier = []
            end

            slackNotifier = options.SlackNotifier;

            if isempty(slackNotifier)
                slackNotifier = openmebius.infrastructure.notification ...
                    .SlackWebhookNotifier();
            end

            notificationDispatcher = options.NotificationDispatcher;

            if isempty(notificationDispatcher)
                notificationDispatcher = openmebius.infrastructure ...
                    .notification.NotificationDispatcher();
                notificationDispatcher.addSink( ...
                    openmebius.infrastructure.notification.TextFileSink());
                notificationDispatcher.addSink( ...
                    openmebius.infrastructure.notification.ConsoleSink());
                notificationDispatcher.addSink( ...
                    openmebius.infrastructure.notification ...
                    .SlackSink(slackNotifier));
            end

            notificationPublisher = notificationDispatcher.reporter();

            session = openmebius.application.session ...
                .MainApplicationSession();
            modelRepository = openmebius.infrastructure.model ...
                .ModelRepository( ...
                    NotificationPublisher = notificationPublisher);
            workbookStore = openmebius.infrastructure.experiment ...
                .ExperimentWorkbookStore( ...
                    NotificationPublisher = notificationPublisher);
            experimentRepository = openmebius.infrastructure.experiment ...
                .ExperimentRepository( ...
                    WorkbookStore = workbookStore, ...
                    NotificationPublisher = notificationPublisher);
            resultRepository = openmebius.infrastructure.result ...
                .ResultRepository( ...
                    NotificationPublisher = notificationPublisher);
            batchRepository = openmebius.infrastructure.batch ...
                .BatchRepository( ...
                    NotificationPublisher = notificationPublisher);
            artifactRepository = openmebius.infrastructure.project ...
                .ProjectArtifactRepository( ...
                    ModelRepository = modelRepository, ...
                    ExperimentRepository = experimentRepository, ...
                    BatchRepository = batchRepository, ...
                    ResultRepository = resultRepository);
            projectController = openmebius.application.project ...
                .ProjectOperationController( ...
                    ArtifactRepository = artifactRepository);
            modelController = openmebius.application.model ...
                .ModelOperationController();
            labelLaunchController = openmebius.application.model ...
                .LabelConfigurationLaunchController();
            batchController = openmebius.application.batch ...
                .BatchOperationController();
            batchLaunchController = openmebius.application.batch ...
                .BatchConfigurationLaunchController();
            batchSelectionController = openmebius.application.batch ...
                .BatchExperimentSelectionEditorController();
            batchRunController = options.BatchRunController;
            resultController = options.ResultController;
            experimentImportController = ...
                openmebius.application.experiment ...
                    .ExperimentImportController();
            experimentCalculationController = ...
                openmebius.application.experiment ...
                    .ExperimentCalculationController( ...
                        Service = openmebius.application.experiment ...
                            .ExperimentCalculationService( ...
                                NotificationEmitter = openmebius ...
                                .application.notification ...
                                .NotificationEmitter( ...
                                    Publisher = notificationPublisher, ...
                                    Source = ...
                                    "ExperimentCalculationService")));
            experimentEditController = ...
                openmebius.application.experiment ...
                    .ExperimentEditController();
            applicationController = openmebius.application.main ...
                .MainApplicationController( ...
                    Session = session, ...
                    ProjectController = projectController, ...
                    ModelController = modelController, ...
                    LabelLaunchController = labelLaunchController, ...
                    ExperimentImportController = ...
                        experimentImportController, ...
                    ExperimentCalculationController = ...
                        experimentCalculationController, ...
                    ExperimentEditController = experimentEditController, ...
                    BatchController = batchController, ...
                    BatchLaunchController = batchLaunchController, ...
                    BatchSelectionController = batchSelectionController, ...
                    BatchRunController = batchRunController, ...
                    ResultController = resultController);

            dependencies = openmebius.bootstrap.MainAppDependencies( ...
                ApplicationController = applicationController, ...
                MainPresenter = openmebius.presentation.main ...
                    .MainPresenter(), ...
                ProjectPresenter = openmebius.presentation.project ...
                    .ProjectPresenter(), ...
                ModelPresenter = openmebius.presentation.model ...
                    .ModelPresenter(), ...
                LabelConfigPresenter = openmebius.presentation.model ...
                    .LabelConfigPresenter(), ...
                BatchPresenter = openmebius.presentation.batch ...
                    .BatchPresenter(), ...
                RunConfigPresenter = openmebius.presentation.batch ...
                    .RunConfigPresenter(), ...
                BatchExperimentSelectionEditorPresenter = ...
                    openmebius.presentation.batch ...
                    .BatchExperimentSelectionEditorPresenter(), ...
                ExperimentPresenter = openmebius.presentation.experiment ...
                    .ExperimentPresenter(), ...
                ResultPresenter = openmebius.presentation.result ...
                    .ResultPresenter(), ...
                ResultPlotPresenter = openmebius.presentation.result ...
                    .ResultPlotPresenter(), ...
                ProgressBarFactory = openmebius.presentation.main ...
                    .ProgressBarFactory(), ...
                ChildAppHost = openmebius.presentation.lifecycle ...
                    .ChildAppHost(), ...
                BatchConfigurationController = ...
                    openmebius.application.batch ...
                    .BatchConfigurationController(), ...
                BatchExperimentSelectionEditorController = ...
                    batchSelectionController, ...
                ExperimentEditController = experimentEditController, ...
                SlackNotifier = slackNotifier, ...
                NotificationDispatcher = notificationDispatcher);

        end % create

    end % methods (Static)

end % classdef
