classdef ExperimentWorkbookStore < handle
    % EXPERIMENTWORKBOOKSTORE Maps experiment workbooks to persistence DTOs.

    properties (Access = private)
        NotificationEmitter openmebius.application.notification ...
            .NotificationEmitter
    end

    properties (Constant, Access = private)
        SheetNames = [ ...
                          "info", ...
                          "substrate", ...
                          "MS", ...
                          "MS (Normalized)", ...
                          "MDV", ...
                          "MDV (biomass)", ...
                          "MDV optimization", ...
                      "Enrichment"]
        SheetWritesRowNames = [ ...
                                   false, true, true, true, true, true, true, true]
        InfoVariableNames = ["mu", "ODi", "ODf"]
        InfoVariableTypes = ["double", "double", "double"]
        SubstrateVariableNames = ["Uptake", "Label"]
        SubstrateVariableTypes = ["double", "string"]
    end

    methods

        function obj = ExperimentWorkbookStore(options)

            arguments
                options.NotificationPublisher (1, 1) function_handle = @(~) []
            end

            obj.NotificationEmitter = openmebius.application.notification ...
                .NotificationEmitter( ...
                Publisher = options.NotificationPublisher, ...
                Source = "ExperimentWorkbookStore");

        end % constructor

        function workbook = load(obj, pathFile)

            arguments
                obj
                pathFile (1, 1) string
            end

            obj.assertDirectory(pathFile);
            obj.publish( ...
                "info", ...
                "The directory " + string(fileparts(pathFile)) + " exists.");

            info = obj.loadInfo(pathFile);
            substrate = obj.loadSubstrate(pathFile);
            ms = obj.loadMS(pathFile);

            workbook = openmebius.infrastructure.experiment ...
                .ExperimentWorkbookData( ...
                Info = info, ...
                Substrate = substrate, ...
                MS = ms, ...
                MSNormalized = obj.readOptionalSheet( ...
                pathFile, "MS (Normalized)", ...
                obj.optionalSheetAliases("MS (Normalized)")), ...
                MDV = obj.readOptionalSheet( ...
                pathFile, "MDV", obj.optionalSheetAliases("MDV")), ...
                MDVBiomass = obj.readOptionalSheet( ...
                pathFile, "MDV (biomass)", ...
                obj.optionalSheetAliases("MDV (biomass)")), ...
                MDVOptimization = obj.readOptionalSheet( ...
                pathFile, "MDV optimization", ...
                obj.optionalSheetAliases("MDV optimization")), ...
                Enrichment = obj.readOptionalSheet( ...
                pathFile, "Enrichment", ...
                obj.optionalSheetAliases("Enrichment")), ...
                DefaultSubstrateVariableNames = ...
                obj.SubstrateVariableNames, ...
                DefaultSubstrateVariableTypes = ...
                obj.SubstrateVariableTypes);

        end % load

        function save(obj, pathFile, workbook)

            arguments
                obj
                pathFile (1, 1) string
                workbook openmebius.infrastructure.experiment ...
                    .ExperimentWorkbookData
            end

            obj.assertDirectory(pathFile);
            workbookTables = { ...
                                  workbook.Info, ...
                                  workbook.Substrate, ...
                                  workbook.MS, ...
                                  workbook.MSNormalized, ...
                                  workbook.MDV, ...
                                  workbook.MDVBiomass, ...
                                  workbook.MDVOptimization, ...
                                  workbook.Enrichment};

            for iSheet = 1:numel(obj.SheetNames)
                [isSuccess, message] = obj.writeSheet( ...
                    pathFile, ...
                    workbookTables{iSheet}, ...
                    obj.SheetNames(iSheet), ...
                    WriteRowNames = obj.SheetWritesRowNames(iSheet));

                if ~isSuccess
                    obj.publish("error", string(message));
                    error( ...
                        "OpenMebius2:ExperimentWorkbookStore:" + ...
                        "WorkbookSaveFailed", ...
                        "%s", string(message));
                end

            end

        end % save

        function data = readSheet(~, pathFile, sheetName, options)

            arguments
                ~
                pathFile (1, 1) string
                sheetName (1, 1) string
                options.ReadRowNames (1, 1) logical = true
                options.ReadVariableNames (1, 1) logical = true
                options.CheckVariable (1, 1) logical = true
                options.RefTypes (1, :) string = []
                options.RefVariableNames (1, :) string = []
            end

            try
                data = openmebius.infrastructure.filesystem.ExcelFileStore ...
                    .readTable( ...
                    pathFile, ...
                    sheetName, ...
                    ReadRowNames = options.ReadRowNames, ...
                    ReadVariableNames = options.ReadVariableNames, ...
                    CheckVariable = options.CheckVariable, ...
                    RefTypes = options.RefTypes, ...
                    RefVariableNames = options.RefVariableNames);
            catch ME
                openmebius.infrastructure.experiment.ExperimentWorkbookStore ...
                    .throwWorkbookReadError(pathFile, ME);
            end

        end % readSheet

        function data = readOptionalSheet( ...
                obj, pathFile, preferredSheetName, aliases, options)

            arguments
                obj
                pathFile (1, 1) string
                preferredSheetName (1, 1) string
                aliases (1, :) string = preferredSheetName
                options.ReadRowNames (1, 1) logical = true
                options.ReadVariableNames (1, 1) logical = true
            end

            sheetName = obj.resolveSheetName( ...
                pathFile, preferredSheetName, aliases);

            try
                data = obj.readSheet( ...
                    pathFile, ...
                    sheetName, ...
                    ReadRowNames = options.ReadRowNames, ...
                    ReadVariableNames = options.ReadVariableNames, ...
                    CheckVariable = false);
            catch
                data = table();
            end

        end % readOptionalSheet

        function [isSuccess, message] = writeSheet( ...
                ~, pathFile, data, sheetName, options)

            arguments
                ~
                pathFile (1, 1) string
                data
                sheetName (1, 1) string
                options.WriteRowNames (1, 1) logical = true
                options.WriteVariableNames (1, 1) logical = true
            end

            [isSuccess, message] = ...
                openmebius.infrastructure.filesystem.ExcelFileStore ...
                .writeTable( ...
                pathFile, ...
                data, ...
                sheetName, ...
                WriteRowNames = options.WriteRowNames, ...
                WriteVariableNames = options.WriteVariableNames);

        end % writeSheet

        function sheetNames = listSheets(~, pathFile)

            arguments
                ~
                pathFile (1, 1) string
            end

            try
                sheetNames = string(sheetnames(pathFile));
                sheetNames = sheetNames(:);
                return
            catch
            end

            try
                [~, sheets] = xlsfinfo(pathFile);
                sheetNames = string(sheets);
                sheetNames = sheetNames(:);
            catch
                sheetNames = strings(0, 1);
            end

        end % listSheets

        function sheetName = resolveSheetName( ...
                obj, pathFile, preferredSheetName, aliases)

            arguments
                obj
                pathFile (1, 1) string
                preferredSheetName (1, 1) string
                aliases (1, :) string = preferredSheetName
            end

            sheetName = preferredSheetName;
            workbookSheets = obj.listSheets(pathFile);

            if isempty(workbookSheets)
                return
            end

            normalizedWorkbookSheets = ...
                openmebius.infrastructure.experiment.ExperimentWorkbookStore ...
                .normalizeSheetName(workbookSheets);
            aliases = unique([preferredSheetName aliases], "stable");

            for iAlias = 1:numel(aliases)
                normalizedAlias = ...
                    openmebius.infrastructure.experiment ...
                    .ExperimentWorkbookStore ...
                    .normalizeSheetName(aliases(iAlias));
                index = find(normalizedWorkbookSheets == normalizedAlias, 1);

                if ~isempty(index)
                    sheetName = workbookSheets(index);
                    return
                end

            end

        end % resolveSheetName

    end % methods

    methods (Access = private)

        function data = loadInfo(obj, pathFile)

            try
                data = obj.readSheet( ...
                    pathFile, ...
                    "info", ...
                    ReadRowNames = false, ...
                    RefVariableNames = obj.InfoVariableNames, ...
                    RefTypes = obj.InfoVariableTypes);
                obj.publish( ...
                    "info", pathFile + "/info is successfully imported.");
            catch ME
                data = obj.createInfoTable();
                obj.publish( ...
                    "warning", ...
                    "Failed to load info data from the Excel file. " + ...
                    "A new sheet has been created. " + string(ME.message));
            end

        end % loadInfo

        function data = loadSubstrate(obj, pathFile)

            try
                data = obj.readSheet( ...
                    pathFile, ...
                    "substrate", ...
                    ReadRowNames = true, ...
                    RefVariableNames = obj.SubstrateVariableNames, ...
                    RefTypes = obj.SubstrateVariableTypes);
                obj.publish( ...
                    "info", pathFile + "/substrate is successfully imported.");
            catch ME
                data = obj.createSubstrateTable();
                obj.publish( ...
                    "warning", ...
                    "Failed to load substrate data from the Excel file. " + ...
                    "A new sheet has been created. " + string(ME.message));
            end

        end % loadSubstrate

        function data = loadMS(obj, pathFile)

            try
                data = obj.readSheet( ...
                    pathFile, "MS", ReadRowNames = true, ...
                    CheckVariable = false);
                obj.publish( ...
                    "info", pathFile + "/MS is successfully imported.");
            catch ME
                data = table();
                obj.publish( ...
                    "warning", ...
                    "The MS sheet was not loaded. Stored MDV-derived " + ...
                    "sheets will still be checked. " + string(ME.message));
            end

        end % loadMS

        function data = createInfoTable(obj)

            data = table( ...
                'Size', [1, 3], ...
                'VariableNames', obj.InfoVariableNames, ...
                'VariableTypes', obj.InfoVariableTypes);

        end % createInfoTable

        function data = createSubstrateTable(obj)

            data = table( ...
                'Size', [0, 2], ...
                'VariableNames', obj.SubstrateVariableNames, ...
                'VariableTypes', obj.SubstrateVariableTypes);

        end % createSubstrateTable

        function aliases = optionalSheetAliases(~, preferredSheetName)

            switch preferredSheetName
                case "MS (Normalized)"
                    aliases = [ ...
                                   "MS (Normalized)", ...
                                   "MS Normalized", ...
                                   "MS normalized data", ...
                                   "MS normarized data", ...
                                   "MSNormalized", ...
                                   "MS_Normalized", ...
                               "正規化MS"];
                case "MDV"
                    aliases = [ ...
                                   "MDV", ...
                                   "MDV (Mass distribution vectors)", ...
                                   "Mass distribution vectors", ...
                               "Mass distribution vector"];
                case "MDV (biomass)"
                    aliases = [ ...
                                   "MDV (biomass)", ...
                                   "MDV (Biomass)", ...
                                   "MDV biomass", ...
                                   "MDVBiomass", ...
                                   "MDV_Biomass", ...
                                   "Biomass corrected MDV", ...
                                   "Biomass-corrected MDV", ...
                                   "Biomass-corrected mass distribution vectors", ...
                                   "Corrected MDV", ...
                                   "corrected MDV", ...
                                   "補正済みMDV", ...
                               "バイオマス補正MDV"];
                case "MDV optimization"
                    aliases = [ ...
                                   "MDV optimization", ...
                                   "MDV Optimization", ...
                                   "MDVOptimization", ...
                               "MDV_Optimization"];
                case "Enrichment"
                    aliases = [ ...
                                   "Enrichment", ...
                                   "Atom enrichment", ...
                                   "Enrichment data", ...
                               "濃縮率"];
                otherwise
                    aliases = preferredSheetName;
            end

            aliases = unique([preferredSheetName aliases], "stable");

        end % optionalSheetAliases

        function assertDirectory(~, pathFile)

            directory = string(fileparts(pathFile));

            if directory == ""
                directory = ".";
            end

            if ~isfolder(directory)
                error( ...
                    "OpenMebius2:ExperimentWorkbookStore:DirectoryNotFound", ...
                    "Experiment directory does not exist: %s", directory);
            end

        end % assertDirectory

        function publish(obj, level, message)

            obj.NotificationEmitter.report( ...
                string(level), ...
                string(message), ...
                Code = "experiment.workbook", ...
                Audience = "developer", ...
                Kind = "diagnostic");

        end % publish

    end % methods (Access = private)

    methods (Static, Access = private)

        function throwWorkbookReadError(pathFile, cause)

            switch string(cause.identifier)
                case "OpenMebius2:ExcelFileStore:FileNotFound"
                    error( ...
                        "OpenMebius2:ExperimentWorkbookStore:" + ...
                        "WorkbookNotFound", ...
                        "The file %s does not exist.", pathFile);
                case "OpenMebius2:ExcelFileStore:VariableMismatch"
                    error( ...
                        "OpenMebius2:ExperimentWorkbookStore:" + ...
                        "WorkbookVariableMismatch", ...
                        "%s", string(cause.message));
                otherwise
                    error( ...
                        "OpenMebius2:ExperimentWorkbookStore:" + ...
                        "InvalidWorkbook", ...
                        "The file %s is not a valid Excel file.", pathFile);
            end

        end % throwWorkbookReadError

        function normalized = normalizeSheetName(sheetNames)

            normalized = lower(string(sheetNames));
            normalized = regexprep(normalized, "[\s_\-\(\)]", "");

        end % normalizeSheetName

    end % methods (Static, Access = private)

end % classdef
