classdef AnalysisMetadataFactory
    % ANALYSISMETADATAFACTORY
    % Builds reproducibility metadata for one analysis run.

    methods (Static)

        function metadata = create( ...
                config, ...
                batchId, ...
                model, ...
                experimentNames, ...
                provenance, ...
                startedAtUtc, ...
                randomState)

            arguments
                config (1, 1) struct
                batchId
                model
                experimentNames
                provenance (1, 1) struct
                startedAtUtc (1, 1) string
                randomState (1, 1) struct
            end

            experimentNames = ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, ...
                'experimentNames', ...
                string(experimentNames(:)));
            experimentFileNames = ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, ...
                'experimentFileNames', ...
                strings(size(experimentNames)));
            experimentHashes = ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, ...
                'experimentSha256', ...
                strings(size(experimentNames)));
            modelFileName = ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, ...
                'modelFileName', ...
                "");
            modelHash = ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, ...
                'modelSha256', ...
                "");

            if strlength(string(modelFileName)) == 0 && ...
                    isobject(model) && isprop(model, 'pathModel')
                modelPath = string(model.pathModel);
                [~, modelName, modelExtension] = fileparts(modelPath);
                modelFileName = string(modelName) + string(modelExtension);
                modelHash = ...
                    openmebius.infrastructure.filesystem.FileHasher.hashFile( ...
                    modelPath);
            end

            semanticConfig = ...
                openmebius.domain.batch.BatchIdentity.semanticConfig(config);
            defaultContentHash = ...
                openmebius.domain.batch.BatchIdentity.contentHash( ...
                config, ...
                string(modelHash), ...
                string(experimentNames), ...
                string(experimentHashes));

            metadata = struct( ...
                'schemaVersion', ...
                double( ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, 'schemaVersion', 1)), ...
                'batchId', ...
                string( ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, 'batchId', batchId)), ...
                'contentHash', ...
                string( ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, 'contentHash', defaultContentHash)), ...
                'contentHashVersion', ...
                double( ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, ...
                'contentHashVersion', ...
                openmebius.domain.batch.BatchIdentity.ContentHashVersion)), ...
                'configJson', ...
                string( ...
                openmebius.application.analysis.AnalysisMetadataFactory ...
                .provenanceValue( ...
                provenance, ...
                'configJson', ...
                openmebius.domain.batch.BatchIdentity.canonicalJson( ...
                semanticConfig))), ...
                'openMebius2Version', System.getCurrentVersion(), ...
                'matlabRelease', string(version('-release')), ...
                'matlabVersion', string(version), ...
                'toolboxesJson', string(jsonencode(ver)), ...
                'modelFileName', string(modelFileName), ...
                'modelSha256', string(modelHash), ...
                'experimentNames', string(experimentNames(:)), ...
                'experimentFileNames', string(experimentFileNames(:)), ...
                'experimentSha256', string(experimentHashes(:)), ...
                'randomType', string(randomState.Type), ...
                'randomSeed', uint32(randomState.Seed), ...
                'randomState', uint32(randomState.State(:)), ...
                'startedAtUtc', startedAtUtc);

        end % create

    end % methods (Static)

    methods (Static, Access = private)

        function value = provenanceValue(provenance, fieldName, defaultValue)

            value = defaultValue;

            if isstruct(provenance) && isfield(provenance, fieldName) && ...
                    ~isempty(provenance.(fieldName))
                value = provenance.(fieldName);
            end

        end % provenanceValue

    end % methods (Static, Access = private)

end % classdef
