classdef AnalysisRunLifecycle
    % ANALYSISRUNLIFECYCLE
    % Creates and persists reproducibility metadata for one analysis run.

    properties (SetAccess = private)
        Repository
    end

    methods

        function obj = AnalysisRunLifecycle(options)

            arguments
                options.Repository = ...
                    openmebius.infrastructure.result.AnalysisRunRepository()
            end

            obj.Repository = options.Repository;

        end % constructor

        function [metadata, isSuccess, message] = start( ...
                obj, config, batchID, model, experimentNames, ...
                provenance, startedAtUtc, randomState, ...
                resultLocation, resultFilePath)

            metadata = openmebius.application.analysis ...
                .AnalysisMetadataFactory.create( ...
                config, ...
                batchID, ...
                model, ...
                experimentNames, ...
                provenance, ...
                startedAtUtc, ...
                randomState);
            [isSuccess, message] = obj.Repository.writeStarted( ...
                resultLocation, resultFilePath, metadata);

        end % start

        function errors = finish( ...
                obj, resultLocation, resultFilePath, metadata, ...
                isError, isCanceled, options)

            arguments
                obj (1, 1) ...
                    openmebius.application.analysis.AnalysisRunLifecycle
                resultLocation
                resultFilePath
                metadata (1, 1) struct
                isError (1, 1) logical
                isCanceled (1, 1) logical
                options.FinishedAtUtc (1, 1) string = string(datetime( ...
                    "now", ...
                    "TimeZone", "UTC", ...
                    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"))
            end

            errors = obj.Repository.writeCompleted( ...
                resultLocation, ...
                resultFilePath, ...
                metadata, ...
                options.FinishedAtUtc, ...
                isError, ...
                isCanceled);

        end % finish

    end % methods

end % classdef
