classdef ConfidenceIntervalSettingsMapper
    % CONFIDENCEINTERVALSETTINGSMAPPER Maps Batch CI structs to domain values.

    methods (Static)

        function settings = fromBatchConfig(config)

            arguments
                config (1, 1) struct
            end

            defaults = openmebius.domain.batch.BatchConfig.defaultConfig();
            enabled = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.mapLogical( ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'isCalcCI', defaults.isCalcCI), ...
            "isCalcCI");
            ciConfig = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.structOrDefault( ...
                config, 'CIConf', defaults.CIConf);
            method = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.mapMethod( ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                ciConfig, 'algorithm', defaults.CIConf.algorithm));
            monteCarlo = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.mapMonteCarlo( ...
                ciConfig, defaults.CIConf.MC);
            gridSearch = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.mapGridSearch( ...
                ciConfig, defaults.CIConf.grid);
            settings = openmebius.mfa.ConfidenceIntervalSettings( ...
                Enabled = enabled, ...
                Method = method, ...
                MonteCarloSettings = monteCarlo, ...
                GridSearchSettings = gridSearch);

        end

    end

    methods (Static, Access = private)

        function settings = mapMonteCarlo(ciConfig, defaults)

            config = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.structOrDefault( ...
                ciConfig, 'MC', defaults);

            if isfield(config, 'optimizationProcedure') && ...
                    ~isempty(config.optimizationProcedure)
                procedureValue = config.optimizationProcedure;
            elseif isfield(config, 'procedure') && ...
                    ~isempty(config.procedure)
                procedureValue = config.procedure;
            else
                procedureValue = defaults.optimizationProcedure;
            end

            settings = openmebius.mfa ...
                .MonteCarloConfidenceIntervalSettings( ...
                IterationCount = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'iteration', defaults.iteration), ...
                FixMDV = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.mapLogical( ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'fixMID', defaults.fixMID), ...
            "CIConf.MC.fixMID"), ...
                StandardDeviation = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'MIDSD', defaults.MIDSD), ...
                Procedure = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.mapProcedure( ...
                procedureValue), ...
                TerminationTolerance = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'terminationTolerance', ...
                defaults.terminationTolerance), ...
                ProximityThreshold = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'proximityThreshold', ...
                defaults.proximityThreshold), ...
                CertainThreshold = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'certainThreshold', ...
                defaults.certainThreshold), ...
                TrialCount = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'theNumberOfRuns', ...
                defaults.theNumberOfRuns), ...
                CalculationMethod = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper ...
                .mapCalculationMethod( ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'calculationMethod', ...
                defaults.calculationMethod)));

        end

        function settings = mapGridSearch(ciConfig, defaults)

            config = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.structOrDefault( ...
                ciConfig, 'grid', defaults);
            [intervalMode, executionMode] = ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.mapGridModes( ...
                config, defaults);
            threshold = lower(strtrim(string( ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'threshold', defaults.threshold))));

            switch threshold
                case {"chi-sq", "chi-squared"}
                    threshold = "chi-sq";
                case {"f-distribution", "f distribution"}
                    threshold = "f-distribution";
                otherwise
                    error( ...
                        "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                        "UnknownGridThreshold", ...
                        "Unknown grid-search threshold: %s.", threshold);
            end

            settings = openmebius.mfa ...
                .GridSearchConfidenceIntervalSettings( ...
                IntervalMode = intervalMode, ...
                ExecutionMode = executionMode, ...
                Delta = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'delta', defaults.delta), ...
                Threshold = threshold, ...
                PointCount = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'points', defaults.points), ...
                IterationCount = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'iteration', defaults.iteration), ...
                MaximumTrial = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'maximumTrial', defaults.maximumTrial), ...
                MinimumFluxRange = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'minimumFluxRange', ...
                defaults.minimumFluxRange), ...
                Alpha = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'alpha', defaults.alpha));

        end

        function [intervalMode, executionMode] = ...
                mapGridModes(config, defaults)

            if isfield(config, 'intervalMode') && ...
                    ~isempty(config.intervalMode)
                intervalValue = config.intervalMode;
            elseif isfield(config, 'isParallel') && ...
                    ~isempty(config.isParallel)
                automatic = openmebius.application.analysis ...
                    .ConfidenceIntervalSettingsMapper.mapLogical( ...
                    config.isParallel, "CIConf.grid.isParallel");

                if automatic
                    intervalValue = "automatic";
                else
                    intervalValue = "fixed-delta";
                end

            else
                intervalValue = defaults.intervalMode;
            end

            intervalMode = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper ...
                .mapGridIntervalMode(intervalValue);
            executionMode = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper ...
                .mapGridExecutionMode( ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, 'executionMode', defaults.executionMode));

        end

        function mode = mapGridIntervalMode(value)

            candidate = lower(strtrim(string(value)));

            if ~isscalar(candidate)
                candidate = "";
            end

            switch candidate
                case "automatic"
                    mode = openmebius.mfa ...
                        .GridSearchIntervalMode.Automatic;
                case {"fixed-delta", "fixed delta"}
                    mode = openmebius.mfa ...
                        .GridSearchIntervalMode.FixedDelta;
                otherwise
                    error( ...
                        "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                        "UnknownGridIntervalMode", ...
                        "Unknown grid-search interval mode: %s.", ...
                        candidate);
            end

        end

        function mode = mapGridExecutionMode(value)

            candidate = lower(strtrim(string(value)));

            if ~isscalar(candidate)
                candidate = "";
            end

            switch candidate
                case "serial"
                    mode = openmebius.mfa ...
                        .GridSearchExecutionMode.Serial;
                case "parallel"
                    mode = openmebius.mfa ...
                        .GridSearchExecutionMode.Parallel;
                otherwise
                    error( ...
                        "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                        "UnknownGridExecutionMode", ...
                        "Unknown grid-search execution mode: %s.", ...
                        candidate);
            end

        end

        function method = mapMethod(value)

            candidate = lower(strtrim(string(value)));

            if ~isscalar(candidate)
                candidate = "";
            end

            switch candidate
                case "monte carlo"
                    method = openmebius.mfa ...
                        .ConfidenceIntervalMethod.MonteCarlo;
                case "grid search"
                    method = openmebius.mfa ...
                        .ConfidenceIntervalMethod.GridSearch;
                otherwise
                    error( ...
                        "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                        "UnknownMethod", ...
                        "Unknown confidence-interval method: %s.", ...
                        candidate);
            end

        end

        function procedure = mapProcedure(value)

            candidate = lower(strtrim(string(value)));

            if ~isscalar(candidate)
                candidate = "";
            end

            switch candidate
                case {"single", "single run"}
                    procedure = openmebius.mfa ...
                        .MonteCarloOptimizationProcedure.SingleRun;
                case {"multiple", "multiple run"}
                    procedure = openmebius.mfa ...
                        .MonteCarloOptimizationProcedure.MultipleRun;
                otherwise
                    error( ...
                        "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                        "UnknownProcedure", ...
                        "Unknown Monte Carlo procedure: %s.", candidate);
            end

        end

        function method = mapCalculationMethod(value)

            candidate = lower(strtrim(string(value)));

            if ~isscalar(candidate)
                candidate = "";
            end

            switch candidate
                case "discarding"
                    method = openmebius.mfa ...
                        .ConfidenceIntervalCalculationMethod.Discarding;
                case "mean-varianced"
                    method = openmebius.mfa ...
                        .ConfidenceIntervalCalculationMethod.MeanVarianced;
                otherwise
                    error( ...
                        "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                        "UnknownCalculationMethod", ...
                        "Unknown confidence-interval calculation " + ...
                        "method: %s.", candidate);
            end

        end

        function value = mapLogical(value, fieldName)

            if islogical(value) && isscalar(value)
                return
            end

            if isnumeric(value) && isscalar(value) && ...
                    isfinite(value) && ismember(value, [0, 1])
                value = logical(value);
                return
            end

            error( ...
                "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                "InvalidLogical", ...
                "%s must be a scalar logical value.", fieldName);

        end

        function value = structOrDefault(config, fieldName, defaultValue)

            value = openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper.valueOrDefault( ...
                config, fieldName, defaultValue);

            if ~isstruct(value) || ~isscalar(value)
                error( ...
                    "OpenMebius2:ConfidenceIntervalSettingsMapper:" + ...
                    "InvalidStruct", ...
                    "%s must be a scalar struct.", fieldName);
            end

        end

        function value = valueOrDefault(config, fieldName, defaultValue)

            value = defaultValue;

            if isfield(config, fieldName) && ~isempty(config.(fieldName))
                value = config.(fieldName);
            end

        end

    end

end
