classdef FluxAnalysisRunSettings
    % FLUXANALYSISRUNSETTINGS Immutable settings catalog for one analysis.

    properties (SetAccess = private)
        DistributionSettings = []
        DistributionFailureStage (1, 1) string = ""
        DistributionErrorMessage (1, 1) string = ""
        ConfidenceIntervalRunSettings = []
        ConfidenceIntervalErrorMessage (1, 1) string = ""
        NextExperimentRunSettings = []
        NextExperimentErrorMessage (1, 1) string = ""
    end

    methods

        function obj = FluxAnalysisRunSettings(options)

            arguments
                options.DistributionSettings = ...
                    openmebius.application.analysis.MFAAnalysisSettings()
                options.DistributionFailureStage (1, 1) string = ""
                options.DistributionErrorMessage (1, 1) string = ""
                options.ConfidenceIntervalRunSettings = ...
                    openmebius.application.analysis ...
                    .MFAConfidenceIntervalRunSettings()
                options.ConfidenceIntervalErrorMessage ...
                    (1, 1) string = ""
                options.NextExperimentRunSettings = ...
                    openmebius.application.analysis ...
                    .NextFluxExperimentRunSettings()
                options.NextExperimentErrorMessage ...
                    (1, 1) string = ""
            end

            obj.validateSection( ...
                options.DistributionSettings, ...
                'openmebius.application.analysis.MFAAnalysisSettings', ...
                options.DistributionErrorMessage, ...
                "distribution");
            obj.validateSection( ...
                options.ConfidenceIntervalRunSettings, ...
                ['openmebius.application.analysis.' ...
                'MFAConfidenceIntervalRunSettings'], ...
                options.ConfidenceIntervalErrorMessage, ...
                "confidence interval");
            obj.validateSection( ...
                options.NextExperimentRunSettings, ...
                ['openmebius.application.analysis.' ...
                'NextFluxExperimentRunSettings'], ...
                options.NextExperimentErrorMessage, ...
                "next experiment");

            hasDistribution = isa( ...
                options.DistributionSettings, ...
                'openmebius.application.analysis.MFAAnalysisSettings');

            if hasDistribution ~= ...
                    (options.DistributionFailureStage == "")
                error( ...
                    "OpenMebius2:FluxAnalysisRunSettings:" + ...
                    "InconsistentDistributionStage", ...
                    "A failed distribution mapping must provide a " + ...
                    "failure stage.");
            end

            obj.DistributionSettings = options.DistributionSettings;
            obj.DistributionFailureStage = ...
                options.DistributionFailureStage;
            obj.DistributionErrorMessage = ...
                options.DistributionErrorMessage;
            obj.ConfidenceIntervalRunSettings = ...
                options.ConfidenceIntervalRunSettings;
            obj.ConfidenceIntervalErrorMessage = ...
                options.ConfidenceIntervalErrorMessage;
            obj.NextExperimentRunSettings = ...
                options.NextExperimentRunSettings;
            obj.NextExperimentErrorMessage = ...
                options.NextExperimentErrorMessage;

        end

        function value = canRunDistribution(obj)

            value = ~isempty(obj.DistributionSettings);

        end

        function value = canCalculateConfidenceInterval(obj)

            value = ~isempty(obj.ConfidenceIntervalRunSettings);

        end

        function value = canSuggestNextExperiment(obj)

            value = ~isempty(obj.NextExperimentRunSettings);

        end

    end

    methods (Static, Access = private)

        function validateSection(settings, expectedClass, message, name)

            hasSettings = isa(settings, expectedClass);
            hasError = strlength(message) > 0;

            if hasSettings == hasError
                error( ...
                    "OpenMebius2:FluxAnalysisRunSettings:" + ...
                    "InconsistentSection", ...
                    "The %s section must contain either settings or " + ...
                    "an error message.", name);
            end

        end

    end

end
