classdef FluxAnalysisDependencies
    % FLUXANALYSISDEPENDENCIES
    % Composes the services used by the FluxAnalysis compatibility facade.

    properties (SetAccess = private)
        FluxVariabilitySolver
        FluxVariabilityProblemFactory
        FluxVariabilityWorkflow
        InitialFluxWorkflow
        MFAIterationRunner
        MFAObjectiveFactory
        MFAIterationService
        MFAWorkflow
        ConfidenceIntervalWorkflow
        ConfidenceIntervalApplicationWorkflow
        NextLabelExperimentWorkflow
        NextFluxExperimentWorkflow
        MFAInputValidator
        MFAInputPreparationWorkflow
        FluxDistributionWorkflow
        MFAFitStatistics
        MFAExperimentalDataBuilder
        MFAConstraintBuilder
        MFAExperimentListNormalizer
        SubstrateEMUFactory
        SteadyStateMDVPredictor
        EffluxPenaltyFactory
        InstationaryInputFactory
        MFAResultCoordinator
        AnalysisRunLifecycle
        RunContext (1, 1) ...
            openmebius.application.analysis.MFAAnalysisRunContext
    end

    methods

        function obj = FluxAnalysisDependencies( ...
                options, hdf5FilePath, isExport)

            arguments
                options (1, 1) ...
                    openmebius.application.analysis ...
                    .FluxAnalysisComposition
                hdf5FilePath (1, 1) string
                isExport (1, 1) logical
            end

            inputWriter = options.MFAInputSnapshotWriter;

            if isempty(inputWriter)
                inputWriter = openmebius.infrastructure.result ...
                    .MFAInputSnapshotWriter( ...
                    Repository = options.Hdf5ResultRepository);
            end

            resultWriter = options.MFAResultCheckpointWriter;

            if isempty(resultWriter)
                resultWriter = openmebius.infrastructure.result ...
                    .MFAResultCheckpointWriter( ...
                    Repository = options.Hdf5ResultRepository);
            end

            nextLabelWriter = options.NextLabelResultCheckpointWriter;

            if isempty(nextLabelWriter)
                nextLabelWriter = openmebius.infrastructure.result ...
                    .NextLabelResultCheckpointWriter( ...
                    Repository = options.Hdf5ResultRepository);
            end

            runRepository = openmebius.infrastructure.result ...
                .AnalysisRunRepository( ...
                Hdf5ResultRepository = ...
                options.Hdf5ResultRepository, ...
                ResultManifestRepository = ...
                options.ResultManifestRepository);
            obj.AnalysisRunLifecycle = options.AnalysisRunLifecycle;

            if isempty(obj.AnalysisRunLifecycle)
                obj.AnalysisRunLifecycle = openmebius.application ...
                    .analysis.AnalysisRunLifecycle( ...
                    Repository = runRepository);
            end

            obj.MFAConstraintBuilder = options.MFAConstraintBuilder;
            obj.FluxVariabilityProblemFactory = ...
                options.FluxVariabilityProblemFactory;

            if isempty(obj.FluxVariabilityProblemFactory)
                obj.FluxVariabilityProblemFactory = ...
                    openmebius.mfa.FluxVariabilityProblemFactory( ...
                    ConstraintBuilder = obj.MFAConstraintBuilder);
            end

            obj.MFAIterationRunner = options.MFAIterationRunner;

            if isempty(obj.MFAIterationRunner)
                obj.MFAIterationRunner = ...
                    openmebius.mfa.MFAIterationRunner( ...
                    Solver = options.SteadyStateSolver);
            end

            obj.MFAFitStatistics = options.MFAFitStatistics;
            obj.SteadyStateMDVPredictor = ...
                options.SteadyStateMDVPredictor;
            obj.InitialFluxWorkflow = options.InitialFluxWorkflow;

            if isempty(obj.InitialFluxWorkflow)
                obj.InitialFluxWorkflow = ...
                    openmebius.mfa.InitialFluxWorkflow( ...
                    ProblemFactory = options.MFAProblemFactory, ...
                    PointGenerator = options.InitialPointGenerator, ...
                    FitStatistics = obj.MFAFitStatistics, ...
                    MDVPredictor = obj.SteadyStateMDVPredictor);
            end

            obj.ConfidenceIntervalWorkflow = ...
                options.ConfidenceIntervalWorkflow;

            if isempty(obj.ConfidenceIntervalWorkflow)
                obj.ConfidenceIntervalWorkflow = ...
                    openmebius.mfa.ConfidenceIntervalWorkflow( ...
                    MonteCarloSolver = ...
                    options.MonteCarloConfidenceIntervalSolver);
            end

            obj.SubstrateEMUFactory = options.SubstrateEMUFactory;
            obj.NextLabelExperimentWorkflow = ...
                options.NextLabelExperimentWorkflow;

            if isempty(obj.NextLabelExperimentWorkflow)
                obj.NextLabelExperimentWorkflow = ...
                    openmebius.mfa.NextLabelExperimentWorkflow( ...
                    SubstrateEMUFactory = obj.SubstrateEMUFactory, ...
                    MDVPredictor = obj.SteadyStateMDVPredictor);
            end

            obj.MFAObjectiveFactory = ...
                openmebius.mfa.MFAObjectiveFactory( ...
                MDVPredictor = obj.SteadyStateMDVPredictor, ...
                EffluxPenaltyFactory = options.EffluxPenaltyFactory);
            obj.MFAIterationService = openmebius.mfa ...
                .MFAIterationService( ...
                Runner = obj.MFAIterationRunner, ...
                ObjectiveFactory = obj.MFAObjectiveFactory);

            obj.MFAResultCoordinator = options.MFAResultCoordinator;

            if isempty(obj.MFAResultCoordinator)
                obj.MFAResultCoordinator = ...
                    openmebius.infrastructure.result ...
                    .MFAResultCoordinator( ...
                    InputSnapshotWriter = inputWriter, ...
                    ResultCheckpointWriter = resultWriter, ...
                    NextLabelCheckpointWriter = nextLabelWriter, ...
                    HDF5FilePath = hdf5FilePath, ...
                    IsExport = isExport);
            end

            obj.FluxVariabilitySolver = ...
                options.FluxVariabilitySolver;
            obj.FluxVariabilityWorkflow = ...
                options.FluxVariabilityWorkflow;

            if isempty(obj.FluxVariabilityWorkflow)
                obj.FluxVariabilityWorkflow = ...
                    openmebius.mfa.FluxVariabilityWorkflow( ...
                    ConstraintBuilder = obj.MFAConstraintBuilder, ...
                    ProblemFactory = ...
                    obj.FluxVariabilityProblemFactory, ...
                    Solver = obj.FluxVariabilitySolver);
            end

            obj.MFAWorkflow = options.MFAWorkflow;
            obj.MFAInputValidator = options.MFAInputValidator;
            obj.MFAExperimentalDataBuilder = ...
                options.MFAExperimentalDataBuilder;
            obj.MFAInputPreparationWorkflow = ...
                options.MFAInputPreparationWorkflow;

            if isempty(obj.MFAInputPreparationWorkflow)
                obj.MFAInputPreparationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAInputPreparationWorkflow( ...
                    Validator = obj.MFAInputValidator, ...
                    ExperimentalDataBuilder = ...
                    obj.MFAExperimentalDataBuilder);
            end

            obj.MFAExperimentListNormalizer = ...
                options.MFAExperimentListNormalizer;
            obj.EffluxPenaltyFactory = options.EffluxPenaltyFactory;
            obj.InstationaryInputFactory = ...
                options.InstationaryInputFactory;
            runContext = options.RunContext;

            if isempty(runContext)
                runContext = openmebius.application.analysis ...
                    .MFAAnalysisRunContext();
            end

            obj.RunContext = runContext;
            obj.FluxDistributionWorkflow = ...
                options.FluxDistributionWorkflow;

            if isempty(obj.FluxDistributionWorkflow)
                obj.FluxDistributionWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAFluxDistributionWorkflow( ...
                    InputPreparationWorkflow = ...
                        obj.MFAInputPreparationWorkflow, ...
                    FluxVariabilityWorkflow = ...
                        obj.FluxVariabilityWorkflow, ...
                    InitialFluxWorkflow = obj.InitialFluxWorkflow, ...
                    MFAWorkflow = obj.MFAWorkflow, ...
                    MFAIterationService = obj.MFAIterationService, ...
                    SubstrateEMUFactory = obj.SubstrateEMUFactory, ...
                    EffluxPenaltyFactory = obj.EffluxPenaltyFactory, ...
                    InstationaryInputFactory = ...
                        obj.InstationaryInputFactory, ...
                    FitStatistics = obj.MFAFitStatistics);
            end

            obj.ConfidenceIntervalApplicationWorkflow = ...
                options.ConfidenceIntervalApplicationWorkflow;

            if isempty(obj.ConfidenceIntervalApplicationWorkflow)
                obj.ConfidenceIntervalApplicationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAConfidenceIntervalWorkflow( ...
                    ConfidenceIntervalWorkflow = ...
                        obj.ConfidenceIntervalWorkflow, ...
                    MFAIterationService = obj.MFAIterationService);
            end

            obj.NextFluxExperimentWorkflow = ...
                options.NextFluxExperimentWorkflow;

            if isempty(obj.NextFluxExperimentWorkflow)
                obj.NextFluxExperimentWorkflow = ...
                    openmebius.application.analysis ...
                    .NextFluxExperimentWorkflow( ...
                    ConfidenceIntervalApplicationWorkflow = ...
                        obj.ConfidenceIntervalApplicationWorkflow, ...
                    NextLabelExperimentWorkflow = ...
                        obj.NextLabelExperimentWorkflow);
            end

        end

    end

end
