classdef FluxAnalysisRunSettingsMapper
    % FLUXANALYSISRUNSETTINGSMAPPER Maps Batch config once per analysis.

    methods (Static)

        function settings = fromBatchConfig(config)

            arguments
                config (1, 1) struct
            end

            distributionMapping = openmebius.application.analysis ...
                .MFAAnalysisSettingsMapper.tryFromBatchConfig(config);
            distributionSettings = [];
            distributionFailureStage = "";
            distributionError = "";

            if distributionMapping.IsValid
                distributionSettings = distributionMapping.Settings;
            else
                distributionFailureStage = ...
                    distributionMapping.FailureStage;
                distributionError = distributionMapping.ErrorMessage;
            end

            confidenceSettings = [];
            confidenceError = "";

            try
                confidenceSettings = openmebius.application.analysis ...
                    .MFAConfidenceIntervalRunSettingsMapper ...
                    .fromBatchConfig(config);
            catch ME
                confidenceError = ...
                    "Invalid confidence interval settings: " + ...
                    string(ME.message);
            end

            nextExperimentSettings = [];
            nextExperimentError = "";

            if isempty(confidenceSettings)
                nextExperimentError = ...
                    "Invalid next experiment settings: " + ...
                    confidenceError;
            else

                try
                    nextLabelSettings = openmebius.application.analysis ...
                        .NextLabelExperimentSettingsMapper ...
                        .fromBatchConfig(config);
                    nextExperimentSettings = ...
                        openmebius.application.analysis ...
                        .NextFluxExperimentRunSettings( ...
                        ConfidenceIntervalRunSettings = ...
                        confidenceSettings, ...
                        NextLabelSettings = nextLabelSettings);
                catch ME
                    nextExperimentError = ...
                        "Invalid next experiment settings: " + ...
                        string(ME.message);
                end

            end

            settings = openmebius.application.analysis ...
                .FluxAnalysisRunSettings( ...
                DistributionSettings = distributionSettings, ...
                DistributionFailureStage = ...
                distributionFailureStage, ...
                DistributionErrorMessage = distributionError, ...
                ConfidenceIntervalRunSettings = confidenceSettings, ...
                ConfidenceIntervalErrorMessage = confidenceError, ...
                NextExperimentRunSettings = nextExperimentSettings, ...
                NextExperimentErrorMessage = nextExperimentError);

        end

    end

end
