classdef FluxAnalysisRuntimeFactory
    % FLUXANALYSISRUNTIMEFACTORY
    % Creates location-aware dependencies and result state for the facade.

    properties (Access = private)
        DependenciesFactory
        ResultSessionFactory
    end

    methods

        function obj = FluxAnalysisRuntimeFactory(options)

            arguments
                options.DependenciesFactory = []
                options.ResultSessionFactory = []
            end

            obj.DependenciesFactory = options.DependenciesFactory;

            if isempty(obj.DependenciesFactory)
                obj.DependenciesFactory = ...
                    @(configuration, path, isExport) ...
                    openmebius.application.analysis ...
                    .FluxAnalysisDependencies( ...
                    configuration, path, isExport);
            end

            obj.ResultSessionFactory = options.ResultSessionFactory;

            if isempty(obj.ResultSessionFactory)
                obj.ResultSessionFactory = ...
                    @(coordinator, reporter) ...
                    openmebius.application.analysis.MFAResultSession( ...
                    Coordinator = coordinator, ...
                    FailureReporter = reporter);
            end

        end

        function runtime = create( ...
                obj, resultInput, resultID, configuration, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .FluxAnalysisRuntimeFactory
                resultInput
                resultID
                configuration (1, 1) ...
                    openmebius.application.analysis ...
                    .FluxAnalysisComposition
                options.FailureReporter (1, 1) function_handle = ...
                    @(~) []
            end

            resultLocation = ...
                openmebius.domain.result.ResultLocation.fromInput( ...
                resultInput);
            resultID = string(resultID);
            resultFilePath = resultLocation.resultFile(resultID);
            [isExport, isError, message, level] = ...
                obj.validateResultLocation( ...
                configuration.Results.Hdf5ResultRepository, ...
                resultLocation);
            dependencies = obj.DependenciesFactory( ...
                configuration, string(resultFilePath), isExport);
            resultSession = obj.ResultSessionFactory( ...
                dependencies.MFAResultCoordinator, ...
                options.FailureReporter);
            runtime = openmebius.application.analysis ...
                .FluxAnalysisRuntime( ...
                ResultLocation = resultLocation, ...
                ResultID = resultID, ...
                ResultFilePath = string(resultFilePath), ...
                IsExport = isExport, ...
                IsError = isError, ...
                DirectoryMessage = message, ...
                DirectoryMessageLevel = level, ...
                Dependencies = dependencies, ...
                RunContext = dependencies.RunContext, ...
                ResultSession = resultSession);

        end

    end

    methods (Static, Access = private)

        function [isExport, isError, message, level] = ...
                validateResultLocation(repository, resultLocation)

            try
                repository.assertResultDirectory(resultLocation);
                isExport = true;
                isError = false;
                message = "The directory " + ...
                    resultLocation.Directory + " exists.";
                level = "Info";
            catch
                isExport = false;
                isError = true;
                message = "The directory " + ...
                    resultLocation.Directory + " does not exist.";
                level = "Error";
            end

        end

    end

end
