classdef InitialFluxSettingsMapper
    % INITIALFLUXSETTINGSMAPPER
    % Maps persisted Batch configuration to typed initial-flux settings.

    methods (Static)

        function settings = fromBatchConfig(config)

            arguments
                config (1, 1) struct
            end

            if ~isfield(config, 'iteration') || ...
                    isempty(config.iteration)
                error( ...
                    "OpenMebius2:InitialFluxSettingsMapper:" + ...
                    "MissingIterationCount", ...
                "Batch configuration requires an iteration count.");
            end

            candidate = config.iteration;

            if ~(isnumeric(candidate) || islogical(candidate)) || ...
                    ~isscalar(candidate)
                error( ...
                    "OpenMebius2:InitialFluxSettingsMapper:" + ...
                    "InvalidIterationCount", ...
                "Batch iteration count must be a numeric scalar.");
            end

            defaults = openmebius.mfa.InitialFluxSettings();
            restrictFreeEffluxSeeds = ...
                defaults.RestrictFreeEffluxSeeds;
            sigmaMultiplier = ...
                defaults.FreeEffluxSeedSigmaMultiplier;

            if isfield(config, 'initialFlux') && ...
                    ~isempty(config.initialFlux)
                initialFlux = config.initialFlux;

                if ~isstruct(initialFlux) || ~isscalar(initialFlux)
                    error( ...
                        "OpenMebius2:InitialFluxSettingsMapper:" + ...
                        "InvalidInitialFluxConfig", ...
                        "Batch initialFlux configuration must be a " + ...
                    "scalar struct.");
                end

                if isfield( ...
                        initialFlux, 'restrictFreeEffluxSeeds') && ...
                        ~isempty(initialFlux.restrictFreeEffluxSeeds)
                    restrictFreeEffluxSeeds = ...
                        openmebius.application.analysis ...
                        .InitialFluxSettingsMapper.toLogical( ...
                        initialFlux.restrictFreeEffluxSeeds);
                end

                if isfield( ...
                        initialFlux, ...
                    'freeEffluxSeedSigmaMultiplier') && ...
                        ~isempty( ...
                        initialFlux.freeEffluxSeedSigmaMultiplier)
                    sigmaCandidate = initialFlux ...
                        .freeEffluxSeedSigmaMultiplier;

                    if ~(isnumeric(sigmaCandidate) || ...
                            islogical(sigmaCandidate)) || ...
                            ~isscalar(sigmaCandidate)
                        error( ...
                            "OpenMebius2:" + ...
                            "InitialFluxSettingsMapper:" + ...
                            "InvalidFreeEffluxSeedSigmaMultiplier", ...
                            "The free-efflux seed sigma multiplier " + ...
                        "must be a numeric scalar.");
                    end

                    sigmaMultiplier = double(sigmaCandidate);
                end

            end

            settings = openmebius.mfa.InitialFluxSettings( ...
                IterationCount = double(candidate), ...
                RestrictFreeEffluxSeeds = ...
                restrictFreeEffluxSeeds, ...
                FreeEffluxSeedSigmaMultiplier = sigmaMultiplier);

        end % fromBatchConfig

    end % methods (Static)

    methods (Static, Access = private)

        function value = toLogical(candidate)

            if ischar(candidate) || isstring(candidate)
                normalized = lower(strtrim(string(candidate)));

                if isscalar(normalized) && ...
                        ismember(normalized, ["true", "1", "yes", "on"])
                    value = true;
                    return
                end

                if isscalar(normalized) && ...
                        ismember(normalized, ["false", "0", "no", "off"])
                    value = false;
                    return
                end

            elseif isscalar(candidate) && ...
                    (islogical(candidate) || isnumeric(candidate)) && ...
                    isfinite(double(candidate)) && ...
                    ismember(double(candidate), [0, 1])
                value = logical(candidate);
                return
            end

            error( ...
                "OpenMebius2:InitialFluxSettingsMapper:" + ...
                "InvalidRestrictFreeEffluxSeeds", ...
                "The free-efflux seed restriction flag must be a " + ...
            "scalar logical value.");

        end

    end % methods (Static, Access = private)

end
