classdef MFAAnalysisController < handle
    % MFAANALYSISCONTROLLER Coordinates commands for one MFA analysis.

    properties (SetAccess = private)
        Model
        Experiments
        ExperimentList
        RunSettings (1, 1) openmebius.application.analysis ...
            .FluxAnalysisRunSettings
        RunContext (1, 1) openmebius.application.analysis ...
            .MFAAnalysisRunContext
        ResultSession (1, 1) openmebius.application.analysis ...
            .MFAResultSession
        InputPreparation = []
        FluxDistributionWorkflow
        ConfidenceIntervalApplicationWorkflow
        NextFluxExperimentWorkflow
    end

    methods

        function obj = MFAAnalysisController( ...
                model, experiments, experimentList, runSettings, ...
                runContext, resultSession, options)

            arguments
                model
                experiments
                experimentList
                runSettings (1, 1) openmebius.application.analysis ...
                    .FluxAnalysisRunSettings
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                resultSession (1, 1) openmebius.application.analysis ...
                    .MFAResultSession
                options.FluxDistributionWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAFluxDistributionWorkflow()
                options.ConfidenceIntervalApplicationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAConfidenceIntervalWorkflow()
                options.NextFluxExperimentWorkflow = ...
                    openmebius.application.analysis ...
                    .NextFluxExperimentWorkflow()
            end

            obj.Model = model;
            obj.Experiments = experiments;
            obj.ExperimentList = experimentList;
            obj.RunSettings = runSettings;
            obj.RunContext = runContext;
            obj.ResultSession = resultSession;
            obj.FluxDistributionWorkflow = ...
                options.FluxDistributionWorkflow;
            obj.ConfidenceIntervalApplicationWorkflow = ...
                options.ConfidenceIntervalApplicationWorkflow;
            obj.NextFluxExperimentWorkflow = ...
                options.NextFluxExperimentWorkflow;

        end

        function result = runFluxDistribution( ...
                obj, resultID, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisController
                resultID (1, 1) string
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.ProgressReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            if ~obj.RunSettings.canRunDistribution()
                message = obj.RunSettings.DistributionErrorMessage;
                options.MessageReporter("error", message);
                result = openmebius.application.analysis ...
                    .MFAFluxDistributionResult( ...
                    IsError = true, ...
                    FailureStage = ...
                        obj.RunSettings.DistributionFailureStage, ...
                    ErrorMessage = message);
                return
            end

            result = obj.FluxDistributionWorkflow.run( ...
                obj.Model, ...
                obj.Experiments, ...
                obj.ExperimentList, ...
                obj.RunSettings.DistributionSettings, ...
                obj.RunContext, ...
                obj.ResultSession, ...
                resultID, ...
                MessageReporter = options.MessageReporter, ...
                ProgressReporter = options.ProgressReporter, ...
                CancellationRequested = ...
                    options.CancellationRequested);
            obj.InputPreparation = result.InputPreparation;

        end

        function result = calculateConfidenceInterval(obj, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisController
                options.PersistResult (1, 1) logical = true
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            if ~obj.RunSettings.canCalculateConfidenceInterval()
                message = ...
                    obj.RunSettings.ConfidenceIntervalErrorMessage;
                options.MessageReporter("error", message);
                result = openmebius.mfa ...
                    .ConfidenceIntervalWorkflowResult( ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            result = obj.ConfidenceIntervalApplicationWorkflow.run( ...
                obj.Model, ...
                obj.RunSettings.ConfidenceIntervalRunSettings, ...
                obj.RunContext, ...
                obj.ResultSession, ...
                obj.InputPreparation, ...
                PersistResult = options.PersistResult, ...
                MessageReporter = options.MessageReporter, ...
                CancellationRequested = ...
                    options.CancellationRequested);

        end

        function result = suggestNextFluxExperiment(obj, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisController
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            if ~obj.RunSettings.canSuggestNextExperiment()
                message = obj.RunSettings.NextExperimentErrorMessage;
                options.MessageReporter("error", message);
                result = openmebius.application.analysis ...
                    .NextFluxExperimentResult( ...
                    IsError = true, ...
                    ErrorMessage = message);
                return
            end

            result = obj.NextFluxExperimentWorkflow.run( ...
                obj.Model, ...
                obj.Experiments, ...
                obj.ExperimentList, ...
                obj.RunSettings.NextExperimentRunSettings, ...
                obj.RunContext, ...
                obj.ResultSession, ...
                obj.InputPreparation, ...
                MessageReporter = options.MessageReporter, ...
                CancellationRequested = ...
                    options.CancellationRequested);

        end

    end

end
