classdef MFAAnalysisSettings
    % MFAANALYSISSETTINGS Typed settings for one MFA analysis run.

    properties (SetAccess = private)
        InputPreparationSettings (1, 1) openmebius.application ...
            .analysis.MFAInputPreparationSettings
        InitialFluxSettings (1, 1) openmebius.mfa.InitialFluxSettings
        IterationSettings (1, 1) openmebius.mfa.MFAIterationSettings
        InstationaryInputSpecification = []
    end

    methods

        function obj = MFAAnalysisSettings(options)

            arguments
                options.InputPreparationSettings (1, 1) ...
                    openmebius.application.analysis ...
                    .MFAInputPreparationSettings = ...
                    openmebius.application.analysis ...
                    .MFAInputPreparationSettings()
                options.InitialFluxSettings (1, 1) openmebius.mfa ...
                    .InitialFluxSettings = ...
                    openmebius.mfa.InitialFluxSettings()
                options.IterationSettings (1, 1) openmebius.mfa ...
                    .MFAIterationSettings = ...
                    openmebius.mfa.MFAIterationSettings()
                options.InstationaryInputSpecification = []
            end

            isInstationary = ...
                options.IterationSettings.AnalysisMode.isInstationary();
            hasSpecification = ...
                ~isempty(options.InstationaryInputSpecification);

            if isInstationary ~= hasSpecification
                error( ...
                    "OpenMebius2:MFAAnalysisSettings:" + ...
                    "InconsistentInstationarySettings", ...
                    "Instationary analysis mode requires exactly one " + ...
                "instationary input specification.");
            end

            if hasSpecification && ...
                    ~isa(options.InstationaryInputSpecification, ...
                'openmebius.mfa.InstationaryInputSpecification')
                error( ...
                    "OpenMebius2:MFAAnalysisSettings:" + ...
                    "InvalidInstationarySpecification", ...
                    "Instationary input specification has an " + ...
                "unsupported type.");
            end

            obj.InputPreparationSettings = ...
                options.InputPreparationSettings;
            obj.InitialFluxSettings = options.InitialFluxSettings;
            obj.IterationSettings = options.IterationSettings;
            obj.InstationaryInputSpecification = ...
                options.InstationaryInputSpecification;

        end

    end

end
