classdef MFAAnalysisControllerFactory
    % MFAANALYSISCONTROLLERFACTORY Assembles one configured controller.

    methods

        function controller = create( ...
                ~, model, experiments, experimentNames, config, ...
                runtime, provenance)

            arguments
                ~
                model
                experiments
                experimentNames
                config (1, 1) struct
                runtime (1, 1) openmebius.application.analysis ...
                    .FluxAnalysisRuntime
                provenance (1, 1) struct = struct
            end

            dependencies = runtime.Dependencies;
            experimentList = dependencies ...
                .MFAExperimentListNormalizer.normalize( ...
                experimentNames);
            runSettings = openmebius.application.analysis ...
                .FluxAnalysisRunSettingsMapper.fromBatchConfig(config);
            controller = openmebius.application.analysis ...
                .MFAAnalysisController( ...
                model, ...
                experiments, ...
                experimentList, ...
                runSettings, ...
                runtime.RunContext, ...
                runtime.ResultSession, ...
                FluxDistributionWorkflow = ...
                    dependencies.FluxDistributionWorkflow, ...
                ConfidenceIntervalApplicationWorkflow = ...
                    dependencies ...
                    .ConfidenceIntervalApplicationWorkflow, ...
                NextFluxExperimentWorkflow = ...
                    dependencies.NextFluxExperimentWorkflow, ...
                Config = config, ...
                ResultID = runtime.ResultID, ...
                ResultLocation = runtime.ResultLocation, ...
                ResultFilePath = runtime.ResultFilePath, ...
                IsExport = runtime.IsExport, ...
                Provenance = provenance, ...
                AnalysisRunLifecycle = ...
                    dependencies.AnalysisRunLifecycle, ...
                Dependencies = dependencies, ...
                InitialError = runtime.IsError);

        end

    end

end
