classdef MFAConfidenceIntervalWorkflow
    % MFACONFIDENCEINTERVALWORKFLOW
    % Connects confidence-interval calculation to one analysis session.

    properties (SetAccess = private)
        ConfidenceIntervalWorkflow
        MFAIterationService
        FitStatistics
    end

    methods

        function obj = MFAConfidenceIntervalWorkflow(options)

            arguments
                options.ConfidenceIntervalWorkflow = ...
                    openmebius.mfa.ConfidenceIntervalWorkflow()
                options.MFAIterationService = ...
                    openmebius.mfa.MFAIterationService()
                options.FitStatistics = ...
                    openmebius.mfa.MFAFitStatistics()
            end

            obj.ConfidenceIntervalWorkflow = ...
                options.ConfidenceIntervalWorkflow;
            obj.MFAIterationService = options.MFAIterationService;
            obj.FitStatistics = options.FitStatistics;

        end

        function result = run( ...
                obj, model, settings, runContext, resultSession, ...
                inputPreparation, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAConfidenceIntervalWorkflow
                model
                settings (1, 1) openmebius.application.analysis ...
                    .MFAConfidenceIntervalRunSettings
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                resultSession
                inputPreparation
                options.ExperimentalMDV double = ...
                    runContext.experimentalMDV()
                options.SubstrateEMUs cell = ...
                    runContext.SubstrateEMUs
                options.PersistResult (1, 1) logical = true
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            reporter = options.MessageReporter;
            initialProblem = [];
            initialRightHandSides = [];
            hasFluxDistribution = ...
                resultSession.Progress.FluxDistributionCompleted;
            isMonteCarlo = ...
                settings.ConfidenceIntervalSettings.Enabled && ...
                settings.ConfidenceIntervalSettings.Method == ...
                openmebius.mfa ...
                .ConfidenceIntervalMethod.MonteCarlo;
            isGridSearch = ...
                settings.ConfidenceIntervalSettings.Enabled && ...
                settings.ConfidenceIntervalSettings.Method == ...
                openmebius.mfa ...
                .ConfidenceIntervalMethod.GridSearch;

            if ~isempty(runContext.InitialResult)
                initialProblem = runContext.InitialResult.Problem;
                initialRightHandSides = ...
                    runContext.InitialResult.RightHandSides;
            end

            profileFluxIndices = zeros(0, 1);
            objectiveThreshold = NaN;
            bestObjective = NaN;

            if isGridSearch && hasFluxDistribution
                [profileFluxIndices, objectiveThreshold, bestObjective] = ...
                    obj.prepareGridSearch( ...
                    model, settings, runContext);
            end

            profileReporter = reporter;
            iterationReporter = reporter;

            if isMonteCarlo
                % Monte Carlo iterations run on parallel workers. Desktop
                % notification callbacks can capture app/UI handles that
                % are not valid after worker serialization.
                iterationReporter = @(~, ~) [];
            end

            if isGridSearch && ...
                    settings.ConfidenceIntervalSettings ...
                    .GridSearchSettings.ExecutionMode.isParallel()
                % UI and application notification callbacks are not
                % guaranteed to be executable on parallel workers.
                profileReporter = @(~, ~) [];
            end

            profileIterationFunction = ...
                @(rightHandSide, Aeq, beq, initialValues) ...
                obj.runProfileIteration( ...
                model, ...
                settings.IterationSettings, ...
                runContext, ...
                inputPreparation, ...
                options.ExperimentalMDV, ...
                rightHandSide, ...
                options.SubstrateEMUs, ...
                Aeq, ...
                beq, ...
                initialValues, ...
                profileReporter ...
            );

            result = obj.ConfidenceIntervalWorkflow.run( ...
                settings.ConfidenceIntervalSettings, ...
                options.ExperimentalMDV, ...
                runContext.workflowFluxes(), ...
                hasFluxDistribution, ...
                initialProblem, ...
                initialRightHandSides, ...
                model.getIdxRev(), ...
                @(mdv, rightHandSide) obj.runIteration( ...
                model, ...
                settings.IterationSettings, ...
                runContext, ...
                inputPreparation, ...
                mdv, ...
                rightHandSide, ...
                options.SubstrateEMUs, ...
                iterationReporter), ...
                ProfileIterationFunction = profileIterationFunction, ...
                GridSearchProfileFluxIndices = ...
                profileFluxIndices, ...
                GridSearchObjectiveThreshold = ...
                objectiveThreshold, ...
                GridSearchBestObjective = bestObjective, ...
                MessageReporter = reporter, ...
                CancellationRequested = ...
                options.CancellationRequested);

            if options.PersistResult && ...
                    result.Method == "Monte Carlo" && ...
                    result.IsCalculated
                resultSession.writeMonteCarloConfidenceInterval( ...
                    result.LowerBounds, ...
                    result.UpperBounds, ...
                    settings.ConfidenceIntervalSettings, ...
                    result.Output);
            end

            if options.PersistResult && ...
                    result.Method == "Grid search" && ...
                    result.IsCalculated && ...
                    ~result.IsCanceled
                modelTable = model.getModelTable();
                reactionIDs = string( ...
                    modelTable.Properties.RowNames(:));
                reactionIDs(end + 1, 1) = "biomass";
                resultSession.writeGridSearchConfidenceInterval( ...
                    result.LowerBounds, ...
                    result.UpperBounds, ...
                    settings.ConfidenceIntervalSettings, ...
                    result.Output, ...
                    reactionIDs);
            end

        end

    end

    methods (Access = private)

        function [profileFluxIndices, objectiveThreshold, bestObjective] = ...
                prepareGridSearch(obj, model, settings, runContext)

            workflowResult = runContext.requireWorkflowResult();
            gridSettings = settings.ConfidenceIntervalSettings ...
                .GridSearchSettings;
            minimumObjective = workflowResult.ObjectiveValues(1);
            bestObjective = minimumObjective;
            experimentalData = runContext.ExperimentalData;
            [~, residualDegreesOfFreedom] = ...
                obj.FitStatistics.chiSquareThreshold( ...
                model.getDOF(), ...
                experimentalData.FragmentLabels, ...
                experimentalData.FragmentMask, ...
                gridSettings.Alpha);
            objectiveThreshold = obj.FitStatistics ...
                .gridSearchObjectiveThreshold( ...
                gridSettings, ...
                minimumObjective, ...
                residualDegreesOfFreedom);
            profileFluxIndices = obj.resolveGridSearchFluxIndices( ...
                model, settings);

        end

        function indices = resolveGridSearchFluxIndices( ...
                ~, model, settings)

            if settings.UseAllGridSearchReactions
                indices = zeros(0, 1);
                return
            end

            selectedIDs = settings.GridSearchSelectedReactionIDs;
            modelTable = model.getModelTable();
            modelIDs = string(modelTable.Properties.RowNames(:));

            if numel(modelIDs) ~= height(modelTable) || ...
                    any(strlength(modelIDs) == 0)
                error( ...
                    "OpenMebius2:MFAConfidenceIntervalWorkflow:" + ...
                    "InvalidModelReactionIDs", ...
                    "The model must provide a nonempty row ID for " + ...
                "each grid-search reaction.");
            end

            [found, indices] = ismember(selectedIDs, modelIDs);

            if any(~found)
                error( ...
                    "OpenMebius2:MFAConfidenceIntervalWorkflow:" + ...
                    "UnknownGridReaction", ...
                    "Grid-search reaction IDs were not found in " + ...
                    "the model: %s.", ...
                    strjoin(selectedIDs(~found), ", "));
            end

            indices = unique(indices, "stable");

        end

        function input = createIterationInput( ...
                ~, model, settings, runContext, inputPreparation, ...
                experimentalMDV, rightHandSide, substrateEMUs)

            initialResult = runContext.requireInitialResult();

            input = openmebius.mfa.MFAIterationInput( ...
                Model = model, ...
                Settings = settings, ...
                Problem = initialResult.Problem, ...
                ExperimentalData = runContext.ExperimentalData, ...
                ExperimentalMDV = experimentalMDV, ...
                RightHandSide = rightHandSide, ...
                SubstrateList = inputPreparation.SubstrateList, ...
                Efflux = inputPreparation.Efflux, ...
                EffluxStandardDeviation = ...
                inputPreparation.EffluxStandardDeviation, ...
                EffluxFree = inputPreparation.EffluxFree, ...
                GrowthRate = inputPreparation.GrowthRate, ...
                GrowthRateStandardDeviation = ...
                inputPreparation.GrowthRateStandardDeviation, ...
                GrowthRateFree = inputPreparation.GrowthRateFree, ...
                SubstrateEMUs = substrateEMUs);

        end % method createIterationInput

        function result = runIteration( ...
                obj, model, settings, runContext, inputPreparation, ...
                experimentalMDV, rightHandSide, substrateEMUs, ...
                reporter)

            input = obj.createIterationInput( ...
                model, ...
                settings, ...
                runContext, ...
                inputPreparation, ...
                experimentalMDV, ...
                rightHandSide, ...
                substrateEMUs);

            result = obj.MFAIterationService.run( ...
                input, ...
                MessageReporter = reporter);

        end % method runIteration

        function result = runProfileIteration( ...
                obj, model, settings, runContext, inputPreparation, ...
                experimentalMDV, rightHandSide, substrateEMUs, ...
                equalityMatrix, equalityRightHandSide, ...
                initialIndependentValues, reporter)

            input = obj.createIterationInput( ...
                model, ...
                settings, ...
                runContext, ...
                inputPreparation, ...
                experimentalMDV, ...
                rightHandSide, ...
                substrateEMUs);

            result = obj.MFAIterationService.run( ...
                input, ...
                InitialIndependentValues = ...
                initialIndependentValues, ...
                LinearEqualityMatrix = equalityMatrix, ...
                LinearEqualityRightHandSide = ...
                equalityRightHandSide, ...
                MessageReporter = reporter);

        end % method runProfileIteration

    end

end
