classdef MFAConfidenceIntervalWorkflow
    % MFACONFIDENCEINTERVALWORKFLOW
    % Connects confidence-interval calculation to one analysis session.

    properties (SetAccess = private)
        ConfidenceIntervalWorkflow
        MFAIterationService
    end

    methods

        function obj = MFAConfidenceIntervalWorkflow(options)

            arguments
                options.ConfidenceIntervalWorkflow = ...
                    openmebius.mfa.ConfidenceIntervalWorkflow()
                options.MFAIterationService = ...
                    openmebius.mfa.MFAIterationService()
            end

            obj.ConfidenceIntervalWorkflow = ...
                options.ConfidenceIntervalWorkflow;
            obj.MFAIterationService = options.MFAIterationService;

        end

        function result = run( ...
                obj, model, config, runContext, resultSession, ...
                inputPreparation, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAConfidenceIntervalWorkflow
                model
                config
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                resultSession
                inputPreparation
                options.ExperimentalMDV double = ...
                    runContext.experimentalMDV()
                options.SubstrateEMUs cell = ...
                    runContext.SubstrateEMUs
                options.PersistResult (1, 1) logical = true
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            reporter = options.MessageReporter;
            initialProblem = [];
            initialRightHandSides = [];

            if ~isempty(runContext.InitialResult)
                initialProblem = runContext.InitialResult.Problem;
                initialRightHandSides = ...
                    runContext.InitialResult.RightHandSides;
            end

            result = obj.ConfidenceIntervalWorkflow.run( ...
                config, ...
                options.ExperimentalMDV, ...
                runContext.workflowFluxes(), ...
                resultSession.Status, ...
                initialProblem, ...
                initialRightHandSides, ...
                model.getIdxRev(), ...
                @(mdv, rightHandSide) obj.runIteration( ...
                model, ...
                config, ...
                runContext, ...
                inputPreparation, ...
                mdv, ...
                rightHandSide, ...
                options.SubstrateEMUs, ...
                reporter), ...
                MessageReporter = reporter, ...
                CancellationRequested = ...
                    options.CancellationRequested);

            if options.PersistResult && ...
                    result.Method == "Monte Carlo" && ...
                    result.IsCalculated
                resultSession.writeMonteCarloConfidenceInterval( ...
                    result.LowerBounds, ...
                    result.UpperBounds, ...
                    config.CIConf, ...
                    result.Output);
            end

        end

    end

    methods (Access = private)

        function result = runIteration( ...
                obj, model, config, runContext, inputPreparation, ...
                experimentalMDV, rightHandSide, substrateEMUs, ...
                reporter)

            initialResult = runContext.requireInitialResult();
            input = openmebius.mfa.MFAIterationInput( ...
                Model = model, ...
                AnalysisConfig = config, ...
                Problem = initialResult.Problem, ...
                ExperimentalData = runContext.ExperimentalData, ...
                ExperimentalMDV = experimentalMDV, ...
                RightHandSide = rightHandSide, ...
                SubstrateList = inputPreparation.SubstrateList, ...
                Efflux = inputPreparation.Efflux, ...
                EffluxStandardDeviation = ...
                    inputPreparation.EffluxStandardDeviation, ...
                EffluxFree = inputPreparation.EffluxFree, ...
                SubstrateEMUs = substrateEMUs, ...
                ForceSteadyState = true);
            result = obj.MFAIterationService.run( ...
                input, ...
                MessageReporter = reporter);

        end

    end

end
