classdef MFAConfidenceIntervalRunSettingsMapper
    % MFACONFIDENCEINTERVALRUNSETTINGSMAPPER Maps Batch config at boundary.

    methods (Static)

        function settings = fromBatchConfig(config)

            arguments
                config (1, 1) struct
            end

            iterationConfig = config;

            if ~isfield(iterationConfig, 'isINSTMFA') || ...
                    isempty(iterationConfig.isINSTMFA)
                iterationConfig.isINSTMFA = false;
            end

            confidenceIntervalSettings = ...
                openmebius.application.analysis ...
                .ConfidenceIntervalSettingsMapper ...
                .fromBatchConfig(config);
            [selectedReactionIDs, useAllReactions] = ...
                openmebius.application.analysis ...
                .MFAConfidenceIntervalRunSettingsMapper ...
                .mapGridReactionSelection( ...
                config, confidenceIntervalSettings);
            settings = openmebius.application.analysis ...
                .MFAConfidenceIntervalRunSettings( ...
                ConfidenceIntervalSettings = confidenceIntervalSettings, ...
                IterationSettings = openmebius.application.analysis ...
                .MFAIterationSettingsMapper.fromBatchConfig( ...
                iterationConfig), ...
                GridSearchSelectedReactionIDs = ...
                selectedReactionIDs, ...
                UseAllGridSearchReactions = useAllReactions);

        end

    end

    methods (Static, Access = private)

        function [selectedIDs, useAll] = ...
                mapGridReactionSelection( ...
                config, confidenceIntervalSettings)

            selectedIDs = strings(0, 1);
            useAll = true;

            if ~isfield(config, 'CIConf') || ...
                    ~isstruct(config.CIConf) || ...
                    ~isfield(config.CIConf, 'grid') || ...
                    ~isstruct(config.CIConf.grid) || ...
                    ~isfield(config.CIConf.grid, 'reactions') || ...
                    ~isstruct(config.CIConf.grid.reactions)
                return
            end

            reactions = config.CIConf.grid.reactions;

            if ~all(isfield(reactions, ...
                    {'select', 'id'}))
                return
            end

            selection = logical(reactions.select(:));
            reactionIDs = string(reactions.id(:));

            if numel(selection) ~= numel(reactionIDs)
                error( ...
                    "OpenMebius2:MFAConfidenceIntervalRunSettings:" + ...
                    "GridReactionSizeMismatch", ...
                    "Grid reaction selections and IDs must have " + ...
                    "the same length.");
            end

            if isempty(reactionIDs)
                return
            end

            useAll = false;
            selectedIDs = reactionIDs(selection);

            if isempty(selectedIDs)
                if confidenceIntervalSettings.Enabled && ...
                        confidenceIntervalSettings.Method == ...
                        openmebius.mfa ...
                        .ConfidenceIntervalMethod.GridSearch
                    error( ...
                        "OpenMebius2:" + ...
                        "MFAConfidenceIntervalRunSettings:" + ...
                        "MissingGridReactions", ...
                        "At least one reaction must be selected for " + ...
                        "grid-search confidence intervals.");
                end

                useAll = true;
            end

        end

    end

end
