classdef MFAExecutionDependenciesFactory
    % MFAEXECUTIONDEPENDENCIESFACTORY Resolves runtime dependencies.

    methods

        function dependencies = create( ...
                ~, configuration, resultConfiguration)

            arguments
                ~
                configuration (1, 1) openmebius.application ...
                    .analysis.MFAExecutionComposition
                resultConfiguration (1, 1) openmebius.application ...
                    .analysis.MFAResultComposition
            end

            lifecycle = configuration.AnalysisRunLifecycle;

            if isempty(lifecycle)
                repository = openmebius.infrastructure.result ...
                    .AnalysisRunRepository( ...
                    Hdf5ResultRepository = resultConfiguration ...
                        .Hdf5ResultRepository, ...
                    ResultManifestRepository = resultConfiguration ...
                        .ResultManifestRepository);
                lifecycle = openmebius.application.analysis ...
                    .AnalysisRunLifecycle(Repository = repository);
            end

            runContext = configuration.RunContext;

            if isempty(runContext)
                runContext = openmebius.application.analysis ...
                    .MFAAnalysisRunContext();
            end

            dependencies = openmebius.application.analysis ...
                .MFAExecutionDependencies( ...
                MFAExperimentListNormalizer = ...
                    configuration.MFAExperimentListNormalizer, ...
                AnalysisRunLifecycle = lifecycle, ...
                RunContext = runContext);

        end

    end

end
