classdef MFAFluxDistributionWorkflow
    % MFAFLUXDISTRIBUTIONWORKFLOW
    % Coordinates one complete MFA flux-distribution calculation.

    properties (SetAccess = private)
        InputPreparationWorkflow
        FluxVariabilityWorkflow
        InitialFluxApplicationWorkflow
        MFAIterationApplicationWorkflow
        FitStatistics
    end

    methods

        function obj = MFAFluxDistributionWorkflow(options)

            arguments
                options.InputPreparationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAInputPreparationWorkflow()
                options.FluxVariabilityWorkflow = ...
                    openmebius.mfa.FluxVariabilityWorkflow()
                options.InitialFluxApplicationWorkflow = []
                options.InitialFluxWorkflow = ...
                    openmebius.mfa.InitialFluxWorkflow()
                options.MFAIterationApplicationWorkflow = []
                options.MFAWorkflow = openmebius.mfa.MFAWorkflow()
                options.MFAIterationService = ...
                    openmebius.mfa.MFAIterationService()
                options.SubstrateEMUFactory = ...
                    openmebius.mfa.SubstrateEMUFactory()
                options.EffluxPenaltyFactory = ...
                    openmebius.mfa.EffluxPenaltyFactory()
                options.InstationaryInputFactory = ...
                    openmebius.mfa.InstationaryInputFactory()
                options.FitStatistics = ...
                    openmebius.mfa.MFAFitStatistics()
            end

            obj.InputPreparationWorkflow = ...
                options.InputPreparationWorkflow;
            obj.FluxVariabilityWorkflow = ...
                options.FluxVariabilityWorkflow;
            obj.InitialFluxApplicationWorkflow = ...
                options.InitialFluxApplicationWorkflow;

            if isempty(obj.InitialFluxApplicationWorkflow)
                obj.InitialFluxApplicationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAInitialFluxApplicationWorkflow( ...
                    InitialFluxWorkflow = ...
                        options.InitialFluxWorkflow, ...
                    SubstrateEMUFactory = ...
                        options.SubstrateEMUFactory, ...
                    EffluxPenaltyFactory = ...
                        options.EffluxPenaltyFactory);
            end

            obj.MFAIterationApplicationWorkflow = ...
                options.MFAIterationApplicationWorkflow;

            if isempty(obj.MFAIterationApplicationWorkflow)
                obj.MFAIterationApplicationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAIterationApplicationWorkflow( ...
                    MFAWorkflow = options.MFAWorkflow, ...
                    MFAIterationService = ...
                        options.MFAIterationService, ...
                    InstationaryInputFactory = ...
                        options.InstationaryInputFactory);
            end

            obj.FitStatistics = options.FitStatistics;

        end

        function result = run( ...
                obj, model, experiments, experimentList, settings, ...
                runContext, resultSession, resultID, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAFluxDistributionWorkflow
                model
                experiments
                experimentList
                settings (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisSettings
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                resultSession
                resultID (1, 1) string
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.ProgressReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            report = options.MessageReporter;
            inputPreparation = obj.InputPreparationWorkflow.run( ...
                model, experiments, experimentList, ...
                settings.InputPreparationSettings, ...
                MessageReporter = report);

            if ~isempty(inputPreparation.ExperimentalData)
                runContext.setExperimentalData( ...
                    inputPreparation.ExperimentalData);
            end

            restoreModel = onCleanup( ...
                @() inputPreparation.restoreModel());

            if ~inputPreparation.IsValid
                message = obj.inputFailureMessage(inputPreparation);
                report("error", message);
                result = obj.failureResult( ...
                    inputPreparation, "input", message);
                return
            end

            experimentalData = runContext.ExperimentalData;
            resultSession.writeGeneral( ...
                resultID, ...
                experimentalData.ExperimentalMDV, ...
                experimentalData.FragmentLabels, ...
                experimentalData.FragmentMask);
            resultSession.writeModel( ...
                model.getModelTable(), model.getModelTableRev());

            report("info", "Calculating flux variability...");
            fvaResult = obj.FluxVariabilityWorkflow.run( ...
                model, ...
                inputPreparation.GrowthRate, ...
                inputPreparation.SubstrateList, ...
                inputPreparation.Efflux, ...
                inputPreparation.EffluxFree, ...
                MessageReporter = report);
            runContext.setRightHandSide(fvaResult.RightHandSide);

            if fvaResult.IsError
                result = obj.failureResult( ...
                    inputPreparation, "fva", fvaResult.ErrorMessage);
                return
            end

            report("info", "Flux variability calculation completed.");
            runContext.setBounds( ...
                fvaResult.LowerBounds, fvaResult.UpperBounds);
            resultSession.writeFluxVariability( ...
                fvaResult.LowerBounds, ...
                fvaResult.UpperBounds, ...
                model.getIdxRev());
            averageFlux = mean( ...
                fvaResult.UpperBounds - fvaResult.LowerBounds);
            report( ...
                "info", ...
                "Average flux range: " + string(averageFlux) + ...
                " mmol/g/h");

            initialResult = obj.InitialFluxApplicationWorkflow.run( ...
                model, ...
                experiments, ...
                experimentList, ...
                settings.InitialFluxSettings, ...
                runContext, ...
                inputPreparation, ...
                MessageReporter = report, ...
                CancellationRequested = ...
                options.CancellationRequested);

            if initialResult.IsCanceled || ...
                    logical(options.CancellationRequested())
                report( ...
                    "info", ...
                    "Initial flux distribution calculation canceled.");
                result = openmebius.application.analysis ...
                    .MFAFluxDistributionResult( ...
                    InputPreparation = inputPreparation, ...
                    IsCanceled = true);
                return
            end

            if initialResult.IsError
                message = ...
                    "Initial flux distribution calculation failed.";
                report("error", message);
                result = obj.failureResult( ...
                    inputPreparation, "initial", message);
                return
            end

            report( ...
                "info", ...
                "Initial flux distribution calculation completed.");
            resultSession.writeInitialFlux( ...
                initialResult.Fluxes, ...
                initialResult.RightHandSides, ...
                initialResult.ObjectiveValues, ...
                model.getIdxRev());

            iterationResult = ...
                obj.MFAIterationApplicationWorkflow.run( ...
                model, ...
                settings.IterationSettings, ...
                settings.InstationaryInputSpecification, ...
                runContext, ...
                resultSession, ...
                inputPreparation, ...
                MessageReporter = report, ...
                ProgressReporter = options.ProgressReporter, ...
                CancellationRequested = ...
                    options.CancellationRequested, ...
                IterationCount = ...
                    settings.InitialFluxSettings.IterationCount);

            if iterationResult.IsError
                result = obj.failureResult( ...
                    inputPreparation, ...
                    iterationResult.FailureStage, ...
                    iterationResult.ErrorMessage);
                return
            end

            workflowResult = iterationResult.WorkflowResult;

            if workflowResult.IsCanceled
                report("info", "Nonlinear optimization canceled.");
                result = openmebius.application.analysis ...
                    .MFAFluxDistributionResult( ...
                    InputPreparation = inputPreparation, ...
                    WorkflowResult = workflowResult, ...
                    IsCanceled = true);
                return
            end

            minimumObjective = workflowResult.ObjectiveValues(1);
            threshold = obj.FitStatistics.chiSquareThreshold( ...
                getDOF(model), ...
                experimentalData.FragmentLabels, ...
                experimentalData.FragmentMask, ...
                0.05);
            resultSession.writeSummary( ...
                workflowResult.ObjectiveValues, ...
                workflowResult.Order, ...
                threshold);
            result = openmebius.application.analysis ...
                .MFAFluxDistributionResult( ...
                InputPreparation = inputPreparation, ...
                WorkflowResult = workflowResult, ...
                MinimumObjective = minimumObjective);

        end

    end

    methods (Static, Access = private)

        function message = inputFailureMessage(inputPreparation)

            if inputPreparation.FailureStage == "efflux"
                message = "Data validation failed.";
            else
                message = "Invalid MDV data (e.g. NaN values).";
            end

        end

        function result = failureResult( ...
                inputPreparation, stage, message)

            result = openmebius.application.analysis ...
                .MFAFluxDistributionResult( ...
                InputPreparation = inputPreparation, ...
                IsError = true, ...
                FailureStage = stage, ...
                ErrorMessage = string(message));

        end

    end

end
