classdef MFAFluxDistributionWorkflow
    % MFAFLUXDISTRIBUTIONWORKFLOW
    % Coordinates one complete MFA flux-distribution calculation.

    properties (SetAccess = private)
        InputPreparationWorkflow
        FluxVariabilityWorkflow
        InitialFluxWorkflow
        MFAWorkflow
        MFAIterationService
        SubstrateEMUFactory
        EffluxPenaltyFactory
        InstationaryInputFactory
        FitStatistics
    end

    methods

        function obj = MFAFluxDistributionWorkflow(options)

            arguments
                options.InputPreparationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAInputPreparationWorkflow()
                options.FluxVariabilityWorkflow = ...
                    openmebius.mfa.FluxVariabilityWorkflow()
                options.InitialFluxWorkflow = ...
                    openmebius.mfa.InitialFluxWorkflow()
                options.MFAWorkflow = openmebius.mfa.MFAWorkflow()
                options.MFAIterationService = ...
                    openmebius.mfa.MFAIterationService()
                options.SubstrateEMUFactory = ...
                    openmebius.mfa.SubstrateEMUFactory()
                options.EffluxPenaltyFactory = ...
                    openmebius.mfa.EffluxPenaltyFactory()
                options.InstationaryInputFactory = ...
                    openmebius.mfa.InstationaryInputFactory()
                options.FitStatistics = ...
                    openmebius.mfa.MFAFitStatistics()
            end

            obj.InputPreparationWorkflow = ...
                options.InputPreparationWorkflow;
            obj.FluxVariabilityWorkflow = ...
                options.FluxVariabilityWorkflow;
            obj.InitialFluxWorkflow = options.InitialFluxWorkflow;
            obj.MFAWorkflow = options.MFAWorkflow;
            obj.MFAIterationService = options.MFAIterationService;
            obj.SubstrateEMUFactory = options.SubstrateEMUFactory;
            obj.EffluxPenaltyFactory = options.EffluxPenaltyFactory;
            obj.InstationaryInputFactory = ...
                options.InstationaryInputFactory;
            obj.FitStatistics = options.FitStatistics;

        end

        function result = run( ...
                obj, model, experiments, experimentList, config, ...
                runContext, resultSession, resultID, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAFluxDistributionWorkflow
                model
                experiments
                experimentList
                config
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                resultSession
                resultID (1, 1) string
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.ProgressReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            report = options.MessageReporter;
            inputPreparation = obj.InputPreparationWorkflow.run( ...
                model, experiments, experimentList, config, ...
                MessageReporter = report);

            if ~isempty(inputPreparation.ExperimentalData)
                runContext.setExperimentalData( ...
                    inputPreparation.ExperimentalData);
            end

            restoreModel = onCleanup( ...
                @() inputPreparation.restoreModel());

            if ~inputPreparation.IsValid
                message = obj.inputFailureMessage(inputPreparation);
                report("error", message);
                result = obj.failureResult( ...
                    inputPreparation, "input", message);
                return
            end

            experimentalData = runContext.ExperimentalData;
            resultSession.writeGeneral( ...
                resultID, ...
                experimentalData.ExperimentalMDV, ...
                experimentalData.FragmentLabels, ...
                experimentalData.FragmentMask);
            resultSession.writeModel( ...
                model.getModelTable(), model.getModelTableRev());

            report("info", "Calculating flux variability...");
            fvaResult = obj.FluxVariabilityWorkflow.run( ...
                model, ...
                inputPreparation.GrowthRate, ...
                inputPreparation.SubstrateList, ...
                inputPreparation.Efflux, ...
                inputPreparation.EffluxFree, ...
                MessageReporter = report);
            runContext.setRightHandSide(fvaResult.RightHandSide);

            if fvaResult.IsError
                result = obj.failureResult( ...
                    inputPreparation, "fva", fvaResult.ErrorMessage);
                return
            end

            report("info", "Flux variability calculation completed.");
            runContext.setBounds( ...
                fvaResult.LowerBounds, fvaResult.UpperBounds);
            resultSession.writeFluxVariability( ...
                fvaResult.LowerBounds, ...
                fvaResult.UpperBounds, ...
                model.getIdxRev());
            averageFlux = mean( ...
                fvaResult.UpperBounds - fvaResult.LowerBounds);
            report( ...
                "info", ...
                "Average flux range: " + string(averageFlux) + ...
                " mmol/g/h");

            substrateEMUs = obj.createSubstrateEMUs( ...
                model, experiments, experimentList);
            runContext.setSubstrateEMUs(substrateEMUs);
            initialResult = obj.runInitialFlux( ...
                model, config, runContext, inputPreparation, ...
                report, options.CancellationRequested);

            if initialResult.IsCanceled || ...
                    logical(options.CancellationRequested())
                report( ...
                    "info", ...
                    "Initial flux distribution calculation canceled.");
                result = openmebius.application.analysis ...
                    .MFAFluxDistributionResult( ...
                    InputPreparation = inputPreparation, ...
                    IsCanceled = true);
                return
            end

            if initialResult.IsError
                message = ...
                    "Initial flux distribution calculation failed.";
                report("error", message);
                result = obj.failureResult( ...
                    inputPreparation, "initial", message);
                return
            end

            runContext.setInitialResult(initialResult);

            report( ...
                "info", ...
                "Initial flux distribution calculation completed.");
            resultSession.writeInitialFlux( ...
                initialResult.Fluxes, ...
                initialResult.RightHandSides, ...
                initialResult.ObjectiveValues, ...
                model.getIdxRev());

            iterationSettings = ...
                openmebius.application.analysis ...
                .MFAIterationSettingsMapper.fromBatchConfig(config);

            if iterationSettings.AnalysisMode.isInstationary()
                try
                    specification = openmebius.application.analysis ...
                        .InstationaryInputSpecificationMapper ...
                        .fromBatchConfig(config);
                    instationaryInput = ...
                        obj.InstationaryInputFactory.create( ...
                        model, specification);
                    runContext.setInstationaryInput( ...
                        instationaryInput);
                catch ME
                    message = "Instationary 13C-MFA: " + ...
                        string(ME.message);
                    report("error", message);
                    result = obj.failureResult( ...
                        inputPreparation, ...
                        "instationary", ...
                        message);
                    return
                end
            end
            workflowResult = obj.MFAWorkflow.run( ...
                initialResult.RightHandSides, ...
                @(rightHandSide) obj.runIteration( ...
                model, iterationSettings, runContext, ...
                inputPreparation, ...
                rightHandSide, report), ...
                ProgressReporter = options.ProgressReporter, ...
                IterationCompleted = ...
                    @(iteration, iterationResult) ...
                    resultSession.writeIteration( ...
                    iteration, iterationResult, model.getIdxRev()), ...
                CancellationRequested = ...
                    options.CancellationRequested, ...
                MDVMapper = @(mdv) ...
                    experimentalData.arrangeMDV(mdv));
            runContext.setWorkflowResult(workflowResult);

            if workflowResult.IsCanceled
                report("info", "Nonlinear optimization canceled.");
                result = openmebius.application.analysis ...
                    .MFAFluxDistributionResult( ...
                    InputPreparation = inputPreparation, ...
                    WorkflowResult = workflowResult, ...
                    IsCanceled = true);
                return
            end

            minimumObjective = workflowResult.ObjectiveValues(1);
            threshold = obj.FitStatistics.chiSquareThreshold( ...
                getDOF(model), ...
                experimentalData.FragmentLabels, ...
                experimentalData.FragmentMask, ...
                0.05);
            resultSession.writeSummary( ...
                workflowResult.ObjectiveValues, ...
                workflowResult.Order, ...
                threshold);
            result = openmebius.application.analysis ...
                .MFAFluxDistributionResult( ...
                InputPreparation = inputPreparation, ...
                WorkflowResult = workflowResult, ...
                MinimumObjective = minimumObjective);

        end

    end

    methods (Access = private)

        function substrateEMUs = createSubstrateEMUs( ...
                obj, model, experiments, experimentList)

            experimentCount = numel(experimentList);
            substrateEMUs = cell(experimentCount, 1);

            for i = 1:experimentCount
                substrateEMUs{i} = obj.SubstrateEMUFactory ...
                    .fromExperiment( ...
                    model, experiments, experimentList(i));
            end

        end

        function initialResult = runInitialFlux( ...
                obj, model, config, runContext, inputPreparation, ...
                reporter, cancellationRequested)

            penalty = obj.EffluxPenaltyFactory.create( ...
                model, ...
                inputPreparation.SubstrateList, ...
                inputPreparation.Efflux, ...
                inputPreparation.EffluxStandardDeviation, ...
                inputPreparation.EffluxFree);
            try
                settings = openmebius.application.analysis ...
                    .InitialFluxSettingsMapper.fromBatchConfig(config);
                input = openmebius.mfa.InitialFluxWorkflowInput( ...
                    Model = model, ...
                    Settings = settings, ...
                    RightHandSide = runContext.RightHandSide(:), ...
                    LowerBounds = runContext.LowerBounds(:), ...
                    UpperBounds = runContext.UpperBounds(:), ...
                    SubstrateEMUs = runContext.SubstrateEMUs, ...
                    ExperimentalData = runContext.ExperimentalData, ...
                    EffluxPenalty = penalty);
            catch ME
                message = "Failed to prepare initial flux input. " + ...
                    string(ME.message);
                reporter("error", message);
                initialResult = ...
                    openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message);
                return
            end

            initialResult = obj.InitialFluxWorkflow.run( ...
                input, ...
                MessageReporter = reporter, ...
                CancellationRequested = cancellationRequested);

        end

        function iterationResult = runIteration( ...
                obj, model, settings, runContext, inputPreparation, ...
                rightHandSide, reporter)

            initialResult = runContext.requireInitialResult();
            input = openmebius.mfa.MFAIterationInput( ...
                Model = model, ...
                Settings = settings, ...
                Problem = initialResult.Problem, ...
                ExperimentalData = runContext.ExperimentalData, ...
                ExperimentalMDV = runContext.experimentalMDV(), ...
                RightHandSide = rightHandSide, ...
                SubstrateList = inputPreparation.SubstrateList, ...
                Efflux = inputPreparation.Efflux, ...
                EffluxStandardDeviation = ...
                    inputPreparation.EffluxStandardDeviation, ...
                EffluxFree = inputPreparation.EffluxFree, ...
                SubstrateEMUs = runContext.SubstrateEMUs, ...
                InstationaryInput = runContext.InstationaryInput);
            iterationResult = obj.MFAIterationService.run( ...
                input, ...
                MessageReporter = reporter);

        end

    end

    methods (Static, Access = private)

        function message = inputFailureMessage(inputPreparation)

            if inputPreparation.FailureStage == "efflux"
                message = "Data validation failed.";
            else
                message = "Invalid MDV data (e.g. NaN values).";
            end

        end

        function result = failureResult( ...
                inputPreparation, stage, message)

            result = openmebius.application.analysis ...
                .MFAFluxDistributionResult( ...
                InputPreparation = inputPreparation, ...
                IsError = true, ...
                FailureStage = stage, ...
                ErrorMessage = string(message));

        end

    end

end
