classdef MFAInitialFluxApplicationWorkflow
    % MFAINITIALFLUXAPPLICATIONWORKFLOW
    % Prepares and runs the initial-flux search for one MFA analysis.

    properties (SetAccess = private)
        InitialFluxWorkflow
        SubstrateEMUFactory
        EffluxPenaltyFactory
    end

    methods

        function obj = MFAInitialFluxApplicationWorkflow(options)

            arguments
                options.InitialFluxWorkflow = ...
                    openmebius.mfa.InitialFluxWorkflow()
                options.SubstrateEMUFactory = ...
                    openmebius.mfa.SubstrateEMUFactory()
                options.EffluxPenaltyFactory = ...
                    openmebius.mfa.EffluxPenaltyFactory()
            end

            obj.InitialFluxWorkflow = options.InitialFluxWorkflow;
            obj.SubstrateEMUFactory = options.SubstrateEMUFactory;
            obj.EffluxPenaltyFactory = options.EffluxPenaltyFactory;

        end

        function result = run( ...
                obj, model, experiments, experimentList, settings, ...
                runContext, inputPreparation, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAInitialFluxApplicationWorkflow
                model
                experiments
                experimentList
                settings (1, 1) openmebius.mfa.InitialFluxSettings
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                inputPreparation (1, 1) ...
                    openmebius.application.analysis ...
                    .MFAInputPreparationResult
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested (1, 1) ...
                    function_handle = @() false
            end

            substrateEMUs = obj.createSubstrateEMUs( ...
                model, experiments, experimentList);
            runContext.setSubstrateEMUs(substrateEMUs);
            [penalty, effluxProfile] = ...
                obj.EffluxPenaltyFactory.create( ...
                model, ...
                inputPreparation.SubstrateList, ...
                inputPreparation.Efflux, ...
                inputPreparation.EffluxStandardDeviation, ...
                inputPreparation.EffluxFree);

            try
                input = openmebius.mfa.InitialFluxWorkflowInput( ...
                    Model = model, ...
                    Settings = settings, ...
                    RightHandSide = runContext.RightHandSide(:), ...
                    LowerBounds = runContext.LowerBounds(:), ...
                    UpperBounds = runContext.UpperBounds(:), ...
                    SubstrateEMUs = runContext.SubstrateEMUs, ...
                    ExperimentalData = runContext.ExperimentalData, ...
                    EffluxPenalty = penalty, ...
                    EffluxProfile = effluxProfile, ...
                    ReversibleReactionIndices = model.getIdxRev());
            catch ME
                message = "Failed to prepare initial flux input. " + ...
                    string(ME.message);
                options.MessageReporter("error", message);
                result = ...
                    openmebius.mfa.InitialFluxWorkflowResult.failure( ...
                    message);
                return
            end

            result = obj.InitialFluxWorkflow.run( ...
                input, ...
                MessageReporter = options.MessageReporter, ...
                CancellationRequested = ...
                options.CancellationRequested);

            if ~result.IsError && ~result.IsCanceled
                runContext.setInitialResult(result);
            end

        end

    end

    methods (Access = private)

        function substrateEMUs = createSubstrateEMUs( ...
                obj, model, experiments, experimentList)

            experimentCount = numel(experimentList);
            substrateEMUs = cell(experimentCount, 1);

            for i = 1:experimentCount
                substrateEMUs{i} = obj.SubstrateEMUFactory ...
                    .fromExperiment( ...
                    model, experiments, experimentList(i));
            end

        end

    end

end
