classdef MFAIterationApplicationWorkflow
    % MFAITERATIONAPPLICATIONWORKFLOW
    % Prepares and executes the nonlinear MFA iterations.

    properties (SetAccess = private)
        MFAWorkflow
        MFAIterationService
        InstationaryInputFactory
    end

    methods

        function obj = MFAIterationApplicationWorkflow(options)

            arguments
                options.MFAWorkflow = openmebius.mfa.MFAWorkflow()
                options.MFAIterationService = ...
                    openmebius.mfa.MFAIterationService()
                options.InstationaryInputFactory = ...
                    openmebius.mfa.InstationaryInputFactory()
            end

            obj.MFAWorkflow = options.MFAWorkflow;
            obj.MFAIterationService = options.MFAIterationService;
            obj.InstationaryInputFactory = ...
                options.InstationaryInputFactory;

        end

        function result = run( ...
                obj, model, settings, instationarySpecification, ...
                runContext, resultSession, inputPreparation, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAIterationApplicationWorkflow
                model
                settings (1, 1) openmebius.mfa.MFAIterationSettings
                instationarySpecification
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                resultSession
                inputPreparation (1, 1) ...
                    openmebius.application.analysis ...
                    .MFAInputPreparationResult
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.ProgressReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested (1, 1) ...
                    function_handle = @() false
                options.IterationCount (1, 1) double = NaN
            end

            reporter = options.MessageReporter;

            if settings.AnalysisMode.isInstationary()

                if isempty(instationarySpecification)
                    message = "Instationary 13C-MFA: Input " + ...
                        "specification is required.";
                    reporter("error", message);
                    result = openmebius.application.analysis ...
                        .MFAIterationApplicationResult.failure( ...
                        "instationary", message);
                    return
                end

                try
                    instationaryInput = ...
                        obj.InstationaryInputFactory.create( ...
                        model, instationarySpecification);
                    runContext.setInstationaryInput( ...
                        instationaryInput);
                catch ME
                    message = "Instationary 13C-MFA: " + ...
                        string(ME.message);
                    reporter("error", message);
                    result = openmebius.application.analysis ...
                        .MFAIterationApplicationResult.failure( ...
                        "instationary", message);
                    return
                end

            end

            initialResult = runContext.requireInitialResult();
            experimentalData = runContext.ExperimentalData;
            workflowResult = obj.MFAWorkflow.run( ...
                initialResult.RightHandSides, ...
                @(rightHandSide) obj.runIteration( ...
                model, settings, runContext, ...
                inputPreparation, rightHandSide, reporter), ...
                ProgressReporter = options.ProgressReporter, ...
                IterationCompleted = ...
                @(iteration, iterationResult) ...
                resultSession.writeIteration( ...
                iteration, iterationResult, model.getIdxRev()), ...
                CancellationRequested = ...
                options.CancellationRequested, ...
                MDVMapper = @(mdv) ...
                experimentalData.arrangeMDV(mdv), ...
                IterationCount = options.IterationCount);
            runContext.setWorkflowResult(workflowResult);
            result = openmebius.application.analysis ...
                .MFAIterationApplicationResult( ...
                WorkflowResult = workflowResult);

        end

    end

    methods (Access = private)

        function iterationResult = runIteration( ...
                obj, model, settings, runContext, inputPreparation, ...
                rightHandSide, reporter)

            initialResult = runContext.requireInitialResult();
            input = openmebius.mfa.MFAIterationInput( ...
                Model = model, ...
                Settings = settings, ...
                Problem = initialResult.Problem, ...
                ExperimentalData = runContext.ExperimentalData, ...
                ExperimentalMDV = runContext.experimentalMDV(), ...
                RightHandSide = rightHandSide, ...
                SubstrateList = inputPreparation.SubstrateList, ...
                Efflux = inputPreparation.Efflux, ...
                EffluxStandardDeviation = ...
                inputPreparation.EffluxStandardDeviation, ...
                EffluxFree = inputPreparation.EffluxFree, ...
                GrowthRate = inputPreparation.GrowthRate, ...
                GrowthRateStandardDeviation = ...
                inputPreparation.GrowthRateStandardDeviation, ...
                GrowthRateFree = inputPreparation.GrowthRateFree, ...
                SubstrateEMUs = runContext.SubstrateEMUs, ...
                InstationaryInput = runContext.InstationaryInput);
            iterationResult = obj.MFAIterationService.run( ...
                input, ...
                MessageReporter = reporter);

        end

    end

end
