classdef MFAInputPreparationWorkflow
    % MFAINPUTPREPARATIONWORKFLOW
    % Validates efflux inputs, prepares MDV data, and owns model changes.

    properties (SetAccess = private)
        Validator
        ExperimentalDataBuilder
        EffluxFreeSessionFactory (1, 1) function_handle = ...
            @(~, ~, ~) []
    end

    methods

        function obj = MFAInputPreparationWorkflow(options)

            arguments
                options.Validator = openmebius.mfa.MFAInputValidator()
                options.ExperimentalDataBuilder = ...
                    openmebius.mfa.MFAExperimentalDataBuilder()
                options.EffluxFreeSessionFactory (1, 1) ...
                    function_handle = @(model, substrates, reporter) ...
                    openmebius.application.analysis ...
                    .EffluxFreeModelSession( ...
                    model, substrates, MessageReporter = reporter)
            end

            obj.Validator = options.Validator;
            obj.ExperimentalDataBuilder = ...
                options.ExperimentalDataBuilder;
            obj.EffluxFreeSessionFactory = ...
                options.EffluxFreeSessionFactory;

        end % constructor

        function result = run( ...
                obj, model, experiments, experimentList, settings, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .MFAInputPreparationWorkflow
                model
                experiments
                experimentList
                settings (1, 1) openmebius.application.analysis ...
                    .MFAInputPreparationSettings
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
            end

            effluxValidation = obj.Validator.validateEfflux( ...
                model, experiments, experimentList, ...
                settings.EffluxPerturbation);

            if ~effluxValidation.IsValid
                options.MessageReporter( ...
                    "error", effluxValidation.ErrorMessage);
                result = openmebius.application.analysis ...
                    .MFAInputPreparationResult( ...
                    IsValid = false, ...
                    FailureStage = "efflux", ...
                    ErrorMessage = effluxValidation.ErrorMessage);
                return
            end

            value = effluxValidation.Value;
            session = [];

            if settings.EffluxPerturbation.Enabled && ...
                    any(value.EffluxFree)
                freeSubstrates = value.SubstrateList( ...
                    logical(value.EffluxFree));
                session = obj.EffluxFreeSessionFactory( ...
                    model, ...
                    freeSubstrates, ...
                    options.MessageReporter);
                message = "Efflux reactions were set as free variables: " + ...
                    strjoin(freeSubstrates, ", ") + ".";
                options.MessageReporter("info", message);
            end

            try
                experimentalData = obj.ExperimentalDataBuilder.build( ...
                    model, experiments, experimentList, ...
                    settings.FragmentSelection);
                mdvValidation = obj.Validator.validateMDV( ...
                    experimentalData.ExperimentalMDV, ...
                    experimentalData.FragmentLabels, ...
                    experimentalData.FragmentMask);
            catch ME
                openmebius.application.analysis ...
                    .MFAInputPreparationWorkflow.restoreSession(session);
                rethrow(ME);
            end

            if ~mdvValidation.IsValid
                options.MessageReporter( ...
                    "error", mdvValidation.ErrorMessage);
                result = openmebius.application.analysis ...
                    .MFAInputPreparationResult( ...
                    IsValid = false, ...
                    FailureStage = "mdv", ...
                    ErrorMessage = mdvValidation.ErrorMessage, ...
                    GrowthRate = value.GrowthRate, ...
                    SubstrateList = value.SubstrateList, ...
                    Efflux = value.Efflux, ...
                    EffluxStandardDeviation = ...
                    value.EffluxStandardDeviation, ...
                    EffluxFree = logical(value.EffluxFree), ...
                    ExperimentalData = experimentalData, ...
                    EffluxFreeSession = session);
                return
            end

            result = openmebius.application.analysis ...
                .MFAInputPreparationResult( ...
                IsValid = true, ...
                GrowthRate = value.GrowthRate, ...
                SubstrateList = value.SubstrateList, ...
                Efflux = value.Efflux, ...
                EffluxStandardDeviation = ...
                value.EffluxStandardDeviation, ...
                EffluxFree = logical(value.EffluxFree), ...
                ExperimentalData = experimentalData, ...
                EffluxFreeSession = session);

        end % run

    end % methods

    methods (Static, Access = private)

        function restoreSession(session)

            if ~isempty(session)
                session.restore();
            end

        end % restoreSession

    end % methods (Static, Access = private)

end % classdef
