classdef MFANumericalDependenciesFactory
    % MFANUMERICALDEPENDENCIESFACTORY Resolves numerical MFA services.

    methods

        function dependencies = create(~, configuration)

            arguments
                ~
                configuration (1, 1) openmebius.application ...
                    .analysis.MFANumericalComposition
            end

            constraintBuilder = configuration.MFAConstraintBuilder;
            fluxProblemFactory = ...
                configuration.FluxVariabilityProblemFactory;

            if isempty(fluxProblemFactory)
                fluxProblemFactory = ...
                    openmebius.mfa.FluxVariabilityProblemFactory( ...
                    ConstraintBuilder = constraintBuilder);
            end

            iterationRunner = configuration.MFAIterationRunner;

            if isempty(iterationRunner)
                iterationRunner = openmebius.mfa ...
                    .MFAIterationRunner( ...
                    Solver = configuration.SteadyStateSolver);
            end

            fitStatistics = configuration.MFAFitStatistics;
            predictor = configuration.SteadyStateMDVPredictor;
            initialFluxWorkflow = configuration.InitialFluxWorkflow;

            if isempty(initialFluxWorkflow)
                initialFluxWorkflow = openmebius.mfa ...
                    .InitialFluxWorkflow( ...
                    ProblemFactory = configuration.MFAProblemFactory, ...
                    PointGenerator = ...
                    configuration.InitialPointGenerator, ...
                    FitStatistics = fitStatistics, ...
                    MDVPredictor = predictor);
            end

            confidenceWorkflow = ...
                configuration.ConfidenceIntervalWorkflow;

            if isempty(confidenceWorkflow)
                confidenceWorkflow = openmebius.mfa ...
                    .ConfidenceIntervalWorkflow( ...
                    MonteCarloSolver = configuration ...
                    .MonteCarloConfidenceIntervalSolver);
            end

            substrateFactory = configuration.SubstrateEMUFactory;
            nextLabelWorkflow = ...
                configuration.NextLabelExperimentWorkflow;

            if isempty(nextLabelWorkflow)
                nextLabelWorkflow = openmebius.mfa ...
                    .NextLabelExperimentWorkflow( ...
                    SubstrateEMUFactory = substrateFactory, ...
                    MDVPredictor = predictor);
            end

            effluxFactory = configuration.EffluxPenaltyFactory;
            objectiveFactory = openmebius.mfa.MFAObjectiveFactory( ...
                MDVPredictor = predictor, ...
                EffluxPenaltyFactory = effluxFactory);
            iterationService = openmebius.mfa ...
                .MFAIterationService( ...
                Runner = iterationRunner, ...
                ObjectiveFactory = objectiveFactory);
            fluxSolver = configuration.FluxVariabilitySolver;
            fluxWorkflow = configuration.FluxVariabilityWorkflow;

            if isempty(fluxWorkflow)
                fluxWorkflow = openmebius.mfa ...
                    .FluxVariabilityWorkflow( ...
                    ConstraintBuilder = constraintBuilder, ...
                    ProblemFactory = fluxProblemFactory, ...
                    Solver = fluxSolver);
            end

            dependencies = openmebius.application.analysis ...
                .MFANumericalDependencies( ...
                FluxVariabilitySolver = fluxSolver, ...
                FluxVariabilityProblemFactory = fluxProblemFactory, ...
                FluxVariabilityWorkflow = fluxWorkflow, ...
                InitialFluxWorkflow = initialFluxWorkflow, ...
                MFAIterationRunner = iterationRunner, ...
                MFAObjectiveFactory = objectiveFactory, ...
                MFAIterationService = iterationService, ...
                MFAWorkflow = configuration.MFAWorkflow, ...
                ConfidenceIntervalWorkflow = confidenceWorkflow, ...
                NextLabelExperimentWorkflow = nextLabelWorkflow, ...
                MFAInputValidator = configuration.MFAInputValidator, ...
                MFAFitStatistics = fitStatistics, ...
                MFAExperimentalDataBuilder = ...
                configuration.MFAExperimentalDataBuilder, ...
                MFAConstraintBuilder = constraintBuilder, ...
                SubstrateEMUFactory = substrateFactory, ...
                SteadyStateMDVPredictor = predictor, ...
                EffluxPenaltyFactory = effluxFactory, ...
                InstationaryInputFactory = ...
                configuration.InstationaryInputFactory);

        end

    end

end
