classdef MFAResultSession < handle
    % MFARESULTSESSION
    % Owns mutable MFA result state and delegates checkpoint persistence.

    properties (SetAccess = private)
        Result = []
        Progress (1, 1) openmebius.application.analysis.AnalysisProgress
    end

    properties (Access = private)
        Coordinator
        FailureReporter (1, 1) function_handle = @(~) []
    end

    methods

        function obj = MFAResultSession(options)

            arguments
                options.Coordinator = openmebius.infrastructure.result ...
                    .MFAResultCoordinator()
                options.FailureReporter (1, 1) function_handle = ...
                    @(~) []
            end

            obj.Coordinator = options.Coordinator;
            obj.FailureReporter = options.FailureReporter;
            obj.Progress = openmebius.application.analysis.AnalysisProgress();

        end

        function writeGeneral( ...
                obj, resultID, experimentalMDV, fragmentList, ...
                fragmentMask)

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeGeneral( ...
                obj.Result, ...
                obj.Progress, ...
                resultID, ...
                experimentalMDV, ...
                fragmentList, ...
                fragmentMask);
            obj.reportFailure(isSuccess, message);

        end

        function writeModel(obj, modelTable, reversibleModelTable)

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeModel( ...
                obj.Result, ...
                obj.Progress, ...
                modelTable, ...
                reversibleModelTable);
            obj.reportFailure(isSuccess, message);

        end

        function writeFluxVariability( ...
                obj, lowerBounds, upperBounds, ...
                reversibleReactionIndices)

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeFluxVariability( ...
                obj.Result, ...
                obj.Progress, ...
                lowerBounds, ...
                upperBounds, ...
                reversibleReactionIndices);
            obj.reportFailure(isSuccess, message);

        end

        function writeInitialFlux( ...
                obj, flux, rightHandSide, objectiveValues, ...
                reversibleReactionIndices)

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeInitialFlux( ...
                obj.Result, ...
                obj.Progress, ...
                flux, ...
                rightHandSide, ...
                objectiveValues, ...
                reversibleReactionIndices);
            obj.reportFailure(isSuccess, message);

        end

        function writeIteration( ...
                obj, iteration, iterationResult, ...
                reversibleReactionIndices)

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeIteration( ...
                obj.Result, ...
                obj.Progress, ...
                iteration, ...
                iterationResult, ...
                reversibleReactionIndices);
            obj.reportFailure(isSuccess, message);

        end

        function writeSummary( ...
                obj, objectiveValues, order, threshold)

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeSummary( ...
                obj.Result, ...
                obj.Progress, ...
                objectiveValues, ...
                order, ...
                threshold);
            obj.reportFailure(isSuccess, message);

        end

        function writeMonteCarloConfidenceInterval( ...
                obj, lowerBounds, upperBounds, ...
                confidenceIntervalConfig, output)

            arguments
                obj (1, 1) openmebius.application.analysis.MFAResultSession
                lowerBounds double
                upperBounds double
                confidenceIntervalConfig (1, 1) openmebius.mfa ...
                    .ConfidenceIntervalSettings
                output (1, 1) struct
            end

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeMonteCarloConfidenceInterval( ...
                obj.Result, ...
                obj.Progress, ...
                lowerBounds, ...
                upperBounds, ...
                confidenceIntervalConfig, ...
                output);
            obj.reportFailure(isSuccess, message);

        end

        function writeGridSearchConfidenceInterval( ...
                obj, lowerBounds, upperBounds, ...
                confidenceIntervalConfig, output, reactionIDs)

            arguments
                obj (1, 1) openmebius.application.analysis.MFAResultSession
                lowerBounds (:, 1) double
                upperBounds (:, 1) double
                confidenceIntervalConfig (1, 1) openmebius.mfa ...
                    .ConfidenceIntervalSettings
                output (1, 1) struct
                reactionIDs (:, 1) string
            end

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeGridSearchConfidenceInterval( ...
                obj.Result, ...
                obj.Progress, ...
                lowerBounds, ...
                upperBounds, ...
                confidenceIntervalConfig, ...
                output, ...
                reactionIDs);
            obj.reportFailure(isSuccess, message);

        end

        function writeSuggestionTable(obj, settings)

            arguments
                obj (1, 1) openmebius.application.analysis.MFAResultSession
                settings (1, 1) openmebius.mfa ...
                    .NextLabelExperimentSettings
            end

            [isSuccess, message] = ...
                obj.Coordinator.writeSuggestionTable( ...
                settings);
            obj.reportFailure(isSuccess, message);

        end

        function writeNextLabelConfidenceInterval( ...
                obj, pattern, lowerBounds, upperBounds)

            [obj.Result, obj.Progress, isSuccess, message] = ...
                obj.Coordinator.writeNextLabelConfidenceInterval( ...
                obj.Result, ...
                obj.Progress, ...
                pattern, ...
                lowerBounds, ...
                upperBounds);
            obj.reportFailure(isSuccess, message);

        end

    end

    methods (Access = private)

        function reportFailure(obj, isSuccess, message)

            if ~isSuccess
                obj.FailureReporter(string(message));
            end

        end

    end

end
