classdef MFAResultDependenciesFactory
    % MFARESULTDEPENDENCIESFACTORY Resolves persistence dependencies.

    methods

        function dependencies = create( ...
                ~, configuration, hdf5FilePath, isExport)

            arguments
                ~
                configuration (1, 1) openmebius.application ...
                    .analysis.MFAResultComposition
                hdf5FilePath (1, 1) string
                isExport (1, 1) logical
            end

            inputWriter = configuration.MFAInputSnapshotWriter;

            if isempty(inputWriter)
                inputWriter = openmebius.infrastructure.result ...
                    .MFAInputSnapshotWriter( ...
                    Repository = configuration.Hdf5ResultRepository);
            end

            resultWriter = configuration.MFAResultCheckpointWriter;

            if isempty(resultWriter)
                resultWriter = openmebius.infrastructure.result ...
                    .MFAResultCheckpointWriter( ...
                    Repository = configuration.Hdf5ResultRepository);
            end

            nextLabelWriter = ...
                configuration.NextLabelResultCheckpointWriter;

            if isempty(nextLabelWriter)
                nextLabelWriter = openmebius.infrastructure.result ...
                    .NextLabelResultCheckpointWriter( ...
                    Repository = configuration.Hdf5ResultRepository);
            end

            coordinator = configuration.MFAResultCoordinator;

            if isempty(coordinator)
                coordinator = openmebius.infrastructure.result ...
                    .MFAResultCoordinator( ...
                    InputSnapshotWriter = inputWriter, ...
                    ResultCheckpointWriter = resultWriter, ...
                    NextLabelCheckpointWriter = nextLabelWriter, ...
                    HDF5FilePath = hdf5FilePath, ...
                    IsExport = isExport);
            end

            dependencies = openmebius.application.analysis ...
                .MFAResultDependencies( ...
                MFAInputSnapshotWriter = inputWriter, ...
                MFAResultCheckpointWriter = resultWriter, ...
                NextLabelResultCheckpointWriter = ...
                    nextLabelWriter, ...
                MFAResultCoordinator = coordinator);

        end

    end

end
