classdef MFAWorkflowDependenciesFactory
    % MFAWORKFLOWDEPENDENCIESFACTORY Resolves application workflows.

    methods

        function dependencies = create( ...
                ~, configuration, numerical)

            arguments
                ~
                configuration (1, 1) openmebius.application ...
                    .analysis.MFAWorkflowComposition
                numerical (1, 1) openmebius.application.analysis ...
                    .MFANumericalDependencies
            end

            inputWorkflow = ...
                configuration.MFAInputPreparationWorkflow;

            if isempty(inputWorkflow)
                inputWorkflow = openmebius.application.analysis ...
                    .MFAInputPreparationWorkflow( ...
                    Validator = numerical.MFAInputValidator, ...
                    ExperimentalDataBuilder = ...
                    numerical.MFAExperimentalDataBuilder);
            end

            initialWorkflow = ...
                configuration.InitialFluxApplicationWorkflow;

            if isempty(initialWorkflow)
                initialWorkflow = openmebius.application.analysis ...
                    .MFAInitialFluxApplicationWorkflow( ...
                    InitialFluxWorkflow = ...
                    numerical.InitialFluxWorkflow, ...
                    SubstrateEMUFactory = ...
                    numerical.SubstrateEMUFactory, ...
                    EffluxPenaltyFactory = ...
                    numerical.EffluxPenaltyFactory);
            end

            iterationWorkflow = ...
                configuration.MFAIterationApplicationWorkflow;

            if isempty(iterationWorkflow)
                iterationWorkflow = openmebius.application.analysis ...
                    .MFAIterationApplicationWorkflow( ...
                    MFAWorkflow = numerical.MFAWorkflow, ...
                    MFAIterationService = ...
                    numerical.MFAIterationService, ...
                    InstationaryInputFactory = ...
                    numerical.InstationaryInputFactory);
            end

            distributionWorkflow = ...
                configuration.FluxDistributionWorkflow;

            if isempty(distributionWorkflow)
                distributionWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAFluxDistributionWorkflow( ...
                    InputPreparationWorkflow = inputWorkflow, ...
                    FluxVariabilityWorkflow = ...
                    numerical.FluxVariabilityWorkflow, ...
                    InitialFluxApplicationWorkflow = ...
                    initialWorkflow, ...
                    MFAIterationApplicationWorkflow = ...
                    iterationWorkflow, ...
                    FitStatistics = numerical.MFAFitStatistics);
            end

            confidenceWorkflow = configuration ...
                .ConfidenceIntervalApplicationWorkflow;

            if isempty(confidenceWorkflow)
                confidenceWorkflow = openmebius.application.analysis ...
                    .MFAConfidenceIntervalWorkflow( ...
                    ConfidenceIntervalWorkflow = ...
                    numerical.ConfidenceIntervalWorkflow, ...
                    MFAIterationService = ...
                    numerical.MFAIterationService, ...
                    FitStatistics = numerical.MFAFitStatistics);
            end

            nextWorkflow = configuration.NextFluxExperimentWorkflow;

            if isempty(nextWorkflow)
                nextWorkflow = openmebius.application.analysis ...
                    .NextFluxExperimentWorkflow( ...
                    ConfidenceIntervalApplicationWorkflow = ...
                    confidenceWorkflow, ...
                    NextLabelExperimentWorkflow = ...
                    numerical.NextLabelExperimentWorkflow);
            end

            dependencies = openmebius.application.analysis ...
                .MFAWorkflowDependencies( ...
                MFAInputPreparationWorkflow = inputWorkflow, ...
                InitialFluxApplicationWorkflow = initialWorkflow, ...
                MFAIterationApplicationWorkflow = iterationWorkflow, ...
                ConfidenceIntervalApplicationWorkflow = ...
                confidenceWorkflow, ...
                NextFluxExperimentWorkflow = nextWorkflow, ...
                FluxDistributionWorkflow = distributionWorkflow);

        end

    end

end
