classdef NextFluxExperimentWorkflow
    % NEXTFLUXEXPERIMENTWORKFLOW
    % Coordinates confidence intervals and next-label suggestions.

    properties (SetAccess = private)
        ConfidenceIntervalApplicationWorkflow
        NextLabelExperimentWorkflow
    end

    methods

        function obj = NextFluxExperimentWorkflow(options)

            arguments
                options.ConfidenceIntervalApplicationWorkflow = ...
                    openmebius.application.analysis ...
                    .MFAConfidenceIntervalWorkflow()
                options.NextLabelExperimentWorkflow = ...
                    openmebius.mfa.NextLabelExperimentWorkflow()
            end

            obj.ConfidenceIntervalApplicationWorkflow = ...
                options.ConfidenceIntervalApplicationWorkflow;
            obj.NextLabelExperimentWorkflow = ...
                options.NextLabelExperimentWorkflow;

        end

        function result = run( ...
                obj, model, experiments, experimentList, config, ...
                runContext, resultSession, inputPreparation, options)

            arguments
                obj (1, 1) openmebius.application.analysis ...
                    .NextFluxExperimentWorkflow
                model
                experiments
                experimentList
                config
                runContext (1, 1) openmebius.application.analysis ...
                    .MFAAnalysisRunContext
                resultSession
                inputPreparation
                options.MessageReporter (1, 1) function_handle = ...
                    @(~, ~) []
                options.CancellationRequested ...
                    (1, 1) function_handle = @() false
            end

            reporter = options.MessageReporter;
            confidenceSettings = openmebius.application.analysis ...
                .MFAConfidenceIntervalRunSettingsMapper ...
                .fromBatchConfig(config);
            confidenceResult = ...
                obj.ConfidenceIntervalApplicationWorkflow.run( ...
                model, ...
                confidenceSettings, ...
                runContext, ...
                resultSession, ...
                inputPreparation, ...
                PersistResult = false, ...
                MessageReporter = reporter, ...
                CancellationRequested = ...
                    options.CancellationRequested);

            if confidenceResult.Method == "Monte Carlo" && ...
                    confidenceResult.IsCalculated
                resultSession.writeMonteCarloConfidenceInterval( ...
                    confidenceResult.LowerBounds, ...
                    confidenceResult.UpperBounds, ...
                    confidenceSettings.ConfidenceIntervalSettings, ...
                    confidenceResult.Output);
            end

            if confidenceResult.IsCanceled || ...
                    logical(options.CancellationRequested())
                reporter( ...
                    "info", ...
                    "Next flux experiment suggestion canceled.");
                result = obj.createResult( ...
                    confidenceResult, [], true, false, "");
                return
            end

            if confidenceResult.IsError
                result = obj.createResult( ...
                    confidenceResult, ...
                    [], ...
                    false, ...
                    true, ...
                    confidenceResult.ErrorMessage);
                return
            end

            if ~confidenceResult.IsCalculated || ...
                    isempty(confidenceResult.LowerBounds)
                message = "A calculated confidence interval is " + ...
                    "required to suggest the next flux experiment.";
                reporter("error", message);
                result = obj.createResult( ...
                    confidenceResult, [], false, true, message);
                return
            end

            resultSession.writeSuggestionTable( ...
                config.suggestionTable, ...
                config.suggestionTableVarNames);
            [lowerBounds, upperBounds] = obj.splitBounds( ...
                model, ...
                confidenceResult.LowerBounds, ...
                confidenceResult.UpperBounds);
            runContext.setBounds(lowerBounds, upperBounds);
            averageFlux = mean(upperBounds - lowerBounds);
            reporter( ...
                "info", ...
                "Average flux range: " + string(averageFlux) + ...
                " mmol/g/h");

            try
                workflowResult = runContext.requireWorkflowResult();
                suggestionResult = ...
                    obj.NextLabelExperimentWorkflow.run( ...
                    model, ...
                    experiments, ...
                    experimentList, ...
                    config, ...
                    workflowResult.Fluxes(:, 1), ...
                    ConfidenceIntervalFunction = ...
                        @(mdv, emus) ...
                        obj.calculateCandidateConfidenceInterval( ...
                        model, ...
                        confidenceSettings, ...
                        runContext, ...
                        resultSession, ...
                        inputPreparation, ...
                        mdv, ...
                        emus, ...
                        reporter, ...
                        options.CancellationRequested), ...
                    PatternCompleted = ...
                        @(pattern, lower, upper) ...
                        resultSession ...
                        .writeNextLabelConfidenceInterval( ...
                        pattern, lower, upper), ...
                    MessageReporter = reporter, ...
                    CancellationRequested = ...
                        options.CancellationRequested);
            catch ME
                message = "Next flux experiment suggestion failed. " + ...
                    string(ME.message);
                reporter("error", message);
                result = obj.createResult( ...
                    confidenceResult, [], false, true, message);
                return
            end

            result = obj.createResult( ...
                confidenceResult, ...
                suggestionResult, ...
                suggestionResult.IsCanceled, ...
                false, ...
                "");

        end

    end

    methods (Access = private)

        function [lowerBounds, upperBounds, output] = ...
                calculateCandidateConfidenceInterval( ...
                obj, model, settings, runContext, resultSession, ...
                inputPreparation, experimentalMDV, substrateEMUs, ...
                reporter, cancellationRequested)

            confidenceResult = ...
                obj.ConfidenceIntervalApplicationWorkflow.run( ...
                model, ...
                settings, ...
                runContext, ...
                resultSession, ...
                inputPreparation, ...
                ExperimentalMDV = experimentalMDV, ...
                SubstrateEMUs = substrateEMUs, ...
                PersistResult = false, ...
                MessageReporter = reporter, ...
                CancellationRequested = cancellationRequested);

            if confidenceResult.IsError
                error( ...
                    "OpenMebius2:NextFluxExperiment:" + ...
                    "CandidateConfidenceIntervalFailed", ...
                    "%s", confidenceResult.ErrorMessage);
            end

            lowerBounds = confidenceResult.LowerBounds;
            upperBounds = confidenceResult.UpperBounds;
            output = confidenceResult.Output;

        end

    end

    methods (Static, Access = private)

        function [lowerBounds, upperBounds] = splitBounds( ...
                model, confidenceLowerBounds, confidenceUpperBounds)

            lowerBounds = model.getSplittedFlux( ...
                confidenceLowerBounds(1:end - 1, end));
            upperBounds = model.getSplittedFlux( ...
                confidenceUpperBounds(1:end - 1, end));
            lowerBounds = [ ...
                lowerBounds; confidenceLowerBounds(end, end)];
            upperBounds = [ ...
                upperBounds; confidenceUpperBounds(end, end)];

        end

        function result = createResult( ...
                confidenceResult, suggestionResult, ...
                isCanceled, isError, errorMessage)

            result = openmebius.application.analysis ...
                .NextFluxExperimentResult( ...
                ConfidenceIntervalResult = confidenceResult, ...
                SuggestionResult = suggestionResult, ...
                LowerBounds = confidenceResult.LowerBounds, ...
                UpperBounds = confidenceResult.UpperBounds, ...
                Output = confidenceResult.Output, ...
                IsCanceled = isCanceled, ...
                IsError = isError, ...
                ErrorMessage = string(errorMessage));

        end

    end

end
