classdef SteadyStateOptionsMapper
    % STEADYSTATEOPTIONSMAPPER
    % Maps persisted Batch configuration to typed MFA solver options.

    methods (Static)

        function [options, warnings] = fromBatchConfig(config)

            arguments
                config (1, 1) struct
            end

            warnings = strings(0, 1);
            algorithm = "sqp";

            if isfield(config, 'algorithm') && ~isempty(config.algorithm)
                candidate = lower(string(config.algorithm));
                candidate = candidate(1);

                switch candidate
                    case {"sqp", "sqp-legacy"}
                        algorithm = candidate;
                    case {"ipms", "interior-point", "interior point"}
                        algorithm = "interior-point";
                    otherwise
                        warnings(end + 1, 1) = ...
                            "Unknown FMINCON algorithm '" + candidate + ...
                            "'. Using sqp.";
                end

            end

            userConfig = struct;

            if isfield(config, 'fmincon') && isstruct(config.fmincon)
                userConfig = config.fmincon;
            end

            finiteDifferenceType = lower(string( ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readString( ...
                userConfig, 'finiteDifferenceType', 'central')));

            if ~ismember(finiteDifferenceType, ["forward", "central"])
                finiteDifferenceType = "central";
            end

            searchConfig = openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readSearchConfig(userConfig);
            defaultCandidates = [1e-3; 1e-4; 1e-5; 1e-6; 1e-7];
            options = openmebius.mfa.SteadyStateOptions( ...
                Algorithm = algorithm, ...
                MaxFunctionEvaluations = max(1000, round( ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'maxFunctionEvaluations', 1000000))), ...
                MaxIterations = max(100, round( ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'maxIterations', 2000))), ...
                FunctionTolerance = max(0, ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'functionTolerance', 1e-6)), ...
                StepTolerance = max(0, ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'stepTolerance', 1e-10)), ...
                OptimalityTolerance = max(0, ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'optimalityTolerance', 1e-8)), ...
                ConstraintTolerance = max(0, ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'constraintTolerance', 1e-8)), ...
                FiniteDifferenceType = finiteDifferenceType, ...
                FiniteDifferenceStepSize = max(eps, ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'finiteDifferenceStepSize', 1e-6)), ...
                ScaleProblem = string( ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readString( ...
                userConfig, 'scaleProblem', 'obj-and-constr')), ...
                RejectWorseThanInitial = ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readLogical( ...
                userConfig, 'rejectWorseThanInitial', true), ...
                ObjectiveIncreaseTolerance = max(0, ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'objectiveIncreaseTolerance', 1e-6)), ...
                InitialFeasibilityTolerance = max(0, ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                userConfig, 'initialFeasibilityTolerance', 1e-7)), ...
                StepSizeSearchEnabled = ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readLogical( ...
                searchConfig, 'enabled', true), ...
                IncludeConfiguredStep = ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readLogical( ...
                searchConfig, 'includeConfiguredStep', true), ...
                MaxStepSizeCandidates = max(1, round( ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumeric( ...
                searchConfig, 'maxCandidates', ...
                numel(defaultCandidates) + 1))), ...
                StepSizeCandidates = ...
                openmebius.application.analysis ...
                .SteadyStateOptionsMapper.readNumericVector( ...
                searchConfig, 'candidates', defaultCandidates));

        end % fromBatchConfig

    end % methods (Static)

    methods (Static, Access = private)

        function searchConfig = readSearchConfig(userConfig)

            searchConfig = struct;

            if isfield(userConfig, 'finiteDifferenceStepSizeSearch') && ...
                    ~isempty(userConfig.finiteDifferenceStepSizeSearch)
                candidate = userConfig.finiteDifferenceStepSizeSearch;
            elseif isfield(userConfig, 'stepSizeSearch') && ...
                    ~isempty(userConfig.stepSizeSearch)
                candidate = userConfig.stepSizeSearch;
            else
                return
            end

            if isstruct(candidate)
                searchConfig = candidate;
            else
                searchConfig.enabled = candidate;
            end

        end % readSearchConfig

        function value = readNumeric(config, fieldName, defaultValue)

            value = defaultValue;

            if isstruct(config) && isfield(config, fieldName) && ...
                    ~isempty(config.(fieldName))
                candidate = config.(fieldName);

                if isnumeric(candidate) || islogical(candidate)
                    value = double(candidate(1));
                end

            end

        end % readNumeric

        function value = readLogical(config, fieldName, defaultValue)

            value = defaultValue;

            if isstruct(config) && isfield(config, fieldName) && ...
                    ~isempty(config.(fieldName))
                candidate = config.(fieldName);

                if islogical(candidate) || isnumeric(candidate)
                    value = logical(candidate(1));
                elseif ischar(candidate) || isstring(candidate)
                    candidate = lower(string(candidate));
                    value = ismember( ...
                        candidate(1), ["true", "1", "yes", "on"]);
                end

            end

        end % readLogical

        function value = readString(config, fieldName, defaultValue)

            value = string(defaultValue);

            if isstruct(config) && isfield(config, fieldName) && ...
                    ~isempty(config.(fieldName))
                candidate = config.(fieldName);

                if ischar(candidate) || isstring(candidate)
                    candidate = string(candidate);
                    value = candidate(1);
                end

            end

        end % readString

        function values = readNumericVector( ...
                config, fieldName, defaultValues)

            values = double(defaultValues(:));

            if isstruct(config) && isfield(config, fieldName) && ...
                    ~isempty(config.(fieldName))
                candidate = config.(fieldName);

                if isnumeric(candidate) || islogical(candidate)
                    values = double(candidate(:));
                elseif iscell(candidate)
                    values = [];

                    for i = 1:numel(candidate)
                        item = candidate{i};

                        if isnumeric(item) || islogical(item)
                            values = [values; double(item(:))]; %#ok<AGROW>
                        elseif ischar(item) || isstring(item)
                            values = [values; ...
                                          openmebius.application.analysis ...
                                          .SteadyStateOptionsMapper ...
                                          .parseNumericTokens(item)]; %#ok<AGROW>
                        end

                    end

                elseif ischar(candidate) || isstring(candidate)
                    values = openmebius.application.analysis ...
                        .SteadyStateOptionsMapper ...
                        .parseNumericTokens(candidate);
                end

            end

            values = values(isfinite(values) & values > 0);

            if isempty(values)
                values = double(defaultValues(:));
            end

        end % readNumericVector

        function values = parseNumericTokens(candidate)

            tokenPattern = '[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?';
            tokens = regexp(char(candidate), tokenPattern, 'match');
            values = str2double(tokens(:));
            values = values(isfinite(values));

        end % parseNumericTokens

    end % methods (Static, Access = private)

end % classdef
