classdef LabelConfigPresenter < handle
    % LABELCONFIGPRESENTER Maps LabelConfig application outcomes to UI data.

    methods

        function viewModel = presentLaunchOutcome(~, outcome)

            arguments
                ~
                outcome (1, 1) openmebius.application.model ...
                    .LabelConfigurationLaunchOutcome
            end

            if outcome.isSuccess()
                viewModel = openmebius.presentation.model ...
                    .LabelConfigLaunchViewModel( ...
                        IsAvailable = true, ...
                        LabelTable = outcome.State.LabelTable, ...
                        RatioTables = outcome.State.RatioTables);
                return
            end

            if isempty(outcome.Exception)
                notification = openmebius.presentation.notification ...
                    .Notification.error( ...
                        outcome.ErrorMessage, ...
                        Title = "Label configuration error", ...
                        ShowAlert = true);
            else
                notification = openmebius.presentation.notification ...
                    .Notification.fromException( ...
                        outcome.Exception, ...
                        Title = "Label configuration error", ...
                        ShowAlert = true);
            end

            viewModel = openmebius.presentation.model ...
                .LabelConfigLaunchViewModel( ...
                    Notifications = {notification});

        end % presentLaunchOutcome

    end % methods

end % classdef
