classdef ModelPresenter
    % MODELPRESENTER Maps model outcomes to UI values.

    methods

        function viewModel = presentTemplateLoadStarted(~)

            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    SectionStatus = "running", ...
                    ErrorTitle = "Template model load failed");

        end % presentTemplateLoadStarted

        function viewModel = presentTemplateLoadOutcome(obj, outcome)

            arguments
                obj
                outcome (1, 1) openmebius.application.model ...
                    .ModelOperationOutcome
            end

            errorTitle = "Template model load failed";

            if outcome.Status == "finished"
                notifications = obj.infoNotifications( ...
                    [string(outcome.Result.Messages(:)); ...
                     "Constructing EMU network..."]);
                completionNotification = ...
                    openmebius.presentation.notification ...
                    .Notification.info( ...
                        "EMU network was successfully constructed.");
                viewModel = openmebius.presentation.model ...
                    .ModelOperationViewModel( ...
                        SectionStatus = "running", ...
                        CompletionStatus = "finished", ...
                        Result = outcome.Result, ...
                        Notifications = notifications, ...
                        CompletionNotification = completionNotification, ...
                        ErrorTitle = errorTitle);
                return
            end

            message = outcome.ErrorMessage;

            if message == ""
                message = errorTitle + ".";
            end

            notification = openmebius.presentation.notification ...
                .Notification.error( ...
                    message, ...
                    Title = errorTitle, ...
                    ShowAlert = true);
            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    SectionStatus = "error", ...
                    Notifications = {notification}, ...
                    ErrorTitle = errorTitle);

        end % presentTemplateLoadOutcome

        function viewModel = presentModelSaveStarted(~)

            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    SectionStatus = "running", ...
                    ErrorTitle = "Model table save failed");

        end % presentModelSaveStarted

        function viewModel = presentModelSaveOutcome(obj, outcome)

            viewModel = obj.presentEditOutcome( ...
                outcome, ...
                "ModelReport", ...
                "model", ...
                "", ...
                "Model table save failed");

        end % presentModelSaveOutcome

        function viewModel = presentMassSpectrometrySaveStarted(~)

            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    SectionStatus = "running", ...
                    ErrorTitle = "MS table save failed");

        end % presentMassSpectrometrySaveStarted

        function viewModel = presentMassSpectrometrySaveOutcome(obj, outcome)

            viewModel = obj.presentEditOutcome( ...
                outcome, ...
                ["MSReport"; "AtomReport"], ...
                ["ms"; "atom"], ...
                "MS table saved", ...
                "MS table save failed");

        end % presentMassSpectrometrySaveOutcome

        function viewModel = presentTemplateExportUnavailable(~)

            notification = openmebius.presentation.notification ...
                .Notification.error( ...
                    "Model is not loaded. Please load a model before " + ...
                    "exporting a template Excel file.", ...
                    Title = "Template export unavailable");
            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    Notifications = {notification}, ...
                    ErrorTitle = "Template export unavailable");

        end % presentTemplateExportUnavailable

        function viewModel = presentTemplateExportStarted(~)

            notification = openmebius.presentation.notification ...
                .Notification.info( ...
                    "Exporting template Excel file. " + ...
                    "Please select the location to save the file.");
            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    Notifications = {notification}, ...
                    ErrorTitle = "Template export failed");

        end % presentTemplateExportStarted

        function viewModel = presentTemplateExportOutcome(obj, outcome)

            arguments
                obj
                outcome (1, 1) openmebius.application.model ...
                    .ModelOperationOutcome
            end

            errorTitle = "Template export failed";

            if outcome.Status == "finished"
                viewModel = openmebius.presentation.model ...
                    .ModelOperationViewModel( ...
                        Notifications = obj.infoNotifications( ...
                            outcome.Result.Messages), ...
                        ErrorTitle = errorTitle);
                return
            end

            message = outcome.ErrorMessage;

            if message == ""
                message = errorTitle + ".";
            end

            notification = openmebius.presentation.notification ...
                .Notification.error( ...
                    message, ...
                    Title = errorTitle, ...
                    ShowAlert = true);
            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    Notifications = {notification}, ...
                    ErrorTitle = errorTitle);

        end % presentTemplateExportOutcome

    end % methods

    methods (Access = private)

        function notifications = infoNotifications(~, messages)

            messages = string(messages);
            messages = messages(:);
            notifications = cell(numel(messages), 1);

            for messageIndex = 1:numel(messages)
                notifications{messageIndex} = ...
                    openmebius.presentation.notification ...
                    .Notification.info(messages(messageIndex));
            end

        end % infoNotifications

        function viewModel = presentEditOutcome( ...
                ~, outcome, reportNames, targets, successMessage, errorTitle)

            arguments
                ~
                outcome (1, 1) openmebius.application.model ...
                    .ModelOperationOutcome
                reportNames (:, 1) string
                targets (:, 1) string
                successMessage (1, 1) string
                errorTitle (1, 1) string
            end

            if outcome.Status == "error"
                message = outcome.ErrorMessage;

                if message == ""
                    message = errorTitle + ".";
                end

                notification = openmebius.presentation.notification ...
                    .Notification.error( ...
                        message, ...
                        Title = errorTitle, ...
                        ShowAlert = true);
                viewModel = openmebius.presentation.model ...
                    .ModelOperationViewModel( ...
                        SectionStatus = "error", ...
                        Notifications = {notification}, ...
                        ErrorTitle = errorTitle, ...
                        FinishEditCommit = true, ...
                        EditCommitSucceeded = false);
                return
            end

            reports = cell(numel(reportNames), 1);
            styles = repmat( ...
                struct("Target", "", "Rows", zeros(0, 1)), ...
                numel(reportNames), ...
                1);
            isValid = true;

            for reportIndex = 1:numel(reportNames)
                report = outcome.Result.(reportNames(reportIndex));
                reports{reportIndex} = report;
                styles(reportIndex).Target = targets(reportIndex);
                styles(reportIndex).Rows = report.InvalidRows;
                isValid = isValid && report.IsValid;
            end

            if isValid
                sectionStatus = "";
                completionStatus = "finished";

                if successMessage == ""
                    completionNotification = [];
                else
                    completionNotification = ...
                        openmebius.presentation.notification ...
                        .Notification.info(successMessage);
                end
            else
                sectionStatus = "error";
                completionStatus = "";
                completionNotification = [];
            end

            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    SectionStatus = sectionStatus, ...
                    CompletionStatus = completionStatus, ...
                    CompletionNotification = completionNotification, ...
                    ErrorTitle = errorTitle, ...
                    ValidationReports = reports, ...
                    ValidationStyles = styles, ...
                    FinishEditCommit = true, ...
                    EditCommitSucceeded = isValid);

        end % presentEditOutcome

    end % methods (Access = private)

end % classdef
