classdef ModelPresenter
    % MODELPRESENTER Maps model outcomes to UI values.

    methods

        function viewModel = presentTemplateLoadStarted(~)

            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    SectionStatus = "running", ...
                    ErrorTitle = "Template model load failed");

        end % presentTemplateLoadStarted

        function viewModel = presentTemplateLoadOutcome(obj, outcome)

            arguments
                obj
                outcome (1, 1) openmebius.application.model ...
                    .ModelOperationOutcome
            end

            errorTitle = "Template model load failed";

            if outcome.Status == "finished"
                notifications = obj.infoNotifications( ...
                    [string(outcome.Result.Messages(:)); ...
                     "Constructing EMU network..."]);
                completionNotification = ...
                    openmebius.presentation.notification ...
                    .Notification.info( ...
                        "EMU network was successfully constructed.");
                viewModel = openmebius.presentation.model ...
                    .ModelOperationViewModel( ...
                        SectionStatus = "running", ...
                        CompletionStatus = "finished", ...
                        Result = outcome.Result, ...
                        Notifications = notifications, ...
                        CompletionNotification = completionNotification, ...
                        ErrorTitle = errorTitle);
                return
            end

            message = outcome.ErrorMessage;

            if message == ""
                message = errorTitle + ".";
            end

            notification = openmebius.presentation.notification ...
                .Notification.error( ...
                    message, ...
                    Title = errorTitle, ...
                    ShowAlert = true);
            viewModel = openmebius.presentation.model ...
                .ModelOperationViewModel( ...
                    SectionStatus = "error", ...
                    Notifications = {notification}, ...
                    ErrorTitle = errorTitle);

        end % presentTemplateLoadOutcome

    end % methods

    methods (Access = private)

        function notifications = infoNotifications(~, messages)

            messages = string(messages);
            messages = messages(:);
            notifications = cell(numel(messages), 1);

            for messageIndex = 1:numel(messages)
                notifications{messageIndex} = ...
                    openmebius.presentation.notification ...
                    .Notification.info(messages(messageIndex));
            end

        end % infoNotifications

    end % methods (Access = private)

end % classdef
