classdef BatchConfigurationController < handle
    % BATCHCONFIGURATIONCONTROLLER Executes RunConfig commands.

    methods

        function outcome = apply(~, session, requestFactory)

            arguments
                ~
                session (1, 1) openmebius.application.batch ...
                    .BatchConfigurationSession
                requestFactory (1, 1) function_handle
            end

            try
                request = requestFactory();

                if ~isa(request, ...
                        "openmebius.application.batch." + ...
                        "BatchConfigurationApplyRequest")
                    error( ...
                        "OpenMebius2:BatchConfigurationController:" + ...
                        "InvalidRequest", ...
                        "Request factory must return a batch " + ...
                        "configuration apply request.");
                end

                if request.ApplySuggestion
                    suggestionTable = request.SuggestionTable;
                else
                    suggestionTable = [];
                end

                session.apply( ...
                    request.Config, ...
                    request.FragmentSelections, ...
                    suggestionTable);
                outcome = openmebius.application.batch ...
                    .BatchConfigurationApplyOutcome("finished");
            catch exception
                outcome = openmebius.application.batch ...
                    .BatchConfigurationApplyOutcome( ...
                        "error", ...
                        ErrorMessage = string(exception.message), ...
                        Exception = exception);
            end

        end % apply

        function outcome = prepareINSTMFAExperimentSelection(~, session)

            arguments
                ~
                session (1, 1) openmebius.application.batch ...
                    .BatchConfigurationSession
            end

            try
                if ~session.isSingleBatch()
                    error( ...
                        "OpenMebius2:BatchConfigurationController:" + ...
                        "MultipleBatchesForINSTMFA", ...
                        "INST-MFA experiments can only be edited for " + ...
                        "a single batch.");
                end

                request = openmebius.application.batch ...
                    .BatchExperimentSelectionEditorRequest( ...
                        session.experimentNames(), ...
                        "inst-mfa", ...
                        session.BatchIds(1));
                outcome = openmebius.application.batch ...
                    .BatchConfigurationChildOutcome( ...
                        "finished", Result = request);
            catch exception
                outcome = openmebius.application.batch ...
                    .BatchConfigurationChildOutcome( ...
                        "error", ...
                        ErrorMessage = string(exception.message), ...
                        Exception = exception);
            end

        end % prepareINSTMFAExperimentSelection

        function outcome = loadTracerConfiguration( ...
                ~, session, experimentController, position)

            arguments
                ~
                session (1, 1) openmebius.application.batch ...
                    .BatchConfigurationSession
                experimentController (1, 1) openmebius.application ...
                    .experiment.ExperimentEditController
                position (1, 2) double
            end

            outcome = session.loadTracerConfiguration( ...
                experimentController, position);

        end % loadTracerConfiguration

        function outcome = applyTracerConfiguration( ...
                ~, experimentController, position, editorTable)

            arguments
                ~
                experimentController (1, 1) openmebius.application ...
                    .experiment.ExperimentEditController
                position (1, 2) double
                editorTable table
            end

            outcome = experimentController.applyTracerConfiguration( ...
                position, editorTable);

        end % applyTracerConfiguration

    end % methods

end % classdef
