classdef BatchConfigurationLaunchController < handle
    % BATCHCONFIGURATIONLAUNCHCONTROLLER Prepares a RunConfig session.

    methods

        function outcome = prepare( ...
                ~, batchSource, experiments, requestFactory)

            arguments
                ~
                batchSource
                experiments
                requestFactory (1, 1) function_handle
            end

            try
                request = requestFactory();

                if ~isa(request, ...
                        "openmebius.application.batch." + ...
                        "BatchConfigurationLaunchRequest")
                    error( ...
                        "OpenMebius2:" + ...
                        "BatchConfigurationLaunchController:" + ...
                        "InvalidRequest", ...
                        "Request factory must return a batch " + ...
                        "configuration launch request.");
                end

                session = openmebius.application.batch ...
                    .BatchConfigurationSession( ...
                        batchSource, experiments, request.BatchIds);
                outcome = openmebius.application.batch ...
                    .BatchConfigurationLaunchOutcome( ...
                        true, Session = session);
            catch exception
                outcome = openmebius.application.batch ...
                    .BatchConfigurationLaunchOutcome( ...
                        false, ...
                        ErrorMessage = string(exception.message), ...
                        Exception = exception);
            end

        end % prepare

    end % methods

end % classdef
