classdef FluxResultEventMapper
    % FLUXRESULTEVENTMAPPER
    % Maps mutable MFA session state to a validated result event.

    methods (Static)

        function eventData = fromSessionResult(result, options)

            arguments
                result (1, 1) struct
                options.Timestamp (1, 1) datetime = datetime( ...
                    "now", "TimeZone", "UTC")
            end

            id = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                result, "ID", "result");
            fluxVariability = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                result, "fluxVariability", "result");
            upperBounds = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                fluxVariability, "fluxUB", "result.fluxVariability");
            lowerBounds = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                fluxVariability, "fluxLB", "result.fluxVariability");
            rssIndices = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                result, "RSSIdx", "result");

            if isempty(rssIndices)
                error( ...
                    "OpenMebius2:FluxResultEventMapper:EmptyRSSOrder", ...
                "The MFA result does not identify a best iteration.");
            end

            bestIteration = rssIndices(1);

            if ~isnumeric(bestIteration) || ~isscalar(bestIteration) || ...
                    ~isfinite(bestIteration) || bestIteration < 1 || ...
                    fix(bestIteration) ~= bestIteration
                error( ...
                    "OpenMebius2:FluxResultEventMapper:" + ...
                    "InvalidBestIteration", ...
                "The best MFA iteration must be a positive integer.");
            end

            fieldName = "fluxResult" + ...
                string(sprintf("%04d", bestIteration));
            iteration = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                result, fieldName, "result");
            flux = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                iteration, "flux", "result." + fieldName);
            rss = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                iteration, "RSS", "result." + fieldName);
            mdv = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                iteration, "MDV", "result." + fieldName);
            exitFlag = openmebius.presentation.result ...
                .FluxResultEventMapper.requiredField( ...
                iteration, "exitflag", "result." + fieldName);
            eventData = openmebius.presentation.result ...
                .FluxResultEventData( ...
                ID = string(id), ...
                FVAUpperBounds = upperBounds, ...
                FVALowerBounds = lowerBounds, ...
                RSSIndices = rssIndices, ...
                Flux = flux, ...
                RSS = rss, ...
                MDV = mdv, ...
                ExitFlag = exitFlag, ...
                Timestamp = options.Timestamp);

        end

    end

    methods (Static, Access = private)

        function value = requiredField(container, fieldName, path)

            if ~isstruct(container) || ~isscalar(container) || ...
                    ~isfield(container, fieldName)
                error( ...
                    "OpenMebius2:FluxResultEventMapper:MissingField", ...
                    "Required field %s.%s is missing.", ...
                    path, fieldName);
            end

            value = container.(fieldName);

        end

    end

end
