classdef ViewComparisonAction
    % VIEWCOMPARISONACTION Exports the configured comparison plot.

    methods

        function notification = exportFigure(~, sourceAxes, filePath, options)

            arguments
                ~
                sourceAxes
                filePath (1, 1) string
                options.WidthPx (1, 1) double {mustBePositive} = 1600
                options.HeightPx (1, 1) double {mustBePositive} = 1200
                options.DPI (1, 1) double {mustBePositive} = 300
                options.FontSize (1, 1) double {mustBePositive} = 10
                options.FontName (1, 1) string = "Arial"
                options.Format (1, 1) string {mustBeMember( ...
                                                  options.Format, ...
                                                  ["png", "pdf", "svg"])} = "png"
            end

            try
                widthInches = options.WidthPx / options.DPI;
                heightInches = options.HeightPx / options.DPI;
                exportFigure = figure( ...
                    'Visible', 'off', ...
                    'Color', 'none', ...
                    'Units', 'pixels', ...
                    'Position', ...
                    [100 100 options.WidthPx options.HeightPx], ...
                    'PaperUnits', 'inches', ...
                    'PaperPosition', ...
                    [0 0 widthInches heightInches], ...
                    'PaperSize', [widthInches heightInches], ...
                    'PaperPositionMode', 'manual');
                cleanup = onCleanup(@() close(exportFigure));
                exportAxes = copyobj(sourceAxes, exportFigure);
                exportAxes.Units = 'normalized';
                exportAxes.Position = [0.13 0.14 0.83 0.79];
                exportAxes.Color = 'none';
                exportAxes.FontName = options.FontName;
                exportAxes.FontSize = options.FontSize;
                exportAxes.XLabel.FontName = options.FontName;
                exportAxes.XLabel.FontSize = options.FontSize;
                exportAxes.YLabel.FontName = options.FontName;
                exportAxes.YLabel.FontSize = options.FontSize;
                exportAxes.Title.FontName = options.FontName;
                exportAxes.Title.FontSize = options.FontSize;

                legendObject = legend(exportAxes);

                if ~isempty(legendObject) && isvalid(legendObject)
                    legendObject.FontName = options.FontName;
                    legendObject.FontSize = options.FontSize;
                end

                drawnow;

                if options.Format == "png"
                    openmebius.presentation.result ...
                        .ViewComparisonAction.exportTransparentPng( ...
                        exportFigure, filePath, options);
                else
                    exportgraphics( ...
                        exportFigure, ...
                        filePath, ...
                        ContentType = "vector", ...
                        BackgroundColor = "none", ...
                        Width = widthInches, ...
                        Height = heightInches, ...
                        Units = "inches", ...
                        Padding = "figure", ...
                        PreserveAspectRatio = "off");
                end

                notification = openmebius.presentation.notification ...
                    .Notification.success( ...
                    "Comparison plot saved to " + filePath + ".");
            catch exception
                notification = openmebius.presentation.notification ...
                    .Notification.fromException( ...
                    exception, ...
                    Title = "Plot save failed", ...
                    ShowAlert = true);
            end

        end % exportFigure

    end % methods

    methods (Static, Access = private)

        function exportTransparentPng(exportFigure, filePath, options)

            whitePath = string(tempname) + ".png";
            blackPath = string(tempname) + ".png";
            cleanup = onCleanup(@() openmebius.presentation.result ...
                .ViewComparisonAction.deleteTemporaryFiles( ...
                [whitePath; blackPath]));
            commonOptions = { ...
                                 'ContentType', 'image', ...
                                 'Resolution', options.DPI, ...
                                 'Width', options.WidthPx, ...
                                 'Height', options.HeightPx, ...
                                 'Units', 'pixels', ...
                                 'Padding', 'figure', ...
                                 'PreserveAspectRatio', 'off'};
            exportgraphics( ...
                exportFigure, ...
                whitePath, ...
                commonOptions{:}, ...
                BackgroundColor = "white");
            exportgraphics( ...
                exportFigure, ...
                blackPath, ...
                commonOptions{:}, ...
                BackgroundColor = "black");
            whiteImage = double(imread(whitePath)) / 255;
            blackImage = double(imread(blackPath)) / 255;
            alpha = 1 - mean(whiteImage - blackImage, 3);
            alpha = max(0, min(1, alpha));
            denominator = max(alpha, 1/255);
            foreground = zeros(size(blackImage));

            for channel = 1:size(blackImage, 3)
                foreground(:, :, channel) = ...
                    blackImage(:, :, channel) ./ denominator;
            end

            foreground = max(0, min(1, foreground));
            foreground(repmat(alpha < 1/255, 1, 1, 3)) = 0;
            pixelsPerMeter = options.DPI / 0.0254;
            imwrite( ...
                uint8(round(foreground * 255)), ...
                filePath, ...
                'Alpha', alpha, ...
                'ResolutionUnit', 'meter', ...
                'XResolution', pixelsPerMeter, ...
                'YResolution', pixelsPerMeter);

        end % exportTransparentPng

        function deleteTemporaryFiles(paths)

            for path = string(paths)

                if isfile(path)
                    delete(path);
                end

            end

        end % deleteTemporaryFiles

    end % methods (Static, Access = private)

end % classdef
