function synchronizeMlappSource(varargin)
%SYNCHRONIZEMLAPPSOURCE Reject unsafe reverse App Designer synchronization.

error( ...
    "OpenMebius2:Development:ReverseMlappSynchronizationUnsupported", ...
    [ ...
    "Reverse synchronization from *_exported.m to .mlapp is unsafe. " ...
    "It can overwrite App Designer generated code without updating " ...
    "the component model, causing the App to open as modified. " ...
    "Edit and save the .mlapp in App Designer, then run " ...
    "synchronizeExportedSource instead." ...
    ]);

end
