function result = BuildMyApp(options)
    %BUILDMYAPP Validate, compile, and optionally package OpenMebius2.

    arguments
        options.OutputDirectory (1, 1) string = ""
        options.InstallerDirectory (1, 1) string = ""
        options.RunFastTests (1, 1) logical = true
        options.VerifySourceSync (1, 1) logical = true
        options.CreateInstaller (1, 1) logical = true
        options.ValidateOnly (1, 1) logical = false
        options.NotificationDispatcher = []
    end

    tStart = tic;
    sourceDirectory = string(fileparts(mfilename("fullpath")));
    repositoryRoot = string(fileparts(sourceDirectory));
    testsDirectory = fullfile(repositoryRoot, "tests");
    appFile = fullfile(sourceDirectory, "OpenMebius2.mlapp");
    assetFiles = [ ...
                      fullfile(sourceDirectory, "+img", "logo.png"); ...
                      fullfile(sourceDirectory, "+img", "splash.png"); ...
                      fullfile(sourceDirectory, "+img", "sidebar.png")];
    runtimeCompatibilityFiles = resolveRuntimeCompatibilityFiles();

    if options.OutputDirectory == ""
        options.OutputDirectory = fullfile( ...
            repositoryRoot, "build", "openmebius2");
    end

    if options.InstallerDirectory == ""
        options.InstallerDirectory = fullfile(repositoryRoot, "installer");
    end

    systemInfo = System();
    version = systemInfo.getCurrentVersion();
    plan = struct( ...
        RepositoryRoot = repositoryRoot, ...
        SourceDirectory = sourceDirectory, ...
        AppFile = appFile, ...
        AssetFiles = assetFiles, ...
        OutputDirectory = options.OutputDirectory, ...
        InstallerDirectory = options.InstallerDirectory, ...
        Version = version, ...
        InstallerName = systemInfo.getFileNameForBinary(version), ...
        RuntimeCompatibilityFiles = runtimeCompatibilityFiles);

    assertRequiredFiles([appFile; assetFiles]);
    addpath(char(sourceDirectory));
    notificationDispatcher = options.NotificationDispatcher;

    if isempty(notificationDispatcher)
        policy = openmebius.infrastructure.notification.RoutingPolicy( ...
            Mode = "cli");
        notificationDispatcher = openmebius.infrastructure.notification ...
            .NotificationDispatcher(Policy = policy);
        notificationDispatcher.addSink( ...
            openmebius.infrastructure.notification.ConsoleSink());
    end

    notificationEmitter = openmebius.application.notification ...
        .NotificationEmitter( ...
        Publisher = notificationDispatcher.reporter(), ...
        Source = "BuildMyApp");

    if options.RunFastTests
        addpath(char(testsDirectory));
        notificationEmitter.report( ...
            "info", ...
            "Running the fast test profile before build...", ...
            Code = "build.tests.started");
        runFastTests();
    elseif options.VerifySourceSync
        addpath(char(testsDirectory));
        notificationEmitter.report( ...
            "info", ...
            "Verifying App Designer source synchronization...", ...
            Code = "build.source-sync.started");
        syncResults = runtests(fullfile( ...
            testsDirectory, "OpenMebius2SourceSyncTest.m"));
        assertSuccess(syncResults);
    end

    result = struct( ...
        Plan = plan, ...
        BuildResults = [], ...
        InstallerCreated = false);

    if options.ValidateOnly
        notificationEmitter.report( ...
            "success", ...
            "Build validation completed for OpenMebius2 " + version + ".", ...
            Code = "build.validation.completed");
        return
    end

    assertCompilerAvailable();
    notificationEmitter.report( ...
        "info", ...
        "Building OpenMebius2 " + version + "...", ...
        Code = "build.started");

    buildOptions = compiler.build.StandaloneApplicationOptions( ...
        appFile, ...
        ExecutableName = "openmebius2", ...
        ExecutableIcon = assetFiles(1), ...
        ExecutableSplashScreen = assetFiles(2), ...
        OutputDir = options.OutputDirectory);

    if strcmp(systemInfo.getOperatingSystem(), "Windows")
        buildResults = ...
            compiler.build.standaloneWindowsApplication(buildOptions);
    else
        buildResults = compiler.build.standaloneApplication(buildOptions);
    end

    result.BuildResults = buildResults;

    if options.CreateInstaller
        installerOptions = compiler.package.InstallerOptions( ...
            buildResults, ...
            ApplicationName = "OpenMebius2", ...
            AuthorName = "Tatsumi Imada", ...
            AuthorEmail = "tatsumi.imada@ist.osaka-u.ac.jp", ...
            AuthorCompany = "The University of Osaka", ...
            InstallerName = plan.InstallerName, ...
            Version = version, ...
            Summary = "GUI application for 13C-metabolic flux analysis.", ...
            Description = "GUI application for 13C-metabolic flux analysis.", ...
            InstallerIcon = assetFiles(1), ...
            InstallerSplash = assetFiles(2), ...
            InstallerLogo = assetFiles(3), ...
            OutputDir = options.InstallerDirectory);

        if ~isempty(plan.RuntimeCompatibilityFiles)
            installerOptions.AdditionalFiles = ...
                plan.RuntimeCompatibilityFiles;
        end

        notificationEmitter.report( ...
            "info", ...
            "Creating installer: " + plan.InstallerName, ...
            Code = "build.installer.started");
        compiler.package.installer(buildResults, Options = installerOptions);
        result.InstallerCreated = true;
    end

    elapsedTime = string(seconds(toc(tStart)), "hh:mm:ss");
    notificationEmitter.report( ...
        "success", ...
        "Build completed in " + elapsedTime + ".", ...
        Code = "build.completed");

end

function files = resolveRuntimeCompatibilityFiles()

    files = strings(0, 1);

    if ~ispc
        return
    end

    % R2026a minimal Runtime installers can include the agent proxy credential
    % client without its native proxy credential API dependency. Installing the
    % dependency beside the application lets the Windows loader resolve it
    % before the agent client is initialized.
    proxyCredentialAPI = fullfile( ...
        matlabroot, "bin", "win64", "libmwflproxycredentialapi.dll");

    if isfile(proxyCredentialAPI)
        files(end + 1, 1) = proxyCredentialAPI;
    end

end

function assertRequiredFiles(files)

    missingFiles = files(~isfile(files));

    if ~isempty(missingFiles)
        error( ...
            "OpenMebius2:Build:MissingInput", ...
            "Required build input is missing: %s", ...
            strjoin(missingFiles, ", "));
    end

end

function assertCompilerAvailable()

    if isempty(which("compiler.build.StandaloneApplicationOptions"))
        error( ...
            "OpenMebius2:Build:CompilerUnavailable", ...
        "MATLAB Compiler is required to build the standalone application.");
    end

end
