function BuildMyApp
    appFile = fullfile(pwd, "OpenMebius2.mlapp");

    exeIcon = fullfile(pwd, "+img", "logo.png");
    exeSplash = fullfile(pwd, "+img", "splash.png");

    system = System();
    latestTag = system.getLatestTag();

    outDir = fullfile(pwd, "../build", "openmebius2");

    buildOpts = compiler.build.StandaloneApplicationOptions( ...
        appFile, ...
        "ExecutableName", "openmebius2", ...
        "ExecutableIcon", exeIcon, ...
        "ExecutableSplashScreen", exeSplash, ...
        "OutputDir", outDir ...
    );

    if strcmp(system.getOperatingSystem(), "Windows")
        buildResults = compiler.build.standaloneWindowsApplication(buildOpts);
    else
        buildResults = compiler.build.standaloneApplication(buildOpts);
    end

    installerIcon = fullfile(pwd, "+img", "logo.png");
    installerSplash = fullfile(pwd, "+img", "splash.png");
    installerLogo = fullfile(pwd, "+img", "sidebar.png");

    filename = system.getFileNameForBinary(latestTag);

    opts = compiler.package.InstallerOptions(buildResults, ...
        "ApplicationName", "OpenMebius2", ...
        "AuthorName", "Tatsumi Imada", ...
        "AuthorEmail", "tatsumi.imada@ist.osaka-u.ac.jp", ...
        "AuthorCompany", "The University of Osaka", ...
        "InstallerName", filename, ...
        "Summary", "GUI application for 13C-metabolic flux analysis.", ...
        "Description", "GUI application for 13C-metabolic flux analysis.", ...
        "InstallerIcon", installerIcon, ...
        "InstallerSplash", installerSplash, ...
        "InstallerLogo", installerLogo, ...
        "OutputDir", fullfile(pwd, "../installer"));

    disp("Creating installer...");

    compiler.package.installer(buildResults, "Options", opts);

    disp("Build and packaging completed.");

    imageName = system.getDockerImageName();

    if strcmp(system.getOperatingSystem(), "Linux")
        opts = compiler.package.DockerOptions(buildResults, ...
            'ImageName', imageName, ...
            'DockerContext', fullfile(pwd, '../docker') ...
        );
        compiler.package.docker(buildResults, 'Options', opts)
    end

end
