function result = BuildMyApp(options)
%BUILDMYAPP Validate, compile, and optionally package OpenMebius2.

arguments
    options.OutputDirectory (1, 1) string = ""
    options.InstallerDirectory (1, 1) string = ""
    options.RunFastTests (1, 1) logical = true
    options.VerifySourceSync (1, 1) logical = true
    options.CreateInstaller (1, 1) logical = true
    options.ValidateOnly (1, 1) logical = false
end

import openmebius.presentation.notification.Notification

tStart = tic;
sourceDirectory = string(fileparts(mfilename("fullpath")));
repositoryRoot = string(fileparts(sourceDirectory));
testsDirectory = fullfile(repositoryRoot, "tests");
appFile = fullfile(sourceDirectory, "OpenMebius2.mlapp");
assetFiles = [ ...
    fullfile(sourceDirectory, "+img", "logo.png"); ...
    fullfile(sourceDirectory, "+img", "splash.png"); ...
    fullfile(sourceDirectory, "+img", "sidebar.png")];

if options.OutputDirectory == ""
    options.OutputDirectory = fullfile( ...
        repositoryRoot, "build", "openmebius2");
end

if options.InstallerDirectory == ""
    options.InstallerDirectory = fullfile(repositoryRoot, "installer");
end

systemInfo = System();
version = systemInfo.getCurrentVersion();
plan = struct( ...
    RepositoryRoot = repositoryRoot, ...
    SourceDirectory = sourceDirectory, ...
    AppFile = appFile, ...
    AssetFiles = assetFiles, ...
    OutputDirectory = options.OutputDirectory, ...
    InstallerDirectory = options.InstallerDirectory, ...
    Version = version, ...
    InstallerName = systemInfo.getFileNameForBinary(version));

assertRequiredFiles([appFile; assetFiles]);
addpath(char(sourceDirectory));

if options.RunFastTests
    addpath(char(testsDirectory));
    logBuild(Notification.info( ...
        "Running the fast test profile before build..."));
    runFastTests();
elseif options.VerifySourceSync
    addpath(char(testsDirectory));
    logBuild(Notification.info( ...
        "Verifying App Designer source synchronization..."));
    syncResults = runtests(fullfile( ...
        testsDirectory, "OpenMebius2SourceSyncTest.m"));
    assertSuccess(syncResults);
end

result = struct( ...
    Plan = plan, ...
    BuildResults = [], ...
    InstallerCreated = false);

if options.ValidateOnly
    logBuild(Notification.info( ...
        "Build validation completed for OpenMebius2 " + version + "."));
    return
end

assertCompilerAvailable();
logBuild(Notification.info( ...
    "Building OpenMebius2 " + version + "..."));

buildOptions = compiler.build.StandaloneApplicationOptions( ...
    appFile, ...
    ExecutableName = "openmebius2", ...
    ExecutableIcon = assetFiles(1), ...
    ExecutableSplashScreen = assetFiles(2), ...
    OutputDir = options.OutputDirectory);

if strcmp(systemInfo.getOperatingSystem(), "Windows")
    buildResults = ...
        compiler.build.standaloneWindowsApplication(buildOptions);
else
    buildResults = compiler.build.standaloneApplication(buildOptions);
end

result.BuildResults = buildResults;

if options.CreateInstaller
    installerOptions = compiler.package.InstallerOptions( ...
        buildResults, ...
        ApplicationName = "OpenMebius2", ...
        AuthorName = "Tatsumi Imada", ...
        AuthorEmail = "tatsumi.imada@ist.osaka-u.ac.jp", ...
        AuthorCompany = "The University of Osaka", ...
        InstallerName = plan.InstallerName, ...
        Summary = "GUI application for 13C-metabolic flux analysis.", ...
        Description = "GUI application for 13C-metabolic flux analysis.", ...
        InstallerIcon = assetFiles(1), ...
        InstallerSplash = assetFiles(2), ...
        InstallerLogo = assetFiles(3), ...
        OutputDir = options.InstallerDirectory);
    logBuild(Notification.info( ...
        "Creating installer: " + plan.InstallerName));
    compiler.package.installer(buildResults, Options = installerOptions);
    result.InstallerCreated = true;
end

elapsedTime = string(seconds(toc(tStart)), "hh:mm:ss");
logBuild(Notification.info( ...
    "Build completed in " + elapsedTime + "."));

end

function assertRequiredFiles(files)

missingFiles = files(~isfile(files));

if ~isempty(missingFiles)
    error( ...
        "OpenMebius2:Build:MissingInput", ...
        "Required build input is missing: %s", ...
        strjoin(missingFiles, ", "));
end

end

function assertCompilerAvailable()

if isempty(which("compiler.build.StandaloneApplicationOptions"))
    error( ...
        "OpenMebius2:Build:CompilerUnavailable", ...
        "MATLAB Compiler is required to build the standalone application.");
end

end

function logBuild(notification)

disp(notification.toLogText());

end
