dirModel = "../../model";

directory = dispDirList( ...
    "metabolic model", ...
    "model", ...
    dirModel, ...
    openmebius.infrastructure.filesystem.DirectoryStore.dirList(dirModel));

Model = ReportResult(fullfile(dirModel, directory ,'results'));
