function generationResult = generateReport( ...
        resultInput, model, experiments, result, options)
% GENERATEREPORT Generates the standard OpenMebius2 analysis report.

    arguments
        resultInput
        model
        experiments
        result
        options.OpenReport (1, 1) logical = true
    end

    resultLocation = ...
        openmebius.domain.result.ResultLocation.fromInput(resultInput);
    service = openmebius.application.report.ReportGenerationService();
    generationResult = service.generate( ...
        resultLocation, ...
        model, ...
        experiments, ...
        result, ...
        IsDeployed = isdeployed, ...
        OpenReport = options.OpenReport);

end % generateReport
