classdef IOExps < openmebius.application.experiment.ExperimentWorkspace
    % IOEXPS Compatibility adapter for the legacy experiment API.

    methods

        function obj = IOExps(experimentInput, modelInput, options)

            arguments
                experimentInput
                modelInput = []
                options.ExperimentRepository = ...
                    openmebius.infrastructure.experiment ...
                    .ExperimentRepository()
                options.ComparisonBuilder = openmebius.domain.experiment ...
                    .ExperimentComparisonBuilder()
                options.EditMapper = openmebius.domain.experiment ...
                    .ExperimentEditMapper()
                options.EditValidator = openmebius.domain.experiment ...
                    .ExperimentEditValidator()
                options.TableAssembler = openmebius.domain.experiment ...
                    .ExperimentTableAssembler()
                options.AllowEmpty (1, 1) logical = false
            end

            obj@openmebius.application.experiment.ExperimentWorkspace( ...
                experimentInput, ...
                modelInput, ...
                ExperimentRepository = options.ExperimentRepository, ...
                ComparisonBuilder = options.ComparisonBuilder, ...
                EditMapper = options.EditMapper, ...
                EditValidator = options.EditValidator, ...
                TableAssembler = options.TableAssembler, ...
                AllowEmpty = options.AllowEmpty);

        end

    end

end
