dirModel = "../model";

directory = dispDirList( ...
    "metabolic model", ...
    "model", ...
    dirModel, ...
    openmebius.infrastructure.filesystem.DirectoryStore.dirList(dirModel));

Model = EMUModel(fullfile(dirModel, directory));
lh = addlistener(Model, 'generalMsg', ...
    @(src, event) fprintf('%s\n', event.toLogText()));
