dirModel = "../model";

directory = dispDirList( ...
    "metabolic model", ...
    "model", ...
    dirModel, ...
    openmebius.infrastructure.filesystem.DirectoryStore.dirList(dirModel));

location = openmebius.domain.model.ModelLocation.fromDirectory( ...
    fullfile(dirModel, directory));
Model = openmebius.infrastructure.model.ModelRepository().load(location);
lh = addlistener(Model, 'generalMsg', ...
    @(src, event) fprintf('%s\n', event.toLogText()));
