clear;
clc;

tStart = datetime("now");

[testResults, coverageResults] = runtests([ ...
                                               "OpenMebius2Test.m", ...
                                               "OpenMebius2IntegratedTest.m", ...
                                               "../tests/AnalysisProvenanceBuilderTest.m", ...
                                               "../tests/BatchExecutionCoordinatorTest.m", ...
                                               "../tests/BatchExecutionIntegrationTest.m", ...
                                               "../tests/BatchPreparationServiceTest.m", ...
                                               "../tests/BatchRunServiceTest.m", ...
                                               "../tests/BatchConfigTest.m", ...
                                               "../tests/BatchConfigEditorTest.m", ...
                                               "../tests/BatchCollectionTest.m", ...
                                               "../tests/BatchJsonRepositoryTest.m", ...
                                               "../tests/ExperimentCalculationServiceTest.m", ...
                                               "../tests/ExperimentCollectionTest.m", ...
                                               "../tests/ExperimentComparisonBuilderTest.m", ...
                                               "../tests/ExperimentDerivedDataRestorerTest.m", ...
                                               "../tests/ExperimentEditMapperTest.m", ...
                                               "../tests/ExperimentEditServiceTest.m", ...
                                               "../tests/ExperimentEditValidatorTest.m", ...
                                               "../tests/ExperimentImportServiceTest.m", ...
                                               "../tests/ExperimentMDVCalculationInputTest.m", ...
                                               "../tests/ExperimentMDVCalculatorTest.m", ...
                                               "../tests/ExperimentTableAssemblerTest.m", ...
                                               "../tests/ExperimentValidationReportTest.m", ...
                                               "../tests/ExperimentWorkbookDataTest.m", ...
                                               "../tests/ExperimentWorkbookStoreTest.m", ...
                                               "../tests/MSFragmentTableMapperTest.m", ...
                                               "../tests/MSViewPresenterTest.m", ...
                                               "../tests/MFAConstraintBuilderTest.m", ...
                                               "../tests/MFAConstraintMetadataTest.m", ...
                                               "../tests/MFAInputValidatorTest.m", ...
                                               "../tests/MFAExperimentalDataBuilderTest.m", ...
                                               "../tests/MFAInputPreparationWorkflowTest.m", ...
                                               "../tests/MFAInputPreparationSettingsMapperTest.m", ...
                                               "../tests/MFAAnalysisSettingsMapperTest.m", ...
                                               "../tests/FluxAnalysisRunSettingsMapperTest.m", ...
                                               "../tests/MFAAnalysisControllerTest.m", ...
                                               "../tests/MFAAnalysisControllerFactoryTest.m", ...
                                               "../tests/ConfidenceIntervalSettingsMapperTest.m", ...
                                               "../tests/MFAConfidenceIntervalApplicationWorkflowTest.m", ...
                                               "../tests/MonteCarloConfidenceIntervalSolverTest.m", ...
                                               "../tests/NextLabelExperimentSettingsMapperTest.m", ...
                                               "../tests/NextFluxExperimentWorkflowTest.m", ...
                                               "../tests/MFAInitialFluxApplicationWorkflowTest.m", ...
                                               "../tests/MFAIterationApplicationWorkflowTest.m", ...
                                               "../tests/InitialFluxWorkflowContractTest.m", ...
                                               "../tests/InitialFluxSettingsTest.m", ...
                                               "../tests/InitialFluxSettingsMapperTest.m", ...
                                               "../tests/InstationaryInputFactoryTest.m", ...
                                               "../tests/InstationaryInputSpecificationMapperTest.m", ...
                                               "../tests/MFAIterationServiceTest.m", ...
                                               "../tests/MFAIterationReporterTest.m", ...
                                               "../tests/MFAIterationSettingsTest.m", ...
                                               "../tests/MFAIterationSettingsMapperTest.m", ...
                                               "../tests/MFAObjectiveFactoryTest.m", ...
                                               "../tests/MFAFluxDistributionWorkflowTest.m", ...
                                               "../tests/SteadyStateOptionsTest.m", ...
                                               "../tests/SteadyStateOptionsMapperTest.m", ...
                                               "../tests/FluxBoundNormalizerTest.m", ...
                                               "../tests/FluxVariabilitySolverTest.m", ...
                                               "../tests/FluxVariabilityWorkflowTest.m", ...
                                               "../tests/MFAResultCheckpointWriterTest.m", ...
                                               "../tests/MFAResultCoordinatorTest.m", ...
                                               "../tests/NextLabelResultCheckpointWriterTest.m", ...
                                               "../tests/AnalysisWorkflowRefactorTest.m", ...
                                               "../tests/ModelRepositoryTest.m", ...
                                               "../tests/RunConfigMapperTest.m", ...
                                               "../tests/ResultArtifactRepositoryTest.m", ...
                                           ], ...
    ReportCoverageFor = pwd ...
);

tStop = datetime("now");
deltaTime = tStop - tStart;
web = Web(getenv("SLACK_WEBHOOK"));
web.sendTestFinishNotification(deltaTime);

testResultsTable = table(testResults);
disp(testResultsTable);

isPassed = testResultsTable.Passed;
numFailed = sum(~isPassed);
idx = find(~isPassed);

for i = 1:numFailed

    testResult = testResults(idx(i));
    disp(testResult);
    testResult.Details.DiagnosticRecord.Report

end
