clear;
clc;

tStart = datetime("now");

[testResults, coverageResults] = runtests([ ...
                                               "OpenMebius2Test.m", ...
                                               "OpenMebius2IntegratedTest.m", ...
                                               "../tests/BatchConfigTest.m", ...
                                               "../tests/BatchJsonRepositoryTest.m", ...
                                               "../tests/ExperimentCalculationServiceTest.m", ...
                                               "../tests/ExperimentCollectionTest.m", ...
                                               "../tests/ExperimentDerivedDataRestorerTest.m", ...
                                               "../tests/ExperimentEditServiceTest.m", ...
                                               "../tests/ExperimentImportServiceTest.m", ...
                                               "../tests/ExperimentMDVCalculationInputTest.m", ...
                                               "../tests/ExperimentMDVCalculatorTest.m", ...
                                               "../tests/ExperimentTableAssemblerTest.m", ...
                                               "../tests/ExperimentValidationReportTest.m", ...
                                               "../tests/ExperimentWorkbookDataTest.m", ...
                                               "../tests/ExperimentWorkbookStoreTest.m", ...
                                               "../tests/MSFragmentTableMapperTest.m", ...
                                               "../tests/RunConfigMapperTest.m", ...
                                           ], ...
    ReportCoverageFor = pwd ...
);

tStop = datetime("now");
deltaTime = tStop - tStart;
web = Web(getenv("SLACK_WEBHOOK"));
web.sendTestFinishNotification(deltaTime);

testResultsTable = table(testResults);
disp(testResultsTable);

isPassed = testResultsTable.Passed;
numFailed = sum(~isPassed);
idx = find(~isPassed);

for i = 1:numFailed

    testResult = testResults(idx(i));
    disp(testResult);
    testResult.Details.DiagnosticRecord.Report

end
