clear;
clc;

tStart = datetime("now");

[testResults, coverageResults] = runtests([ ...
                                               "OpenMebius2Test.m", ...
                                               "OpenMebius2IntegratedTest.m", ...
                                               "../tests/AnalysisProvenanceBuilderTest.m", ...
                                               "../tests/BatchExecutionCoordinatorTest.m", ...
                                               "../tests/BatchExecutionIntegrationTest.m", ...
                                               "../tests/BatchPreparationServiceTest.m", ...
                                               "../tests/BatchRunServiceTest.m", ...
                                               "../tests/BatchConfigTest.m", ...
                                               "../tests/BatchConfigEditorTest.m", ...
                                               "../tests/BatchCollectionTest.m", ...
                                               "../tests/BatchJsonRepositoryTest.m", ...
                                               "../tests/ExperimentCalculationServiceTest.m", ...
                                               "../tests/ExperimentCollectionTest.m", ...
                                               "../tests/ExperimentComparisonBuilderTest.m", ...
                                               "../tests/ExperimentDerivedDataRestorerTest.m", ...
                                               "../tests/ExperimentEditMapperTest.m", ...
                                               "../tests/ExperimentEditServiceTest.m", ...
                                               "../tests/ExperimentEditValidatorTest.m", ...
                                               "../tests/ExperimentImportServiceTest.m", ...
                                               "../tests/ExperimentMDVCalculationInputTest.m", ...
                                               "../tests/ExperimentMDVCalculatorTest.m", ...
                                               "../tests/ExperimentTableAssemblerTest.m", ...
                                               "../tests/ExperimentValidationReportTest.m", ...
                                               "../tests/ExperimentWorkbookDataTest.m", ...
                                               "../tests/ExperimentWorkbookStoreTest.m", ...
                                               "../tests/MSFragmentTableMapperTest.m", ...
                                               "../tests/MSViewPresenterTest.m", ...
                                               "../tests/MFAConstraintBuilderTest.m", ...
                                               "../tests/MFAConstraintMetadataTest.m", ...
                                               "../tests/MFAInputValidatorTest.m", ...
                                               "../tests/InitialFluxWorkflowContractTest.m", ...
                                               "../tests/MFAIterationServiceTest.m", ...
                                               "../tests/FluxBoundNormalizerTest.m", ...
                                               "../tests/FluxVariabilitySolverTest.m", ...
                                               "../tests/FluxVariabilityWorkflowTest.m", ...
                                               "../tests/ModelRepositoryTest.m", ...
                                               "../tests/RunConfigMapperTest.m", ...
                                               "../tests/ResultArtifactRepositoryTest.m", ...
                                           ], ...
    ReportCoverageFor = pwd ...
);

tStop = datetime("now");
deltaTime = tStop - tStart;
web = Web(getenv("SLACK_WEBHOOK"));
web.sendTestFinishNotification(deltaTime);

testResultsTable = table(testResults);
disp(testResultsTable);

isPassed = testResultsTable.Passed;
numFailed = sum(~isPassed);
idx = find(~isPassed);

for i = 1:numFailed

    testResult = testResults(idx(i));
    disp(testResult);
    testResult.Details.DiagnosticRecord.Report

end
