classdef Web < handle

    properties (Access = private)

        WebHookURL = "";

    end % properties (Access = private)

    methods

        function obj = Web(url)

            obj.WebHookURL = url;

        end % function obj = Web(webhookURL)

    end % methods

    methods (Access = public)

        function sendSlackNotification(obj, message)

            if isempty(obj.WebHookURL)
                return;
            end

            payload = struct();
            payload.text = message;

            options = weboptions("MediaType", "application/json");

            try
                webwrite(obj.WebHookURL, payload, options);
            catch
                % Do nothing
            end

        end % function sendSlackNotification(obj, message)

        function sendTestFinishNotification(obj, deltaTime)

            if isempty(obj.WebHookURL)
                return;
            end

            payload = obj.getTestFinishMessage(deltaTime);

            options = weboptions("MediaType", "application/json");

            try
                webwrite(obj.WebHookURL, payload, options);
            catch
                % Do nothing
            end

        end % function sendTestFinishNotification(obj, deltaTime)

    end % methods (Access = public)

    methods (Access = private)

        function payload = getTestFinishMessage(~, deltaTime)

            nowText = "*Time:*" + newline + string(deltaTime);
            system = System();
            osinfo = system.getOperatingSystem();
            cpuInfo = system.getCPUInfo();
            ramInfo = system.getRAMInfo();
            osText = "*OS:*" + newline + osinfo;
            cpuText = "*CPU:*" + newline + cpuInfo;
            ramText = "*RAM:*" + newline + ramInfo;

            payload = struct( ...
                "attachments", {{
                struct( ...
                    "color", "#36a64f", ...
                    "blocks", {{ ...
                    struct( ...
                    "type", "section", ...
                    "text", struct( ...
                    "type", "mrkdwn", ...
                    "text", "OpenMebius2 unit test is now finished." ...
                ) ...
                ), ...
                    struct( ...
                    "type", "section", ...
                    "fields", {{ ...
                    struct( ...
                    "type", "mrkdwn", ...
                    "text", "*Type:*" + newline + "Computer (laptop)" ...
                ), ...
                    struct( ...
                    "type", "mrkdwn", ...
                    "text", nowText ...
                ), ...
                    struct( ...
                    "type", "mrkdwn", ...
                    "text", osText ...
                ), ...
                    struct( ...
                    "type", "mrkdwn", ...
                    "text", cpuText ...
                ), ...
                    struct( ...
                    "type", "mrkdwn", ...
                    "text", ramText ...
                ) ...
                }} ...
            ) ...
            }} ...
            )}});

            payload.text = "OpenMebius2 Unit Test Finished";

        end % function payload = getTestFinishMessage(~, deltaTime)

    end % methods (Access = private)

end % classdef Web < handle
