classdef HtmlReportStyle
    % HTMLREPORTSTYLE Provides the shared visual language for HTML reports.

    methods (Static)

        function markup = headMarkup()

            lines = { ...
                '<meta name="viewport" content="width=device-width, initial-scale=1">'; ...
                '<style id="openmebius-report-style">'; ...
                ':root {'; ...
                '  --om-bg: #f4f6f8;'; ...
                '  --om-surface: #ffffff;'; ...
                '  --om-text: #1f2933;'; ...
                '  --om-muted: #607080;'; ...
                '  --om-border: #d7dee5;'; ...
                '  --om-border-strong: #b8c3cc;'; ...
                '  --om-accent: #087f72;'; ...
                '  --om-accent-soft: #e7f4f1;'; ...
                '  --om-heading: #24313d;'; ...
                '  --om-table-head: #2f3b45;'; ...
                '  --om-row-alt: #f7f9fa;'; ...
                '}'; ...
                'html {'; ...
                '  background: var(--om-bg);'; ...
                '  color-scheme: light;'; ...
                '}'; ...
                'body {'; ...
                '  box-sizing: border-box;'; ...
                '  max-width: 1440px;'; ...
                '  margin: 0 auto;'; ...
                '  padding: 48px 56px 96px;'; ...
                '  background: var(--om-surface);'; ...
                '  color: var(--om-text);'; ...
                '  font-family: "Segoe UI", "Noto Sans", Arial, sans-serif;'; ...
                '  font-size: 14px;'; ...
                '  line-height: 1.55;'; ...
                '  letter-spacing: 0;'; ...
                '  box-shadow: 0 0 0 1px rgba(31, 41, 51, 0.04);'; ...
                '}'; ...
                'p.TitlePageTitle {'; ...
                '  margin: 64px 0 0;'; ...
                '  padding: 40px 0 14px;'; ...
                '  border-top: 6px solid var(--om-accent);'; ...
                '  color: var(--om-heading);'; ...
                '  font-family: "Segoe UI", "Noto Sans", Arial, sans-serif;'; ...
                '  font-size: 34px;'; ...
                '  font-weight: 700;'; ...
                '  line-height: 1.15;'; ...
                '  text-align: left;'; ...
                '  letter-spacing: 0;'; ...
                '}'; ...
                'p.TitlePageSubtitle {'; ...
                '  margin: 0;'; ...
                '  color: var(--om-muted);'; ...
                '  font-family: "Cascadia Mono", Consolas, monospace;'; ...
                '  font-size: 13px;'; ...
                '  font-weight: 400;'; ...
                '  line-height: 1.5;'; ...
                '  text-align: left;'; ...
                '  letter-spacing: 0;'; ...
                '}'; ...
                'p.TitlePageAuthor, p.TitlePagePubDate {'; ...
                '  margin: 18px 0 0;'; ...
                '  color: var(--om-text);'; ...
                '  font-size: 13px;'; ...
                '  font-weight: 600;'; ...
                '  text-align: left;'; ...
                '  letter-spacing: 0;'; ...
                '}'; ...
                'p.TitlePagePubDate {'; ...
                '  margin-top: 2px;'; ...
                '  color: var(--om-muted);'; ...
                '  font-weight: 400;'; ...
                '}'; ...
                'p.TableOfContentsTitle {'; ...
                '  margin: 64px 0 0;'; ...
                '  padding: 18px 22px 14px;'; ...
                '  border: 1px solid var(--om-border);'; ...
                '  border-bottom: 0;'; ...
                '  border-left: 4px solid var(--om-accent);'; ...
                '  border-radius: 6px 6px 0 0;'; ...
                '  background: var(--om-surface);'; ...
                '  color: var(--om-heading);'; ...
                '  font-size: 18px;'; ...
                '  font-weight: 700;'; ...
                '  letter-spacing: 0;'; ...
                '}'; ...
                'toc {'; ...
                '  display: block;'; ...
                '  margin: 0 0 64px;'; ...
                '  padding: 8px 22px 18px;'; ...
                '  border: 1px solid var(--om-border);'; ...
                '  border-top: 0;'; ...
                '  border-left: 4px solid var(--om-accent);'; ...
                '  border-radius: 0 0 6px 6px;'; ...
                '  background: var(--om-surface);'; ...
                '}'; ...
                'a.TOCItemTitle {'; ...
                '  color: #086a61;'; ...
                '  font-family: "Segoe UI", "Noto Sans", Arial, sans-serif;'; ...
                '  font-size: 13px;'; ...
                '  font-weight: 600;'; ...
                '  text-decoration: none;'; ...
                '  letter-spacing: 0;'; ...
                '}'; ...
                'a.TOCItemTitle:hover {'; ...
                '  text-decoration: underline;'; ...
                '}'; ...
                'span.TOCHandle {'; ...
                '  border-color: var(--om-border-strong);'; ...
                '  border-radius: 2px;'; ...
                '}'; ...
                'h1.SectionTitle1, h2.SectionTitle2,'; ...
                'h3.SectionTitle3, h4.SectionTitle4 {'; ...
                '  font-family: "Segoe UI", "Noto Sans", Arial, sans-serif;'; ...
                '  font-style: normal;'; ...
                '  white-space: normal;'; ...
                '  letter-spacing: 0;'; ...
                '}'; ...
                'h1.SectionTitle1 {'; ...
                '  margin: 72px 0 24px;'; ...
                '  padding: 0 0 12px;'; ...
                '  border-bottom: 2px solid var(--om-accent);'; ...
                '  color: var(--om-heading);'; ...
                '  font-size: 26px;'; ...
                '  font-weight: 700;'; ...
                '  line-height: 1.25;'; ...
                '}'; ...
                'h1.SectionTitle1 > span:first-child {'; ...
                '  display: none;'; ...
                '}'; ...
                'h2.SectionTitle2 {'; ...
                '  margin: 42px 0 14px;'; ...
                '  padding-left: 12px;'; ...
                '  border-left: 4px solid var(--om-accent);'; ...
                '  color: var(--om-heading);'; ...
                '  font-size: 20px;'; ...
                '  font-weight: 700;'; ...
                '  line-height: 1.35;'; ...
                '}'; ...
                'h3.SectionTitle3 {'; ...
                '  margin: 30px 0 12px;'; ...
                '  color: #34444f;'; ...
                '  font-size: 16px;'; ...
                '  font-weight: 700;'; ...
                '  line-height: 1.4;'; ...
                '}'; ...
                'h4.SectionTitle4 {'; ...
                '  margin: 24px 0 10px;'; ...
                '  color: #4d5d68;'; ...
                '  font-size: 14px;'; ...
                '  font-weight: 700;'; ...
                '  line-height: 1.4;'; ...
                '}'; ...
                'table.openmebius-report-table {'; ...
                '  display: block;'; ...
                '  width: max-content;'; ...
                '  max-width: 100%;'; ...
                '  margin: 12px 0 30px;'; ...
                '  overflow-x: auto;'; ...
                '  border: 1px solid var(--om-border);'; ...
                '  border-collapse: separate;'; ...
                '  border-spacing: 0;'; ...
                '  border-radius: 6px;'; ...
                '  background: var(--om-surface);'; ...
                '  color: var(--om-text);'; ...
                '  font-family: "Segoe UI", "Noto Sans", Arial, sans-serif;'; ...
                '  font-size: 13px;'; ...
                '  font-variant-numeric: tabular-nums;'; ...
                '  line-height: 1.45;'; ...
                '  text-align: left;'; ...
                '  letter-spacing: 0;'; ...
                '}'; ...
                'table.openmebius-report-table th {'; ...
                '  padding: 10px 12px;'; ...
                '  border: 0;'; ...
                '  border-right: 1px solid #4d5a64;'; ...
                '  background: var(--om-table-head);'; ...
                '  color: #ffffff;'; ...
                '  font-size: 12px;'; ...
                '  font-weight: 700;'; ...
                '  line-height: 1.35;'; ...
                '  text-align: left;'; ...
                '  vertical-align: bottom;'; ...
                '  white-space: nowrap;'; ...
                '}'; ...
                'table.openmebius-report-table th:last-child {'; ...
                '  border-right: 0;'; ...
                '}'; ...
                'table.openmebius-report-table td {'; ...
                '  max-width: 520px;'; ...
                '  padding: 9px 12px;'; ...
                '  border: 0;'; ...
                '  border-right: 1px solid #e3e8ec;'; ...
                '  border-bottom: 1px solid #e3e8ec;'; ...
                '  background: var(--om-surface);'; ...
                '  color: var(--om-text);'; ...
                '  text-align: left;'; ...
                '  vertical-align: top;'; ...
                '  overflow-wrap: anywhere;'; ...
                '  word-break: normal;'; ...
                '}'; ...
                'table.openmebius-report-table tbody tr:nth-child(even) td {'; ...
                '  background: var(--om-row-alt);'; ...
                '}'; ...
                'table.openmebius-report-table tbody tr:hover td {'; ...
                '  background: var(--om-accent-soft);'; ...
                '}'; ...
                'table.openmebius-report-table tbody tr:last-child td {'; ...
                '  border-bottom: 0;'; ...
                '}'; ...
                'table.openmebius-report-table td:last-child {'; ...
                '  border-right: 0;'; ...
                '}'; ...
                'table.openmebius-report-table td:first-child {'; ...
                '  font-weight: 600;'; ...
                '}'; ...
                'table.openmebius-report-table p {'; ...
                '  margin: 0;'; ...
                '}'; ...
                'p.openmebius-report-note {'; ...
                '  margin: 12px 0 28px;'; ...
                '  padding: 12px 14px;'; ...
                '  border: 1px solid #b8d8d2;'; ...
                '  border-left: 4px solid var(--om-accent);'; ...
                '  border-radius: 4px;'; ...
                '  background: #f0f8f6;'; ...
                '  color: #36514d;'; ...
                '  font-size: 13px;'; ...
                '}'; ...
                '@media (max-width: 720px) {'; ...
                '  body {'; ...
                '    padding: 24px 18px 64px;'; ...
                '  }'; ...
                '  p.TitlePageTitle {'; ...
                '    margin-top: 24px;'; ...
                '    padding-top: 28px;'; ...
                '    font-size: 28px;'; ...
                '  }'; ...
                '  h1.SectionTitle1 {'; ...
                '    margin-top: 52px;'; ...
                '    font-size: 23px;'; ...
                '  }'; ...
                '  h2.SectionTitle2 {'; ...
                '    font-size: 18px;'; ...
                '  }'; ...
                '  table.openmebius-report-table {'; ...
                '    font-size: 12px;'; ...
                '  }'; ...
                '}'; ...
                '@media print {'; ...
                '  html, body {'; ...
                '    background: #ffffff;'; ...
                '  }'; ...
                '  body {'; ...
                '    max-width: none;'; ...
                '    padding: 0;'; ...
                '    box-shadow: none;'; ...
                '    font-size: 10pt;'; ...
                '  }'; ...
                '  h1.SectionTitle1 {'; ...
                '    break-before: page;'; ...
                '  }'; ...
                '  table.openmebius-report-table {'; ...
                '    display: table;'; ...
                '    width: 100%;'; ...
                '    max-width: none;'; ...
                '    overflow: visible;'; ...
                '    font-size: 8pt;'; ...
                '  }'; ...
                '  table.openmebius-report-table th {'; ...
                '    background: #e7ebee;'; ...
                '    color: #1f2933;'; ...
                '  }'; ...
                '}'; ...
                '</style>'};

            markup = strjoin(lines, newline);

        end % headMarkup

    end % methods (Static)

end % classdef
